cassandra-schema.cql, changelog.d/2-features/atomic-commits, services/galley/galley.cabal, services/galley/schema/src/Main.hs, services/galley/schema/src/V68_MLSCommitLock.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/App.hs, services/galley/src/Galley/Cassandra/Conversation.hs, services/galley/src/Galley/Cassandra/Conversation/MLS.hs, services/galley/src/Galley/Cassandra/Queries.hs, services/galley/src/Galley/Data/Types.hs, services/galley/src/Galley/Effects/ConversationStore.hs, services/galley/test/integration/API/MLS.hs, services/galley/test/integration/API/MLS/Util.hs
https://wearezeta.atlassian.net/browse/FS-437
=> Prevent race conditions in concurrent MLS commit requests

docs/src/how-to/single-sign-on/trouble-shooting.rst
=> Added preferred language field to mapping scheme.

libs/schema-profunctor/README.md
Added a couple of interesting use-cases that arose when working on #2526.
=> Added more examples to Schema Profuctor docs.

changelog.d/3-bug-fixes/lets-encrypt-default, charts/nginx-ingress-services/values.yaml
In nginx-ingress-services chart, when enabling useCertManager, now correctly creates the required issuer by default.
See also Line 1 in https://github.com/wireapp/wire-server/blob/develop/charts/nginx-ingress-services/templates/issuer.yaml for the name of the variable checked, this didn't match the defaults inside values.yaml.
=> correctly set default nginx-ingress-services-issuer-creation variable

docs/src/how-to/administrate/backup-disaster-recovery.md
Instructions on backing up Wire, and recovering from a Backup.
=> Backup and disaster recovery instructions

changelog.d/5-internal/galley-logging, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/App.hs, services/galley/src/Galley/Effects.hs, services/galley/src/Galley/Run.hs
This should fix the excessive logging issue reported by @jschaul.
=> Only log IO exceptions, not polysemy errors

build/ubuntu/Dockerfile.deps, changelog.d/5-internal/remove-crypto-cli
The old crypto-cli tool has been replaced by mls-test-cli.
=> Remove old crypto-cli tool from the ubuntu image

changelog.d/1-api-changes/store-put-connection, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
This endpoint shouldn't have been deleted, because it's not actually possible to modify a connection using the POST endpoint.
=> Restore PUT /connections endpoint

cabal.project, changelog.d/5-internal/bump-saml2-lib, services/galley/galley.cabal, services/galley/package.yaml, services/spar/package.yaml, services/spar/spar.cabal, services/spar/src/Spar/API.hs, services/spar/src/Spar/App.hs, services/spar/src/Spar/Scim/User.hs, services/spar/src/Spar/Sem/SAML2.hs, services/spar/src/Spar/Sem/SAML2/Library.hs, services/spar/test-integration/Test/Spar/AppSpec.hs, stack.yaml, stack.yaml.lock
https://wearezeta.atlassian.net/browse/SQSERVICES-1630
=> Bump saml2-web-sso.

cabal.project, changelog.d/5-internal/bump-saml2-lib, libs/wire-api/src/Wire/API/Routes/Public/Spar.hs, services/spar/src/Spar/Sem/SamlProtocolSettings/Servant.hs, stack.yaml, stack.yaml.lock
This is a trivial refactoring, moving a generic instance into the library and pushing some constraints down from classes to values.
=> Bump saml2-web-sso. (again)

changelog.d/5-internal/checked-cluser-connect-redis, services/gundeck/gundeck.cabal, services/gundeck/src/Gundeck/Env.hs, services/gundeck/src/Gundeck/Redis.hs, services/gundeck/src/Gundeck/Redis/HedisExtensions.hs
https://wearezeta.atlassian.net/browse/BE-571
=> use checkedConnectCluster to Redis in Gundeck

changelog.d/0-release-notes/coturn-secrets, changelog.d/2-features/coturn-secrets, charts/coturn/templates/configmap-coturn-conf-template.yaml, charts/coturn/templates/secret.yaml, charts/coturn/templates/statefulset.yaml
This change updates the coturn Helm chart to add support for passing multiple authentication secrets to coturn. This makes it possible to operate a multi-tenant TURN service without needing to share secrets between consumers.
coturn already supports multiple auth secrets, so this change just adds the necessary configuration machinery to the Helm chart.
=> coturn multi-tenancy support

docs/src/how-to/install/configuration-options.rst
=> Fs 698/classified domains

changelog.d/5-internal/ci-integration-test-timeout, hack/bin/integration-test.sh
Possibly help with some CI failures we have been seeing of the type
```
Error: unable to get pod logs for test-cbwmwl9q8aha-wire-server-cargohold-integration: pods "test-cbwmwl9q8aha-wire-server-cargohold-integration" not found
```
CI runs `make kube-integration-test` which is an alias for `./hack/bin/integration-tests.sh` which runs this line:
```
helm test --logs -n "${NAMESPACE}" "${NAMESPACE}-${CHART}" --timeout 600s
```
`helm test --logs` will run all tests as defined under `./charts/<chart-e.g.brig>/templates/tests/*`, then post all logs. My hunch is that tests did not have enough time, so there's actually a timeout; but the error doesn't say timeout, but "can't find this pod I'd expect to have started"
By looking at these timings, we can see the last log entry from being done …
=> give integration tests more time to run

changelog.d/3-bug-fixes/charts-minor-fixes, charts/brig/values.yaml, charts/cannon/templates/conf/_nginx.conf.tpl, charts/cannon/values.yaml, charts/galley/templates/configmap.yaml, charts/galley/values.yaml, charts/gundeck/templates/configmap.yaml, charts/nginz/templates/conf/_nginx.conf.tpl, charts/nginz/values.yaml, hack/helm_vars/wire-server/values.yaml.gotmpl
=> Minor fixes in helm charts

changelog.d/5-internal/proposal-hold-time, services/galley/src/Galley/Cassandra/Proposal.hs
Rohan asked to keep proposal hold time consistent with message hold time, which is 28 days by default. The PR updates the value accordingly.
Tracked by https://wearezeta.atlassian.net/browse/FS-509.
=> [FS-509] 28-day Proposal Hold Time

changelog.d/2-features/cannon-hsts, charts/cannon/templates/conf/_nginx.conf.tpl
Also include subdomains
Resolves https://wearezeta.atlassian.net/browse/SEC-183
=> charts/cannon: Ensure HSTS headers are set for all endpoints

changelog.d/3-bug-fixes/nginz-rate-limit-exemptions, charts/nginz/templates/conf/_nginx.conf.tpl
Previous place we did this was in https://github.com/zinfra/cailleach/pull/726/commits/6f10bf407915a2f07e849007f181a723660eac9f as part of https://github.com/zinfra/cailleach/pull/726
We are in general lacking tests for these issues. Anyone has ideas on how to test this to avoid regressions?
=> do rate limiting exemptions by proxy_protocol_ip

changelog.d/2-features/expired-key-packages, libs/wire-api/wire-api.cabal, nix/pkgs/mls_test_cli/default.nix, services/brig/brig.cabal, services/brig/package.yaml, services/brig/src/Brig/API/MLS/KeyPackages.hs, services/brig/src/Brig/API/MLS/KeyPackages/Validation.hs, services/brig/src/Brig/Data/MLS/KeyPackage.hs, services/brig/test/integration/API/Federation.hs, services/brig/test/integration/API/Internal.hs, services/brig/test/integration/API/MLS.hs, services/brig/test/integration/API/MLS/Util.hs, services/brig/test/integration/Federation/End2end.hs, services/galley/galley.cabal, services/galley/package.yaml, services/galley/src/Galley/Cassandra/Proposal.hs
When looking up an MLS key package for a client, all of its expired key packages are deleted first from the database. This affects the claim endpoint and the key-package count endpoint (in the sense of filtering out expired key packages).
My first attempt was to use Cassandra's `using ttl` clause, but that failed because a maximum value of 20 years is supported for  expiring records in Cassandra, yet key packages can last longer than that.
Tracked by https://wearezeta.atlassian.net/browse/FS-794.
TODO:
=> [FS-794] MLS: Delete Expired Key Packages

changelog.d/1-api-changes/deprecated-member-removal, libs/wire-api/src/Wire/API/Routes/Public/Galley.hs, services/galley/test/integration/API.hs, services/galley/test/integration/API/MLS.hs, services/galley/test/integration/API/Roles.hs, services/galley/test/integration/API/Teams.hs, services/galley/test/integration/API/Teams/LegalHold.hs, services/galley/test/integration/API/Util.hs
The PR drops the deprecated `DELETE /conversations/:cnv/members/:usr` endpoint from version 2 of the client API. It also updates the integration tests in Galley not to use the deprecated and from version 2 removed endpoint `POST /conversations/:cnv/members` for adding members.
=> Drop a Deprecated Conversation Member Removal Endpoint

docs/src/how-to/install/includes/helm_dns-ingress-troubleshooting.inc.rst, docs/src/how-to/install/troubleshooting.rst, docs/src/understand/helm.rst
Helm charts live in wire-server codebase, so these links were broken.
=> docs: update links to helm chart values

build/ubuntu/Dockerfile.prebuilder
From CI logs:
```
#10 155.2 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
#10 155.2 @ WARNING: Installation might not be completed as desired! @
#10 155.2 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
#10 155.2 The command "cabal install [TARGETS]" doesn't expose libraries.
#10 155.2 * You might have wanted to add them as dependencies to your package. In this
#10 155.2 case add "cabal-plan" to the build-depends field(s) of your package's .cabal
#10 155.2 file.
#10 155.2 * You might have wanted to add them to a GHC environment. In this case use
#10 155.2 "cabal install --lib cabal-plan". The "--lib" flag is provisional: see
#10 155.2 https://github.com/haskell/cabal/issues/6481 for more information.
```
This showed up when the prebuilder got built again in the …
=> build/ubuntu/Dockerfile.prebuiler: Enable exe flag when installing cabal-plan

cassandra-schema.cql, changelog.d/2-features/pr-2565, libs/wire-api/src/Wire/API/Routes/Public/Spar.hs, libs/wire-api/src/Wire/API/User/IdentityProvider.hs, services/spar/schema/src/Main.hs, services/spar/schema/src/V16.hs, services/spar/spar.cabal, services/spar/src/Spar/API.hs, services/spar/src/Spar/Data.hs, services/spar/src/Spar/Sem/IdPConfigStore.hs, services/spar/src/Spar/Sem/IdPConfigStore/Cassandra.hs, services/spar/src/Spar/Sem/IdPConfigStore/Mem.hs, services/spar/test-integration/Test/Spar/APISpec.hs, services/spar/test-integration/Test/Spar/DataSpec.hs, services/spar/test-integration/Util/Core.hs, services/spar/test/Arbitrary.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1533
`handle` is an optional query parameter on the POST and PUT requests. Can't easily add it to the body because the content-type is XML. Refactoring this will be a breaking change for the clients.
When a handle is not given, we will generate one like "IdP 1..n" and take the first one that is not used already.
If an IdP already exists, the handle that is returned is generated from the uuid of the IdP, taking the first 6 characters, e.g.
```
IdP 63621f
```
Since IdP handles are only alias, the uniqueness requirements for the handle can be a bit softer. Also, team admins can simply change the handles in case of a clash.
There was a discussion in the BE channel about a potential data migration. But the current implementation doesn’t need …
=> Sqservices 1533 be give saml id ps human readable names in tm

changelog.d/2-features/tls-certs-reduce-default-list, charts/backoffice/templates/configmap.yaml, charts/cannon/templates/conf/_nginx.conf.tpl, charts/cannon/values.yaml, charts/nginx-ingress-controller/values.yaml, docs/src/how-to/install/tls.rst, services/federator/src/Federator/Remote.hs
As discussed with @mythsunwind and @comawill.
Removes these ciphers from ingress traffic getting to nginz; nginz-cannon; and if appliccable backoffice (which was using a larger list of ciphers). Also removes these ciphers from federation exchanges.
Also removes `TLS_CHACHA20_POLY1305_SHA256` when TLS 1.3 is active.
=> Remove AES128 TLS ciphers for TLS 1.2 by default

Makefile, changelog.d/5-internal/cabal-fmt, hack/bin/cabal-fmt.sh, nix/default.nix
This PR adds `cabal-fmt` to the development environment as well as a Makefile target:
```
make cabal-fmt package=wire-api
```
which will reformat the corresponding `.cabal` file in-place. This PR also adds formatting to `make c` target.
If we add suitable stanzas like this (see [blog post](http://oleg.fi/gists/posts/2019-08-11-cabal-fmt.html#extra-expand-exposed-modules-and-other-modules))
```
-- cabal-fmt: expand src
```
then `cabal-fmt` will auto-fill modules like hpack does.
We can use this after we drop hpack in https://github.com/wireapp/wire-server/pull/2596
=> Add cabal-fmt

changelog.d/5-internal/update-key-package-ref, libs/wire-api/src/Wire/API/MLS/Commit.hs, libs/wire-api/src/Wire/API/MLS/KeyPackage.hs, libs/wire-api/src/Wire/API/Routes/Internal/Brig.hs, services/brig/src/Brig/API/Internal.hs, services/brig/src/Brig/Data/MLS/KeyPackage.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/Effects/BrigAccess.hs, services/galley/src/Galley/Intra/Client.hs, services/galley/src/Galley/Intra/Effects.hs
https://wearezeta.atlassian.net/browse/FS-878
The logic has been manually tested. Automated tests will be added/integrated by FS-797.
=> update clients' key package refs upon committing

changelog.d/5-internal/2609-tweak-stuff, hack/bin/cabal-fmt.sh, nix/default.nix
=> Tweak nix env, cabal-fmt

changelog.d/5-internal/allow-patch-method-for-feature-setting, libs/wire-api/src/Wire/API/MLS/CipherSuite.hs, services/galley/src/Galley/API/Internal.hs, services/galley/test/integration/API/Teams/Feature.hs, services/galley/test/integration/API/Util/TeamFeature.hs
This reflects a prior behavior that is used by Ibis. (They had issues because some features couldn't be `PATCH`ed anymore.) Additionally, it's more consistent when all setters can be called with PUT and PATCH.
=> Allow features to be set with HTTP method PATCH (SQPIT-1142)

build/ubuntu/Dockerfile.deps
=> Use rust image to build mls-test-cli

changelog.d/2-features/pr-2605, libs/brig-types/src/Brig/Types/Intra.hs, libs/wire-api/src/Wire/API/Routes/Internal/Brig.hs, libs/wire-api/src/Wire/API/User.hs, services/brig/src/Brig/API/Internal.hs, services/spar/spar.cabal, services/spar/src/Spar/App.hs, services/spar/src/Spar/Intra/Brig.hs, services/spar/src/Spar/Scim/User.hs, services/spar/src/Spar/Sem/BrigAccess.hs, services/spar/src/Spar/Sem/BrigAccess/Http.hs, services/spar/test-integration/Test/Spar/Scim/UserSpec.hs, services/spar/test-integration/Util/Scim.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1388
The `preferredLanguage` field from SCIM now maps to the user locale in BRIG and will be set and updated on post SCIM user and on update SCIM user using SAML.
When the `preferredLangauge` is not set in SCIM it will fall back to the `defaultUserLocale` defined in brig. This also works for updates.
=> SQSERVICES-1388-email-localization-when-provisioning-users-with-scim-2

libs/metrics-core/src/Data/Metrics.hs, libs/wire-api/src/Wire/API/Asset.hs, libs/wire-api/src/Wire/API/Error.hs, libs/wire-api/src/Wire/API/Routes/MultiVerb.hs, libs/wire-api/src/Wire/API/Routes/Named.hs, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley.hs, libs/wire-api/src/Wire/API/Routes/Public/Util.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Manual/ConversationCoverView.hs, nix/default.nix, nix/overlay-docs.nix, nix/pkgs/mls_test_cli/default.nix, nix/sources.json, nix/sources.nix, services/brig/src/Brig/Data/Activation.hs, services/brig/src/Brig/Data/Client.hs, services/brig/src/Brig/User/Auth/Cookie.hs, services/brig/test/integration/API/Team.hs, services/brig/test/integration/API/User/Account.hs, services/gundeck/test/unit/DelayQueue.hs, tools/api-simulations/smoketest/src/Network/Wire/Simulations/SmokeTest.hs
Updated mls-test-cli dependency, and the pin nixpkgs itself. Also removed the nixpkgs pin for building the docs.
This required some fiddling with rust dependencies (in particular the `ring` crate), since it seems to require the presence of a `.git` directory in order to build successfully. Hopefully this kludge can be removed eventually once the rust libraries mature.
=> Bump mls-test-cli

build/ubuntu/Dockerfile.builder, build/ubuntu/Dockerfile.deps, changelog.d/5-internal/ml-test-cli-builder-image
Motivation: Unit tests are run in the builder image. We'd like to use the mls-test-cli in unit tests.
This PR can be tested locally by running
```
docker build --build-arg prebuilder=quay.io/wire/ubuntu20-prebuilder:develop -f ./Dockerfile.builder .
```
=> Add mls-test-cli to builder image

build/ubuntu/Dockerfile.deps, changelog.d/5-internal/mls-test-cli-deps-image
Followup to https://github.com/wireapp/wire-server/pull/2626 (which removed `mls-test-cli` from the deps image). `mls-test-cli` is also needed in the `deps` image for integration tests.
=> Add mls-test-cli to deps image

changelog.d/5-internal/hls-hlint-plugin-workaround, nix/sources.json
This PR applies this suggestion https://github.com/NixOS/nixpkgs/issues/168064#issuecomment-1146691884
in a wire's nixpkgs fork. Since the problem has been fixed in https://github.com/haskell/haskell-language-server/pull/2854 we can switch to nixos/nixpkgs once a new HLS version is released an available in nixpkgs.
=> Fix broken hls-hlint-plugin in nix env

changelog.d/5-internal/apply-cabal-fmt, libs/dns-util/dns-util.cabal, libs/extended/extended.cabal, libs/hscim/hscim.cabal, libs/metrics-wai/metrics-wai.cabal, libs/sodium-crypto-sign/sodium-crypto-sign.cabal, libs/types-common-journal/types-common-journal.cabal, libs/wire-api-federation/wire-api-federation.cabal, libs/wire-message-proto-lens/wire-message-proto-lens.cabal, services/spar/spar.cabal
=> apply cabal-fmt

build/ubuntu/Dockerfile.builder, build/ubuntu/Dockerfile.deps, changelog.d/5-internal/mls-test-cli-lock-file
This PR builds `mls-test-cli` with `cargo build` instead of `cargo install`, because `cargo install` without the `--locked` file ignores `Cargo.lock` (which we don't want).
=> mls-test-cli - use Cargo.lock

changelog.d/5-internal/typos-etc, docs/legacy/reference/user/registration.md, libs/galley-types/src/Galley/Types/Teams.hs, libs/wire-api/src/Wire/API/Team/Feature.hs, libs/wire-api/src/Wire/API/Team/SearchVisibility.hs, services/galley/src/Galley/API/Teams/Features.hs
A few trivialities that happened in the context of exploring https://wearezeta.atlassian.net/browse/SQSERVICES-1687  Hopefully uncontroversial?
=> Typos etc.

changelog.d/5-internal/pr-2633, libs/wire-api/src/Wire/API/User/Auth.hs, libs/wire-api/src/Wire/API/User/Auth2.hs, libs/wire-api/test/unit/Main.hs, libs/wire-api/test/unit/Test/Wire/API/User/Auth.hs, libs/wire-api/wire-api.cabal
=> SQSERVICES-1645-backend-servantify-brig-auth-api

charts/galley/templates/configmap.yaml, charts/galley/templates/mls-secret.yaml
This is a followup to #2602, fixing an issue with the helm templates. This PR makes it possible to omit the `mlsPrivateKeys` value.
=> Make mlsPrivateKeys value optional

Makefile, changelog.d/5-internal/tweak-makefile, docs/developer/building.md
- simplify and consolidate make rule names
- drop hint in case of compiler error
=> We only need one rule for `make clean`.

.github/pull_request_template.md, changelog.d/5-internal/internal-PR-template-processes, docs/legacy/developer/adding-api-endpoints.md, docs/legacy/developer/adding-config-options.md
Old documentation was at
https://github.com/zinfra/backend-wiki/wiki/Checklists and was partially
outdated due to hegemony not being a thing anymore. Updated docs.
=> port checklist documentation over to docs, and adjust PR template

charts/coturn/Chart.yaml, charts/coturn/templates/configmap-coturn-conf-template.yaml
This change bumps the coturn container image in the Helm chart, and updates the configuration file for changes in option processing. No functional changes.
=> Update coturn container image.

charts/galley/values.yaml
This avoids some templating errors when deploying the chart without any secrets
as the templating code can assume that `.Values.secrets` is a map and not
`null`.
=> charts/galley: Set secrets to empty object

changelog.d/5-internal/brig-redundant-constraints, services/brig/src/Brig/API/Client.hs, services/brig/src/Brig/API/Error.hs, services/brig/src/Brig/API/Public.hs, services/brig/src/Brig/API/User.hs, services/brig/src/Brig/AWS.hs, services/brig/src/Brig/App.hs, services/brig/src/Brig/Data/Activation.hs, services/brig/src/Brig/Data/Client.hs, services/brig/src/Brig/Data/User.hs, services/brig/src/Brig/Federation/Client.hs, services/brig/src/Brig/IO/Intra.hs, services/brig/src/Brig/Index/Eval.hs, services/brig/src/Brig/Index/Migrations.hs, services/brig/src/Brig/InternalEvent/Process.hs, services/brig/src/Brig/Provider/API.hs, services/brig/src/Brig/Team/DB.hs, services/brig/src/Brig/User/API/Auth.hs, services/brig/src/Brig/User/Auth.hs, services/brig/src/Brig/User/Auth/Cookie.hs, services/brig/src/Brig/User/Search/Index.hs
While doing some polysemy work on brig, I noticed a bunch of redundant constraints. These make it harder to determine which code paths actually require cleaning up before polysemization, so I decided to do a quick cleanup here.
There are also some unrelated changes that `make format` has been yelling at me about for several PRs now.
=> Brig: Remove redundant constraints

changelog.d/2-features/mls-fwd-all-default-proposals, libs/wire-api/src/Wire/API/MLS/Extension.hs, libs/wire-api/src/Wire/API/MLS/Message.hs, libs/wire-api/src/Wire/API/MLS/Proposal.hs, libs/wire-api/src/Wire/API/MLS/Serialisation.hs, libs/wire-api/test/unit/Test/Wire/API/Roundtrip/MLS.hs, services/galley/galley.cabal, services/galley/src/Galley/API/MLS/Message.hs, services/galley/test/integration/API/MLS.hs, services/galley/test/integration/API/MLS/Util.hs
The PR adapts the Wire server such that it simply forwards all MLS default proposal types, including those that it currently does not support.
Tracked by https://wearezeta.atlassian.net/browse/FS-721.
=> [FS-721] Forward All Default Proposals

changelog.d/5-internal/FS-797, libs/polysemy-wire-zoo/polysemy-wire-zoo.cabal, libs/wire-api/src/Wire/API/Error/Galley.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley.hs, services/brig/src/Brig/Data/MLS/KeyPackage.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/Cassandra/Conversation/Members.hs, services/galley/src/Galley/Effects/MemberStore.hs, services/galley/test/integration/API/MLS.hs
https://wearezeta.atlassian.net/browse/FS-797
Removed the test `"user tries to remove themselves from conversation"`. In the test, the group creator was creating a _remove_ commit which was then send by Bob to the backend. It is not working anymore, since now it is made sure by the backend that Bob creates all his commits himself. Switching to Bob creating the _remove_ commit for his clients won't work either, since OpenMLS would forbid to create a commit in which the user even removes one of his/her own clients. Thus, the test was beyond repairable. However, there might be the option to craft a _remove_ commit for Bob without OpenMLS later on when crafting MLS messages is available.
=> Add additional checks on incoming MLS messages

changelog.d/0-release-notes/get-mls-clients, changelog.d/3-bug-fixes/improve-client-check, libs/wire-api-federation/src/Wire/API/Federation/API/Brig.hs, libs/wire-api/src/Wire/API/Routes/Internal/Brig.hs, libs/wire-api/src/Wire/API/User/Client.hs, services/brig/src/Brig/API/Federation.hs, services/brig/src/Brig/API/Internal.hs, services/brig/test/integration/API/Internal.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/Effects/BrigAccess.hs, services/galley/src/Galley/Intra/Client.hs, services/galley/test/integration/API/MLS.hs, services/galley/test/integration/API/MLS/Util.hs
This PR changes the way MLS-capable clients are defined to exclude those that have a public key set, but no key packages. Furthermore, adding a client to an MLS conversation that already includes the user results in the client check being skipped.
Tracked by https://wearezeta.atlassian.net/browse/FS-853.
=> Improve MLS client checks

cassandra-schema.cql, changelog.d/5-internal/fix-nonce-table, libs/types-common/src/Data/Nonce.hs, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs, services/brig/brig.cabal, services/brig/schema/src/Main.hs, services/brig/schema/src/V73_ReplaceNonceTable.hs, services/brig/src/Brig/API/Public.hs, services/brig/src/Brig/App.hs, services/brig/src/Brig/Data/Nonce.hs, services/brig/src/Brig/Options.hs, services/brig/test/integration/API/User/Client.hs, services/brig/test/integration/API/User/Util.hs
https://wearezeta.atlassian.net/browse/FS-736 (the part where we need to change the way we store nonces)
=> Make nonces lookuppable by client ids

nix/pkgs/mls_test_cli/default.nix
Upgrade mls-test-cli tool to version containing the `consume` command.
=> Update mls-test-cli to 0.4.0

changelog.d/5-internal/update_elasticsearch_ephemeral_version, charts/elasticsearch-ephemeral/values.yaml
wire-server-deploy delivered a different version as used here for integration tests.
=> Run integration tests with delivered Elastic Search version

.github/pull_request_template.md, docs/src/developer/developer/pr-guidelines.md
This PR simplifies the PR checklist and moves most of the content into a dedicated document containing guidelines to be followed by PR authors.
=> Create PR guidelines and simplify checklist

changelog.d/4-docs/tweak-docs-2, docs/src/developer/index.rst, docs/src/index.rst
https://wearezeta.atlassian.net/browse/BE-514
=> Make target audience explicit on docs.wire.com.

cassandra-schema.cql, changelog.d/2-features/mls-remove-proposals-on-user-deletion, docs/src/developer/reference/cassandra-schema.cql, libs/galley-types/src/Galley/Types/Conversations/Members.hs, libs/wire-api/src/Wire/API/Error/Galley.hs, libs/wire-api/src/Wire/API/MLS/Credential.hs, libs/wire-api/src/Wire/API/MLS/KeyPackage.hs, libs/wire-api/src/Wire/API/MLS/Message.hs, libs/wire-api/src/Wire/API/MLS/Serialisation.hs, libs/wire-api/test/unit/Test/Wire/API/MLS.hs, services/brig/src/Brig/Data/Instances.hs, services/galley/galley.cabal, services/galley/schema/src/Main.hs, services/galley/schema/src/V71_MemberClientKeypackage.hs, services/galley/src/Galley/API/Create.hs, services/galley/src/Galley/API/Error.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/MLS/KeyPackage.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/Cassandra/Conversation/Members.hs, services/galley/src/Galley/Cassandra/Queries.hs, services/galley/src/Galley/Data/Conversation/Types.hs, services/galley/src/Galley/Effects/MemberStore.hs, services/galley/test/integration/API/MLS.hs, services/galley/test/integration/API/MLS/Util.hs, services/galley/test/integration/API/Util.hs
Send external remove proposals when users are deleted.
Tracked by https://wearezeta.atlassian.net/browse/FS-906.
=> MLS: Backend sends remove proposal upon user deletion

cassandra-schema.cql, changelog.d/5-internal/gundeck-notifications-cassandra-compaction-strategy, services/gundeck/gundeck.cabal, services/gundeck/schema/src/V9.hs
In Gundeck's 'notifications' cassandra table, switch to [TWCS](https://cassandra.apache.org/doc/latest/cassandra/operating/compaction/twcs.html) compaction strategy, which should be more efficient for this workload, and possibly bring performance benefits to latencies.
It may be beneficial to run a manual compaction before rolling out this
change (but things should also work without this manual operation).
In case you have time, run the following before deploying this update:
```
nodetool compact gundeck notifications
```
=> gundeck/cassandra: TWCS for 'notifications' table

changelog.d/4-docs/FS-672, libs/schema-profunctor/src/Data/Schema.hs, libs/types-common/src/Data/Json/Util.hs, libs/wire-api/src/Wire/API/Swagger.hs, libs/wire-api/src/Wire/API/User/Client.hs
[FS-672](https://wearezeta.atlassian.net/browse/FS-672)
=> [FS-672] Improve swagger docs for Client fields.

changelog.d/5-internal/FS-921, libs/wire-api/src/Wire/API/MLS/KeyPackage.hs, libs/wire-api/src/Wire/API/Routes/Internal/Brig.hs, services/brig/src/Brig/API/Internal.hs, services/brig/src/Brig/API/MLS/KeyPackages/Validation.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/Effects/BrigAccess.hs, services/galley/src/Galley/Intra/Client.hs, services/galley/src/Galley/Intra/Effects.hs, services/galley/test/integration/API/MLS.hs, services/galley/test/integration/API/MLS/Util.hs
https://wearezeta.atlassian.net/browse/FS-921
=> Fix processing of external add proposals 

changelog.d/1-api-changes/add-mls-public-keys-to-nginz, charts/nginz/values.yaml, deploy/services-demo/conf/nginz/nginx.conf
=> Add /mls/public-keys to nginz

changelog.d/0-release-notes/helm-chart-default-resources, charts/backoffice/values.yaml, charts/brig/values.yaml, charts/cannon/values.yaml, charts/cargohold/values.yaml, charts/galley/values.yaml, charts/gundeck/values.yaml, charts/nginz/values.yaml, charts/proxy/values.yaml, charts/spar/values.yaml
Related to https://wearezeta.atlassian.net/browse/SQPIT-1347
* Remove CPU limits to avoid CPU throttling
* adjust request CPU and memory based on observed values
Overall this decreases the amount of CPU/memory that the wire-server chart needs to install/schedule pods.
=> wire-server helm chart: Adjust default CPU/Memory

docs/src/developer/reference/team/legalhold.md
=> Update documentation for legalhold whitlisted implicit consent

changelog.d/5-internal/mls-test-cli-0.5, nix/pkgs/mls_test_cli/default.nix
Update mls-test-cli to version 0.5.
=> Update to mls-test-cli 0.5

build/ubuntu/Dockerfile.builder, build/ubuntu/Dockerfile.deps, changelog.d/5-internal/pr-2686
=> [FS-736] Add rusty-jwt-tools dependency to docker deps and builder

Makefile, tools/hlint.sh
Sometimes we create smaller commits during the course of work, and don't remember or take the time to wait for the linter between those steps. Sometimes it's useful / helpful to be able to run hlint over all haskell files touched by a PR as a last ste, or as a CI step.
=> Added hlint pr check makefile cmd.

changelog.d/2-features/mls-remote-proposals-on-client-deletion, libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs, services/galley/galley.cabal, services/galley/src/Galley/API/Clients.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/MLS/Removal.hs, services/galley/test/integration/API/MLS.hs
=> Deleting clients creates MLS remove proposals

changelog.d/2-features/non-admin-commits, services/galley/src/Galley/API/MLS/Message.hs, services/galley/test/integration/API/MLS.hs
- Allow non-admins to commit add proposals
- Test non-admin commit for client deletion
=> Allow add proposal commits by non-admins

changelog.d/1-api-changes/validate-remotely-claimed-key-packages, libs/wire-api/src/Wire/API/Error/Brig.hs, libs/wire-api/src/Wire/API/MLS/Credential.hs, services/brig/src/Brig/API/Error.hs, services/brig/src/Brig/API/MLS/KeyPackages.hs, services/brig/src/Brig/API/MLS/KeyPackages/Validation.hs, services/brig/src/Brig/Data/Client.hs, services/brig/test/integration/API/MLS.hs, services/brig/test/integration/API/MLS/Util.hs
The PR validates remotely claimed key packages. Such packages go through the same kind of validation as locally claimed packages, though for local ones the validation happens upon uploading to the local backend.
Tracked by https://wearezeta.atlassian.net/browse/FS-937.
**Note**: An old Git branch to ignore is similarly named: [`fs-937/remote-claimed-kps`](https://github.com/wireapp/wire-server/tree/fs-937/remote-claimed-kps).
=> [FS-937] Validate Remotely Claimed Key Packages

tools/hlint.sh
Turns out hlint already provided a way to silence the annoying no hints output.
On top of that, I added a quick early break with a better error message in case of grep failures b/c no files were found.
=> Use hlint with no summary instead of grep.

changelog.d/4-docs/update-of-monitoring-wire-server-page, docs/src/how-to/install/monitoring.rst
https://wearezeta.atlassian.net/browse/SER-162
=> SER-162: updated monitoring

changelog.d/5-internal/pr-2699, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs, libs/wire-api/src/Wire/API/Swagger.hs, libs/wire-api/src/Wire/API/User.hs, services/brig/src/Brig/API/Public.hs
=> [SQSERVICES-1643] Servantify brig account API 1 - `POST /delete`

changelog.d/5-internal/pr-2700, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs, libs/wire-api/src/Wire/API/User/Activation.hs, services/brig/src/Brig/API/Public.hs
=> [SQSERVICES-1643] Servantify brig account API 2 - `GET /activate`

changelog.d/5-internal/pr-2701, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs, libs/wire-api/src/Wire/API/Swagger.hs, libs/wire-api/src/Wire/API/User/Activation.hs, services/brig/src/Brig/API/Public.hs
=> [SQSERVICES-1643] Servantify brig account API 3 - `POST /activate`

changelog.d/5-internal/pr-2702, libs/wire-api/src/Wire/API/Error/Brig.hs, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs, libs/wire-api/src/Wire/API/Swagger.hs, libs/wire-api/src/Wire/API/User/Activation.hs, services/brig/src/Brig/API/Public.hs
=> [SQSERVICES-1643] Servantify brig account API 4 - `POST /activate/send`

.hlint.yaml, libs/wire-api/src/Wire/API/MLS/CommitBundle.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/API/MLS/Propagate.hs, tools/hlint.sh
Also applies hlint again to the whole codebase (excluding tests), as we had some drift between finalising hlint and new PRs being merged without being linted / having CI catch those cases.
I also disabled the pipefail from the script, as that would short-circuit the linter on first issue found. Hopefully that doesn't mess with CI.
PS: This will fail CI linters phase until #2715 has been merged.
=> Add new custom hlint rule for runSetting.

changelog.d/5-internal/pr-2704, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs, libs/wire-api/src/Wire/API/Swagger.hs, libs/wire-api/src/Wire/API/User/Password.hs, services/brig/src/Brig/API/Error.hs, services/brig/src/Brig/API/Public.hs
=> [SQSERVICES-1643] Servantify brig account API 6- `POST password-reset/complete`

changelog.d/3-bug-fixes/sqpit-1431, libs/wai-utilities/src/Network/Wai/Utilities/Server.hs, services/brig/brig.cabal, services/brig/src/Brig/Run.hs, services/cannon/src/Cannon/Run.hs, services/cargohold/src/CargoHold/Run.hs, services/galley/src/Galley/Run.hs, services/gundeck/src/Gundeck/Run.hs, services/proxy/src/Proxy/Run.hs, services/spar/src/Spar/Run.hs, tools/stern/src/Stern/API.hs
https://wearezeta.atlassian.net/browse/SQPIT-1431
=> Better signal handling for proxy, stern

services/brig/test/integration/API/Provider.hs, services/brig/test/integration/Util.hs, services/galley/test/integration/API/Teams.hs, services/galley/test/integration/API/Teams/Feature.hs, services/galley/test/integration/TestHelpers.hs
(very small change, hopefully non-controversial.)
=> Note on race condition in integration test.

changelog.d/5-internal/pr-2705, libs/wire-api/src/Wire/API/Error/Brig.hs, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs, libs/wire-api/src/Wire/API/User/Password.hs, services/brig/src/Brig/API/Public.hs
=> [SQSERVICES-1643] Servantify brig account API 7 - `POST /password-reset/:key`

changelog.d/5-internal/pr-2699, changelog.d/5-internal/pr-2700, changelog.d/5-internal/pr-2701, changelog.d/5-internal/pr-2702, changelog.d/5-internal/pr-2703, changelog.d/5-internal/pr-2704, changelog.d/5-internal/pr-2705, changelog.d/5-internal/pr-2707, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs, services/brig/src/Brig/API/Public.hs, services/brig/src/Brig/User/API/Auth.hs, services/brig/test/integration/API/Metrics.hs
=> [SQSERVICES-1643] Servantify brig account API 8 - `POST /onboading/v3`

changelog.d/5-internal/pr-2725, charts/cannon/conf/static/zauth.acl, charts/nginz/static/conf/zauth.acl
This PR updates the ACL files to include api-versioned paths (paths prefixed by `v2/`, etc).
This PR makes use of the new regex syntax in libzauth that was introduced in https://github.com/wireapp/wire-server/pull/2714
=> Update nginz and cannon ACLs to match api-versioned paths

changelog.d/4-docs/pr-2720, docs/src/understand/single-sign-on/main.rst
=> JCT-147: update SCIM documentation how to deactivate user

changelog.d/5-internal/acl-legalhold-tokens, charts/nginz/static/conf/zauth.acl, deploy/services-demo/conf/nginz/zauth_acl.txt, services/brig/test/integration/API/User/Auth.hs
This PR:
- adds `/conversations/<uuid>` to the allowlist for legalhold tokens. It can replace the changes introduced https://github.com/wireapp/wire-server/pull/2682 by using of the new regex syntax for acl files introduced in https://github.com/wireapp/wire-server/pull/2714
- sets acl file for integration tests to the same as the acl file embedded in the nginz chart
=> Allow /conversations/<uuid> paths for legalhold tokens

changelog.d/5-internal/topology-aware-hints, charts/backoffice/templates/service.yaml, charts/brig/templates/service.yaml, charts/cannon/templates/headless-service.yaml, charts/cannon/templates/nginz-service.yaml, charts/cargohold/templates/service.yaml, charts/federator/templates/service.yaml, charts/galley/templates/service.yaml, charts/gundeck/templates/service.yaml, charts/legalhold/templates/service.yaml, charts/nginz/templates/service.yaml, charts/proxy/templates/service.yaml, charts/spar/templates/service.yaml
For wire-server cloud, on kubernetes 1.21+, favour topology-aware routing, which reduces unnecessary inter-availability-zone traffic, reducing latency and AWS costs.
Documentation: https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/ 
See [SQPIT-1439](https://wearezeta.atlassian.net/browse/SQPIT-1439)
=> charts/wire-server: enable topology-aware hints.

deploy/services-demo/conf/nginz/nginx.conf
This fixes a bug in the local testing setup of nginz.
=> Fix: versioned routing for /conversations missing

docs/src/developer/developer/building.md
Added a new section to troubleshooting.
=> Updated building.md docs

changelog.d/2-features/FS-1002, libs/wire-api/src/Wire/API/Conversation/Protocol.hs, services/galley/test/integration/API/MLS.hs
=> Allow deletion of MLS team conversations

changelog.d/3-bug-fixes/2773, services/brig/src/Brig/API/Client.hs, services/brig/src/Brig/InternalEvent/Process.hs, services/brig/src/Brig/InternalEvent/Types.hs, services/brig/test/integration/API/User/Client.hs, services/galley/test/integration/API/Teams/LegalHold.hs
This PR reverts in part changes introduced in https://github.com/wireapp/wire-server/pull/2669 . Concretely it reverts the client deletion endpoints back to synchronous semantics: When the call from `DELETE /clients/{client}` returns then a call to `GET /clients` (or any other endpoint that fetches the client) will no longer list the client.
What is kept asynchronous is the removal of the client in galley and the removal of the client from (federated) MLS conversations it participates in.
=> Remove clients synchronously from brig's DB

changelog.d/4-docs/pr-2736, docs/src/how-to/administrate/backup-disaster-recovery.md, docs/src/how-to/administrate/cassandra.rst, docs/src/understand/single-sign-on/main.rst
=> Documentation updates

Makefile, changelog.d/5-internal/make-repl
This PR adds a little Make target to get into a `ghci` environment.
Usage:
> make repl package=brig
=> Add a repl target to Makefile

changelog.d/5-internal/pr-2738, docs/src/developer/reference/config-options.md, docs/src/how-to/install/index.rst, docs/src/how-to/install/mls.md, services/galley/src/Galley/API/Create.hs, services/galley/src/Galley/API/MLS/Keys.hs, services/galley/src/Galley/API/MLS/Removal.hs
This PR changes the way the backend behaves when removal key for MLS is not configured.
If the key is not configured, then:
- creating MLS conversations is not allowed (was allowed before)
- when a client gets deleted then backend will not send remove proposals to mls groups and log a warning (before the deletion process would fail halfway through)
This PR adds documentation for wire-server for operators on how to configure the removal key.
=> Update error checking for MLS removal key & add operator documenteation

changelog.d/gundeck-integration-test-docs, services/gundeck/test/integration/API.hs
This adds some documentation on what SNS Platform Applications that test expects, and moves a constant closer to where it's being used for readability.
=> gundeck: integration test docs

changelog.d/5-internal/cleanup-scim-tests, services/spar/test/Test/Spar/Scim/UserSpec.hs
This PR is a minor cleanup of some of the tests from #2637, which are delightful examples of writing tests against Polysemy. It tests the same things, but in a slightly more reusable way, notably:
- Factoring the mock brig interpreters into a single, parameterized version
- Adding a little combinator `withActiveUser` for building those parameters
- Introducing a combinator `ignoringState` to dramatically reduce the typing burden
=> Refactor Scim.Scim.UserSpec tests to use composable pieces

changelog.d/3-bug-fixes/pr-2758, services/brig/src/Brig/API.hs, services/brig/src/Brig/API/Client.hs, services/brig/src/Brig/API/Federation.hs, services/brig/src/Brig/API/MLS/KeyPackages.hs, services/brig/src/Brig/API/Public.hs, services/brig/src/Brig/App.hs, services/brig/src/Brig/CanonicalInterpreter.hs, services/brig/src/Brig/IO/Intra.hs, services/brig/src/Brig/Provider/API.hs, services/brig/test/integration/API/User/Client.hs
https://wearezeta.atlassian.net/browse/FS-966
This PR changes the behaviour when clients without prekeys are detected during prekey claiming.
Without this PR: a client without any prekeys is deleted from other services synchronously, but _not_ from brig.
With this PR: a client without any prekeys is deleted
1) synchronously from brig: This leads to the client not be listed anymore. Without this change the client's prekeys are attempted to be fetched over and over again also triggering the deletion attempts over and over again.
2) asynchronously from all other services: This should improve response times when claming prekeys. The removal of clients from the galley service can be particularly slow for MLS clients. with this change it won't block prekey claiming
=> Fix bug: clients without prekeys are not deleted competely

services/brig/src/Brig/API/Client.hs, services/brig/src/Brig/API/Public/Swagger.hs, services/brig/src/Brig/CanonicalInterpreter.hs, services/brig/src/Brig/Provider/API.hs, services/brig/src/Brig/User/API/Handle.hs, services/brig/test/integration/API/User/Client.hs, tools/hlint.sh, tools/rex/Main.hs
Now that we've bumped dev tools versions, hlint is catching more cases.
=> Re-lint the codebase

nix/wire-server.nix
If you use `INTEGRATION_USE_NGINZ=1` then it will attempt to build `nginz`. Currently `nginz` is not cached causing rebuilds, which may take long time.
=> Add nginz to nix develop environment

changelog.d/5-internal/nginz-upgrade, services/nginz/Dockerfile, services/nginz/Makefile
=> nginz: upgrade nginx version

.envrc, changelog.d/0-release-notes/nix-builds, nix/wire-server.nix
Using haskellPacakges.shellFor directly forced us to use nix-shell which exports too many environment variables. These environment variables cause a lot of problems, specially for people not using NixOS.
This change reads buildInputs and nativeBuildInputs for the derivation produced by haskellPacakges.shellFor and adds it to paths of pkgs.buildEnv. To allow cabal to find C dependencies, we also have to export PKG_CONFIG_PATH.
=> nix: Use pkgs.buildEnv for development environment

changelog.d/4-docs/copyright-date, docs/src/conf.py
=> fix copyright date in the docs

changelog.d/5-internal/polysemy-intersperse, libs/polysemy-wire-zoo/polysemy-wire-zoo.cabal, libs/polysemy-wire-zoo/src/Polysemy/Testing.hs, libs/polysemy-wire-zoo/test/Spec.hs, libs/polysemy-wire-zoo/test/Test/IntersperseSpec.hs
This PR implements a new polysemy combinator `intersperse` which allows for injecting logic between every handled action in the effect stack. It also adds a test-suite to `polysemy-wire-zoo`, with a new test showing how to use `intersperse` to poll from an `async` thread. 
The short-term use case for this is to use it to test brig's STOMP client, where we can `intersperse` the listener callback, which otherwise gets in the way of the removing `IO` effort.
=> Polysemy: intersperse combinator

changelog.d/5-internal/bump-nginx-module-vts
https://wearezeta.atlassian.net/browse/SER-218
upstream changelog: https://github.com/vozlt/nginx-module-vts/blob/v0.2.1/CHANGELOG.md
=> bump nginx-module-vts from v0.1.15 to v0.2.1

changelog.d/1-api-changes/rate-limit-asset-dl, charts/nginz/values.yaml
After not using the wire client for some time, it can easily happen that many conversations have many assets that should be downloaded. We may wish to be more lenient on asset download (well, getting signed URLs to download assets) requests. See https://wearezeta.atlassian.net/browse/SQCORE-1372 and https://wearezeta.atlassian.net/browse/SQSERVICES-1763
=> Stop rate-limiting asset-signed-url requests

nix/manual-overrides.nix, nix/overlay.nix, nix/wire-server.nix
https://wearezeta.atlassian.net/browse/SQPIT-1478
=> nix: Pin openssl to 1.1

docs/src/developer/developer/building.md
=> Documentation: add nix cache instructions

changelog.d/2-features/pr-2802, libs/polysemy-wire-zoo/src/Wire/Sem/Paging/Cassandra.hs, libs/wire-api/src/Wire/API/Routes/MultiTablePaging/State.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley.hs, libs/wire-api/src/Wire/API/Team/Member.hs, services/galley/src/Galley/API/Teams.hs, services/galley/src/Galley/App.hs, services/galley/src/Galley/Cassandra/Team.hs, services/galley/src/Galley/Effects.hs, services/galley/test/integration/API/Teams.hs, services/galley/test/integration/API/Util.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1769
This PR only covers the `GET /teams/{tid}/members` endpoint.
=> [SQSERVICES 1769] Allow pagination for team endpoints

changelog.d/5-internal/client-deletion-payload, libs/brig-types/src/Brig/Types/User/Event.hs, services/brig/src/Brig/API/Client.hs, services/brig/src/Brig/IO/Intra.hs, services/brig/src/Brig/InternalEvent/Process.hs, services/brig/src/Brig/InternalEvent/Types.hs, services/galley/test/integration/API/Teams/LegalHold.hs, services/galley/test/integration/API/Teams/LegalHold/DisabledByDefault.hs
This PR:
* reduces the payload of the internal "client.delete" event by using `ClientId` instead of `Client`.
* changes also `Client` to `ClientId` in the `ClientRemoved` constructor of `ClientEvent`. There is no API change, because the push format was only using the `id` of the `Client`.
Tracked in https://wearezeta.atlassian.net/browse/FS-1131
=> Reduce payload size for internal client.delete event

docs/src/security-responses/2022-11-01_openssl.md
=> chore: remove wrong "prior to" in openssl advisory

changelog.d/4-docs/FS-1008-event-notification-schemas, libs/wire-api/src/Wire/API/Event/Team.hs, services/brig/src/Brig/API/Public.hs, services/brig/src/Brig/API/Public/Swagger.hs, services/brig/src/Brig/Run.hs
https://wearezeta.atlassian.net/browse/FS-1008
our swagger2 docs do not contain event types, since they are contained in an untyped json body in a the notification payload.  this PR partially fills this gap by creating the event type schemas under a new public end-point.  it falls short of creating schemas that are correct and complete, but it contains a list of tasks that would get us there [in the code](https://github.com/wireapp/wire-server/blob/9a050941e2a492ff93d25a61f184eade485fdb89/services/brig/src/Brig/API/Public/Swagger.hs#L48-L72).
```
$ curl http://localhost:8082/api/event-notification-schemas | jq . | tee /tmp/schema.json
```
[schema.json.zip](https://github.com/wireapp/wire-server/files/9864165/schema.json.zip)
=> json schemas for event notifications from haskell types

changelog.d/4-docs/sphinx-redirect, docs/src/conf.py, docs/src/how-to/scim/index.rst, docs/src/how-to/single-sign-on/index.rst, docs/src/index.rst, nix/default.nix, nix/overlay-docs.nix, nix/pkgs/python-docs/sphinx_reredirects.nix
This PR introduces a sphinx extension [`sphinx-reredirects`](https://documatt.gitlab.io/sphinx-reredirects/index.html) and configuration to generate simple JavaScript based redirects to new locations of previously inconsistently named files.
=> fixup: add redirects for pages renamed in #2808

changelog.d/5-internal/client-deletion-payload, services/brig/brig.cabal, services/brig/default.nix, services/brig/src/Brig/InternalEvent/Types.hs, services/brig/test/resources/internal-notification.json, services/brig/test/unit/Main.hs, services/brig/test/unit/Test/Brig/InternalNotification.hs
=> Make FromJSON instance of InternalNotification backwards-compatible

changelog.d/3-bug-fixes/removal-client-check, services/galley/src/Galley/API/MLS/Message.hs, services/galley/test/integration/API/MLS.hs
=> Fix client check when removing clients from MLS conversations

changelog.d/5-internal/add-invitation-url-test, changelog.d/5-internal/add-invitation-url-tests, services/brig/brig.cabal, services/brig/default.nix, services/brig/test/integration/API/Team.hs
If team invitation urls are rendered in the response of a team invitation request depends on the settings of galley. Because these cannot be changed during test runs, we first left this test out. This PR adds a test with a mocked instance of galley (such that the configuration change can be simulated).
https://wearezeta.atlassian.net/browse/SQPIT-1368
=> Add test for urls in team invitations (SQPIT-1368)

changelog.d/5-internal/pr-2823, services/galley/test/integration/API/Teams/Feature.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1618
Relaxed the assertion a little bit.
Instead of checking for equality, we check for the upper bound of the TTL, because TTL decreases and if the test application/network/DB is slow, more than a second can pass between writing and reading, which caused the flakiness.
=> [SQSERVICES-1618] Flaky test for TTL feature flag

changelog.d/1-api-changes/mls-self-conversation, libs/wire-api/src/Wire/API/Conversation.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley.hs, services/galley/src/Galley/API/Create.hs, services/galley/src/Galley/API/Public/Servant.hs, services/galley/src/Galley/API/Query.hs, services/galley/src/Galley/API/Util.hs, services/galley/test/integration/API/MLS.hs, services/galley/test/integration/API/MLS/Util.hs, services/galley/test/integration/API/Util.hs
The PR introduces a new endpoint `PUT /conversations/mls-self` for creating and retrieving an MLS self-conversation.
Tracked by https://wearezeta.atlassian.net/browse/FS-925.
=> [FS-925] Add endpoint to create MLS self-conversation

changelog.d/5-internal/nixpkgs-bump, nix/manual-overrides.nix, nix/sources.json, nix/wire-server.nix
https://wearezeta.atlassian.net/browse/SQPIT-1478
=> Bump nixpkgs to latest unstable, unpin openssl

Makefile, changelog.d/5-internal/debugging-tools, nix/wire-server.nix
=> docker images: Add container utilities

CHANGELOG.md
Followup to https://github.com/wireapp/wire-server/pull/2827#issuecomment-1305616398
The changelog entry will be included in the next release. See https://github.com/wireapp/wire-server/pull/2827
=> Remove incorrect changelog: nginx-module-vts 

services/galley/test/integration/API/Teams/Feature.hs
=> Make flaky integration test less flaky

.gitmodules, treefmt.toml
We use nginxModules.vts from nixpkgs now instead, so there's no need to keep the submodule around.
=> services/nginz/third_party/nginx-module-vts: drop submodule

changelog.d/3-bug-fixes/sftd-restund-coturn-hostname-nodename, charts/coturn/templates/statefulset.yaml, charts/restund/templates/statefulset.yaml, charts/sftd/templates/statefulset.yaml
Kubernetes might be installed in a way where the machine hostname is not used as node name. Using the statefulset's spec to determine the node name would allow for such deviation.
=> [charts:sftd,restund,coturn] Fix case when hostname is not node name

changelog.d/5-internal/refactor-mls-message, libs/wire-api/src/Wire/API/Routes/Public.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/MLS.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/MLS/Message.hs
This is an attempt to simplify and streamline the logic of MLS message handling. There is still a lot of complexity there, but hopefully less than before. This PR also introduces optional Client IDs taken from the tokens into the MLS message handlers. Making those IDs mandatory and changing conversation creation logic in the V3 API will happen in a separate PR.
=> Simplify and cleanup MLS message handling

cassandra-schema.cql, changelog.d/5-internal/replay-backend-proposals, libs/wire-api/src/Wire/API/MLS/Proposal.hs, services/galley/galley.cabal, services/galley/schema/src/Main.hs, services/galley/schema/src/V76_ProposalOrigin.hs, services/galley/src/Galley/API/MLS/GroupInfo.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/API/MLS/Removal.hs, services/galley/src/Galley/API/MLS/Util.hs, services/galley/src/Galley/Cassandra/Proposal.hs, services/galley/src/Galley/Effects/ProposalStore.hs, services/galley/test/integration/API/MLS.hs, services/galley/test/integration/API/Util.hs
https://wearezeta.atlassian.net/browse/FS-920
=> Replay external backend proposals after external commits

docs/README.md
=> add note about direnv allow

changelog.d/5-internal/pr-2852, services/galley/src/Galley/API/MLS/Message.hs, services/galley/test/integration/API/MLS.hs, services/galley/test/integration/API/MLS/Util.hs
This PR affects external comits:
- adds requirement of Z-Client
- adds a check that Z-Client matches the client idenity in the keypackage that is added
- adds a check that Z-User matches the client idenity in the keypackage that is added
- removes a duplicated call to `addKeyPackageRef`
=> External commits: add additional checks

services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/Effects/BrigAccess.hs, services/galley/src/Galley/Intra/Client.hs
=> KeyPackage validation: Add detailled error

changelog.d/5-internal/pr-2861, libs/wire-api/src/Wire/API/Event/FeatureConfig.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Generated.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/Event_conversation.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/Event_featureConfig.hs, libs/wire-api/test/golden/testObject_Event_conversation_1.json, libs/wire-api/test/golden/testObject_Event_conversation_10.json, libs/wire-api/test/golden/testObject_Event_conversation_11.json, libs/wire-api/test/golden/testObject_Event_conversation_2.json, libs/wire-api/test/golden/testObject_Event_conversation_3.json, libs/wire-api/test/golden/testObject_Event_conversation_4.json, libs/wire-api/test/golden/testObject_Event_conversation_5.json, libs/wire-api/test/golden/testObject_Event_conversation_6.json, libs/wire-api/test/golden/testObject_Event_conversation_7.json, libs/wire-api/test/golden/testObject_Event_conversation_8.json, libs/wire-api/test/golden/testObject_Event_conversation_9.json, libs/wire-api/test/golden/testObject_Event_featureConfig_1.json, libs/wire-api/test/golden/testObject_Event_featureConfig_10.json, libs/wire-api/test/golden/testObject_Event_featureConfig_2.json, libs/wire-api/test/golden/testObject_Event_featureConfig_3.json, libs/wire-api/test/golden/testObject_Event_featureConfig_4.json, libs/wire-api/test/golden/testObject_Event_featureConfig_5.json, libs/wire-api/test/golden/testObject_Event_featureConfig_6.json, libs/wire-api/test/golden/testObject_Event_featureConfig_7.json, libs/wire-api/test/golden/testObject_Event_featureConfig_8.json, libs/wire-api/test/golden/testObject_Event_featureConfig_9.json, libs/wire-api/wire-api.cabal
=> [FS-1008] Golden tests for event schemas

changelog.d/2-features/smtp-logging, libs/types-common/default.nix, libs/types-common/src/Wire/Arbitrary.hs, libs/types-common/types-common.cabal, nix/haskell-pins.nix, nix/manual-overrides.nix, services/brig/brig.cabal, services/brig/default.nix, services/brig/src/Brig/Email.hs, services/brig/src/Brig/SMTP.hs, services/brig/src/Brig/User/Email.hs, services/brig/test/integration/Main.hs, services/brig/test/integration/SMTP.hs
**Problem** to be solved:
When an SMTP server was misconfigured in the `brig` configuration or was misbehaving itself, `brig` was hanging on startup without any useful logs.
**Changes** in this PR:
- Add tests for sending via SMTP. The used SMTP server is [*postie*](https://hackage.haskell.org/package/postie). Unfortunately, the current version of *postie* wasn't compatible to our GHC version due to outdated dependencies. I've updated *postie*'s dependencies and brought it upstream (https://github.com/alexbiehl/postie/commit/c92702386f760fcaa65cd052dc8114889c001e3f). However, these changes are neither on *Hackage* nor in *nixpkgs*, yet. That's why I had to add a Nix override...
- The entry and exit (with result) are now logged. I've separated the log logic from other concerns.
- In the …
=> bullet proof smtp

.envrc
This PR makes direnv watch all `.nix` files in the repo. If any of those files change (e.g. after a `git pull` that updates the nix env) direnv will automatically reload.
=> direnv: watch all .nix files for changes

.envrc
This PR fixes a problem in direnv setup: `.nix` files in in the `./nix` subdirectory were ignored for the computation of cache-key: `nix-rebuild`. This is wrong because nix files in `./nix` directory define the environment.
=> Direnv: Consider all .nix files (especially the ones in ./nix)

Makefile, nix/wire-server.nix, tools/hlint.sh
This PR fixes some issues of the `./tools/hlint.sh` script
- adds the missing `refactor` binary to nix. Without the `-m inplace` option doesn't work
- adds missing implementation for the `-f all -m inplace` combination
- Removes verbosity for `-f all -m check`. This prevents a wall of text on our CI and makes it easier to read the suggestions of hlint
=> hlint: fix inplace option, less verbosity on ci

Makefile, tools/ormolu.sh
This PR speeds up `make formatf` (not used on CI) by only restricting to files that
- are changed in the branch compared to `origin/develop`
- are changed compared to HEAD
This PR adds `make formatf-all` target that behaves like the the `make formatf` without this PR.
=> Speed up "make formatf"

changelog.d/3-bug-fixes/pr-2870, services/brig/src/Brig/Provider/API.hs, services/brig/test/integration/API/Provider.hs, services/brig/test/integration/API/Team/Util.hs, services/galley/src/Galley/API/Update.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1801
=> [SQSERVICES-1801] Prevent dead bots in database

changelog.d/3-bug-fixes/mls-self-conv-not-listed-below-v3, services/galley/src/Galley/API/MLS/Types.hs, services/galley/src/Galley/API/Public/Conversation.hs, services/galley/src/Galley/API/Query.hs, services/galley/test/integration/API/MLS.hs
Currently the call to `POST /conversation/list-ids` will list the MLS self-conversation in client API v1 and v2 if a v3 client created the conversation. Filter out the conversation in versions below v3.
Tracked by https://wearezeta.atlassian.net/browse/FS-1249.
=> [FS-1249] Do Not List MLS Self-conversation in client API v1 and v2

libs/wire-api/src/Wire/API/Error/Galley.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/MLS.hs, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/API/MLS/Util.hs, services/galley/src/Galley/API/Query.hs, services/galley/src/Galley/API/Util.hs, services/galley/src/Galley/Cassandra/Conversation.hs, services/galley/src/Galley/Effects/ConversationStore.hs, services/galley/test/integration/API/MLS.hs
Removed global team conversation creator, improved tests, improve adding users.
Improves error thrown when creating the self conversation, 500 bad.
=> Improve global team conversation handling and self conversation creation error.

changelog.d/2-features/pr-2851, changelog.d/2-features/pr-2855, libs/hscim/src/Web/Scim/Schema/User.hs, libs/hscim/test/Test/Schema/UserSpec.hs, services/spar/test-integration/Test/Spar/Scim/UserSpec.hs, services/spar/test-integration/Util/Scim.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-253
support for `PATCH`
=> [SQSERVICES-253] Support provisioning role information with scim `PATCH`

services/brig/src/Brig/Effects/SFT.hs, services/federator/test/unit/Test/Federator/ExternalServer.hs, services/galley/src/Galley/API/Query.hs, services/galley/test/integration/API/Teams/LegalHold/DisabledByDefault.hs, services/spar/migrate-data/src/Spar/DataMigration/V2_UserV2.hs, tools/db/repair-handles/src/Work.hs
Some extra copyright headers were probably added by mistake by some scripts at some point. This PR removes them.
=> Remove duplicated copyright headers

changelog.d/3-bug-fixes/sftd-forwards-compat, charts/sftd/templates/secret.yaml, charts/sftd/templates/statefulset.yaml, charts/sftd/values.yaml
SFT has changed how it handles credentials in versions 3.1.10 and later. This PR adds logic to handle the different configuration options in these newer versions. This new logic is not enabled by default, for backwards compatibility with older versions of this chart.
=> Fix SFT Helm chart for new sftd versions

changelog.d/4-docs/pr-2889, docs/src/developer/developer/pr-guidelines.md
=> Update PR guideline docs

changelog.d/3-bug-fixes/list-self-mls-not-configured, services/galley/src/Galley/API/Public/Conversation.hs, services/galley/src/Galley/API/Query.hs, services/galley/test/integration/API/MLS.hs
This fixes a bug where conversations couldn't be listed in an environment not configured for MLS. This was because of automatic MLS self-conversation creation when listing conversations.
Tracked by https://wearezeta.atlassian.net/browse/FS-1271.
=> [FS-1271] Do not throw 500 when listing conversations

changelog.d/2-features/pr-2895, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs, libs/wire-api/src/Wire/API/User/Search.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/SearchResult_20Contact_user.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/SearchResult_20TeamContact_user.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Manual/SearchResultContact.hs, libs/wire-api/test/golden/testObject_SearchResultContact_2.json, libs/wire-api/test/golden/testObject_SearchResult_20Contact_user_2.json, libs/wire-api/test/golden/testObject_SearchResult_20Contact_user_3.json, libs/wire-api/test/golden/testObject_SearchResult_20TeamContact_user_2.json, libs/wire-api/test/golden/testObject_SearchResult_20TeamContact_user_3.json, services/brig/src/Brig/User/API/Search.hs, services/brig/src/Brig/User/Search/SearchIndex.hs, services/brig/src/Brig/User/Search/TeamUserSearch.hs, services/brig/test/integration/API/Search.hs, services/brig/test/integration/API/TeamUserSearch.hs
This is an extension of https://github.com/wireapp/wire-server/pull/2895 and adds the `has_more` field to the search result.
https://wearezeta.atlassian.net/browse/SQSERVICES-1773
=> [SQSERVICES-1773] Allow pagination for team search endpoints - `has_more`

Makefile, tools/ormolu.sh
As it says on the tin 🥤
Using diff-filter to select only added, copied, modified, and renamed files, but not deleted, unmerged, unknown status, or broken files.
Also fixes `make full-clean` trying to delete the wrongly named dist-* folder.
=> Prevent ormolu from trying to format deleted files, fixed wrong name for make full-clean target

libs/wire-api/src/Wire/API/Conversation.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/Conversation.hs, libs/wire-api/test/golden/testObject_NewConv_user_1.json, libs/wire-api/test/golden/testObject_NewConv_user_3.json, services/galley/test/integration/API.hs, services/galley/test/integration/API/Roles.hs, services/galley/test/integration/API/Teams.hs, services/galley/test/integration/API/Util.hs
- Restore unqualified v2 PUT access endpoint
- Fix `access_role` field name in `NewConv`
- Add tests
https://wearezeta.atlassian.net/browse/FS-1281
=> Restore v2 PUT access endpoint and add tests

changelog.d/5-internal/add-aws-sns-token-invalid-log, services/gundeck/src/Gundeck/Aws.hs
To debug notification (token) specific issues, we need to know the exact answer of AWS/SNS.
This happens is on log level `debug`, of course.
[SQCORE-1267](https://wearezeta.atlassian.net/browse/SQCORE-1267)
=> Log AWS SNS invalid token responses (SQCORE-1267)

changelog.d/3-bug-fixes/2896, charts/brig/values.yaml, charts/cannon/values.yaml, charts/cargohold/values.yaml, charts/galley/values.yaml, charts/gundeck/values.yaml, charts/proxy/values.yaml, charts/spar/values.yaml
=> update enabled key for servicemonitor in helm chart default values

changelog.d/3-bug-fixes/aws-sns-without-CustomUserData, services/gundeck/src/Gundeck/Aws.hs, services/gundeck/src/Gundeck/Push.hs
Reverts wireapp/wire-server#2910
It turns out that just leaving out `CustomUserData` does not solve the issue. The values of `CustomUserData` (a set of `UserId`s) are elsewhere in use.
=> Revert "AWS/SNS create endpoint without custom user data (SQCORE-1267)"

changelog.d/3-bug-fixes/aws-error-message-parser-bug, services/gundeck/gundeck.cabal, services/gundeck/src/Gundeck/Aws.hs, services/gundeck/test/unit/Main.hs, services/gundeck/test/unit/ParseExistsError.hs
The parser for the AWS/SNS error message to explain that an endpoint is already in use was incorrect. This lead to an "invalid token" error when registering push tokens for multiple user accounts (user ids) instead of updating the SNS endpoint with an additional user id.
The fix is to not apply `endParser` twice. (Because, the end is already consumed by `manyTill`.)
https://wearezeta.atlassian.net/browse/SQCORE-1267
=> fix gundeck aws endpoint parsing

changelog.d/5-internal/pr-2878, charts/brig/templates/deployment.yaml
Ticket - https://wearezeta.atlassian.net/browse/SQPIT-491
Brig pods continuously restarts in case of liveness and readiness probes failing on the startup in the low compute resource environment.
To reproduce - 
- reduce the memory and cpu resource limits in charts/brig/values.yaml and deploy the chart.
- Components of brig will take time to start which is greater than the wait time for before running first liveness probe, hence the pod is marked as failed and restarted again and again.
Added a initial delay before running first liveness and readiness probe, which allows all the brig containers to start on a low resource environment before running the probes.
=> add initial delay seconds to brig liveness and readiness probes

changelog.d/2-features/disable-extra-nginz-upstreams-by-default, charts/nginz/templates/_helpers.tpl, charts/nginz/templates/conf/_nginx.conf.tpl, charts/nginz/templates/conf/_upstreams.txt.tpl, charts/nginz/templates/configmap.yaml, charts/nginz/values.yaml, docs/src/how-to/install/configuration-options.rst
Some upstreams are configured by default in `nginz` that have no backing service. This leads to many unnecessary DNS lookups and opens unused routes into our K8s clusters (which might be a security issue).
Upstream configuration in `nginz` goes from two entries (`ignored_upstreams`, `upstreams`) to four (`ignored_upstreams`, `upstreams`, `enabled_extra_upstreams`, `extra_upstreams`):
- `ignored_upstreams` : default upstreams that should be ignored (for backwards compatibility)
- `upstreams` : default upstreams (kept for backwards compatibility)
- `enabled_extra_upstreams` : Extra upstreams that should be enabled (routed / rendered; this one is new)
- `extra_upstreams` : Contains upstreams that are usually not deployed by default (this is new, too)
I see two benefits with this:
- Existing …
=> nginz deactivate unused upstreams (SQPIT-1174)

changelog.d/1-api-changes/get-subconversation-groupinfo, changelog.d/2-features/subconv-commit-bundles, libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs, libs/wire-api/src/Wire/API/MLS/SubConversation.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/Conversation.hs, nix/pkgs/mls-test-cli/default.nix, services/galley/galley.cabal, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/MLS/Conversation.hs, services/galley/src/Galley/API/MLS/GroupInfo.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/API/MLS/Propagate.hs, services/galley/src/Galley/API/MLS/Removal.hs, services/galley/src/Galley/API/MLS/SubConversation.hs, services/galley/src/Galley/API/MLS/Types.hs, services/galley/src/Galley/API/Public/Conversation.hs, services/galley/src/Galley/Cassandra/Queries.hs, services/galley/src/Galley/Cassandra/SubConversation.hs, services/galley/src/Galley/Effects/MemberStore.hs, services/galley/src/Galley/Effects/SubConversationStore.hs, services/galley/test/integration/API/MLS.hs, services/galley/test/integration/API/MLS/Util.hs
=> Commit bundles for subconversations

changelog.d/1-api-changes/subconv-field, libs/wire-api/src/Wire/API/Conversation/Action.hs, libs/wire-api/src/Wire/API/Event/Conversation.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/AddBotResponse_user.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/Event_conversation.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/Event_user.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/RemoveBotResponse_user.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Manual.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Manual/ConversationEvent.hs, libs/wire-api/test/golden/testObject_Event_conversation_manual_1.json, libs/wire-api/wire-api.cabal, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Create.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/MLS/Propagate.hs, services/galley/src/Galley/API/MLS/Welcome.hs, services/galley/src/Galley/API/Message.hs, services/galley/src/Galley/API/Teams.hs, services/galley/src/Galley/API/Update.hs, services/galley/src/Galley/API/Util.hs, services/galley/test/integration/API/Util.hs
=> Add optional subconversation field to conversation events

changelog.d/5-internal/mls-subconv-messages, charts/redis-cluster/requirements.yaml, libs/wire-api/src/Wire/API/Error/Galley.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/MLS.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/API/MLS/Propagate.hs, services/galley/test/integration/API/MLS.hs, services/galley/test/integration/API/MLS/Util.hs, services/galley/test/integration/API/Util.hs
This PR:
- Fixes a bug: on the first commit the creator's client is not added to member clients of the subconversation
- MLS message are propagated with the `subconv` field populated
=> FS-902: Fix empty client set & set subconv field in message propagation

charts/redis-cluster/requirements.yaml
The old version `version: 7.4.8` is no longer available on the upstream repository
=> redis-cluster chart: bump to 7.6.4

services/galley/src/Galley/API/MLS/Message.hs
- Use same validation error in internal & external commit validation
- Refactor: Factor out update path lookup
=> Factor out update path handling

changelog.d/4-docs/auth-cookie, docs/src/how-to/install/configuration-options.rst, docs/src/understand/api-client-perspective/authentication.rst
- Fix wrong statements
- Add configuration example
=> Overhaul the auth cookie documentation

changelog.d/5-internal/pr-2949, nix/haskell-pins.nix
This PR uses newly-cut releases for polysemy/polysemy-plugin/polysemy-check that mitigate the issues from #2947, rather than depending on explicit git commits.
=> Pin polysemy to 1.8.0.0

changelog.d/2-features/pr-2952, libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs, libs/wire-api/src/Wire/API/MLS/SubConversation.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/MLS/SubConversation.hs, services/galley/src/Galley/API/Query.hs, services/galley/src/Galley/API/Util.hs, services/galley/test/integration/API/MLS.hs
https://wearezeta.atlassian.net/browse/FS-901
=> Add federated endpoints to get subconversations

hack/bin/upload-image.sh
Executing `"$@"` within first argument of `if` prevents `set -e` from immediately failing the whole script.
It could also be written as `while ! "$@"; do ...`, but then getting status of `"$@"` is more complicated as `! "$@"` has status=0 and overwrites the value of `$?`.
=> hack/bin/upload-image: Retry despite `set -e`

docs/src/how-to/associate/deeplink.rst
The documentation contains a typo using the https scheme for the socks proxy configuration, this scheme is wrong and also a scheme is not necessary.
=> docs: remove invalid scheme from example socks5 host

changelog.d/1-api-changes/delete-subconversation, changelog.d/2-features/delete-subconversation, libs/wire-api/src/Wire/API/MLS/SubConversation.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/Conversation.hs, services/galley/galley.cabal, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/API/MLS/SubConversation.hs, services/galley/src/Galley/API/MLS/Util.hs, services/galley/src/Galley/API/Public/Conversation.hs, services/galley/src/Galley/App.hs, services/galley/src/Galley/Cassandra/Conversation/Members.hs, services/galley/src/Galley/Cassandra/Queries.hs, services/galley/src/Galley/Cassandra/SubConversation.hs, services/galley/src/Galley/Effects.hs, services/galley/src/Galley/Effects/MemberStore.hs, services/galley/src/Galley/Effects/SubConversationStore.hs, services/galley/src/Galley/Effects/SubConversationSupply.hs, services/galley/src/Galley/Effects/SubConversationSupply/Random.hs, services/galley/test/integration/API/MLS.hs, services/galley/test/integration/API/MLS/Util.hs
Per https://wearezeta.atlassian.net/browse/FS-1334, the PR introduces a DELETE endpoint for resetting a subconversation.
=> [FS-1334] Reset a Subconversation

changelog.d/2-features/coturn-tls, charts/coturn/templates/configmap-coturn-conf-template.yaml, charts/coturn/values.yaml
This PR introduces a configuration option in the coturn Helm chart to allow operators to set the list of ciphers permitted for TLS connections, with the defaults set for compliance with BSI TR-02102-2. Based on [this coturn PR](https://github.com/coturn/coturn/pull/1118), it's likely that TLS 1.3 ciphersuite configuration will reuse the same configuration option for TLS 1.2 and below cipher list configuration, so we can provide the configuration strings for both versions concatenated together.
=> Add TLS cipher configuration to coturn Helm chart [SQPIT-1512]

changelog.d/5-internal/brig-multi-core, services/brig/brig.cabal
`-with-rtsopts=-N1` was set very long time ago when brig started depending on http-client-openssl. It doesn't seem relevant anymore and using multiple cores should improve performance.
=> brig: Allow multiple threads to run simulaneously

libs/zauth/README.md
The specification in the readme is missing the newly added (#2764) client-id part.
This PR intends to complete the specification.
=> docs: add documentation of client id to zauth readme

changelog.d/5-internal/subconv-update-path, services/galley/src/Galley/API/MLS/Message.hs, services/galley/test/integration/API/MLS.hs
There is a bug in that when the first member of a subconversation is adding themselves to the subconversation, the key package reference mapping was not performed. This PR fixes that.
Tracked by https://wearezeta.atlassian.net/browse/FS-901.
=> [FS-901] Update the key package reference mapping of the creator of the subconversation

changelog.d/3-bug-fixes/pr-2968, services/brig/src/Brig/User/Search/TeamUserSearch.hs, services/brig/test/integration/API/TeamUserSearch.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1828
=> [SQSERVICES-1828] pagination of team members does not work properly for certain team sizes

changelog.d/2-features/delete-remote-subconversation, changelog.d/6-federation/delete-remote-subconversation, libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs, libs/wire-api/src/Wire/API/MLS/Epoch.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/Conversation.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/MLS/SubConversation.hs, services/galley/src/Galley/API/Public/Conversation.hs, services/galley/test/integration/API/MLS.hs, services/galley/test/integration/API/MLS/Util.hs
As part of https://wearezeta.atlassian.net/browse/FS-1334, this PR adds support for resetting a remote subconversation. The local case was done in PR #2956.
=> [FS-1334] Reset a Remote Subconversation

docs/src/how-to/install/configure-federation.md, docs/src/understand/federation/api.md, docs/src/understand/federation/architecture.md, docs/src/understand/federation/backend-communication.md
- fix small mistakes
- infra domain -> infrastructure domain
- apply fix "only includes the backend domain..."
- Remove "DNS Scope" section
=> Fix Federation Docs errata

changelog.d/5-internal/pr-2991, libs/types-common/src/Data/Id.hs
=> [REFACTORING] ID tag expand abbreviation to full name

changelog.d/5-internal/refactor-writetime, libs/cassandra-util/src/Cassandra/Util.hs, services/brig/src/Brig/User/Search/Index.hs, services/brig/test/integration/API/Internal.hs, services/galley/src/Galley/Cassandra/Team.hs, tools/db/find-undead/src/Work.hs, tools/db/inconsistencies/src/DanglingHandles.hs
This PR refactors multiple definitions of the `Writetime a` type to a single one, which wraps a UTCTime value.
This means no loss of precision: The function `writetimeToInt64` can recover the original integer that cassandra uses to represent writetimes.
=> Refactor Writetime

changelog.d/5-internal/sqservices-1848, docs/convert/shell.nix, services/brig/src/Brig/User/Search/Index.hs, services/brig/test/integration/API/Internal.hs, services/brig/test/integration/API/TeamUserSearch.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1848
Using the default sort specification (`created_at`)  should fix the issue, as these values are unique for this integration test.
=> [SQSERVICES-1848] Flaky test team user search query with paging state

changelog.d/3-bug-fixes/update-inbucket-chart-dependency, charts/inbucket/requirements.yaml
The prior version relied on an image that has been removed from docker hub.
For details, please refer to the [corresponding PR at `inbucket`](https://github.com/inbucket/inbucket-community/pull/5).
I've tested this on my `sven-test` test environment: http://inbucket.sven-test.wire.link/m/foobar@example.com/2
=> Update inbucket (fake smtp server) chart dependency

changelog.d/0-release-notes/chart-compatibility, charts/elasticsearch-ephemeral/templates/_helpers.tpl, charts/inbucket/templates/_helpers.tpl, charts/inbucket/templates/ingress.yaml, charts/ldap-scim-bridge/templates/_helpers.tpl, charts/ldap-scim-bridge/templates/cronjob.yaml, charts/legalhold/templates/_helpers.tpl, charts/legalhold/templates/ingress.yaml, charts/nginx-ingress-services/templates/_helpers.tpl, charts/nginx-ingress-services/templates/ingress.yaml, charts/nginx-ingress-services/templates/ingress_federator.yaml, charts/sftd/templates/_helpers.tpl, charts/sftd/templates/ingress.yaml
Ingress compatibility k8s 1.22 and beyond
See https://kubernetes.io/docs/reference/using-api/deprecation-guide/ and https://www.sobyte.net/post/2021-11/helm-chart-compatible-different-kube-versio/
=> Chart compatibility kubernetes 1.22

changelog.d/5-internal/pr-2694, libs/wire-api/src/Wire/API/User/Client/Prekey.hs, services/brig/src/Brig/App.hs, services/brig/test/integration/API/User/Client.hs, services/brig/test/integration/Util.hs
=> Prekeys investigation: test

Makefile, changelog.d/5-internal/kind-fix, docs/src/developer/developer/how-to.md, hack/bin/kind-upload-image.sh, hack/bin/kind-upload-images.sh, hack/helm_vars/redis-cluster/values.yaml.gotmpl, hack/helmfile-single.yaml, hack/helmfile.yaml, services/brig/federation-tests.sh
=> Fix kind setup for running end-to-end federation tests locally

changelog.d/5-internal/mock-utilities, services/federator/default.nix, services/federator/federator.cabal, services/federator/src/Federator/MockServer.hs, services/galley/galley.cabal, services/galley/test/integration/API.hs, services/galley/test/integration/API/Federation.hs, services/galley/test/integration/API/MLS.hs, services/galley/test/integration/API/MLS/Mocks.hs, services/galley/test/integration/API/MessageTimer.hs, services/galley/test/integration/API/Roles.hs, services/galley/test/integration/API/Util.hs
This PR introduces a very simple system for specifying federation mocks in a composable way. This replaces previous attempts (in Galley) that were only adopted in a few tests. All instances of mocked federator are now using the new system.
The system itself is a super-minimalistic "web framework" of sorts, based on a `ReaderT FederatedRequest MaybeT` monad transformer. You use `guard` to expect a certain request, and the `Alternative` combinators to specify multiple responses based on various criteria.
=> Mock combinators

.github/workflows/ci.yml
This should solve all these "temporarily deployed to cachix" messages in PR
=> Github Workflow: dont use environment for secrets

charts/galley/templates/configmap.yaml
Flag configuration already exists in [LOCs L90-L93](https://github.com/wireapp/wire-server/blob/develop/charts/galley/templates/configmap.yaml#L90-L93). Accidentally introduced in https://github.com/wireapp/wire-server/pull/2494.
=> charts/galley/configmap: remove duplicate feature flag searchVisibilityInbound

changelog.d/0-release-notes/chart-compatibility, docs/src/how-to/administrate/kubernetes/upgrade-cluster/index.md
Documentation follow-up of #3002
=> document helm chart upgrades after k8s version upgrades

changelog.d/5-internal/pr-3030, libs/wire-api/src/Wire/API/Routes/Public/Galley/Conversation.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/TeamConversation.hs, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Teams.hs, services/galley/src/Galley/API/Update.hs
This PR checks against the `ConversationActionTag` singleton in Galley's `performAction` in order to give finer-grained constraints about which federated calls get made.
=> Discriminate against performAction tags for CallsFed constraints

changelog.d/3-bug-fixes/ingress-fixup-3034, charts/nginx-ingress-services/templates/ingress_federator.yaml
Fixup to #3002 - at least since that PR was merged develop->mls branch, federator's ingress does not deploy properly on the federation environments anymore [concourse logs](https://concourse.ops.zinfra.io/teams/main/pipelines/federation-staging/jobs/deploy-bella/builds/620).
this may fix the problem. Should I make this PR to mls branch? Or to develop, then do a develop->mls merge?
I did not test this fix, just applied the same syntax as in the other working ingress resources.
=> fixup to federator ingress helm chart syntax from the changes in #3002

changelog.d/5-internal/pr-3036, libs/wire-api/src/Wire/API/Routes/Version.hs, tools/stern/exec/Main.hs, tools/stern/src/Stern/API.hs, tools/stern/src/Stern/Intra.hs, tools/stern/stern.cabal
=> Make stern assert backend api version

changelog.d/5-internal/pr-3035, changelog.d/5-internal/pr-3036, libs/wire-api/src/Wire/API/Routes/Version.hs, tools/stern/default.nix, tools/stern/src/Stern/API.hs, tools/stern/src/Stern/Intra.hs, tools/stern/stern.cabal
=> fix conversation list parser in stern

libs/wire-api/src/Wire/API/Team/Feature.hs, services/galley/src/Galley/API/Teams/Features.hs
Changed the code a little that was introduced by https://github.com/wireapp/wire-server/pull/2684 to streamline the feature flag implementation.
=> Streamline team feature ExposeInvitationURLsToTeamAdminConfig implementation

changelog.d/5-internal/helm-test, charts/brig/templates/tests/brig-integration.yaml, charts/brig/templates/tests/configmap.yaml, charts/brig/templates/tests/nginz-service.yaml, charts/brig/templates/tests/secret.yaml, charts/cargohold/templates/tests/cargohold-integration.yaml, charts/cargohold/templates/tests/configmap.yaml, charts/federator/templates/tests/configmap.yaml, charts/federator/templates/tests/federator-integration.yaml, charts/galley/templates/tests/configmap.yaml, charts/galley/templates/tests/galley-integration.yaml, charts/galley/templates/tests/secret.yaml, charts/gundeck/templates/tests/configmap.yaml, charts/gundeck/templates/tests/gundeck-integration.yaml, charts/spar/templates/tests/configmap.yaml, charts/spar/templates/tests/spar-integration.yaml, nix/overlay.nix, nix/pkgs/helm/default.nix, nix/wire-server.nix
=> charts: Mark all test resources to be only created while running tests

changelog.d/6-federation/on-new-remote-subconversation, libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs, libs/wire-api/src/Wire/API/Conversation/Protocol.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/Conversation.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/Feature.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/LegalHold.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/MLS.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/TeamConversation.hs, services/brig/test/integration/Federation/End2end.hs, services/brig/test/integration/Federation/Util.hs, services/brig/test/integration/Util.hs, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/LegalHold.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/API/MLS/SubConversation.hs, services/galley/src/Galley/API/Teams.hs, services/galley/src/Galley/API/Teams/Features.hs, services/galley/src/Galley/API/Update.hs, services/galley/src/Galley/Cassandra/Queries.hs, services/galley/src/Galley/Cassandra/SubConversation.hs, services/galley/src/Galley/Effects.hs, services/galley/src/Galley/Effects/FederatorAccess.hs, services/galley/src/Galley/Effects/SubConversationStore.hs, services/galley/test/integration/API.hs, services/galley/test/integration/API/MLS.hs, services/galley/test/integration/API/MLS/Mocks.hs, services/galley/test/integration/API/MLS/Util.hs
When a subconversation is created, all backends involved in the main conversation need to be notified, so that they create a group ID → subconversation mapping. Otherwise, commits coming from clients on those backends cannot be routed.
Similarly, when a user from a new backend B joins a conversation containing non-empty subconversations, it needs to be informed of those subconversations, so that (external) commits for those subconversations coming from clients in B can be routed.
https://wearezeta.atlassian.net/browse/FS-1451
=> extend on-new-remote-conversation by the subconv ID

services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
The function called refresh should do a refresh, not a full reindexing.
Some tests inserting data into elasticsearch need the index to be up-to-date, not re-created from cassandra. This should also avoid the arbitrary wait for 3 seconds.
=> spar tests deflake: do an ES refresh, not reindex

changelog.d/5-internal/helm-test, charts/brig/templates/tests/brig-integration.yaml, charts/brig/templates/tests/configmap.yaml, charts/brig/templates/tests/nginz-service.yaml, charts/brig/templates/tests/secret.yaml, charts/cargohold/templates/tests/configmap.yaml, charts/federator/templates/tests/configmap.yaml, charts/galley/templates/tests/configmap.yaml, charts/galley/templates/tests/galley-integration.yaml, charts/galley/templates/tests/secret.yaml, charts/gundeck/templates/tests/configmap.yaml, charts/spar/templates/tests/configmap.yaml
Defining configmaps/secrets/services as helm hook type of "test" has the disadvantage of not being able to use `helm test --filter name=...` as done in #3040 
Originally, the motivation for #3037 was to be able to go from a clusterIP-based service to a headless service. marking these as hooks with a delete policy should achieve the same result.
=> Helm hook type

changelog.d/5-internal/helm-setup, charts/cassandra-ephemeral/values.yaml, hack/helmfile.yaml
- change liveness and readyness probes to start querying more quickly to see if cassandra is up. Instead of 90 - 120 seconds, if cassandra is up earlier that should manifest itself in the setup time of 'make kube-integration-setup'
- change helmfile for wire-server to wait for databases-ephemeral to be up before launching pods: cassandra-migration needs to have a working cassandra anyway - the crashloop-backoff strategy leads to a lot of waiting in between restarts; so it should be faster to wait for cassandra to be up before attempting schema migrations
Observed speedup: 30-60 seconds.
=> helmfile sync: speedup

changelog.d/5-internal/deflake-metrics, services/brig/test/integration/API/Metrics.hs
example case where this test failed: https://concourse.ops.zinfra.io/teams/main/pipelines/staging/jobs/test/builds/342
output of failing test:
```
metrics
prometheus:                                                                              OK (0.02s)
work:                                                                                    FAIL (1.06s)
Error message: /login was called twice
expected: 2
but got: 3
CallStack (from HasCallStack):
assertFailure, called at ./Test/Tasty/HUnit/Orig.hs:86:32 in tasty-hunit-0.10.0.3-KJER1RJhmod6e0raY4U8z6:Test.Tasty.HUnit.Orig
assertEqual, called at test/integration/API/Metrics.hs:78:12 in main:API.Metrics
Use -p '(!/turn/&&!/user.auth.cookies.limit/)&&/metrics.work/' to rerun this test only.
```
=> Deflake metrics test

changelog.d/4-docs/federation-error-type, services/brig/docs/swagger.md
This is a tiny update to the Swagger documentation so client developers know how to easily tell one federation error type from another (i.e., whether to blame the local or a remote backend for the error).
Tracked by https://wearezeta.atlassian.net/browse/FS-1075.
=> [FS-1075] Extend the Swagger documentation for federation error types

changelog.d/3-bug-fixes/mls-self-conv-creator-ref, services/brig/src/Brig/Data/MLS/KeyPackage.hs, services/galley/src/Galley/API/Clients.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/API/MLS/Removal.hs, services/galley/src/Galley/API/MLS/Welcome.hs, services/galley/test/integration/API/MLS.hs
As reported in https://wearezeta.atlassian.net/browse/FS-1488, when a device of a creator of an MLS self-conversation is deleted, the device cannot be successfully removed from an MLS self-conversation. This was the case because there was no mapping of the creator client key package reference in Brig. This PR fixes that.
=> [FS-1488] Fix self-conversation creator key package mapping

libs/types-common-aws/src/Util/Test/SQS.hs
The previous logic of emptying the queue introduced in #2825 by reading all messages and deleting them assumes there is no other process writing anything into the queue, which might not be the case (in case of parallel brig/galley/spar tests). Instead, use purgeQueue to empty the queue, which should be faster and more reliable.
=> Test helper SQSWatcher: use purgeQueue

services/galley/test/integration/API/MLS.hs, services/galley/test/integration/API/MLS/Util.hs
This PR changes the way `MLSTest` monad manages client's group state: The client's group state is now transparently availble in the monad's state instead of in the file system.
=> MLS integration testing: make client group state transparent in state

changelog.d/2-features/subconv-leave, libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/Conversation.hs, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Clients.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/LegalHold.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/API/MLS/SubConversation.hs, services/galley/src/Galley/API/Public/Conversation.hs, services/galley/src/Galley/API/Teams/Features.hs, services/galley/src/Galley/API/Update.hs, services/galley/src/Galley/Effects.hs, services/galley/test/integration/API/MLS.hs, services/galley/test/integration/API/MLS/Util.hs
https://wearezeta.atlassian.net/browse/FS-1336
=> [FS-1336] Leaving subconversations

changelog.d/5-internal/federator-log, services/federator/src/Federator/Monitor/Internal.hs
Lower the log level of federator inotify. Now it doesn't spam the console output anymore when running integration tests.
=> Lower the log level of federator inotify

changelog.d/5-internal/servantify-teams-notifications, libs/wire-api/src/Wire/API/Error/Galley.hs, libs/wire-api/src/Wire/API/Notification.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/TeamNotification.hs, libs/wire-api/wire-api.cabal, services/galley/galley.cabal, services/galley/src/Galley/API/Error.hs, services/galley/src/Galley/API/Public.hs, services/galley/src/Galley/API/Public/Servant.hs, services/galley/src/Galley/API/Public/TeamNotification.hs, services/galley/src/Galley/API/Teams.hs
I left the old Swagger `Doc` models untouched. But, I migrated the existing Swagger fields as good as possible. Removing old Swagger from our code base (including related `Doc` models) will be the next step.
[**Ticket**](https://wearezeta.atlassian.net/browse/SQPIT-1479)
=> Servantify /teams/notifications

Makefile, libs/types-common/src/Util/Options.hs
Follow up to https://github.com/wireapp/wire-server/issues/2791
This PR updates local development test setup:
- the ES schema is always reset before any local integration tests are run
- all DB schemas are migrated when you run any test suite (was only the DB for the test suite's service before). This is most likely what we want.
This PR also removes am unhelpful warning in the -schema binaries.
=> Development: Make sure ES schema is reset before test runs

deploy/dockerephemeral/run.sh
Needed to put docker into a consistent state somehow more reliably after shutdown.  This works as you'd expect for a single `^C`.  If you press ^C twice, you're on your own!
=> Tweak docker-ephemeral/run.sh

changelog.d/5-internal/doc-msg-sending, services/galley/src/Galley/API/Message.hs
This is a tiny PR documenting a remote message sending function.
Tracked by https://wearezeta.atlassian.net/browse/FS-1075.
=> Haddock for a message sending function

services/galley/src/Galley/API/Create.hs
As the note in the changed file reads:
> FUTUREWORK: Invoke the creating a conversation action only once
> protocol-specific validation is successful. Otherwise we might write the
> conversation to the database, and throw a validation error when the
> conversation is already in the database.
I believe the PR does not need a changelog.
=> Add a futurework note on the order of actions when creating a conversation

changelog.d/5-internal/graceful-shutdown, libs/wai-utilities/src/Network/Wai/Utilities/Server.hs
=> use Wai's settings for graceful shutdown

deploy/dockerephemeral/run.sh
Follow up to #3068. Using `docker compose` caused problems in multiple developer's dev envs.
=> Use docker-compose in run.sh

changelog.d/0-release-notes/coturn-beta, changelog.d/2-features/coturn-image-update, changelog.d/3-bug-fixes/coturn-config-reloader, charts/coturn/Chart.yaml, charts/coturn/README.md, charts/coturn/values.yaml
This updates the default version of coturn in the Helm chart to the latest stable version currently in use in our cloud environments. Also, the config reloader sidecar image has been updated to a version with metadata which is compatible with containerd.
The Helm chart is also promoted from alpha to beta stability, given that we now have this deployed in our cloud environments.
=> Update container images in coturn Helm chart

changelog.d/2-features/subconv-leave, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/API/MLS/Propagate.hs, services/galley/src/Galley/API/MLS/Removal.hs, services/galley/src/Galley/API/MLS/SubConversation.hs, services/galley/src/Galley/API/MLS/Types.hs, services/galley/test/integration/API/MLS.hs
This fixes a bug identified in https://wearezeta.atlassian.net/browse/FS-1534. A client leaving a subconversation would get a backend-created remove proposal, while it should not. The fix makes the application logic consistent with the MLS conversation leaving case where the leaving user gets no backend-created proposals.
=> [FS-1534] A subconversation leaver gets a remove proposal

changelog.d/5-internal/nixpkgs, hack/bin/register_idp.sh, libs/hscim/test/Test/Capabilities/MetaSchemaSpec.hs, libs/wire-api/src/Wire/API/Routes/Public/Spar.hs, libs/wire-api/src/Wire/API/Routes/QualifiedCapture.hs, nix/manual-overrides.nix, nix/nginz.nix, nix/overlay.nix, nix/pkgs/mls-test-cli/default.nix, nix/pkgs/zauth/default.nix, nix/sources.json, services/spar/src/Spar/Scim.hs
=> Bump nixpkgs

services/brig/test/integration/API/User/Auth.hs
The failure:
```
nginz-login-multiple-cookies: FAIL
2: Nothing === Nothing
```
occurs on the check for the header
```haskell
-- Refresh tokens
_rs <-
post (unversioned . n . path "/access" . cookie c) <!! do
const 200 === statusCode
const Nothing =/= getHeader "Set-Cookie"  -- FAILURE
const (Just "access_token") =~= responseBody
```
context: you only get a fresh user cookie after the renew age (2 seconds) have elapsed. Before that, only the access token is renewed, but you don't get a fresh cookie. As this is based on time, it's possible the timestamp used to decide whether you get a fresh token isn't reached yet. So we wait 1 extra second (3 in total, instead of 2.00001 seconds).
Only time will tell if this is actually deflaking the test in question. …
=> deflake: wait 1 extra second before attempting to renew a cookie.

services/brig/test/integration/API/Team.hs
deflake `post /teams/:tid/invitations - 403 too many pending'`
```   
FAIL
1: 403 =/= 201
2: Just too-many-team-invitations =/= Nothing
```
=> Deflake invitation too many pending

Makefile
This was probably the result of a broken conflict resolution.
=> Remove duplicated Makefile rule

changelog.d/2-features/coturn-image-update, charts/coturn/Chart.yaml
This is a follow-up to #3078. The pre-stop hook script was not updated when some metrics were relabeled in the update from 4.5.2 to 4.6.0, which would mean that the script would inadvertently exit while there were still active TURN sessions in the coturn process. This change updates the coturn image to a version with a fixed pre-stop hook script.
=> Coturn container image update errata

libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/Conversation.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/MLS/SubConversation.hs, services/galley/src/Galley/API/MLS/Types.hs, services/galley/test/integration/API/MLS.hs
According to https://wearezeta.atlassian.net/wiki/spaces/CORE/pages/641171479/Conferencing+in+MLS+Subconversations#Hangup, a subconversation's epoch should be reset to zero once its last member leaves. The test case in this PR shows the code doesn't currently do that. It additionally asserts there should be no members after the last member leaves, which is a reasonable expectation.
Tracked by https://wearezeta.atlassian.net/browse/FS-1541.
=> [FS-1541] After the last leaver the subconversation should be reset

libs/wire-api/src/Wire/API/Team.hs
Add some wisdom of @akshaymankar to `TeamBinding`. :smile_cat:
=> Add Haddock for TeamBinding

changelog.d/5-internal/FS-1564, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/MLS/SubConversation.hs, services/galley/test/integration/API/MLS.hs
=> [FS-1564] no messages sent to clients who left subconv

libs/wire-api/src/Wire/API/Team/Member.hs
This PR is meant to be reverted after testing large MLS conversations
=> Raise HardTrunctationLimit to 100k

services/brig/brig.integration.yaml
Whoever approves, please merge directly!
=> Fix local tests

services/cannon/src/Cannon/App.hs, services/gundeck/test/integration/API.hs
* introduces an integration test / regression test to check that control-level pings with a payload result in a control-level pong with the same payload as specified in the [RFC](https://www.rfc-editor.org/rfc/rfc6455#section-5.5.2)
This is about debugging https://wearezeta.atlassian.net/browse/FS-1489
(related ping-pong prior work: https://github.com/wireapp/wire-server/pull/561 and prior discussion: https://github.com/wireapp/wire-server/issues/560)
=> websocket ping-pong

docs/src/conf.py
=> Fix error in conf when SOURCE_DATE_EPOCH is unset

changelog.d/6-federation/openssl, libs/wire-api-federation/default.nix, libs/wire-api-federation/src/Wire/API/Federation/Client.hs, libs/wire-api-federation/src/Wire/API/Federation/Error.hs, libs/wire-api-federation/wire-api-federation.cabal, nix/haskell-pins.nix, services/federator/default.nix, services/federator/exec/Main.hs, services/federator/federator.cabal, services/federator/src/Federator/Env.hs, services/federator/src/Federator/InternalServer.hs, services/federator/src/Federator/Monitor.hs, services/federator/src/Federator/Monitor/Internal.hs, services/federator/src/Federator/Remote.hs, services/federator/src/Federator/Response.hs, services/federator/src/Federator/Run.hs, services/federator/test/integration/Main.hs, services/federator/test/integration/Test/Federator/IngressSpec.hs, services/federator/test/integration/Test/Federator/Util.hs, services/federator/test/unit/Main.hs, services/federator/test/unit/Test/Federator/Client.hs, services/federator/test/unit/Test/Federator/InternalServer.hs, services/federator/test/unit/Test/Federator/Monitor.hs, services/federator/test/unit/Test/Federator/Options.hs, services/federator/test/unit/Test/Federator/Remote.hs
=> Use openssl instead of tls in federator http2 client

.github/workflows/ci.yml
This updates the nix and cachix GitHub actions to their latest versions. The cachix action was a few versions behind, and an upgrade of the nix action is necessary for compatibility with nix 1.14, as reported in cachix/install-nix-action#161.
=> Upgrade nix and cachix GitHub actions

libs/wire-api-federation/src/Wire/API/Federation/Error.hs, nix/haskell-pins.nix, nix/manual-overrides.nix, services/brig/brig.cabal, services/brig/default.nix, tools/db/inconsistencies/default.nix, tools/db/inconsistencies/inconsistencies.cabal
=> Cleanup haskell-pins

changelog.d/1-api-changes/v3, libs/api-client/src/Network/Wire/Client/API/Conversation.hs, libs/wire-api/src/Wire/API/Conversation.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/Conversation.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/MLS.hs, libs/wire-api/src/Wire/API/Routes/Version.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/NewConv_user.hs, libs/wire-api/test/golden/testObject_NewConv_user_3.json, libs/wire-api/test/golden/testObject_NewConv_v2_user_3.json, libs/wire-api/test/unit/Test/Wire/API/Routes/Version.hs, services/brig/docs/swagger-v3.json, services/brig/src/Brig/API/Public.hs, services/brig/test/integration/API/Provider.hs, services/brig/test/integration/API/Team/Util.hs, services/brig/test/integration/Federation/End2end.hs, services/brig/test/integration/Util.hs, services/galley/src/Galley/API/Create.hs, services/galley/test/integration/API.hs, services/galley/test/integration/API/Federation.hs, services/galley/test/integration/API/MLS.hs, services/galley/test/integration/API/MLS/Util.hs, services/galley/test/integration/API/MessageTimer.hs, services/galley/test/integration/API/Roles.hs, services/galley/test/integration/API/Util.hs
This finalises API v3, makes it supported, and introduces a new development API v4. All the new MLS endpoints have been removed from v3 and moved to v4.
=> Finalise API v3

docs/src/understand/single-sign-on/understand/main.md
* replace "tho" with "the"
* fix glossary reference
* fix terminology list upstream uses "End User/Browser" here, in our context Transport makes more sense
=> chore: Fix typos in SSO documentation

changelog.d/5-internal/pr-3125, libs/jwt-tools/test/Spec.hs
In the test for the `jwt-tools` rust FFI we used a hard coded proof with a very short expiration time.
Replaced it with a proof with max expiration time (until 2038).
=> Fix dpop access token test

hack/bin/git-log-bumps.py
This PR adds this script
```
usage: git-log-bumps [-h] [--env ENV] [--rev REV]
Shows commits in wire-server together with their environment bumps in cailleach.
This script assumes that your wire-server and cailleach repos live next to each other.
Examples:
hack/bin/git-log-bumps.py --env staging --rev origin/develop          # the default
hack/bin/git-log-bumps.py --env prod --rev origin/master              # production releases
hack/bin/git-log-bumps.py --env '{anta,bella,chala}' --rev origin/mls # releases to anta&co
options:
-h, --help  show this help message and exit
--env ENV   Name of the environment in cailleach. default: staging
--rev REV   The target of git log. default: origin/develop
```
Example output
```
git log --first-parent origin/develop
with version bumps for staging …
```
=> Add script that shows commits together with environment bumps

libs/wai-utilities/default.nix, libs/wai-utilities/src/Network/Wai/Utilities/MockServer.hs, libs/wai-utilities/wai-utilities.cabal
=> MockServer: Supress noise from ConnectionIsClosed errror from http2

changelog.d/3-bug-fixes/stern-api-check, tools/stern/default.nix, tools/stern/src/Stern/API.hs, tools/stern/src/Stern/Intra.hs, tools/stern/stern.cabal, tools/stern/test/unit/Main.hs
This PR removes the runtime check introduced https://github.com/wireapp/wire-server/pull/3036 and replaces it with a unit test.
Also the overly restrictive test condition
```
maximum (vinfoSupported vinfo) == backendApiVersion
```
is replaced with
```
backendApiVersion `elem` (vinfoSupported vinfo)
```
=> stern: make api version check a unit test

changelog.d/1-api-changes/delete-subconversation, services/galley/test/integration/API/MLS.hs
This adds a test for deleting a subconversation where a user that is in the parent conversation, but not in the subconversation successfully deletes the subconversation. This is an important functionality that allows to delete a subconversation with members that have crashed and never cleaned it up.
Tracked by https://wearezeta.atlassian.net/browse/FS-1588.
=> [FS-1558] Add a test: delete a subconversation as a conversation member

changelog.d/4-docs/client-api-version-bump-checklist, docs/src/developer/developer/api-versioning.md, libs/wire-api/src/Wire/API/Routes/Version.hs
This is a small PR adding a checklist for a client API version bump. Please expand/modify as you see fit!
=> Add a client API version bump checklist

changelog.d/5-internal/downgrade-http2, libs/wai-utilities/src/Network/Wai/Utilities/MockServer.hs, libs/wire-api-federation/src/Wire/API/Federation/Error.hs, nix/haskell-pins.nix
Downgrade http2 library.
https://wearezeta.atlassian.net/browse/FS-1609
=> Downgrade to our fork of http2

changelog.d/5-internal/downgrade-http2, libs/wai-utilities/src/Network/Wai/Utilities/MockServer.hs, libs/wire-api-federation/src/Wire/API/Federation/Error.hs, nix/haskell-pins.nix
This is PR #3141 backported to the Frida release branch.
Tracked by https://wearezeta.atlassian.net/browse/FS-1609.
=> [Frida release] Backport the reverting of the http2 change

changelog.d/5-internal/pr-3136, services/gundeck/src/Gundeck/Env.hs, services/gundeck/src/Gundeck/Redis.hs, services/gundeck/src/Gundeck/Run.hs, services/gundeck/test/integration/Util.hs
This PR fixes a memory leak in gundeck caused by its reconnection logic when Redis is down. The heap before this PR:
and after:
Each spike here is a series of requests sent to gundeck while redis is down; the resulting taper-off in both charts is when redis comes back online.
It's unclear exactly what is causing this behavior in HEAD, but the original logic is highly suspicious. An `MVar` is created with the redis connection and is always assumed to be full. Subsequent requests to Redis then catch any exceptions they might see, and trigger a reconnection event, where they spin, attempting to reconnect. Only one thread may spin on this reconnection event, but the others are all blocked on it, and all will be in contention to update the `MVar` --- ironically, they will all be attempting to …
=> Fix gundeck leak

Makefile
Fix command for resetting ES index in the Makefile
=> Fix ES reset command in Makefile

libs/wire-api/src/Wire/API/User/Profile.hs, nix/default.nix, nix/sources.json, nix/wire-server.nix
This PR updates to cachix 1.3.1 in hopes of solving the issue https://github.com/cachix/cachix/issues/509
I've added a separate nixpkgs pin for cachix to avoid having to upgrade all the things and quickly try out if upgrading solves the issue.
If this PR fixes it we can take some time to upgrade our main `nixpkgs` pin and use cachix from there. If not we can consider reverting this PR.
=> Upgrade cachix to 1.3.1

libs/wire-api-federation/default.nix, libs/wire-api-federation/src/Wire/API/Federation/Client.hs, libs/wire-api-federation/src/Wire/API/Federation/Error.hs, libs/wire-api-federation/wire-api-federation.cabal, services/federator/default.nix, services/federator/exec/Main.hs, services/federator/federator.cabal, services/federator/src/Federator/Env.hs, services/federator/src/Federator/InternalServer.hs, services/federator/src/Federator/Monitor.hs, services/federator/src/Federator/Monitor/Internal.hs, services/federator/src/Federator/Remote.hs, services/federator/src/Federator/Response.hs, services/federator/src/Federator/Run.hs, services/federator/test/integration/Main.hs, services/federator/test/integration/Test/Federator/IngressSpec.hs, services/federator/test/integration/Test/Federator/Util.hs, services/federator/test/unit/Main.hs, services/federator/test/unit/Test/Federator/Monitor.hs, services/federator/test/unit/Test/Federator/Options.hs, services/federator/test/unit/Test/Federator/Remote.hs
Reverts wireapp/wire-server#3051
Context https://wearezeta.atlassian.net/browse/FS-1609
=> Revert "Use openssl instead of tls in federator http2 client"

services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/Teams.hs, services/galley/src/Galley/API/Update.hs, services/galley/test/integration/API.hs
Make the following routes fault tolerant of federation members being unavailable, and adding tests to cover this situation. The two routes removing members from conversations are covered by the same test, as they quickly converge on the same code path.
- DELETE /conversations/{cnv_domain}/{cnv}/members/{usr_domain}/{usr}
- DELETE /conversations/{cnv}/members/{usr}
- DELETE /teams/{tid}/conversations/{cid}
=> FS-1530 Suppress federated errors when removing users from conversation

changelog.d/5-internal/pr-3142, libs/jwt-tools/src/Data/Jwt/Tools.hs, libs/jwt-tools/test/Spec.hs, nix/pkgs/rusty_jwt_tools_ffi/add-Cargo.lock.patch, nix/pkgs/rusty_jwt_tools_ffi/default.nix
https://wearezeta.atlassian.net/browse/SQSERVICES-1942
=> [SQSERVICES-1942] Fix DPoP access token error propagation (2/2)

services/run-services, tools/stern/src/Stern/Intra.hs
=> fix: paths in stern

changelog.d/2-features/inbucket-tls-and-basic-auth, charts/inbucket/templates/basic-auth-secret.yaml, charts/inbucket/templates/cert.yaml, charts/inbucket/templates/ingress.yaml, charts/inbucket/templates/issuer.yaml, charts/inbucket/values.yaml, charts/nginx-ingress-services/templates/certificate.yaml
As discussed with QA and security: This adds TLS (HTTPS) and HTTP basic authentication to the `inbucket` Helm chart. (It was: No authentication, no HTTPS.)
I tried to separate the `cert-manager` stuff of `nginx-ingress-service` from this chart, because this should really just be a help for testing and not interfere with production things.
The branch name is a bit misleading, because we switched the goal from ip allow listing to basic authentication.
=> inbucket Helm chart: TLS and basic authentication

changelog.d/5-internal/SQPIT-1544, services/gundeck/src/Gundeck/Aws.hs, services/gundeck/src/Gundeck/Push/Data.hs, services/gundeck/src/Gundeck/Push/Native.hs, services/gundeck/src/Gundeck/Push/Native/Types.hs
=> try recreating ARN when token exists in Cassandra

changelog.d/3-bug-fixes/ingress-controller-logs, charts/nginx-ingress-controller/values.yaml
For the new ingress controller, see https://github.com/wireapp/wire-server/pull/3140
https://wearezeta.atlassian.net/browse/SEC-47
=> old-ingress-stop-logging-query-parameters

changelog.d/1-api-changes/create-conv-failed-to-add, changelog.d/6-federation/create-conversation-dos, libs/types-common/src/Data/Qualified.hs, libs/wire-api/src/Wire/API/Conversation.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/Conversation.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Manual.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Manual/CreateGroupConversation.hs, libs/wire-api/test/golden/testObject_CreateGroupConversation_1.json, libs/wire-api/test/golden/testObject_CreateGroupConversation_2.json, libs/wire-api/test/golden/testObject_CreateGroupConversation_3.json, libs/wire-api/wire-api.cabal, services/galley/src/Galley/API/Create.hs, services/galley/src/Galley/API/Public/Conversation.hs, services/galley/src/Galley/API/Util.hs, services/galley/test/integration/API.hs, services/galley/test/integration/API/Federation/Util.hs
Tracked by https://wearezeta.atlassian.net/browse/FS-1147.
=> [FS-1147] Proteus: Support creating a conversation when remote backends are unavailable

flaky-tests.yaml, hack/bin/flaky_tests.py
This PR adds a a script `hack/bin/flaky_test.py` that lists flaky integration tests together with links to the builds they failed. It lists flaky tests that caused the most builds to fail first.
The script makes use of the data collected by the new [failing-tests](https://concourse.ops.zinfra.io/teams/main/pipelines/failing-tests) pipeline. Since this pipeline only just started collecting data the quality of reporting from `flaky_test.py` should increase when more data has been collected.
Flaky tests are discovered from data and also can manually marked as flaky by adding entries to `flaky-tests.yaml`. You can also add comments to `flaky-tests.yaml` that are shown in the output of the script. Flaky test discovery works by assuming that all failing test in the `staging`, `prod` and `mls` …
=> Add flaky_tests.py and flaky-tests.yaml

flaky-tests.yaml, hack/bin/flaky_tests.py
This PR adds `--discover` to `flaky_tests.py` that can help you manually discover flaky tests.
This PR also adds two more flaky tests discovered through it.
=> flaky_tests.py add --discover option

changelog.d/3-bug-fixes/pr-3152, services/brig/brig.cabal, services/brig/src/Brig/API/Public.hs, services/brig/src/Brig/API/Public/Swagger.hs, services/brig/test/integration/API/Swagger.hs, services/brig/test/integration/Main.hs
https://wearezeta.atlassian.net/browse/SQPIT-1654
separate commits for (failing) test cases, for fix, and house keeping.
Before the fix:
```
$ make ci package=brig TASTY_PATTERN=/swagger/
[...]
Brig API Integration
version
GET /api/swagger.json:    OK (0.13s)
GET /api/swagger-ui:      OK (0.03s)
GET /v2/api/swagger.json: FAIL
Exception: HttpExceptionRequest Request {
host                 = "127.0.0.1"
port                 = 8082
secure               = False
requestHeaders       = []
path                 = "/v2/api/swagger.json"
queryString          = ""
method               = "GET"
proxy                = Nothing
rawBody              = False
redirectCount        = 10
responseTimeout      = ResponseTimeoutDefault
requestVersion       = HTTP/1.1
}
(StatusCodeException (Response …
```
=> Fix version paths

Makefile, changelog.d/5-internal/upload-integration-test-logs-s3, hack/bin/integration-test.sh, nix/wire-server.nix
Add a flag `UPLOAD_LOGS` to enable/disable uploading integration test run logs to AWS S3.
=> Upload test results to AWS

changelog.d/4-docs/unblock-swagger, libs/wire-api/src/Wire/API/Routes/Version/Wai.hs
https://wearezeta.atlassian.net/browse/SQPIT-1691
=> Allow swagger on disabled versions.

changelog.d/5-internal/downgrade-http2, libs/wai-utilities/src/Network/Wai/Utilities/MockServer.hs, libs/wire-api-federation/src/Wire/API/Federation/Error.hs, nix/haskell-pins.nix
This reverts commit 02ba744844b5e130caaf881cf91d89b366ac4c0d.
The real issue was resolved in #3154
=> Revert "Downgrade to our fork of http2 (#3141)"

charts/nginz/values.yaml
For reference this is how it is called from within the integration tests:
https://github.com/wireapp/wire-server/blob/e3f8b9c0d2a85ad275d97152858469b3e2e0fefc/services/galley/test/integration/API/Teams.hs?plain=1#L1146
=> Expose internal verification-code endpoint in QA envs

changelog.d/5-internal/pr-3194, nix/pkgs/rusty_jwt_tools_ffi/default.nix
=> rusty_jwt_tools_ffi: bump + fix build

changelog.d/3-bug-fixes/coturn-liveness, charts/coturn/templates/statefulset.yaml, charts/coturn/values.yaml
Increase default of liveness/readiness probe and make it configurable.
Under high load, the default of failureThreshold=3 timeoutSeconds=1 can lead to restarts of the coturn pod due to the http port being temporarily starved of CPU, leading to an unnecessary restart of the coturn pods. This change should make this less frequent and improve call stability.
=> Coturn helm chart: Increase liveness timeout

changelog.d/3-bug-fixes/coturn-interal-db, charts/coturn/templates/statefulset.yaml
Add memory-backed mount /var/lib/coturn to store sqllite DB to improve performance, as described on https://github.com/wireapp/coturn/tree/master/docker/coturn#persistence
=> coturn helm chart: use a memory-backed mount

changelog.d/4-docs/fs-51-proteus-failed-to-send, libs/wire-api/src/Wire/API/Message.hs, libs/wire-api/src/Wire/API/User/Client.hs
The response to the `POST /conversations/:domain/:cnv/proteus/messages` endpoint contains the `failed_to_send` field, but the rendered Swagger documentation for the filed was overwritten by another field's documentation. This PR fixes the documentation for that and other response fields listing clients.
Tracked by https://wearezeta.atlassian.net/browse/FS-51.
=> [FS-51] Fix Swagger for failed_to_send in Proteus

libs/wire-api/src/Wire/API/Routes/Public/Galley/Conversation.hs
=> avoid overlapping versions

docs/src/developer/developer/large-conversations.md, docs/src/developer/developer/large-conversations.yaml
=> Documentation: references for refactoring galley for large convs

changelog.d/5-internal/pr-3232, tools/stern/src/Stern/API.hs, tools/stern/src/Stern/Intra.hs, tools/stern/test/integration/API.hs
=> More stern integration tests and fixes

hack/helm_vars/ingress-nginx-controller/values.yaml.gotmpl
Using load balancer could work also, but requires additional annotations that are environment-specific. This is a fix to a previous PR which was first tested, then refactored without properly being tested, which is why the intended `type: Nodeport` line was missing.
=> integration tests fixup: use nodeport

hack/bin/integration-setup-federation.sh
We run `helm dep update` right before running the helmfile command, so this shouldn't be required.
This saves 1.5 mins in CI.
=> integration-setup: Pass --skip-deps to helmfile sync

changelog.d/5-internal/searchcontacts-permission, libs/galley-types/src/Galley/Types/Teams.hs, services/brig/src/Brig/Team/Util.hs, services/brig/src/Brig/User/API/Search.hs
https://wearezeta.atlassian.net/browse/FS-1880
integration test is under way [elsewhere](https://github.com/wireapp/wire-server/pull/3251) for technical reasons.
=> Introduce SearchContacts permission.

changelog.d/4-docs/grepinclude, docs/src/conf.py, docs/src/grepinclude.py, docs/src/how-to/install/tls.md
Some python to include pieces of code inside docs.wire.com that auto-updates and in somewhat resilient to minor moving lines up and down.
Also document TLS ciphers used for coturn.
=> Grepinclude sphinx directive

changelog.d/4-docs/swagger-ui-toc, docs/src/understand/api-client-perspective/swagger.md, services/brig/src/Brig/API/Public.hs, services/brig/test/integration/API/Swagger.hs
https://wearezeta.atlassian.net/browse/FS-1910
=> Make /api/swagger{-ui,.json} TOC html pages to all versions.

.hlint.yaml
What it says on the tin. Without this we were getting false positives, specifically when using parentheses.
```haskell
(someF someA).fieldAccess
```
=> [chore]: Ensure hlint config accounts for record-dot-syntax.

changelog.d/3-bug-fixes/pr-3263, charts/nginz/templates/conf/_nginx.conf.tpl, libs/wire-api/src/Wire/API/Routes/Public.hs, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs, services/brig/src/Brig/API/Client.hs, services/brig/src/Brig/API/Public.hs, services/brig/test/integration/API/User.hs, services/brig/test/integration/API/User/Client.hs, services/brig/test/integration/API/User/Util.hs, services/brig/test/integration/Main.hs, services/nginz/integration-test/conf/nginz/common_response_with_zauth.conf, services/nginz/integration-test/conf/nginz/nginx.conf
To create a valid DPoP access token for the client's e2eid CSR we have to pass the correct domain to the crypto library.
We can extract the domain from the request via the HTTP host header.
However, with `nginz` in front of `brig` the host header is automatically redefined as `$proxy_host`. (see <http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header>)
To pass the original header, a new header `Z-Host` is defined and set to the original HTTP host header value via `$host`.
=> fix: forward original http host to proxy request in nginz as `Z-Host`

Makefile, hack/bin/cassandra_dump_schema
This PR fixes this bug: `git-add-cassandra-schema` also dumps the _test2 keyspaces
=> Fix cassandra-schema.cql generation script

changelog.d/3-bug-fixes/pr-3269, libs/wire-api/src/Wire/API/User/Client/DPoPAccessToken.hs
https://wearezeta.atlassian.net/browse/FS-1931
=> [FS-1931] Dpop Access Token Should Be Base64 Encoded

changelog.d/6-federation/FS-1868, libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/MLS/Propagate.hs, services/galley/test/integration/API/MLS.hs
See also https://github.com/wireapp/wire-server/pull/3271.
=> Add subconversation ID to RemoteMLSMessage

integration/test/API/Galley.hs, integration/test/SetupHelpers.hs, integration/test/Testlib/Assertions.hs, integration/test/Testlib/Cannon.hs, integration/test/Testlib/HTTP.hs, integration/test/Testlib/JSON.hs
This PR adds `postConversation` to the new integration test suite as well as a small helpers.
This PR also removes some filtering of callstack items, that turned out not to be helpful: In case of missing callstack information you can end up with an empty callstack and almost no clue where to begin your search.
=> Add postConversation test suite and some helpers

integration/integration.cabal, integration/test/Test/MLS.hs, libs/wire-api/src/Wire/API/Conversation/Protocol.hs, libs/wire-api/src/Wire/API/Event/Conversation.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/Conversation.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Manual.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Manual/ConversationEvent.hs, libs/wire-api/test/golden/testObject_Event_conversation_manual_2.json, services/galley/src/Galley/API/Update.hs, services/galley/test/integration/API/MLS.hs
This PR adds sending a `conversation.update-protocol` event to all conversation participants when the protocol is switched.
=> Add conversation.protocol-update event

.hlint.yaml, integration/test/Test/Demo.hs, integration/test/Testlib/App.hs, integration/test/Testlib/Cannon.hs
=> Handle race conditions in /integration

hack/bin/create_team.sh, hack/bin/create_team_members.sh, hack/bin/create_team_request_code.sh, hack/bin/create_test_team_admins.sh, hack/bin/create_test_team_members.sh, hack/bin/create_test_user.sh
[FS-1148]: https://wearezeta.atlassian.net/browse/FS-1148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Restore deleted scripts

changelog.d/5-internal/mls-integration, integration/default.nix, integration/integration.cabal, integration/test/API/Brig.hs, integration/test/API/Galley.hs, integration/test/MLS/Util.hs, integration/test/SetupHelpers.hs, integration/test/Testlib/Assertions.hs, integration/test/Testlib/Cannon.hs, integration/test/Testlib/Env.hs, integration/test/Testlib/HTTP.hs, integration/test/Testlib/JSON.hs, integration/test/Testlib/Run.hs, integration/test/Testlib/Types.hs
This PR copies and adapts the MLS test code in the galley integration suite to the new integration tests. This is necessary in order to write new MLS tests.
A copy of this PR for the MLS branch can be found [here](https://github.com/wireapp/wire-server/pull/3286).
https://wearezeta.atlassian.net/browse/FS-1937
=> Port MLS test framework to new integration suite

changelog.d/1-api-changes/FS-1467, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/Update.hs, services/galley/test/integration/API.hs, services/galley/test/integration/API/Federation.hs, services/galley/test/integration/API/MessageTimer.hs, services/galley/test/integration/API/Roles.hs
This just merges PR #3229 into the `mls` branch.
=> FS-1467: Make conversation metadata APIs fault tolerant to federation errors

changelog.d/1-api-changes/delete-keypackages, integration/integration.cabal, integration/test/API/Brig.hs, integration/test/MLS/Util.hs, integration/test/Test/MLS/KeyPackage.hs, libs/wire-api/src/Wire/API/MLS/KeyPackage.hs, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs, services/brig/src/Brig/API/MLS/KeyPackages.hs, services/brig/src/Brig/API/Public.hs, services/brig/src/Brig/Data/MLS/KeyPackage.hs
Add endpoint to delete key packages
https://wearezeta.atlassian.net/browse/FS-1881
=> Endpoint for deleting key packages

changelog.d/5-internal/ptests, integration/Setup.hs, integration/integration.cabal, integration/test/Testlib/PTest.hs, integration/test/Testlib/Prelude.hs
Add support for parametrised tests to the integration test suite. At the moment, it only supports parametrised tests of the form `Domain -> App ()`, which are then instantiated with both domain ('own' and 'other').
=> Add parametrised tests

changelog.d/5-internal/pr-3305, integration/test/API/BrigInternal.hs, integration/test/Test/Brig.hs, libs/wire-api/src/Wire/API/OAuth.hs, libs/wire-api/src/Wire/API/Routes/Internal/Brig/OAuth.hs, libs/wire-api/test/unit/Test/Wire/API/Roundtrip/Aeson.hs, services/brig/src/Brig/API/OAuth.hs, services/brig/test/integration/API/OAuth.hs, tools/stern/src/Stern/API.hs, tools/stern/src/Stern/API/Routes.hs, tools/stern/src/Stern/Intra.hs, tools/stern/test/integration/API.hs
=> Register and Update OAuth client via Stern/Backoffice

integration/test/API/GalleyInternal.hs, integration/test/Test/B2B.hs, integration/test/Test/Brig.hs, integration/test/Test/Demo.hs, integration/test/Testlib/App.hs, integration/test/Testlib/Cannon.hs, integration/test/Testlib/ModService.hs, integration/test/Testlib/PTest.hs
This is a small improvement to the new integration test suite. The `Domain` type used as an argument to parametrised tests is now the default type used to represent domains throughout the tests. This makes it easier to e.g. collect domains coming from different sources into a list.
=> Use `Domain` type everywhere.

changelog.d/2-features/coturn-federation-dtls-helm-chart, charts/coturn/Chart.yaml, charts/coturn/templates/_helpers.tpl, charts/coturn/templates/configmap-coturn-conf-template.yaml, charts/coturn/templates/secret-or-certificate.yaml, charts/coturn/templates/statefulset.yaml, charts/coturn/values.yaml
This is mostly inspired by the restund Helm chart.
Why is this a draft? Because, we haven't finished testing `coturn` on dogfood environments and may need more changes.
There's a related PR in `cailleach`: https://github.com/zinfra/cailleach/pull/1648
=> coturn: Add federation and DTLS support to Helm chart

docs/src/how-to/install/post-install.md
The website does currently not hold a privacy whitepaper section -> link directly to the pdf
=> fix: link to correct privacy whitepaper

services/brig/src/Brig/App.hs, services/brig/src/Brig/Federation/Client.hs, services/brig/src/Brig/Options.hs
It is only required when federation is enabled.
=> brig: Make RabbitMQ config optional

.envrc, Makefile, charts/integration/templates/integration-integration.yaml, charts/integration/values.yaml, integration/scripts/integration-dynamic-backends-brig-index.sh, integration/scripts/integration-dynamic-backends-db-schemas.sh, nix/wire-server.nix
This PR sets up separate cassandra schemas and ES indices to be used by integration tests.
The number of backends can be controlled by `INTEGRATION_DYNAMIC_BACKENDS_POOLSIZE` for the local dev environment and `config.dynamicBackendsPoolsize` in the `integration` helm chart.
The db schemas will be named `brig_test_dyn_X`, `galley_test_dyn_X`, etc; the ES index is named `directory_dyn_X_test`, where `X` ranges from 1 to the poolsize.
=> FS-1959: Setup schemas and ES indices for dynamic backend tests

services/galley/src/Galley/Cassandra/TeamFeatures.hs
This was a merge mistake that is fixed now. No changelog.
=> Fix: Use the mls_migration_lock_status DB column when storing the MLS migration status

hack/bin/python3.sh, integration/scripts/integration-dynamic-backends-brig-index.sh, integration/scripts/integration-dynamic-backends-db-schemas.sh, nix/wire-server.nix
I've tested that scripts with
```
#!/usr/bin/env bash
```
(or `sh`) will use the interpreter in `.env/bin/bash` (or `.env/bin/sh`). Even though in my shell `which bash` doesn't point to the executable in `.env/bin`.
=> Add bash/sh interpreters to development environment

changelog.d/4-docs/pr-3319-swagger-named-names, docs/src/developer/developer/servant.md, docs/src/understand/api-client-perspective/swagger.md, libs/wire-api/src/Wire/API/Routes/Named.hs, libs/wire-api/src/Wire/API/Team/Feature.hs
This should make jumping from swagger docs into the source code by grepping for the ID much easier.
=> Render `Named` names as "internal route ID" in swagger UI.

Makefile
This should restore the previous behaviour of calling a bare `make ci`.
=> [chore] Add default suite to make ci

changelog.d/0-release-notes/background-worker, charts/galley/templates/configmap.yaml, charts/galley/templates/deployment.yaml, charts/galley/templates/secret.yaml, charts/galley/templates/tests/galley-integration.yaml, charts/galley/values.yaml, hack/helm_vars/wire-server/values.yaml.gotmpl, libs/wire-api/src/Wire/API/Routes/Internal/Galley.hs, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs, services/brig/src/Brig/App.hs, services/brig/test/integration/API/User/Handles.hs, services/galley/default.nix, services/galley/galley.cabal, services/galley/galley.integration.yaml, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/App.hs, services/galley/src/Galley/Effects.hs, services/galley/src/Galley/Effects/BackendNotificationQueueAccess.hs, services/galley/src/Galley/Env.hs, services/galley/src/Galley/Intra/BackendNotificationQueue.hs, services/galley/src/Galley/Options.hs, services/galley/test/integration/API.hs
https://wearezeta.atlassian.net/browse/WPB-200
Also includes some fixups for #3276 (all brig related changes are fixups)
=> galley: Send on-user-deleted-conversations backend notification through RabbitMQ

deploy/dockerephemeral/docker-compose.yaml
Follow-up to https://github.com/wireapp/wire-server/pull/3350 which seems accidentaly increased -Xms3806 instead of the intended 1GB. The name of the environment variable was not correct in the original PR
=> Develop cassndra: use only 1GB instead of 4GB of heap

libs/extended/src/Network/AMQP/Extended.hs, services/background-worker/src/Wire/BackgroundWorker/Options.hs, services/brig/src/Brig/App.hs, services/brig/src/Brig/Options.hs, services/galley/src/Galley/App.hs, services/galley/src/Galley/Env.hs, services/galley/src/Galley/Options.hs
=> Extract RabbitMQOpts and the function to create channel in extended

integration/test/Test/MLS/One2One.hs, libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs, libs/wire-api-federation/src/Wire/API/Federation/Error.hs, services/galley/galley.cabal, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/MLS/One2One.hs, services/galley/src/Galley/API/Query.hs
- Fetch 1-1 conversation from database if present
- Get conversation from the other backend when the conversation is supposed to be remote
=> More general MLS 1-1 conversation GET handler

changelog.d/5-internal/WPB-1925, integration/test/API/Galley.hs, integration/test/Test/MLS.hs, libs/wire-api/src/Wire/API/Conversation.hs, libs/wire-api/src/Wire/API/MLS/Group.hs, libs/wire-api/src/Wire/API/MLS/Group/Serialisation.hs, libs/wire-api/src/Wire/API/Routes/Internal/Galley.hs, libs/wire-api/test/unit/Test/Wire/API/MLS/Group.hs, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/MLS/One2One.hs, services/galley/src/Galley/API/MLS/SubConversation.hs, services/galley/src/Galley/API/MLS/Util.hs, services/galley/src/Galley/Cassandra/Conversation.hs, services/galley/src/Galley/Effects/ConversationStore.hs, services/galley/test/integration/API/MLS.hs, services/galley/test/integration/API/MLS/Util.hs, services/galley/test/integration/API/Util.hs
=> add conversation type to group ID serialisation

charts/cannon/templates/conf/_nginx.conf.tpl, charts/cannon/values.yaml, charts/nginz/templates/conf/_nginx.conf.tpl, charts/nginz/values.yaml, nix/nginz-disco.nix, nix/nginz.nix, nix/wire-server.nix
Containers now run as non-root, to improve compatibility with default PodSecurityPolicies in more recent versions of Kubernetes.
This is part of [WPB-1234](https://wearezeta.atlassian.net/browse/WPB-1234)
[WPB-1234]: https://wearezeta.atlassian.net/browse/WPB-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Run containers as non-root

changelog.d/5-internal/containers-nonroot
This was missed to stage during #3352.
=> add missing changelog for nonroot containers

changelog.d/5-internal/mls-subconv-creation, integration/integration.cabal, integration/test/API/Galley.hs, integration/test/MLS/Util.hs, integration/test/Test/MLS.hs, integration/test/Test/MLS/SubConversation.hs, services/galley/src/Galley/API/MLS/Commit/ExternalCommit.hs, services/galley/src/Galley/API/MLS/Commit/InternalCommit.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/API/MLS/SubConversation.hs, services/galley/src/Galley/API/MLS/Types.hs, services/galley/src/Galley/Cassandra/SubConversation.hs, services/galley/src/Galley/Effects/SubConversationStore.hs, services/galley/test/integration/API/MLS.hs
This PR changes the way subconversations are created to be consistent with the approach used for MLS 1-1 conversations. Namely, instead of the GET endpoint creating the conversation when it doesn't exist, creation happens within the commit lock of the first commit.
This also fixes a latent race condition where one thread could "create" an existing conversation which had already progressed to epoch 1, thereby resetting its epoch to 0 and breaking it.
https://wearezeta.atlassian.net/browse/WPB-1927
=> Create subconversations on first commit

charts/brig/templates/deployment.yaml, charts/brig/values.yaml
The geoipupdate image runs as root by default, preventing brig from starting up. Here we upgrade image version & set user=geoipupdate=1000
This change was tested manually. CI does not have geopip enabled, as that would require credentials. (hence this problem only appeared during deployment).
=> Fixup to brig chart from #3351 when geoip enabled

changelog.d/5-internal/better-golden-errors, libs/wire-api/default.nix, libs/wire-api/test/golden/Test/Wire/API/Golden/Runner.hs, libs/wire-api/wire-api.cabal
before:
```
testObject_RichInfoMapAndList_user_19.json: FAIL
Error message: RichInfoMapAndList: ToJSON should match golden file: testObject_RichInfoMapAndList_user_19.json
expected: Object (fromList [("urn:ietf:params:scim:schemas:extension:wire:1.0:User",Object (fromList [("\DC3\DC2\1026333vS\t\NUL\DC4\1073519<\EM\539\DLE<\NULxR\SUBU\FSx\SYN\\JtiN?&\1092138",String "\1000631\1058954x\23412\&3\n\18517\1040637\20472\r0e\DLE\1029504"),("l%\35922\ACK\DC4b\82954\119943\EM$\1011647\&5~f\37664H",String "d\34056\1074598)A\18354k@\SUB\1097784<\1054362\132080I\1003614\DC1}:\SYN\1085924\994398$\v\EM\DC2&OMW")])),("urn:wire:scim:schemas:profile:1.0",Object (fromList [("wrongName",Object (fromList [("fields",Array [Object (fromList [("type",String …
```
=> Better errors in golden tests.

changelog.d/5-internal/dont-return-to-sender, integration/test/Test/MLS.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/API/MLS/Propagate.hs, services/galley/src/Galley/API/MLS/Removal.hs, services/galley/test/integration/API/MLS.hs
=> Avoid MLS messages in sender client's event stream

hack/bin/create-user
This PR creates adds a script that can create a users on testing environments using the basicauth method.
```
usage: ./hack/bin/create-user [-h] [-e ENV] [-n]
Create a user on a testing environment.
options:
-h, --help         show this help message and exit
-e ENV, --env ENV  One of: staging, anta, bella, chala, foma, ninjas, pirates, unicorns. Default: staging.
-n, --no-team      Don't create a team admin, but a personal user.
```
=> Add testing script "create-user"

changelog.d/0-release-notes/background-worker, charts/background-worker/templates/configmap.yaml, charts/background-worker/values.yaml, hack/helm_vars/wire-server/values.yaml.gotmpl, hack/helmfile.yaml, libs/extended/default.nix, libs/extended/extended.cabal, libs/extended/src/Network/AMQP/Extended.hs, libs/extended/src/Network/RabbitMqAdmin.hs, nix/haskell-pins.nix, services/background-worker/background-worker.cabal, services/background-worker/background-worker.integration.yaml, services/background-worker/default.nix, services/background-worker/src/Wire/BackendNotificationPusher.hs, services/background-worker/src/Wire/BackgroundWorker.hs, services/background-worker/src/Wire/BackgroundWorker/Env.hs, services/background-worker/src/Wire/BackgroundWorker/Options.hs, services/background-worker/test/Test/Wire/BackendNotificationPusherSpec.hs
https://wearezeta.atlassian.net/browse/WPB-1130
=> backend-notification-pusher: Dynamically discover remote domains

changelog.d/0-release-notes/supported-protocols, changelog.d/2-features/supported-protocols, charts/galley/values.yaml, libs/wire-api/src/Wire/API/Conversation/Protocol.hs, libs/wire-api/src/Wire/API/Error/Galley.hs, libs/wire-api/src/Wire/API/Team/Feature.hs, services/galley/galley.cabal, services/galley/galley.integration.yaml, services/galley/schema/src/Run.hs, services/galley/schema/src/V85_TeamFeatureSupportedProtocols.hs, services/galley/src/Galley/API/Teams/Features.hs, services/galley/src/Galley/App.hs, services/galley/src/Galley/Cassandra/TeamFeatures.hs, services/galley/test/integration/API/Teams/Feature.hs
=> Add supportedProtocols field to mls feature config

changelog.d/2-features/multi-ingress-support-nginx-ingress-services, charts/nginx-ingress-services/templates/ca_federator.yaml, charts/nginx-ingress-services/templates/certificate_federator.yaml, charts/nginx-ingress-services/templates/ingress.yaml, charts/nginx-ingress-services/templates/ingress_federator.yaml, charts/nginx-ingress-services/templates/issuer.yaml, charts/nginx-ingress-services/templates/secret_federator.yaml, charts/nginx-ingress-services/templates/service.yaml, charts/nginx-ingress-services/values.yaml
Render additional K8s objects for additional backend domains ("multi-ingress").
The best entry to this PR is the `values.yaml` file which shows the new configuration settings: https://github.com/wireapp/wire-server/pull/3375/files#diff-6752e60cbd59fb7f3c26228bae9955905976750f391ce424ac849ce0450432abR45
=> multi ingress ingress services

libs/wire-api/src/Wire/API/FederationUpdate.hs
Also avoid logging asynchronous exceptions (such as the thread being
killed by a signal).
This prevents spurious error log messages while running tests.
=> Rework federator domain sync loop

changelog.d/0-release-notes/pr-3260
The changelog for #3260 wasn't very exhaustive, here's an improved version.
=> Tweak changelog.

changelog.d/0-release-notes/pr-3260, charts/cannon/templates/configmap.yaml, services/cannon/cannon.integration.yaml, services/cannon/cannon2.integration.yaml, services/cannon/src/Cannon/Options.hs, services/cannon/src/Cannon/Run.hs
https://wearezeta.atlassian.net/browse/WPB-2942
=> Remove dead code from cannon.

changelog.d/2-features/multi-ingress-support-nginx-ingress-services, charts/nginx-ingress-services/templates/ca_federator.yaml, charts/nginx-ingress-services/templates/certificate_federator.yaml, charts/nginx-ingress-services/templates/ingress.yaml, charts/nginx-ingress-services/templates/ingress_federator.yaml, charts/nginx-ingress-services/templates/issuer.yaml, charts/nginx-ingress-services/templates/secret_federator.yaml, charts/nginx-ingress-services/templates/service.yaml, charts/nginx-ingress-services/values.yaml
Reverts wireapp/wire-server#3375
Staging deployment was broken because of conflicting ingresses.
https://concourse.ops.zinfra.io/teams/main/pipelines/staging/jobs/deploy-eks-staging/builds/512
Probably, the name for the default ingress has to stay the same.
=> Revert "multi ingress ingress services"

libs/wire-api/src/Wire/API/FederationUpdate.hs
https://wearezeta.atlassian.net/browse/WPB-3007
timing of `./services/run-services date`:
- without fix, with federation enabled: `real 0m7.475s`
- without fix, with federation disabled: `real 0m3.912s`
- with fix, with federation enabled: `real 0m2.934s`
- with fix, with federation disabled: `real 0m1.659s`
=> Tweak retry policy for pulling federation remotes from brig.

changelog.d/2-features/multi-ingress-support-nginx-ingress-services, charts/nginx-ingress-services/templates/_helpers.tpl, charts/nginx-ingress-services/templates/ca_federator.yaml, charts/nginx-ingress-services/templates/certificate.yaml, charts/nginx-ingress-services/templates/certificate_federator.yaml, charts/nginx-ingress-services/templates/ingress.yaml, charts/nginx-ingress-services/templates/ingress_federator.yaml, charts/nginx-ingress-services/templates/issuer.yaml, charts/nginx-ingress-services/templates/secret_federator.yaml, charts/nginx-ingress-services/templates/service.yaml, charts/nginx-ingress-services/values.yaml
Brings back the changes reverted with https://github.com/wireapp/wire-server/pull/3399 (which reverted https://github.com/wireapp/wire-server/pull/3375 .)
Add backwards compatibility to existing deployments by ensuring that the existing ingress is replaced when the default settings are applied. This happens by using the same name.
(Helm isn't smart enough to understand that the ingress had a changed name.)
=> Re-revert: multi ingress ingress services

changelog.d/0-release-notes/domain-sync-thread-cleanup, charts/gundeck/templates/configmap.yaml, libs/wire-api/src/Wire/API/FederationUpdate.hs, services/galley/src/Galley/App.hs, services/galley/src/Galley/Env.hs, services/galley/src/Galley/Run.hs, services/galley/test/integration/API/Util.hs, services/gundeck/gundeck.integration.yaml, services/gundeck/src/Gundeck/Options.hs, services/gundeck/src/Gundeck/Run.hs
- Remove the domain sync thread from galley and gundeck.
- Remove the brig config value from gundeck.
=> Removing domain sync threads where not currently used.

changelog.d/gundeck-integration-test-docs
This probably should have gotten into one of the subdirectories (internal maybe), but considering the PR was already released, there's no point including this in a future changelog, so best to just remove it now.
=> changelog: drop changelog.d/gundeck-integration-test-docs

hack/bin/performance.py, hack/python/wire/api.py, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/MLS/Propagate.hs, services/galley/src/Galley/API/MLS/Welcome.hs
This PR changes the way welcomes and all mls messages are stored for fanned out to recipients in gundeck: Message payloads are only saved once per push:
https://github.com/wireapp/wire-server/pull/3403
=> Make use of deduplication for MLS

integration/test/Testlib/ModService.hs, integration/test/Testlib/RunServices.hs
gundeck-integration assumes `AWS_` variables to be set. Without this PR some tests fail
=> Fix run-services: Binaries started not with AWS_ variables set

Makefile
=> Introduce `make ci-fast`, `make ci-safe`.

changelog.d/2-features/remove-indexed-billing-members-feature, charts/galley/templates/configmap.yaml, charts/galley/values.yaml, docs/src/developer/reference/config-options.md, flaky-tests.yaml, hack/helm_vars/wire-server/values.yaml.gotmpl, services/galley/galley.integration.yaml, services/galley/src/Galley/API/Teams.hs, services/galley/src/Galley/App.hs, services/galley/src/Galley/Intra/Journal.hs, services/galley/src/Galley/Options.hs, services/galley/test/integration/API/Teams.hs
No release notes necessary because the only affected deployment is Wire Cloud (on-prem don't track billing) which has this feature flag already enabled.
=> WPB 2565 remove indexed billing members feature flag

tools/stern/src/Stern/Intra.hs
[WPB-2888](https://wearezeta.atlassian.net/browse/WPB-2888)
We observed failed requests to galley with batch size = 100 for the user: 241f3fc8-f022-46b3-8c6e-21d0bf297da9
This might be caused by the size of the returning payload for this user.
According to SWAG best practise batch=50 might help
[WPB-2888]: https://wearezeta.atlassian.net/browse/WPB-2888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Stern: Reduce batch size to 50 when GetNotifications

hack/helm_vars/ingress-nginx-controller/values.yaml.gotmpl
According to https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml#L1, this flag is under controller.admissionWebhooks, not controller.service.admissionWebhooks. Fix yaml indentation.
=> yaml indentation: do not create ingress webhooks on CI runs

services/galley/test/integration/API.hs
Making the defederation notification tests run last.
If these tests run in parallel with other tests, it will cause them to break because it is sending a notification to every registered client. The other tests don't know how to deal with these notifications, so they break. Running this last will sidestep that issue.
=> WPB-240: Fixing tests by making defederation tests run last.

changelog.d/5-internal/ci-redis-ephemeral, hack/helm_vars/wire-server/values.yaml.gotmpl, hack/helmfile.yaml
We wish to avoid needing persistence during CI runs, as we run into limits of volume creation, which causes integration test setup failures.
This PR can be reverted at some point in the future when:
- hedis code is both compatible with current redis version AND redis version 7 and its tests pass, and it is released to hackage / nixpkgs.
- (or temporarily if you make changes to redis and/or redis code in gundeck and wish to test these changes on CI)
Then:
- Step 1. We can use latest hedis code (and merge this to develop, ensuring this works on staging)
- Step 2: Subsequently this PR can be reverted, and the redis-cluster helm chart bumped, and persistence disabled. See also #3444
- ensure to do steps 1 and 2 on *separate* PRs, to avoid requiring a redis helm chart update concurrently with …
=> In CI, use redis-ephemeral master mode

changelog.d/3-bug-fixes/sender-welcome, integration/test/Test/MLS.hs, services/galley/src/Galley/API/MLS/Message.hs
This fixes a bug where welcome messages were sent to the creator of a group on the first commit.
=> Welcome messages should not be sent to creator

changelog.d/1-api-changes/connection-update, libs/wire-api/src/Wire/API/User.hs
This fixes an integration test failure on develop.
Note that the change breaks the format of the request body for one internal Brig endpoint. The previous format included a heterogenous JSON array, which is currently not supported by schema-profunctor.
=> Implement schema for UpdateConnectionsInternal

integration/test/Testlib/JSON.hs
Add support for selecting elements of JSON arrays in the integration test suite.
=> Array support in JSON selectors

services/brig/brig.integration.yaml, services/brig/test/integration/API/Federation.hs, services/brig/test/integration/API/User/Auth.hs, services/brig/test/integration/Util.hs
I'm double-fixing this because i don't want to think about the legacy integration tests any more.  The `recoverAll` is probably not needed, but I don't see how it hurts either.
=> Make flaky test less flaky.

changelog.d/2-features/pr-3460, services/galley/src/Galley/API/Message.hs, services/galley/test/integration/API.hs
https://wearezeta.atlassian.net/browse/WPB-3394
This is an update to https://github.com/wireapp/wire-server/pull/3460
Users that are in `failed_to_send` are now also included in `failed_to_confirm_clients`.
No need to update change log.
=> [WPB-3394] Sending proteus messages when a remote backend is offline (update)

changelog.d/2-features/mls-conv-limits, hack/python/wire/mlscli.py, libs/wire-api/src/Wire/API/Team/Member.hs, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Update.hs, services/galley/src/Galley/API/Util.hs, services/galley/src/Galley/Data/Conversation/Types.hs
https://wearezeta.atlassian.net/browse/WPB-2940
=> MLS conversation limits

changelog.d/3-bug-fixes/pr-3477, changelog.d/6-federation/pr-3477, services/galley/src/Galley/API/Internal.hs
if the main defederation background process fails to remove a remote conversation because it's already gone, it crashes, gives the job back to rabbitMQ, and picks it up again immediately.  this PR avoids this particular situation by gracefully ignoring already-removed conversations.
there are more exceptions that can lead to crash loops, work in progress in https://github.com/wireapp/wire-server/pull/3477 and by @lepsa.
https://wearezeta.atlassian.net/browse/WPB-3631
=> Fix defederate loop - the easy part

changelog.d/3-bug-fixes/WPB-3665, changelog.d/6-federation/WPB-3665, services/federator/src/Federator/ExternalServer.hs
https://wearezeta.atlassian.net/browse/WPB-3665
=> Do not accept federation traffic from not-federating backends.

changelog.d/1-api-changes/no-partial-success-in-creating-conv, libs/wire-api-federation/src/Wire/API/Federation/Error.hs, libs/wire-api/src/Wire/API/Conversation.hs, libs/wire-api/src/Wire/API/Routes/Internal/Galley.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/Conversation.hs, services/federator/src/Federator/MockServer.hs, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Create.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/Util.hs, services/galley/src/Galley/Data/Types.hs, services/galley/test/integration/API.hs, services/galley/test/integration/API/Federation/Util.hs, services/galley/test/integration/API/Util.hs
Instead of partially succeeding when creating a Proteus conversation with unreachable remote users, now the `POST /conversations` endpoint returns a 503 error listing unreachable backends, as documented at https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/28837389/Use+Case+Create+a+group+conversation.
Tracked by https://wearezeta.atlassian.net/browse/WPB-3640.
=> [WPB-3640] Disallow partial success and fix reporting of unreachable backends when creating a Proteus conversation

changelog.d/3-bug-fixes/pr-3485, integration/test/API/Brig.hs, integration/test/API/Galley.hs, integration/test/Test/Conversation.hs, integration/test/Testlib/Assertions.hs, integration/test/Testlib/Cannon.hs, services/brig/src/Brig/API/Internal.hs, services/galley/src/Galley/API/Internal.hs
https://wearezeta.atlassian.net/browse/WPB-3633
=> [WPB-3633] client receives conversation deleted conversation events after federation delete event

changelog.d/3-bug-fixes/WPB-2959-fix-roles-in-scim, libs/wire-api/src/Wire/API/User/Scim.hs, services/spar/src/Spar/Scim/User.hs, services/spar/test-integration/Test/Spar/APISpec.hs, services/spar/test-integration/Test/Spar/Scim/UserSpec.hs, services/spar/test-integration/Util/Scim.hs
https://wearezeta.atlassian.net/browse/WPB-2959
reviewer: please read commit by commit.
without the fix, but with the test:
```
$ make ci-safe package=spar
[...]
test-integration/Test/Spar/Scim/UserSpec.hs:1810:7:
1) WireIdPAPIV1.Spar.Scim.User, PUT /Users/:id, updates role
expected: Just RoleOwner
but got: Just RoleMember
To rerun use: --match "/WireIdPAPIV1/Spar.Scim.User/PUT /Users/:id/updates role/"
test-integration/Test/Spar/Scim/UserSpec.hs:1810:7:
2) WireIdPAPIV2.Spar.Scim.User, PUT /Users/:id, updates role
expected: Just RoleOwner
but got: Just RoleMember
To rerun use: --match "/WireIdPAPIV2/Spar.Scim.User/PUT /Users/:id/updates role/"
[...]
```
with both:
```
$ make ci-safe package=spar
[...]
WireIdPAPIV1
Spar.Scim.User
PUT /Users/:id
updates role [✔]
[...]
```
=> Fix SCIM role update

integration/test/Testlib/HTTP.hs
=> Add missing HasCallStack to getJSON, getBody

changelog.d/1-api-changes/WPB-2542, changelog.d/1-api-changes/WPB-3640, integration/test/Test/Conversation.hs, libs/wai-utilities/src/Network/Wai/Utilities/Error.hs, libs/wai-utilities/src/Network/Wai/Utilities/Server.hs, libs/wire-api-federation/default.nix, libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs, libs/wire-api-federation/src/Wire/API/Federation/Client.hs, libs/wire-api-federation/src/Wire/API/Federation/Error.hs, libs/wire-api-federation/wire-api-federation.cabal, libs/wire-api/src/Wire/API/Conversation.hs, libs/wire-api/src/Wire/API/Error/Galley.hs, libs/wire-api/src/Wire/API/Routes/Internal/Galley.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/Conversation.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/MLS.hs, services/brig/docs/swagger.md, services/brig/test/integration/API/User/Account.hs, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Create.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/API/Update.hs, services/galley/src/Galley/API/Util.hs, services/galley/test/integration/API.hs, services/galley/test/integration/API/Federation.hs
This PR introduces an `UnreachableBackends` error type which behaves similarly to `NonFederatingBackends` from https://github.com/wireapp/wire-server/pull/3483.
https://wearezeta.atlassian.net/browse/WPB-3640
=> Turn UnreachableBackends response into a Polysemy error

hack/bin/create-user
=> Add 7 more envs to create-user script

changelog.d/1-api-changes/WPB-3640, integration/test/Test/Conversation.hs, libs/wire-api/src/Wire/API/Error/Galley.hs, services/galley/test/integration/API.hs
To avoid alerting instance operators in case a remote backend is unreachable, change the error status code when creating a conversation or adding members from 503 to 533.
Tracked by https://wearezeta.atlassian.net/browse/WPB-3865.
=> [WPB-3865] Conversation creation and member adding: change error response status code to 533

changelog.d/2-features/mls-stale-app-messages, integration/test/Test/MLS.hs, services/galley/src/Galley/API/MLS/Message.hs
An application message is considered stale if its epoch is 2 or more epochs behind the current epoch. This PR makes it so that stale application messages are rejected. Note that proposal message are still stale as soon as their epoch is older than the current one.
https://wearezeta.atlassian.net/browse/WPB-505
=> Reject stale application messages

integration/test/Testlib/ModService.hs
This PR fixes a bug in `integration` where the federator host is incorrect for dyamic backends.
With this PR the test `testDefederationNonFullyConnectedGraph` can be added again and passes on CI.
=> Fix bug in integration: federator host is not set

charts/background-worker/values.yaml, deploy/dockerephemeral/init_vhosts.sh, hack/bin/integration-test.sh, hack/helm_vars/common.yaml.gotmpl, hack/helm_vars/wire-server/values.yaml.gotmpl, hack/helmfile.yaml, integration/default.nix, integration/integration.cabal, integration/test/API/Brig.hs, integration/test/API/Galley.hs, integration/test/Notifications.hs, integration/test/SetupHelpers.hs, integration/test/Test/Federation.hs, integration/test/Testlib/Assertions.hs, integration/test/Testlib/Cannon.hs, integration/test/Testlib/HTTP.hs, integration/test/Testlib/JSON.hs, integration/test/Testlib/ModService.hs, integration/test/Testlib/RunServices.hs, integration/test/Testlib/Types.hs, services/background-worker/background-worker.integration.yaml, services/background-worker/src/Wire/BackendNotificationPusher.hs, services/background-worker/src/Wire/BackgroundWorker/Env.hs, services/background-worker/src/Wire/BackgroundWorker/Options.hs, services/background-worker/test/Test/Wire/BackendNotificationPusherSpec.hs, services/background-worker/test/Test/Wire/Util.hs, services/brig/src/Brig/API/Federation.hs
Tracked by https://wearezeta.atlassian.net/browse/WPB-2890.
=> integration: Add test to verify behaviour with offline backends

changelog.d/3-bug-fixes/WPB-3842-federation-completeness-checks, integration/test/Test/Conversation.hs, integration/test/Testlib/Run.hs, services/galley/src/Galley/API/Action.hs
- Improving the completeness check for federation sub-graphs that are or will be involved in a given conversation.
- Updating tests that were relying on the old semantics where exiting domains in a conversation weren't considered in the completeness check.
- Adding the test from the Jira ticket, thanks @pcapriotti!
=> Wpb 3842 federation completeness check

integration/test/API/BrigInternal.hs, integration/test/API/Galley.hs, integration/test/Test/Conversation.hs, integration/test/Test/Federation.hs, integration/test/Testlib/HTTP.hs
https://wearezeta.atlassian.net/browse/WPB-3974
=> integration: Fix testAddingUserNonFullyConnectedFederation and testNotificationsForOfflineBackends

changelog.d/5-internal/optimize-stern, tools/stern/src/Stern/API.hs, tools/stern/src/Stern/Intra.hs
https://wearezeta.atlassian.net/browse/WPB-2888
=> stern: Optimize RAM usage of /i/users/meta-info

integration/integration.cabal, integration/test/API/Cargohold.hs, integration/test/API/GalleyInternal.hs, integration/test/SetupHelpers.hs, integration/test/Test/AssetDownload.hs, integration/test/Test/Brig.hs, integration/test/Test/Conversation.hs, integration/test/Test/Defederation.hs, integration/test/Test/Demo.hs, integration/test/Test/Federation.hs, integration/test/Testlib/App.hs, integration/test/Testlib/Cannon.hs, integration/test/Testlib/Env.hs, integration/test/Testlib/HTTP.hs, integration/test/Testlib/ModService.hs, integration/test/Testlib/Ports.hs, integration/test/Testlib/Prelude.hs, integration/test/Testlib/ResourcePool.hs, integration/test/Testlib/Run.hs, integration/test/Testlib/RunServices.hs, integration/test/Testlib/Service.hs, integration/test/Testlib/Types.hs
This PR changes the `integration` test suite:
- changes random port allocation to fixed ports for all services. This should reduce some flakiness caused by re-using radom ports.
- removes `withModifiedService(s)`: force all overriding backend configuration override testing to run in separated backends (`withModifiedBackend`)
This PR also heavily refactors the `ModService` module with the goal of simplification: duplication and lots of arguments are removed, `ServiceOverrides` is used everywhere instead of maps.
=> Integration tests: use static ports

services/brig/test/integration/API/Federation.hs, services/brig/test/integration/Util.hs
https://wearezeta.atlassian.net/browse/WPB-3974
=> brig-integration: Fix flaky tests for API.Federation

changelog.d/1-api-changes/mls-x509, integration/test/MLS/Util.hs, integration/test/Test/MLS.hs, integration/test/Test/MLS/KeyPackage.hs, integration/test/Test/MLS/One2One.hs, integration/test/Test/MLS/SubConversation.hs, libs/wire-api/src/Wire/API/MLS/Credential.hs, libs/wire-api/src/Wire/API/MLS/KeyPackage.hs, libs/wire-api/src/Wire/API/MLS/Validation.hs, nix/pkgs/mls-test-cli/default.nix
This PR adds minimal support for x509 credentials in MLS.
At the moment, this is based on the `x509` branch of `mls-test-cli`. 
https://wearezeta.atlassian.net/browse/WPB-3787
=> Support x509 credentials

integration/test/Testlib/ModService.hs
=> Integration suite: Fix bug in local setup: wrong port for nginz http2

integration/test/API/Brig.hs, integration/test/MLS/Util.hs, integration/test/Test/MLS/KeyPackage.hs, services/brig/test/integration/API/MLS.hs
Simply moved some key package tests to the new integration suite, and made them parametric in the ciphersuite.
https://wearezeta.atlassian.net/browse/WPB-4297
=> Move key package upload tests to new suite

changelog.d/2-features/mls-x509-improvements, libs/wire-api/src/Wire/API/MLS/KeyPackage.hs, libs/wire-api/src/Wire/API/MLS/Validation.hs, nix/pkgs/mls-test-cli/default.nix
Followup to #3532.
See corresponding change in mls-test-cli: https://github.com/wireapp/mls-test-cli/commit/e6e6ce0c29f0e48e84b4ccef058130aca0625492.
https://wearezeta.atlassian.net/browse/WPB-3787
=> Validate public key in an x509 credential

changelog.d/5-internal/WPB-4406, changelog.d/6-federation/FOO, libs/wai-utilities/src/Network/Wai/Utilities/Error.hs, libs/wai-utilities/src/Network/Wai/Utilities/Server.hs, libs/wire-api-federation/src/Wire/API/Federation/Client.hs, libs/wire-api-federation/src/Wire/API/Federation/Error.hs, services/federator/default.nix, services/federator/src/Federator/InternalServer.hs, services/federator/src/Federator/Remote.hs, services/federator/test/integration/Test/Federator/IngressSpec.hs, services/federator/test/unit/Test/Federator/InternalServer.hs, services/federator/test/unit/Test/Federator/Remote.hs, services/federator/test/unit/Test/Federator/Response.hs
- Adding a response field to `Network.Wai.Utilities.ErrorData` to hold responses, if they exist.
- Extending federation error functions to track paths and responses.
- Added a no-op metrics interpreter for the testing frameworks.
- Logging all outbound calls in federator. This is set at the debug log level.
=> WPB-4406 federator logging

changelog.d/5-internal/notification-500, integration/test/SetupHelpers.hs, integration/test/Test/Notifications.hs, libs/wire-api/src/Wire/API/Notification.hs, services/gundeck/src/Gundeck/Monad.hs, services/gundeck/src/Gundeck/Notification.hs
UUIDs passed as the `since` parameter of `GET /notifications` should be v1. Before this PR, passing a UUID of the wrong version would result in a 500. With this change, the UUID is validated and a 400 is returned if its version is not 1.
=> Check validity of notification IDs

changelog.d/5-internal/WPB-663, libs/types-common/src/Data/Range.hs, libs/wire-api/src/Wire/API/Provider/Service.hs, libs/wire-api/src/Wire/API/Provider/Service/Tag.hs, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs, services/brig/src/Brig/API/Public.hs, services/brig/src/Brig/Provider/API.hs, services/brig/src/Brig/Team/API.hs
Migrating routes to servant
Adding instances where needed to make servant happy
=> WPB-633 Servantify Brig/Provider.Service API

changelog.d/3-bug-fixes/WPB-4425-fix-es-migration-script, services/brig/src/Brig/Index/Migrations.hs
https://wearezeta.atlassian.net/browse/WPB-4425
=> Fix ES migration script.

changelog.d/5-internal/WPB-4406, integration/integration.cabal, integration/test/API/Federator.hs, integration/test/Test/Federator.hs, libs/wai-utilities/src/Network/Wai/Utilities/Error.hs, libs/wai-utilities/src/Network/Wai/Utilities/Server.hs, libs/wire-api-federation/src/Wire/API/Federation/Client.hs, libs/wire-api-federation/src/Wire/API/Federation/Error.hs, services/federator/default.nix, services/federator/federator.cabal, services/federator/src/Federator/Env.hs, services/federator/src/Federator/ExternalServer.hs, services/federator/src/Federator/InternalServer.hs, services/federator/src/Federator/Metrics.hs, services/federator/src/Federator/Remote.hs, services/federator/src/Federator/Response.hs, services/federator/src/Federator/Run.hs, services/federator/test/integration/Test/Federator/IngressSpec.hs, services/federator/test/unit/Test/Federator/ExternalServer.hs, services/federator/test/unit/Test/Federator/InternalServer.hs, services/federator/test/unit/Test/Federator/Remote.hs, services/federator/test/unit/Test/Federator/Response.hs
https://wearezeta.atlassian.net/browse/WPB-4406
=> [WPB-4406] federator improve logging

Makefile
Backticks execute the command even when they are in quotes.
=> Makefile: Avoid executing the hint

libs/wire-api/src/Wire/API/User/IdentityProvider.hs, services/spar/test-integration/Test/Spar/APISpec.hs, services/spar/test-integration/Util/Core.hs, services/spar/test-integration/Util/Scim.hs
https://wearezeta.atlassian.net/browse/WPB-3530
this only adds a set of integration test with one failing (and thus deactivated) instance.  fix coming up in #3563, but i'd rather merge this now and keep the other PR smaller.
=> Fix: SCIM user lookup after changing IdP issuer ID

docs/src/developer/reference/config-options.md
=> doc: document webapp configuration for multi-ingress environments

changelog.d/5-internal/pr-3572, libs/jwt-tools/test/Spec.hs, nix/overlay.nix, nix/pkgs/rusty_jwt_tools_ffi/default.nix, nix/sources.json, services/brig/brig.cabal, services/brig/default.nix, services/brig/test/integration/API/User/Client.hs
=> WPB-4361 upgrade jwt tools in wire server

libs/wire-api/src/Wire/API/Routes/Public/Galley/Conversation.hs, services/brig/docs/swagger-v4.json
This PR removes some remaining MLS endpoints (only present in the mls branch) from v4 and regenerates the v4 swagger documentation.
=> Remove MLS endpoints from v4 in the mls branch

charts/fake-aws-s3/requirements.yaml, charts/fake-aws-s3/values.yaml, deploy/dockerephemeral/docker-compose.yaml
This PR upgrades the minio chart version from `3.2.0` to `5.0.13` in the `fake-aws-s3` chart.
This amounts to upgrading from https://github.com/minio/minio/commit/082755de1a436c63a06793541b29b08701161fcc to https://github.com/minio/minio/commit/af3d99e35fe6e811bb3cb191bed604c7ca471bb2 (diff 
https://github.com/minio/minio/compare/082755d...af3d99e), a upgrade to `RELEASE.2023-07-07T07-13-57Z`
=> fake-aws-s3 chart: Upgrade to minio 5.0.13

changelog.d/4-docs/WPB-4556-internal-user-creation, docs/src/understand/block-user-creation.md, hack/bin/create_test_team_admins.sh
https://wearezeta.atlassian.net/browse/WPB-4556
=> [WPB-4556] document internal user creation

changelog.d/6-federation/tcp-timeout, charts/federator/templates/configmap.yaml, charts/federator/values.yaml, libs/http2-manager/src/HTTP2/Client/Manager.hs, libs/http2-manager/src/HTTP2/Client/Manager/Internal.hs, services/federator/federator.integration.yaml, services/federator/src/Federator/Env.hs, services/federator/src/Federator/Options.hs, services/federator/src/Federator/Run.hs, services/federator/test/unit/Test/Federator/Options.hs, services/federator/test/unit/Test/Federator/Remote.hs
https://wearezeta.atlassian.net/browse/WPB-4792
Defaults to 5s in helm chart.
Also in this PR:
http2-manager: Add timeout for creating a TCP connection. 
This one defaults to 30s. It will affect connections from brig, galley, etc to the federator. Usually this shouldn't reach a timeout unless something is really wrong with networking in the cluster or configuration. There is currently no way to configure this as it is unlikely that TCP connections are slow withing the network of one backend.
=> federator: Allow setting TCP connection timeout for HTTP2 requests

changelog.d/5-internal/WPB-4406, charts/federator/templates/servicemonitor.yaml, charts/federator/values.yaml
This will mark federator Metrics for scraping, if
`metrics.serviceMonitor.enabled` is set to true, similar to all other charts.
WPB-4778
=> federator: allow creating ServiceMonitor resources

changelog.d/6-federation/tcp-timeout, charts/federator/templates/configmap.yaml, charts/federator/values.yaml, libs/http2-manager/src/HTTP2/Client/Manager.hs, libs/http2-manager/src/HTTP2/Client/Manager/Internal.hs, services/federator/federator.integration.yaml, services/federator/src/Federator/Env.hs, services/federator/src/Federator/Options.hs, services/federator/src/Federator/Run.hs, services/federator/test/unit/Test/Federator/Options.hs, services/federator/test/unit/Test/Federator/Remote.hs
This ports (cherry-picks) the changes for the TCP connection timeout per PR #3595  from `develop` to `mandarin`.
Tracked by https://wearezeta.atlassian.net/browse/WPB-4792.
=> [WPB-4792] Port ticket changes from `develop` to `mandarin`

charts/outlook-addin/Chart.yaml, charts/outlook-addin/README.md, charts/outlook-addin/generate_jwk.py, charts/outlook-addin/templates/_helpers.tpl, charts/outlook-addin/templates/deployment.yaml, charts/outlook-addin/templates/ingress.yaml, charts/outlook-addin/templates/secret-or-certificate.yaml, charts/outlook-addin/templates/service.yaml, charts/outlook-addin/values.yaml
=> Outlook integration helm chart

changelog.d/3-bug-fixes/WPB-4787, libs/http2-manager/src/HTTP2/Client/Manager.hs, libs/wire-api-federation/default.nix, libs/wire-api-federation/src/Wire/API/Federation/Client.hs, libs/wire-api-federation/wire-api-federation.cabal
Create a new http2 connection in every federator client request instead of using a shared connection via http2-manager.
This is to workaround the issue discovered here https://wearezeta.atlassian.net/browse/WPB-4787
=> federator-client: Use a new http2 connection on every request

changelog.d/5-internal/xml-reports, integration/default.nix, integration/integration.cabal, integration/test/Testlib/Options.hs, integration/test/Testlib/Run.hs, integration/test/Testlib/Types.hs, integration/test/Testlib/XML.hs, nix/haskell-pins.nix, nix/manual-overrides.nix, services/brig/brig.cabal, services/brig/default.nix, services/brig/test/integration/Main.hs, services/cargohold/cargohold.cabal, services/cargohold/default.nix, services/cargohold/test/integration/Main.hs, services/federator/default.nix, services/federator/federator.cabal, services/federator/test/integration/Main.hs, services/galley/default.nix, services/galley/galley.cabal, services/galley/test/integration/Main.hs, services/gundeck/default.nix, services/gundeck/gundeck.cabal, services/gundeck/test/integration/Main.hs, services/spar/default.nix, services/spar/spar.cabal, services/spar/test-integration/Main.hs, tools/stern/default.nix, tools/stern/stern.cabal, tools/stern/test/integration/Main.hs
https://wearezeta.atlassian.net/browse/WPB-4267
For tasty tests (i.e. brig, cargohold, gundeck and stern) pass `--xml=<outfile>` to generate an xml report.
For hspec tests (i.e. federator and spar) pass `-f junit` and set environment variables `JUNIT_OUTPUT_DIRECTORY` and `JUNIT_SUITE_NAME`. The report will be at `$JUNIT_OUTPUT_DIRECTORY/junit.xml` 
For the integration test suite pass `--xml <outfile>` to generate an xml report.
=> integration-tests: Allow generating tests results in ant xml format

charts/federator/templates/servicemonitor.yaml
copy-paste error from another component.
=> federator: fix ServiceMonitor name and app label

cabal.project
The CI runs this build with -Werror, local compilation should also follow that as we do for all the other packages.
=> cabal.project: Add -Werror for integration tests

changelog.d/5-internal/background-worker-nosync, charts/background-worker/templates/configmap.yaml, charts/background-worker/values.yaml, hack/helm_vars/wire-server/values.yaml.gotmpl, hack/helmfile.yaml, integration/test/API/Brig.hs, integration/test/API/Common.hs, integration/test/SetupHelpers.hs, integration/test/Test/Brig.hs, integration/test/Test/Conversation.hs, integration/test/Test/Demo.hs, integration/test/Test/Federation.hs, services/background-worker/background-worker.cabal, services/background-worker/background-worker.integration.yaml, services/background-worker/default.nix, services/background-worker/src/Wire/BackendNotificationPusher.hs, services/background-worker/src/Wire/BackgroundWorker.hs, services/background-worker/src/Wire/BackgroundWorker/Env.hs, services/background-worker/src/Wire/BackgroundWorker/Options.hs, services/background-worker/test/Test/Wire/BackendNotificationPusherSpec.hs, services/background-worker/test/Test/Wire/Util.hs, services/brig/test/integration/Federation/End2end.hs
https://wearezeta.atlassian.net/browse/WPB-3796
Supersedes #3526
=> Fix federationStrategy 'allowAll'

changelog.d/3-bug-fixes/WPB-4835, integration/test/API/Brig.hs, integration/test/Test/Client.hs, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs, services/brig/src/Brig/API/Client.hs
https://wearezeta.atlassian.net/browse/WPB-4835
Implementation according to https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/897712162/Use+Case+Fetching+the+clients+of+a+user
=> WPB-4835 call-between-web-and-android-cant-be-established-when-one-backend-is-not-available

changelog.d/5-internal/shutdown-cleanup, integration/test/Testlib/RunServices.hs, libs/extended/src/Network/AMQP/Extended.hs, services/gundeck/src/Gundeck/Monad.hs
Avoid unnecessary error logs on service shutdown.
=> Cleanup error logs on shutdown

charts/rabbitmq-external/Chart.yaml, charts/rabbitmq-external/templates/endpoint.yaml, charts/rabbitmq-external/templates/helpers.tpl, charts/rabbitmq-external/values.yaml
To connect with the ansible based rabbitmq cluster deployed outside kubernetes.
https://github.com/wireapp/wire-server-deploy/pull/643
=> Add Rabbitmq external chart

changelog.d/4-docs/WPB-1103, services/brig/docs/swagger-v0.json, services/brig/docs/swagger-v1.json, services/brig/docs/swagger-v2.json, services/brig/docs/swagger-v3.json, services/brig/docs/swagger-v4.json, services/brig/src/Brig/API/Public.hs
Adding relative paths to the OpenApi generation code so that it matches with any URL that the server is using.
Adding basePath values to the older swagger files reflecting their versions. This is essentially the same as the OpenApi relative server URLs.
=> WPB-1103: Adding relative URLs to swagger docs.

charts/rabbitmq-external/Chart.yaml, charts/rabbitmq-external/templates/endpoint.yaml, charts/rabbitmq-external/templates/helpers.tpl, charts/rabbitmq-external/values.yaml
Add #3594 to `mandarin`. I.e. sync `mandarin` with `develop` regarding the `rabbitmq-external` Helm chart
=> Add Rabbitmq external chart (#3594)

changelog.d/3-bug-fixes/WPB-1908-guest-creating-conversation, integration/test/API/BrigInternal.hs, integration/test/Test/Conversation.hs, services/galley/src/Galley/API/Create.hs
Make sure an unverified (guest) user cannot create a group conversation.
Tracked by https://wearezeta.atlassian.net/browse/WPB-1908.
=> [WPB-1908] Unverified user creating conversation

Makefile, changelog.d/2-features/rabbitmq-external_helm_chart
Otherwise, it's not available in deployments, CI pipelines, etc..
=> Helm: Push rabbitmq-external to Helm repo

changelog.d/5-internal/WPB-4910, hack/bin/integration-test.sh, nix/wire-server.nix
https://wearezeta.atlassian.net/browse/WPB-4910
Results in logs like this:
```
Copy logs-integration to s3://wire-server-test-logs/test-logs-0.0.2-pr.5027/integration-0.0.2-pr.5027-1695992949.log
upload: ./logs-integration to s3://wire-server-test-logs/test-logs-0.0.2-pr.5027/integration-0.0.2-pr.5027-1695992949.log
```
=> WPB-4910 include build timestamp in s3 upload path for test logs

changelog.d/6-federation/wpb-3867-queue-endpoints, changelog.d/6-federation/wpb-3867-unreachable-users, libs/wire-api-federation/src/Wire/API/Federation/API.hs, libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/API/MLS/Propagate.hs, services/galley/src/Galley/API/Util.hs, services/galley/src/Galley/Effects/BackendNotificationQueueAccess.hs, services/galley/src/Galley/Intra/BackendNotificationQueue.hs, services/galley/test/integration/API/MLS/Mocks.hs
This ports changes from the MLS branch to `develop`. The changes are in using the queueing federation client for the `"on-mls-message-sent"` federation endpoint.
Tracked by https://wearezeta.atlassian.net/browse/WPB-3867.
=> [WPB-3867] Use queueing federation client for a federation API endpoint

integration/test/SetupHelpers.hs, integration/test/Test/AccessUpdate.hs, integration/test/Test/Client.hs, integration/test/Test/Conversation.hs, integration/test/Test/Demo.hs, integration/test/Test/Federation.hs, integration/test/Test/MessageTimer.hs, integration/test/Test/Roles.hs
There have been some diverging changes on the mls branch related to the way users are created and connected in tests. This aligns the version on develop with that on mls.
=> Align connectUsers to mls branch

integration/test/Test/Federation.hs
It seems the timeout was too aggressive. After testing extensively locally, I could no longer reproduce the flakiness after bumping the timeout. (I could reproduce the flakiness by running the test continuously until failure, pre-bump).
=> [chore] Fix flaky offline backend notification integration test.

changelog.d/5-internal/WBP-1224, libs/wire-api-federation/src/Wire/API/Federation/API.hs, libs/wire-api/src/Wire/API/Error.hs, libs/wire-api/src/Wire/API/Routes/Internal/Brig.hs, libs/wire-api/src/Wire/API/Routes/Internal/Brig/OAuth.hs, libs/wire-api/src/Wire/API/Routes/Internal/Brig/SearchIndex.hs, libs/wire-api/src/Wire/API/Routes/Named.hs, libs/wire-api/src/Wire/API/Routes/Public/Brig/Bot.hs, libs/wire-api/src/Wire/API/Routes/Public/Brig/OAuth.hs, libs/wire-api/src/Wire/API/Routes/Public/Brig/Provider.hs, libs/wire-api/src/Wire/API/Routes/Version.hs, libs/wire-api/src/Wire/API/User.hs, services/brig/src/Brig/API.hs, services/brig/src/Brig/API/Internal.hs, services/brig/src/Brig/API/OAuth.hs, services/brig/src/Brig/API/Public.hs, services/brig/src/Brig/Provider/API.hs, services/brig/src/Brig/Team/API.hs, services/brig/test/integration/Main.hs, services/galley/test/integration/API/Federation/Util.hs, services/gundeck/src/Gundeck/API/Public.hs, tools/stern/src/Stern/API.hs
https://wearezeta.atlassian.net/browse/WPB-1224
- improve type safety of Named by making it possible to rule out weakly typed arguments to the type (e.g. Type)
- servantify the internal route for querying the teams API for servant
=> [feat] improve type safety for Named, servantify brig internal route

changelog.d/5-internal/refactored-schema-version-tracking, services/gundeck/default.nix, services/gundeck/gundeck.cabal, services/gundeck/schema/Main.hs, services/gundeck/src/Gundeck/Schema/Run.hs, services/gundeck/src/Gundeck/Schema/V1.hs, services/gundeck/src/Gundeck/Schema/V10.hs, services/gundeck/src/Gundeck/Schema/V2.hs, services/gundeck/src/Gundeck/Schema/V3.hs, services/gundeck/src/Gundeck/Schema/V4.hs, services/gundeck/src/Gundeck/Schema/V5.hs, services/gundeck/src/Gundeck/Schema/V6.hs, services/gundeck/src/Gundeck/Schema/V7.hs, services/gundeck/src/Gundeck/Schema/V8.hs, services/gundeck/src/Gundeck/Schema/V9.hs
https://wearezeta.atlassian.net/browse/WPB-3138
=> [WPB-3138] Moved gundeck schema migrations to gundeck lib.

integration/test/Test/Federation.hs
=> [chore] Deflake federation offline notification test again.

docs/src/how-to/install/troubleshooting.md
=> add DNS troubleshooting documentation

changelog.d/5-internal/empty-push, libs/gundeck-types/src/Gundeck/Types/Push/V2.hs, libs/types-common/src/Data/Id.hs, services/cannon/cannon.cabal, services/cannon/default.nix, services/cannon/test/Test/Cannon/Dict.hs, services/galley/galley.cabal, services/galley/src/Galley/Intra/Push/Internal.hs, services/galley/test/unit/Test/Galley/Intra/Push.hs
This fixes the edge case of empty pushes being sent to gundeck from galley, due to a wrong base case in the chunk splitting function. It also adds some unit tests.
https://wearezeta.atlassian.net/browse/WPB-3169
=> Avoid empty pushes from galley

changelog.d/3-bug-fixes/mls-notification-bug, integration/test/Test/MLS/Message.hs, libs/gundeck-types/src/Gundeck/Types/Push/V2.hs, libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/MLS/Propagate.hs, services/galley/src/Galley/API/Push.hs, services/galley/src/Galley/Intra/Push/Internal.hs, services/galley/test/integration/API/MLS.hs
https://wearezeta.atlassian.net/browse/WPB-3867
This PR fixes a bug where some clients do not see MLS message notifications when fetching them with a `client` query parameter. The problem is that MLS message notifications are sent to gundeck as a single push, which will in general contain different `Recipient` objects for different clients of the same users. This makes the entries conflict with one another in cassandra, and therefore only one client ends up being stored in the database.
~The fix here is "condensing" consecutive `Recipient` items relating to the same user by joining them together into a single `Recipient` object. This works because because recipient lists are generated by user.~
This is now fixed by overloading `newMessagePush` so that it can work both with simple `(User, …
=> Fix MLS message notification bug

libs/wire-api/default.nix, libs/wire-api/test/golden/Test/Wire/API/Golden/Runner.hs, libs/wire-api/wire-api.cabal
`proto-lens` already provides wrappers around the usage, so we should stick to those.
=> wire-api: Remove explicit dependency on the `pretty` package

nix/wire-server.nix
Required for https://github.com/wireapp/wire-server/pull/3633
https://wearezeta.atlassian.net/browse/WPB-4267
=> wire-server.nix: Add aws cli to all integration test docker images

hack/bin/integration-teardown-federation.sh
This can happen due to some credentials being missing, the steps afterwards delete the whole namespace anyway.
Also in this commit:
Use 1 kubectl command to delete both namespaces, its faster like this because kubectl deletes them in parallel and kubeneretes can destroy resources inside in parallel.
=> kube-integration-teardown: Ignore failures in `helmfile destroy`

changelog.d/3-bug-fixes/federator-disconnect, libs/wire-api-federation/src/Wire/API/Federation/Client.hs
https://wearezeta.atlassian.net/browse/WPB-5116
=> wire-api-federation: Disconnect from federator after consuming the response

charts/outlook-addin/templates/deployment.yaml, charts/outlook-addin/values.yaml
=> update outlook addin version, remove unneccesary value

changelog.d/6-federation/WPB-4928-notification-endpoints, libs/wire-api-federation/src/Wire/API/Federation/API.hs, libs/wire-api-federation/src/Wire/API/Federation/API/Brig.hs, libs/wire-api-federation/src/Wire/API/Federation/API/Brig/Notifications.hs, libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs, libs/wire-api-federation/src/Wire/API/Federation/API/Galley/Notifications.hs, libs/wire-api-federation/src/Wire/API/Federation/BackendNotifications.hs, libs/wire-api-federation/src/Wire/API/Federation/Endpoint.hs, libs/wire-api-federation/src/Wire/API/Federation/HasNotificationEndpoint.hs, libs/wire-api-federation/wire-api-federation.cabal, services/brig/src/Brig/API/Federation.hs, services/brig/src/Brig/Federation/Client.hs, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Clients.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/MLS/Propagate.hs, services/galley/src/Galley/API/Message.hs
This stops using the Servant client to enqueue federation notifications. It also reorganises the federation API notification endpoints such that they are separated more from the synchronous endpoints. The notification endpoints rely on a type alias that always has `EmptyResponse` as the response type.
Tracked by https://wearezeta.atlassian.net/browse/WPB-4928.
=> [WPB-4928] Stop using Servant client to enqueue federation notifications

services/galley/test/integration/API/MLS.hs
Due to message queue the assertion on no events became flaky.
=> [fix] Flaky test for leaving self-conv on MLS

changelog.d/1-api-changes/mls-replace-kps, integration/test/API/Brig.hs, integration/test/MLS/Util.hs, integration/test/Test/MLS/KeyPackage.hs, libs/wire-api/src/Wire/API/MLS/CipherSuite.hs, libs/wire-api/src/Wire/API/MLS/KeyPackage.hs, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs, services/brig/src/Brig/API/MLS/CipherSuite.hs, services/brig/src/Brig/API/MLS/KeyPackages.hs, services/brig/src/Brig/API/Public.hs, services/brig/src/Brig/Data/MLS/KeyPackage.hs
https://wearezeta.atlassian.net/browse/WPB-4981
=> [WPB-4981] replace unclaimed keypackages atomically

changelog.d/6-federation/wpb-5103-add-to-mls-conv-unreachable-backends, integration/integration.cabal, integration/test/Test/Conversation.hs, integration/test/Test/MLS/Message.hs, integration/test/Test/MLS/One2One.hs, integration/test/Test/MLS/Unreachable.hs
The PR implements no new functionality. It just adds tests that confirm that the expected behavior of adding members to a conversation is the same as in Proteus in presence of unreachable backends.
Tracked by https://wearezeta.atlassian.net/browse/WPB-5103.
=> [WPB-5103] Add users to MLS conversation when some backends are unreachable

changelog.d/3-bug-fixes/extra-remove-proposals, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/MLS/Removal.hs
We were sending external remove proposals for each client of a user that was kicked out of a conversation following a remove commit. This was caused by some overgeneralisation of the mechanism that removes clients from subconversations when a user is deleted from the main.
I haven't added a test for this behaviour, but the upcoming PR #3671 is able to catch this problem (which is how I discovered it in the first place), so it should be covered when that one is merged.
=> Fix extra remove proposal bug

changelog.d/5-internal/mls-robust-consume, integration/test/API/Galley.hs, integration/test/MLS/Util.hs, integration/test/Notifications.hs, integration/test/SetupHelpers.hs, integration/test/Test/MLS.hs, integration/test/Test/MLS/Message.hs, integration/test/Test/MLS/SubConversation.hs, integration/test/Testlib/Env.hs, integration/test/Testlib/JSON.hs, integration/test/Testlib/Types.hs
This PR changes the way messages are consumed by clients. Before, clients would just take the message to be consumed from the `MessagePackage` that was being sent. This causes some unrealistic scenarios where a client would be able to consume a message while the message itself is still sitting in a queue, resulting in test flakiness.
After this change, every `sendAndConsume*` call listens on the appropriate websockets, gets the messages from there and consumes them, while also making some extra assertions about the corresponding notifications. This has helped catch at least one bug, and should remove any flakiness associated with delayed delivery of MLS messages.
https://wearezeta.atlassian.net/browse/WPB-5020
=> Consume MLS messages from websocket

changelog.d/3-bug-fixes/fix-subconv-client-check, integration/test/Test/MLS.hs, services/galley/src/Galley/API/MLS/Commit/InternalCommit.hs
There should be no client completeness check for subconversations. The reason the tests were not catching this so far is that we are often uploading a single key package per client, so by the time we would get to the completeness check, all key packages are exhausted and the check would succeed trivially.
https://wearezeta.atlassian.net/browse/WPB-5226
=> Remove client check for subconversations

changelog.d/5-internal/multiple-messages, integration/test/MLS/Util.hs, integration/test/Test/MLS/Message.hs, libs/wire-api/test/unit/Test/Wire/API/MLS.hs, nix/pkgs/mls-test-cli/default.nix, services/galley/test/integration/API/MLS/Util.hs
After an application message the ratchet is updated, therefore we need to save the updated group state so that future messages are generated correctly.
This PR includes an mls-test-cli update. The new mls-test-cli version modifies the `message` command to include both `group-in` and `group-out` options, as other similar commands already do.
https://wearezeta.atlassian.net/browse/WPB-5002
=> Update group state after application messages

cassandra-schema.cql, changelog.d/0-release-notes/WPB-5143, changelog.d/2-features/WPB-5143, charts/galley/values.yaml, docs/src/developer/reference/config-options.md, libs/galley-types/src/Galley/Types/Teams.hs, libs/galley-types/test/unit/Test/Galley/Types.hs, libs/wire-api/src/Wire/API/Routes/Internal/Galley.hs, services/galley/galley.cabal, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/Teams/Features.hs, services/galley/src/Galley/API/Teams/Features/Get.hs, services/galley/src/Galley/App.hs, services/galley/src/Galley/Cassandra/TeamFeatures.hs, services/galley/src/Galley/Schema/Run.hs, services/galley/src/Galley/Schema/V89_MlsLockStatus.hs, services/galley/test/integration/API/Teams/Feature.hs
https://wearezeta.atlassian.net/browse/WPB-5143
=> WPB-5143 locked status for mls config

changelog.d/5-internal/notification-client-refactor, libs/wire-api-federation/src/Wire/API/Federation/API.hs, libs/wire-api-federation/src/Wire/API/Federation/API/Brig/Notifications.hs, libs/wire-api-federation/src/Wire/API/Federation/API/Galley/Notifications.hs, libs/wire-api-federation/src/Wire/API/Federation/HasNotificationEndpoint.hs, services/galley/src/Galley/API/Federation.hs
A small refactoring to clean up the way notification API descriptions are specified and converted to servant endpoints.
=> Refactor notification API descriptions

changelog.d/6-federation/wpb-5208-add-users-when-others-unreachable, integration/test/Test/Conversation.hs, integration/test/Test/MLS/Unreachable.hs, libs/wire-api/src/Wire/API/FederationStatus.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Manual/FederationStatus.hs, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Create.hs
This ended up changing no logic in the application code. However, tests have been extended to confirm the expected behavior.
Tracked by https://wearezeta.atlassian.net/browse/WPB-5208.
=> [WPB-5208] Allow adding users to conversations when other backends are unreachable

changelog.d/5-internal/WPB-4853, libs/wire-api/src/Wire/API/MakesFederatedCall.hs
=> Swagger docs: new line after fed call tag

changelog.d/3-bug-fixes/WPB-5330, integration/test/MLS/Util.hs, libs/wire-api/test/unit/Test/Wire/API/MLS.hs, services/galley/test/integration/API/MLS/Util.hs
Removing command args that were causing `mls-test-cli` to throw errors in the test suites.
=> Hotfix: Fixing how mls-test-cli is called

changelog.d/3-bug-fixes/WPB-5330, integration/test/MLS/Util.hs, libs/wire-api/test/unit/Test/Wire/API/MLS.hs, services/galley/test/integration/API/MLS/Util.hs
This reverts commit 58bcc0c03c99519442ce7979dff12a4bf2cd6d9a.
It was not required, this breaks tests for everyone.
=> Revert "Hotfix: Fixing how mls-test-cli is called (#3690)"

.envrc, changelog.d/2-features/WPB-5241, integration/test/MLS/Util.hs, integration/test/Notifications.hs, integration/test/Test/AccessUpdate.hs, integration/test/Test/Conversation.hs, integration/test/Test/Demo.hs, integration/test/Test/Federation.hs, integration/test/Test/MLS.hs, integration/test/Test/MLS/Message.hs, integration/test/Test/MLS/One2One.hs, integration/test/Test/MLS/SubConversation.hs, integration/test/Test/MLS/Unreachable.hs, integration/test/Test/MessageTimer.hs, integration/test/Test/Roles.hs, integration/test/Testlib/Cannon.hs, integration/test/Testlib/Env.hs, integration/test/Testlib/Types.hs
https://wearezeta.atlassian.net/browse/WPB-5241
- have the functions that want a timeout `ask` it from the environment
- adjust all usages to not take a timeout explicitly
=> [WPB-5241] add the timeout to the global and local environment

changelog.d/5-internal/coturn-multiple-installations, charts/coturn/templates/service-account.yaml
See also https://github.com/zinfra/cailleach/pull/1860 for prood of concept of this working.
In theory for other purposes, a Role and RoleBinding could be used. But that is not powerful enough to provide the "get nodes" permission which is scoped at the cluster level. To avoid helm tripping over objects installed in another release, create multiple of these roles and bindings.
=> Coturn: avoid name clashes when installing multiple times

changelog.d/5-internal/increase-sqs-timeout, libs/types-common-aws/src/Util/Test/SQS.hs
It seems 3 seconds is not enough sometimes, and it was causing flakiness of legalhold tests in CI.
https://wearezeta.atlassian.net/browse/WPB-5359
=> Increase SQS timeout in galley integration

.gitignore, changelog.d/3-bug-fixes/brig-flake, services/brig/test/integration/API/MLS/Util.hs
https://wearezeta.atlassian.net/browse/WPB-5356
Not entirely sure this fixes it but it's the only thing we're doing differently so it might be worth a shot :) 
> [!NOTE]
> I investigated into one of the flaking tests. As the flake only occurs with theses tests I can basically localise the flaking to one location, the issue being that I cannot reproduce it locally. Neither in the normal testsuite nor in a local cluster.
> Due to what the error says I’m suspecting some sort of memory corruption, normally you get this error when you pass an unitialised buffer or a null pointer.
> As I cannot reproduce, Akshays guess was that it’s somehow influenced by other tests. (Which is hard to test again because I cannot run the entire test suite 100 times locally) so what I’m going to try today is …
=> [WPB 5356] fix brig flaking

changelog.d/2-features/WPB-2565-member-updates, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/Teams.hs, services/galley/test/integration/API/Teams.hs, services/galley/test/integration/API/Util.hs
This dusts off PR #3431, which got reverted in PR #3447. Specific events (member join, update and leave) are sent only to team admins now.
Tracked by https://wearezeta.atlassian.net/browse/WPB-2565.
=> [WPB-2565] Do not send member updates to all

changelog.d/3-bug-fixes/correct-notification-timeout, services/galley/src/Galley/Cassandra/TeamNotifications.hs
=> [fix] set notificationTimeOut to 28 days, make it legible

.envrc, changelog.d/5-internal/add-ghc-flakr, hack/bin/.envrc
This PR is according to our discussion in C&D from November 14, 2023.
Mind that the pinning is done by `ghc-flakr` itself to ensure caching. 
https://github.com/wireapp/ghc-flakr
=> [feat] add support for ghc-flakr's hs-run executable

changelog.d/4-docs/group-id-docs, libs/wire-api/src/Wire/API/Conversation/Protocol.hs
The MLS group ID is base64-encoded, and not anymore limited to 256 bytes.
=> Update group ID documentation

changelog.d/4-docs/long-summaries, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/Conversation.hs
Turn long summaries in openapi documentation into descriptions.
=> Turn long summaries into descriptions

changelog.d/5-internal/WPB-1226-servantify-internal-galley-conv-endpoints, libs/wire-api/src/Wire/API/Routes/Internal/Galley.hs, services/galley/src/Galley/API.hs, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/Query.hs, services/galley/src/Galley/API/Update.hs, services/galley/src/Galley/Run.hs, services/galley/test/integration/Run.hs
The PR servantifies a few internal Galley endpoints.
Tracked by https://wearezeta.atlassian.net/browse/WPB-1226.
=> [WPB-1226] Servantify internal Galley conversation endpoints

changelog.d/5-internal/PR-3727, services/brig/src/Brig/API/Client.hs, services/brig/src/Brig/Effects/JwtTools.hs
=> [chore] Remove client ID conversion roundtrip

changelog.d/5-internal/WPB-5577, charts/nginz/templates/conf/_nginx.conf.tpl, services/brig/test/integration/API/User/Client.hs, services/brig/test/integration/API/User/Util.hs, services/nginz/integration-test/conf/nginz/common_response.conf
https://wearezeta.atlassian.net/browse/WPB-5577
=> WBP-5577 make replay nonce header accessible for frontend

integration/test/Testlib/RunServices.hs
Previously this looked for a directory, which is not correct, in git worktrees, the .git dir is shared between multiple directories, .git is merely a file that contains the path to the original .git dir.
=> [fix] fix discovery of directory

libs/tasty-cannon/src/Test/Tasty/Cannon.hs, services/galley/test/integration/API/Teams.hs, services/galley/test/integration/API/Util.hs
This function doesn't tell the caller whether the expected event came or not and hence pointless to be used in testing. It is used only in 1 place (`checkTeamMemberJoin`) and that place should be using assertMatch_ instead.
The `checkTeamMemberJoin` function was used wrongly in 1 place, it has been deleted.
=> tasty-cannon: Delete awaitMatch_

changelog.d/3-bug-fixes/spar-scim-old-issuer, services/spar/src/Spar/App.hs, services/spar/src/Spar/Scim/User.hs, services/spar/test-integration/Test/Spar/APISpec.hs, services/spar/test-integration/Test/Spar/Scim/UserSpec.hs, services/spar/test-integration/Util/Scim.hs
https://wearezeta.atlassian.net/browse/WPB-3530
A valid URef can be used for lookups in tables spar.user and spar.user_v2 even after issuer updates.
This ensures that SCIM can find users even when the issuer for the team has changed and the spar.user_v2 table is not yet up to date with it.
=>  Spar: Ensure mkValidExternalId returns a valid URef 

changelog.d/5-internal/WPB-4887, charts/nginz/values.yaml
https://wearezeta.atlassian.net/browse/WPB-4887
=> WPB-4887 increased ingress payload size from 256k to 512k

changelog.d/3-bug-fixes/WPB-5603, integration/test/API/Galley.hs, integration/test/Notifications.hs, integration/test/Test/Conversation.hs, services/galley/src/Galley/API/Teams.hs
When a team member is deleted, the backend would not trigger sending of a `conversation.member-leave` event to remotes that are in the conversations the deleted member used to be part of. This PR fixes that.
Tracked by https://wearezeta.atlassian.net/browse/WPB-5603.
=> [WPB-5603] Deleting a team member does not result in a conversation event

changelog.d/5-internal/WPB-5541, libs/wire-api/src/Wire/API/Team/Feature.hs, tools/stern/src/Stern/API.hs, tools/stern/src/Stern/API/Routes.hs, tools/stern/src/Stern/Intra.hs, tools/stern/test/integration/API.hs
https://wearezeta.atlassian.net/browse/WPB-5541
stern has end-points for changing a number of team feature.  outlook calendar integration is a feature that can be enabled / disabled by the team admin, but also locked / unlocked by the site admin (in order to prevent / allow team admins to use the feature).
this PR adds the missing lock/unlock end-point for outlook calendar integration to stern.
=> Fix calendar integration setting in backoffice / stern

changelog.d/5-internal/fisx-spar-refactorings-2023-11-27-1, services/spar/src/Spar/API.hs, services/spar/src/Spar/Scim/User.hs, services/spar/test-integration/Test/Spar/APISpec.hs, services/spar/test-integration/Util/Core.hs, services/spar/test-integration/Util/Scim.hs
https://wearezeta.atlassian.net/browse/WPB-5708
=> Improve spar test coverage

changelog.d/3-bug-fixes/WPB-5603, integration/test/Test/Conversation.hs, libs/wire-api/src/Wire/API/Conversation.hs, libs/wire-api/src/Wire/API/Conversation/Action.hs, libs/wire-api/src/Wire/API/Event/Conversation.hs, libs/wire-api/src/Wire/API/Event/LeaveReason.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/Event_conversation.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/Event_user.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/RemoveBotResponse_user.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Manual.hs, libs/wire-api/test/golden/Test/Wire/API/Golden/Manual/ConversationRemoveMembers.hs, libs/wire-api/test/golden/testObject_ConversationRemoveMembers_1.json, libs/wire-api/test/golden/testObject_ConversationRemoveMembers_2.json, libs/wire-api/test/golden/testObject_ConversationRemoveMembers_3.json, libs/wire-api/wire-api.cabal, services/brig/test/integration/API/Provider.hs, services/brig/test/integration/API/User/Util.hs, services/brig/test/integration/Federation/End2end.hs, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/MLS/Commit/InternalCommit.hs, services/galley/src/Galley/API/Teams.hs, services/galley/src/Galley/API/Update.hs, services/galley/test/integration/API.hs, services/galley/test/integration/API/Federation.hs, services/galley/test/integration/API/Util.hs
As reported by a client developer, the event reason when a team member is deleted was incorrectly "member removed", when it should have been "member deleted" (from a team). This PR fixes it.
Tracked by https://wearezeta.atlassian.net/browse/WPB-5603.
=> [WPB-5603] Fix the team member deleted event reason

changelog.d/5-internal/refactor-get-options, libs/types-common/src/Util/Options.hs
We can combine the two parsers instead of invoking them both. This way we get a help text even if no configuration file is passed.
=> Refactor getOptions

Makefile, changelog.d/5-internal/upload-bom, hack/bin/bombon.hs, nix/default.nix, nix/sources.json, nix/wire-server.nix
for tracking of wire-server bom 
cc @emil-wire
=> [feat] bombon derivations

services/galley/test/integration/API/Teams/LegalHold/Util.hs
Earlier we gave it up to 3.15 milliseconds, now its up to 5 seconds.
https://wearezeta.atlassian.net/browse/WPB-5803
=> galley-integration: Give legalhold service longer to be connectable from galley

changelog.d/3-bug-fixes/warp-connection-close, nix/haskell-pins.nix
https://wearezeta.atlassian.net/browse/WPB-5678
Please review the upstream PR before approving this PR: https://github.com/yesodweb/wai/pull/958
=> Use fork of warp which closes connections gracefully

.envrc, hack/bin/.envrc, hack/bin/bombon.hs
at the request of @flokli 
- ~~Add a new entry in an appropriate subdirectory of `changelog.d`~~
=> [fix] remove dependency on experimental feature flakes

libs/http2-manager/src/HTTP2/Client/Manager.hs, libs/http2-manager/src/HTTP2/Client/Manager/Internal.hs, services/federator/src/Federator/Remote.hs
https://wearezeta.atlassian.net/browse/WPB-5934
This comes with performance penalty but its required to get around this bug in
the http2 library: https://github.com/kazu-yamamoto/http2/issues/102
=>  federator: Do no reuse connections when talking to remotes 

libs/types-common-aws/default.nix, libs/types-common-aws/src/Util/Test/SQS.hs, libs/types-common-aws/types-common-aws.cabal
https://wearezeta.atlassian.net/browse/WPB-5911
Perhaps they started getting delivered multiple times. There is code in ElasticMQ which only allows last delivery receipt to be used for deletion.
=> SQSWatcher: Ignore failures in deleting recieved messages

changelog.d/3-bug-fixes/WPB-5810, integration/integration.cabal, integration/test/API/Brig.hs, integration/test/API/BrigInternal.hs, integration/test/SetupHelpers.hs, integration/test/Test/Services.hs, libs/wire-api/src/Wire/API/Routes/Public/Brig/Services.hs, services/brig/src/Brig/Provider/API.hs
There are a couple of endpoints that have no response body and that were written using Servant's `Verb` mechanism that matches on the `Accept` header. The PR fixes this.
Tracked by https://wearezeta.atlassian.net/browse/WPB-5810.
=> [WPB-5810] Fix the service provider endpoints that return no body

changelog.d/2-features/WPB-5936, integration/test/Test/Conversation.hs, services/brig/src/Brig/IO/Intra.hs, services/galley/src/Galley/API/Teams.hs
Send a `conversation.member-leave` event to team admins for each conversation the deleted team member used to be part of.
Tracked by https://wearezeta.atlassian.net/browse/WPB-5936.
=> [WPB-5936] Send `conversation.member-leave` events to team admins

changelog.d/2-features/sft-chart-service-monitor, charts/sftd/templates/servicemonitor.yaml, charts/sftd/values.yaml
Part of https://wearezeta.atlassian.net/browse/WPB-5768
=> add optional serviceMonitor field for SFTD chart

charts/brig/templates/deployment.yaml
=> fix brig's Helm template for geoip disabled

changelog.d/2-features/WPB-1436, charts/galley/templates/configmap.yaml, charts/galley/values.yaml, docs/src/developer/reference/config-options.md, integration/test/API/Galley.hs, integration/test/Test/Conversation.hs, services/galley/galley.integration.yaml, services/galley/src/Galley/API/Update.hs, services/galley/src/Galley/Options.hs
=> WPB-1436 make guest link maximum lifetime configurable

integration/integration.cabal, libs/bilge/src/Bilge/IO.hs, libs/ssl-util/default.nix, libs/ssl-util/src/Ssl/Util.hs, libs/ssl-util/ssl-util.cabal, libs/types-common-aws/default.nix, libs/types-common-aws/src/AWS/Util.hs, libs/types-common-aws/src/Util/Test/SQS.hs, libs/types-common-aws/types-common-aws.cabal, nix/haskell-pins.nix, nix/manual-overrides.nix, services/brig/brig.cabal, services/brig/src/Brig/AWS.hs, services/brig/src/Brig/App.hs, services/brig/src/Brig/Data/Client.hs, services/brig/src/Brig/Provider/RPC.hs, services/cargohold/cargohold.cabal, services/cargohold/src/CargoHold/AWS.hs, services/cargohold/src/CargoHold/S3.hs, services/galley/galley.cabal, services/galley/src/Galley/App.hs, services/galley/src/Galley/Aws.hs, services/galley/src/Galley/Env.hs, services/galley/src/Galley/External.hs, services/galley/src/Galley/External/LegalHoldService/Internal.hs, services/gundeck/gundeck.cabal, services/gundeck/src/Gundeck/Aws.hs, services/proxy/proxy.cabal
Reverts wireapp/wire-server#3736 for now until we fix the LH certificate pinning error.
=> Revert "Migrate away from our http-client fork, use upstream."

services/brig/src/Brig/Data/Client.hs
=> remove more geoip (dead) code

changelog.d/0-release-notes/upgrade-webapp, charts/webapp/values.yaml
Beside using up-to-date versions in Helm charts is generally beneficial, this version also provides multi-ingress support.
The version has been discussed with the web-team.
Ticket: https://wearezeta.atlassian.net/browse/WPB-6077
=> webapp: Upgrade to 2023-12-11-production.0-v0.31.17-0-1e91445

cassandra-schema.cql, changelog.d/2-features/WPB-5883, charts/galley/templates/configmap.yaml, charts/galley/values.yaml, docs/src/developer/reference/config-options.md, hack/helm_vars/wire-server/values.yaml.gotmpl, integration/integration.cabal, integration/test/Notifications.hs, integration/test/Test/Conversation.hs, integration/test/Test/FeatureFlags.hs, libs/galley-types/src/Galley/Types/Teams.hs, libs/galley-types/test/unit/Test/Galley/Types.hs, libs/wire-api/src/Wire/API/Routes/Internal/Galley.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/Feature.hs, libs/wire-api/src/Wire/API/Team/Feature.hs, services/galley/galley.cabal, services/galley/galley.integration.yaml, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/Public/Feature.hs, services/galley/src/Galley/API/Teams.hs, services/galley/src/Galley/API/Teams/Features.hs, services/galley/src/Galley/API/Teams/Features/Get.hs, services/galley/src/Galley/Cassandra/TeamFeatures.hs, services/galley/src/Galley/Schema/Run.hs, services/galley/src/Galley/Schema/V91_TeamMemberDeletedLimitedEventFanout.hs, services/galley/test/integration/API/Teams/Feature.hs
To maintain compatibility with old clients that do not implement the limited even fanout feature when a team member is deleted, this PR puts the limited fanout behind a feature flag. The flag is disabled by default to maintain compatibility with old clients that rely on the full fanout.
Tracked by https://wearezeta.atlassian.net/browse/WPB-5883.
done, port it to the current PR branch. That way we make sure the behavior is as before. Otherwise it would be hard to know what are the expected semantics given that PR #3434 made some changes without writing tests.
=> [WPB-5883] Feature flag for a limited event fanout

changelog.d/5-internal/restored-brig-memory-quota, hack/helm_vars/wire-server/values.yaml.gotmpl
https://wearezeta.atlassian.net/browse/WPB-5676
After some local and CI based testing, it seems that whatever was causing the OOM issue for bring after upgrading GHC to 9.4 is no longer present. Considering the sheer scope of changes since then and the dependencies we updated or swapped since then, and as discussed within the team, I'm setting this up to revert the memory quota back to the previous value, so we can see how it behaves on staging.
=> Revert brig memory setup back to 512mb

changelog.d/3-bug-fixes/PR-3808, integration/test/Test/MLS.hs, libs/wire-api/src/Wire/API/MLS/Credential.hs, libs/wire-api/src/Wire/API/MLS/KeyPackage.hs
=> fix: X509 Client Identity parser

integration/Setup.hs
Very small change to /integration/Setup.hs, hopefully uncontroversial.
=> Fix integration test collector

changelog.d/3-bug-fixes/WPB-5064, charts/demo-smtp/values.yaml, deploy/dockerephemeral/build/Makefile, deploy/dockerephemeral/docker-compose.yaml, docs/src/developer/reference/make-docker-and-qemu.md
=> fix: WPB-5064 Moved namshi to ix-ai smtp image 

Makefile, changelog.d/5-internal/upload-bom-to-deptrack, hack/bin/bombon.hs
Upload bill-of-material (BOM) files directly to the Dependency Tracker via REST.
This eases the life of the security team and prevents cluttering our release artifact page.
Ticket: https://wearezeta.atlassian.net/browse/WPB-6142
Should be merged after this `ghc-flakr` PR has landed: https://github.com/wireapp/ghc-flakr/pull/2 (I need to update the commit has in the flake's URL then.)
=> Upload bombon bom files directly to deptrack (WPB-6142)

changelog.d/5-internal/WPB-6073, nix/haskell-pins.nix, nix/manual-overrides.nix
https://wearezeta.atlassian.net/browse/WPB-6073
I have tried to sort these roughly by importance
- bloodhound (immense divergence, tests don't pass)
- warp (tests don't pass)
- saml2-web-sso (tests don't pass) 
- amqp (tests don't pass)
- cql-io (tests don't pass) 
- hspec-junit-formatter (tests don't pass) 
- markov-chain-usage-model (tests don't pass) 
- openapi3 (tests don't pass) 
- quickcheck-state-machine (tests don't pass) 
- transitive-anns (tests are flaky) 
- wai-route (it has been noted to get rid of it for a while and we depend on a quite old version) 
- tasty (immense divergence) 
- there's an entire family of libraries that are made by thoralf wittner that we still have in use, commonly as a fork that may also already be years old, it doesn't seem like any of these libraries …
=> [WPB-6073] cleanup haskell pins

changelog.d/4-docs/WPB-6177, docs/src/developer/developer/api-versioning.md, services/brig/src/Brig/API/Public.hs, services/brig/src/Brig/API/Public/Swagger.hs
=> WPB-6177 document steps for creating new API version

changelog.d/5-internal/WPB-6181, libs/jwt-tools/src/Data/Jwt/Tools.hs, libs/jwt-tools/test/Spec.hs, nix/pkgs/rusty_jwt_tools_ffi/default.nix, services/brig/test/integration/API/User/Client.hs
https://wearezeta.atlassian.net/browse/WPB-6181
=> WPB-6181 Update rusty-jwt-tools

changelog.d/3-bug-fixes/adjust-nginz-memory-limits, charts/nginz/values.yaml
Adjust the requested memory and upper bound limit of `nginz` pods in the related Helm chart. (We experienced OOM errors with the old settings.)
=> increase nginz memory limit

changelog.d/1-api-changes/WPB-6189, integration/integration.cabal, integration/test/API/Brig.hs, integration/test/API/BrigInternal.hs, integration/test/API/Spar.hs, integration/test/Test/Demo.hs, integration/test/Test/User.hs, services/brig/src/Brig/API/Internal.hs, services/brig/src/Brig/API/Public.hs, services/brig/src/Brig/API/User.hs
https://wearezeta.atlassian.net/browse/WPB-6189
=> Disallow changing user display name, handle in mlsE2EId-enabled teams

changelog.d/1-api-changes/WPB-6189, integration/integration.cabal, integration/test/API/Brig.hs, integration/test/API/BrigInternal.hs, integration/test/API/Spar.hs, integration/test/Test/Demo.hs, integration/test/Test/User.hs, services/brig/src/Brig/API/Internal.hs, services/brig/src/Brig/API/Public.hs, services/brig/src/Brig/API/User.hs
https://wearezeta.atlassian.net/browse/WPB-6189
- Integration tests
- block changes in the backend.
- lie about managed_by in `GET /self`, but only there.
=> Block changes to some user data in mlsE2EId teams (q1-2024)

nix/pkgs/mls-test-cli/default.nix
=> remove Rust dependency on local tls_codec copy

changelog.d/4-docs/WPB-4554, docs/README.md, docs/src/how-to/install/tls.md, nix/default.nix, services/run-services
=> fixing grepinclude references for docs.wire.com and adjusting nix build context; updating TLS documentation

changelog.d/5-internal/reuse-manager, libs/ssl-util/src/Ssl/Util.hs, services/brig/src/Brig/App.hs, services/brig/src/Brig/Provider/RPC.hs, services/galley/src/Galley/App.hs, services/galley/src/Galley/Cassandra/LegalHold.hs, services/galley/src/Galley/Effects/LegalHoldStore.hs, services/galley/src/Galley/Env.hs, services/galley/src/Galley/External.hs, services/galley/src/Galley/External/LegalHoldService.hs, services/galley/src/Galley/External/LegalHoldService/Internal.hs
reuse manager whenever possible but drop it in legalhold scenarios without using a fork
the crux of the `http-client` change can probably be broken down to these lines: 
```haskell
manF <- view extGetManager
man <- liftIO $ manF fprs
```
because we only initialize the manager as soon as we have the fingerprints (per request), we don't reuse connections, ever but create a new manager per request. 
there's a fundamental issue where receiving fingerprints per request modifies the ssl context, which is per manager. the previous approach avoided this, by verifying directly in the request and not by letting `http-client` run a callback.
=> Improve usage of http-manager (fixes for fingerprint verification)

nix/haskell-pins.nix
Updated references to git repositories to wireapp forks
This is a follow up to https://github.com/wireapp/wire-server/pull/3841, which missed one repository
=> Move repository from GitLab to GitHub

nix/haskell-pins.nix
Use GitHub wireapp forks for nix dependencies
=> refactor: use GitHub forks

integration/integration.cabal, integration/test/API/Galley.hs, integration/test/Test/TeamSettings.hs
=> WPB-6269 add test for team settings auth

integration/test/API/Galley.hs, integration/test/Test/TeamSettings.hs
=> WPB-6269 add test for team properties auth

changelog.d/3-bug-fixes/WPB-5845, integration/test/Test/LegalHold.hs, services/galley/src/Galley/API/Util.hs
https://wearezeta.atlassian.net/browse/WPB-5845
=> WPB-5845 guests should not be able to join conversations under legalhold

changelog.d/4-docs/update-build-instructions-for-wire-server, docs/src/developer/developer/building.md
=> backport documentation changes

changelog.d/4-docs/update-build-instructions-for-wire-server, docs/src/developer/developer/building.md
https://wearezeta.atlassian.net/browse/WPB-6210
backport to q1-2024 in #3867 
I have updated the build instructions for `wire-server`, my reasoning for the updates is 
as follows 
- as much copy/paste-able snippets as possible
- don't skip any steps that are unclear for non-Haskellers but relevant for getting a basic build
- don't explain anything that is explained elsewhere (installation instructions for nix/ direnv/ docker) 
- don't update documentation that is not relevant for the people needing nothing more than to build `wire-server`
=> [WPB-6210] update documentation on how to build `wire-server`

changelog.d/3-bug-fixes/use-proper-api-in-integration-testsuite, integration/test/API/Brig.hs, integration/test/API/BrigInternal.hs, integration/test/Test/Demo.hs
=> [fix] use the correct API in the integration tests

changelog.d/3-bug-fixes/WPB-6351, libs/wire-api/src/Wire/API/Routes/Version.hs, libs/wire-api/test/unit/Test/Wire/API/Routes/Version.hs, services/brig/src/Brig/CanonicalInterpreter.hs, services/brig/src/Brig/Effects/GalleyProvider/RPC.hs
https://wearezeta.atlassian.net/browse/WPB-6351
The problem only occurs for intra service calls to public APIs if the latest version(s) are disabled. Internal APIs are not versioned, so everything is fine there.
=> WPB-6351 Use max available version for internal API calls

changelog.d/3-bug-fixes/coturn-pre-stop-hook, charts/coturn/Chart.yaml
Update coturn image with bugfix to its pre-stop-hook from https://github.com/wireapp/coturn/pull/10 to allow coturn pods to terminate once their traffic has drained, instead of waiting for its terminationGracePeriod (up to 24 hours).
Part of https://wearezeta.atlassian.net/browse/WPB-5328
=> Update coturn default image

services/galley/src/Galley/API/MLS/Message.hs
=> move a comment closer to the commented line

integration/test/Test/LegalHold.hs, services/galley/src/Galley/API/LegalHold/Conflicts.hs
https://wearezeta.atlassian.net/browse/WPB-6392
=> Unblock release.

changelog.d/5-internal/update-webapp-teams-accounts-helm-values, charts/account-pages/values.yaml, charts/team-settings/values.yaml, charts/webapp/values.yaml
While trying to install wire-server on Kubernetes v1.28.2 in an on-premise test environment, got the warning/errors for the following things, and this pr includes fixes for them - 
1. for the accounts, team-setting and webapp, got into following error - 
Error: container has runAsNonRoot and image will run as root
While trying to debug the issue, came across similar issue here - https://github.com/jaegertracing/helm-charts/issues/105
the solution in this pr, uses `runAsUser: 1000` policy for these 3 deployments and with this no errors were seen while deploying this.
=> Update helm charts to support k8s v1.28

changelog.d/5-internal/update-k8s-annotation-for-topology-aware-routing, charts/background-worker/templates/service.yaml, charts/backoffice/templates/service.yaml, charts/brig/templates/service.yaml, charts/cannon/templates/headless-service.yaml, charts/cannon/templates/nginz-service.yaml, charts/cargohold/templates/service.yaml, charts/federator/templates/service.yaml, charts/galley/templates/service.yaml, charts/gundeck/templates/service.yaml, charts/legalhold/templates/service.yaml, charts/nginz/templates/service.yaml, charts/proxy/templates/service.yaml, charts/spar/templates/service.yaml
Annotation for enabling Topology Aware Routing has been changed to `service.kubernetes.io/topology-mode` for k8s 1.27+
https://kubernetes.io/docs/concepts/services-networking/topology-aware-routing/
=> update annotation key for k8s 1.27+

changelog.d/5-internal/integration-cleanup-sh, hack/bin/integration-cleanup.sh
The `-f` filter is a regex and should match the prefix `test-`, thus,
the regex should be `^test-`. Without `^`, the search string is looked
up in the entire release name.
=> fix integration-cleanup.sh to match prefix only

changelog.d/4-docs/wpb-6780-patch-hole-in-scim-docs, docs/src/understand/single-sign-on/trouble-shooting.md
https://wearezeta.atlassian.net/browse/WPB-6780
=> Patch hole in scim docs regarding wire team role manipulation.

.envrc, .hlint.yaml, changelog.d/5-internal/WPB-5687, deploy/dockerephemeral/run.sh, integration/test/API/Brig.hs, integration/test/API/BrigInternal.hs, integration/test/API/Galley.hs, integration/test/API/GalleyInternal.hs, integration/test/MLS/Util.hs, integration/test/Notifications.hs, integration/test/SetupHelpers.hs, integration/test/Test/LegalHold.hs, integration/test/Test/MLS.hs, integration/test/Test/MLS/One2One.hs, integration/test/Test/MLS/SubConversation.hs, integration/test/Test/Search.hs, integration/test/Test/User.hs, integration/test/Test/Version.hs, integration/test/Testlib/App.hs, integration/test/Testlib/Assertions.hs, integration/test/Testlib/Env.hs, integration/test/Testlib/HTTP.hs, integration/test/Testlib/JSON.hs, integration/test/Testlib/MockIntegrationService.hs, integration/test/Testlib/ModService.hs, integration/test/Testlib/PTest.hs, integration/test/Testlib/Types.hs, libs/brig-types/src/Brig/Types/User/Event.hs, services/galley/test/integration/API/Teams/LegalHold.hs
https://wearezeta.atlassian.net/browse/WPB-5687
=> [WPB-5687] port flaking LH tests to new integration

changelog.d/3-bug-fixes/sns-arn-parsing, services/gundeck/default.nix, services/gundeck/gundeck.cabal, services/gundeck/src/Gundeck/Aws/Arn.hs, services/gundeck/src/Gundeck/Push.hs, services/gundeck/test/unit/Aws/Arn.hs, services/gundeck/test/unit/Main.hs
This PR contains two things:
1. Add fields to the log message such that mismatches between stored and app-provided data become more obvious.
2. Fix an AWS SNS Endpoint parsing bug: We parsed the environment up to the first dash. But, environment names may contain dashes themselves, thus we must accumulate them up to the last dash.
Tickets:
- https://wearezeta.atlassian.net/browse/WPB-6650
- https://wearezeta.atlassian.net/browse/WPB-6653
=> gundeck: Fix SNS endpoint parser

changelog.d/3-bug-fixes/log-requestId-gundeck, services/gundeck/src/Gundeck/Run.hs
The request id was missing in the `Env`. This led to `"N/A"` being logged.
I've deployed the `gundeck` Docker image of this branch on a test system (`sven-test`) and have seen that request IDs are being logged for queries where this didn't work before.
Ticket: https://wearezeta.atlassian.net/browse/WPB-6815
=> gundeck: set request id in request env

Makefile, changelog.d/5-internal/v0-integration-setup, hack/bin/integration-setup-federation.sh, hack/bin/integration-test.sh, hack/helm_vars/common.yaml.gotmpl, hack/helm_vars/nginx-ingress-services/values.yaml.gotmpl, hack/helm_vars/wire-federation-v0/values.yaml.gotmpl, hack/helm_vars/wire-server/values.yaml.gotmpl, hack/helmfile-federation-v0.yaml, nix/overlay.nix
=> WPB-6309 deploy the released mandarin version in kind dev environment

changelog.d/3-bug-fixes/wpb-6144-messaging-blocked-user, services/galley/src/Galley/API/One2One.hs, services/galley/src/Galley/Cassandra/Conversation/Members.hs, services/galley/src/Galley/Cassandra/Queries.hs, services/galley/src/Galley/Effects/MemberStore.hs
As part of PR #3889, we used to remove MLS clients from a 1-to-1 conversation only on the backend side (i.e., not updating the group state). However, that's problematic as the state of the group on the backend side and on the client side is out of sync. This PR changes that by not removing the clients from the conversation; only the user is removed.
This PR adds no new tests, but it does rely on the `Test.MLS.One2One.testMLSOne2OneBlockedAfterConnected` test from PR #3889.
Tracked by https://wearezeta.atlassian.net/browse/WPB-6144.
=> [WPB-6144] Don't remove MLS clients from a 1-1 conversation

changelog.d/3-bug-fixes/bw-service-monitor, charts/background-worker/templates/servicemonitor.yaml
=>  charts/background-worker: Fix name of the service monitor 

changelog.d/3-bug-fixes/WPB-6567, charts/coturn/templates/statefulset.yaml
The sidecar only looks for the process name.
=> coturn cert-reloader sidecar config: process name should not contain the path (helm chart)

changelog.d/3-bug-fixes/bw-service-monitor, charts/background-worker/templates/servicemonitor.yaml
=>  charts/background-worker: Fix name of the service monitor  (#3913)

integration/test/Testlib/ModService.hs, integration/test/Testlib/Run.hs
Integration tests weren't being killed on control-c, when investigating a proposed fix we realised that tests were running sequentially on the main thread, causing the issue with exception handling. Since running them in parallel increases flakiness, I'm holding off on correcting this until we do some of the mitigation work we have planned.
=> Handle async exceptions so Control-C works as expected

changelog.d/2-features/claim-key-packages-rate-limit, changelog.d/2-features/one2one-rate-limit, charts/nginz/templates/conf/_nginx.conf.tpl, charts/nginz/values.yaml
https://wearezeta.atlassian.net/browse/WPB-6979
=> charts/nginz: Configure rate limits for claiming MLS key packages and getting one2one conversations

charts/nginz/templates/conf/_nginx.conf.tpl, charts/nginz/values.yaml
Previous logic limited how many keys could be claimed for one user, but continued limiting claims on multiple users. This causes problems while creating conversations when a lot of key package claims are needed.
This commit introduces a concept of specific_rate_limits which allow setting multiple rate limit zones in nginz. Here we use one for limiting how many key packages can be claimed by a user per target and another for limiting how many key packages claimed by a user for any target.
Fixup #3918
https://wearezeta.atlassian.net/browse/WPB-6979
=> charts/nginz: Fixup Rate limit for claiming MLS key-pacakges by requesting and target user

nix/haskell-pins.nix
https://wearezeta.atlassian.net/browse/WPB-6170
Ideally this should make it easier to upstream and get rid of the fork all together.
=> Point hsaml2 to a minimal version of our fork

changelog.d/5-internal/wpb6998-improve-federator-error-logs, libs/wire-api-federation/default.nix, libs/wire-api-federation/src/Wire/API/Federation/Error.hs, libs/wire-api-federation/wire-api-federation.cabal, services/federator/src/Federator/Remote.hs
https://wearezeta.atlassian.net/browse/WPB-6998
=> Make federator error logs more informative.

cassandra-schema.cql, changelog.d/3-bug-fixes/WPB-6577, integration/integration.cabal, integration/test/API/Common.hs, integration/test/API/Spar.hs, integration/test/SetupHelpers.hs, integration/test/Test/Spar.hs, libs/wire-api/src/Wire/API/User.hs, libs/wire-api/src/Wire/API/User/Scim.hs, services/brig/src/Brig/API/User.hs, services/brig/src/Brig/Team/API.hs, services/spar/spar.cabal, services/spar/src/Spar/Data/Instances.hs, services/spar/src/Spar/Intra/Brig.hs, services/spar/src/Spar/Schema/Run.hs, services/spar/src/Spar/Schema/V18.hs, services/spar/src/Spar/Scim/Types.hs, services/spar/src/Spar/Scim/User.hs, services/spar/src/Spar/Sem/BrigAccess.hs, services/spar/src/Spar/Sem/BrigAccess/Http.hs, services/spar/src/Spar/Sem/ScimExternalIdStore.hs, services/spar/src/Spar/Sem/ScimExternalIdStore/Cassandra.hs, services/spar/src/Spar/Sem/ScimExternalIdStore/Mem.hs, services/spar/src/Spar/Sem/ScimExternalIdStore/Spec.hs, services/spar/test/Arbitrary.hs, services/spar/test/Test/Spar/Intra/BrigSpec.hs
For a description of the manual test approach, see comments of https://wearezeta.atlassian.net/browse/WPB-6577
=> WPB-6577 Fix user creation conflict in SCIM

changelog.d/3-bug-fixes/sns-arn-parsing, services/gundeck/default.nix, services/gundeck/gundeck.cabal, services/gundeck/src/Gundeck/Aws/Arn.hs, services/gundeck/src/Gundeck/Push.hs, services/gundeck/test/unit/Aws/Arn.hs, services/gundeck/test/unit/Main.hs
This commit contains two things:
1. Add fields to the log message such that mismatches between stored and app-provided data become more obvious.
2. Fix an AWS SNS Endpoint parsing bug: We parsed the environment up to the first dash. But, environment names may contain dashes themselves, thus we must accumulate them up to the last dash.
Tickets:
* https://wearezeta.atlassian.net/browse/WPB-6650
* https://wearezeta.atlassian.net/browse/WPB-6653
=> gundeck: Fix SNS endpoint parser (backport q1-2024)

changelog.d/3-bug-fixes/welcome-notifications, integration/integration.cabal, integration/test/Test/MLS/Notifications.hs, services/galley/src/Galley/API/MLS/Welcome.hs
This implements collecting welcome notifications by user before sending them to gundeck. Otherwise, gundeck would attempt to store one entry for each client, and one would overwrite the others.
We had already fixed a similar bug for MLS messages (https://github.com/wireapp/wire-server/pull/3610), but neglected to apply a similar fix to welcome messages.
https://wearezeta.atlassian.net/browse/WPB-6852
=> Welcome notification bug

changelog.d/3-bug-fixes/enqueue-lazy, integration/test/Test/Conversation.hs, services/galley/src/Galley/Intra/BackendNotificationQueue.hs
When sending an empty list of notification, we don't want to fail if federation is disabled.
https://wearezeta.atlassian.net/browse/WPB-7072
=> Lazily attempt to get rabbitmq channel

changelog.d/3-bug-fixes/welcome-notifications, integration/integration.cabal, integration/test/Test/MLS/Notifications.hs, services/galley/src/Galley/API/MLS/Welcome.hs
https://wearezeta.atlassian.net/browse/WPB-6852
=> Backport welcome notification fix

changelog.d/3-bug-fixes/WPB-6524, charts/nginz/templates/conf/_deeplink.json.tpl
https://wearezeta.atlassian.net/browse/WPB-6524
Test like this:
cd into `charts`
create file `nginz-overrides.yaml`
```shell
echo 'nginx_conf:
deeplink:
endpoints:
backendURL: "https://prod-nginz-https.wire.com"
backendWSURL: "https://prod-nginz-ssl.wire.com"
blackListURL: "https://clientblacklist.wire.com/prod"
teamsURL: "https://teams.wire.com"
accountsURL: "https://accounts.wire.com"
websiteURL: "https://wire.com"
title: "Leif Test"
apiProxy: # (optional)
host: "socks5.proxy.com"
port: 1080
needsAuthentication: true' > nginz-overrides.yaml
```
create file `nginz-secrets.yaml`
```shell
echo 'secrets:
basicAuth: "whatever"
zAuth:
publicKeys: 0UW38se1yeoc5bVNEvf5LyrHWGZkyvcGTVilK2geGdU=
oAuth:
publicKeys: |
{
"kty": "OKP",
"crv": "Ed25519",
"x": …
```
=> WPB-6524 Added optional api proxy attribute to deeplink json in nginz chart

changelog.d/3-bug-fixes/enqueue-lazy, integration/test/Test/Conversation.hs, services/galley/src/Galley/Intra/BackendNotificationQueue.hs
When sending an empty list of notification, we don't want to fail if federation is disabled.
https://wearezeta.atlassian.net/browse/WPB-7072
=> Lazily attempt to get rabbitmq channel (#3936)

changelog.d/2-features/WPB-6997-smallstep-accomp, charts/smallstep-accomp/Chart.yaml, charts/smallstep-accomp/README.md, charts/smallstep-accomp/templates/_helpers.tpl, charts/smallstep-accomp/templates/ca-password.yaml, charts/smallstep-accomp/templates/certs.yaml, charts/smallstep-accomp/templates/secrets.yaml, charts/smallstep-accomp/templates/server-block-configmap.yaml, charts/smallstep-accomp/templates/step-config.yaml, charts/smallstep-accomp/values.yaml
This PR udpates the Helm chart `smallstep-accomp`. It adds a configuration setup for `smallstep` for End-to-End Identity
Internal note: Upstreams changes from commit `0ea5726c53ff9f4a1641455a0def44f3c01c4e77`.
https://wearezeta.atlassian.net/browse/WPB-6997
=> Update smallstep-accomp Helm chart

changelog.d/5-internal/wpb-6329_ejpd_stuff, integration/default.nix, integration/integration.cabal, integration/test/API/BrigInternal.hs, integration/test/API/Cargohold.hs, integration/test/API/Common.hs, integration/test/SetupHelpers.hs, integration/test/Test/AssetDownload.hs, integration/test/Test/EJPD.hs, integration/test/Testlib/Assertions.hs, libs/wire-api/src/Wire/API/Routes/Internal/Brig/EJPD.hs, libs/wire-api/src/Wire/API/Routes/Internal/Cargohold.hs, services/brig/src/Brig/API/Internal.hs, services/brig/src/Brig/App.hs, services/brig/src/Brig/User/EJPD.hs, services/brig/test/integration/API/Internal.hs, services/brig/test/integration/API/Internal/Util.hs, services/brig/test/integration/Run.hs, services/cargohold/src/CargoHold/API/Public.hs, services/cargohold/src/CargoHold/API/V3.hs
https://wearezeta.atlassian.net/browse/WPB-6329
=> Make ejpd data model exhaustive

changelog.d/2-features/WPB-6783, integration/test/Test/MLS/One2One.hs, libs/wire-api/src/Wire/API/Routes/Internal/Galley.hs, services/brig/src/Brig/API/Connection.hs, services/brig/src/Brig/API/Connection/Remote.hs, services/brig/src/Brig/API/Federation.hs, services/brig/src/Brig/API/Internal.hs, services/brig/src/Brig/Effects/GalleyProvider.hs, services/brig/src/Brig/Effects/GalleyProvider/RPC.hs, services/brig/src/Brig/IO/Intra.hs, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/Query.hs, services/galley/src/Galley/API/Update.hs
The PR adds support for unblocking a user in an MLS 1-to-1 conversation.
Tracked by https://wearezeta.atlassian.net/browse/WPB-6783.
=> [WPB-6783] Support unblocking an MLS 1-to-1 conversation

changelog.d/2-features/WPB-6997-smallstep-accomp, charts/smallstep-accomp/Chart.yaml, charts/smallstep-accomp/README.md, charts/smallstep-accomp/requirements.yaml, charts/smallstep-accomp/templates/_helpers.tpl, charts/smallstep-accomp/templates/ca-password.yaml, charts/smallstep-accomp/templates/certs.yaml, charts/smallstep-accomp/templates/secrets.yaml, charts/smallstep-accomp/templates/server-block-configmap.yaml, charts/smallstep-accomp/templates/step-config.yaml, charts/smallstep-accomp/values.yaml
Add an exemplary configuration setup for smallstep for End-to-End Identity. Document new values in Helm chart.
Upstreaming/backporting https://github.com/wireapp/wire-server/pull/3932
Ticket: https://wearezeta.atlassian.net/browse/WPB-6997
=> Update smallstep-accomp Helm chart (#3932)

changelog.d/5-internal/smallstep-accomp-no-client-side-caching, charts/smallstep-accomp/templates/server-block-configmap.yaml
To ensure certificate revocations get active in a short time frame, disable caching of proxy results on client side by setting respective HTTP headers.
Ticket:  https://wearezeta.atlassian.net/browse/WPB-6904
=> smallstep-accomp: Prevent smallstep proxy caching

changelog.d/5-internal/smallstep-accomp-target-resolving, charts/smallstep-accomp/templates/server-block-configmap.yaml
Usually, proxy targets are resolved when nginx is started. This can lead to strange behavior if the target either doesn't exist (yet) or the DNS entry changes while nginx is running.
This little trick with the indirection via a variable should trigger the lookup(s) while nginx is running. The default behavior of the `resolver` directive is to update the target according to its TTL in the configured DNS server.
N.B. this a cherry-pick / backport of https://github.com/wireapp/wire-server/pull/3946
Ticket: https://wearezeta.atlassian.net/browse/WPB-6822
=> smallstep-accomp: Resolve proxy target on request (#3946)

changelog.d/3-bug-fixes/coturn-pre-stop-hook, charts/coturn/Chart.yaml
Update coturn image with bugfix to its pre-stop-hook from https://github.com/wireapp/coturn/pull/10 to allow coturn pods to terminate once their traffic has drained, instead of waiting for its terminationGracePeriod (up to 24 hours).
Cherry picked from: https://github.com/wireapp/wire-server/pull/3872
=> Cherry-pick: coturn prestop hook

changelog.d/5-internal/WPB-7155, charts/smallstep-accomp/values.yaml
In order for the CRL-proxy to function correctly, it needs to have CORS headers set.
We are now setting the CORS headers on the ingress level.
=> WPB 7155 smallstep-accomp CRL-Proxy CORS

changelog.d/4-docs/utctime-swagger, libs/types-common/src/Data/Json/Util.hs
Fix openapi docs inconsistency with datetime fields. We have two kinds of datetime fields: with and without a millisecond component. They were both documented as having the millisecond component.
https://wearezeta.atlassian.net/browse/WPB-6529
=> Fix openapi docs of UTCTime and UTCTimeMillis

libs/hscim/CHANGELOG, libs/hscim/default.nix, libs/hscim/hscim.cabal
https://wearezeta.atlassian.net/browse/WPB-7176
prerequisite for https://wearezeta.atlassian.net/browse/WPB-2970
https://hackage.haskell.org/package/hscim-0.4.0.2 has been published, this PR is to keep track of that version in wire-server.
=> Bump hscim version and deps

libs/http2-manager/default.nix, libs/http2-manager/http2-manager.cabal, libs/http2-manager/src/HTTP2/Client/Manager/Internal.hs, libs/http2-manager/test/Test/HTTP2/Client/ManagerSpec.hs, nix/haskell-pins.nix, nix/manual-overrides.nix
Removed a pin that was introduced in 8f823f2517f, as it only made things worse.
- ~~[ ] Add a new entry in an appropriate subdirectory of `changelog.d`~~
=> Revert http2 pin.

changelog.d/2-features/gundeck-configure-notificationTTL, charts/gundeck/templates/configmap.yaml, charts/gundeck/values.yaml
Decreasing the notification TTL can e.g. safe database space on test environments.
=> gundeck: Make notificationTTL configurable

Makefile, changelog.d/2-features/WPB-6717, charts/brig/templates/configmap.yaml, charts/brig/templates/secret.yaml, charts/elasticsearch-ephemeral/templates/es.yaml, charts/elasticsearch-index/templates/create-index.yaml, charts/elasticsearch-index/templates/migrate-data.yaml, charts/elasticsearch-index/templates/secret.yaml, charts/elasticsearch-index/values.yaml, charts/integration/templates/integration-integration.yaml, deploy/dockerephemeral/docker-compose.yaml, deploy/dockerephemeral/federation-v0/brig.yaml, docs/src/developer/reference/config-options.md, hack/helm_vars/wire-server/values.yaml.gotmpl, libs/types-common/src/Data/Credentials.hs, libs/types-common/src/Util/Options.hs, libs/types-common/types-common.cabal, services/brig/brig.integration.yaml, services/brig/src/Brig/App.hs, services/brig/src/Brig/Index/Eval.hs, services/brig/src/Brig/Index/Migrations.hs, services/brig/src/Brig/Index/Options.hs, services/brig/src/Brig/Options.hs, services/brig/src/Brig/User/API/Search.hs, services/brig/src/Brig/User/Search/Index.hs, services/brig/test/integration/API/Search.hs, services/brig/test/integration/API/Search/Util.hs, services/brig/test/integration/Index/Create.hs, services/brig/test/resources/elasticsearch-credentials.yaml
=> WPB-6717 ES Credentials

libs/wire-api/src/Wire/API/Routes/Internal/Brig.hs, services/brig/src/Brig/API/Internal.hs
https://wearezeta.atlassian.net/browse/WPB-7265
New behavior should be trivially identical to the old one, but the routing table tree makes more sense now.
No changelog entry needed.
=> Re-arrange internal routing table types in brig to make more sense.

.envrc, changelog.d/2-features/redis-creds, charts/gundeck/templates/deployment.yaml, charts/gundeck/templates/secret.yaml, charts/gundeck/templates/tests/configmap.yaml, charts/gundeck/templates/tests/gundeck-integration.yaml, charts/gundeck/templates/tests/secret.yaml, charts/integration/templates/integration-integration.yaml, charts/integration/templates/secret.yaml, deploy/dockerephemeral/docker-compose.yaml, deploy/dockerephemeral/docker/redis-master-mode.conf, deploy/dockerephemeral/docker/redis-node-1.conf, deploy/dockerephemeral/docker/redis-node-2.conf, deploy/dockerephemeral/docker/redis-node-3.conf, deploy/dockerephemeral/docker/redis-node-4.conf, deploy/dockerephemeral/docker/redis-node-5.conf, deploy/dockerephemeral/docker/redis-node-6.conf, docs/src/developer/reference/config-options.md, hack/helm_vars/redis-cluster/values.yaml.gotmpl, hack/helm_vars/wire-server/values.yaml.gotmpl, hack/helmfile.yaml, nix/haskell-pins.nix, nix/manual-overrides.nix, services/gundeck/src/Gundeck/Env.hs, services/gundeck/src/Gundeck/Presence/Data.hs, services/gundeck/src/Gundeck/Redis.hs, services/gundeck/test/integration/API.hs, services/gundeck/test/integration/Util.hs
https://wearezeta.atlassian.net/browse/WPB-6721
Upstream PR: https://github.com/informatikr/hedis/pull/224
=> gundeck: Support authenticating to redis

changelog.d/5-internal/disable-integration-chart, charts/wire-server/values.yaml, hack/helm_vars/wire-server/values.yaml.gotmpl
Fixup to #3171. This PR updates the `wire-server` chart so that it doesn't include the `integration` chart by default.
Without this PR the [integration](https://github.com/wireapp/wire-server/tree/36bae6e2ce25b3cddeb9c7d72b2b48fb9d89b270/charts/integration) chart is installed, which creates an superfluous kubernetes objects, including an (internal) ingress for a subdomain of `svc.cluster.local`.
Disabling works because of [this tag](https://github.com/wireapp/wire-server/blob/f87b3b39803d79906e79ba573eed2df46b02e9ae/charts/wire-server/requirements.yaml#L131C1-L131C1)
=> wire-server chart: Disable integration chart by default

changelog.d/2-features/WPB-6783, integration/test/Test/MLS/One2One.hs, libs/wire-api/src/Wire/API/Routes/Internal/Galley.hs, services/brig/src/Brig/API/Connection.hs, services/brig/src/Brig/API/Connection/Remote.hs, services/brig/src/Brig/API/Internal.hs, services/brig/src/Brig/Effects/GalleyProvider.hs, services/brig/src/Brig/Effects/GalleyProvider/RPC.hs, services/brig/src/Brig/IO/Intra.hs, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/Query.hs, services/galley/src/Galley/API/Update.hs
This ports PR #3940 that has been merged to develop, to the `q1-2024` branch.
Tracked by https://wearezeta.atlassian.net/browse/WPB-6783.
=> [WPB-6783] Support unblocking an MLS 1-to-1 conversation (the `q1-2024` port)

changelog.d/5-internal/WPB-7416, services/galley/galley.cabal, services/galley/src/Galley/API/Clients.hs, services/galley/src/Galley/App.hs, services/galley/src/Galley/Cassandra/Client.hs, services/galley/src/Galley/Cassandra/Code.hs, services/galley/src/Galley/Cassandra/Conversation.hs, services/galley/src/Galley/Cassandra/Conversation/Members.hs, services/galley/src/Galley/Cassandra/ConversationList.hs, services/galley/src/Galley/Cassandra/CustomBackend.hs, services/galley/src/Galley/Cassandra/LegalHold.hs, services/galley/src/Galley/Cassandra/Proposal.hs, services/galley/src/Galley/Cassandra/SearchVisibility.hs, services/galley/src/Galley/Cassandra/Services.hs, services/galley/src/Galley/Cassandra/SubConversation.hs, services/galley/src/Galley/Cassandra/Team.hs, services/galley/src/Galley/Cassandra/TeamFeatures.hs, services/galley/src/Galley/Cassandra/TeamNotifications.hs, services/galley/src/Galley/Cassandra/Util.hs, services/galley/src/Galley/External.hs, services/galley/src/Galley/Intra/BackendNotificationQueue.hs, services/galley/src/Galley/Intra/Effects.hs, services/galley/src/Galley/Intra/Federator.hs
Ticket: https://wearezeta.atlassian.net/browse/WPB-7416
=> early exit when deleting already gone client

changelog.d/5-internal/port-2fa-tests, integration/integration.cabal, integration/test/API/BrigInternal.hs, integration/test/API/GalleyInternal.hs, integration/test/API/Nginz.hs, integration/test/Test/Login.hs, services/brig/test/integration/API/User/Auth.hs
=> [chore] Port 2FA tests

changelog.d/5-internal/elasticsearch-ephemeral_configurable_password, charts/elasticsearch-ephemeral/templates/es.yaml, charts/elasticsearch-ephemeral/values.yaml
This way we can use different passwords on our test systems. Ensuring that the password is really configurable (and not accidentally hardcoded somewhere.)
Ticket: https://wearezeta.atlassian.net/browse/WPB-7283
=> elasticsearch-ephemeral: Provide password as value

changelog.d/5-internal/wpb6170-bump-hsaml2-dep, nix/haskell-pins.nix, services/galley/galley.cabal, services/spar/spar.cabal
https://wearezeta.atlassian.net/browse/WPB-6170
pls also take a look at https://github.com/wireapp/saml2-web-sso/pull/85 when you review this.
=> Bump hsaml2, saml2-web-sso dependencies.

changelog.d/3-bug-fixes/WPB-7415, integration/test/Test/MLS/One2One.hs, services/galley/src/Galley/API/MLS/One2One.hs
The `GET /conversations/one2one/{usr_domain}/{usr}` endpoint would always return an empty list of other members in case the MLS 1-to-1 conversation was hosted on a remote backend. The PR fixes the bug.
This is the `develop` branch counterpart of the already approved PR #3993.
Tracked by https://wearezeta.atlassian.net/browse/WPB-7415.
=> [WPB-7415] Fix the list of other members in an MLS 1-to-1 conversation (the `develop` counterpart)

Makefile, changelog.d/5-internal/add-ldap-chart-in-release
https://wearezeta.atlassian.net/browse/WPB-7170
=> add ldap-scim-bridge chart in wire release

changelog.d/3-bug-fixes/WPB-7415, integration/test/Test/MLS/One2One.hs, services/galley/src/Galley/API/MLS/One2One.hs
The `GET /conversations/one2one/{usr_domain}/{usr}` endpoint would always return an empty list of other members in case the MLS 1-to-1 conversation was hosted on a remote backend. The PR fixes the bug.
Tracked by https://wearezeta.atlassian.net/browse/WPB-7415.
=> [WPB-7415] Fix the list of other members in an MLS 1-to-1 conversation

Makefile, changelog.d/5-internal/SEC-596, hack/bin/Sbom.hs, hack/bin/bombon.hs, nix/all-toplevel-derivations.nix, nix/default.nix, nix/overlay.nix, nix/pkg-info.nix, nix/pkgs/sbomqs/default.nix, nix/wire-server.nix
https://wearezeta.atlassian.net/browse/SEC-596
=> [feat] use new script for sbom generation

hack/bin/Sbom.hs
@supersven this was actually no `PathInfo`, it just looked similar :eyes:
This reverts commit 71c8c596d5b8024847730d2aac6a5eec1edb4b9b.
- ~~Add a new entry in an appropriate subdirectory of `changelog.d`~~ n/a
=> Revert "[chore] use `PathInfo` consistently" [skip-ci]

changelog.d/5-internal/WPB-8713, integration/test/API/Galley.hs, integration/test/API/GalleyInternal.hs, integration/test/Test/Demo.hs, integration/test/Test/FeatureFlags.hs, integration/test/Test/Login.hs, integration/test/Test/User.hs, services/galley/src/Galley/API/Teams/Features/Get.hs
https://wearezeta.atlassian.net/browse/WPB-8713
=> WPB-8713 Optimize feature configs tests

changelog.d/4-docs/start-coding-conventions, docs/src/developer/developer/coding-conventions.md
https://wearezeta.atlassian.net/browse/WPB-7222
=> [WPB-7222] (part 2) add coding-conventions.md to developer docs

changelog.d/0-release-notes/WPB-227, charts/brig/templates/configmap.yaml
https://wearezeta.atlassian.net/browse/WPB-227
=> improve release notes/make brig's multiSFT optional

Makefile, changelog.d/5-internal/WPB-8712, treefmt.toml
https://wearezeta.atlassian.net/browse/WPB-8712
=> [WPB-8712] use treefmt for everything

changelog.d/1-api-changes/gzip, services/proxy/default.nix, services/proxy/proxy.cabal, services/proxy/src/Proxy/Run.hs, services/spar/default.nix, services/spar/spar.cabal, services/spar/src/Spar/Run.hs
Add gzip middlewares to spar and proxy. This makes it possible for clients to uniformly use gzipped requests across all endpoints.
https://wearezeta.atlassian.net/browse/WPB-8718
=> Add gzip middlewares to spar and proxy

changelog.d/5-internal/fluent-bit, charts/fluent-bit/requirements.yaml, charts/fluent-bit/values.yaml
https://wearezeta.atlassian.net/browse/WPB-7431
=> Bump fluent-bit chart version and add example values for syslog

Makefile
Followup to https://github.com/wireapp/wire-server/pull/4014
=> Remove sftd from list of published charts

Makefile, treefmt.toml
This is a follow up for #4000  because caching gets invalidated by running with a subset of formatters (see https://github.com/numtide/treefmt/issues/286) we don't use hlint in treefmt at all. This is a bit unfortunate, I think we can readd it though at some point 
- n/a~~Add a new entry in an appropriate subdirectory of `changelog.d`~~
=> [chore] don't use treefmt for hlint, readd the remove hlint rules

docs/src/developer/reference/config-options.md
The example command line for generating an ECDSA private key with `openssl` was incorrect.
=> Fix openssl example in docs

Makefile, treefmt.toml
sorry for issues caused
- ~~Add a new entry in an appropriate subdirectory of `changelog.d`~~
=> Use makefile targets again 

changelog.d/5-internal/federator-request-id, libs/wai-utilities/src/Network/Wai/Utilities/Server.hs, services/federator/src/Federator/Response.hs
Make it possible for services to specify a different way to extract the ID of a request. For federator requests, the ID is in a different header, so the `catchErrors` middleware needs to be aware of the difference when logging.
Related to: https://wearezeta.atlassian.net/browse/WPB-7161
=> Generalise catchErrors middleware

changelog.d/5-internal/mls-test-cli-update, nix/pkgs/mls-test-cli/default.nix
Update to mls-test-cli version 0.12, based on openmls's `wire/stable` stable.
mls-test-cli commit: https://github.com/wireapp/mls-test-cli/commit/09aaf66585039e0ba0af78f292af90b90f30c325
https://wearezeta.atlassian.net/browse/WPB-8684
=> Update mls-test-cli to version 0.12

nix/overlay.nix, services/nginz/third_party/nginx-zauth-module/zauth_module.c
https://wearezeta.atlassian.net/browse/WPB-5360
turns out it was not that hard after all, I could trace back our compile issue to a refactoring done in this commit
https://github.com/nginx/nginx/commit/3aef1d693f3cc431563a7e6a6aba6a34e5290f03?diff=split&w=1 and that was quite easy to fix
=> [WPB-5360] update the nginz nginx module to support nginx 1.26

integration/test/Test/MLS/One2One.hs
Check that the backend has an up-to-date view of the ciphersuite of a one-to-one conversation after the first commit. This is a follow-up to #4009. A similar assertion has been added when backporting #4009 to q1-2024, so it makes sense to add it here too.
=> Add assertions to MLS one-to-one test

cassandra-schema.cql, changelog.d/2-features/delete-voip-tokens, charts/cassandra-migrations/templates/gundeck-migrate-data.yaml, charts/cassandra-migrations/values.yaml, nix/wire-server.nix, services/gundeck/default.nix, services/gundeck/gundeck.cabal, services/gundeck/migrate-data/main.hs, services/gundeck/migrate-data/src/Gundeck/DataMigration.hs, services/gundeck/migrate-data/src/Gundeck/DataMigration/Types.hs, services/gundeck/migrate-data/src/Run.hs, services/gundeck/migrate-data/src/V1_DeleteApnsVoipTokens.hs, services/gundeck/src/Gundeck/Schema/Run.hs, services/gundeck/src/Gundeck/Schema/V11.hs
This also introduces the concept of data-migrations in gundeck. They are run as post-install and post-upgrade hooks in cassandra-migrations helm chart, just like galley-migrate-data and spar-migrate-data.
https://wearezeta.atlassian.net/browse/WPB-9027
=> gundeck: Delete all APNS_VOIP and APNS_VOIP_SANDBOX push tokens

changelog.d/3-bug-fixes/mixed-ciphersuite, integration/test/Test/MLS.hs, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/Cassandra/Conversation.hs, services/galley/src/Galley/Cassandra/Queries.hs, services/galley/src/Galley/Effects/ConversationStore.hs
Ciphersuite 1 was still used as the hardcoded ciphersuite for the newly created MLS group after a proteus → mixed transition. This made it impossible to use other ciphersuites for the MLS part of a mixed conversation.
https://wearezeta.atlassian.net/browse/WPB-9142
=> Fix hardcoded use of ciphersuite 1 when switching to mixed protocol

changelog.d/3-bug-fixes/mixed-ciphersuite, integration/test/Test/MLS.hs, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/Cassandra/Conversation.hs, services/galley/src/Galley/Cassandra/Queries.hs, services/galley/src/Galley/Effects/ConversationStore.hs
https://wearezeta.atlassian.net/browse/WPB-9142
=> Backport mixed protocol ciphersuite fix #4048

Makefile
=> [fix] elasticsearch reset on local db-reset

changelog.d/5-internal/federator-request-id, libs/wai-utilities/src/Network/Wai/Utilities/Server.hs, services/federator/src/Federator/Response.hs
=> [WPB-7161] Generalise catchErrors middleware

changelog.d/5-internal/elasticsearch, deploy/dockerephemeral/federation-v0/brig.yaml, deploy/dockerephemeral/federation-v0/nginz/conf/integration.conf, deploy/dockerephemeral/federation-v0/nginz/conf/nginx.conf
https://wearezeta.atlassian.net/browse/WPB-9000
=> dockerephemeral environment: give ES an http interface (needed for old brig)

changelog.d/3-bug-fixes/redis, nix/haskell-pins.nix
https://wearezeta.atlassian.net/browse/WPB-9102
Upstream PR: https://github.com/informatikr/hedis/pull/227
=> WPB-9102 gundeck: Better tolerance for redis-cluster restarts

changelog.d/5-internal/WPB-9495, charts/nginz/templates/conf/_nginx.conf.tpl, charts/nginz/values.yaml
This adds a new key `allowlisted_fqdn_origins` to the `nginx_conf` value of the `nginz` chart.
The purpose is to add more domain name entries in the `cors_header` map of the nginx config in test/dev/staging environments.
Made use of by https://github.com/zinfra/cailleach/pull/2147
=> WPB-9495: nginz: configure extra origins

changelog.d/3-bug-fixes/federator-client-cert-chain, services/federator/src/Federator/Monitor/Internal.hs
Without this openssl doesn't forward to whole chain causing mTLS to not succeed.
https://wearezeta.atlassian.net/browse/WPB-9692
=> federator: Expect a client certificate to be the certificate chain

deploy/dockerephemeral/docker-compose.yaml
https://wearezeta.atlassian.net/browse/WPB-2624
Drop-In replacement for Docker images hosted with Julia's private Dockerhub account.
=> moving docker images from Julia's private repo to quay

changelog.d/2-features/coturn-params, charts/coturn/templates/configmap-coturn-conf-template.yaml, charts/coturn/templates/statefulset.yaml, charts/coturn/values.yaml
This PR adds configuration options in the `coturn` helm chart for settings
- `relay-ip`
- `external-ip`
- `prometheus-ip`
- `federation-listening-ip`
It also adds a `__COTURN_HOST_IP__` template variable which will be substitued by the host ip of the `k8s` node that is running coturn.
This PR is backwards-compatible to `values.yaml` files written for version of this helm charts without this PR: new variables have defaults that match their previous hardcoded value.
=> coturn: Add IP configuration options

libs/http2-manager/src/HTTP2/Client/Manager/Internal.hs, libs/http2-manager/test/Test/HTTP2/Client/ManagerSpec.hs, libs/wire-api-federation/src/Wire/API/Federation/Client.hs, nix/haskell-pins.nix, nix/manual-overrides.nix
this upgrades warp including the bug fix in http2
- n/a Add a new entry in an appropriate subdirectory of `changelog.d`
=> followup: update warp

changelog.d/3-bug-fixes/WPB-9685, integration/test/Test/LegalHold.hs, services/galley/src/Galley/API/LegalHold.hs
https://wearezeta.atlassian.net/browse/WPB-9685
=> [WPB-9685] don't react with "legalhold already disabled" when on pending state

charts/brig/templates/tests/brig-integration.yaml, charts/galley/templates/tests/galley-integration.yaml
Allow nil rabbitmq tlsCaSecretRef in brig and galley integration charts.
=> Allow nil rabbitmq CA in integration charts

integration/test/MLS/Util.hs, integration/test/Test/MLS/SubConversation.hs, integration/test/Testlib/Cannon.hs
This PR stemmed from an unsuccessful attempt at reproducing the duplicate proposal issue. It contains a new test for subconversations.
https://wearezeta.atlassian.net/browse/WPB-9210
=> Add subconversation test

changelog.d/5-internal/reduce-thread-killed-log-noise, libs/wai-utilities/src/Network/Wai/Utilities/Server.hs
Also don't log anything. This happens when warp decides to reap a worker thread,
it could happen because the client has already closed the connection. Creating
responses and logging seems unnecessary.
https://wearezeta.atlassian.net/browse/WPB-7161
=>  catchErrors middleware: Don't create responses for ThreadKilled errors 

changelog.d/3-bug-fixes/repeated-rtsopts, services/background-worker/background-worker.cabal, services/brig/brig.cabal, services/cannon/cannon.cabal, services/federator/federator.cabal, services/spar/spar.cabal, tools/db/auto-whitelist/auto-whitelist.cabal, tools/db/find-undead/find-undead.cabal, tools/db/inconsistencies/inconsistencies.cabal, tools/db/migrate-sso-feature-flag/migrate-sso-feature-flag.cabal, tools/db/move-team/move-team.cabal, tools/db/repair-brig-clients-table/repair-brig-clients-table.cabal, tools/db/service-backfill/service-backfill.cabal, tools/fedcalls/fedcalls.cabal
GHC does not support repeated `--with-rtsopts` options, and it simply applies the last one. This means many of the baked-in options were actually not being passed, including `-N` for some of the services and `-T` for cannon.
=> Fix repeated with-rtsopts option

changelog.d/3-bug-fixes/metric-names, libs/metrics-core/src/Data/Metrics/AWS.hs, libs/wai-utilities/src/Network/Wai/Utilities/Server.hs, services/brig/src/Brig/API/User.hs, services/brig/src/Brig/Data/Client.hs, services/brig/src/Brig/User/Auth/Cookie.hs, services/brig/src/Brig/User/Search/Index.hs, services/cannon/src/Cannon/Run.hs, services/cargohold/src/CargoHold/Metrics.hs, services/galley/src/Galley/Run.hs, services/gundeck/src/Gundeck/Push/Native.hs, services/gundeck/src/Gundeck/Push/Websocket.hs, services/gundeck/src/Gundeck/ThreadBudget/Internal.hs
=> Fix names of metrics so they do not contain any dots

services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
=> Add spar integration test about empty scim search results.

changelog.d/2-features/WPB-9773, integration/test/Test/MLS/SubConversation.hs, services/galley/src/Galley/API/MLS/SubConversation.hs
https://wearezeta.atlassian.net/browse/WPB-9773
=> allow subconversations for MLS 1-1 conversation

changelog.d/5-internal/optimize-list-users, libs/wire-subsystems/src/Wire/UserSubsystem/Interpreter.hs
The endpoint typically takes 0.5-1 second to respond with ~200 users. It is called by the webapp on boot for every known user (not sure why) making UX very slow. 
Here is a chart from prod showing response times for this particular endpoint:
Local tests show about 70% reduction in response time.
=> Concurrently fetch user profiles from the DB

changelog.d/3-bug-fixes/WPB-10207, integration/test/API/Brig.hs, integration/test/Test/MLS/KeyPackage.hs, services/brig/src/Brig/API/MLS/CipherSuite.hs, services/brig/src/Brig/API/MLS/KeyPackages.hs, services/brig/src/Brig/Data/MLS/KeyPackage.hs
=> WPB-10207 Match cipher suite tag in query parameters against key packages on replacing key packages

changelog.d/2-features/sft-username, services/brig/brig.cabal, services/brig/default.nix, services/brig/src/Brig/Calling.hs, services/brig/src/Brig/Calling/API.hs, services/brig/src/Brig/Calling/Internal.hs, services/brig/test/unit/Test/Brig/Calling.hs, services/brig/test/unit/Test/Brig/Calling/Internal.hs
https://wearezeta.atlassian.net/browse/WPB-8587
=> Use user ID hashes as SFT usernames

changelog.d/5-internal/wpb6985-better-integration-test-logs, integration/default.nix, integration/integration.cabal, integration/test/Test/Cargohold/API.hs, integration/test/Test/Demo.hs, integration/test/Testlib/ModService.hs, integration/test/Testlib/ModService/ServiceInstance.hs, integration/test/Testlib/Run.hs
* Duplicate console output of services from log noise to error msg.
* integration: Store stdout and stderr chans in the ServiceInstance (Also ensure logs are kept for nginz)
* Stronger signal to backend processes when terminating.  (The timeout before this change wasn't effective; waitForProcess blocks beyond the timeout if the process doesn't terminate.)
* Make default log level in ModServices easier to change.
* shouldMatch argument order matters for error message!
* Use lifted-base (instead of re-inventing it).
* Use timestats library to dig into where the timeouts are caused.
=> WPB-9733 backport flakiness fixes

services/brig/src/Brig/API/Public/Swagger.hs
some parts of it were outdated or wrong, and what was valid is now tracked in WPB-10315, WPB-10316.
=> Remove FUTUREWORK about openapi3/swagger.

Makefile, cabal.project, integration/integration.cabal, libs/types-common-journal/types-common-journal.cabal, libs/wire-message-proto-lens/wire-message-proto-lens.cabal, nix/default.nix, nix/haskell-pins.nix, nix/manual-overrides.nix, nix/overlay-docs.nix, nix/sources.json, nix/wire-server.nix, services/federator/default.nix, services/federator/federator.cabal, services/federator/test/integration/Main.hs, services/federator/test/integration/Test/Federator/Util.hs, services/spar/default.nix, services/spar/spar.cabal, services/spar/test-integration/Main.hs
=> [feat] bump nixpkgs - allow cabal-install 3.12

changelog.d/2-features/helm-coturn-service-annotations, charts/coturn/templates/service.yaml, charts/coturn/values.yaml
This can e.g. be used to set external-dns annotations. Or, any other annotations (depending on the setup of the K8s cluster.) We'll be using it in our internal deployments to configure `external-dns`.
I've tested this manually on `sven-test` by pointing the `chart` of the Helm release to my local checkout.
=> coturn: Allow setting of K8s annotations at the Service

changelog.d/5-internal/user-features, services/galley/src/Galley/API/Public/Bot.hs, services/galley/src/Galley/API/Public/Feature.hs, services/galley/src/Galley/API/Teams/Features.hs, services/galley/src/Galley/API/Teams/Features/Get.hs
This is a refactoring of the user feature lookup logic. It removes a redundant team lookup and a gratuitous CPS.
Followup to #4164.
https://wearezeta.atlassian.net/browse/WPB-10323
=> Simplify user feature logic

docs/src/understand/single-sign-on/understand/main.md
(The old phrasing can be interpreted as suggesting that `NameID` can not be an email, which is false.)
=> Small clarification in SAML/SCIM docs.

changelog.d/4-docs/revert-wpb8628, integration/test/Test/AccessUpdate.hs, integration/test/Test/Login.hs, libs/zauth/test/ZAuth.hs, services/brig/test/integration/API/User/Account.hs, services/brig/test/integration/API/User/Auth.hs, services/brig/test/integration/API/User/Client.hs, services/brig/test/integration/API/User/Handles.hs, services/federator/test/integration/Test/Federator/IngressSpec.hs, services/federator/test/integration/Test/Federator/InwardSpec.hs, services/federator/test/unit/Test/Federator/ExternalServer.hs, services/federator/test/unit/Test/Federator/InternalServer.hs, services/federator/test/unit/Test/Federator/Options.hs, services/federator/test/unit/Test/Federator/Remote.hs, services/federator/test/unit/Test/Federator/Validation.hs, services/galley/test/integration/API.hs, services/galley/test/integration/API/Federation.hs, services/galley/test/integration/API/Teams.hs, services/spar/test-integration/Test/Spar/APISpec.hs, services/spar/test-integration/Test/Spar/Scim/AuthSpec.hs, services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
https://wearezeta.atlassian.net/browse/WPB-10497
=> Re-introduce test case tags for BSI audit (revert #4041).

services/brig/src/Brig/API/Public.hs, services/brig/src/Brig/API/User.hs, services/brig/src/Brig/Data/User.hs
Brig.API.User still had functions referencing phones unnecessarily.
=> [chore] Deleted dangling phone references in Brig

changelog.d/5-internal/todo, libs/imports/src/Imports.hs
adds the `todo` function and the `TODO` pattern to `Imports`. The documentation hopefully clearly tells you how they work.
=> add the `todo` function and the `TODO` pattern

nix/sources.json
updates treefmt to treefmt 2.0.4 which includes a fix to the segfaulting behaviour. 
=> [fix] update treefmt s.t. it doesn't segfault anymore

changelog.d/5-internal/feature-flag-refactoring-2, libs/galley-types/default.nix, libs/galley-types/galley-types.cabal, libs/galley-types/src/Galley/Types/Teams.hs, libs/wire-api/src/Wire/API/Error.hs, libs/wire-api/src/Wire/API/Event/FeatureConfig.hs, libs/wire-api/src/Wire/API/Routes/Features.hs, libs/wire-api/src/Wire/API/Routes/Internal/Galley.hs, libs/wire-api/src/Wire/API/Routes/Named.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/Feature.hs, libs/wire-api/src/Wire/API/Team/Feature.hs, libs/wire-api/wire-api.cabal, services/brig/test/integration/API/User/Util.hs, services/galley/default.nix, services/galley/galley.cabal, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/Public/Feature.hs, services/galley/src/Galley/API/Teams/Features.hs, services/galley/test/integration/API/Teams.hs, services/galley/test/integration/API/Util/TeamFeature.hs, tools/stern/src/Stern/API.hs, tools/stern/src/Stern/Intra.hs
Follow-up to #4181.
This PR reorganises and simplifies the servant endpoints related to features.
https://wearezeta.atlassian.net/browse/WPB-10323
=> Feature flag refactoring (part 2)

Makefile, changelog.d/5-internal/migrate-postgres-chart, charts/postgresql/Chart.yaml, charts/postgresql/README.md, charts/postgresql/requirements.yaml, charts/postgresql/values.yaml
=> remove postgres wrapper chart from wire-server

changelog.d/1-api-changes/jwk, integration/test/API/Galley.hs, integration/test/Test/MLS/Keys.hs, libs/wire-api/src/Wire/API/MLS/Keys.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/MLS.hs, services/galley/src/Galley/API/MLS.hs, services/galley/src/Galley/API/Public/MLS.hs
This removes the new endpoint for fetching JWK public keys, and replaces it with a backwards-compatible change on the existing endpoint, namely a query parameter determining the format (`raw` vs `jwk`).
https://wearezeta.atlassian.net/browse/WPB-10606
=> Add format paramter to mls public key endpoint

hack/bin/integration-teardown-federation.sh
This should fix CI teardown failures.
=> [fix] Export FEDERATION_DOMAIN_BASE vars for teardown.

changelog.d/5-internal/WPB-10335, charts/brig/templates/deployment.yaml, charts/cannon/templates/statefulset.yaml, charts/cargohold/templates/deployment.yaml, charts/demo-smtp/templates/deployment.yaml, charts/fake-aws-s3/templates/reaper.yaml, charts/fake-aws-ses/templates/deployment.yaml, charts/fake-aws-sns/templates/deployment.yaml, charts/fake-aws-sqs/templates/deployment.yaml, charts/federator/templates/deployment.yaml, charts/galley/templates/deployment.yaml, charts/gundeck/templates/deployment.yaml, charts/legalhold/templates/deployment.yaml, charts/nginz/templates/deployment.yaml, charts/openldap/templates/openldap.yaml, charts/outlook-addin/templates/deployment.yaml, charts/proxy/templates/deployment.yaml, charts/reaper/templates/deployment.yaml, charts/restund/templates/statefulset.yaml, charts/spar/templates/deployment.yaml
https://wearezeta.atlassian.net/browse/WPB-10335
=> Wpb 10335 | Ensure pods are distributed evenly on each k8s node

libs/wire-api/src/Wire/API/Team/Feature.hs, services/cargohold/cargohold.cabal, services/cargohold/default.nix, services/cargohold/test/integration/API/Util.hs, services/spar/test-integration/Util/Core.hs, weeder.toml
It seems data-migration was the reason for the over 800 false positives after all.
=> [weed] Added data-migration to weed route, removed more dead code.

changelog.d/2-features/upgrade-rabbitmq, charts/rabbitmq/requirements.yaml, deploy/dockerephemeral/docker-compose.yaml
Use latest stable RabbitMQ version (`3.13.7`) and Helm chart (`14.6.9`) - one is implied by the other.
This is compatible to our backend:
- I ran tests locally against a docker-compose deployment
- The Helmfile deployment for the CI test runs uses the chart: https://github.com/wireapp/wire-server/blob/sventennie%2Fupgrade-to-latest-stable-rabbitmq/hack/helmfile.yaml#L160
=> upgrade to latest stable rabbitmq

hack/helm_vars/wire-server/values.yaml.gotmpl, integration/test/Test/FeatureFlags.hs, services/galley/galley.integration.yaml, services/galley/src/Galley/Cassandra/GetAllTeamFeatureConfigs.hs
https://wearezeta.atlassian.net/browse/WPB-10985
https://github.com/wireapp/wire-server/pull/4233
=> WPB-10985 `crlProxy` attribute missing from mls E2EID team config

changelog.d/4-docs/mls-test-tags, integration/test/Test/AccessUpdate.hs, integration/test/Test/MLS.hs, integration/test/Test/MLS/Message.hs, services/galley/test/integration/API.hs, services/galley/test/integration/API/MLS.hs
Move test doc tags from proteus to MLS
Deleted some of the documentation start and ending tags from Proteus
tests and added them to some of the MLS tests.
Deleted tags from:
- `postCryptoMessageVerifyMsgSentAndRejectIfMissingClient`
- `postCryptoMessageVerifyRejectMissingClientAndRepondMissingPrekeysJson`
- `postCryptoMessageVerifyRejectMissingClientAndRespondMissingPrekeysProto`
- `postMessageClientNotInGroupDoesNotReceiveMsg`
- `postMessageRejectIfMissingClients`
- `postCryptoMessageVerifyCorrectResponseIfIgnoreAndReportMissingQueryParam`
- `postMessageQualifiedLocalOwningBackendMissingClients`
Added tags to
- `testSenderNotInConversation`
- `testApplicationMessage`
- `testExternalCommitNotMember `
- `testCommitNotReferencingAllProposals `
- `testAddUserPartial`
Also generalised …
=> Move test documentation tags from proteus to MLS

changelog.d/3-bug-fixes/WBP-8790, hack/helm_vars/wire-server/values.yaml.gotmpl, integration/test/Test/FeatureFlags.hs, services/galley/galley.integration.yaml, services/galley/src/Galley/Cassandra/MakeFeature.hs
https://wearezeta.atlassian.net/browse/WPB-10985
=> Fix clrProxy field of MLSE2EId feature flag

services/brig/test/integration/Run.hs
=> Work around legacy integration test resource leak.

changelog.d/2-features/block-lh-for-mls-users, integration/test/Test/LegalHold.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/LegalHold.hs, services/galley/src/Galley/API/LegalHold.hs
=> [WPB-10783] Prevent MLS-Legalhold interactions

libs/types-common/src/Data/Qualified.hs, services/galley/src/Galley/API/MLS/Message.hs
ADTs are simpler, easier to reason about and cover this specific case better, without us having to override completeness checks with pragmas.
=> [chore] Replace pattern synomyn with ADT.

changelog.d/1-api-changes/wpb-10708, integration/test/API/Brig.hs, integration/test/API/Galley.hs, integration/test/Test/Teams.hs, integration/test/Testlib/Assertions.hs, libs/wire-api/src/Wire/API/Error/Brig.hs, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs, libs/wire-api/src/Wire/API/User.hs, services/brig/src/Brig/API/Public.hs, services/brig/src/Brig/API/Types.hs, services/brig/src/Brig/API/User.hs
Add brig endpoint `/upgrade-personal-to-team` to create a new team and make the user an owner. Sending confirmation emails will be done in a [followup PR](https://github.com/wireapp/wire-server/pull/4253).
https://wearezeta.atlassian.net/browse/WPB-10708
=> [WPB-10708] personal account to own team

integration/test/Test/Conversation.hs, integration/test/Testlib/Assertions.hs, services/galley/test/integration/API.hs, services/galley/test/integration/API/Federation/Util.hs, services/galley/test/integration/API/Util.hs
https://wearezeta.atlassian.net/browse/WPB-11186
=> [WPB-11186] Translate flaky integration test to /integration.

cassandra-schema.cql, changelog.d/5-internal/WPB-11101, services/brig/brig.cabal, services/brig/src/Brig/Schema/Run.hs, services/brig/src/Brig/Schema/V87_DropInvitationTables.hs
https://wearezeta.atlassian.net/browse/WPB-11101
=> WPB-11101 remove invitation tables from brig

changelog.d/1-api-changes/WPB-10797, integration/integration.cabal, integration/test/API/Brig.hs, integration/test/Test/MLS/Services.hs, libs/wire-api/src/Wire/API/Error/Brig.hs, libs/wire-subsystems/src/Wire/UserSubsystem/Error.hs, services/brig/src/Brig/Provider/API.hs, services/brig/test/integration/API/Provider.hs
https://wearezeta.atlassian.net/browse/WPB-10797
=> Block services whitelist for teams with default protocol MLS

changelog.d/2-features/WPB-10658, integration/test/API/Galley.hs, integration/test/Notifications.hs, integration/test/Test/Teams.hs, integration/test/Testlib/Assertions.hs, integration/test/Testlib/Cannon.hs, integration/test/Testlib/HTTP.hs, integration/test/Testlib/JSON.hs, integration/test/Testlib/Types.hs
Also contains small changes to the integration test suite:
1. Allow looking up elements from the end in JSON array using negative numbers. So something like `"notifications.-1"` will get the last notification.
2. Separate context from failure message in the `AssertionFailure`.  (I (@akshaymankar) wasn't aware it was appended to message earlier and implemented a separate one, then realized it was the case, so I removed appending to message part).
=> [WPB-10659] Test notifications for personal user to team user migration

libs/wire-api/src/Wire/API/Team/Permission.hs
=> Document self and copy fields of the Permissions type

changelog.d/2-features/new-teams-mls, docs/src/developer/reference/config-options.md, integration/integration.cabal, integration/test/SetupHelpers.hs, integration/test/Test/FeatureFlags/Initialisation.hs, integration/test/Testlib/ModService.hs, integration/test/Testlib/RunServices.hs, libs/galley-types/default.nix, libs/galley-types/galley-types.cabal, libs/galley-types/src/Galley/Types/Teams.hs, services/galley/src/Galley/API/Teams.hs, services/galley/src/Galley/API/Teams/Features.hs
Add `initialConfig` setting for the `mls` feature flag. This is used to initialise MLS configuration values for new teams.
https://wearezeta.atlassian.net/browse/WPB-10795
=> Initial MLS configuration for new teams

changelog.d/3-bug-fixes/WPB-11386-map-range, changelog.d/5-internal/WPB-11386-map-range, libs/types-common/src/Data/Range.hs, services/brig/src/Brig/IO/Intra.hs
=> [WPB-11386] Introduce length-preserving function mapRange to replace fmap.

Makefile, changelog.d/5-internal/pwd, libs/types-common/src/Data/Misc.hs, libs/wire-api/src/Wire/API/Password.hs, libs/wire-api/src/Wire/API/Provider.hs, libs/wire-api/test/unit/Test/Wire/API/Password.hs, libs/wire-subsystems/src/Wire/AuthenticationSubsystem.hs, libs/wire-subsystems/src/Wire/AuthenticationSubsystem/Interpreter.hs, libs/wire-subsystems/src/Wire/HashPassword.hs, libs/wire-subsystems/src/Wire/PasswordStore.hs, libs/wire-subsystems/src/Wire/PasswordStore/Cassandra.hs, libs/wire-subsystems/src/Wire/UserSubsystem/Interpreter.hs, libs/wire-subsystems/test/unit/Wire/AuthenticationSubsystem/InterpreterSpec.hs, libs/wire-subsystems/test/unit/Wire/MockInterpreters/HashPassword.hs, libs/wire-subsystems/test/unit/Wire/MockInterpreters/PasswordStore.hs, services/brig/brig.integration.yaml, services/brig/src/Brig/API/Auth.hs, services/brig/src/Brig/API/Client.hs, services/brig/src/Brig/API/Internal.hs, services/brig/src/Brig/API/OAuth.hs, services/brig/src/Brig/API/Public.hs, services/brig/src/Brig/API/User.hs, services/brig/src/Brig/Data/Client.hs, services/brig/src/Brig/Data/User.hs, services/brig/src/Brig/Provider/API.hs, services/brig/src/Brig/Provider/DB.hs, services/brig/src/Brig/User/Auth.hs, services/brig/test/integration/API/User/Auth.hs, services/galley/src/Galley/API/Update.hs
https://wearezeta.atlassian.net/browse/WPB-9746
=> [Brig] Move password verification to the AuthenticationSubsystem, move to Argon2id with new settings.

services/brig/src/Brig/Data/Client.hs
Seems to be a mistake when rebasing a PR without aligning with develop ahead of time, weird.
=> Removed redundant MonadReader constraint.

libs/wire-subsystems/src/Wire/NotificationSubsystem.hs, libs/wire-subsystems/src/Wire/NotificationSubsystem/Interpreter.hs, libs/wire-subsystems/test/unit/Wire/NotificationSubsystem/InterpreterSpec.hs, services/brig/src/Brig/API/Federation.hs, services/brig/src/Brig/IO/Intra.hs
Brig only ever pushes 1 notification at a time. Also remove the list from corresponding call the the NotificationSubsystem.
=> brig: Remove unnecessary List1 Event when pushing notifications

changelog.d/0-release-notes/gundeck-bulk-push, charts/gundeck/templates/configmap.yaml, charts/gundeck/values.yaml, hack/helm_vars/wire-server/values.yaml.gotmpl, services/gundeck/gundeck.integration.yaml, services/gundeck/src/Gundeck/Options.hs, services/gundeck/src/Gundeck/Push.hs, services/gundeck/test/integration/API.hs, services/gundeck/test/unit/MockGundeck.hs, services/gundeck/test/unit/Push.hs
It has been set to `true` for a few years now and seems to work well. It is being removed to reduce work for RabbitMq based notifications.
Related: https://github.com/wireapp/wire-server/pull/4272
Also: https://wearezeta.atlassian.net/browse/WPB-10308
=> gundeck: Remove bulkPush config option

services/brig/test/integration/Run.hs
https://wearezeta.atlassian.net/browse/WPB-11472
This reverts commit a72c70a9a9b9d71af1b864384e80b6d3eb0827a9.
it turns out this only helps with resource consumption because after running the first bach of tests, defaultMainWithIngredients exits...  m|
=> [WPB-11472] Revert "Work around legacy integration test resource leak. (#4244)"

changelog.d/5-internal/test-csv-export, integration/test/API/BrigInternal.hs, integration/test/API/Galley.hs, integration/test/SetupHelpers.hs, integration/test/Test/Conversation.hs, integration/test/Test/ExternalPartner.hs, integration/test/Test/MLS/Services.hs, integration/test/Test/Search.hs, integration/test/Test/TeamSettings.hs, integration/test/Test/Teams.hs, services/galley/default.nix, services/galley/galley.cabal, services/galley/test/integration/API/Teams.hs
In preparation for https://github.com/wireapp/wire-server/pull/4293, this moves the CSV export test to the new integration suite.
https://wearezeta.atlassian.net/browse/WPB-11368
=> [WPB-11368] Test for export team member CSV

Makefile, changelog.d/5-internal/fix-nginx-paths, changelog.d/5-internal/inbucket, changelog.d/5-internal/make-crm, deploy/dockerephemeral/docker-compose.yaml, docs/src/developer/developer/building.md, hack/bin/cabal-run-integration.sh, integration/test/Testlib/JSON.hs, integration/test/Testlib/RunServices.hs, services/nginz/integration-test/conf/nginz/nginx.conf
Webapp repository needed a little change for this to work: https://github.com/wireapp/wire-webapp/pull/17844
=> Enable manual usage of locally running wire-server 

changelog.d/4-docs/fix-swagger, libs/wire-api/default.nix, libs/wire-api/src/Wire/API/Routes/SpecialiseToVersion.hs, libs/wire-api/src/Wire/API/Routes/Version.hs, libs/wire-api/src/Wire/API/Routes/Version/Wai.hs, libs/wire-api/wire-api.cabal, services/brig/src/Brig/API/Public.hs, services/brig/src/Brig/API/Public/Swagger.hs
dc889c0305eac14fd42a1b1ddd163fcf26271e54 is the interesting commit in this PR.  Tested this with and without the patch on a blocked version, and the fix does the right thing.
=> Fix swagger

changelog.d/2-features/no-federated-proteus, charts/galley/templates/configmap.yaml, charts/galley/values.yaml, docs/src/developer/reference/config-options.md, integration/test/Test/Conversation.hs, libs/wire-api-federation/src/Wire/API/Federation/Error.hs, services/galley/galley.integration.yaml, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Create.hs, services/galley/src/Galley/Options.hs, services/galley/src/Galley/Types/UserList.hs
https://wearezeta.atlassian.net/browse/WPB-10787
=> Disable federation for specific protocols

Makefile, changelog.d/5-internal/fix-galley-overlaps, integration/test/Test/Swagger.hs, libs/wire-api/src/Wire/API/Routes/Internal/Galley.hs, libs/wire-subsystems/src/Wire/GalleyAPIAccess/Rpc.hs, services/brig/test/integration/Util.hs, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/Query.hs, services/galley/test/integration/API.hs
Followup to https://github.com/wireapp/wire-server/pull/4302.
https://wearezeta.atlassian.net/browse/WPB-10314.
=> Fix overlapping paths errors in galley internal

changelog.d/3-bug-fixes/WPB-11925-fix-add-bot, charts/nginz/values.yaml, libs/wire-api/src/Wire/API/VersionInfo.hs
this route was accidentally removed from #4302.
=> [WPB-11925] fix add-bot

changelog.d/0-release-notes/configurable-argon, changelog.d/2-features/add-config-for-pwd-hash, changelog.d/5-internal/pwd, charts/brig/values.yaml, charts/galley/values.yaml, docs/src/developer/reference/config-options.md, hack/helm_vars/wire-server/values.yaml.gotmpl, integration/test/Test/User.hs, libs/types-common/src/Util/Options.hs, libs/wire-api/src/Wire/API/Password.hs, libs/wire-subsystems/src/Wire/HashPassword.hs, services/brig/brig.integration.yaml, services/brig/src/Brig/CanonicalInterpreter.hs, services/brig/test/integration/API/User/Auth.hs, services/galley/galley.integration.yaml, services/galley/src/Galley/App.hs
https://wearezeta.atlassian.net/browse/WPB-11924
=> Allow choosing between argon2id and scrypt as hashing algorithm

changelog.d/5-internal/fix-local-fed-v1, deploy/dockerephemeral/federation-v0/nginz/conf/integration.conf, deploy/dockerephemeral/federation-v1/nginz/conf/integration.conf, deploy/dockerephemeral/run.sh, integration/test/Test/MLS/One2One.hs
=> [fix] Local federation v1 tests fixed

changelog.d/5-internal/WPB-11791, charts/nginx-ingress-services/templates/ingress.yaml, charts/nginx-ingress-services/templates/ingress_minio.yaml
https://wearezeta.atlassian.net/browse/WPB-11791
=> block access to assets.*/minio/ path

changelog.d/3-bug-fixes/optimize-get-all-features, services/galley/src/Galley/API/Teams/Features/Get.hs
This used to be specialized, but mistakenly got converted to multiple DB calls here:
https://github.com/wireapp/wire-server/pull/4178/files#diff-9daaabfa64d3ada89e121d9f68351f16a0237abf97d8fdc672acde7f9f2fd2ffL197-L207https://github.com/wireapp/wire-server/pull/4178/files#diff-9daaabfa64d3ada89e121d9f68351f16a0237abf97d8fdc672acde7f9f2fd2ffL197-L207
https://wearezeta.atlassian.net/browse/WPB-12044
=> galley: Use bulk query when getting all feature configs for a team user

changelog.d/5-internal/delete-multi-get, integration/test/Test/FeatureFlags/SearchVisibilityInbound.hs, libs/wire-api/src/Wire/API/Routes/Internal/Galley.hs, libs/wire-api/src/Wire/API/Routes/Internal/Galley/TeamFeatureNoConfigMulti.hs, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/Teams/Features.hs, services/galley/src/Galley/API/Teams/Features/Get.hs, services/galley/src/Galley/Cassandra/TeamFeatures.hs, services/galley/src/Galley/Effects/TeamFeatureStore.hs
=> galley: Delete unused endpoint for getting feature status for multiple teams

changelog.d/4-docs/fix-swagger-2024-10-31, libs/schema-profunctor/src/Data/Schema.hs, libs/wire-api/src/Wire/API/Asset.hs, libs/wire-api/src/Wire/API/Routes/Internal/Galley/TeamsIntra.hs, libs/wire-api/src/Wire/API/Team.hs, libs/wire-api/src/Wire/API/User.hs, libs/wire-api/src/Wire/API/User/Orphans.hs, services/brig/src/Brig/API/User.hs, services/brig/src/Brig/Version.hs
=> Add a few more swagger descriptions and examples.

changelog.d/5-internal/WPB-8881, libs/wire-api/src/Wire/API/Error/Brig.hs, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs, libs/wire-api/src/Wire/API/User.hs, libs/wire-api/src/Wire/API/User/Activation.hs, libs/wire-subsystems/src/Wire/ActivationCodeStore.hs, libs/wire-subsystems/src/Wire/ActivationCodeStore/Cassandra.hs, libs/wire-subsystems/src/Wire/UserStore.hs, libs/wire-subsystems/src/Wire/UserStore/Cassandra.hs, libs/wire-subsystems/src/Wire/UserSubsystem.hs, libs/wire-subsystems/src/Wire/UserSubsystem/Error.hs, libs/wire-subsystems/src/Wire/UserSubsystem/Interpreter.hs, libs/wire-subsystems/src/Wire/UserSubsystem/UserSubsystemConfig.hs, libs/wire-subsystems/test/unit/Wire/MockInterpreters/ActivationCodeStore.hs, libs/wire-subsystems/test/unit/Wire/MockInterpreters/UserStore.hs, libs/wire-subsystems/test/unit/Wire/UserSubsystem/InterpreterSpec.hs, libs/wire-subsystems/wire-subsystems.cabal, services/brig/src/Brig/API/Auth.hs, services/brig/src/Brig/API/Error.hs, services/brig/src/Brig/API/Handler.hs, services/brig/src/Brig/API/Internal.hs, services/brig/src/Brig/API/Public.hs, services/brig/src/Brig/API/Types.hs, services/brig/src/Brig/API/User.hs, services/brig/src/Brig/CanonicalInterpreter.hs, services/brig/src/Brig/Data/Activation.hs, services/brig/src/Brig/Data/User.hs, services/galley/test/integration/API/Util.hs
This is a refactoring PR about user email update and remove operations.
Tracked by https://wearezeta.atlassian.net/browse/WPB-8881.
=> [WPB-8881] Move email update and remove operations to effects

changelog.d/3-bug-fixes/WBP-10658, charts/nginz/values.yaml, integration/test/API/Nginz.hs, integration/test/Test/Teams.hs, services/nginz/integration-test/conf/nginz/nginx.conf
=> WPB-10658 invitation and acceptance of individual users to teams fix nginz

changelog.d/5-internal/WPB-8881, libs/wire-api/src/Wire/API/User.hs, libs/wire-api/src/Wire/API/User/Identity.hs, libs/wire-subsystems/src/Wire/ActivationCodeStore.hs, libs/wire-subsystems/test/unit/Wire/ActivationCodeStore/InterpreterSpec.hs, libs/wire-subsystems/test/unit/Wire/MiniBackend.hs, libs/wire-subsystems/test/unit/Wire/MockInterpreters/ActivationCodeStore.hs, libs/wire-subsystems/test/unit/Wire/MockInterpreters/UserStore.hs, libs/wire-subsystems/test/unit/Wire/UserStoreSpec.hs, libs/wire-subsystems/test/unit/Wire/UserSubsystem/InterpreterSpec.hs, libs/wire-subsystems/wire-subsystems.cabal
This is a follow-up PR to #4316 that adds unit tests for effect actions that were introduced in that PR.
Tracked by https://wearezeta.atlassian.net/browse/WPB-8881
=> [WPB-8881] Add unit tests for new effect actions

Makefile, integration/default.nix, integration/integration.cabal, integration/test/API/Galley.hs, integration/test/MLS/Util.hs, integration/test/Notifications.hs, integration/test/SetupHelpers.hs, integration/test/Test/AccessUpdate.hs, integration/test/Test/ExternalPartner.hs, integration/test/Test/FeatureFlags/LegalHold.hs, integration/test/Test/LegalHold.hs, integration/test/Test/MLS.hs, integration/test/Test/MLS/KeyPackage.hs, integration/test/Test/MLS/Message.hs, integration/test/Test/MLS/Notifications.hs, integration/test/Test/MLS/One2One.hs, integration/test/Test/MLS/SubConversation.hs, integration/test/Test/MLS/Unreachable.hs, integration/test/Testlib/App.hs, integration/test/Testlib/Assertions.hs, integration/test/Testlib/Env.hs, integration/test/Testlib/JSON.hs, integration/test/Testlib/ModService.hs, integration/test/Testlib/Run.hs, integration/test/Testlib/Types.hs
=> integration: Allow MLS State to track multiple conversations

changelog.d/0-release-notes/WBP-10308, charts/background-worker/templates/deployment.yaml, charts/brig/templates/configmap.yaml
=> [charts] Fix staging configuration

changelog.d/3-bug-fixes/brig-rabbitmq, charts/brig/templates/configmap.yaml, services/brig/src/Brig/App.hs, services/brig/src/Brig/CanonicalInterpreter.hs, services/brig/src/Brig/Federation/Client.hs, services/brig/src/Brig/Options.hs, services/brig/test/integration/API/User/Handles.hs
It seems the rabbitmq configuration field in brig was made mandatory by mistake in #4272. This reverts it to an optional field and removes the corresponding `Input` effect, which was unused.
=> brig: make rabbitmq field optional again

changelog.d/0-release-notes/WPB-14284, changelog.d/3-bug-fixes/WPB-14284, charts/brig/templates/configmap.yaml, docs/src/developer/reference/config-options.md, hack/helm_vars/wire-server/values.yaml.gotmpl
https://wearezeta.atlassian.net/browse/WPB-14284
This in combination with the caillaich PR https://github.com/zinfra/cailleach/pull/2380 should fix the setting for the team invitation URL for personal users.
The brig server configs in some environments have the field `emailSMS.team` set, in which case the invitation URL set there as `tExistingUserInvitationUrl`. If `emailSMS.team` does not exist, the URL is constructed from `externalUrls.accountPages`.
So depending on the environment, a correct config must contain either a value for `emailSMS.team.tExistingUserInvitationUrl` or for `externalUrls.accountPages`.
=> WPB-14284 personal user invitation URL configmap fixed

libs/wire-api/src/Wire/API/Routes/Internal/Galley/TeamsIntra.hs
Just a tiny fix for the Swagger description of `TeamStatus`.
- ~~[ ] Add a new entry in an appropriate subdirectory of `changelog.d`~~
=> Fix the description of `TeamStatus`

services/brig/src/Brig/Index/Options.hs, services/brig/test/integration/API/Search.hs
Call migration code instead of faking it.
Ticket: https://wearezeta.atlassian.net/browse/WPB-10715
=> Improve ES migration test coverage

changelog.d/5-internal/efficient-queue-listing, integration/test/Testlib/ResourcePool.hs, libs/extended/src/Network/RabbitMqAdmin.hs, services/background-worker/src/Wire/BackendNotificationPusher.hs, services/background-worker/test/Test/Wire/BackendNotificationPusherSpec.hs
With consumable-notifications we expect a lot of queues to exist in RabbitMQ. Using regex to filter here would ensure this loop doesn't keep going over all of those queues over and over again.
https://wearezeta.atlassian.net/browse/WPB-11811
=> background-worker: Use regex to list queues for backend-notifications

libs/hscim/CHANGELOG, libs/hscim/README.md, libs/hscim/default.nix, libs/hscim/hscim.cabal, libs/hscim/src/Web/Scim/Client.hs, weeder.toml
in preparation for hackage release of hscim 0.4.0.6
=> [WPB-14436] Bump deps, fix README.

changelog.d/5-internal/cargohold-errors, services/cargohold/src/CargoHold/App.hs
Uncaught IO exceptions in cargohold simply become "Server Error" responses with no extra information. This PR ensures that such exceptions are logged before being handled by the middleware, just like it happens in galley.
https://wearezeta.atlassian.net/browse/WPB-14410
=> Log uncaught IO exceptions in cargohold

Makefile
The generated file already exists in our repo and won't change.
Current `hie.yaml`:
```yaml
cradle:
cabal: {}
```
=> chore: Remove hie.yaml Makefile target

changelog.d/3-bug-fixes/WPB-14856, integration/test/API/Brig.hs, integration/test/Test/Teams.hs, services/brig/src/Brig/API/User.hs
=> WPB-14856 fix: Personal user to team owner not listed in team search

Makefile, changelog.d/2-features/enterprise-helm-chart, charts/README.md, charts/wire-server-enterprise/Chart.yaml, charts/wire-server-enterprise/templates/configmap.yaml, charts/wire-server-enterprise/templates/deployment.yaml, charts/wire-server-enterprise/templates/image-pull-secret.yaml, charts/wire-server-enterprise/templates/service.yaml, charts/wire-server-enterprise/templates/servicemonitor.yaml, charts/wire-server-enterprise/values.yaml
https://wearezeta.atlassian.net/browse/WPB-14291
=> Add helm chart for wire-server-enterprise

changelog.d/5-internal/mls, charts/galley/templates/secret.yaml, docs/src/understand/mls.md
This PR 
- forces the MLS removal key to be provided for all ciphersuites at template time. Without this PR missing keys become a runtime error.
- adds missing documentation on how to generate MLS removal keys
=> MLS: Make missing MLS removal keys a template error

integration/test/Test/Events.hs, libs/wire-api/src/Wire/API/Routes/Public/Cannon.hs
Tracked by https://wearezeta.atlassian.net/browse/WPB-14912.
=> [WPB-14912] Limit the consume events endpoint to v8

changelog.d/1-api-changes/rabbitmq-temp, integration/test/Test/Events.hs, libs/wire-api/src/Wire/API/Notification.hs, libs/wire-api/src/Wire/API/Routes/Public/Cannon.hs, services/cannon/cannon.cabal, services/cannon/default.nix, services/cannon/src/Cannon/API/Public.hs, services/cannon/src/Cannon/RabbitMq.hs, services/cannon/src/Cannon/RabbitMqConsumerApp.hs, services/cannon/src/Cannon/WS.hs, services/gundeck/src/Gundeck/Client.hs, services/gundeck/src/Gundeck/Push.hs
This PR implements "temporary" queues for listening to events not bound to a specific client, meant to be used by team management or similar services.
When `GET /events` is called without a `client_id` parameter, we create a new temporary queue and bind it to the `user-notifications` exchange with routing keys `<user-id>` and `<user-id>.temporary`.
When a notification is published to RabbitMQ to all clients of a user, nothing changes, and `<user-id>` is used as its routing key. When it is published to a list of clients, it is now also published with routing key `<user-id>.temporary`. Each notifications is only published once with the `<user-id>.temporary` routing key even if the user has multiple capable clients.
When the websocket is closed, the temporary queue is deleted. …
=> RabbitMQ temporary clients

changelog.d/3-bug-fixes/WPB-15072, integration/test/API/GalleyInternal.hs, integration/test/Test/Teams.hs, services/brig/src/Brig/API/User.hs
=> WPB-15072 team activated is not sent to ibis when a personal user creates a new team

integration/test/Test/Events.hs
The creation of temp queue races with client creation event. This is removed by first expecting the event to be served to the real client and then listening to events temporarily
Fixup for https://github.com/wireapp/wire-server/pull/4360
https://wearezeta.atlassian.net/browse/WPB-11173
=> integration/testConsumeTempEvents: Remove race causing flaky test

changelog.d/5-internal/submodule-formatting, tools/ormolu.sh, tools/ormolu1.sh
The wrapper calls the renamed old script to also format the wire-server-enterprise submodule.
Ticket: https://wearezeta.atlassian.net/browse/WPB-14285
=> Format submodule with existing Ormolu script

integration/default.nix, integration/integration.cabal, integration/test/SetupHelpers.hs, integration/test/Test/Events.hs, integration/test/Testlib/Assertions.hs, integration/test/Testlib/ModService.hs, libs/wire-api/src/Wire/API/Notification.hs, services/cannon/cannon.cabal, services/cannon/default.nix, services/cannon/src/Cannon/RabbitMq.hs, services/cannon/src/Cannon/RabbitMqConsumerApp.hs, services/cannon/src/Cannon/Types.hs, services/cannon/src/Cannon/WS.hs, services/gundeck/src/Gundeck/Client.hs, services/gundeck/src/Gundeck/Push.hs
https://wearezeta.atlassian.net/browse/WPB-11173
=> gundeck/cannon: Fixup for temporary recipients of events

changelog.d/5-internal/stabilize-es-migration-test, services/brig/src/Brig/API/Internal.hs, services/brig/src/Brig/User/Search/Index.hs, services/brig/test/integration/API/Search.hs, services/brig/test/integration/API/Search/Util.hs
https://wearezeta.atlassian.net/browse/WPB-15037
=> [WPB-15037] fix flaky test migration to new index

changelog.d/5-internal/wpb-15151-revive-and-translate-tests, integration/test/API/Galley.hs, integration/test/API/GalleyInternal.hs, integration/test/Test/LegalHold.hs, integration/test/Testlib/ModService.hs, services/galley/test/integration/API/Teams/LegalHold/DisabledByDefault.hs
=> [WPB-15151] eliminate legahold test redundancy

integration/test/Testlib/ModService.hs, nix/wire-server.nix
Also don't ignore exceptions when stopping dynamic backends.
=> integration: Use lsof instead of ss to find processes listening on a port

changelog.d/3-bug-fixes/WPB-14613, charts/nginz/values.yaml
This PR fixes the following bug: requests to nginz of form `/v./consent/.*` are not forwaded forwarded to `galeb` with path `/consent/.*` but with path `/consent`
I also considered changing the rewrite rule from
```
rewrite ^/v[0-9]+({{ $location.path }}) $1;
```
to
```
rewrite ^/v[0-9]+({{ $location.path }}.*) $1;
```
to fix the bug, but opted against it, because it would make the paths configured in `values.yaml` less explicit.
I think it's better to be explicit in the config about the fact that requests may be of form `/consent/<foo>/<bar>/<baz>`.
This is also consistent with other parts in the configuration where we are explicit about the whole path instead of relying on the fact for a `~*` you may omit the tail.
Tracked by https://wearezeta.atlassian.net/browse/WPB-14613
=> fix bug: consent request not correctly forwarded to galeb

integration/test/Testlib/ModService.hs
=> integration: Print more information when a dynamic backend fails to start

charts/rabbitmq/requirements.yaml, charts/redis-cluster/requirements.yaml, hack/helmfile.yaml
The main repo seems to have some intermittent issues
https://github.com/bitnami/charts/issues/31257
=> charts: Use bitnami helm repo from github 

charts/background-worker/templates/deployment.yaml
Fixup for https://github.com/wireapp/wire-server/pull/4410
The service account needs to be unset expliclty otherwise the previous value remains. https://github.com/kubernetes/kubernetes/issues/72519
=> charts/background-worker: Explicitly remove serviceAccount

changelog.d/5-internal/refreshIndex-correct-url, services/brig/src/Brig/User/Search/Index.hs, services/brig/test/integration/API/Search.hs
Additional indices were not correctly refreshed in [testMigrationToNewIndex](https://github.com/wireapp/wire-server/blob/b9959a626deb256bd9d49f5eb34330b51f75d0a8/services/brig/test/integration/API/Search.hs#L623) due to a proxy masking them (forbidding to write access to the additional index with the default one's proxy URL.) Thus, it was a bit of luck if all index writes could be read, which led to flaky tests.
This PR lets `/i/index/refresh` sync default and additional indices with their dedicated URL.
Tickets:
- https://wearezeta.atlassian.net/browse/WPB-15437
- https://wearezeta.atlassian.net/browse/WPB-15433
N.B. yes, it is a bit weird to request merging with a failing pipeline. But, index migration tests seem to be stable now.
=> Stabilize index migration tests

services/brig/src/Brig/User/Search/Index.hs
This case was missing: The additional index can reside on the same ElasticSearch instance as the normal/default one.
Ticket: https://wearezeta.atlassian.net/browse/WPB-15437
- ~[ ] Add a new entry in an appropriate subdirectory of `changelog.d`~ (This is a fixup of https://github.com/wireapp/wire-server/pull/4413/)
=> /i/index/refresh : Refresh additional index on same ElasticSearch

libs/wire-api/src/Wire/API/EnterpriseLogin.hs, libs/wire-subsystems/test/unit/Wire/MockInterpreters/SparAPIAccess.hs
=> Fix nits of #4389

changelog.d/3-bug-fixes/WPB-14307-quickfix-503, integration/test/Test/Teams.hs, libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem/Null.hs
Fix 503 on user registration when the enterprise service is disabled.
=> Fix 503 on registration with disabled enterprise service

changelog.d/3-bug-fixes/WPB-15400, integration/test/Test/MLS/SubConversation.hs, services/galley/src/Galley/API/MLS/Commit/ExternalCommit.hs, services/galley/src/Galley/API/MLS/Commit/InternalCommit.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/API/MLS/Removal.hs, services/galley/src/Galley/API/MLS/SubConversation.hs, services/galley/src/Galley/API/MLS/Util.hs
https://wearezeta.atlassian.net/browse/WPB-15400
=> MLS: send ext commit before sending ext proposals

integration/test/Test/Teams.hs, libs/types-common/src/Data/Domain.hs, libs/wire-api/src/Wire/API/EnterpriseLogin.hs, libs/wire-api/src/Wire/API/User/EmailAddress.hs, libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem.hs, libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem/Error.hs, libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem/Interpreter.hs, libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem/Null.hs, libs/wire-subsystems/src/Wire/InvitationStore.hs, libs/wire-subsystems/src/Wire/InvitationStore/Cassandra.hs, libs/wire-subsystems/src/Wire/TeamInvitationSubsystem/Error.hs, libs/wire-subsystems/src/Wire/TeamInvitationSubsystem/Interpreter.hs, libs/wire-subsystems/src/Wire/UserSubsystem.hs, libs/wire-subsystems/src/Wire/UserSubsystem/Error.hs, libs/wire-subsystems/src/Wire/UserSubsystem/Interpreter.hs, libs/wire-subsystems/test/unit/Wire/EnterpriseLoginSubsystem/InterpreterSpec.hs, libs/wire-subsystems/test/unit/Wire/MiniBackend.hs, libs/wire-subsystems/test/unit/Wire/MockInterpreters.hs, libs/wire-subsystems/test/unit/Wire/MockInterpreters/EmailSubsystem.hs, libs/wire-subsystems/test/unit/Wire/MockInterpreters/EnterpriseLoginSubsystem.hs, libs/wire-subsystems/test/unit/Wire/MockInterpreters/GalleyAPIAccess.hs, libs/wire-subsystems/test/unit/Wire/MockInterpreters/InvitationStore.hs, libs/wire-subsystems/test/unit/Wire/MockInterpreters/TinyLog.hs, libs/wire-subsystems/test/unit/Wire/MockInterpreters/UserSubsystem.hs, libs/wire-subsystems/test/unit/Wire/TeamInvitationSubsystem/InterpreterSpec.hs, libs/wire-subsystems/test/unit/Wire/UserSubsystem/InterpreterSpec.hs, libs/wire-subsystems/wire-subsystems.cabal, services/brig/src/Brig/API/Internal.hs, services/brig/src/Brig/API/Public.hs
https://wearezeta.atlassian.net/browse/WPB-14310
please read commit-by-commit.
=> [WPB-14310] Move domain registration guards to their respective subsystems 

changelog.d/3-bug-fixes/mls-group-info-lock, integration/test/Test/MLS/SubConversation.hs, services/galley/src/Galley/API/MLS/Commit/InternalCommit.hs, services/galley/src/Galley/API/MLS/Message.hs
This makes the behaviour for internal commits consistent with that of external commits. As a side effect, `propagateMessage` is called inside the lock, which is not necessary.
https://wearezeta.atlassian.net/browse/WPB-15811
=> Save group info within commit lock

cassandra-schema.cql, changelog.d/1-api-changes/WPB-14307, charts/nginz/values.yaml, integration/test/API/Brig.hs, integration/test/Test/DomainVerification.hs, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs, libs/wire-api/src/Wire/API/Routes/Public/Brig/DomainVerification.hs, libs/wire-subsystems/src/Wire/DomainRegistrationStore.hs, libs/wire-subsystems/src/Wire/DomainRegistrationStore/Cassandra.hs, libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem.hs, libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem/Interpreter.hs, libs/wire-subsystems/test/unit/Wire/MockInterpreters/DomainRegistrationStore.hs, libs/wire-subsystems/test/unit/Wire/MockInterpreters/EnterpriseLoginSubsystem.hs, services/brig/brig.cabal, services/brig/src/Brig/API/Public.hs, services/brig/src/Brig/Schema/Run.hs, services/brig/src/Brig/Schema/V90_DomainRegistrationTeamIndex.hs, services/nginz/integration-test/conf/nginz/nginx.conf
=> WPB-15801 GET and DELETE Registered Domains

changelog.d/1-api-changes/WPB-15933, integration/test/Test/DomainVerification.hs, libs/wire-api/src/Wire/API/Routes/Public/Brig/DomainVerification.hs, libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem.hs, libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem/Interpreter.hs, services/brig/src/Brig/API/Public.hs
Add a flag to the response body of `POST /get-domain-registration` to indicate
whether `domain_redirect` is set to `none` due to the existence of a registered
account.
This makes it possible for clients to let a user log in with an existing cloud
account even if a redirection to an on-prem backend is set up for their domain.
https://wearezeta.atlassian.net/browse/WPB-15933
=> WPB-15933 Special case of getDomainRegistrationPublic

changelog.d/5-internal/ingress-classes, hack/bin/integration-cleanup.sh, hack/bin/integration-spring-cleaning.sh, hack/bin/integration-teardown-federation.sh, hack/bin/integration-teardown-ingress-classes.sh
These objects used to linger forever, eventually exhausting etcd after many months of development.
=> Cleanup ingress classes after integration tests.

changelog.d/5-internal/helmfile-destroy, hack/bin/integration-teardown-federation.sh
=> Fix helmfile destroy that was missing an env variable

changelog.d/2-features/WPB-16141, integration/test/Test/User.hs, libs/wire-subsystems/src/Wire/UserSubsystem.hs, libs/wire-subsystems/src/Wire/UserSubsystem/Interpreter.hs, libs/wire-subsystems/test/unit/Wire/MockInterpreters/UserSubsystem.hs, libs/wire-subsystems/test/unit/Wire/UserSubsystem/InterpreterSpec.hs, services/brig/src/Brig/API/Public.hs, services/brig/src/Brig/API/User.hs, services/brig/src/Brig/Data/Activation.hs
=> WPB-16141 Enforce no activation if email domain is registered for another team or backend

changelog.d/5-internal/alpine-version, charts/cannon/templates/statefulset.yaml, charts/cassandra-migrations/templates/migrate-schema.yaml
**Security Fixes:**
- Addressed OpenSSL vulnerabilities:
- CVE-2023-1255: Potential denial of service due to excessive resource consumption.
- CVE-2023-2650: Possible buffer overrun during X.509 certificate verification.
**Source:** [Alpine 3.15.9, 3.16.6, 3.17.4, and 3.18.2 released](https://www.alpinelinux.org/posts/Alpine-3.15.9-3.16.6-3.17.4-3.18.2-released.html)
**Breaking Changes:**
- OpenRC Update: Removal of the deprecated /sbin/rc binary. Ensure /etc/inittab references /sbin/openrc to maintain system initialization processes.
- iptables Backend Change: Default transition to iptables-nft. Users relying on traditional iptables should adjust configurations accordingly.
- Kernel Consolidation: Unification of linux-rpi4 and linux-rpi2 kernels into a single linux-rpi package. Raspberry …
=> feat: Alpine version bump to v3.21.3 for cassandra-migrations and cannon helm charts

changelog.d/5-internal/update-kubectl-image-reaper-helm-chart, charts/reaper/templates/deployment.yaml
Ticket: https://wearezeta.atlassian.net/browse/WPB-15648
=> feat(reaper) bump bitnami/kubectl docker image from 1.24.12 to 1.32.2

changelog.d/3-bug-fixes/W-16210, integration/test/Test/DomainVerification.hs, libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem/Interpreter.hs
=> WPB-16210 Allow transitioning from `no-registration` to `backend` configuration for email domain registration

hack/bin/cassandra_dump_schema
Fix regex escaping in cassandra dump script.
=> Fix regex escaping in cassandra dump script

changelog.d/3-bug-fixes/WPB-16333, integration/test/SetupHelpers.hs, integration/test/Test/Teams.hs, services/brig/src/Brig/API/User.hs
https://wearezeta.atlassian.net/browse/WPB-16333
=> WPB-16333 Fix: Prevent team creation by guests

changelog.d/3-bug-fixes/WPB-16026, integration/test/Test/LegalHold.hs, services/galley/src/Galley/API/LegalHold.hs
https://wearezeta.atlassian.net/browse/WPB-16026
=> WPB-16026 secure hold does not activate on prod with protheus only client

libs/wire-subsystems/test/unit/Wire/UserSubsystem/InterpreterSpec.hs
This fixes a rare unit test failure introduced by #4478.
=> Fix assertion in unit test

docs/src/developer/reference/config-options.md
I'm not sure how this fits into the migration of docs (@mohitrajain ?). However, the doc files seem to only be moved, so this would be easy to copy somewhere else.
Ticket: https://wearezeta.atlassian.net/browse/WPB-16301
=> Document Channels feature flag

changelog.d/2-features/WPB-16387, integration/test/API/Galley.hs, integration/test/MLS/Util.hs, integration/test/Test/Channels.hs, integration/test/Testlib/Types.hs, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/Query.hs, services/galley/src/Galley/API/Update.hs, services/galley/src/Galley/API/Util.hs
https://wearezeta.atlassian.net/browse/WPB-16387
=> WPB-16387 add team admins with wire admin permissions to channels

hack/bin/check-weed.sh
You cannot expect Bash in /bin for all OSs.
=> Improve bash PATH in check-weed.sh

charts/ingress-nginx-controller/Chart.yaml, charts/ingress-nginx-controller/values.yaml
Upgrade ingress-nginx chart to the same version used in kube-ci.
=> Upgrade ingress-nginx chart

integration/test/Test/MLS/One2One.hs
=> Prevent v1 tests from running when v1 is disabled

changelog.d/3-bug-fixes/multi-ingress_minio-ingress, charts/nginx-ingress-services/templates/_helpers.tpl, charts/nginx-ingress-services/templates/ingress_minio.yaml
When `fakeS3` is enabled, `nginx-ingress-services` creates an ingress for Minio. This ingress' name is now configurable to allow multiple of them("multi-ingress".)
Ticket: https://wearezeta.atlassian.net/browse/WPB-16855
=> Make minio-ingress multi-ingress ready

changelog.d/3-bug-fixes/mls-duplicate-client, integration/test/Test/MLS.hs, services/galley/src/Galley/API/MLS/Commit/ExternalCommit.hs, services/galley/src/Galley/API/MLS/Commit/InternalCommit.hs
This is a first step to safeguard against broken clients that sometimes operate with new credentials without registering a new client to the backend. We simply check that duplicate clients are never introduced in group, either with internal or external commits.
Checking that the signature key of new leaf nodes always matches the one registered with the backend will be in a followup PR.
https://wearezeta.atlassian.net/browse/WPB-16786
=> Disallow duplicate clients in MLS groups

charts/nginx-ingress-services/templates/ingress.yaml
They are not created for the single-ingress case as well. So, this just translates the existing behaviour to multi-ingress.
We cannot have them, because we do weird stuff (auto-executing javascript to submit a form) in our SSO responses.
The endpoints that won't get CSP headers are:
- `/sso/finalize-login`
- `/sso/finalize-login/<teamID :: UUID>`
- `/sso/initiate-login`
- `/sso/initiate-login/<idpId :: UUID>`
- `/favicon.ico`
I'm not sure why the browser queries the favicon. However, it should be safe to get it without CSP headers.
Ticket: https://wearezeta.atlassian.net/browse/WPB-16420
- ~~[ ] Add a new entry in an appropriate subdirectory of `changelog.d`~~ (Covered by https://github.com/wireapp/wire-server/blob/develop/changelog.d/2-features/WPB-16420_multi-ingress_sso)
=> Don't create CSP headers for multi-ingress SSO

changelog.d/3-bug-fixes/WPB-16535-emulate-saml-idp-initiated-login, integration/test/SetupHelpers.hs, integration/test/Test/Spar.hs, libs/saml2-web-sso/src/SAML2/WebSSO/SP.hs, libs/saml2-web-sso/src/SAML2/WebSSO/Test/MockResponse.hs, libs/saml2-web-sso/src/SAML2/WebSSO/Types.hs, libs/saml2-web-sso/src/SAML2/WebSSO/XML.hs, libs/saml2-web-sso/test/Test/SAML2/WebSSO/APISpec.hs, libs/saml2-web-sso/test/Test/SAML2/WebSSO/XML/ExamplesSpec.hs, libs/wire-api/src/Wire/API/Routes/Public/Spar.hs, services/spar/src/Spar/API.hs, services/spar/src/Spar/Error.hs, services/spar/test-integration/Test/Spar/APISpec.hs, services/spar/test-integration/Test/Spar/AppSpec.hs, services/spar/test-integration/Test/Spar/Scim/UserSpec.hs, services/spar/test-integration/Util/Core.hs
https://wearezeta.atlassian.net/browse/WPB-16535
before:
```
$ make ci-safe package=integration TEST_INCLUDE=testSparIdPInitiatedLogin
[...]
----- Spar.testSparIdPInitiatedLogin FAIL (0.74 s) -----
assertion failure:
Actual:
400
Expected:
303
call stack:
1. assertFailure at test/Testlib/Assertions.hs:102
assertFailure $ (maybe "" (<> "\n") msg) <> "Actual:\n" <> pa <> "\nExpected:\n" <> pb <> diff
2. shouldMatchWithMsg at test/Testlib/Assertions.hs:71
shouldMatch = shouldMatchWithMsg Nothing
3. shouldMatch at test/Testlib/Assertions.hs:198
shouldMatchInt = shouldMatch
4. shouldMatchInt at test/Test/Spar.hs:382
resp.status `shouldMatchInt` 303
request:
POST http://127.0.0.1:8088/v9/sso/finalize-login/07e50c4f-c1db-4ccc-9e63-32b9da884c14
request headers:
Content-Type: multipart/form-data; …
```
=> [WPB-16535] emulate saml idp-initiated login

deploy/dockerephemeral/federation-v1/federator.yaml
Fix copy-paste mistake in the configuration of federator-v1 for the local test environment. This prevented federation v1 from being able to run without federation-v0 being present as well.
=> Fix DNS hostname in federation-v1 config

changelog.d/3-bug-fixes/fix-servant-streaming, nix/haskell-pins.nix
Streams were broken upstream due to https://github.com/haskell-servant/servant/pull/1781
Ticket: https://wearezeta.atlassian.net/browse/WPB-17171
=> Use patched version of servant 0.20.2

changelog.d/2-features/WBP-16875, libs/wire-api/src/Wire/API/Routes/Public/Galley/Conversation.hs, services/galley/src/Galley/API/Create.hs
Follow up/ clean up of #4527
The `ConversationExisted` constructor was never used and therefore removed.
https://wearezeta.atlassian.net/browse/WPB-16875
=> WPB-16875 Team admin creates a channel without joining - follow up

changelog.d/5-internal/redis-6.2.16, charts/redis-ephemeral/values.yaml
related to WPB-15658 - we did bump the Helm chart, but it didn't contain the latest available image.
=> fix(redis-ephemeral): bump to 6.2.16

hack/helmfile.yaml
This version is known to work. Newer versions probably need adjustment(s) to their values.
CI deployments started to fail with:
```
Error: template: technitium-dnsserver/templates/NOTES.txt:2:18: executing "technitium-dnsserver/templates/NOTES.txt" at <include "common.names.namespace" .>: error calling include: template: no template "common.names.namespace" associated with template "gotpl"
```
(https://concourse.ops.zinfra.io/teams/main/pipelines/wire-server-pr/jobs/integration-tests-kube-ci/builds/482.1#L67ecfd7c:448)
Ticket: https://wearezeta.atlassian.net/browse/WPB-17472
=> CI: Pin technitium-dnsserver chart version

changelog.d/1-api-changes/WPB-17032_add_webapp_url, integration/test/Test/EnterpriseLogin.hs, integration/test/Test/User.hs, libs/wire-api/src/Wire/API/EnterpriseLogin.hs, libs/wire-api/test/golden/testObject_DomainRegistrationResponse_4.json, libs/wire-api/test/golden/testObject_DomainRegistrationResponse_7.json, libs/wire-api/test/golden/testObject_DomainRegistrationUpdate_4.json, libs/wire-api/test/golden/testObject_DomainRegistrationUpdate_7.json
`PUT /i/domain-registration` and `GET /i/domain-registration` (both are internal endpoints used only by Stern) are changed in their payloads:
- `backend_url` becomes `config_url` in a new `backend` field / object. 
- The `webapp_url` field is new.
Old payload:
```json
{
"backend_url": "{url}",
...
}
```
New payload:
```json
{
"backend": {
"config_url": "{url}",
"webapp_url": "{url}"
},
...
}
```
This change of the payload has also been documented here: https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/1570832467/Email+domain+registration+and+configuration#API-changes
Because we don't have system tests for Stern, I also made a quick manual smoke test: Checked that the redirect URL can still be configured and fetched.
Ticket: https://wearezeta.atlassian.net/browse/WPB-17032
=> Add a webapp url field to email domain registration (2)

services/cannon/src/Cannon/RabbitMqConsumerApp.hs
=> cannon: Log parse error when message from client fails to parse

changelog.d/5-internal/inconsistencies-unparseable-emails, tools/db/inconsistencies/README.md, tools/db/inconsistencies/default.nix, tools/db/inconsistencies/inconsistencies.cabal, tools/db/inconsistencies/src/EmailUnparseableUsers.hs, tools/db/inconsistencies/src/Main.hs, tools/db/inconsistencies/src/Options.hs
https://wearezeta.atlassian.net/browse/WPB-17408
This should help find instances of
```
brig-index: cql-io: protocol error: parse error: response body reading
From:    Reading column "email" of table "brig.user"
```
to analyze and then take further actions later.
=> WPB-17408 inconsistent database: unparseable emails

.envrc, changelog.d/5-internal/galley-request-id, libs/wire-otel/default.nix, libs/wire-otel/src/Wire/OpenTelemetry/Servant.hs, libs/wire-otel/test/Main.hs, libs/wire-otel/wire-otel.cabal, nix/haskell-pins.nix, nix/wire-server.nix, services/galley/default.nix, services/galley/galley.cabal, services/galley/src/Galley/Intra/User.hs, services/galley/src/Galley/Intra/Util.hs
=> galley: Make servant calls to brig/spar are sent with tracing and retries [WPB-17847]

changelog.d/2-features/WPB-16870-user-groups-everything-except-search, integration/test/Test/Auth.hs, libs/wire-subsystems/postgres-migrations/20250604084743-user_group_member_delete_on_cascade.sql, libs/wire-subsystems/src/Wire/UserGroupSubsystem/Interpreter.hs
=> Fix: postgres migrations, added migration for foreign key constraint

changelog.d/2-features/WPB-16887, integration/test/Test/Channels.hs, services/galley/src/Galley/API/Action.hs
=> WPB-16887 Allow Team Admin to Change a Channel Name

changelog.d/5-internal/test-z-timestamp, integration/default.nix, integration/integration.cabal, integration/test/Test/NginxZAuthModule.hs, services/nginz/integration-test/conf/nginz/common_response.conf
Ensure that `Z-Timestamp` / `$zauth_timestamp` is the expiration timestamp of the token, because it is in future.
Ticket: https://wearezeta.atlassian.net/browse/WPB-17736
=> Test nginz zauth_timestamp

changelog.d/5-internal/WPB-18478, integration/test/Test/Conversation.hs, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Action/Notify.hs
https://wearezeta.atlassian.net/browse/WPB-18478
=> WPB-18478 Fix false positive warning: attempt to send notification about conversation update to users not in the conversation

changelog.d/2-features/WPB-17885, charts/brig/templates/configmap.yaml, charts/brig/values.yaml, docs/src/developer/reference/config-options.md, integration/test/Test/User.hs, libs/wire-api/src/Wire/API/Error/Brig.hs, libs/wire-api/src/Wire/API/User.hs, services/brig/brig.integration.yaml, services/brig/src/Brig/API/User.hs, services/brig/src/Brig/Options.hs
=> WPB-17885 EphemeralUserCreation feature flag

changelog.d/2-features/bw-metrics, changelog.d/3-bug-fixes/rabbitmq-reconnect, integration/test/Test/Cells.hs, integration/test/Test/Events.hs, integration/test/Testlib/Assertions.hs, libs/extended/src/Network/AMQP/Extended.hs, services/background-worker/background-worker.cabal, services/background-worker/default.nix, services/background-worker/src/Wire/BackendDeadUserNotificationWatcher.hs, services/background-worker/src/Wire/BackendNotificationPusher.hs, services/background-worker/src/Wire/BackgroundWorker.hs, services/background-worker/src/Wire/BackgroundWorker/Env.hs, services/background-worker/src/Wire/BackgroundWorker/Health.hs, services/background-worker/src/Wire/BackgroundWorker/Util.hs, services/background-worker/src/Wire/DeadUserNotificationWatcher.hs, services/background-worker/test/Test/Wire/BackendNotificationPusherSpec.hs, services/background-worker/test/Test/Wire/Util.hs, services/brig/src/Brig/App.hs, services/galley/src/Galley/App.hs, services/gundeck/src/Gundeck/Env.hs
https://wearezeta.atlassian.net/browse/WPB-18631
Alternative approach for #4632 (Test is copied from there).
=> background-worker/dead-user-notifs-watcher: Reconnect when connection with RabbitMQ is broken

changelog.d/3-bug-fixes/bw-metrics, services/background-worker/src/Wire/BackgroundWorker/Env.hs
=> background-worker: Set metric gauge `wire_background_worker_running_workers` to 1 when a worker is running instead of 0

Makefile, charts/redis-ephemeral/requirements.yaml, hack/bin/helm-oci-login.sh, hack/bin/integration-setup-federation.sh, hack/helmfile.yaml.gotmpl
This way helmfile correctly logs in to the repository. To make it happen during `helmfile sync` `--skip-deps` cannot be passed anymore.
https://wearezeta.atlassian.net/browse/WPB-18677
=> integration-setup: Use docker registry for bitnami

changelog.d/5-internal/WPB-18695, integration/test/Test/MLS.hs, libs/wire-api/src/Wire/API/Error/Brig.hs, libs/wire-api/src/Wire/API/Error/Galley.hs, libs/wire-api/src/Wire/API/MLS/Validation.hs, libs/wire-api/src/Wire/API/MLS/Validation/Error.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/MLS.hs, libs/wire-api/wire-api.cabal, services/brig/src/Brig/API/MLS/KeyPackages/Validation.hs, services/galley/src/Galley/API/MLS/Commit/Core.hs, services/galley/src/Galley/API/MLS/Commit/ExternalCommit.hs, services/galley/src/Galley/API/MLS/Commit/InternalCommit.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/API/MLS/Proposal.hs
=> WPB-18695 Return a specific error for leaf signature verification failure

Makefile, hack/bin/helm-oci-login.sh, hack/helmfile.yaml.gotmpl
This is required because we have to run `helm dep update` manually before
running `helmfile` even if we run `helmfile` without `--skip-sync` because `helm
dep update` needs to happen in a certain order to make sure all nested local
dependencies are packaged correctly.
It was removed in #4664 because it was wrongly considered unnecessary. 
https://wearezeta.atlassian.net/browse/WPB-18677
=> integration-setup: Add explicit helm login to docker hub 

libs/wai-utilities/src/Network/Wai/Utilities/Server.hs, services/background-worker/src/Wire/BackgroundWorker.hs, services/brig/src/Brig/Run.hs, services/cannon/src/Cannon/Run.hs, services/cargohold/src/CargoHold/Run.hs, services/galley/src/Galley/Run.hs, services/gundeck/src/Gundeck/Run.hs, services/proxy/src/Proxy/Run.hs, tools/stern/src/Stern/API.hs
This makes `newSettings` a pure function as it doesn't actually do any IO (it used to do so in the past though, so that's why it had it).
! This also requires changing the use site of `newSettings` in wire-server-enterprise as well, so I guess we will need to wait for a PR in that repo, too.
=> Make `newSettings` pure

changelog.d/5-internal/WPB-18562, integration/test/Test/Teams.hs, libs/wire-api/src/Wire/API/Error/Galley.hs, services/galley/src/Galley/Intra/User.hs
=> WPB-18562 Propagate a rate limit error with status 429 on internal call to reauthenticate

changelog.d/2-features/group-info-check, charts/galley/templates/configmap.yaml, charts/galley/values.yaml, docs/src/developer/reference/config-options.md, integration/test/Test/MLS.hs, integration/test/Test/MLS/SubConversation.hs, libs/wire-api/src/Wire/API/Error/Galley.hs, libs/wire-api/src/Wire/API/MLS/Extension.hs, libs/wire-api/src/Wire/API/MLS/GroupInfo.hs, libs/wire-api/src/Wire/API/MLS/RatchetTree.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/MLS.hs, libs/wire-api/wire-api.cabal, services/galley/src/Galley/API/MLS/Commit/Core.hs, services/galley/src/Galley/API/MLS/Commit/ExternalCommit.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/API/MLS/Proposal.hs, services/galley/src/Galley/API/MLS/Types.hs, services/galley/src/Galley/Options.hs
This PR adds an optional consistency check of the submitted group info on any commit. The ratchet tree extension is parsed and compared with the index map of the group after the commit is applied.
https://wearezeta.atlassian.net/browse/WPB-18394
=> Check consistency of group info

integration/default.nix, integration/integration.cabal, integration/test/Testlib/ModService.hs
My branch to try refactorings on the base branch (instead of messing with it directly.)
Besides minor cleanups, I'm now using an Attoparsec `Parser` to identify and drop `upsteam <name> { <code> }` blocks (blocks can be nested, thus a simple regex won't help) and Interpolate Template Haskell templates to generate new upstream blocks.
=> Refactor the nginx upstream creation for Joe's PR

hack/bin/nix-hls.sh
To use this set `HLS_MAX_MEMORY` in your global env or in `.envrc.local`.
=> nix-hls.sh: Allow limiting memory used by HLS

services/brig/src/Brig/API/Public.hs, services/brig/src/Brig/API/User.hs, services/brig/src/Brig/CanonicalInterpreter.hs, services/brig/src/Brig/IO/Intra.hs, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Action/Kick.hs, services/galley/src/Galley/API/Action/Leave.hs, services/galley/src/Galley/API/Action/Notify.hs, services/galley/src/Galley/API/Action/Reset.hs, services/galley/src/Galley/API/Clients.hs, services/galley/src/Galley/API/Create.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/LegalHold.hs, services/galley/src/Galley/API/MLS/Commit/Core.hs, services/galley/src/Galley/API/MLS/Message.hs, services/galley/src/Galley/API/MLS/Propagate.hs, services/galley/src/Galley/API/MLS/Proposal.hs, services/galley/src/Galley/API/MLS/Removal.hs, services/galley/src/Galley/API/MLS/Reset.hs, services/galley/src/Galley/API/MLS/SubConversation.hs, services/galley/src/Galley/API/MLS/Welcome.hs, services/galley/src/Galley/API/Message.hs, services/galley/src/Galley/API/Teams.hs, services/galley/src/Galley/API/Teams/Features.hs, services/galley/src/Galley/API/Update.hs, services/galley/src/Galley/API/Util.hs, services/galley/src/Galley/App.hs, services/galley/src/Galley/Effects.hs, services/galley/src/Galley/Intra/Journal.hs
So we have only one way to get current time across the code.
=> brig,galley: Use the `Now` effect instead of `Input UTCTime`

changelog.d/5-internal/log-rabbitmq-channel-cancellations, changelog.d/5-internal/rabbitmq-decrease-backendNotificationPusher.remotesRefreshInterval, deploy/dockerephemeral/federation-v1/background-worker.yaml, deploy/dockerephemeral/federation-v2/background-worker.yaml, integration/test/Test/Events.hs, integration/test/Testlib/Assertions.hs, services/background-worker/src/Wire/BackendNotificationPusher.hs
Actually, there isn't much we can do when a queue is externally deleted:
- There is a loop which handles the reconfiguration according to existing (!) queues
- Older federation backend versions (`V0` and `V1`) cannot be changed anymore.
To heal the symptoms of detached consumers, I've decreased the cleanup interval for local integration test runs to one Second. That should be a good tradeoff between the time to re-execute tests and not making to many bogus requests to RabbitMQ.
I've also added a test to ensure that reestablishing the consumer works.
Ticket: https://wearezeta.atlassian.net/browse/WPB-17247
=> detached background worker 2nd attempt

changelog.d/2-features/WPB-18195, integration/test/API/Galley.hs, integration/test/Test/TeamCollaborators.hs, libs/wire-api/src/Wire/API/Team/Member.hs, services/galley/src/Galley/API/Create.hs
Allow team collaborators to create 1:1 conversations via `POST /one2one-conversations` if they've the `implicit_connection` permission.
Ticket: https://wearezeta.atlassian.net/browse/WPB-18195
=> Team collaborator: Implicit connection permission

changelog.d/2-features/WPB-18195, integration/test/Test/TeamCollaborators.hs, libs/wire-subsystems/postgres-migrations/20250729181800-create-collaborators-uid.sql, libs/wire-subsystems/src/Wire/TeamCollaboratorsStore.hs, libs/wire-subsystems/src/Wire/TeamCollaboratorsStore/Postgres.hs, libs/wire-subsystems/src/Wire/TeamCollaboratorsSubsystem.hs, libs/wire-subsystems/src/Wire/TeamCollaboratorsSubsystem/Interpreter.hs, libs/wire-subsystems/test/unit/Wire/MockInterpreters/TeamCollaboratorsStore.hs, libs/wire-subsystems/test/unit/Wire/TeamCollaboratorsSubsystem/InterpreterSpec.hs, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Clients.hs, services/galley/src/Galley/API/Federation.hs, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/LegalHold.hs, services/galley/src/Galley/API/MLS/Commit/Core.hs, services/galley/src/Galley/API/MLS/Commit/InternalCommit.hs, services/galley/src/Galley/API/MLS/Proposal.hs, services/galley/src/Galley/API/MLS/Reset.hs, services/galley/src/Galley/API/Query.hs, services/galley/src/Galley/API/Teams.hs, services/galley/src/Galley/API/Teams/Features.hs, services/galley/src/Galley/API/Update.hs, services/galley/src/Galley/API/Util.hs
Allow team collaborators with `impicit_connection` permission to get a MLS 1:1 where the collaborator is involved.
The affected endpoint is `GET /one2one-conversations/{usr_domain}/{usr}`.
The other affected bit is `performConversationJoin`. Which (hopefully) should be fine, as team collaborators would be able to join conversations.
Ticket: https://wearezeta.atlassian.net/browse/WPB-18195
=> team collaborators with implicit connection to team can get mls one2one

changelog.d/5-internal/nginz-disco-fix, charts/nginz/templates/conf/_nginx.conf.tpl
If `upstream_name` is set, we're including it in the proxy_pass directive. However, the actual upstreams never included the namespace name.
This PR adds the namespace to the upstream name in the upstream declaration, so that proxy_pass is not running into a 504 error for such services.
related to WPB-19292
=> fix(nginz): also include namespace in upstream name when `upstream_namespace` is set

changelog.d/3-bug-fixes/reset-non-group, integration/test/Test/MLS/Reset.hs, services/galley/src/Galley/API/Action.hs, services/galley/src/Galley/API/Util.hs
This fixes a bug where the backend was incorrectly checking that a conversation being reset is a group conversation, and throwing "invalid-op" if not.
https://wearezeta.atlassian.net/browse/WPB-19296
=> Fix conversation type check for reset action

changelog.d/2-features/WPB-19263, charts/galley/templates/configmap.yaml, charts/galley/values.yaml, docs/src/developer/reference/config-options.md, hack/helm_vars/wire-server/values.yaml.gotmpl, integration/integration.cabal, integration/test/Test/FeatureFlags/ChatBubbles.hs, integration/test/Test/FeatureFlags/Util.hs, libs/galley-types/src/Galley/Types/Teams.hs, libs/wire-api/src/Wire/API/Routes/Internal/Galley.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/Feature.hs, libs/wire-api/src/Wire/API/Team/Feature.hs, services/galley/galley.integration.yaml, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/Public/Feature.hs, services/galley/src/Galley/API/Teams/Features.hs, services/galley/src/Galley/API/Teams/Features/Get.hs, tools/stern/src/Stern/API.hs, tools/stern/src/Stern/API/Routes.hs, tools/stern/test/integration/API.hs
=> WPB-19263 feature flag to enable iOS chat bubbles

Makefile
This fixes a help message and might fix the cabal repl used by ghcid. _Might_ in the sense that when I run `make devtest package=wire-subsystems` I get the following error:
```
Error: [Cabal-7076]
Cannot open a repl for multiple components at onnce. The targets 'wire-subsystems' and 'wire-subsystems-tests' refer to different components..
Your compiler supports a multiple component repl but support is not enabled.
The experimental multi repl can be enabled by
* Globally: Setting multi-repl: True in your .cabal/config
* Project Wide: Setting multi-repl: True in your cabal.project file
* Per Invocation: By passing --enable-multi-repl when starting the repl
Command "cabal repl wire-subsystems:wire-subsystems-tests lib:wire-subsystems" exited unexpectedly with error message: 
*** usage: make …
```
=> Fixes to `make devtest`

changelog.d/3-bug-fixes/reset-one2one, integration/test/MLS/Util.hs, integration/test/Test/MLS/Reset.hs, integration/test/Testlib/Types.hs, libs/wire-subsystems/src/Wire/ConversationStore/Cassandra.hs, libs/wire-subsystems/src/Wire/StoredConversation.hs, services/galley/src/Galley/API/Create.hs, services/galley/src/Galley/API/MLS/One2One.hs, services/galley/src/Galley/API/One2One.hs
Fix bug in reset logic for MLS one2one conversations. The conversation groupId was being regenerated on the first commit after reset.
https://wearezeta.atlassian.net/browse/WPB-19643
=> Do not overwrite groupId when recreating a one2one

renovate.json
This PR configures renovate bot to perform security udpates only. Link to docs: https://docs.renovatebot.com/presets-security/#securityonly-security-updates
=> renovate: security updates only

libs/wire-api/default.nix, libs/wire-api/src/Wire/API/PostgresMarshall.hs, libs/wire-api/wire-api.cabal
This will allow for better error messages when we encoding/decoding errors.
This also changes dimapPG to use `refinedResult` to make the decoding errors not visible in business logic.
=> PostgresUnmarshall: Use Either instead of Maybe

changelog.d/2-features/WPB-20206, charts/galley/templates/configmap.yaml, charts/galley/values.yaml, docs/src/developer/reference/config-options.md, hack/helm_vars/wire-server/values.yaml.gotmpl, integration/integration.cabal, integration/test/Test/FeatureFlags/AssetAuditLog.hs, integration/test/Test/FeatureFlags/Util.hs, libs/galley-types/src/Galley/Types/Teams.hs, libs/wire-api/src/Wire/API/Routes/Internal/Galley.hs, libs/wire-api/src/Wire/API/Routes/Public/Galley/Feature.hs, libs/wire-api/src/Wire/API/Team/Feature.hs, services/galley/galley.integration.yaml, services/galley/src/Galley/API/Internal.hs, services/galley/src/Galley/API/Public/Feature.hs, services/galley/src/Galley/API/Teams/Features/Get.hs
=> WPB-20206 create a new feature flag asset audit log

changelog.d/2-features/WPB-20203, integration/test/Test/Spar.hs, libs/wire-subsystems/src/Wire/UserSubsystem/Interpreter.hs, libs/wire-subsystems/test/unit/Wire/UserSubsystem/InterpreterSpec.hs
=> WPB-20203 backend updating user attributes via SCIM should be possible when E2EID is enabled

.github/workflows/build.yaml, changelog.d/4-docs/update-multiingress-deeplink-docs, docs/README.md, docs/src/understand/associate/deeplink.md
WPB-20718: update multi-ingress deeplink doc, update docs for contributing to wire-docs and fix build.yaml
=> WPB-20718: update multi-ingress deeplink doc

changelog.d/2-features/WPB-19712, integration/test/API/Brig.hs, integration/test/Test/UserGroup.hs, libs/wire-api/src/Wire/API/Error/Brig.hs, libs/wire-api/src/Wire/API/Routes/Public/Brig.hs, libs/wire-subsystems/postgres-migrations/202509190851023-user_group_conversations_create_table.sql, libs/wire-subsystems/src/Wire/GalleyAPIAccess.hs, libs/wire-subsystems/src/Wire/GalleyAPIAccess/Rpc.hs, libs/wire-subsystems/src/Wire/UserGroupStore.hs, libs/wire-subsystems/src/Wire/UserGroupStore/Postgres.hs, libs/wire-subsystems/src/Wire/UserGroupSubsystem.hs, libs/wire-subsystems/src/Wire/UserGroupSubsystem/Interpreter.hs, libs/wire-subsystems/test/unit/Wire/MockInterpreters/GalleyAPIAccess.hs, libs/wire-subsystems/test/unit/Wire/MockInterpreters/UserGroupStore.hs, postgres-schema.sql, services/brig/src/Brig/API/Public.hs
https://wearezeta.atlassian.net/browse/WPB-19712
=> WPB-19712: Allow team admin to update the channels to user-group association
