- services/cannon/cannon.cabal
- services/cannon/src/Cannon/API.hs
- services/cannon/stack.yaml
Websockets 0.11 supports the permessage-deflate compression extension.
> Update websockets to 0.11

- services/cannon/cannon.cabal
- services/cargohold/cargohold.cabal
- services/galley/galley.cabal
- services/proxy/proxy.cabal
In the right environment, this allows building static executables with
e.g. `stack build --flag proxy:static`
> Add optional -static flag to cabal files

- libs/ropes/ropes.cabal
These tests require AWS credentials, so should be run with other integration tests (instead of during each `stack build --test` of services using this, e.g. cargohold).
> [ropes] change integration test to be an executable

- services/nginz/Makefile
> Verify signature on nginx tarballs

- libs/galley-types/src/Galley/Types/Swagger.hs
- libs/galley-types/src/Galley/Types/Teams.hs
- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/Data.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Util.hs
- Include team metadata as part of `team.create` event.
- Add support for updating team member permissions.
- Add API endpoint to get a single team conversation.
- Add API endpoint to get a single team member.
- If a team member is removed, remove it from all team conversations.
- Update API documentation.
> Various tweaks to teams.

- services/nginz/Makefile
Nginx version should be set in the Makefile (as before).
Nginz version should be set at build time via an environment variable,
e.g.
```
make dist NGINZ_VERSION=0.0.1
```
or
```
export NGINZ_VERSION=0.0.1
make dist
```
Can be used with e.g. concourse version resource at build time.
> Decouple nginx version from nginz version

- services/gundeck/src/Gundeck/Client.hs
- services/gundeck/src/Gundeck/Push.hs
- services/gundeck/src/Gundeck/Push/Data.hs
- services/gundeck/src/Gundeck/Push/Native/Fallback.hs
- services/gundeck/src/Gundeck/React.hs
- services/gundeck/test/integration/API.hs
Reduce the consistency requirement from `Quorum` to `One` for push token lookups in the main async code path for sending (native) push notifications to increase chances of delivery in the presence of
network problems (and possibly slightly reduced latency).
Note: Other code paths for push token lookups still need to use `Quorum` consistency as the
lookups happen in the context of possible token updates or removal, i.e. a (strongly) consistent read is typically necessary for correct operation and / or to fulfill the API contract.
> Reduce consistency requirement for token lookup.

- services/cannon/Makefile
- services/cargohold/Makefile
- services/galley/Makefile
- services/gundeck/Makefile
- services/proxy/Makefile
- tools/bonanza/Makefile
- tools/makedeb/Makefile
`make dist` now depends on the `VERSION` environment variable.
Motivation: creating new build artifacts from a service should not depend on a developer bumping versions in the cabal file manually; build artifact versioning can be automated by CI jobs.
> Decouple debian package version from cabal version

- services/gundeck/Makefile
- services/gundeck/src/Gundeck/Aws.hs
- services/gundeck/src/Gundeck/Client.hs
- services/gundeck/src/Gundeck/Push.hs
- services/gundeck/src/Gundeck/Push/Native.hs
- services/gundeck/src/Gundeck/Push/Native/Serialise.hs
- services/gundeck/src/Gundeck/React.hs
- services/gundeck/test/integration/API.hs
The desire to use multiple accounts from a single device and app
installation simultaneously, i.e. being logged into multiple accounts,
receiving push notifications for each. So far ownership of a push token
was restricted to a single user, mostly to avoid scenarios where push
notifications may end up being shown to an unintended recipient on a
device that is shared by multiple users and if the notifications contain
a payload in plain text.  Plain text payloads are no longer used.
1. Multiple users can have the same push token registered, without
either being removed on registration of the other.
2. The mapping from push tokens stored in gundeck (Cassandra) to SNS
endpoints becomes N to 1. To that effect, `CustomUserData` of an SNS
endpoint can now contain a list of user IDs, instead of …
> Support sharing of push tokens across users.

- services/gundeck/src/Gundeck/Client.hs
- services/gundeck/src/Gundeck/Notification/Data.hs
- services/gundeck/test/integration/API.hs
Immediately delete all notifications of deleted users instead of just letting them expire.
> Delete notifications of deleted users.

- services/brig/brig.cabal
- services/brig/src/Brig/Provider/Email.hs
- services/brig/src/Brig/Provider/Template.hs
- services/brig/src/Brig/Team/Email.hs
- services/brig/src/Brig/Team/Template.hs
- services/brig/src/Brig/Template.hs
- services/brig/src/Brig/User/Email.hs
- services/brig/src/Brig/User/Phone.hs
- services/brig/src/Brig/User/Template.hs
- services/brig/stack.yaml
To prevent / disallow arbitrary HTML injection in scenarios where input to templates directly or indirectly originates from user input (e.g. primarily current invitation emails).
> HTML-encode all input of HTML templates.

- services/nginz/Makefile
Upgrading to `1.12.1` due to:
```
2017-07-11 | nginx-1.12.1 stable and nginx-1.13.3 mainline versions have been released with a fix for theinteger overflow in the range filter vulnerability (CVE-2017-7529).
```
http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-7529
> Upgrade to nginx-1.12.1

- stack.yaml
The collectd dependency is not on stackage, so this adds the github dependency. Uses the latest version, 0.0.0.2.
> Fix collectd dependency

- libs/brig-types/src/Brig/Types/Swagger.hs
If we don't re-export the swagger models (and thus return them from the API endpoint), then the swagger client cannot display them properly
> Add missing re-exports to other swagger models

- services/gundeck/src/Gundeck/Client/Data.hs
The same motivation as in https://github.com/wireapp/wire-server/pull/25. Since these keys are updated comparatively rarely by clients but read all the time.
Upsides:
* Increased chances of delivery of (native) push notifications in case of database-related network issues.
* (Slightly?) improved latency.
Downsides:
* Outdated keys may be used temporarily, e.g. for keys that have been changed shortly before a network partition occurs and for as long as the partition is not resolved.
> Use consistency 'One' for (native) push key lookups.

- Makefile
- services/nginz/Dockerfile
- services/nginz/Makefile
Based on the official nginx alpine Dockerfile (but includes the zauth module). Does not contain any configuration (needs to be provided at run-time). Results in a ~15MB container uncompressed.
> Add alpine-based nginz Dockerfile

- libs/api-bot/src/Network/Wire/Bot/Cache.hs
- libs/api-bot/src/Network/Wire/Bot/Monad.hs
- libs/api-bot/stack.yaml
- libs/api-client/stack.yaml
`PlainTextPassword` was moved to types-common and `newUserTeam` introduced at some point; api-client/bot libs were not updated.
> Fix compilation for api-bot and api-client

- build/alpine/Dockerfile
Fix the COPY destination path so it matches the absolute source path. This means we get the registered packages under .stack-work for the build, reducing build time significantly.
> Fix alpine builder path

- build/alpine/Dockerfile
- services/brig/Makefile
- services/cannon/Makefile
- services/cargohold/Makefile
- services/galley/Makefile
- services/gundeck/Makefile
- services/proxy/Makefile
Create separate docker images containing other executables like e.g. `brig-schema`, `brig-integration`, etc. Does not need additional recompilation time.
> Containers for integration,schema,etc executables

- libs/galley-types/src/Galley/Types/Teams/Intra.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/IO/Intra.hs
- services/brig/test/integration/API/Team.hs
- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Data/Instances.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Util.hs
Add `Pending` state to Teams, which is their initial state. Upon the first user account activation, an associated team also becomes active.
> Activate team on account activation only

- services/brig/deb/etc/sv/brig/run
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Options.hs
- services/brig/src/Brig/TURN.hs
- services/brig/src/Brig/TURN/API.hs
Allow TTL values for the TURN config itself (default: 1 hour) to be different from the TURN token lifetime (default: 6 hours).
> Distinguish TURN token/config TTLs

- services/nginz/Dockerfile
- services/nginz/nginz_reload.sh
Uses [dumb-init](https://github.com/Yelp/dumb-init) as PID 1 and `inotifywait` to reload nginz if upstreams
change. Change only affects docker image.
> nginz-container: Reload process on upstreams.conf change.

- build/alpine/Dockerfile
- build/alpine/Dockerfile.deps
- services/brig/Dockerfile
Our haskell executables, if used as PID 1 inside containers, don't do signal handling well, don't reap zombie processes, etc. Dumb-init should be a more sane default init process.
See e.g. https://engineeringblog.yelp.com/2016/01/dumb-init-an-init-for-docker.html
> Use dumb-init as the default PID 1 in containers

- libs/galley-types/src/Galley/Types/Teams.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/test/integration/API/Teams.hs
Currently we only include the user id in the event sent for a successful member update.
This adds the new permissions of the user to the recipients with the GetPermissions permission.
> Inform privileged users of permission update

- Makefile
- build/alpine/Dockerfile
- build/alpine/Dockerfile.deps
- services/brig/Dockerfile
Allows to use different base images via `--build-arg builder=...`
> [docker] make base images configurable

- services/brig/brig.yaml.example
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Aws/Types.hs
- services/brig/src/Brig/Options.hs
* Adds partial support for regions, for SQS/DynamoDB
* The used [aws library](https://hackage.haskell.org/package/aws-0.17.1) does not have a "higher level" datatype for region so I have defined an internal one, similarly to [amazonka](https://github.com/brendanhay/amazonka/blob/afeb929c758c772fe83692a54978cf7bb05a9de5/amazonka-lightsail/gen/Network/AWS/Lightsail/Types/Sum.hs#L559-L573) to then choose the correct regions depending on the service.
* At the moment, we support only `eu-west-1` and `eu-central-1`. You can easily add more if needed
* Since the [AWS SQS library](https://hackage.haskell.org/package/aws-0.17.1/docs/Aws-Sqs-Core.html) does not yet support a specific endpoint for eu-central-1, a "hardcoded" string is used
* As SES is only available in some regions (namely, …
> [brig] Allow region for SQS and DynamoDB to be specified

- services/gundeck/src/Gundeck/Push/Native.hs
- services/gundeck/src/Gundeck/Push/Websocket.hs
`gundeck` currently logs a bit too much so this PR intends to reduce it in 2 ways:
* Add metrics to track `Payload too large` and log it only at `Debug` level
* Add metrics to track `Presence unreachable` and avoid logging the error which is typically ~800 Bytes long and includes line breaks, which messes up our logging pipeline
> Reduce logging in gundeck

- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/Data/User.hs
- services/brig/src/Brig/Provider/API.hs
- services/brig/src/Brig/User/API/Search.hs
- services/brig/test/integration/API/Search.hs
- services/brig/test/integration/API/Search/Util.hs
- services/brig/test/integration/API/Team.hs
On user creation, set the searchable flag to false for team creators and members.
> Make team members unsearchable by default

- libs/ropes/src/Ropes/Aws.hs
Currently, services (`brig` and `cargohold`) using the `ropes` (and thus using the underlying aws library) library can only read AWS credentials in 2 ways: either by supplying key/secret directly in a config file (`PermAuth`) or using the ec2 metadata (`TempAuth`).
It would be useful to have this done in a similar way as [amazonka's discovery](https://hackage.haskell.org/package/amazonka-1.5.0/docs/src/Network-AWS-Auth.html#Credentials)
> Try loading AWS keys and secrets from sensible defaults

- services/nginz/Dockerfile
- services/nginz/Makefile
Adds `realip_module` which _is used to change the client address and optional port to those sent in the specified header field_ (useful when running `nginz` as a proxy).
> Add realip module to nginz

- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/Data.hs
`withValidBroadcastRecipients` currently has a theoretical limit of 1127 users. Instead of a single `IN` lookup, this PR instead does multiple smaller lookups in parallel.
> parallelize client lookups if ids > 128

- services/proxy/src/Proxy/API.hs
Also simplify routing by allowing more of the proxied APIs to be used. Example for giphy:
```
Request {requestMethod = "GET", httpVersion = HTTP/1.1, rawPathInfo = "/proxy/giphy/v1/gifs/eSQKNSmg07dHq", rawQueryString = "", (...)}
Request {requestMethod = "GET", httpVersion = HTTP/1.1, rawPathInfo = "/v1/gifs/eSQKNSmg07dHq", rawQueryString = "?api_key=API_KEY", (...)}
```
> [proxy] allow proxying of /giphy/v1/gifs/<some-id>

- services/brig/brig.cabal
- services/brig/src/Brig/API.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/Team/Util.hs
- services/brig/test/integration/API/Team.hs
- services/brig/test/integration/Util.hs
Similarly to the public endpoint, this PR ensures that using the internal deletion endpoint to delete users will not cause teams to become "orphan" (i.e., without a full permission user)
> Internal user deletion endpoint should not cause orphan teams

- services/brig/src/Brig/API.hs
- services/brig/test/integration/API/Team.hs
This PR basically reverts a [previous one](https://github.com/wireapp/wire-server/pull/159) that introduced a problem when deleting teams.
When a team is [deleted](https://github.com/wireapp/wire-server/blob/develop/services/galley/src/Galley/API/Teams.hs#L194), we delete all the users of that team before we delete the team. Thus, this creates a bit of a chicken-egg problem and prevents a team from ever getting properly deleted (not sure how this was missed in the galley tests but I retried them and they failed).
The main driver for this is to avoid backoffice users accidentally causing orphan teams so I'd suggest fixing the backoffice tool itself. The other option would be to add a query parameter like `force` that galley would use in the case of team deletion but the backdoor to create …
> Allow internal endpoint to always delete a user

- services/brig/brig.cabal
- services/brig/stack.yaml
- stack.yaml
The latest version of tasty is pretty useful as it allows using [pattern tests](https://github.com/feuerbach/tasty#patterns) as _awk expressions_.
Unfortunately it's pretty bleeding edge so not present in any LTS.
> Upgrade to tasty-1.0.0.1

- services/gundeck/test/integration/API.hs
With this change we no longer use `brig` for user/client creation and create only 1 push token per user, halving the number of token creation requests to SNS. In addition, we also do not clean up SNS/cassandra.
Locally, the test now runs in ~25 secs (vs. the previous 120)
> Speed up test for too many tokens

- services/brig/deb/etc/sv/brig/run
- services/brig/src/Brig/Options.hs
- services/brig/src/Brig/Provider/API.hs
- services/brig/src/Brig/Provider/DB.hs
Add an option when starting `brig` to list only services from a specific providerID on the `GET "/services"` endpoint.
Adding tests for this is tricky but I ran them without the option (and all tests succeed) and then added `--provider-id-search-filter <random uuid_v4>` on the Procfile which causes the provider/service search test to fail (which is what you'd expect - no services are returned).
The happy path was checked locally by launching brig with `--provider-id-search-filter=<known_providerid>` and verified that only services for that provider were returned from `GET /services`. Clearly room for improvement...
> Optionally filter services by provider

- libs/brig-types/src/Brig/Types/Intra.hs
- libs/galley-types/src/Galley/Types.hs
- services/brig/brig.cabal
- services/brig/src/Brig/API.hs
- services/brig/src/Brig/API/Client.hs
- services/brig/src/Brig/API/Connection.hs
- services/brig/src/Brig/Data/Client.hs
- services/brig/src/Brig/IO/Intra.hs
- services/brig/test/integration/API.hs
- services/galley/deb/etc/sv/galley/run
- services/galley/galley.cabal
- services/galley/src/Galley/API/Clients.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/Intra/Client.hs
- services/galley/src/Galley/Intra/User.hs
- services/galley/src/Galley/Intra/Util.hs
- services/galley/src/Galley/Options.hs
- services/galley/src/Galley/Types/Clients.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Util.hs
Change the Galley read path for client lookup to go through Brig. The write path is still the same, i.e. Galley still writes its own client mapping to Cassandra. This way we can we test the implications of the higher read latency before making a (potential) full switch.
The current code has two identical definitions for userid to client mappings, one for internal use in Galley and one for serialization. This is changed slightly so that the external representation is wrapped in the internal one (it's not pretty but it works).
> Let Galley read client list form Brig

- services/cargohold/src/CargoHold/API.hs
This is currently done in cargohold due to an old [nginx bug](https://trac.nginx.org/nginx/ticket/669) (which fronts cargohold).
We can now safely remove this since it negatively affects the asset upload API, especially with large(r) uploads, since the client will only receive error responses after he transmitted the full body, however large the body.
See: 
https://github.com/wearezeta/backend-issues/issues/487
https://github.com/zinfra/wai-utilities/pull/12
https://github.com/zinfra/cargohold/commit/5820c4858872d4dd1f0ac778fb17d4451477c454
> Do not fully consume the request body in the success case

- services/nginz/Dockerfile
- services/nginz/Makefile
It would be nice to allow `nginz` to do the gunzip "heavy lifting", instead of having it at the haskell service level.
Also brings `nginz`'s docker image to `alpine-3.7` to be in sync with the other service. `make docker` worked fine for me.
> Upgrade nginx to 1.12.2, use alpine-3.7 and compile with gunzip

- services/galley/src/Galley/Validation.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Util.hs
This PR changes the behaviour of `rangeCheckedMaybe` (which is used in the creation of every type of conversation) to verify that if we have a `Just`, then this `Just` is within the required `Range`.
Thus, when creating conversations, if `Name` is specified, then it must be within the `[1, 256]` range.
Also fixed one test which was failing after the configurable options for max connections was introduced.
> Ensure 'Just Range' is within Range

- services/brig/stack.yaml
- services/galley/stack.yaml
- services/gundeck/stack.yaml
- stack.yaml
Currently, brig, galley, gundeck, cargohold don't compile/link with openssl 1.1.x. (#203 already removes that dependency for cargohold). The latest HsOpenSSL fixes that, and works with both the 1.0.x and 1.1.x branches. 1.1.x tested with:
```
OpenSSL 1.1.0g-fips  2 Nov 2017
```
```
ldd ~/.local/bin/brig
(...)
libssl.so.1.1 => /lib64/libssl.so.1.1 (0x0000783c4913a000)
(...)
```
Integration tests work, too.
Whenever we upgrade the resolver to `lts-10.6` or later, that will also upgrade HsOpenSSL, so at that point it doesn't need to be specified as extra-dep.
> Latest HsOpenSSL is compatible with openssl 1.1.x

- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Util.hs
* introduce /conversations/code-check
* Change post /conversations/:cnv/code behaviour
returns 201 if a new code is created (returns the event json)
returns 200 if a code already exists (returns that exisiting code)
* Implement removing non-verified users
* Ensure requesting user also gets member-remove event
> Minor Conversation code API change

- .travis.yml
- Makefile
- build/alpine/Dockerfile
- build/alpine/Dockerfile.builder
- build/alpine/Dockerfile.executable
- build/alpine/Dockerfile.intermediate
- build/alpine/Dockerfile.migrations
- build/alpine/Makefile
- build/alpine/README.md
- services/brig/Dockerfile
Adds a few docker images and Makefile targets. 'wireserver' on dockerhub becomes the default namespace (I'll convert this shortly to an organization).
`docker-builder` is currently uploaded manually due to it taking >50 minutes (which is the travis hard limit)
Example build: https://travis-ci.org/wireapp/wire-server/builds/346911997
Resulting docker images: https://hub.docker.com/r/wireserver/
> Add travis file that builds & pushes docker images

- libs/brig-types/src/Brig/Types/Intra.hs
- libs/brig-types/src/Brig/Types/User.hs
- services/brig/Makefile
- services/brig/src/Brig/API.hs
- services/brig/src/Brig/API/Error.hs
- services/brig/src/Brig/API/Types.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/Data/Instances.hs
- services/brig/src/Brig/Data/User.hs
- services/brig/src/Brig/Provider/API.hs
- services/brig/src/Brig/User/Auth.hs
- services/brig/test/integration/API.hs
Ephemeral users are defined as users created with neither email nor phone
The optional field 'expires_at' is available for these users on
- /register
- /self (SelfProfile)
- /users/:Id (public UserProfile)
expiry time is creation time + SessionTokenTimeout (default: 1 day). JSON example of user profile: 
```
{
(... other user fields)
"expires_at" : "2018-03-06T20:36:12.000Z"
}
```
> Expose 'expires_at' json field for ephemeral users

- services/gundeck/test/integration/API.hs
Running this test locally against a remote server (or cluster of) "often" fails due to clock drift; this PR fixes that by using a notification ID remotely generated (for another user, to keep the semantics of the test) instead of a local one.
> Use remotely generated notification id

- build/alpine/ghc/config.yaml
See https://github.com/commercialhaskell/stack/issues/2509
Resolves https://github.com/wireapp/wire-server/issues/236
> Allow stack to use haskell.org instead of fpcomplete.com

- deploy/docker-ephemeral/init.sh
- services/galley/.env
- services/galley/galley.cabal
- services/galley/test/integration/API/SQS.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/Main.hs
This PR tries to make testing of journaling events more reliable and caters for some differences between the real AWS queues behaviour and fake SQS (e.g., visibility timeout does not work properly with the fake queue).
If order is not relevant for some journaling events (or cannot be reliably determined, for instance, when deleting a team), `tryMatch` makes no assumptions on the order of such events in the queue and can just check that the desired event is in fact in the queue. It also ensures that the SQS queue is cleared before starting the test suite making it easier to re-run the tests.
> More robust integration tests

- libs/api-bot/src/Network/Wire/Bot/Cache.hs
- libs/brig-types/src/Brig/Types/Provider/External.hs
- libs/brig-types/src/Brig/Types/User.hs
- services/brig/brig.cabal
- services/brig/schema/src/Main.hs
- services/brig/schema/src/V49.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Data/User.hs
- services/brig/src/Brig/IO/Intra.hs
- services/brig/src/Brig/Provider/API.hs
- services/brig/test/integration/API/Team.hs
- services/brig/test/integration/API/Team/Util.hs
- services/brig/test/integration/Util.hs
This PR adds a field in the `user`'s table for the binding `team_id` of that user; it exposes it over the `/users` and `/self` endpoints as part of the user's public profile.
A migration to backfill `team_id`s for existing users will be done after.
> Team id user profile

- libs/tasty-cannon/src/Test/Tasty/Cannon.hs
- libs/tasty-cannon/tasty-cannon.cabal
- services/cannon/src/Cannon/API.hs
- services/cannon/src/Cannon/WS.hs
Some of our integration tests seem to "ramdomly" fail, which hinted at a race condition somewhere as sometimes notifications did not arrive.
This PR changes the way our tests establish connections with cannon by waiting until it has a confirmation that this presence has been registered (i.e., that `gundeck` has confirmed the presence) before it returns the websocket connection back to the caller.
Even though it could have been fixed by passing around a reference to gundeck everywhere in the tests, it seemed easier and cleaner to add an internal endpoint in `cannon` which queries that presence from `gundeck`.
> Confirm WS registration before returning

- build/alpine/Dockerfile.builder
- build/alpine/Dockerfile.prebuilder
- build/alpine/Makefile
- build/alpine/README.md
Pros:
* The next time we want to change something about the way we build Haskell stuff, we won't have to wait for the GHC build every. single. time.
Cons:
* A split based on components (e.g. GHC in a separate docker image) would be nicer conceptually.
> Split alpine-builder

- deploy/services-demo/conf/brig.demo.yaml
Missing config change after https://github.com/wireapp/wire-server/pull/296
> Fix brig demo config

- deploy/docker-ephemeral/docker-compose.yaml
- deploy/docker-ephemeral/init.sh
- deploy/services-demo/conf/cargohold.demo.yaml
- services/cargohold/cargohold.integration.yaml
- services/cargohold/src/CargoHold/S3.hs
- services/cargohold/stack.yaml
- services/integration.sh
- stack.yaml
This PR introduces 2 changes:
1. Migrate to use [minio](https://minio.io/) instead of fake-s3; one of the many advantages is that all tests now also pass locally (resumable uploads work against minio).
2. The meta information about an upload is now stored in a different file, i.e., it was stored under `v3/resumable/<asset_id>` and it is now stored under `v3/resumable/<asset_id>/meta`. The reason for this change is that parts are then stored under `v3/resumable/<asset_id>/<part_nr>`, which is fine for S3 but not very portable since it is not possible, when using your local filesystem, to have a file and a folder with the same name.
> Store asset meta info in a specific file, use minio instead of fake-s3

- Makefile
- services/brig/Makefile
- services/brig/stack.yaml
- services/cannon/Makefile
- services/cannon/stack.yaml
- services/cargohold/Makefile
- services/cargohold/stack.yaml
- services/galley/Makefile
- services/galley/stack.yaml
- services/gundeck/Makefile
- services/gundeck/stack.yaml
- services/proxy/Makefile
- services/proxy/stack.yaml
- tools/api-simulations/Makefile
- tools/bonanza/Makefile
Tweak the `make fast` rule such that it lets you ignore warnings during development without risking to accidentally commit your compiler settings:
```shell
$ WIRE_STACK_OPTIONS="--ghc-options=-Wwarn" make fast
```
> Guide `make fast` behavior during development via shell env.

- services/brig/brig.cabal
- services/brig/test/integration/API/User/Auth.hs
In this PR, I try to fix a flaky throttling test by using 8 threads instead of 1 for logging in. This will probably make logging-in fast enough that throttling will actually kick in.
For an example of test failure, see here: https://bridge-ie-concourse.zinfra.io/teams/main/pipelines/wire-server-pr-integration/jobs/test/builds/111
```
throttle:                                          FAIL
1: 429 =/= 200
Response was:
Response {responseStatus = Status {statusCode = 200, statusMessage = "OK"}, responseVersion = HTTP/1.1, responseHeaders = [("Transfer-Encoding","chunked"),("Date","Tue, 22 May 2018 12:06:50 GMT"),("Server","Warp/3.2.13"),("Content-Encoding","gzip"),("Set-Cookie","zuid=XUcvxEq3LTq9n8-tEAPfHpFuMSzmb1Fuk97AQDV3x6Kmf3an8p8HtUl4e2KyWer7ayWNWny-cW5mNqJV …
```
> Fix a flaky throttling test

- libs/brig-types/test/unit/Test/Brig/Types/Arbitrary.hs
- libs/types-common/src/Data/Misc.hs
Fix for https://github.com/wireapp/wire-server/issues/339
> Fix ToJSON and arbitrary instance for PlainTextPassword

- libs/brig-types/src/Brig/Types/Connection.hs
- services/brig/src/Brig/API.hs
- services/galley/src/Galley/API/Util.hs
- services/galley/src/Galley/Intra/User.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Util.hs
The old endpoint (`GET /i/users/connections-status`) sinned in two ways:
* It took the list of users as a query parameter. This doesn't fly for
256 users.
* It gave N^2 responses (connections between all users), while most of the
time we only need to know connection status for connections from one
user to a bunch of other users.
The new `POST /i/users/connections-status` endpoint is pure as snow
in comparison.
> Add a new, more efficient connections-status endpoint

- libs/api-bot/src/Network/Wire/Bot/Crypto/Glue.hs
- libs/api-bot/src/Network/Wire/Bot/Monad.hs
- libs/api-client/src/Network/Wire/Client/HTTP.hs
- libs/extended/LICENSE
- libs/extended/extended.cabal
- libs/extended/src/Control/Concurrent/Async/Lifted/Safe/Extended.hs
- libs/extended/src/Options/Applicative/Extended.hs
- services/brig/brig.cabal
- services/brig/test/integration/API/User/Auth.hs
- stack.yaml
- tools/api-simulations/api-simulations.cabal
- tools/api-simulations/loadtest/src/Main.hs
- tools/api-simulations/loadtest/src/Network/Wire/Simulations/LoadTest.hs
* Changed command-line syntax: instead of `-min` and `-max` options, there is now a range parser.
* Added the `extended` library, containing `optparse-applicative` and `async` utilities.
* More fine-grained control over conversations: you can specify how many bots will/will not be sending messages. Useful when testing team size (sending 256^2 messages is bad)
* Added `--parallel-requests` for specifying the maximum number of requests that can happen in parallel (per conversation)
* Set user-agent for all requests originating from api-client
* Added `--clients` for testing with more than one client per bot
> Extend loadtest

- libs/wai-utilities/src/Network/Wai/Utilities/Server.hs
- stack.yaml
We want to treat
```
HTTP/1.1 404 Not Found
Date: Tue, 12 Sep 2017 12:15:37 GMT
Server: Warp/3.2.11.2
Transfer-Encoding: chunked
```
differently from
```
HTTP/1.1 404 Not Found
Content-Type: application/json
Date: Tue, 12 Sep 2017 12:15:18 GMT
Server: Warp/3.2.11.2
Transfer-Encoding: chunked
{
"code": 404, 
"label": "...", 
"message": "..."
}
```
i.e., the first one is an endpoint that does not exist while the second is an endpoint that _does_ exist and a `404` is an expected code from the APIs PoV (e.g., when calling `/notifications`)
> Differentiate between "expected" and "unexpected" 404

- services/proxy/src/Proxy/API.hs
i.e., requests to `[...]/proxy/googlemaps/maps/api/geocode/json?latlng=0,0` will be proxied to `maps.googleapis.com/maps/api/geocode/json?key=...&latlng=0,0`
TODO: It'd be nicer if we could match on a prefix like `/googlemaps` and route any request in the form of `/googlemaps/maps/api/:a/:b/:c/...` to `maps.googleapis.com/maps/api/:a/:b/:c`
> Route geocode requests to googlemaps too

- services/brig/src/Brig/API.hs
- services/brig/src/Brig/API/Types.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/Data/Activation.hs
- services/brig/test/integration/API/Provider.hs
- services/brig/test/integration/API/User/Account.hs
- services/brig/test/integration/API/User/Util.hs
- services/brig/test/integration/Util.hs
This PR includes the following changes:
* if a user tries to change the email to the exact same address, a 204 is returned
* if a user tries to change the local address of a verified email address, the change can now be seen also on the user's profile
Due to the fact that we need to test out non-trusted addresses ([meaning from domains not listed here](https://github.com/wireapp/wire-server/blob/fe39c4435fa87b2ff993886b47c9da8e7819c689/services/brig/src/Brig/Email.hs#L110)), a new internal endpoint was added so that an _actual email_ is not sent out (that could potentially give us problems with bounces)
> Email changes

- libs/libzauth/libzauth-c/Cargo.lock
- libs/libzauth/libzauth/Cargo.toml
Having Cargo.lock in git avoids surprises on CI when new (incompatible) crates are released.
> pin libzauth-c dependencies; use sodiumoxide 0.0.16 for now

- libs/brig-types/src/Brig/Types/Client.hs
- libs/brig-types/src/Brig/Types/Connection.hs
- libs/brig-types/src/Brig/Types/Team/Invitation.hs
- libs/brig-types/src/Brig/Types/User.hs
- libs/brig-types/test/unit/Test/Brig/Types/Arbitrary.hs
- libs/cargohold-types/src/CargoHold/Types/V3.hs
- libs/cargohold-types/src/CargoHold/Types/V3/Resumable.hs
- libs/galley-types/src/Galley/Types.hs
- libs/galley-types/src/Galley/Types/Teams/Intra.hs
- libs/types-common/src/Data/Json/Util.hs
- libs/types-common/test/Test/Properties.hs
- libs/types-common/types-common.cabal
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/Data/Client.hs
- services/brig/src/Brig/Data/Connection.hs
- services/brig/src/Brig/Data/User.hs
- services/brig/src/Brig/Team/DB.hs
- services/brig/src/Brig/User/Email.hs
- services/brig/test/integration/API/User/Account.hs
`UTCTimeMillis` is currently used like this:
```haskell
data User = User { ..., timestamp :: UTCTime, ... }
instance ToJSON User where
toJSON u = object [ ..., "timestamp" .= UTCTimeMillis (timestamp u), ... ]
```
This makes sure that the client will never see more than 3 decimal digits in time stamps.  The representation on the server side is not ideal, though:
1. The roundtrip-property `decode . encode === id` will fail on all timestamps with more digits.
2. The law that if `show x == show y` then `x == y` is broken.
This PR makes the data type opaque and adds a smart constructor and `Eq`, `Show`, `{To,From}JSON` instances that satisfy the above laws.
The implementation of `(==)` is not very fast, but I'm not sure it's worth optimizing?  I think we are using this only for serialization …
> Make UTCTimeMillis abstract and fix Eq, Show instances.

- deploy/docker-ephemeral/init.sh
rebased and tested on two machines.  it seems to work at least as good as before, and i could not reproduce the race condition that motivated this.
> Fix: wait for dynamo to come up before attempting to delete stale tables.

- libs/api-bot/src/Network/Wire/Bot/Monad.hs
- libs/brig-types/src/Brig/Types/User.hs
- libs/brig-types/test/unit/Test/Brig/Types/Arbitrary.hs
- services/brig/src/Brig/Data/User.hs
In spar, we will need to be able to pick a UUID for a user we want to create.
Otherwise we would not be able to find dangling users after crashed creation
attempts.
Adding an optional field for this to the `NewUser` type is a small, reasonably
safe change: the two place where they are pulled from the network are here:
```
$ git grep -Hn NewUser
[...]
services/brig/src/Brig/API.hs:1150:    NewUserNoSSO new <- parseJsonBody req
services/brig/src/Brig/API.hs:1189:    (uData :: NewUser)  <- parseJsonBody req
[...]
```
We only allow the 'UUID' to be chosen by the creator in the 'NewUser' case;
the 'NewUserNoSSO' case fails to parse if anybody tries.
> New field in NewUser for storing a UUID pre-fabricated.

- libs/api-client/src/Network/Wire/Client/API/Conversation.hs
- libs/galley-types/src/Galley/Types.hs
- libs/galley-types/src/Galley/Types/Swagger.hs
- libs/gundeck-types/src/Gundeck/Types/Presence.hs
- libs/types-common/src/Data/Json/Util.hs
- libs/types-common/src/Data/Misc.hs
- services/brig/test/integration/API/Provider.hs
- services/brig/test/integration/API/Team/Util.hs
- services/galley/galley.cabal
- services/galley/schema/src/Main.hs
- services/galley/schema/src/V27.hs
- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/Create.hs
- services/galley/src/Galley/API/Mapping.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Data/Queries.hs
- services/galley/src/Galley/Data/Types.hs
- services/galley/src/Galley/External.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/MessageTimer.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Util.hs
- services/gundeck/src/Gundeck/Env.hs
- services/gundeck/src/Gundeck/Monad.hs
- services/gundeck/src/Gundeck/Notification.hs
- services/gundeck/src/Gundeck/Presence/Data.hs
- services/gundeck/src/Gundeck/Push/Websocket.hs
> Add a per-conversation message timer

- libs/galley-types/src/Galley/Types/Swagger.hs
- services/galley/src/Galley/API.hs
* `:cnv` was missing sometimes
* In some places `message_timer` is not optional, but nullable
> Fix some inaccuracies in Swagger docs

- services/gundeck/src/Gundeck/API.hs
- services/gundeck/test/integration/API.hs
This PR simply exposes a previously internal only endpoint (was not needed by clients but useful for debugging purposes on the client side)
> Expose push tokens over the public API

- libs/brig-types/src/Brig/Types/Swagger.hs
- libs/brig-types/src/Brig/Types/User/Auth.hs
- services/brig/src/Brig/User/API/Auth.hs
- services/brig/src/Brig/User/Auth.hs
- services/brig/test/integration/API/User/Auth.hs
- services/brig/test/integration/Util.hs
The old name introduced in https://github.com/wireapp/wire-server/pull/329 was confusing and prone to create misunderstandings.
This end-point will be used for SSO login.  Neither does it violate our attack model, nor is security deteriorated in any way.  Without it, admins with access to the cassandra nodes on the server would still be able to impersonate any user by temporarily replacing their password.
> Change end-point name from /i/backdoor-login to /i/sso-login.

- libs/api-client/src/Network/Wire/Client/API/Conversation.hs
- libs/galley-types/src/Galley/Types.hs
- services/brig/test/integration/API/Provider.hs
- services/brig/test/integration/API/Team/Util.hs
- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/Create.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/MessageTimer.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Util.hs
Now we have an internal endpoint for creating them, and that endpoint is still used for tests. The public endpoint forbids creating them.
> Forbid managed conversations

- services/spar/package.yaml
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/API/Instances.hs
- services/spar/src/Spar/API/Test.hs
- services/spar/src/Spar/App.hs
- services/spar/src/Spar/Error.hs
- services/spar/src/Spar/Intra/Brig.hs
- services/spar/test-integration/Test/Spar/DataSpec.hs
- stack.yaml
on request by the client teams, we need to adjust the behavior after successful validation of the login credentials:
> Spar login success handler

- deploy/services-demo/conf/brig.demo.yaml
- services/brig/brig.cabal
- services/brig/brig.integration.yaml
- services/brig/src/Brig/API.hs
- services/brig/src/Brig/AWS.hs
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Email.hs
- services/brig/src/Brig/Options.hs
- services/brig/src/Brig/SMTP.hs
- services/brig/test/integration/API/User/Account.hs
- services/brig/test/integration/Main.hs
This PR introduces an optional way to send out emails: by using SMTP instead of forcing SES. The basic functionality works, want to improve a few things namely, we need to ensure that
Feedback on how the config file could look easier to read is welcome!
> Alternatively use SMTP for email

- services/spar/test-integration/Spec.hs
(background: kubernetes volume mounting is made easier if config and integration config are put in different directories; also: paths are now consistent with brig/galley/gundeck)
> consistent default integration test file path

- services/spar/src/Spar/API.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
- services/spar/test-integration/Util.hs
- services/spar/test/Test/Spar/APISpec.hs
A number of things can go wrong during the authreq; at that point, clients have already opened a web session and errors are difficult to handle, unless we wrap all these errors in html, similarly to how we reply in the [verdictHandlerWeb](https://github.com/wireapp/wire-server/blob/develop/services/spar/src/Spar/App.hs#L214-L249).
This shouldn't be part of [saml2-web-sso](https://github.com/wireapp/saml2-web-sso) since it is quite specific to our use case and thus was added only on spar.
> Add a HEAD request for prechecking of authn requests

- doc/Dependencies.md
- services/spar/package.yaml
This PR support for MacOS build:
+ Update homebrew dependencies in Dependency.md file
+ Fix filename case cabal issue https://github.com/haskell/cabal/issues/4739
> Update macos homebrew dependencies and filename case

- services/galley/src/Galley/API/Update.hs
Uninlined `ensureConvMember`, `traverse_`, `traverse`, `ensureGroupConv` and `when`.
I saw [neongreen](https://medium.com/@neongreen/wire-is-hiring-a-haskell-developer-and-an-operations-engineer-berlin-51e7f3ed3050) link to this as a typical file, read it a bit and made a few tweaks of the most agreeable sort.
> Refactor Update.hs

- libs/cassandra-util/cassandra-util.cabal
- libs/cassandra-util/src/Cassandra/Settings.hs
- services/brig/src/Brig/App.hs
- services/galley/src/Galley/App.hs
- services/gundeck/src/Gundeck/Env.hs
- services/spar/src/Spar/Run.hs
When initialising a connection to a cassandra cluster, we currently do this in 2 different ways:
1. connect to that hostname directly (be it an IP address or a DNS name)
2. use our internal `disco`, which expects a list of cassandra nodes and parses them in a "proprietary" 
Using 1. has a small problem when the C* cluster is behind a load balancer: it resolves the name once and keeps retrying connections to that same address. This PR aims to improve that behaviour, making connections to a DNS name behave a little more like when we use our `disco`.
> Try to do a DNS lookup to provide an initial list of contacts

- services/brig/src/Brig/Provider/API.hs
- services/brig/src/Brig/Provider/DB.hs
- services/brig/src/Brig/Team/API.hs
- services/brig/test/integration/API/Provider.hs
Currently it just returns whatever /services returns. I'll replace it with a fully-functional version later.
> Implement a stub for whitelisted services search

- libs/brig-types/src/Brig/Types/Provider.hs
- libs/brig-types/test/unit/Test/Brig/Types/Arbitrary.hs
- libs/brig-types/test/unit/Test/Brig/Types/User.hs
- libs/galley-types/src/Galley/Types/Teams.hs
- libs/galley-types/src/Galley/Types/Teams/Swagger.hs
- services/brig/brig.cabal
- services/brig/schema/src/Main.hs
- services/brig/schema/src/V17.hs
- services/brig/schema/src/V52.hs
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Data/User.hs
- services/brig/src/Brig/IO/Intra.hs
- services/brig/src/Brig/Provider/API.hs
- services/brig/src/Brig/Provider/DB.hs
- services/brig/src/Brig/Team/API.hs
- services/brig/src/Brig/Team/Util.hs
- services/brig/test/integration/API/Provider.hs
- services/brig/test/integration/API/TURN.hs
- services/brig/test/integration/API/Team.hs
- services/brig/test/integration/API/Team/Util.hs
- services/brig/test/integration/API/User/Account.hs
- services/brig/test/integration/API/User/Auth.hs
- services/brig/test/integration/API/User/Client.hs
- services/brig/test/integration/API/User/Util.hs
- services/brig/test/integration/Util.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Intra/User.hs
* ~Send out events when service whitelist status changes~
* ~through the endpoint~
* ~because of being deleted~ won't get done in this PR
* ~Events are sent out when whitelist status changes:~
* ~through the endpoint~
* ~because of being deleted~ won't get done in this PR
* ~No events when the status doesn't change (code 204).~
~**Lowercase `service_prefix` in production.** (or else search will break)~ done.
~Create a new permission for service handling. Or something.~ the permission system is broken anyway.
Cleanup whitelists when a team is deleted.
When a service is de-whitelisted, we want to:
* Kick the service out of all team conversations it's in.
When a service is deleted, we want to:
* Send events about de-whitelisting (tricky because event originates from a provider in this case …
> Service whitelisting, for real this time

- stack.yaml
the hsaml2 commit referenced before was destroyed when i merged a branch.  saml2-web-sso is just in here because i was already at it.
from here on, i will only merge PRs that have depencies pointing to commits that have already landed stable branches.
> Bump saml2-web-sso, hsaml2 deps.

- .gitignore
- build/alpine/Dockerfile.builder
This is the first step towards having automatic stack traces in integration tests. (The second step will be enabling `-xc` when running integration tests, and the third step will be just fixing makefiles/etc so that locally we would get stack traces as well.)
I checked locally and the image builds successfully; I can also upload it to Quay if nobody objects.
> Build profiling versions of libraries in alpine-builder

- deploy/docker-ephemeral/docker-compose.yaml
- deploy/services-demo/README.md
- deploy/services-demo/conf/brig.demo.yaml
- deploy/services-demo/resources/smtp-secret.txt
- libs/api-bot/src/Network/Wire/Bot/Email.hs
- libs/api-bot/src/Network/Wire/Bot/Monad.hs
- libs/api-bot/src/Network/Wire/Bot/Settings.hs
Allows sending real emails when e.g signing up via POST
localhost:8080/register
Note that these emails will most likely land in your spam folder.
WIP note: email sending works, but smoketests don't actually work (when the mailbot is configured to use gmail), since emails land in the spam folder, where the mailbot doesn't find them. Three options:
1. Make the smoketester also look in the spam folder
2. Invest time into using a mail server docker image from which emails are not labelled as spam (might be hard)
3. configure smoketester's mailbox.json to use an account without spam detection (e.g. another docker image running a mail server)
Thoughts?
> Add minimal smtp/postfix docker image to the demo

- deploy/services-demo/README.md
- deploy/services-demo/conf/brig.demo.yaml
- deploy/services-demo/conf/cargohold.demo.yaml
- deploy/services-demo/conf/galley.demo.yaml
- deploy/services-demo/conf/gundeck.demo.yaml
- deploy/services-demo/conf/proxy.demo.yaml
- deploy/services-demo/conf/spar.demo.yaml
For the demo setup: Along with ce342b4fd5ab2aebb305d20dfd37ed598eaf6999 (which also restricts docker images to localhost), restrict all services other than nginz to bind to localhost only.
> [demo]: bind haskell services to localhost by default, only expose nginz

- libs/tasty-cannon/src/Test/Tasty/Cannon.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Util.hs
- services/gundeck/test/integration/API.hs
- services/integration.yaml
- services/spar/package.yaml
- services/spar/spar.integration.yaml
- services/spar/src/Spar/Options.hs
- services/spar/src/Spar/Run.hs
- services/spar/test-integration/Test/Spar/DataSpec.hs
- services/spar/test-integration/Util.hs
- services/spar/test-integration/Util/MockIdP.hs
- services/spar/test-integration/Util/Types.hs
- services/spar/test-integration/resources/cert.pem
- services/spar/test-integration/resources/key.pem
- services/spar/test-integration/resources/pubkey.pem
- make some flaky integration tests less flaky (hopefully...)
- spar integration tests:
- fix behavior on concourse
- better error messages
- assert availability of mock idp
- make mock idp in spar integration tests serve via SSL
> Work on integration tests

- libs/galley-types/src/Galley/Types.hs
- services/galley/galley.cabal
- services/galley/schema/src/Main.hs
- services/galley/schema/src/V28.hs
- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Data/Instances.hs
- services/galley/src/Galley/Data/Queries.hs
- services/galley/src/Galley/Intra/Push.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Util.hs
- tools/api-simulations/smoketest/src/Network/Wire/Simulations/SmokeTest.hs
Currently, clients can only set 2 values related to muting a conversation: on/off and a _ref_ which is a reference of when a conversation was muted (a timestamp).
This PR introduces a new field (_otr_muted_status_, implemented as an _int32_) which allows clients to set a more granular value, per conversation (e.g., 0 may mean mute certain message types and 1 would mean mute other messages or calls). The meaning of each value must be agreed upon between different clients and the backend will make no validation of this value (other than being an int32).
Some TODO's related to _muting conversations_ and its consequences on _fallback notifications_ were added inline as comments.
> Extra muted conversation field

- services/nginz/Makefile
- services/nginz/README.md
This should work on Linux as well and it should not harm anything if OpenSSL paths change on macOS in the future. However, I'd like somebody familiar with Makefile syntax to take a closer look.
> Put OpenSSL paths for macOS into the nginz makefile

- deploy/docker-ephemeral/docker-compose.yaml
- deploy/services-demo/conf/brig.demo.yaml
- services/brig/brig.integration.yaml
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Options.hs
- services/brig/src/Brig/SMTP.hs
This PR introduces 2 changes:
1. Addresses an old comment, namely:
>     # if binding to port 25 is a problem,
>     # connection handling needs to be made more generic to accept
>     # alternative ports. See changes introduced in
>     # https://github.com/wireapp/wire-server/pull/405
Indeed it's a bit inconvenient to have to use privileged ports so it's always good to allow some flexibility here.
2. It changes the SMTP docker image which seems to work better than the current one; at least, I have been able to deliver emails without a problem with this solution. Note though that the communication between brig and this SMTP container should be done using `plain` protocol and then configure the container for the [desired scenario](https://github.com/namshi/docker-smtp#below-are-scenarios-f …
> Allow setting specific ports for SMTP and use different image for SMTP

- deploy/services-demo/register_idp.sh
We can give this to customers until the admin settings pages support registering IdPs.
Tested on staging to the point where I got an expected error for the bad metadata I sent, and I have tested the rest in swagger successfully, so I'm assuming this will work.
> Script for registering IdPs in wire teams.

- deploy/services-demo/conf/nginz/nginx.conf
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/API/Types.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
- services/spar/test-integration/Util.hs
nginz exposes the `/sso/` prefix without authentication, but the bind end-point needs to be authenticated.  so we give it its own prefix `/sso-initiate-bind/` prefix.
> Fix: URI path for initiate-bind.

- services/spar/package.yaml
- services/spar/src/Spar/Run.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
> Add metrics middleware to spar.

- Makefile
This is not relevant for production, and only for development if you ever use `make run-docker-builder`.
> Fix: use available env var for docker tag in dev make rule.

- services/spar/test-integration/Util.hs
@neongreen Is this the answer to your question?  If not please try again.  :-)
> Spar tests: add scim auth token to database in TestEnv.

- libs/gundeck-types/src/Gundeck/Types/Push/V2.hs
- libs/wai-utilities/src/Network/Wai/Utilities/Request.hs
- services/brig/src/Brig/API.hs
- services/brig/src/Brig/API/Handler.hs
- services/brig/src/Brig/Team/API.hs
- services/cannon/cannon2.integration.yaml
- services/cannon/src/Cannon/API.hs
- services/gundeck/gundeck.integration.yaml
- services/gundeck/src/Gundeck/API.hs
- services/gundeck/src/Gundeck/Push.hs
- services/gundeck/src/Gundeck/Push/Websocket.hs
- services/gundeck/src/Gundeck/Util.hs
- services/gundeck/test/integration/API.hs
- services/gundeck/test/integration/Main.hs
- services/integration.sh
- services/integration.yaml
Also:
- add a second cannon instance to integration tests;
- improve tests considerably around the bug;
There is also branch `gundeck-bulkpush-fix`, which is a less organised version of this branch.  both should be removed once this has landed at the latest.
> Fix: gundeck bulkpush option.

- README.md
https://github.com/wireapp/wire-server-deploy
> Self-hosting on kubernetes: Link to recently open-sourced wire-server-deploy

- libs/galley-types/src/Galley/Types.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/test/integration/API.hs
Current implementation sends out the update event as a plain int; the desired behaviour is that it's wrapped in a JSON object of type `ConversationReceiptModeUpdate` (as indicated on swagger)
> Use proper payload when sending out update events

- deploy/services-demo/conf/galley.demo.yaml
- services/galley/galley.cabal
- services/galley/galley.integration.yaml
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/Intra/Spar.hs
- services/galley/src/Galley/Intra/Util.hs
- services/galley/src/Galley/Options.hs
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/API/Types.hs
- services/spar/src/Spar/Data.hs
- services/spar/test-integration/Test/Spar/DataSpec.hs
- services/spar/test-integration/Test/Spar/SCIMSpec.hs
> Notify Spar when a team is deleted

- services/cannon/src/Cannon/API.hs
- services/cannon/src/Cannon/Options.hs
fixes inconsistency in #555 (code did not match config changes here; this PR makes options consistent with the other services)
> consistency: logLevel/logNetstrings are top-level configuration options

- services/nginz/third_party/nginx-zauth-module/zauth_module.c
This pull request fixes a bug in nginx-zauth-module. We pass the `&r->args.data` to `ngx_unescape_uri`, the pointer will be modified in `ngx_unescape_uri`, see https://github.com/nginx/nginx/blob/master/src/core/ngx_string.c#L1735. Then the argument variables in query string would be lost in nginx script.
You can confirm the trouble by this way:
1. in nginx.conf, create such a `location`:
```
location /bug {
return 200 "bug is $arg_bug";
}
```
2. visit this endpoint via curl: `curl -i -XGET http://localhost/bug?bug=zauth-bug`. You should get `bug is zauth-bug` however currently the value or this variable is null.
> Avoid modifying r->args.data, which breaks the $arg_name in nginx

- services/spar/src/Spar/Intra/Brig.hs
This avoids ugly errors if a user with a long SAML subject ID wants to have a user created via spar.
We could be even nicer here, and generate some random, user-readable, non-offensive-to-anybody username if using the SSO subject id fails.  Not sure it's worth it, though.
(Note that this is already causing CS noise because some users do not like this default, and are having trouble configuring the subject ID on the IdP side so they like the wire names.  We should really wait for SCIM to provide a more robust solution for these issues.)
> Prune SSO subject identities if they exceed 128 chars.

- README.md
> Warn about Docker running out of memory

- services/galley/src/Galley/API/Create.hs
without this, collaborators can only create *empty* conversations, but they need to create 1:1 convs, too.
> Make adding users implicit in CreateConversation permission.

- libs/brig-types/src/Brig/Types/Swagger.hs
- libs/brig-types/src/Brig/Types/Team/Invitation.hs
- libs/galley-types/src/Galley/Types/Teams.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/IO/Intra.hs
- services/brig/src/Brig/Team/API.hs
- services/brig/src/Brig/Team/DB.hs
Without this, the default role would have to be picked twice: once in the backend, and once in team settings.  This is both extra work and poses the risk of running out of sync.
With these changes, the backend stores all future `Invitation`s in the DB with a default role that is defined near the type.  For migration, we allow for database entries with missing `Role`, and fill in the default there again.  This is marked in the code as `FUTUREWORK: remove`.
> Always carry a Role in the Invitation type.

- libs/brig-types/test/unit/Test/Brig/Types/Arbitrary.hs
- libs/brig-types/test/unit/Test/Brig/Types/User.hs
- libs/galley-types/src/Galley/Types/Teams.hs
- services/brig/test/integration/API/Team.hs
- services/galley/test/integration/API/Teams.hs
This changes will mess with staging only, since none of the features touched have seen master yet.  All changes have been agreed on with the other teams.
1. json representation of TeamMember will look more like the one of Invitation, i.e. instead of { invited: { by: <uuid>, at: <timestamp> }, it will contain { created_by: <uuid>, created_at: <timestamp> }.
2. collaborator will disappear from everywhere, and partner will be used instead.  (when you send collaborator, the backend will hear "partner", but when you expect to receive collaborator, you are in trouble.
> Tidy up partner role.

- libs/wai-utilities/src/Network/Wai/Utilities/Server.hs
The proposed fix is very simple, and arguably not the most readable, but it solve the problem of two error messages interleaving each other by dropping all newlines.
Alternatives:
- replace newline with space, or `--`, or something else.
- use netstrings
- ?
> Fix: log multi-line error messages on one line.

- libs/brig-types/src/Brig/Types/Common.hs
- libs/brig-types/test/unit/Test/Brig/Types/Arbitrary.hs
- libs/brig-types/test/unit/Test/Brig/Types/Common.hs
- services/brig/brig.cabal
- services/brig/schema/src/Main.hs
- services/brig/schema/src/V56.hs
- services/brig/src/Brig/API.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Data/Blacklist.hs
- services/brig/src/Brig/Data/Instances.hs
- services/brig/test/integration/API/Team.hs
- services/brig/test/integration/API/User/Account.hs
- services/brig/test/integration/Util.hs
This PR is part of a cat and mouse game.
Happy to take comments about perhaps more consistent naming (`exclude`, `block`, `disallow`, `blacklist`, ... ?).
> Add support for disallowing certain phone number prefixes

- stack.yaml
- tools/bonanza/src/Bonanza/Metrics.hs
- tools/bonanza/src/Bonanza/Streaming/Kibana.hs
```
service: Network.Socket.getAddrInfo: does not exist (Name does not resolve)
```
Starting from network-2.7, `getAddrInfo` also prints the host that it was trying to connect to.
> Use network-2.7 for more informative "connection failed" errors

- snapshots/wire-1.0.yaml
- stack.yaml
This uses Stack's custom snapshot feature (<https://docs.haskellstack.org/en/stable/custom_snapshot/>). A custom snapshot extends the set of packages in the resolver and can be used from any other project (including other Wire repos). No more copying parts of stack.yaml from one project to another.
Custom snapshots are stored in `~/.stack`. This has several benefits:
* They survive `stack clean`. (Well, Git deps have to be cloned anyway because of a bug in Stack, but they won't be recompiled, only recloned, and for the biggest deps I've switched to using tarballs so that should be faster.)
* They survive branch switches (i.e. if different package versions are used in different branches, no recompiling is necessary when switching between the two).
* We no longer need to cache both `.stack` …
> Use custom snapshots

- services/spar/src/Spar/Data/Instances.hs
- stack.yaml
Changes:
- IdP Metadata parsing implements some corner cases from the standard now.
- Notice and capture more IO exceptions (instead of turning them into impore exceptions).
- Capture noise on stdout / stderr emitted by libxml2 (which is a C library used by hsaml2, which is used by saml2-web-sso, for xml dsigs).
Please take a look at https://github.com/wireapp/saml2-web-sso/pull/44 when you review this.
> Bump spar dependency

- services/spar/src/Spar/API.hs
- services/spar/src/Spar/API/Swagger.hs
- services/spar/src/Spar/API/Types.hs
- services/spar/src/Spar/API/Util.hs
- services/spar/src/Spar/App.hs
- services/spar/src/Spar/Data.hs
- services/spar/src/Spar/Data/Instances.hs
- services/spar/src/Spar/Error.hs
- services/spar/src/Spar/Intra/Brig.hs
- services/spar/src/Spar/Intra/Galley.hs
- services/spar/src/Spar/Options.hs
- services/spar/src/Spar/Orphans.hs
- services/spar/src/Spar/Run.hs
- services/spar/src/Spar/Scim/Swagger.hs
- services/spar/src/Spar/Scim/Types.hs
- services/spar/src/Spar/Types.hs
I'm very often bitten by "should X go to this module or to some other module?", so I thought spending a bit of time on adding module descriptions would be a good idea.
I would also love it if CI barked at PRs that introduce modules without documentation. Thoughts?
> Add module descriptions for all Spar modules

- services/integration.yaml
Ideally warp-tls should crash when the port is taken, but it doesn't do that for some reason. I'll wait until I get an answer to https://github.com/yesodweb/wai/issues/730 and then I might open another PR to further improve the situation (or just check for the port in `integration.sh`).
> Change the bot port in integration tests to something less common

- services/spar/test-integration/Spec.hs
- services/spar/test-integration/Test/Spar/Scim/AuthSpec.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
Purpose: Ensure that user management is secure and auth is respected
> Add Authorization tests to Spar regarding Scim User management

- services/brig/src/Brig/Phone.hs
I'd missed one section where I'd agreed to remove View Patterns as requested by @jschaul.
He asked that I fix it up :)
> Remove superfluous view pattern

- Makefile
- build/alpine/Dockerfile.builder
- build/alpine/Dockerfile.intermediate
Remove the wire-server directory after pre-builder so there aren't files polluting the builder image.
We can do this now, because @neongreen has moved our dependencies into a snapshot; meaning they will be cached outside of the project in `/root/.stack`.
He also mentions we only need to [build once](https://github.com/wireapp/wire-server-private/pull/118#issuecomment-462281113):
> We also don't have to build twice (with profiling and without profiling) because custom snapshots play nicely with profiling, unlike local `.stack-work` dependencies.
I'll still need to make the appropriate adjustments to our Ubuntu server cache to not keep those files around, but this was just a start on simplifying things.
Unfortunately this may cause problems with @fisx 's work environment, but I volunteer to …
> Use /root/.stack rather than local stack-work files.

- libs/brig-types/test/unit/Test/Brig/Types/Common.hs
- libs/galley-types/src/Galley/Types/Teams.hs
This is a production issue, but the web team agreed to provide a work-around and submit `{ "password": null }` rather than `{}`.
> Fix: empty objects `{}` are valid TeamMemberDeleteData.

- libs/bilge/src/Bilge/IO.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/MessageTimer.hs
- services/galley/test/integration/API/SQS.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Util.hs
- services/galley/test/integration/Main.hs
- services/galley/test/integration/TestSetup.hs
I was having some trouble writing easily re-usable test fixtures for a few reasons:
- Explicit arg passing makes writing higher-order helpers tricky, e.g. passing a test into a helper to run some transformation on it (e.g. modifying one of the arguments before running a test, passing a fixture in to a list of tests, etc.)
- explicit passing added a lot of noise; there were unused arguments everywhere.
- Previously, adding a new dependency on some service would mean changing EVERY test signature
Turns out this is pretty much exactly what reader monad is meant to solve;
Also by switching to an explicit TestM we can make changes there and gain the benefits in all tests; e.g. if we lift assertion functions we can gain the benefits everywhere.
This is strictly a refactoring; no behaviour …
> Refactor Galley Tests to use Reader Pattern

- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
Deletion calls out to brig asyncronously (hence the 204) so this test is very flakey and is breaking on CI; there's no guarantee that the user is properly deleted by the second time we call. We could add some threadDelay; but that's just slowing down our test suite and hiding the flakiness.
I prefer instead to just leave double-deletion undefined in the tests; in practice it will 404 unless you call it twice very quickly in which case it will 204 twice which I think is totally fine.
Thoughts @fisx?
> Adjust flaky test for user deletion in SCIM

- stack.yaml
Fixes wireapp/wire-server#656
See https://github.com/wireapp/saml2-web-sso/pull/50
> ADFS work-around.

- libs/wai-utilities/src/Network/Wai/Utilities/Request.hs
- libs/wai-utilities/src/Network/Wai/Utilities/Server.hs
- services/brig/src/Brig/API.hs
- services/brig/src/Brig/API/Handler.hs
- services/brig/src/Brig/Provider/API.hs
- services/brig/src/Brig/Team/API.hs
- services/brig/src/Brig/User/API/Auth.hs
- services/brig/src/Brig/User/API/Search.hs
- services/cannon/src/Cannon/API.hs
- services/cargohold/src/CargoHold/API.hs
- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/Create.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/App.hs
- services/gundeck/src/Gundeck/API.hs
- services/gundeck/src/Gundeck/Monad.hs
- services/gundeck/src/Gundeck/Presence.hs
- services/gundeck/src/Gundeck/Push.hs
Figuring out "which request body type does this handler take" is a constant annoyance for me. Should be easier with this change.
If you think it's worth it, I'll migrate the rest.
> Allow writing request types in handler signatures

- snapshots/README.md
- snapshots/wire-1.0.yaml
- snapshots/wire-1.1.yaml
- snapshots/wire-1.2.yaml
Now wire-1.2.yaml contains a link to wire-1.1.yaml, and not just a relative path.
Without this PR we can't use wire-server snapshots in other repos, because Stack is not smart enough to fetch snapshots based on relative paths.
From this point on, the resolver/snapshot files *actually* have to be immutable.
This PR will cause another "copying precompiled package" cascade. @fisx sorry!
> Use URLs for snapshots; switch fork repos

- deploy/services-demo/conf/brig.demo.yaml
Forgot to change the `brig.demo.yaml` config after https://github.com/wireapp/wire-server/pull/612
This PR fixes that.
> Add missing config options

- libs/wai-utilities/src/Network/Wai/Utilities/Server.hs
- services/spar/src/Spar/Run.hs
(they happen all the time, and that's fine!)
> Remove middleware for warning about errors that are not exceptions.

- services/spar/src/Spar/Intra/Brig.hs
- stack.yaml
> Fix: saml implicit user creation does not choke on odd but legal names.

- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/Unique.hs
- services/brig/src/Brig/User/Handle.hs
- services/brig/test/integration/API/User/Handles.hs
- services/spar/src/Spar/App.hs
- services/spar/src/Spar/Data.hs
- services/spar/src/Spar/Data/Instances.hs
- services/spar/src/Spar/Intra/Brig.hs
- services/spar/src/Spar/Scim.hs
- services/spar/src/Spar/Scim/Auth.hs
- services/spar/src/Spar/Scim/Types.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Test/Spar/DataSpec.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
- services/spar/test-integration/Util/Core.hs
- services/spar/test-integration/Util/Scim.hs
- services/spar/test/Test/Spar/ScimSpec.hs
- stack.yaml
The new tests fail thusly:
```
Failures:
test-integration/Test/Spar/Scim/UserSpec.hs:543:22: 
1) Spar.Scim.User, DELETE /Users/:id, should delete user from brig, spar.scim_user, spar.user
expected: (Nothing,Nothing,Nothing)
but got: (Just (User {userId = 3eb69525-b292-44a7-bba3-b33af69733a2, userIdentity = Just (SSOIdentity (UserSSOId {userSSOIdTenant = "<Issuer xmlns:samlp=\"urn:oasis:names:tc:SAML:2.0:protocol\" xmlns:samla=\"urn:oasis:names:tc:SAML:2.0:assertion\" xmlns:samlm=\"urn:oasis:names:tc:SAML:2.0:metadata\" xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\" xmlns=\"urn:oasis:names:tc:SAML:2.0:assertion\">https://issuer.net/_802b24ec-0542-4ff5-bd82-b688478b4272</Issuer>", userSSOIdSubject = "<NameID xmlns:samlp=\"urn:oasis:names:tc:SAML:2.0:protocol\" …
```
> Fix: user deletion via scim

- libs/metrics-core/src/Data/Metrics.hs
Looks like a few metrics use `-` in them and I missed it the first time; this should solve that (and catch anything else I missed) 👍 
Example:
Sanitize the metric name 
```
net.resources._conversations_:cnv-members_:usr.DELETE.time.960
```
into the valid name 
```
net_resources_conversations_:cnv_members_:usr_delete_time_960
```
> Further sanitize metric names in prometheus

- deploy/services-demo/create_test_user.sh
On Linux, both variants have the same output, but on mac, allegedly only the second one works:
```sh
$ echo '{"email":"l8TVlbK0@example.com","locale":"en","accent_id":0,"picture":[],"name":"demo","id":"29740ea6-c54a-4a92-8fd5-3f8c5b05cdc3","assets":[]}' | sed 's/.*"id":"\([0-9a-z-]\+\)".*/\1/'
$ echo '{"email":"l8TVlbK0@example.com","locale":"en","accent_id":0,"picture":[],"name":"demo","id":"29740ea6-c54a-4a92-8fd5-3f8c5b05cdc3","assets":[]}' | sed 's/.*\"id\":\"\([a-z0-9-]*\)\".*/\1/'
```
See https://github.com/wireapp/wire-server/issues/712 (thanks @limengyu1990!)
> sed compat

- stack.yaml
discussion: https://github.com/wireapp/wire-server/issues/678,
https://github.com/wireapp/wire-server/issues/727
> Gitlab seems to need the `.git` suffix on repo urls.

- libs/wai-utilities/src/Network/Wai/Utilities/Server.hs
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/API/Types.hs
- services/spar/src/Spar/App.hs
- stack.yaml
This is mostly to pull in https://github.com/wireapp/saml2-web-sso/pull/52, which helps with drifting IdP clocks.  During investigating this, I did some refactorings that I would like to keep that are the only thing you can see in this PR.
>  Add hard-wired 60 sec tolerance to all time bounds checks.

- build/alpine/Dockerfile.builder
Originally, the plan was to build integration tests with `--profile` and get nice stacktraces without having to add `HasCallStack` everywhere.
However, we ended up adding `HasCallStack` anyway, and half a year later we still don't have tests with profiling.
Furthermore, compiling tests with profiling is not trivial. We would have to build alpine-intermediate both with and without profiling, bringing it from 20m to probably 40m. I'm not sure whether it's avoidable. We also need to make sure that service binaries are built without profiling, which is annoyingly hard thanks to bugs like <https://github.com/commercialhaskell/stack/issues/3827>.
If somebody wants to add stack traces later, it will be easy for them to do. For now we can just merge this PR and enjoy a smaller alpine-builder.
> Don't build alpine-builder with --profile

- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
This is a minor bug that manifests when a user is provisioned via SCIM.
When a user is provisioned via SCIM, our backend receives a user record that includes the `"schemas"` field. It might include `"urn:wire:scim:schemas:profile:1.0"`, or it might not.
Before this PR, we just wrote the received user record into the database. After this PR, we also make sure to overwrite the list of schemas with schemas we actually support. (Even if the received record doesn't have `"richInfo"`, we still return it – so we have to signal `"richInfo"` support in the schema.)
This is a freshly created SCIM user record in Spar database, before and after this PR:
```diff
{
-   "schemas": [ "urn:ietf:params:scim:schemas:core:2.0:User" ],
+   "schemas": [
+        "urn:ietf:params:scim:schemas:core:2.0:User",
+ …
```
> Add Wire-specific schemas to SCIM user records

- libs/metrics-wai/src/Data/Metrics/Middleware/Prometheus.hs
- stack.yaml
it turns out cloning functions that are marked NOINLINE and contain a top-level call to unsafePerformIO is changing behavior of your code.  D'OH!
> Fix prometheus mutation.

- Makefile
- build/alpine/Makefile
These changes add the ability to run custom builds using the `$DOCKER_USER` variables starting at the prebuilder stage, while retaining original functionality of course. 
For example
```shell
DOCKER_USER='james.brink' make docker-prebuilder docker-builder docker-deps docker-intermediate
```
> Refactor Makefiles to support $DOCKER_USER through all docker build targets

- libs/wai-utilities/src/Network/Wai/Utilities/Server.hs
- services/cannon/src/Cannon/API.hs
- services/cannon/src/Cannon/App.hs
Second episode after the popular pilot #749
If some application (or inner middleware) responds with status >=500 rather than throwing an exception, turn that into an actual exception so `catchErrors` can do its thing.
> Cannon analytics (2)

- libs/types-common/test/Test/Properties.hs
Fixes #764 
This PR restricts input to [`Ascii.unsafeFromByteString`](https://github.com/wireapp/wire-server/blob/f03d8f701bfb3458e81dd446f4f772eee01875e8/libs/types-common/src/Data/Text/Ascii.hs#L293-L297) to valid input in the test.  It is safe to not test invalid input, since the function name suggests caution, and we're actually only ever calling it on valid input:
```sh
$ git grep -Hn unsafeFromByteString
libs/types-common/src/Data/Text/Ascii.hs:52:    , unsafeFromByteString
libs/types-common/src/Data/Text/Ascii.hs:196:encodeBase64 = unsafeFromByteString . B64.encode
libs/types-common/src/Data/Text/Ascii.hs:236:encodeBase64Url = unsafeFromByteString . B64Url.encode
libs/types-common/src/Data/Text/Ascii.hs:267:encodeBase16 = unsafeFromByteString . B16.encode …
```
> Fix flaky unit test.

- libs/brig-types/src/Brig/Types/Team/LegalHold.hs
- libs/brig-types/src/Brig/Types/Test/Arbitrary.hs
- services/galley/src/Galley/API/Swagger.hs
a minor sync of the swagger docs with the actual interface.
one more thing i noticed: `UserLegalHoldStatus` is returned in a response body as a string, but json is sometimes required to be wrapped in an object.  Not sure if that's outdated or still a requirement.  if so, we can just write a newtype `UserLegalHoldStatusObject` that wraps the json string into a `{ "status": ... }`.
> legalhold swagger updates

- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/LegalHold.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
> Legalhold remove settings on disable

- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/LegalHold.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
Exposes the GET LH status so that admins can view this information. In addition, it _actually_ checks for LH disabled at the DB level so that we can manually disable LH using the internal endpoint.
> Expose legalhold status and check if it is really disabled

- libs/brig-types/src/Brig/Types/Team/LegalHold.hs
- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/LegalHold.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
`GET "/teams/:tid/legalhold"` was not needed; renamed `"info"` to `"settings"`
> Remove unnecessary endpoint and rename info to settings

- services/brig/src/Brig/API/Client.hs
- services/brig/src/Brig/IO/Intra.hs
- services/brig/src/Brig/User/Event.hs
- services/brig/src/Brig/User/Event/Log.hs
- services/brig/test/integration/API/User/Client.hs
Before, devices did not know when legalhold would go from pending to disabled. Even when legalhold was disabled before the user approved it, the notification to approve would still show up. We now make sure that we send a notification when legalhold gets disabled, such that the client can react appropriately.
> legalhold cancel pending

- services/brig/src/Brig/Data/Client.hs
This line accounts for > 90% of our log lines and does not really provide any interesting info besides the fact that these users should probably publish prekeys more often.
> Log this message only at debug level

- libs/cassandra-util/src/Cassandra.hs
- libs/cassandra-util/src/Cassandra/CQL.hs
- libs/cassandra-util/src/Cassandra/Schema.hs
- services/brig/index/src/Eval.hs
- services/brig/src/Brig/App.hs
- services/galley/journaler/src/Main.hs
- services/galley/src/Galley/App.hs
- services/gundeck/src/Gundeck/Env.hs
- services/spar/src/Spar/Run.hs
- tools/db/auto-whitelist/src/Main.hs
- tools/db/service-backfill/src/Main.hs
We're running cassandra 3.11+ across the board so this operation should be safe. Relevant changes [from V3](https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v4.spec#L1171-L1187)
> Upgrade CQL protocol version to V4

- services/brig/src/Brig/API/Client.hs
- services/brig/src/Brig/IO/Intra.hs
- services/brig/src/Brig/User/Event.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/LegalHold.hs
- services/galley/src/Galley/API/Swagger.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
- services/galley/test/integration/API/Util.hs
better tests, plus:
- make LH disabled by default in all teams.
- do not allow to create LH devices via `POST /clients` any more.
- always test that LH is enabled first when performing LH operations.
> LH: disable by default; tests.

- libs/brig-types/src/Brig/Types/Activation.hs
- libs/brig-types/src/Brig/Types/Common.hs
- libs/brig-types/src/Brig/Types/Connection.hs
- libs/brig-types/src/Brig/Types/Intra.hs
- libs/brig-types/src/Brig/Types/User.hs
- libs/brig-types/src/Brig/Types/User/Auth.hs
- libs/galley-types/src/Galley/Types/Bot/Service/Internal.hs
- libs/galley-types/src/Galley/Types/Teams.hs
- libs/galley-types/src/Galley/Types/Teams/Internal.hs
- libs/metrics-core/src/Data/Metrics.hs
- libs/types-common/src/Data/Json/Util.hs
- libs/types-common/src/Data/Misc.hs
This is needed for the servant-swagger / swagger2 business.  It's not an
exhaustive change set, just what I needed when playing with this.
> Add generics instances to common, brig, galley types.

- libs/brig-types/package.yaml
- libs/galley-types/package.yaml
- libs/metrics-wai/package.yaml
- libs/metrics-wai/src/Data/Metrics/Test.hs
- libs/types-common-aws/package.yaml
- libs/types-common/package.yaml
- services/brig/package.yaml
- services/brig/test/integration/Main.hs
- services/cannon/package.yaml
- services/cannon/test/Main.hs
- services/cargohold/package.yaml
- services/cargohold/test/integration/Main.hs
- services/galley/package.yaml
- services/galley/test/integration/Main.hs
- services/gundeck/package.yaml
- services/gundeck/test/unit/Main.hs
- services/proxy/package.yaml
- services/spar/package.yaml
- services/spar/test/Test/Spar/APISpec.hs
- stack.yaml
- tools/stern/package.yaml
Develop contains some changes in `package.yaml` files that make some executables depend on packages they don't need, which can trigger dynamic linker errors in our ~~docker~~ ops setup.
This PR reverts these changes and adds some more conservative ones to get the tests added in #808 to build again.
> Fix package deps

- libs/extended/package.yaml
- libs/extended/src/Servant/API/Extended.hs
- services/spar/src/Spar/API/Types.hs
- services/spar/src/Spar/Error.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
We introduce a variant of `ReqBody` that allows us to pick a function that wraps the parser error (`String`) into a `ServantErr`.
Fixes #703
Future work (also noted in the code):
- fix swagger2 instance for new body type
- error construction should be in the custom monad (so we can log)
- move everything upstream into github://haskell-servant/servant/
> Allow servant request body parsers that throw json errors.

- libs/bilge/src/Bilge/Response.hs
- libs/brig-types/test/unit/Test/Brig/Types/Common.hs
- libs/galley-types/package.yaml
- libs/galley-types/src/Galley/Types/Teams.hs
- libs/galley-types/src/Galley/Types/Teams/Feature.hs
- libs/galley-types/src/Galley/Types/Teams/SSO.hs
- services/galley/schema/src/Main.hs
- services/galley/schema/src/V33.hs
- services/galley/schema/src/V34.hs
- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/LegalHold.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/Data/Instances.hs
- services/galley/src/Galley/Data/Queries.hs
- services/galley/src/Galley/Data/SSO.hs
- services/galley/src/Galley/Data/Teams.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
- services/galley/test/integration/API/Util.hs
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/Error.hs
- services/spar/src/Spar/Intra/Galley.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
- services/spar/test-integration/Util/Core.hs
- tools/stern/src/Stern/API.hs
- tools/stern/src/Stern/Intra.hs
This PR intends to add an extra value to enable/disable SSO per team: current default is enabled. In addition, it moves all "flags" under a single CF since it's easier to manage and helps keeping all these "flags" in one place. Feel free to keep it as-is if you find that isolation is preferable.
TODO:
- ~~[ ] There's a TODO in the code, have a look at that too: separate PR~~
> New feature flags backend

- libs/api-client/src/Network/Wire/Client/API/Push.hs
- libs/api-client/src/Network/Wire/Client/HTTP.hs
- libs/cassandra-util/src/Cassandra/Schema.hs
- libs/imports/src/Orphans.hs
- services/brig/index/src/Main.hs
- services/brig/src/Brig/API/Handler.hs
- services/brig/src/Brig/Options.hs
- services/cannon/src/Cannon/API.hs
- services/cannon/src/Cannon/App.hs
- services/cannon/src/Cannon/Options.hs
- services/galley/journaler/src/Journal.hs
- services/galley/journaler/src/Main.hs
- services/galley/src/Galley/Intra/Client.hs
- services/galley/src/Galley/Options.hs
- services/galley/src/Galley/Run.hs
- services/galley/test/integration/API/SQS.hs
- services/galley/test/integration/Main.hs
- services/proxy/package.yaml
- services/proxy/src/Proxy/API.hs
- services/proxy/src/Proxy/Options.hs
- services/proxy/src/Proxy/Proxy.hs
- services/spar/src/Spar/App.hs
- services/spar/src/Spar/Error.hs
- services/spar/src/Spar/Run.hs
- services/spar/src/Spar/Scim/User.hs
We want to make sure that we were using the `MonadLogger` typeclass everywhere, as this will make it easy to consistently inject metadata into the logs throughout the project. 
Turns out,  most places where already fine.
I made this PR by using `sed` and then making stuff compile. So maybe some places we could have left untouched. We should go over the diff and decide what things do not need to be changed, such that the diff becomes a bit smaller
> Cleanup logging

- tools/stern/src/Stern/API.hs
Revert this commit if once LH tokens are fully implemented and ready for production use.
> Block legalhold on stern / backoffice.

- services/brig/brig.integration.yaml
- services/brig/src/Brig/API/Error.hs
- services/brig/src/Brig/API/Types.hs
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Budget.hs
- services/brig/src/Brig/Options.hs
- services/brig/src/Brig/User/Auth.hs
- services/brig/test/integration/API/User/Account.hs
- services/brig/test/integration/API/User/Auth.hs
- services/brig/test/integration/Util.hs
Implements https://github.com/wearezeta/backend-issues/issues/841#issuecomment-518033685 .
Open questions:
1. I use `forM_` instead of `pooledForConcurrentlyN_` [here](https://github.com/wireapp/wire-server/blob/33a66e5732404bc8de91d9329dd3347d8d5be622/services/brig/test/integration/API/User/Auth.hs#L246).  The latter will fail because `Bridge.Budget` is not concurrency-proof: if two threads / services request a budget coin concurrently, only one of them will decrement the budget value in cassandra.  We could use [counters](https://cassandra.apache.org/doc/latest/cql/types.html#counters) instead of `int` in the [schema](https://github.com/wireapp/wire-server/blob/33a66e5732404bc8de91d9329dd3347d8d5be622/services/brig/schema/src/V37.hs), but it is unclear what that will mean for the other …
> Limit login retries

- services/brig/src/Brig/API.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/IO/Intra.hs
- services/brig/src/Brig/Team/Util.hs
- services/brig/test/integration/API/User/Auth.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
- services/spar/test-integration/Util/Core.hs
galley has an end-point only used by spar for deciding team ownership.  so far this end-point has not acknowledged owners if they didn't have an email address.
this constraint is relaxed here, the code for membership status is cleaned up, and tests are added.
> SSO permissions

- libs/api-bot/package.yaml
- libs/api-client/package.yaml
- libs/bilge/package.yaml
- libs/cargohold-types/package.yaml
- libs/cassandra-util/package.yaml
- libs/gundeck-types/package.yaml
- libs/imports/package.yaml
- libs/metrics-collectd/package.yaml
- libs/ropes/package.yaml
- libs/sodium-crypto-sign/package.yaml
- libs/ssl-util/package.yaml
- libs/tasty-cannon/package.yaml
- libs/types-common-aws/package.yaml
- libs/types-common-journal/package.yaml
- libs/types-common/package.yaml
- libs/wai-utilities/package.yaml
- libs/zauth/package.yaml
- services/brig/package.yaml
- services/cannon/package.yaml
- services/cargohold/package.yaml
- services/gundeck/package.yaml
- services/proxy/package.yaml
- tools/api-simulations/package.yaml
- tools/bonanza/package.yaml
- tools/makedeb/package.yaml
- tools/stern/package.yaml
(with these sections, we need to manually add new modules to expose them; without, everything gets exposed by default.)
cherry-picked from https://github.com/wireapp/wire-server/pull/826 because controversial.
> Remove `exposed-modules` sections from all package.yaml files.

- libs/bilge/src/Bilge/IO.hs
- libs/imports/src/Imports.hs
- services/cannon/src/Cannon/WS.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/MessageTimer.hs
- services/galley/test/integration/API/SQS.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
- services/galley/test/integration/API/Util.hs
Debug.Trace should not be used in production code, but it's easy to miss a trace statement in a PR.  It's much easier to see that `Debug.Trace` is still imported somewhere.  Also, not providing it implicitly makes it clearer that it shouldn't be used in production code.
> Remove Debug.Trace from Imports.

- services/brig/test/integration/API/User/Connection.hs
- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/Query.hs
- services/galley/test/integration/API.hs
Fixes https://github.com/wearezeta/backend-issues/issues/870
@tiago-loureiro writes:
> Currently there is no distinction between "there is no conversation with id X" and "you are not a member of the conversation".
> 
> This creates a problem now that we will effectively add "conversation deletion" on the UI and clients need to distinguish between the 2 (i.e., was I kicked or did the conversation get deleted). This is particularly important for new devices or when missing a lot of notifications (note that when deleting conversations clients must delete this locally too but not when getting kicked/leaving conversations).
This PR changes the behavior to return two errors for these two cases:
```haskell
Error status404 "no-conversation" "conversation not found"
Error status403 "access-denied" …
```
> Specialize the error cases on conversation lookup.

- libs/tasty-cannon/src/Test/Tasty/Cannon.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/API/Util.hs
- services/galley/test/integration/API/Teams.hs
Start sending `conversation.delete` event also to all team members (whether in the conversation or not).  `team.conversation-delete` will still be sent as before.
This solves the following issue:
> One side effect of getting only one of the team.converation-delete and conversation.delete events is that we can't display who deleted a conversation in a team. The team.converation-delete event doesn't contain the from field.
Also, lots of small refactoring.
> Better events for deletion of team conversations

- services/brig/src/Brig/API.hs
- services/galley/src/Galley/API.hs
Fixes https://github.com/wearezeta/backend-issues/issues/885
> Fix swagger.

- services/brig/src/Brig/User/Auth.hs
Currently we log this _really_ often, and at the `Warn` log level; the `mustSuspend` value is also redundant.
In addition, I added an extra field named `"action"` (`"type"` sounds more appropriate but I'd generally avoid using such keywords that may be reserved or whatnot): I think we should have a consistent way of tracking and filtering important events. The name of the event tries to follow the convention of [our push formats](https://github.com/wireapp/wire-server/blob/develop/services/brig/src/Brig/IO/Intra.hs#L279-L374).
In general, I'd like to then start a little internal discussion on how we structure logs, etc., and also document this so that it becomes easier to trace logs, etc.
> Log warnings only when users are suspended

- CHANGELOG.md
- deploy/services-demo/README.md
- deploy/services-demo/conf/nginz/zauth_acl.txt
- docs/reference/config-options.md
- libs/bilge/src/Bilge/Request.hs
- libs/brig-types/test/unit/Test/Brig/Types/Common.hs
- libs/galley-types/package.yaml
- libs/galley-types/src/Galley/Types/Teams.hs
- mailboxes.json
- services/brig/src/Brig/API.hs
- services/galley/galley.integration.yaml
- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/Options.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
- services/restund/README.md
- tools/stern/package.yaml
- tools/stern/src/Stern/API.hs
- tools/stern/src/Stern/Intra.hs
- tools/stern/src/Stern/Swagger.hs
- tools/stern/src/Stern/Types.hs
This should not change behavior in any observable way except for better error messages.  But it does add more type information to the code that should make mistakes like [this one](https://github.com/wireapp/wire-server/pull/844) harder in this particular place.  We should do that more in general!.
Fixes https://github.com/wearezeta/backend-issues/issues/877 (mostly with ed28786)
> Cleanup stern

- libs/metrics-wai/src/Data/Metrics/Servant.hs
- services/cannon/package.yaml
- services/cannon/src/Cannon/API.hs
- services/cannon/src/Cannon/Dict.hs
- services/cannon/src/Cannon/Run.hs
- services/cannon/src/Cannon/Types.hs
- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/Run.hs
- services/gundeck/src/Gundeck/API.hs
- services/spar/src/Spar/Run.hs
@tiago writes:
> Start cannon and curl localhost:8083/i/metrics
> 
> Notice there is no net_websocket_clients on the output?
> 
> Now try curl localhost:8083/i/monitoring and again curl localhost:8083/i/metrics.
> 
> Look at what happens! :) Anyway... just wanted to share this... so, culprit
> 
> https://github.com/wireapp/wire-server/blob/develop/services/cannon/src/Cannon/API.hs#L72-L77
> https://github.com/wireapp/wire-server/blob/develop/services/galley/src/Galley/API.hs#L1007-L1010
> 
> Can we please move those to a different place? Calling /i/monitoring should only render metrics and not do some extra logic.
> Fix metrics.

- services/gundeck/test/integration/API.hs
The recoverAll was not needed because the test itself is already running inside `retryWhile`.
> Sneak up on flaky test.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/other.md
- .github/ISSUE_TEMPLATE/question.md
Following https://help.github.com/en/articles/creating-issue-templates-for-your-repository
This creates a template to use when issues are opened, which may help provide more context and require less back-and-forth initally.
> Add issue templates

- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/User/Auth.hs
- services/galley/src/Galley/API/LegalHold.hs
- services/galley/src/Galley/API/Teams.hs
E.g.  this is useful to see if someone is actively trying to reset
someone's password.
> Add debug logging for endpoints that don't have a user but affect a user

- services/spar/package.yaml
- services/spar/schema/src/Main.hs
- services/spar/schema/src/V6.hs
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/API/Swagger.hs
- services/spar/src/Spar/API/Types.hs
- services/spar/src/Spar/Data.hs
- services/spar/src/Spar/Types.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
- services/spar/test-integration/Util/Core.hs
- services/spar/test/Arbitrary.hs
- services/spar/test/Test/Spar/APISpec.hs
- Change`IdPMetadataInfo` to contain the raw text from the xml body.
- Introduce a new content type tag for servant that can feed the raw text to `IdPMetadataInfo` (the `SAML.XML` tag we used before comes with its own parser instances that do not allow for that).
- Store this raw text in a new table with a new pair of cassandra helper functions (the `SAML.storeIdPConfig` function that could have been used for that has its type fixed by the `saml-web-sso` library as well; I think somewhere in the library we want to be able to call the database functions, so the library needs to decide the type).
Why?  Will give us more info for trouble shooting!
> Store raw idp metadata with typed details in c*

- deploy/services-demo/create_team_members.sh
Nothing big, part of it a bit opinionated, but I'm happy to remove anything that's controversial.
The most important change is probably that the output now contains the failed email addresses in the same lines as the errors, which makes it easier to generate a list of failed accounts with grep.
> Tweak invite script

- docs/reference/provisioning/scim-via-curl.md
UUIDs are a bit confusing here. It is more common that your SAML provider is configured to have email addresses isntead
> Change SCIM documentation to actually use SAML Ids

- shell.nix
- stack-deps.nix
- stack.yaml
Stack started not liking being called from a nix-shell anymore, because
stack wants to create the nix-shell itself so it does some
auto-detection and crashes.  To trick it into doing the right thing
again, we only use the nix-shell for non-build-deps and just for dev
tools, then stack itself will call another nix-shell file that just
handles build deps for the stack project.
(just opening this PR for arian since he's budy :))
> stack:  Split nix stuff into build deps and runtime deps.

- libs/types-common/package.yaml
- libs/types-common/test/Main.hs
- libs/types-common/test/Test/SizedHashMap.hs
- services/gundeck/gundeck.integration.yaml
- services/gundeck/package.yaml
- services/gundeck/src/Gundeck/Env.hs
- services/gundeck/src/Gundeck/Options.hs
- services/gundeck/src/Gundeck/Push.hs
- services/gundeck/src/Gundeck/Run.hs
- services/gundeck/src/Gundeck/ThreadBudget.hs
- services/gundeck/test/unit/MockGundeck.hs
- services/gundeck/test/unit/ThreadBudget.hs
- stack.yaml
Fixes https://github.com/zinfra/backend-issues/issues/647
This is downwards compatible in the sense that if you don't change the config, the behavior of the gundeck before and after this PR won't be distinguishable in any way.
If we add a budget to the configuration, `push1'` (formerly `push1`) will only be called *sometimes*, which means there is a chance push notifications will be lost.  On the bright side, this is a robust way to limit the number of parallel runs of `push1`, which makes it a net win, since we won't choke on SNS outages any more.
Tasks:
FUTUREWORK: there are two branches with interesting, but buggy code for testing the lower bound of running threads with quickcheck-state-machine:
- https://github.com/wireapp/wire-server/blob/fisx/gundeck-handling-sns-outages-backup/servi …
> Make gundeck handle AWS outages better.

- services/gundeck/src/Gundeck/ThreadBudget.hs
Currently, we get spammed with these warnings before any traffic
happens, due to an incorrect handling of booleans introduced in #869 .
```
[gundeck] W, request=N/A, watchThreadBudgetState: total overall thread budget diverged from async weights (repaired).
[gundeck] W, request=N/A, watchThreadBudgetState: total overall thread budget diverged from async weights (repaired).
[gundeck] W, request=N/A, watchThreadBudgetState: total overall thread budget diverged from async weights (repaired).
```
It's questionable whether this "sanitization" is necessary and should be used at all, as [a comment](https://github.com/wireapp/wire-server/blob/develop/services/gundeck/src/Gundeck/ThreadBudget.hs#L63-L72) indicates this should only be used in testing (but it's used in the "prod" watcher thread …
> gundeck: fix incorrect boolean logic

- services/gundeck/package.yaml
- services/gundeck/src/Gundeck/ThreadBudget.hs
- services/gundeck/test/bench/Main.hs
Just a little experiment to extablish whether we really want to call the more expensive `budgetSpent`, and not just `bsize`, for the metrics.
> benchmarking for O(n) function, remove expensive call from atomicModifyIORef

- services/galley/src/Galley/API/Teams.hs
- services/galley/test/integration/API/Teams.hs
Events about deleted conversations do not need to be sent to everyone
when a team is deleted. Indeed, it is harmful in that it leads to performance problems:
For large teams with many conversations, notifying
every team member about that fact that every conversation has been
deleted creates a lot of events.
None of these events are useful, since on a team deletion, the accounts
of every user are deleted, i.e. in practice these events cannot be read.
This PR fixes the bug that was introduced in #849
> Do not send events to team members to be deleted

- snapshots/wire-1.4.yaml
- stack.yaml
We have updated https://github.com/wireapp/http-client to [wire-20191104](https://github.com/wireapp/http-client/tree/wire-2019-11-04), which includes http-client-openssl-0.2.2.0, and as such should include SNI support when initiating HTTPS connections.
> http-client: bump to wire-20191104

- services/brig/brig.integration.yaml
- services/brig/src/Brig/InternalEvent/Process.hs
- services/brig/src/Brig/Options.hs
- services/galley/galley.integration.yaml
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/Options.hs
Even though #897 already reduces the amount of events sent on team deletions, the function logic on team deletions is unbounded in the number of events sent in parallel: Every non-team member of every team conversation gets an event for each conversation that is deleted (N=unbounded), and every team member gets an event that their team has been deleted (M=MAX_TEAM_SIZE).
This PR thus reduces the events sent in parallel from M+N=unbounded at once to `N=MAX_CONV_SIZE - 1` and `M=128` during team deletion, irrespective of team size.
Note that these constraints apply only to team deletions, not other events.
Also adds a delay when processing user deletions.
> throttle galley->gundeck on team deletion

- services/spar/src/Spar/App.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
This should make us more robust against partial failures, especially after we implement `PATCH` for SCIM.
I have no idea how to test this properly as we don't seem to have a good story in our test framework for testing components that fail on purpose.  I would love us to be able to programmatically call into other components, instead of having them as fixed processes. This would allow us to write an intricate test for this. Alternative ideas are welcome; as we probably don't have time to refactor our test suite to allow this :P (Though we should definitely discuss this at some time in the future).
> SCIM fixes Phase 0: User creation in correct order

- services/nginz/Makefile
- services/spar/Makefile
Follow up from https://github.com/wireapp/wire-server/commit/132c700c06baff8bebd725640b99494f35dddc6d
> Fix Makefiles to use the correct dist folder

- services/brig/test/integration/API/Provider.hs
- services/galley/src/Galley/API/Create.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/test/integration/API/Teams.hs
Currently, `team.conversation-create` and `team.conversation-delete` events are sent to _all_ team members that are _not_ part of the conversation.
While this may theoretically be useful for conversation discovery in case of teams (e.g., you may be interested in joining these conversations) there's currently no UI nor a use case for it so we're better off avoiding unnecessary fan outs. In case this does become relevant again, one could simply undo (redo?) this PR.
> Remove unnecessary fanout team events

- services/brig/test/integration/API/User/Property.hs
Seems to have been accidentally broken in #867 / 870b10b80a3dceaae07da21bbed29fc1d025f627 .
Log:
Brig API Integration
user
property
put /properties/:key - 403:                                FAIL
1: 403 =/= 200
2: Just "property-key-too-large" =/= Nothing
> brig: fix integration tests after #867

- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/Data.hs
- services/galley/test/integration/API.hs
This _actually_ fixes https://github.com/wireapp/wire-server/pull/924 - the fact that tests did not break before is a sign that nothing got changed.
Background: previously it was assumed that the user _adding_ others to a conversation was a `wire_admin` - this is not always true: when adding to a conversation, a user adds itself. Also, it's conceivable that in the future there will be more roles able to add users to conversations so this PR also takes that into account making this more forwards compatible.
> The adding member is not always an admin

- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/API/Util.hs
- services/galley/test/integration/API/Teams.hs
This is actually an existing bug with the current permission check that surfaced with the latest conversation role PR. The _actual_ logic should be:
```
-- users can add other users to a conversation iff:
--    - *the adding user is connected to the users being added*
--    OR
--    - *the adding user is part of the team of the users being added*
```
> Fixed logic with connection checks

- Makefile
This was a red herring when I was trying to understand migration
automation, and @jschaul says it is outdated, not used anymore and can
be deleted.
> Makefile: remove unused docker-migrations target

- services/spar/src/Spar/Intra/Brig.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
- services/spar/test-integration/Util/Core.hs
- services/spar/test-integration/Util/Scim.hs
- stack.yaml
- For now; only brig users that are SSO users. to be sure.
> SCIM Fixes Phase 1 + 2

- services/brig/brig.integration.yaml
- services/brig/src/Brig/API.hs
- services/brig/src/Brig/API/Util.hs
- services/brig/src/Brig/Data/User.hs
- services/brig/src/Brig/Options.hs
- services/brig/src/Brig/User/API/Search.hs
- services/brig/test/integration/API/Search.hs
- services/brig/test/integration/API/Search/Util.hs
- services/brig/test/integration/API/Team.hs
- services/brig/test/integration/API/User.hs
- services/brig/test/integration/API/User/Account.hs
- services/brig/test/integration/API/User/Auth.hs
- services/brig/test/integration/API/User/Client.hs
- services/brig/test/integration/API/User/Connection.hs
- services/brig/test/integration/API/User/Handles.hs
- services/brig/test/integration/API/User/Onboarding.hs
- services/brig/test/integration/API/User/PasswordReset.hs
- services/brig/test/integration/API/User/Property.hs
- services/brig/test/integration/API/User/RichInfo.hs
- services/brig/test/integration/Main.hs
- services/brig/test/integration/Util.hs
This solves the problem for on premise deployments where it is not desirable have team members connecting outside their team
> Handle search within team

- services/spar/src/Spar/API.hs
- services/spar/src/Spar/Data.hs
- services/spar/src/Spar/Error.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
Fixes https://github.com/zinfra/backend-issues/issues/754
> Refuse to delete non-empty IdPs (412 precondition failed)

- libs/brig-types/src/Brig/Types/Common.hs
- libs/brig-types/src/Brig/Types/Test/Arbitrary.hs
This fits more globally into making users unique and searchable in an enterprise world. 64 characters should be enough for most use cases; I did _not_ run any integration tests, so I will let the CI do that job.
Adding extra `-` and `.` was done so that it supports, more directly, conversions of emails to handles. `@` and `+` should _NOT_ be used so that "phone numbers", "emails", and "handles" remain disjoint sets.
> Allow up to 256 characters as handle, dots and dashes too

- deploy/services-demo/conf/brig.demo.yaml
- deploy/services-demo/conf/galley.demo.yaml
With the current config files, brig and galley refused to start with errors like
```
brig: user error (AesonException "Error in $.zauth.authSettings: key \"legalHoldAccessTokenTimeout\" not present")
```
Not sure if the given values are the right ones for the demo, though. Is there something we should change?
> Add missing options to services-demo config files

- services/spar/test-integration/Test/Spar/APISpec.hs
- services/spar/test-integration/Util/Core.hs
Just realized that supplying the Z-User header was unnecessary at best and confusing at worst.
> spar/integration: no auth required for /sso/settings

- services/brig/src/Brig/API.hs
- services/brig/src/Brig/Provider/API.hs
- services/brig/src/Brig/TURN/API.hs
- services/brig/src/Brig/Team/API.hs
- services/brig/src/Brig/User/API/Auth.hs
- services/brig/src/Brig/User/API/Search.hs
- services/brig/src/Brig/User/Auth/Cookie.hs
API handlers carry very little type information, which makes the code hard to read.
- split up every handler function into a wrapper that takes care of json parsing and rendering, and a core that contains the app logic.
- the core takes and returns a typed values.
- the core is in the `AppIO` monad wherever feasible, and the wrapper is in `Handler` (as before).
- the core carries the name of the original, un-split function; the wrapper has a `H` appended to the original name.
This change is easy to do on only parts of the code base, will make the code more readable in the short run, and is hard to get wrong (errors should all be caught by the compiler immediately).
It is helpful for the transition to servant, since the core functions are closer (and ideally identical) to the handler …
> Refactor: separate http parsing / generation from app logic.

- libs/wai-utilities/src/Network/Wai/Utilities/Server.hs
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/App.hs
- services/spar/src/Spar/Error.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
- stack.yaml
We need to collect more information from `/sso/finalize-login` for cases where customers complain about errors.  Currently, customers can only show us a json blob containing some info about the error, but not the original request, which would be required for reproducing it.
Depends on https://github.com/wireapp/saml2-web-sso/pull/57
Couple things to decide:
1. we could not log this with level `Info`, but make the json blob that customers get really big.  gives us the information in cases where customers are able to cut&paste, but logs will have less potentially sensitive data.
2.  we could add an end-point to spar for whitelisting teams that we log.
3.  we could just log the data and decide it's not sensitive.  (it is only logged in case of real errors, not "login rejected".)
answer: 1.
> debug spar prod

- build/alpine/Dockerfile.builder
This is very close to irrelevant, but before anybody runs into this and needs to spend a day waiting for the fix, we should just add it now.
> Make ormolu available in builder

- services/nginz/Dockerfile
- services/nginz/Makefile
This fixes the error seen on our kubernetes deployments:
```
Starting nginx
Setting up watches for /etc/wire/nginz/upstreams
nginx PID: 9
Setting up watches.
Watches established.
2020/02/19 08:22:55 [emerg] 10#0: mkdir() "/var/cache/nginx/client_temp" failed (2: No such file or directory)
nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (2: No such file or directory)
```
> fix nginx permissions in docker image

- libs/brig-types/package.yaml
- libs/brig-types/src/Brig/Types/Common.hs
- libs/brig-types/src/Brig/Types/Instances.hs
- libs/brig-types/src/Brig/Types/Provider/Tag.hs
- libs/brig-types/src/Brig/Types/Test/Arbitrary.hs
- libs/galley-types/package.yaml
- libs/galley-types/src/Galley/Types.hs
- libs/galley-types/src/Galley/Types/Bot/Service/Internal.hs
- libs/galley-types/src/Galley/Types/Conversations/Roles.hs
- libs/galley-types/src/Galley/Types/Teams.hs
- libs/types-common/package.yaml
- libs/types-common/src/Data/Code.hs
- libs/types-common/src/Data/Id.hs
- libs/types-common/src/Data/Json/Util.hs
- libs/types-common/src/Data/LegalHold.hs
- libs/types-common/src/Data/List1.hs
- libs/types-common/src/Data/Misc.hs
- libs/types-common/src/Data/Range.hs
- libs/types-common/src/Data/Text/Ascii.hs
- services/galley/src/Galley/API/Error.hs
- stack.yaml
see commit messages for details.
> Eliminate more CPP

- .gitignore
If someone tries to build the project with cabal (either on accident or because they're cool) it will leave these folders around and they might be accidentally commited
> Ignore dist-newstyle

- .gitignore
- nix/overlays/wire-server.nix
Before, for building libzauth we were only considering the .gitignore
in the ./lib/libzauth directory, (ignoring the toplevel one) which
didn't contain a Cargo.lock ignore (and shouldn't! lockfiles should be
comitted so builds are reproducible!).  Then we deleted the local
gitignore
which tripped up the nix build as the gitignore didn't exist anymore.
We now use the toplevel .gitignore, but remove the global Cargo.lock
ignore as Cargo.lock's are important to be comitted (and were already!).
For some reason we do not have a Cargo.lock for ./libs/libzauth/libzauth
but only ./libs/libzauth/libzauth-c so I kept it like that.  libzauth-c
is the thing we directly build, and then pulls in libzauth as a
dependency, so  locking at just libzauth-c is sufficient and is also the
lockfile we had in …
> Fix .gitignore shenanigans in Nix

- snapshots/README.md
- snapshots/wire-3.0.yaml
- stack.yaml
This does not change any dependencies from 2.2.
I broke 2.* a while ago by editing the files, and thus learned
that even editing typos in comments is a bad idea.  the easiest
way out is to abandon the old snapshot and clone it into a new
one with the same content.
> stack snapshot 3.0.

- tools/ormolu.sh
By using `yq` we don't rely on formatting and ordering of the `package.yaml` and `package-default.yaml` files anymore.
I needed these changes to [make the script work in `saml-web-sso`](https://github.com/wireapp/saml2-web-sso/pull/59), now I'm just backporting them.
> ormolu.sh: make queries for options more robust

- services/brig/src/Brig/API/Util.hs
- services/galley/src/Galley/API/Create.hs
- services/galley/src/Galley/API/Query.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/API/Util.hs
This saves us some unnecessary ID resolution lookups.
Probably easiest to review each commit individually.
> federation: resolve opaque IDs at the edges of galley

- services/galley/src/Galley/API.hs
This way you know which routes are handled in which modules.
Next step is to regroup handlers by resource type instead of by
modification type.
> Qualify all API imports in Galley

- libs/types-common/src/Data/UUID/Tagged.hs
- services/galley/src/Galley/Data.hs
It's not being used and doesn't seem to have any of the desirable
properties (being the inverse of addv4)
I'm also not sure if addv4 is functionally correct, as addition is not a
local operation like bitwise XOR. There might be some bias in how we
allocate conversation ids due to the fact that we add the numbers
together before bitwise-AND'ing in the version and variant. This is all a
bit naughty but we can't change it retroactively I think.
λ> quickCheck $ \x y -> subv4 (addv4 x y) x === y
*** Failed! Falsified (after 26 tests):
UUID 0000035e-0000-47d5-8000-0a7e00000d9b
UUID 00000b1c-0000-4d8f-8000-04f600000565
UUID 00000b1c-ffff-4d8f-8000-04f600000565 /= UUID 00000b1c-0000-4d8f-8000-04f600000565
λ> quickCheck $ \x y -> subv4 (addv4 y x) y === x
*** Failed! Falsified (after 26 tests): …
> Remove subv4

- stack.yaml
- stack.yaml.lock
Depends on https://github.com/wireapp/hscim/pull/44
I was wondering if bumping would work without too many changes; and it seems it did :)
> Bump to lts-14.27

- libs/brig-types/src/Brig/Types/Swagger.hs
- libs/brig-types/src/Brig/Types/Team/Invitation.hs
- libs/brig-types/src/Brig/Types/Test/Arbitrary.hs
- services/brig/brig.cabal
- services/brig/schema/src/Main.hs
- services/brig/schema/src/V59.hs
- services/brig/src/Brig/API/Error.hs
- services/brig/src/Brig/Team/API.hs
- services/brig/src/Brig/Team/DB.hs
- services/brig/test/integration/API/Team.hs
- services/brig/test/integration/API/Team/Util.hs
There are certain on-boarding flows where the inviter wants to provide more information about the invitee, particularly information about the invitee's name and phone number.
These values can be picked up during the registration process and clients (web) can pull that extra information from the invitation and add it to the `/register` call.
The new integration test shows how this can be used by our webapp in order to enhance the invitation process.
> Extended team invitations

- services/brig/brig.cabal
- services/brig/package.yaml
Changes in #964 were causing brig-schema to depend on cryptobox, libsodium, etc, which failed the build in staging. This PR reverts that.
> Minimize dependencies of all brig binaries

- services/brig/src/Brig/API/Error.hs
- services/galley/src/Galley/API/Error.hs
1) For consistency of other "not implemented uses" (e.g. in
services/galley/src/Galley/API/Error.hs:178)
2) To avoid 5xx metrics/logs and unactionable alarms to go off by accident.
It's known that 501 would be the semantically correct code to use. This
change is a pragmatic one in our deployment context.
> Use status 403 for 'not implemented'

- services/brig/src/Brig/Options.hs
especially for the folders feature: https://wire.com/en/blog/folders-feature/
These precise numbers were introduced also here:
https://github.com/wireapp/wire-server-deploy/pull/173
> Better defaults

- libs/api-bot/src/Network/Wire/Bot/Cache.hs
- libs/api-bot/src/Network/Wire/Bot/Monad.hs
- libs/brig-types/src/Brig/Types/Swagger.hs
- libs/brig-types/src/Brig/Types/Test/Arbitrary.hs
- libs/brig-types/src/Brig/Types/User.hs
- services/brig/src/Brig/API.hs
- services/brig/src/Brig/API/Client.hs
- services/brig/src/Brig/API/Types.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/Data/User.hs
- services/brig/src/Brig/IO/Journal.hs
- services/brig/src/Brig/Provider/API.hs
- services/brig/test/integration/API/Search.hs
- services/brig/test/integration/API/Team.hs
- services/brig/test/integration/API/User/Account.hs
- services/brig/test/integration/Util/AWS.hs
- services/spar/src/Spar/Intra/Brig.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Util/Scim.hs
To avoid current and future confusions with the variable `userName`, this renames all (of brig's) usages to `userDisplayName`. To keep backwards compatibility, json instances have not been touched.
Spar still uses `userName` (for a different meaning than what brig used it for), which can stay as is.
> Rename brig's userName to userDisplayName to avoid confusion

- libs/galley-types/src/Galley/Types.hs
- services/brig/src/Brig/API.hs
- services/brig/src/Brig/API/Client.hs
- services/brig/src/Brig/API/Connection.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/API/Util.hs
- services/brig/src/Brig/User/API/Search.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Query.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/API/Util.hs
- services/galley/src/Galley/Data.hs
There's also a small change where in two endpoints the `Z-User` header was marked as opaque user ID.
> Federation: Link related issue IDs

- libs/galley-types/src/Galley/Types/Teams.hs
- services/brig/src/Brig/API.hs
- services/brig/src/Brig/API/Error.hs
- services/brig/src/Brig/API/Types.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/IO/Intra.hs
- services/brig/src/Brig/Team/Util.hs
- services/brig/test/integration/API/Team.hs
- services/brig/test/integration/API/Team/Util.hs
- services/brig/test/unit/Test/Brig/User/Search/Index/Types.hs
- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/API/Util.hs
- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Intra/User.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/SQS.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Util.hs
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/Intra/Brig.hs
- services/spar/src/Spar/Intra/Galley.hs
- tools/stern/src/Stern/API.hs
- tools/stern/src/Stern/Intra.hs
https://github.com/zinfra/backend-issues/issues/1237
> Make delete or downgrade team owners scale

- stack.yaml
- stack.yaml.lock
Fixes https://github.com/zinfra/backend-issues/issues/1299
Branch on bloodhound fork: https://github.com/wireapp/bloodhound/tree/feature/count-with-ES-5.2
I don't plan on sending a PR for this as ES 5.2 is very old and we should just upgrade from it. There is already an issue for that: https://github.com/zinfra/backend-issues/issues/1161
> Use fork of bloodhound to support ES 5.2

- libs/galley-types/src/Galley/Types/Teams/Swagger.hs
- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Util.hs
see https://github.com/zinfra/backend-issues/issues/1197
> List team members by UserId

- services/galley/test/integration/API/CustomBackend.hs
They get normalized to lowercase during parsing.
> Test that custom backend domains are case-insensitive

- libs/galley-types/src/Galley/Types/Swagger.hs
- libs/galley-types/src/Galley/Types/Teams/Swagger.hs
- services/galley/src/Galley/API.hs
Fixes https://github.com/zinfra/backend-issues/issues/1304
> Move swagger model to a better place; index it.

- services/brig/src/Brig/User/Search/Index.hs
Fixes https://github.com/zinfra/backend-issues/issues/1308
This is required to go to production before we can push changes from #1046, hence the hotfix.
> HotFix: Tolerate nulls in DB while re-creating ES index

- deploy/services-demo/demo.sh
The script failed for me when trying to run the services demo.
After checking out this repository, the directory `deploy/services-demo/resource/zauth` doesn't exist.
Because of that, demo.sh failed writing the public and private keys to `resource/zauth/{pub,priv}keys.txt`.
> Small fix for services-demo/demo.sh: mkdir zauth

- services/galley/galley.cabal
- services/galley/package.yaml
- services/galley/src/Galley/App.hs
- services/galley/src/Galley/Run.hs
This wraps the existing galley `Application` into a Servant API.
Extracted from #1015, as I wanted people to be able to review and discuss it separately.
> Host galley endpoints via Servant.Raw

- services/spar/src/Spar/API.hs
- services/spar/src/Spar/API/Types.hs
- services/spar/src/Spar/Data.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
- services/spar/test-integration/Util/Core.hs
https://github.com/zinfra/backend-issues/issues/1295
~~This is based on https://github.com/wireapp/wire-server/pull/1065, I can rebase this when that is merged.~~
> delete non-empty IdPs

- deploy/dockerephemeral/run.sh
This will ensure brig-index is up to date before running the tests.
> Pull brig-index before running the docker ephemeral setup

- Makefile
This allows you to build docker images locally again.
It is still super slow; which gets annoying quickly.
Perhaps we can improve this by bind-mounting `.stack-work` into the container. This should be safe
if `stack.yaml` has `docker.enable: true`  we could set `docker.image: alpine-prebuilder` on the `stack.yaml` for that
> Make make docker-intermediate command work again

- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Util.hs
- tools/stern/src/Stern/API.hs
- tools/stern/src/Stern/Intra.hs
Adds an internal endpoint allowing binding teams of 1 member to be unconditionally deleted.
Fixes: https://github.com/zinfra/backend-issues/issues/1387
> Allow team deletion on stern

- services/brig/brig.integration.yaml
- services/brig/src/Brig/AWS.hs
- services/brig/src/Brig/Options.hs
- services/brig/src/Brig/Queue.hs
- services/brig/src/Brig/Run.hs
- services/gundeck/gundeck.integration.yaml
- services/gundeck/src/Gundeck/Aws.hs
- services/gundeck/src/Gundeck/Options.hs
- services/gundeck/src/Gundeck/Run.hs
Relates to https://github.com/zinfra/backend-issues/issues/891
We currently poll SQS as fast as possible for three queues: two in brig and one in gundeck. For local development / integration tests, this creates a lot of unnecessary logs and high CPU usage for the fake-sqs container. On my machine, I get about 65 polling requests to fake SQS per second. This PR takes that down to 3 requests per second.
I'd like to 
* get a CI run though to see whether tests fail or not (whether any tests are time-critical when it comes to queing).
* get a review here to see whether the approach makes any sense: can we afford to be slower at querying SQS? I think we can, as neither the internal nor the email feedback or push notification feedback events need to be processed in the same split second. But I'd …
> don't poll from SQS as often

- tools/db/auto-whitelist/auto-whitelist.cabal
- tools/db/auto-whitelist/package.yaml
- tools/db/migrate-sso-feature-flag/migrate-sso-feature-flag.cabal
- tools/db/migrate-sso-feature-flag/package.yaml
- tools/db/service-backfill/package.yaml
- tools/db/service-backfill/service-backfill.cabal
It looks like we made a mistake in the past while moving from cabal to hpack.
> Fix licenses of db tools

- services/galley/src/Galley/App.hs
Fixes https://github.com/zinfra/backend-issues/issues/1296
This warning is false for users using indexedBillingTeamMembers.
> Don't warn about team size when indexedBillingTeamMembers is true

- services/brig/brig.integration.yaml
> Set brig's logLevel to Warn while running integration-tests

- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Util.hs
No new functionality in the PR. Just more tests that I found useful to add when checking the logic behind `report_missing` and how all that works
> More tests for OTR messages using protobuf

- deploy/services-demo/conf/brig.demo-docker.yaml
- deploy/services-demo/conf/brig.demo.yaml
- deploy/services-demo/conf/nginz/nginx.conf
- services/brig/brig.integration.yaml
- services/brig/src/Brig/Options.hs
- services/brig/src/Brig/Provider/API.hs
- services/brig/src/Brig/User/Auth/Cookie.hs
- services/brig/test/integration/API/User/Auth.hs
- services/brig/test/integration/Util.hs
- services/galley/src/Galley/API/LegalHold.hs
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/Options.hs
- services/spar/src/Spar/Types.hs
This makes UAs default to server host (plus sub-domains).
Fixes https://github.com/zinfra/backend-issues/issues/953
> Leave domain empty in cookies.

- services/spar/test-integration/Test/Spar/APISpec.hs
- services/spar/test-integration/Test/Spar/AppSpec.hs
- services/spar/test-integration/Util/Core.hs
- stack.yaml
- stack.yaml.lock
Depends on https://github.com/wireapp/saml2-web-sso/pull/63
> Spar tests cleanup

- libs/types-common/src/Data/Misc.hs
- libs/types-common/src/Data/Range.hs
- libs/wire-api/package.yaml
- libs/wire-api/src/Wire/API/Arbitrary.hs
- libs/wire-api/src/Wire/API/User/Identity.hs
- libs/wire-api/test/unit/Test/Wire/API/Call/TURN.hs
- libs/wire-api/test/unit/Test/Wire/API/Roundtrip.hs
- libs/wire-api/wire-api.cabal
- stack.yaml
- stack.yaml.lock
~This builds on top of #1098, so I'll have to rebase once that is merged. The diff should be quite small then.~
The instance for shrink makes it much easier to find the reason for failing test cases, for example the roundtrip tests still marked as failing (see #https://github.com/zinfra/backend-issues/issues/1446). To write the generic instance, we need QuickCheck 2.14.
Another benefit with QuickCheck 2.14 is that many generators became significantly faster.
> wire-api: extend generic Arbitrary instances with implementation for 'shrink'

- services/brig/src/Brig/App.hs
- services/galley/src/Galley/Data.hs
Both of these were behind by 1, with migrations 59 and 41 respectively already existing.
> Fix: bump schemaVersion for Brig and Galley

- docs/reference/elastic-search.md
Fixes https://github.com/zinfra/backend-issues/issues/1286
From discussion with Tiago, we came to a conclusion that it may be easier for some customers to take some downtime and recreate the ES index instead of migrating to a new index while maintaining uptime. This PR adds documentation about how to recreate the index.
> Add documentation for recreating the ES index

- services/brig/test/integration/API/User/Auth.hs
- services/spar/test-integration/Util/Core.hs
- stack.yaml
- stack.yaml.lock
Still some issues. The bump breaks `hspec-wai` but I would've expect this break to show up as a version bound conflict. Is this stack being weird?
```
[nix-shell:~/Projects/wire/wire-server]$ stack build
warning: attempt to call something which is not a function but a set, at (string):1:2; will use bash from your environment
galley-0.83.0: unregistering (missing dependencies: zauth)
sodium-crypto-sign-0.1.2: unregistering (local file changes: /nix/store/c1zpndaxjvdzgygz8kzlbz3k53bmnh01-ghc-8.6.5/lib/ghc-8.6.5/include/ghcversion.h /nix/sto...)
zauth-0.10.3: unregistering (missing dependencies: sodium-crypto-sign)
sodium-crypto-sign      > build (lib)
sodium-crypto-sign      > Preprocessing library for sodium-crypto-sign-0.1.2..
sodium-crypto-sign      > Building library for …
```
> Bump http-client

- tools/ormolu.sh
actually fail if ormolu version check fails.
> Fix ormolu script.

- deploy/services-demo/conf/brig.demo-docker.yaml
- deploy/services-demo/conf/galley.demo-docker.yaml
- deploy/services-demo/conf/galley.demo.yaml
- deploy/services-demo/conf/nginz/nginx-docker.conf
- deploy/services-demo/conf/proxy.demo-docker.yaml
- deploy/services-demo/docker-compose.yaml
The brig and galley containers didn't start due to missing configuration values, which I fixed now. I also aligned some other `-docker` files to the non-Docker version.
> Fix services-demo (Docker)

- libs/wire-api/src/Wire/API/Team/Feature.hs
- libs/wire-api/test/unit/Test/Wire/API/Roundtrip/Aeson.hs
- libs/wire-api/test/unit/Test/Wire/API/Roundtrip/ByteString.hs
- services/brig/src/Brig/User/Auth.hs
- services/brig/test/integration/API/Search.hs
- services/brig/test/integration/API/Team/Util.hs
- services/brig/test/integration/API/User/Auth.hs
- services/brig/test/integration/API/User/Handles.hs
- services/galley/src/Galley/API/Swagger.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/Data/Instances.hs
- services/galley/src/Galley/Data/TeamFeatures.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Teams/Feature.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
- services/galley/test/integration/API/Util/TeamFeature.hs
- services/spar/src/Spar/Intra/Galley.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
- services/spar/test-integration/Util/Core.hs
- tools/db/migrate-sso-feature-flag/src/Work.hs
- tools/stern/src/Stern/API.hs
- tools/stern/src/Stern/Intra.hs
- tools/stern/src/Stern/Swagger.hs
See https://github.com/zinfra/backend-issues/issues/1529
> Fix setting team feature status in Stern/backoffice

- libs/wire-api/src/Wire/API/Swagger.hs
- libs/wire-api/src/Wire/API/User/Client.hs
They led to errors (and displaying `undefined`) in `swagger-ui`.
Now there are still 3 cases left where it shows `undefined` instead of the model, but it seems to be a problem with using returning an array of references (`Doc.returns (Doc.array (Doc.ref Public.modelFoo))`). The models are all there.
> add missing Swagger models

- deploy/dockerephemeral/docker-compose.yaml
cassandra didn't start up any more, and I added this to the `docker-compose.yaml` during debugging.
it turned out that i should have read the logs better, because there was also a database inconsistency that could only be removed by `docker-compose kill`, not by shutting down and restarting.  so these changes may not be entirely necessary for this to work on nixos, but they remove some warnings.
> Tweak cassandra container settings to get it to work on nixos.

- docs/reference/cassandra-schema.cql
- libs/galley-types/galley-types.cabal
- libs/galley-types/src/Galley/Types/IdMapping.hs
- libs/galley-types/test/unit/Test/Galley/Types.hs
- libs/types-common/src/Data/IdMapping.hs
- services/brig/src/Brig/API/Client.hs
- services/brig/src/Brig/API/Connection.hs
- services/brig/src/Brig/API/Error.hs
- services/galley/galley.cabal
- services/galley/schema/src/Main.hs
- services/galley/schema/src/V45_AddFederationIdMapping.hs
- services/galley/schema/src/V45_AddFederationUUIDMapping.hs
- services/galley/src/Galley/API/Create.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/IdMapping.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Mapping.hs
- services/galley/src/Galley/API/Query.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/API/Util.hs
- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Data/IdMapping.hs
- services/galley/src/Galley/Data/Queries.hs
- services/galley/src/Galley/Intra/IdMapping.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/IdMapping.hs
Related to https://github.com/zinfra/backend-issues/issues/1178
> Federation: Implement ID mapping (galley)

- libs/brig-types/src/Brig/Types/Intra.hs
- services/brig/src/Brig/API/Internal.hs
- services/brig/src/Brig/API/User.hs
- services/spar/src/Spar/Intra/Brig.hs
- services/spar/src/Spar/Scim/Types.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
When the active flag is false, suspend the user
Fixes https://github.com/zinfra/backend-issues/issues/1471
TODOs that I couldn't get done:
> Implement active flag in SCIM

- build/alpine/Dockerfile.prebuilder
- docs/developer/dependencies.md
See https://github.com/zinfra/backend-issues/issues/1466
It seems like this is the only place we need to change for CI. If it turns out that it isn't, I'll fix it and document it for next time. After merging, we need to trigger the `alpine-prebuilder` job.
I also updated the installation instructions for Stack, with two related question I'll add as comments.
> Upgrade stack to 2.3.1

- services/spar/src/Spar/Scim/Types.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/src/Spar/Types.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
- services/spar/test-integration/Util/Scim.hs
This PR contains some cleanup work that should lead to fixing https://github.com/zinfra/backend-issues/issues/1006 in another PR.
> SCIM Cleanup

- deploy/services-demo/conf/nginz/nginx-docker.conf
- deploy/services-demo/conf/nginz/nginx.conf
- docs/reference/cassandra-schema.cql
- docs/reference/user/registration.md
- services/brig/brig.cabal
- services/brig/schema/src/Main.hs
- services/brig/schema/src/V61_team_invitation_email.hs
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Team/API.hs
- services/brig/src/Brig/Team/DB.hs
- services/brig/test/integration/API/Team.hs
- services/brig/test/integration/Main.hs
Context: https://github.com/zinfra/backend-issues/issues/1489
> Pending invitations by email lookup

- libs/federation-util/src/Network/Federation/Util/DNS.hs
- libs/federation-util/src/Network/Federation/Util/Internal.hs
- libs/federation-util/test/Test/DNSSpec.hs
I started with the interface of `srvLookup` to avoid dealing with tuples of primitive types in `federator`, but quickly continued refactoring the actual logic itself after seeing bit tuples of `Word16` and things like `(\(priority', weight', port', domain', _) -> (priority', weight', port', domain'))` and `srvResult''''`.
Probably easiest to convince oneself of the correctness by looking at the commits individually.
> Refactor: Simplify SRV lookup logic in federation-util

- tools/ormolu.sh
When an expression evaluates to 0, its exit code is set to 1. Life is always
interesting when you write bash.
More information:
https://unix.stackexchange.com/questions/32250/why-does-a-0-let-a-return-exit-code-1/32251
> Use ++FAILURES as it will not evaluate to 0

- docs/reference/user/registration.md
- services/brig/src/Brig/API/User.hs
- services/brig/test/integration/API/User/Account.hs
Follow up to https://github.com/wireapp/wire-server/pull/1161 where the team creation case was missed.
Fixes: https://github.com/zinfra/backend-issues/issues/1602
> Disallow team creation when setRestrictUserCreation is true

- tools/rebase-onto-formatter.sh
Related to https://github.com/zinfra/backend-issues/issues/1623.
Upgrading Ormolu can be painful, because the style will often change in a lot of places (see for example #1145). Any active branches/PRs will then have to rebase onto these changes and resolve the resulting conflicts. It becomes a bit less cumbersome after first squashing all commits of the branch into a single one, but that's often not desirable.
This script will automate the rebasing process, keeping the (linear) history of intact and making the commits appear as if the changes had been applied onto the newly-formatted version all along.
For example, I rebased #1179 onto #1145, resulting in [this branch](https://github.com/wireapp/wire-server/compare/mheinzel/upgrade-ormolu-squashed...fisx/cleanup-rebased-onto-ormolu-0.1.2? …
> Add script to rebase branch onto formatting changes (like Ormolu upgrades)

- libs/cassandra-util/src/Cassandra/Exec.hs
- libs/imports/src/Imports.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/Index/Eval.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/Intra/Journal.hs
- services/galley/src/Galley/Intra/Push.hs
- services/galley/test/integration/API/Util.hs
- services/gundeck/src/Gundeck/Push.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
With Ormolu 0.1.2, we can now stop separating definitions in a where-clause by empty comments. This PR fixes all the places I found using `grep`.
It also fixes some comments that got broken when Ormolu was introduced.
> Some formatting cleanup

- libs/wire-api-federation/package.yaml
- libs/wire-api-federation/src/Wire/API/Federation/API.hs
- libs/wire-api-federation/src/Wire/API/Federation/API/Conversation.hs
- libs/wire-api-federation/test/Test/Wire/API/Federation/APISpec.hs
- libs/wire-api-federation/wire-api-federation.cabal
See https://github.com/zinfra/backend-issues/issues/1279.
Also part 2 of https://github.com/zinfra/backend-issues/issues/1213#issuecomment-659237907
Currently targetting part 1 of that until it is merged.
> Create first endpoint in Federation API

- docs/reference/user/registration.md
- libs/brig-types/src/Brig/Types/User.hs
- libs/wire-api/src/Wire/API/User.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/Data/User.hs
- services/brig/test/integration/API/User/Account.hs
Fixes https://github.com/zinfra/backend-issues/issues/1685
Long story short: the logic that checked whether a user was ephemeral was flawed, causing user creation to fail when it should succeed. This PR fixes that.
> Fixed logic related to ephemeral users

- libs/wire-api/src/Wire/API/Team/Invitation.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/API/Util.hs
- services/brig/src/Brig/Team/API.hs
- services/brig/src/Brig/Team/DB.hs
- services/brig/test/integration/API/Team.hs
- services/brig/test/integration/API/Team/Util.hs
- services/galley/test/integration/API/Util.hs
- services/spar/test-integration/Util/Core.hs
tl;dr:
- rename stuff that doesn't make sense and/or has no effects on behavior.
- move stuff to make upcoming PRs smaller.
slightly more details:
- drop irName, which carried the inviter name, but was never used.
- fix test suite where we used irName wrong, and then ignored it.
- give irEmail, irPhone, inIdentity, inPhone less ambiguous names.
- shuffle record fields.
- swagger.
- move around validateHandle and some other helpers.
> Refactor Invitations

- deploy/services-demo/conf/brig.demo-docker.yaml
- deploy/services-demo/conf/brig.demo.yaml
- deploy/services-demo/conf/nginz/nginx.conf
- services/brig/brig.integration.yaml
- services/brig/src/Brig/Options.hs
- services/brig/src/Brig/Provider/API.hs
- services/brig/src/Brig/User/API/Auth.hs
- services/brig/src/Brig/User/Auth.hs
- services/brig/src/Brig/User/Auth/Cookie.hs
- services/brig/test/integration/API/User/Auth.hs
- services/brig/test/integration/Util.hs
- services/galley/src/Galley/API/LegalHold.hs
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/Options.hs
- services/spar/src/Spar/Types.hs
Fixes https://github.com/zinfra/backend-issues/issues/953
#1076 breaks UX: clients attempting to get new tokens from `/access` with cookies they got before this change will receive an error, and will have to login again.
This PR does it right.
When multiple cookies are presented to the backend, _all of them_ will be tested against the database. If any of them is valid, then we pick the "first" one and use that for auth purposes.
> Leave domain empty in cookies, but account for clients with old cookies.

- services/cargohold/src/CargoHold/AWS.hs
- services/cargohold/src/CargoHold/S3.hs
This will help us debug some things we're seeing since #1157, such as https://github.com/zinfra/backend-issues/issues/1665 and https://github.com/wireapp/wire-server/issues/1203.
> Cargohold: Log more about AWS errors

- services/cargohold/Makefile
- services/cargohold/compat
- services/integration.sh
If testing against S3, minio, and others, this allows to run
```
make compat-minio
make compat-s3
...
```
Requires a `compat` folder (currently symlinked to a private repository containing some credentials)
> cargohold compat target for testing different S3-like buckets

- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
When a user has been invited to a team with SAML IdP via team settings, and then is searched via SCIM, the user won't be found and bound.  This is most likely because spar doesn't treat the email address that is the `externalId`  as an email, but as a SAML `NameID`.
This PR will fix this.
Fixes https://github.com/zinfra/backend-issues/issues/1572
> Manage invited user by SCIM when SSO is enabled

- deploy/dockerephemeral/docker-compose.yaml
As discussed with @fisx. Some integration tests were failing because of not enough memory.
> Double memory available to cassandra dockerephemeral

- docs/developer/dependencies.md
- nix/sources.json
- stack-deps.nix
proto-lens-protoc switched to ghc-source-gen, which requires libtinfo.
Don't know what the equivalent on macOS is and if it's even needed. Didn't find it with some googling.
Also not sure if the Nix dependency is the right one. Please tell me if it's not right.
> add libtinfo/ncurses to docs and nix deps

- services/gundeck/src/Gundeck/Push/Native.hs
Needed to debug native push notifications on staging.
This will make the logs contain user-identifying information, but not content.  I think we're already at that point, and anyway it's log level `DEBUG`, so I think this is fine.
> More debug logging for native push notifications.

- services/brig/src/Brig/PolyLog.hs
- services/spar/test-integration/Util/Email.hs
Just ran `make add-license` and this showed up.
> add missing license headers

- stack.yaml
- stack.yaml.lock
See https://github.com/zinfra/backend-issues/issues/1659
This pins [5d31aa49177e33ff1d6a00255f28e4ef3b711f7d](https://github.com/wireapp/amazonka/commit/5d31aa49177e33ff1d6a00255f28e4ef3b711f7d), which is now the most recent commit on `wireapp/amazonka` `develop`. If we want to merge this, I can also make a new release in our amazonka fork to make it clearer which version we're using (like [this one](https://github.com/wireapp/amazonka/releases/tag/wire-2019-01-25)).
> cargohold: pin newer amazonka with Content-Length patch

- services/brig/deb/opt/brig/bin/fetch.py
Relates to https://github.com/zinfra/backend-issues/issues/897
* also update license for consistency
> make fetch.py compatible with python 3

- services/brig/src/Brig/API/Error.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/Team/API.hs
we should be able to distinguish the handful of places where this error is raised [WIP]
> Better brig errors

- services/cargohold/src/CargoHold/App.hs
- services/cargohold/src/CargoHold/Options.hs
- stack.yaml
- stack.yaml.lock
See https://github.com/zinfra/backend-issues/issues/1659
Not the nicest way to do it and doesn't adhere to the S3 spec, but at least this way it's behind an optional setting.
> cargohold: add compatibility mode for Scality RING S3 implementation

- stack.yaml
- stack.yaml.lock
stack wants you to commit cabal files now, even if there is a package.yaml in version control.
> Fix stack warning about bloodhound.

- tools/bonanza/bonanza.cabal
- tools/bonanza/package.yaml
- tools/bonanza/src/Bonanza/App.hs
- tools/bonanza/src/Bonanza/Geo.hs
- tools/bonanza/src/Bonanza/Types.hs
Fixes https://github.com/zinfra/backend-issues/issues/1841
It uses the newer library that has support for the [V2 version of maxmind](https://www.maxmind.com/en/geoip2-city) which we want to use but bonanza had no support for ([brig](https://github.com/wireapp/wire-server/blob/develop/services/brig/src/Brig/App.hs#L98) was already using it).
How did I test this? I didn't add integration tests so I ran some manual tests (far from ideal I know). Previous, using this log line (mind the blurred out IP addresses):
```
2020-10-26T21:58:46.99997 10.10.10.10: 2020-10-26T21:58:32.61354 |srv=nginz_access|42.86.xxx.yy - - [26/Oct/2020:21:58:32 +0000] "POST /conversations/763d2bf2-0000-4576-ac01-54c98f426105/otr/messages HTTP/1.1" 201 87 "-" "some user agent" "42.86.xxx.yy" - 409954 0.092 0.092 - …
```
> Upgrade bonanza geoip2

- stack.yaml
- stack.yaml.lock
Fixes https://wearezeta.atlassian.net/browse/SQSERVICES-30
After this PR the spar config `saml.contacts` can be a empty list (was NonEmpty).
Related PR in saml2-web-sso: https://github.com/wireapp/saml2-web-sso/pull/68
> Update web-saml2-sso version: contact list may now be empty

- libs/wire-api/src/Wire/API/Asset/V3.hs
- services/cargohold/src/CargoHold/API/V3.hs
- services/cargohold/src/CargoHold/S3.hs
See https://github.com/zinfra/backend-issues/issues/1843.
This passes the cargohold compatibility tests with AWS, Scality RING and Minio.
> Remove Content-MD5 header for asset upload

- libs/wire-api/src/Wire/API/Asset/V3.hs
- services/cargohold/src/CargoHold/API/V3.hs
- services/cargohold/src/CargoHold/S3.hs
This reverts commit 66f69a0a88181a7daa6bfd2157ecd222fabc540e.
This change expected clients to stop sending the Content-MD5 header,
which breaks all the clients.
> Revert "remove Content-MD5 header for asset upload (#1247)"

- libs/wire-api/src/Wire/API/Asset/V3.hs
- services/cargohold/src/CargoHold/API/V3.hs
- services/cargohold/src/CargoHold/S3.hs
- services/cargohold/test/integration/API/V3.hs
See zinfra/backend-issues#1843.
To avoid undetected API breakage as in https://github.com/wireapp/wire-server/pull/1247, I added a testcase that uses a hardcoded multipart request as it is currently sent by clients. The test fails on #1247, but passes now.
Ideally we would not have our own multipart parser in the first place, but the change in `headers` was relatively straight-forward.
> Make Content-MD5 header optional for asset upload

- services/integration.sh
- services/spar/Makefile
- services/spar/test-scim-suite/Makefile
- services/spar/test-scim-suite/README.md
- services/spar/test-scim-suite/mk_collection.sh
- services/spar/test-scim-suite/run.sh
- services/spar/test-scim-suite/runsuite.sh
- services/spar/test-scim-suite/setup.js
- services/spar/test-scim-suite/shell.nix
- services/spar/test-scim-suite/update.jq
This PR adds script files that allow running the SCIM Test suite (https://github.com/zinfra/backend-issues/issues/1782), see the [README included](https://github.com/wireapp/wire-server/blob/scim-test-suite/services/spar/test-scim-suite/README.md) for details.
The scripts are run automatically before any other spar integration tests unless `INTEGRATION_SKIP_SCIM_SUITE=1`
> [skip ci] SCIM Test Suite

- libs/deriving-swagger2/src/Deriving/Swagger.hs
- libs/wire-api/test/unit/Test/Wire/API/Swagger.hs
Maybe it makes sense to add `headroom` to our CI pipeline? Should be straight-forward. Maybe `ormolu` + `headroom` = `haskell-stylecheck-ubuntu`?
> Add two missing license headers

- libs/galley-types/galley-types.cabal
- libs/galley-types/package.yaml
- services/galley/galley.cabal
Fixes broken and inconsitent cabal and package.yaml for galley-types introduced by https://github.com/wireapp/wire-server/pull/1256
> Fix .cabal & package.yaml galley-types and galley

- services/brig/src/Brig/Calling/API.hs
- services/brig/src/Brig/Options.hs
- services/brig/test/integration/API/Calling.hs
When SFT is deployed behind a load-balancer we can get away with a
single static entry. We need this for our Kubernetes-based SFT
deployment.
> brig: Allow setting a static SFT Server  (rebased  on develop)

- libs/galley-types/src/Galley/Types/Teams.hs
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/Error.hs
- services/spar/src/Spar/Intra/Galley.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
Fixes https://github.com/zinfra/backend-issues/issues/931
> IdP permissions

- deploy/services-demo/conf/nginz/nginx.conf
- docs/developer/dependencies.md
- services/brig/brig.cabal
- services/brig/package.yaml
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/Run.hs
- services/nginz/zwagger-ui/index.html
- stack-deps.nix
- stack.yaml
- stack.yaml.lock
Relates to https://wearezeta.atlassian.net/browse/SQCORE-232
This could be the first step towards deprecating usage of custom nginx-hosted zwagger-ui
See swagger json under http://localhost:8082/api/swagger.json
and a new and shiny UI under http://localhost:8082/api/swagger-ui
The same routes are also exposed through nginz.
We could keep the existing zwagger-ui as-is, but document new endpoints under a new URL going forward. In the long term, we could remove the old custom nginz-zwagger-ui.
> Integrate servant-swagger-ui to brig

- services/brig/src/Brig/User/API/Search.hs
- services/brig/src/Brig/User/Search/Index.hs
We decided that we'll keep using search in team-settings for now to get some overview of the team (in addition to a csv download button for getting an exhaustive member list).
I'm hoping this is not going to put too much load on ES in prod, but we can keep an eye on it during testing on staging.
> Increase the max allowed search results from 100 to 500.

- libs/api-bot/src/Network/Wire/Bot/Cache.hs
- libs/api-bot/src/Network/Wire/Bot/Monad.hs
- libs/api-bot/src/Network/Wire/Bot/Settings.hs
- libs/types-common/src/Data/Qualified.hs
- libs/wire-api/package.yaml
- libs/wire-api/src/Wire/API/Swagger.hs
- libs/wire-api/src/Wire/API/User.hs
- libs/wire-api/src/Wire/API/User/Identity.hs
- libs/wire-api/src/Wire/API/User/Profile.hs
- libs/wire-api/test/unit/Test/Wire/API/Swagger.hs
- libs/wire-api/wire-api.cabal
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/API/Util.hs
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Data/User.hs
- services/brig/src/Brig/Provider/API.hs
- services/brig/test/integration/API/User/Account.hs
- services/brig/test/integration/API/User/Handles.hs
- services/federator/federator.integration.yaml
* move /self endpoint to servant & swagger 2.0
* expose `qualified_id` field for `GET /self`:
```
"qualified_id": {
"id": "00000000-0000-0000-0000-000000000000",
"domain": "string"
}
```
> servantify /self endpoint

- libs/types-common/src/Data/Handle.hs
- libs/types-common/src/Data/Qualified.hs
- libs/wire-api/src/Wire/API/User.hs
- libs/wire-api/src/Wire/API/User/Handle.hs
- libs/wire-api/test/unit/Test/Wire/API/Swagger.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/test/integration/API/User/Handles.hs
Federation is not implemented yet, so remote handles will always return 404.
> Create endpoint for getting handle info by qualified handle

- libs/types-common/src/Data/IdMapping.hs
- libs/types-common/src/Data/Qualified.hs
- libs/wire-api/src/Wire/API/User.hs
- libs/wire-api/src/Wire/API/User/Handle.hs
- services/brig/src/Brig/API/Public.hs
* Typing underscores was getting annoying.
* _qDomain becomes qDomain.
* _qLocalPart becomes qUnqualified. The qualified thing may not be local, so
calling this local seems wrong.
* The `OptionallyQualified` type seems to be unused, I didn't delete it since I thought
it would be useful when we want to be backwards compatible in request body.
> Data.Qualified: Better field names

- libs/wire-api/package.yaml
- libs/wire-api/src/Wire/API/User.hs
- libs/wire-api/test/unit/Test/Wire/API/User.hs
- libs/wire-api/wire-api.cabal
While omitting a json field, or setting the field to null parses the
same for Haskell, that is not the case for other programming languages,
which can easily trip up over a change in behaviour.
The problem was accidentally introduced in #1281, resulting in null
values instead of omitting fields for unset values in UserProfile json, e.g.
```json
{
"deleted" : null,
"picture" : [],
"email" : null,
"accent_id" : 1,
"team" : null,
"handle" : "test1",
"expires_at" : null,
"locale" : "en-US",
"qualified_id" : {
"id" : "d93f2555-e4b7-4051-8d84-2bcf59ea6066",
"domain" : "staging.zinfra.io"
},
"service" : null,
"name" : "test",
"id" : "d93f2555-e4b7-4051-8d84-2bcf59ea6066",
"assets" : [
{
"type" : "image",
"size" : "preview",
"key" : "3-1-43978d07-040c-4f49-be7e-06e2560701fd"
},
{
"type" : …
```
> unit test and fix for null values in rendered JSON in UserProfile

- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/User/Handle.hs
- services/spar/src/Spar/Scim/User.hs
please review commit-by-commit, or with whitespace differences turned off, or both.
> Random nit-picks

- Makefile
- hack/bin/integration-teardown.sh
And minor drive-by fixes to bash/Makefile.
> Makefile: allow overriding NAMESPACE for kube-integration target

- .dockerignore
- tools/nginz_disco/Dockerfile
- tools/nginz_disco/Makefile
Other docker images get their build context from the top level, nginz_disco is inconsistently expecting a subdirectory (and trips up CI).
> nginz_disco: docker building consistency

- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/Data/User.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
This PR fixes the following bug:
1. SCIM creates an invitation with a user handle
2. The registers with the invitation. The registration function ignores the `handle` value from the invitation and thereby overwrites it with `null` in the users table. However the user and handle are still contained `user_handle` which leads to the issue described in https://wearezeta.atlassian.net/browse/SQSERVICES-158
This bug can be verified by an additional check in the integeration test for SCIM-invitations.
> Fix bug: handle lost after registration of scim-invited users

- stack.yaml
- tools/db/repair-handles/README.md
- tools/db/repair-handles/package.yaml
- tools/db/repair-handles/repair-handles.cabal
- tools/db/repair-handles/repair-handles/Main.hs
- tools/db/repair-handles/src/Options.hs
- tools/db/repair-handles/src/Types.hs
- tools/db/repair-handles/src/Work.hs
This PR adds a CLI tool `repair-handles` that can fix DB inconsistencies described in
https://wearezeta.atlassian.net/browse/SQSERVICES-158
See also https://github.com/wireapp/wire-server/pull/1303
> Add tools/db/repair-handles

- stack.yaml
these have been released on hackage two months ago.
> Cleanup stack.yaml.

- nix/sources.json
- shell.nix
This allows me to keep HLS built for different projects potentially using
different versions of nixpkgs (and so c libraries) separate.
> Upgrade nixpkgs and add HLS to shell.nix

- services/spar/src/Spar/Scim/User.hs
This PR adds error logging in spar. FUTUREWORK: use structured logs instead of strings.
> SCIM: Add error logging for CRUD operations with hashed context

- services/brig/brig.cabal
- services/brig/src/Brig/API/Error.hs
- services/brig/src/Brig/API/Internal.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/API/Types.hs
- services/brig/src/Brig/API/User.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
- services/spar/test-integration/Util/Core.hs
- services/spar/test-integration/Util/Email.hs
Implements https://wearezeta.atlassian.net/browse/SQSERVICES-171
> Forbid manual updates to email, handle, display for SCIM-managed users

- services/spar/src/Spar/Intra/Brig.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
This PR fixes this bug:
Deleting a user via SCIM when there is no IdP won't remove the entry from `spar.scim_external_ids`.
This might be a cause for issues such as [SQSERVICES-179](https://wearezeta.atlassian.net/browse/SQSERVICES-179)
The test `testDeletedUsersFreeExternalIdNoIdp` proves the bug and the fix.
The function `userToExternalId` was removed because its name is misleading. The only call site of this function is refactored.
> Fix bug: SCIM-Deleting a user retains the externalId

- charts/federator/.helmignore
- charts/federator/Chart.yaml
- charts/federator/templates/configmap.yaml
- charts/federator/templates/deployment.yaml
- charts/federator/templates/service.yaml
- charts/federator/values.yaml
- charts/wire-server/requirements.yaml
- charts/wire-server/values.yaml
- hack/bin/set-wire-server-image-version.sh
- hack/helm_vars/wire-server/values.yaml
- services/federator/src/Federator/API.hs
https://wearezeta.atlassian.net/browse/SQCORE-364
> Add helm chart for the federator

- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
This PR will update the behaviour of `GET /scim/v2/Users?filter=externalId eq "<x>"`. Without this PR if `<x>` is not en email the endpoint will return a `400`. With this PR it will return an empty result set.
For context: https://wearezeta.atlassian.net/browse/SQSERVICES-204
> Accept any query string for externalId

- services/brig/test/integration/API/Search.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
This PR should help with two sporadically fail on CI:
- https://wearezeta.atlassian.net/browse/SQSERVICES-189
- https://wearezeta.atlassian.net/browse/SQSERVICES-206
> Improve flaky integration tests

- libs/polysemy-wire-zoo/package.yaml
- libs/polysemy-wire-zoo/polysemy-wire-zoo.cabal
- libs/polysemy-wire-zoo/src/Polysemy/TinyLog.hs
- services/brig/brig.cabal
- services/brig/package.yaml
- services/brig/src/Brig/Calling.hs
- services/brig/test/unit/Test/Brig/Calling.hs
- stack.yaml
polysemy-wire-zoo is inspired by polysemy-zoo. We can use it to keep our pets
which we might need to interface with other libraries.
I named the constructor `Polylog` so `makeSem` will generate a function called `polylog`. Ideally I would have named it `Log` and the function would've been `log`, but that would collide with `Imports`.
> Extract and rename PolyLog to a library for reusability

- charts/nginz/values.yaml
Our internal staging environment had a few more internal QA routes in the `nginz` service missing from our helm charts.
> Add missing internal qa routes

- libs/dns-util/src/Wire/Network/DNS/Effect.hs
This will allow us to rely on caching built into the DNS library.
The function is unused right now, but this will help keep the federator work small.
> dns-util: Allow running lookup with a given resolver

- Makefile
- charts/brig/templates/tests/brig-integration.yaml
- docs/developer/dependencies.md
- hack/bin/integration-setup-federation.sh
- hack/bin/integration-setup.sh
- hack/helm_vars/wire-server/values.yaml
- services/brig/Makefile
- services/brig/federation-tests.sh
For easier review, this PR is a small piece from the now-long-running "federation" branch https://github.com/wireapp/wire-server/pull/1319 with the following purpose:
* introduces telepresence as a new development dependency (right now only for running end2end federation tests spanning multiple backends)
* prepares using brig as a place to keep some federation end2end tests spanning more than one backend, by using pattern matching on `brig-federation`: those tests will not run by default locally or on CI, until they are more stable and CI can actually run them.
* Makefile targets and bash scripts to spawn up two backends (one backend will have a namespace-suffix-by-convention)
* Each ephemeral backend will have a unique federationDomain (based on the kubernetes namespace), so that tests …
> Federation end2end test scripts and Makefile targets

- nix/overlays/wire-server.nix
- stack-deps.nix
cryptobox and zauth wouldn't build on OSX because the wrong path was included in the `dylib`.
The symptom was that the `cryptobox-c` haskell library build would fail with:
```
cryptobox-haskell                > running .stack-work/dist/x86_64-osx-nix/Cabal-3.0.1.0/build/System/CryptoBox_hsc_make failed (exit code -6)
cryptobox-haskell                > rsp file was: ".stack-work/dist/x86_64-osx-nix/Cabal-3.0.1.0/build/System/hsc2hscall42850-3.rsp"           
cryptobox-haskell                > output file:".stack-work/dist/x86_64-osx-nix/Cabal-3.0.1.0/build/System/CryptoBox.hs"                      
cryptobox-haskell                > command was: .stack-work/dist/x86_64-osx-nix/Cabal-3.0.1.0/build/System/CryptoBox_hsc_make  >.stack-work/dist/x86_64-osx-nix/Cabal-3.0.1.0/build/System/CryptoBo …
```
> Fix nix build on OSX

- charts/brig/templates/configmap.yaml
- charts/brig/templates/tests/configmap.yaml
- charts/federator/templates/configmap.yaml
- charts/federator/templates/deployment.yaml
- charts/federator/templates/service.yaml
- charts/federator/values.yaml
- hack/bin/integration-setup.sh
- services/brig/brig.cabal
- services/brig/brig.integration.yaml
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Options.hs
- services/brig/test/integration/API/Provider.hs
- services/brig/test/integration/Federation/User.hs
- services/brig/test/integration/Main.hs
- services/brig/test/integration/Util.hs
- services/integration.yaml
Brig integration/end2end initial test for federation
For easier review, this PR is a small piece from the now-long-running "federation" branch #1319 with the following purpose:
* refactor some brig-integration setup code (remove looking at environment
variables)
* brig now knows about federator's existence in the config file. This is
an optional field. (should it be required?)
* introduce a first test that needs two backends. This test is failing
on this branch (but working to success on #1319 currently), but will
be disabled-by-default to run both on CI and locally, as long as this PR
is merged *after* #1341
* prepare some federation chart config. Note there is currently a `federator` and `federatorInternal` config here: the former can be deleted as soon as some PRs involving the actual …
> Brig integration tests

- services/brig/Makefile
- services/brig/test/integration/Main.hs
Tasty doesn't allow multiple `-p` arguments.
That's why ` -p "!/brig-federation/"`  breaks any `-p` arguments in `WIRE_INTEGRATION_TEST_OPTIONS`.
This PR fixes this by guarding the federation test with an `INTEGRATION_FEDERATION_TESTS` env var.
> Brig integration tests: Replace federation guard with env var

- libs/wire-api/src/Wire/API/Arbitrary.hs
- libs/wire-api/src/Wire/API/UserMap.hs
- libs/wire-api/test/unit/Test/Wire/API/Swagger.hs
- services/brig/src/Brig/API/Public.hs
For WIre.API.UserMap:
The examples generated by swagger will not be nice, but it is very difficult to
get it right, unless we want to add explicit examples everywhere. Perhaps we can
use Arbitrary and some DerivingVia strategy to generate those. But for now, it
doesn't seem like it is worth it.
> Wire.API.UserMap & Brig.API.Public: Fix Swagger docs

- .gitignore
- Makefile
- docs/developer/dependencies.md
- hack/bin/buildah-clean.sh
- hack/bin/buildah-compile.sh
- hack/bin/buildah-inside.sh
- hack/bin/buildah-make-images.sh
- hack/bin/buildah-purge-untagged.sh
buildah-compile.sh compiles wire-server inside an alpine-based container based on quay.io/wire/alpine-builder.
the tool 'buildah' is used to mount some folders in, and to
keep the stack caches of .stack and .stack-work (renamed to avoid conflicts) for the next compilation. 
After compilation, ./buildah-make-images.sh can be used
to bake individual executables into their respective docker images used by kubernetes.
Usage: just run 'make buildah-docker' which will compile and upload
images to quay.io under the docker tag $USER by default.
On my machine, the overhead (from a successful `stack build` of wire-server to a set of ~15 docker images locally) is 1.5 minutes. Pushing to quay.io depends on your internet connection. Pushing to a local kubernetes cluster would be faster.
FUTUREWORK: …
> [skip ci] faster local docker image building using buildah

- libs/wire-api/src/Wire/API/Team/Role.hs
- libs/wire-api/src/Wire/API/User/Search.hs
- libs/wire-api/test/unit/Test/Wire/API/Roundtrip/Aeson.hs
- libs/wire-api/test/unit/Test/Wire/API/Roundtrip/ByteString.hs
- services/brig/brig.cabal
- services/brig/package.yaml
- services/brig/src/Brig/User/API/Search.hs
- services/brig/src/Brig/User/Search/Index.hs
- services/brig/src/Brig/User/Search/TeamUserSearch.hs
- services/brig/test/integration/API/Search/Util.hs
- services/brig/test/integration/API/TeamUserSearch.hs
Follow-up for #1286. This PR adds ordering of the search result by name, email, handle, samlIdp, managedBy to `/teams/:tid/search`.
This PR requires rebuilding the ES index. However this PR doesn't increase the migration version, since this PR is meant to be released together with #1286.
> Team search: add sorting

- shell.nix
This adds the upstream static 2.3.1 build of stack to shell.nix.
I tested on linux that HLS from within shell.nix generates the same .cabal files as stack 2.3.1.
> Add stack 2.3.1 to shell.nix

- libs/wire-api/src/Wire/API/Team/Size.hs
- libs/wire-api/wire-api.cabal
- services/brig/src/Brig/Team/API.hs
> Public end-point for getting the team size.

- libs/galley-types/src/Galley/Types/Teams.hs
- libs/types-common/src/Data/Json/Util.hs
- libs/types-common/test/Test/Properties.hs
- libs/wire-api/package.yaml
- libs/wire-api/src/Wire/API/Team/Export.hs
- libs/wire-api/src/Wire/API/Team/Role.hs
- libs/wire-api/test/unit/Main.hs
- libs/wire-api/test/unit/Test/Wire/API/Roundtrip/CSV.hs
- libs/wire-api/wire-api.cabal
- services/galley/galley.cabal
- services/galley/package.yaml
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/Intra/User.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Util.hs
This PR extends the existing `/teams/:tid/members` so that it if it is requested with `Accept: text/csv` it will respond with a csv file. For details see https://wearezeta.atlassian.net/browse/SQSERVICES-107
> Galley: Add /teams/:tid/members csv download

- charts/nginz/values.yaml
- deploy/services-demo/conf/nginz/nginx-docker.conf
- deploy/services-demo/conf/nginz/nginx.conf
- services/brig/src/Brig/Team/API.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/test/integration/API/Teams.hs
see https://github.com/wireapp/wire-server/pull/1351
I really didn't mean for this to get committed, apologies for my language.
This PR:
- removes some leftovers from #1351 
- adds routes + swagger docs + headers for csv endpoint  (#1351)
- adds routes for team size endpoint (#1295)
> Cleanup noise from #1351

- charts/elasticsearch-index/templates/create-index.yaml
- charts/elasticsearch-index/values.yaml
- docs/reference/elasticsearch-migration-2021-02-15.md
- services/brig/brig.cabal
- services/brig/src/Brig/Index/Eval.hs
- services/brig/src/Brig/Index/Options.hs
- services/brig/src/Brig/Index/Types.hs
- services/brig/src/Brig/User/Search/Index.hs
This PR updates the `elasticsearch-index` chart to simplify the the ES migration path introduced in #1360.
This PR adds an optional config flag `--delete-template TEMPLATE_NAME`  to `brig-index` that deletes an index template `TEMPLATE_NAME` before it creates any index. If `--delete-template` isn't set then the bahaviour of `brig-index` is unchanged.
> Simplify ES upgrade path

- charts/cannon/templates/statefulset.yaml
- charts/demo-smtp/values.yaml
- charts/reaper/templates/deployment.yaml
This is needed for the wire offline package; as it doesn't support untagged container images.
> charts: Use tagged container images and update kubectl contaienr image

- charts/sftd/README.md
- charts/sftd/templates/_helpers.tpl
- charts/sftd/templates/configmap-join-call.yaml
- charts/sftd/templates/deployment-join-call.yaml
- charts/sftd/templates/ingress.yaml
- charts/sftd/templates/service-join-call.yaml
- charts/sftd/templates/statefulset.yaml
- charts/sftd/values.yaml
- charts/wire-server/requirements.yaml
- hack/helm_vars/wire-server/values.yaml
* The ingress assigns an SFT allocation request to a random SFT
* Each sftd pod is made aware of an URL on which it is directly
reachable, and will return the URL in the response to the client.  e.g.
Pod `sftd-0` will be assigned `https://sft.example.com/sfts/sftd-0`
* The client tells this URL to other clients willing to join the call
* Other clients make a request to this URL
* The ingress points requests to `/sfts` to the `join-call` deployment,
which will redirect to the specific pod, such that the client can join
the conference call of the other client
>  sftd: add support for multiple SFT servers

- charts/federator/templates/configmap.yaml
- docs/reference/config-options.md
The current syntax uses 'with' which leads to end results like
optSettings:
setFederationStrategy:
allowedDomains:
- "[domain1.wire.link domain2.wire.link]"
which is not what we want. Range is the keyword to loop over a list.
Also: document federator allow list configuration
> charts/federator: fix allowList syntax

- Makefile
- charts/brig/templates/tests/brig-integration.yaml
- charts/brig/values.yaml
- charts/federator/templates/configmap.yaml
- hack/bin/integration-teardown-federation.sh
- hack/helm_vars/wire-server/values.yaml
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Federation/Client.hs
Keep old targets with suffix '-sans-federation' in case anyone needs them.
> Makefile: Default to setting up and testing federation in K8s

- charts/sftd/templates/statefulset.yaml
I somehow missed this. It's needed for the offline deliverable
Can I somehow get this into master without making a release though?
> Pin kubectl image in sftd chart

- stack.yaml
- tools/db/migrate-external-ids/Makefile
- tools/db/migrate-external-ids/README.md
- tools/db/migrate-external-ids/migrate-external-ids.cabal
- tools/db/migrate-external-ids/package.yaml
- tools/db/migrate-external-ids/src/Main.hs
- tools/db/migrate-external-ids/src/Options.hs
- tools/db/migrate-external-ids/src/Work.hs
This pr adds `tools/db/migrate-external-ids`
This tool fills entries in the table `spar.scim_external` (introduced in #1359 and rreleased [2021-02-16](https://github.com/wireapp/wire-server/releases/tag/v2021-02-16)) from table `spar.scim_external_ids` and `brig.user`. It is meant to be used in the migration from `spar.scim_external_ids` to `spar.scim_external`.
> Add migrate-external-ids tool

- services/spar/src/Spar/Scim.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-304
spar is transforming legitimate errors from eg. brig into 500 errors.  this PR fixes that.  the new scim errors in non-scim errors under scim end-points have the correct status and message and no type.  they also keep the scim error schema information.
i haven't managed to find the definition of what `Error20` or `"urn:ietf:params:scim:api:messages:2.0:Error"` says about the shape of the json object, and even if we find something scim peers may speak their own dialect violating the standard.
so there is a small risk now that instead of returning a 500 to a scim peer, they may get a much more reasonable error they still consider malformed.  i argue this is a clear improvement no matter what our scim peers think.  :)
> Spar errors

- services/spar/Makefile
- services/spar/migrate-data/src/Spar/DataMigration/Run.hs
This PR:
- Adds a first migration `V1_ExternalIds` (introduced in #1400) to the list of  migrations in `spar-migrate-data`
- Adds debian package for the `spar-migrate-data` executable (#1400)
> spar-migrate-data: Add migration and *.deb package

- charts/cassandra-migrations/templates/galley-migrate-data.yaml
- charts/cassandra-migrations/templates/spar-migrate-data.yaml
- charts/cassandra-migrations/values.yaml
This PR adds `spar-migrate-data.yaml` (similar to `galley-migrate-data.yaml` in the same directory) to the `cassandra-migrations` chart.
This should be released after https://github.com/wireapp/wire-server-private/pull/283
> Add spar-migrate-data to cassandara-migrations helm chart

- services/spar/schema/src/Main.hs
- services/spar/src/Spar/App.hs
- services/spar/src/Spar/Data.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
- services/spar/test-integration/Util/Core.hs
This PR discontinues use of `spar.scim_external_ids` table in favor of `spar.scim_externals` table.
:warning: Release this in a separate release after #1417 is released and only after the `spar-migrate-data` job has completed on production.
> Remove usage of spar.scim_external_ids table

- services/brig/brig.integration.yaml
- services/brig/src/Brig/AWS.hs
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Data/Client.hs
- services/brig/src/Brig/Options.hs
Implement https://wearezeta.atlassian.net/browse/SQPIT-348
TODO:
> Random prekeys strategy

- services/brig/src/Brig/API/Handler.hs
- services/brig/test/integration/API/User/Handles.hs
Previously all the servant endpoints were wrongly fabricating the phrase for
status and only putting the message in the body. So, some 404's would return
something like:
```
HTTP/1.1 404 handle-not-found
```
This is allowed in HTTP, but still is a breaking change to our API. So, I think
it should be reverted.
Apart from this we also broke our API by not writing the whole error object in
the body, fortunately nothing broke, but I am pretty sure something would have
broken if we touched the endpoints where clients try to parse the error labels
and messages.
> Brig: Return correct status phrase and body on error

- charts/webapp/templates/deployment.yaml
This will allow us to detect new webapps and deploy them immediately to some
environment without having to relying on `imagePullPolicy: Always`.
Using `imagePullPolicy: Always` supresses tranparency of what and when something
was deployed.
> Allow specifying digest of webapp

- services/integration.sh
I have nix, but I don't want to use the nix-compiled version of nginz, especially when making changes such as https://github.com/wireapp/wire-server/pull/1386 which change which modules we use.
Also, my experience has been that something in the nix derivatation changes every week or every other week, leading to a nginx recomilation side effect each time I wish to run an integration test (which is not the time this should run: it could be hooked into services/nginz's makefile if that is useful)
@fisx you can set `COMPILE_NGINX_USING_NIX=1` globally in your bashprofile if you'd like to use the previous behaviour.
> stop re-compiling nginz when running integration test for unrelated changes

- hack/bin/filter-old-releases.jq
- hack/bin/integration-cleanup.sh
For some reason the the bash expression to calculate time fails in CI and helm
now supports outputting json, so I swapped bash magic with jq magic. It more
robust, hopefully it is also more understandable.
> hack/bin/integration-cleanup.sh: Use jq magic instead of bash

- shell.nix
Running SCIM test-suite requires wget.
> shell.nix: Add wget

- Makefile
- hack/bin/upload-helm-charts-s3.sh
This PR changes `update-helm-charts-s3.sh `
- new option `-r <wire|wire-develop|wire-custom>` - this was derived from the branch beforehand
- new option `-d CHART_DIR` - this was a positional argument before
Tested: options parsing works.
Not tested: compatibility with uses of the script (CI, where else?)
Make sure to deploy https://github.com/wireapp/wire-server-private/pull/291 after this
> Update update-helm-charts-s3.sh arguments

- docs/developer/how-to.md
- libs/wire-api-federation/src/Wire/API/Federation/API/Brig.hs
- libs/wire-api/package.yaml
- libs/wire-api/src/Wire/API/User/Search.hs
- libs/wire-api/test/unit/Main.hs
- libs/wire-api/test/unit/Test/Wire/API/Swagger.hs
- libs/wire-api/test/unit/Test/Wire/API/User/Search.hs
- libs/wire-api/wire-api.cabal
- services/brig/brig.cabal
- services/brig/package.yaml
- services/brig/src/Brig/API/Federation.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/API/Util.hs
- services/brig/src/Brig/Federation/Client.hs
- services/brig/src/Brig/User/API/Handle.hs
- services/brig/src/Brig/User/API/Search.hs
- services/brig/src/Brig/User/Search/SearchIndex.hs
- services/brig/test/integration/API/Federation.hs
- services/brig/test/integration/API/Search.hs
- services/brig/test/integration/API/Search/Util.hs
- services/brig/test/integration/API/User/Account.hs
- services/brig/test/integration/API/User/Handles.hs
- services/brig/test/integration/Federation/End2end.hs
- services/brig/test/integration/Federation/User.hs
- services/brig/test/integration/Federation/Util.hs
- services/brig/test/integration/Main.hs
- services/brig/test/integration/Util.hs
Fixes https://wearezeta.atlassian.net/browse/SQCORE-563
Pending:
> brig: Add exact handle matches from all teams in /search/contacts

- .dockerignore
- services/nginz/Dockerfile
nginz docker image has been flaky recently, and it seems the `apk add` command doesn't actually run (it says 'OK' but doesn't acutally install these packages; and then the next invocations using curl and gpg fail):
```
#13 0.260 + apk add --no-cache --virtual .build-deps libsodium-dev llvm-libunwind-dev gcc libc-dev make openssl-dev pcre-dev zlib-dev linux-headers curl gnupg1 libxslt-dev gd-dev geoip-dev
#13 0.264 fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
#13 0.308 fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
#13 0.396 OK: 7 MiB in 20 packages
#13 0.408 + curl -fSL https://nginx.org/download/nginx-1.16.1.tar.gz -o nginx.tar.gz
```
This PR:
* adds `apk update` (which seems to render the thing less flaky) (or fix the …
> nginz: add apk installations to separate RUN task

- services/brig/src/Brig/User/API/Search.hs
- services/brig/src/Brig/User/Handle.hs
- services/brig/test/integration/API/Search.hs
This is requried because cassandra doesn't like querying with empty keys.
Ideally we should just not allow making the 'Handle' value if something isn't a
valid handle, a FUTUREWORK has been added for this.
> Search: Only perform exact handle match if term is a valid handle

- tools/ormolu.sh
* Reduce size of ormolu output when running in a terminal
* Make the ormolu script detect Ctrl-C more reliably
> Ormolu script improvements

- hack/bin/diff-failure.sh
This is useful when equality assertions fail on large objects.
> Add script to colourise test failure output [skip ci]

- hack/federation/grpcurlhandle.sh
- libs/wire-api-federation/proto/router.proto
- libs/wire-api-federation/src/Wire/API/Federation/Client.hs
- libs/wire-api-federation/src/Wire/API/Federation/GRPC/Types.hs
- services/brig/src/Brig/Federation/Client.hs
- services/federator/federator.cabal
- services/federator/src/Federator/Brig.hs
- services/federator/src/Federator/Discovery.hs
- services/federator/src/Federator/ExternalServer.hs
- services/federator/src/Federator/InternalServer.hs
- services/federator/src/Federator/Util.hs
- services/federator/src/Federator/Validation.hs
- services/federator/test/integration/Test/Federator/InwardSpec.hs
- services/federator/test/unit/Main.hs
- services/federator/test/unit/Test/Federator/ExternalServer.hs
- services/federator/test/unit/Test/Federator/InternalServer.hs
- services/federator/test/unit/Test/Federator/Validation.hs
To eventually support server-to-server authentication, the first step implemented in this PR is to add an originating domain to federated requests. At the moment this domain could be arbitrarily set (i.e. server2server authentication is not yet implemented here). But in this PR, some validation logic compares this domain to the allowList for incoming requests at federator level, if configured.
That domain can then in the future be used for:
* authenticating the domain with DNS/SRV or other means to validate that the request indeed comes from the claimed sender
* independent of authentication/authorization concerns, the domain may be required for any RPC calls that need to write data (e.g. to create a conversation).
In this PR, a field `originDomain` is added to the `Request` object in the …
> Add originDomain to federation API

- libs/wire-api/src/Wire/API/Team/Export.hs
- services/brig/src/Brig/API/Internal.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/Data/User.hs
- services/galley/galley.cabal
- services/galley/package.yaml
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/Intra/User.hs
This PR updates the CSV export returned on `/teams/:tid/members/csv` as follows
- in the header of CSV use underscore `_` instead of space in column names
- add 3 columns
- `saml_name_id` the SAML subjectects NameId
- `scim_external_id` SCIM `externalId` field
- `scim_rich_info` SCIM `richInfo` profile field (JSON-encoded)
- prevent duplicated unnecessary calls to /i/users
I tested all new columns manually.
> CSV endpoint: Add columns to output

- libs/wire-api/src/Wire/API/User.hs
- libs/wire-api/src/Wire/API/UserMap.hs
- libs/wire-api/src/Wire/API/Wrapped.hs
- libs/wire-api/test/unit/Test/Wire/API/Roundtrip/Aeson.hs
- libs/wire-api/test/unit/Test/Wire/API/Swagger.hs
- libs/wire-api/wire-api.cabal
- services/brig/src/Brig/API/Public.hs
- services/brig/test/integration/API/User/Client.hs
The new endpoint is at `POST /users/list-clients/v2`, this endpoint consumes a
JSON object with one key `qualified_users` whose value must be a list of
`Qualiified UserId` limited to MaxUsersForListClientsBulk.
> Add endpoint to list clients which doesn't accept a JSON list in req

- libs/wire-api/src/Wire/API/User/Client.hs
This has been broken during introduction of ormolu, and nobody has
noticed since.
> Fix comment formatting.

- README.md
This one-line fix is about a typo in the README
> Fixes a k8s typo in the README

- libs/wire-api-federation/test/Test/Wire/API/Federation/ClientSpec.hs
Rerelease https://github.com/wireapp/wire-server/pull/1483 with fix for a flaky test. 
- [brig] New option to use a random prekey selection strategy to remove DynamoDB dependency (#1416, #1476) 
- [brig] Ensure servant APIs are recorded by the metrics middleware (#1441)
- [brig] Add exact handle matches from all teams in /search/contacts (#1431, #1455)
- [brig] CSV endpoint: Add columns to output (#1452)
- [galley] Make pagination more idiomatic (#1460)
- [federation] Testing improvements (#1411, #1429)
- [federation] error reporting, DNS error logging (#1433, #1463)
- [federation] endpoint refactoring, new brig endpoints, servant client for federated calls, originDomain metadata (#1389, #1446, #1445, #1468, #1447)
- [federation] Add federator to galley (#1465)
- [move-team] Update …
> Release 2021_05_05

- libs/types-common/src/Data/Misc.hs
- libs/wire-api/src/Wire/API/Asset/V3.hs
- libs/wire-api/src/Wire/API/Asset/V3/Resumable.hs
- libs/wire-api/src/Wire/API/Conversation/Member.hs
- libs/wire-api/src/Wire/API/Event/Conversation.hs
- libs/wire-api/src/Wire/API/Message.hs
- libs/wire-api/src/Wire/API/Team.hs
- libs/wire-api/test/unit/Test/Wire/API/Roundtrip/Aeson.hs
This changes `Arbitrary` instances for types that had flaky JSON roundtrip tests. Here is the list of changes:
- `Milliseconds` is a 64 bit integer which is converted to and from `Double` when going through JSON encoding. Its arbitrary instance now limits it to values that JSON can represent exactly (up to 2^53).
- `Asset`, `ResumableAsset`, `Event` and `ClientMismatch` truncate the times they contain to millisecond precision. The `Arbitrary` instance now reflects that.
- The "mute status" field of `MemberUpdate` never gets serialised (why?). Therefore, the arbitrary instance always sets it to `Nothing`.
- `OtherMemberUpdate` cannot be `Nothing`.
- `TeamUpdateData` cannot have all its fields set to `Nothing`.
> Fix Arbitrary instances and enable corresponding roundtrip tests

- charts/brig/templates/tests/configmap.yaml
- libs/brig-types/brig-types.cabal
- libs/brig-types/package.yaml
- libs/brig-types/src/Brig/Types/User/EJPD.hs
- libs/brig-types/test/unit/Test/Brig/Roundtrip.hs
- libs/brig-types/test/unit/Test/Brig/Types/User.hs
- libs/hscim/src/Web/Scim/Schema/User/Phone.hs
- libs/types-common/src/Data/Handle.hs
- libs/wire-api/src/Wire/API/Connection.hs
- libs/wire-api/src/Wire/API/Team/Member.hs
- libs/wire-api/src/Wire/API/User/Identity.hs
- libs/wire-api/test/unit/Test/Wire/API/Roundtrip/Aeson.hs
- services/brig/brig.cabal
- services/brig/package.yaml
- services/brig/src/Brig/API/Internal.hs
- services/brig/src/Brig/Data/Connection.hs
- services/brig/src/Brig/IO/Intra.hs
- services/brig/src/Brig/Run.hs
- services/brig/src/Brig/User/EJPD.hs
- services/brig/test/integration/API/Internal.hs
- services/brig/test/integration/Main.hs
- services/brig/test/integration/Util.hs
- services/gundeck/src/Gundeck/API/Internal.hs
Attempt at streamlining the internal process at wire.com described [here](https://wearezeta.atlassian.net/wiki/spaces/~463749889/pages/256738296/EJPD+official+requests+process).
We are legally required to sometimes provide user information to law enforcement.  This change introduces an internal end-point to compile the minimum required information into a json blob.
**Security:** to access the internal end-point, you need the same access privileges that also give you direct access to the database.  So the information we provide here does not get any more accessible.  On the other hand, direct database access is error prone and make result in revealing information on the wrong user due to cut&paste errors.  This end-point mitigates this risk to a large extent.
> Internal end-point for ejpd request processing.

- libs/wire-api/src/Wire/API/User.hs
This one-line PR fixes a typo in the `wire-api` documentation.
> Fixes a typo in the wire-api documentation

- libs/wire-api/package.yaml
- libs/wire-api/wire-api.cabal
This dependency was introduced by mistake, and it added an extra libsodium dependency to all the executables.
> Remove zauth dependency from wire-api

- tools/ormolu.sh
This is probably slightly less robust, but it removes a dev dependency with multiple incompatible incarnations (https://github.com/mikefarah/yq, https://github.com/abesto/yq, https://github.com/kislyuk/yq ...) and different incompatible versions. Also avoids the use of awk in the script.
> RFC: Use sed instead of yq to read yaml files in ormolu script

- libs/types-common/src/Data/Qualified.hs
This simple PR removes the `Data.Qualified.OptionallyQualified` data type from types-common as it is unused.
> Remove OptionallyQualified data type from types-common

- libs/wire-api/src/Wire/API/Conversation/Member.hs
- libs/wire-api/test/golden/testObject_MemberUpdate_user_11.json
- libs/wire-api/test/golden/testObject_MemberUpdate_user_3.json
- libs/wire-api/test/golden/testObject_MemberUpdate_user_4.json
- libs/wire-api/test/golden/testObject_MemberUpdate_user_7.json
- libs/wire-api/test/unit/Test/Wire/API/Golden/Generated/MemberUpdate_user.hs
Also adds the missing field (`otr_muted_status`) and remove the `Arbitrary` hack. The `ToJSON` instance of this type does not affect clients, so there should be no backward-compatibility worries.
> Schema instance for MemberUpdate

- charts/galley/templates/configmap.yaml
- charts/galley/templates/tests/configmap.yaml
- libs/wire-api-federation/package.yaml
- libs/wire-api-federation/src/Wire/API/Federation/Error.hs
- libs/wire-api-federation/wire-api-federation.cabal
- services/brig/src/Brig/API/Error.hs
- services/brig/test/unit/Test/Brig/API/Error.hs
- services/galley/galley.cabal
- services/galley/galley.integration.yaml
- services/galley/package.yaml
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Util.hs
Some preliminary work to make the endpoint for adding remote users to conversations functional. This implements point (1) in the comment of `addMembers`, i.e. it checks if remote users exist before adding them to a conversation. If some remote users do not exist, a new error with status code 400 is returned.
I also added some tests using the mock federator exposed by #1524.
The rest of the functionality required by `addMembers` will be implemented in follow-up PRs.
> Add remote members to conversations

- libs/schema-profunctor/src/Data/Schema.hs
- libs/schema-profunctor/test/unit/Test/Data/Schema.hs
- libs/types-common/src/Data/LegalHold.hs
- libs/wire-api/src/Wire/API/Conversation.hs
- libs/wire-api/src/Wire/API/Conversation/Typing.hs
- libs/wire-api/src/Wire/API/Event/Conversation.hs
- libs/wire-api/src/Wire/API/User/Profile.hs
This populates the `required` field of Swagger schemas generated using `SchemaP`. See commit description for more information on the implementation.
> Add required fields to Swagger for SchemaP

- libs/schema-profunctor/README.md
- libs/schema-profunctor/src/Data/Schema.hs
- libs/schema-profunctor/test/unit/Test/Data/Schema.hs
I have added some more explanations and examples to the README of schema-profunctor. These should hopefully cover most of the situations encountered in wire-api.
> More examples in schema-profunctor documentation

- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/LegalHold.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/API/Teams/Features.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-410
> Allow Legalhold for large teams (>2000)

- CHANGELOG.md
- libs/brig-types/src/Brig/Types/Connection.hs
- libs/wire-api/src/Wire/API/Connection.hs
- services/brig/src/Brig/API/Connection.hs
- services/brig/src/Brig/API/Internal.hs
- services/brig/src/Brig/Data/Connection.hs
- services/brig/src/Brig/Data/Instances.hs
- services/brig/src/Brig/User/EJPD.hs
- services/galley/src/Galley/API/LegalHold.hs
- services/galley/src/Galley/API/Query.hs
- services/galley/src/Galley/API/Util.hs
- services/galley/src/Galley/Intra/User.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
See haddocks for `RelationWithHistory` for more info.  Fixes a bug [introduced here](https://github.com/wireapp/wire-server/pull/1507) that can only be triggered if legalhold is enabled (not the default).
> Fix: Connection type when unblocking after LH

- libs/types-common/src/Data/Misc.hs
- libs/wire-api/src/Wire/API/User/Orphans.hs
- libs/wire-api/src/Wire/API/User/Profile.hs
- services/galley/src/Galley/API/LegalHold.hs
- services/galley/src/Galley/API/Update.hs
internal change, no need to show in the release notes.  it's pretty small and self-explanatory.
>  Refactoring-friendly FutureWork data type

- libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs
- libs/wire-api/src/Wire/API/Event/Conversation.hs
- services/galley/src/Galley/API/Federation.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/API/Util.hs
- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Data/Queries.hs
- services/galley/test/integration/API/Federation.hs
This implements the federation RPC `update-conversation-membership` in galley. It simply registers local users as belonging to the given remote conversation and sends out an event. Actually calling this RPC from the other domain will be implemented separately in another PR.
Note that at this point the event type does not properly reflect the fact that the conversation and the joined users may belong to different domains. This will be fixed once #1547 is merged.
> Update conversation membership

- libs/wire-api-federation/src/Wire/API/Federation/Mock.hs
- libs/wire-api-federation/test/Test/Wire/API/Federation/ClientSpec.hs
- services/brig/test/integration/Federation/Util.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Util.hs
This makes the fake response provided to a mock federator take a request argument. The motivation is that it allows a single mock to be used to provide multiple fake responses depending on the requests received.
For example, when testing the endpoint for adding remote members to conversations, the mock federator will be queried twice: once to fetch remote user profiles, and once to propagate the join event to the remote backend. Therefore, we need to be able to set up different fake responses for the two requests.
See [this commit](https://github.com/wireapp/wire-server/pull/1556/commits/1f69b233508a01378d54bfd694335023ecd1d345) in #1556 for a usage example.
> Parametric mock federator

- libs/schema-profunctor/src/Data/Schema.hs
Schemas created with the `text` and `parsedText` combinators now have a `String` type in the corresponding Swagger schema.
> Set swagger type of text schema

- charts/nginz/values.yaml
- hack/helm_vars/wire-server/values.yaml
- services/brig/test/integration/API/Team/Util.hs
- services/brig/test/integration/API/User/Auth.hs
- services/galley/galley.cabal
- services/galley/package.yaml
- services/galley/src/Galley/API/LegalHold.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/App.hs
- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Data/LegalHold.hs
- services/galley/src/Galley/Run.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
- services/galley/test/integration/API/Teams/LegalHold/DisabledByDefault.hs
- services/galley/test/integration/API/Util.hs
- services/galley/test/integration/TestHelpers.hs
- services/galley/test/unit/Main.hs
- services/galley/test/unit/Test/Galley/Roundtrip.hs
This PR removes the `legalHoldTeamsWhitelist` galley config item and introduces a new internal endpoint `/i/legalhold/whitelisted-teams` to manage the set of whitelisted teams (the underlying table is `galley.legalhold_whitelisted`). Since the whitelisted teams are needed on every team member lookup this list is cached: at the beginning of every request the list is fetched and stored in an ioref in galley's environment.
The API is
- `PUT /i/legalhold/whitelisted-teams/{tid}` to whitelist a team
- `GET /i/legalhold/whitelisted-teams` which returns a list of team uuids as a JSON array
- There is no way to remove team from the whitelist. 
This PR updates the galley configuration for 1) CI and and for 2) local development:
`legalhold: whitelist-teams-and-implicit-consent` (was `legalhold: …
> Legalhold: dynamic whitelisted teams & whitelist-teams-and-implicit-consent feature in tests

- libs/bilge/bilge.cabal
- libs/bilge/src/Bilge/IO.hs
- libs/bilge/src/Bilge/TestSession.hs
It allows for having any MonadIO m monad at the bottom, and not just IO.
> Introduce a generalized version of wai-extra Session type constructor

- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Util.hs
- It allows to access a Galley instance in a monad implementing the class.
> Introduces the HasGalley class

- libs/wire-api/src/Wire/API/ErrorDescription.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- libs/wire-api/wire-api.cabal
- services/galley/src/Galley/API/Update.hs
This type will have special instances of HasSwagger so we can express the error
responses of a request using UVerb and they will appear correctly in the swagger
documentation.
> wire-api: Introduce ErrorDescription

- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/LegalHold.hs
- services/galley/src/Galley/App.hs
- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Data/LegalHold.hs
- services/galley/src/Galley/Data/Queries.hs
- services/galley/src/Galley/Run.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
Follow up from #1557. This removes the full-table scan strategy and adds a whitelist query on every team member lookup.
This PR also removes the internal endpoint
`GET /i/legalhold/whitelisted-teams`
and introduces a new internal endpoint
`GET /i/legalhold/whitelisted-teams/:tid"` (200 if the team is whitelisted, otherwise 404)
> Legalhold: Remove caching for whitelisted teams

- charts/federator/templates/configmap.yaml
- charts/federator/templates/tests/configmap.yaml
- services/federator/federator.cabal
- services/federator/federator.integration.yaml
- services/federator/src/Federator/Env.hs
- services/federator/src/Federator/ExternalServer.hs
- services/federator/src/Federator/Options.hs
- services/federator/src/Federator/Run.hs
- services/federator/src/Federator/Service.hs
- services/federator/test/unit/Test/Federator/ExternalServer.hs
Federator is currently forwarding all its requests to brig, regardless of the value of the `Component` field. This PR adds support for arbitrary internal services, renames the `Brig` effect to `Service` to reflect its generalised function, and adds a configuration option for galley.
> federator: rename Brig -> Service and add galley

- hack/helm_vars/wire-server/values.yaml
If I understand correctly, these are only used in tests, so there should be no danger in disabling them. With those requests on, I cannot run two clusters on my machine, so I always have to apply this patch locally, which is inconvenient.
> Remove resource requests

- libs/wire-api/package.yaml
- libs/wire-api/src/Wire/API/Message.hs
- libs/wire-api/src/Wire/API/Message/Proto.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- libs/wire-api/src/Wire/API/ServantProto.hs
- libs/wire-api/wire-api.cabal
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/test/integration/API/Util.hs
Changes:
- Introduce `Wire.API.ServantProto.Proto` to express that an endpoint can accept or respond with protobuf
- Make `Wire.API.Message` depend on `Wire.API.Message.Proto` so that an instance of `FromProto Wire.API.Message.NewOtrMessage` can be written in `Wire.API.Message` module. This required moving some functions around.
- Delete unused code in galley
> Servantify Protobuf endpoint to send messages

- stack.yaml
- stack.yaml.lock
This should fix the issue we were experiencing with end2end tests randomly failing on CI. The underlying problem is that the nginx controller proxying the federator uses an HTTP2 feature which was implemented incorrectly in the http2 library, which we indirectly depend on. See https://github.com/kazu-yamamoto/http2/issues/27.
This imports a [fix from our fork](https://github.com/wireapp/http2/tree/header-encoding-0-size-table-backport) into our stackage snapshot.
> Import http2 fix

- services/brig/src/Brig/Team/API.hs
Server operators can't act on these errors in any way.
> demote logging failed invitations to a warning, rather than an error

- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/API/Util.hs
- Break up addToConversation to its constituents
- Move Galley helper functions to a Util module
> Reorganise helper functions for conversation notifications

- services/galley/src/Galley/API/Create.hs
- services/galley/src/Galley/API/LegalHold.hs
- services/galley/src/Galley/API/Query.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/API/Util.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
- services/galley/test/integration/API/Util.hs
Description rewritten by me (@smatting):
This PR ensures that users of these categories
- category 1: users that are under legalhold (are in state
`UserLegalholdPending` or `UserLegalholdActive`)
- category 2: users that didn't give consent to be in a conversation with user from group 1
cannot be in the same group conversation (1:1 conversations are handled in #).
This is enforced by
1) removing users from group conversations and
2) preventing the creation of conversations with users from both categories 1 and 2.
When a user is transitioning into the `UserLegalholdPending` state all her group
conversations are traversed and users are removed. Who gets removed from the
conversation depends on the admins of the group conversation:
- If any of the admins has given consent then all users …
> Handle LH policy conflicts in group conversations

- libs/wire-api/package.yaml
- libs/wire-api/src/Wire/API/ErrorDescription.hs
- libs/wire-api/src/Wire/API/Routes/Public.hs
- libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
- libs/wire-api/src/Wire/API/ServantSwagger.hs
- libs/wire-api/wire-api.cabal
- services/brig/src/Brig/API/Public.hs
There is a slight complication here due to the fact that `Empty200` and `Empty404` are used in a `UVerb`, and `UVerb` does not really support the no content type case.
The solution in this patch is to define an overlapping instance for `HasServer UVerb` for an empty list of content types.
Also, the combinators in `ErrorDescription` (taken from `servant-swagger`) have been moved to a new module and reused for the
definition of the `Swagger` instance for a `UVerb` contaning empty results.
> Merge Empty200, Empty404 and EmptyResult

- libs/schema-profunctor/src/Data/Schema.hs
- libs/types-common/src/Data/Misc.hs
- libs/wire-api/src/Wire/API/ErrorDescription.hs
- libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
- libs/wire-api/src/Wire/API/User/Auth.hs
- libs/wire-api/src/Wire/API/User/Client.hs
- services/brig/src/Brig/API/Public.hs
This just converts a few more endpoints to servant and introduces the corresponding schema instances.
> Servantify own client API

- charts/brig/templates/tests/configmap.yaml
- libs/wire-api/src/Wire/API/Conversation/Member.hs
- services/brig/test/integration/Federation/End2end.hs
- services/brig/test/integration/Federation/Util.hs
- services/brig/test/integration/Main.hs
- services/galley/galley.cabal
- services/galley/src/Galley/API/Federation.hs
- services/galley/src/Galley/API/Mapping.hs
- services/galley/test/integration/API.hs
- services/galley/test/unit/Main.hs
- services/galley/test/unit/Test/Galley/Mapping.hs
- services/integration.yaml
* fixes the implementation of getting a conversation by ID: the conversationView and getConversationRPC call was incomplete / wrong.
* also fixes one futurework in one brig integration test
This should have been part of #1566
> end2end test getting remote conversation and complete its implementation

- services/brig/brig.cabal
- services/brig/package.yaml
- services/brig/src/Brig/API/Handler.hs
- services/brig/test/integration/API/User/Client.hs
- services/galley/galley.cabal
- services/galley/package.yaml
- services/galley/src/Galley/App.hs
Clients are relying on the content type being set in order to parse the error and react accordingly. This is true at least for the `too-many-clients` error, but possibly others.
> Set content-type header for JSON errors in Servant

- .github/pull_request_template.md
Hopefully this helps us create a nicer experience for reviewers and people who cut releases.
> Add checklist for PRs

- services/brig/src/Brig/API/Error.hs
- services/brig/src/Brig/API/Handler.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/Team/API.hs
- services/brig/test/integration/API/User/Client.hs
- services/brig/test/unit/Test/Brig/API/Error.hs
Some clients (webapp at least) are relying on the response body being empty (or at least not a valid JSON error value) when fetching a non-existing client. This restores the previous behaviour by adding a new special constructor for brig handler errors, resulting in an empty response body.
> Restore old error behaviour for client not found

- services/brig/test/integration/API/User/Util.hs
This checks that the password field of a delete client request is indeed optional. Previously, a null value was used for the password, but removing the field completely should catch more decoding bugs. See #1604.
> Test passwordless client delete with empty object

- .github/pull_request_template.md
Some lines were formatted with hard breaks, while some were left long. This removes all hard breaks and relies on github for line wrapping.
> More consistent formatting of PR template

- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Util.hs
These tests broke when merging #1593
> Galley/int: Expect remote call when creating conv with remotes

- charts/team-settings/values.yaml
Image tag: `4.0.0-v0.28.18-0-0846c0a`
Release: [`v4.0.0`](https://github.com/wireapp/wire-team-settings/releases/tag/v4.0.0)
> Update team-settings version in Helm chart [skip ci]

- charts/nginz/values.yaml
- deploy/services-demo/conf/nginz/nginx.conf
Also bump max_body_size on all conversation endpoints to 40m
Leftover from #1593
> Add qualified endpoint to send messages in nginz config

- charts/webapp/values.yaml
Addresses https://github.com/wireapp/wire-webapp/security/advisories/GHSA-382j-mmc8-m5rw
We have automation in place, so this will happen automatically in the future.  The PR with the security fix was merged just before the github action that triggers release updates was merged hence this slipped through the cracks (https://github.com/wireapp/wire-webapp/pull/11158). Hence triggering manually.
> Bump wire-webapp

- CHANGELOG.md
- charts/nginz/values.yaml
- deploy/services-demo/conf/nginz/nginx.conf
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Util.hs
'OTR' refers to the predecessor of proteus. Since we use proteus as our messaging protocol, it is more appropriate to call it so.
> Replace 'otr' with 'proteus' in new message sending API

- libs/wire-api/src/Wire/API/Conversation.hs
- libs/wire-api/test/golden/fromJSON/testObject_NewConvUnmanaged_user_21.json
- libs/wire-api/test/unit/Test/Wire/API/Golden/FromJSON.hs
- libs/wire-api/test/unit/Test/Wire/API/Golden/Generated/NewConvUnmanaged_user.hs
Allow creating a conversation without any local users by omitting the 'users' field entirely. This allows client teams to slowly deprecate the 'users' field in the request body in favour of 'qualified_users' going forward.
> Federation: Allow conversation creation without specifying 'users' in the request (but only qualified_users)

- CHANGELOG.md
- libs/schema-profunctor/README.md
This adds some extra explanations to the section about optional fields, and introduces the new `optField` combinator, added to work around the parser leniency issue described in #1621.
> Document optField combinator.

- CHANGELOG.md
- libs/wire-api/src/Wire/API/Message.hs
> Message: Disallow unspecified ClientMismatchStrategy

- CHANGELOG.md
- libs/schema-profunctor/src/Data/Schema.hs
- libs/types-common/src/Data/Qualified.hs
- libs/wire-api/src/Wire/API/Conversation/Role.hs
- libs/wire-api/src/Wire/API/User/Orphans.hs
- libs/wire-api/src/Wire/API/UserMap.hs
- libs/wire-api/src/Wire/API/Wrapped.hs
- services/brig/src/Brig/API/Public.hs
This fixes issues in our Swagger schema reported by @ffflorian, plus other validation errors reported by https://editor.swagger.io/.
- Removed spaces and parentheses from schema names. I simply used dots instead of spaces and avoided parentheses.
- Fixed dangling reference by explicitly declaring `Action` in a manually defined `Swagger.Schema`.
- Made the schema produced by `optField` optional (this should have been part of #1621, but I forgot).
- Fixed the schema for `FormRedirect`, which made absolutely no sense. It was generated by the generic mechanism, but now it's written by hand. See the corresponding commit (or comment) for more information on why it was broken.
- Removed duplicated `SecurityRequirement` entries. This is a bit strange, since it is a list of maps, instead of simply …
> Swagger fixes

- CHANGELOG.md
- services/brig/src/Brig/Run.hs
- services/brig/test/integration/API/User/Client.hs
- services/galley/src/Galley/Run.hs
A parse error in an endpoint body now returns a proper JSON error object that includes the label "bad-request". This should reproduce the behaviour on parse errors before the migration to Servant.
> Add label to parse error responses

- CHANGELOG.md
- hack/federation/grpcurlhandle.sh
- hack/federation/python-client/README.md
- hack/federation/python-client/client.py
Both the grpcurl and the python client were not working anymore after the changes made in #1447, #1445 and #1511 This Pr makes these scripts work again.
> Adjust grpccurl and python client examples to recent protobuf changes

- CHANGELOG.md
- libs/bilge/src/Bilge/Assert.hs
- services/galley/src/Galley/API/Message.hs
- services/galley/src/Galley/Data.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
- services/galley/test/integration/API/Teams/LegalHold/DisabledByDefault.hs
- services/galley/test/integration/API/Util.hs
This PR implements fetching of remote clients when sending messages involving remote users, and takes those clients into account when checking recipients and computing missing, deleted and redundant clients. 
This supersedes #1623.
> Remote client discovery

- CHANGELOG.md
- deploy/services-demo/conf/galley.demo.yaml
- hack/helm_vars/wire-server/values.yaml
- services/galley/galley.integration.yaml
https://wearezeta.atlassian.net/browse/SQSERVICES-535
**Mote context:** (thanks @Yserz, and please correct me if I got anything wrong)
The old url was pointing to the webapp, and that will keep working as well as it works now, namely:
- webapp can create and consume those links;
- mobile clients can create, but not consume them.
In order to allow mobile clients to join conversations with the logged-in user (not a guest, that was harder to implement), the backend should now create new guest-links that point to the account pages under the new path.  For web, this does not change anything, the new link will work as well as the old.  For mobile, this will make things work via the logged-in user.
This PR makes sure that all tests, on-prem installations, ... can make this change.  Until they …
> Change conversationCodeURI in galley.yaml.

- CHANGELOG.md
- services/federator/src/Federator/ExternalServer.hs
- services/federator/src/Federator/Service.hs
- services/federator/src/Federator/Validation.hs
- services/federator/test/integration/Test/Federator/InwardSpec.hs
- services/federator/test/unit/Test/Federator/ExternalServer.hs
- services/federator/test/unit/Test/Federator/Validation.hs
At the moment we use the convention that all RPCs between federator -> brig/galley/etc use the "federation" path prefix. This PR adds validation to ensure other paths cannot be called, as that would expose non-federation APIs (including internal, non-authenticated ones) to the world.
See also the discussion in https://wearezeta.atlassian.net/wiki/spaces/CORE/pages/224166764/Limiting+access+to+federation+endpoints
> Federation: sanitize paths to avoid path traversal attacks

- CHANGELOG.md
- services/spar/src/Spar/API.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
**Bug:** If an IdP issuer is changed from A to B and then back to A, the second update fails with the message "A alredy in use".  This is technically correct, since we keep old idp configs around to allow gradual migration of users from old issuer name to new.  
**Fix:** IdPs should be allowed to reuser their *own* issuer names.
**Technical details:** [from memory, I probably should double-check] the idp keeps a list of old idp issuer names around.  If a user tries to auth with a new issuer name, but cannot be found in `spar.user`, we pull the list of old idp issuer names, and do lookups in `spar.user` by those.  If we find a user, it is because that user has not been seen since before one or more idp metadata updates, and the entry in `spar.user` is outdated.  We fix the entry and return …
> Saml IDP: allow to re-use previously used issuer names.

- Makefile
- hack/bin/helm-template.sh
This allows debugging helm templating issues more easily without installing everything for a quicker feedback loop. (e.g. in #1626 this would have saved some debugging time)
- this doesn't need any mention in the changelog.
> makefile target for helm templating charts

- .github/pull_request_template.md
>  Extend checklist in PR template.

- CHANGELOG.md
- libs/wire-api/src/Wire/API/Team/Export.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/test/integration/API/Teams.hs
This PR adds a column "user_id" to the CSV file returned by `GET /teams/:tid/members/csv`.
The column is appended to the end with the hopes of breaking less workflows that are build upon this CSV than prepending would.
> Add user_id to csv export

- CHANGELOG.md
- services/brig/src/Brig/API/Public.hs
- services/brig/test/integration/API/User/Account.hs
- services/brig/test/integration/API/User/Auth.hs
- services/brig/test/integration/API/User/PasswordReset.hs
- services/brig/test/integration/API/User/Util.hs
- services/brig/test/integration/Util.hs
This reverts commit 72fefad91e6d569e247541bedf7571004950825d, which breaks both our CI and QA test automation.
> Revert "Remove deprecated end-point for changing email."

- CHANGELOG.md
- libs/schema-profunctor/src/Data/Schema.hs
- libs/schema-profunctor/test/unit/Test/Data/Schema.hs
- libs/types-common/src/Data/Id.hs
- libs/wire-api/src/Wire/API/ErrorDescription.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Query.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/API/Util.hs
This introduces a `CanThrow` type to be used in Servant APIs, declaring exceptions that can be thrown by the handler. The `CanThrow` type is ignored by Servant, but results in a new response being produced in Swagger.
This PR also arranges for specialised Swagger schemas to be displayed in the response section of endpoints with possible error responses. The specialised schemas have better example and more restrictions on the possible values of the error label.
> Document Servant endpoint errors for Galley routes

- CHANGELOG.md
- libs/galley-types/src/Galley/Types/Teams.hs
- libs/galley-types/test/unit/Test/Galley/Types.hs
- services/galley/galley.integration.yaml
- services/galley/src/Galley/API/Teams/Features.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-622
Related: https://github.com/wireapp/wire-server/pull/1652
> Make file sharing feature configurable at instance level.

- CHANGELOG.md
- services/brig/src/Brig/API/User.hs
This PR is a pure refactoring of `createUser` from `Brig.API.User`. Motivation for this PR was to make function more readable.
> Refactor createUser function

- services/galley/src/Galley/API/Error.hs
Just removing an unused federation error. I haven't added a CHANGELOG entry for this, should I?
> Remove old federation error code

- CHANGELOG.md
- services/brig/test/integration/API/User/Account.hs
- services/brig/test/integration/API/User/Handles.hs
- services/galley/test/integration/API.hs
This PR adds integration tests to make sure that certain error responses behave as expected. This is mostly preparation for merging #1657.
> Test error responses

- CHANGELOG.md
- docs/reference/config-options.md
This improves the documentation for the classified domains feature by making it clear that your own domain has to be listed as a classified domain for the feature to work properly.
> [Federation] [Documentation] Clarify Whitelisting Your Own Domain as Classified

- CHANGELOG.md
- libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/test/integration/API/User/Account.hs
Servant implements HEAD endpoints automatically in terms of GET endpoints. As it turned out, the explicit implementations we had for `HEAD /users/:uid` (and its qualified counterpart) ended up not being invoked by Servant's routing mechanism.
This simply removes the endpoints, and adds tests showing that the functionality is still present and works as expected.
> Remove unused HEAD endpoints

- CHANGELOG.md
- docs/reference/cassandra-schema.cql
- docs/reference/config-options.md
- libs/galley-types/src/Galley/Types/Teams.hs
- libs/galley-types/test/unit/Test/Galley/Types.hs
- libs/wire-api/src/Wire/API/Event/FeatureConfig.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- libs/wire-api/src/Wire/API/Team/Feature.hs
- libs/wire-api/test/unit/Test/Wire/API/Roundtrip/Aeson.hs
- services/federator/federator.cabal
- services/galley/galley.cabal
- services/galley/galley.integration.yaml
- services/galley/schema/src/Main.hs
- services/galley/schema/src/V52_FeatureConferenceCalling.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Teams/Features.hs
- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Data/TeamFeatures.hs
- services/galley/test/integration/API/Teams/Feature.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-681
This PR also:
- refactor some of the feature endpoint implementation
- adds to test that all simple flags should emit a `feature-config.update` event
> Add feature flag "conferenceCalling"

- CHANGELOG.md
- libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs
- libs/wire-api-federation/src/Wire/API/Federation/Domain.hs
- services/federator/src/Federator/Service.hs
- services/galley/test/integration/API/Util.hs
> Rename `DomainHeader` to `OriginDomainHeader`

- CHANGELOG.md
- libs/wire-api/src/Wire/API/User.hs
> fix swagger: mark name in UserUpdate as optional

- CHANGELOG.md
- services/brig/src/Brig/API/Error.hs
- services/brig/src/Brig/IO/Intra.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
- services/galley/test/integration/API/Teams/LegalHold/DisabledByDefault.hs
412 is used for "need to add some clients" in message posting; 403 makes client implementations more straight-forward.
It's probably worth mentioning that this only affects users about to get in contact with LH devices.  For those users, we have a new safety check in place that if the user has old clients or is not in a team cleared for LH, she will get a new error response.  403 in that case is better, since it makes it clear to the client that this won't work on retry either.  412 is used for notifying the client that they need to pick up some newly added clients listening in on the conversation, so this will probably break in less nice ways.
tl;dr: only affects users in touch with LH teams that shouldn't, and makes their UX strictly better.  :)
> Change http response code for `missing-legalhold-consent`.

- services/galley/test/integration/API/Federation.hs
This is a rather small and insignificant change, hence I haven't added a change log.
The one-line change just puts the expected and actual value arguments to `(@?=)` in the correct order in a federation test.
> Fix the Order of Arguments to a Test Assertion

- CHANGELOG.md
- libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs
- libs/wire-api-federation/test/Test/Wire/API/Federation/Golden/MessageSendResponse.hs
- libs/wire-api/package.yaml
- libs/wire-api/src/Wire/API/ErrorDescription.hs
- libs/wire-api/src/Wire/API/Message.hs
- libs/wire-api/src/Wire/API/Routes/MultiVerb.hs
- libs/wire-api/src/Wire/API/Routes/Public.hs
- libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- libs/wire-api/wire-api.cabal
- services/brig/src/Brig/API/Error.hs
- services/brig/src/Brig/API/Public.hs
- services/galley/src/Galley/API/Create.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Message.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/API/Update.hs
This PR completely removes `UVerb` from the codebase, as well as the `EmptyResult` kludge that we needed to generate empty responses. Both are now replaced by `MultiVerb`.
> Finish integrating `MultiVerb`

- CHANGELOG.md
- libs/hscim/hscim.cabal
- libs/hscim/package.yaml
- libs/hscim/src/Web/Scim/Capabilities/MetaSchema.hs
- libs/hscim/src/Web/Scim/Client.hs
- libs/hscim/src/Web/Scim/Schema/AuthenticationScheme.hs
- libs/hscim/src/Web/Scim/Server.hs
- libs/hscim/test/Test/Schema/MetaSchemaSpec.hs
- libs/hscim/test/Test/Schema/UserSpec.hs
I need client functions for https://github.com/wireapp/ldap-scim-bridge.  This PR introduces them to the hscim library.
Please read commit-by-commit.
> hscim client

- libs/hscim/hscim.cabal
- libs/hscim/package.yaml
- libs/hscim/src/Web/Scim/Client.hs
- libs/hscim/test/Test/Schema/MetaSchemaSpec.hs
Inspired by another upload to hackage: https://hackage.haskell.org/package/hscim-0.3.5
> Bump hscim version / fix flaky test

- CHANGELOG.md
- services/galley/test/integration/API/Teams/Feature.hs
- services/galley/test/integration/API/Util/TeamFeature.hs
Motivated by https://wearezeta.atlassian.net/browse/SQSERVICES-712
> Integration test coverage.

- libs/schema-profunctor/README.md
Just typo fixes. No CHANGELOG entry.
> Fix typos in schema-profunctor README

- CHANGELOG-draft.md
- libs/galley-types/src/Galley/Types/Teams.hs
- libs/galley-types/test/unit/Test/Galley/Types.hs
shouldn't change behavior for any existing users, but i found a user in our staging env that has an unknown set of permissions, and for that user is should fix https://wearezeta.atlassian.net/browse/SQSERVICES-720.
I've explained things in comments in the code, where we'll be able to find it in the future.
> Make mapping between (team) permissions and roles more lenient.

- CHANGELOG-draft.md
- libs/hscim/CHANGELOG
- libs/hscim/hscim.cabal
- libs/hscim/package.yaml
- libs/hscim/src/Web/Scim/Capabilities/MetaSchema.hs
- libs/hscim/src/Web/Scim/Schema/AuthenticationScheme.hs
- libs/hscim/src/Web/Scim/Schema/Common.hs
- libs/hscim/src/Web/Scim/Schema/ResourceType.hs
- libs/hscim/test/Test/Schema/AuthenticationSchemeSpec.hs
- libs/hscim/test/Test/Schema/GroupSpec.hs
- libs/hscim/test/Test/Schema/MetaSchemaSpec.hs
- libs/hscim/test/Test/Schema/PatchOpSpec.hs
- libs/hscim/test/Test/Schema/ResourceSpec.hs
- libs/hscim/test/Test/Schema/UserSpec.hs
- libs/hscim/test/Test/Schema/Util.hs
The SCIM requires json attribute keys to be case-insensitive, and hscim mostly implements this, but not quite, until now.  This fixes this: `stack test --fast hscim --test-arguments='--match "/Test.Schema.User/JSON serialization/allows casing variations in field names/"'` fails on 7fbe431, but passes on 8e2ef77.
This is done by [turning all keys in a JSON object to lowercase recursively](https://github.com/wireapp/wire-server/pull/1714/files#diff-62d1c322a7c5856c36271c84e557df82a8d5d0fc9c2e294db7d280cb0d46061cR89-R99)
<details>
<summary>Failing tests on 7fbe431 for reference</summary>
```
test-integration/Test/Spar/Scim/UserSpec.hs:330:5: 
1) Spar.Scim.User, POST /Users, team has no SAML IdP, creates a user with PendingInvitation, and user can follow usual invitation process
uncaught …
```
> Fix hscim serialization

- CHANGELOG-draft.md
- charts/nginx-ingress-services/templates/certificate_federator.yaml
- charts/nginx-ingress-services/templates/secret.yaml
- charts/nginx-ingress-services/templates/secret_federator.yaml
Before this change, when using the 'jetstack/cert-manager' alongside
'wire-server' and 'nginx-ingress-services' helm charts (with
useCertManager: true), then each subsequent 'helm upgrade' command
re-generated a fresh 'certificaterequest' object that retrieved a fresh
certificate from let's encrypt; even if the existing certificate was
still valid.
This is probably due to both the 'Certificate' resource managing the
'Secret' resource, as well as helm itself also creating the 'Secret'
resource (with empty strings)
This is a problem because:
* it wastes let's encrypt resources
* it quickly leads to duplicate certificate rate limiting (5/week)
causing deployments to fail.
Using this command:
```
kubectl -n wire get certificaterequest --sort-by=.metadata.creationTimestamp
```
one can see that …
> [helm] certificate-manager: avoid duplicate certificate generation and rate limiting

- CHANGELOG-draft.md
- services/federator/src/Federator/Remote.hs
- services/federator/test/integration/Test/Federator/IngressSpec.hs
- services/federator/test/unit/Test/Federator/Remote.hs
Small reorganisation of how `RemoteError`s are thrown and logged in federator.
> federator: Refactor RemoteError handling

- CHANGELOG-draft.md
- docs/reference/spar-braindump.md
We should have a proper administrator's manual for SAML and SCIM topics, but for now we have a few files under `docs/reference`, and a few FAQ entries under docs.wire.com.  I am just quickly adding some up-to-date information here for lack of time to write the entire manual.  I am somewhat hopeful it'll be obvious this is a net improvement...
> Update spar braindump and explain idp deletion.

- CHANGELOG-draft.md
- stack.yaml
- stack.yaml.lock
This selects a snappy branch containing a fix for a linker issue with libsnappy-1.1.9. The fix is in this PR: https://github.com/bos/snappy/pull/7
> Fix snappy linker issue

- CHANGELOG-draft.md
- charts/webapp/values.yaml
> Bump webapp to 2021-09-06-staging.3-v0.28.24-e6e306b

- hack/bin/integration-test.sh
The hack in #1700 does not actually seem to work in CI, and in fact it prevents log output from being displayed at all when helm test fails.
The `integration-test-logs.sh` script is still around, and it can be used to display `helm test` output interactive when running tests manually in a terminal.
*No CHANGELOG entry.*
> Revert hack to display helm test output

- CHANGELOG-draft.md
- hack/bin/integration-test.sh
- libs/wire-api/src/Wire/API/Conversation.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Util.hs
This migrates the conversation rename endpoints to Servant, makes them deprecated, and adds a qualified endpoint for renaming a conversation. The qualified endpoint still only works for local conversations.
I also added some tests for both deprecated endpoints and the qualified endpoint, and a failing test for the qualified endpoint.
No new nginx routes are needed.
> Servantify conversation rename

- CHANGELOG-draft.md
- libs/tasty-cannon/package.yaml
- libs/tasty-cannon/src/Test/Tasty/Cannon.hs
- libs/tasty-cannon/tasty-cannon.cabal
- services/galley/src/Galley/API/Federation.hs
- services/galley/src/Galley/API/Message.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/test/integration/API/Federation.hs
This PR removes duplicated logic to push messages to clients by making logic
in Galley.API.Message.sendLocalMessages accomodating to pushing messages for
remote conversations, but still enforcing the recipients to be local. Using this
function from federation endpoint of galley allows us to not duplicate the logic
for how a message becomes an event and gets pushed to each client.
The PR also moves this logic from Galley.API.Update to Galley.API.Federation
as most of the logic to translate from inputs of the federation endpoint to
inputs for Galley.API.Message.sendLocalMessages is very federation specific and
doesn't need to live in the public API module.
> Ensure clients only receive messages meant for them in remote convs

- CHANGELOG-draft.md
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Query.hs
- services/galley/src/Galley/API/Update.hs
This converts `/conversation/:cnv/self` endpoints (`GET` and `PUT`) to servant, adds local-only stubs for their qualified counterparts, and deprecates the unqualified endpoints. This is only an internal change.
> Servantify conversation self member endpoints

- CHANGELOG-draft.md
- libs/wire-api-federation/proto/router.proto
- libs/wire-api-federation/src/Wire/API/Federation/Error.hs
- libs/wire-api-federation/src/Wire/API/Federation/GRPC/Types.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/test/unit/Test/Brig/API/Error.hs
- services/federator/src/Federator/InternalServer.hs
- services/federator/test/unit/Test/Federator/InternalServer.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Util.hs
This adds documentation of federation errors to Swagger. These are not response entries by endpoints, but simply a list of errors (with some brief explanations) divided into categories. They apply more or less to all endpoints that have anything to do with federation.
I also pasted it here so it is possible to see it rendered without building anything: https://gist.github.com/pcapriotti/e50f61c3a8f6abab900e25c9ff3457aa.
After some discussion, we decided the error codes are mostly fine
> Document federation errors

- CHANGELOG-draft.md
- services/galley/src/Galley/API/Query.hs
- services/galley/test/integration/API.hs
Depends on #1703
Re-work of #1713
>  Avoid remote calls to get conversation when it is not found locally

- CHANGELOG-draft.md
- libs/types-common/src/Data/Domain.hs
- libs/types-common/src/Data/Range.hs
> Fix swagger for `Range` and `Domain`

- changelog.d/5-internal/fed-cert-test-timeout
- services/federator/test/unit/Test/Federator/Monitor.hs
Apparently, 1 second is not enough in CI.
> Increase federator monitor test timeout to 10s

- changelog.d/1-api-changes/remove-get-self
- changelog.d/1-api-changes/remove-self-role-update
- libs/wire-api/src/Wire/API/Conversation/Member.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- libs/wire-api/test/golden/testObject_MemberUpdate_user_1.json
- libs/wire-api/test/unit/Test/Wire/API/Golden/Generated/MemberUpdate_user.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Query.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/Data.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Roles.hs
Updates to a member's role now always happen via `OtherMemberUpdate`, while `MemberUpdate` is only used to change conversation self status (i.e. hidden/muted/archived).
Also remove the newly added qualified endpoint for fetching self membership data. It was not implemented for remote conversations, and it is not going to be, since the role will not even be stored remotely.
> Remove self role updates

- changelog.d/5-internal/fix-flaky-spar-test
- services/spar/test-integration/Test/Spar/APISpec.hs
Possible fix for flaky test as described in https://wearezeta.atlassian.net/browse/SQSERVICES-780
```
Failures:
test-integration/Test/Spar/APISpec.hs:1159:17: 
1) Spar.API, delete corner cases, re-create previously deleted, dangling users
"<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\" \"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\"><html xml:lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\"><head>  <title>wire:sso:error:unknown-error</title>   <script type=\"text/javascript\">       const receiverOrigin = '*';       window.opener.postMessage({\"payload\":{\"errors\":[\"invalid-credentials {\\\"code\\\":403,\\\"message\\\":\\\"Authentication failed.\\\",\\\"label\\\":\\\"invalid-credentials\\\"}\"],\"label\":\"forbidden\"},\"type\":\"AUTH_ER …
```
> fix flaky test by waiting for user deletion to finish

- changelog.d/6-federation/new-remote-conversation-unqualify
- libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs
- services/galley/src/Galley/API/Federation.hs
- services/galley/src/Galley/API/Util.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Util.hs
This makes the conversation ID field of the `on-conversation-created` RPC (previously `register-conversation`) unqualified. The domain of the conversation is assumed to be the same as the backend invoking the RPC, which is obtained via `OriginDomainHeader`, so we do not need to include it in the RPC body, and therefore we do not need to check that it matches.
https://wearezeta.atlassian.net/browse/SQCORE-891
> Make conversation ID in on-conversation-created RPC unqualified

- changelog.d/5-internal/servantify-connections
- libs/wire-api/src/Wire/API/ErrorDescription.hs
- libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- libs/wire-api/src/Wire/API/Routes/Public/Util.hs
- services/brig/src/Brig/API/Error.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/test/integration/API/Metrics.hs
- services/galley/src/Galley/API/Update.hs
As part of https://wearezeta.atlassian.net/browse/SQCORE-693 before work on https://wearezeta.atlassian.net/browse/SQCORE-958 can begin.
Follow-up to #1726
> Servantify /connections endpoints

- changelog.d/5-internal/fix-conv-generator
- services/galley/test/unit/Test/Galley/Mapping.hs
The `ConvWithLocalUser` and `ConvWithRemoteUser` generators were potentially duplicating members. This makes sure that the member added by the generator was not already present.
> Fix conversation generator in mapping test

- changelog.d/4-docs/list-ids
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
Added more details on how to use the `conversation/list-ids` endpoint, included some information on the `paging_state` field and how to use it.
> Expand documentation of `list-ids` endpoint

- changelog.d/5-internal/applicative-style-generators
- services/galley/test/unit/Test/Galley/Mapping.hs
In Galley testing, this patch rewrites monadic style generators to applicative style generators. This has the benefit of smaller counterexamples in failing test cases, which makes debugging the tests easier and managable.
> Testing: Rewrite Conversation Generators in an Applicative Style

- changelog.d/1-api-changes/deprecate-messager-timer-update
- changelog.d/1-api-changes/qualified-message-timer-update
- changelog.d/5-internal/servantify-message-timer
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/test/integration/API/MessageTimer.hs
- services/galley/test/integration/API/Util.hs
Converted endpoint to Servant, made a qualified version and deprecated the unqualified one. This is part of https://wearezeta.atlassian.net/browse/SQCORE-885.
> Servantify message timer update endpoint

- build/alpine/Dockerfile.deps
- changelog.d/5-internal/ncurses-deps
It seems https://github.com/wireapp/wire-server/commit/36f51b59914c0112b1181199534048c22f37f59e has added a runtime dependency on ncurses to spar-schema. This adds ncurses to the docker image dependencies, so that the ephemeral services and CI can run.
> Add ncurses dependency

- changelog.d/1-api-changes/deprecate-other-member-update
- changelog.d/1-api-changes/qualified-other-member-update
- changelog.d/6-federation/servantify-other-member-update
- libs/wire-api/src/Wire/API/Conversation/Member.hs
- libs/wire-api/src/Wire/API/ErrorDescription.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/API/Util.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Util.hs
Converted endpoint to Servant, made a qualified version and deprecated the unqualified one. This is part of https://wearezeta.atlassian.net/browse/SQCORE-885.
> Servantify other member update

- changelog.d/6-federation/fed-conv-rename
- changelog.d/6-federation/fed-conv-update-notifications
- libs/tasty-cannon/src/Test/Tasty/Cannon.hs
- libs/types-common/src/Data/Qualified.hs
- libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs
- libs/wire-api-federation/test/Test/Wire/API/Federation/Golden/ConversationMemberUpdate.hs
- libs/wire-api-federation/test/Test/Wire/API/Federation/Golden/ConversationUpdate.hs
- libs/wire-api-federation/test/Test/Wire/API/Federation/Golden/GoldenSpec.hs
- libs/wire-api-federation/test/golden/testObject_ConversationUpdate1.json
- libs/wire-api-federation/test/golden/testObject_ConversationUpdate2.json
- libs/wire-api-federation/wire-api-federation.cabal
- libs/wire-api/src/Wire/API/Conversation.hs
- libs/wire-api/src/Wire/API/Conversation/Role.hs
- libs/wire-api/src/Wire/API/Event/Conversation.hs
- services/galley/src/Galley/API/Federation.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/API/Util.hs
- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Data/Queries.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Federation.hs
- services/galley/test/integration/API/Util.hs
This generalises the `on-conversation-memberships-changed` RPC to support notifications of conversation renames, by adding a new constructor to the corresponding "action" type.
We also unified and cleaned up the handling of these events on the remote side of a conversation, and added tests to make sure that we never send notifications to a usere when we are not sure they are part of the conversation.
This is part of https://wearezeta.atlassian.net/browse/SQCORE-885 (federated conversation metadata updates).
> Federation: support conversation renames

- changelog.d/5-internal/remove-explicit-errdesc
- libs/wire-api/src/Wire/API/ErrorDescription.hs
- services/brig/src/Brig/API/Connection.hs
- services/brig/src/Brig/API/Error.hs
- services/brig/src/Brig/API/Internal.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/Provider/API.hs
- services/brig/src/Brig/User/API/Auth.hs
- services/galley/src/Galley/API/Create.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Query.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/API/Util.hs
So far, every `ErrorDescription` type has been accompanied by a corresponding value created with `mkErrorDescription`. This PR removes all those definitions, and adds some convenience functions (to be used with type application) that make it easier to refer to the error without having an explicit typed instantiation available.
> Remove explicit instantiations of ErrorDescription values

- changelog.d/5-internal/remove-flaky-test
- services/brig/test/integration/API/Search.hs
This test is flaky for reasons that are probably out of our control. Since what is testing is not a particularly essential piece of functionality, I think we are better off removing it altogether, at least until a good solution is found.
See also https://github.com/wireapp/wire-server/pull/1774 and https://github.com/wireapp/wire-server/pull/1776.
> Remove flaky search order test

- changelog.d/1-api-changes/deprecate-receipt-mode-update
- changelog.d/1-api-changes/qualified-receipt-mode-update
- changelog.d/5-internal/servantify-receipt-mode
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Update.hs
Converted endpoint to Servant, made a qualified version and deprecated the unqualified one. This is part of https://wearezeta.atlassian.net/browse/SQCORE-885.
> Servantify receipt mode update

- changelog.d/5-internal/idp-effect
- services/spar/spar.cabal
- services/spar/src/Spar/Sem/IdP/Mem.hs
New polysemy interpreter for the effect introduced in #1787.
I suppose this would be even more useful if we had a `quickcheck-state-machine`-based "proof" that the two interpreters are equivalent, but that can be done in a separate PR.
> Pure interpreter for IdP effect

- changelog.d/6-federation/fed-conv-message-timer
- libs/wire-api/src/Wire/API/Conversation.hs
- libs/wire-api/src/Wire/API/Event/Conversation.hs
- services/galley/src/Galley/API/Federation.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Query.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/API/Util.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Federation.hs
- services/galley/test/integration/API/MessageTimer.hs
- services/galley/test/integration/API/Util.hs
This generalises the `on-conversation-updated` RPC to support notifications of message timer updates, by adding a new constructor to the corresponding "action" type.
This is part of https://wearezeta.atlassian.net/browse/SQCORE-885 (federated conversation metadata updates).
> Federation: support message timer updates

- libs/wire-api/src/Wire/API/Routes/MultiTablePaging.hs
This PR is about adding 'r' in a function name where it was missing. That said, I don't think this PR deserves an entry in the change log.
> Fix a Typo in a Function Name

- changelog.d/6-federation/fed-conv-member-update
- changelog.d/6-federation/fed-update-remote-members
- libs/api-bot/src/Network/Wire/Bot/Monad.hs
- libs/types-common/src/Data/Qualified.hs
- libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs
- libs/wire-api-federation/test/Test/Wire/API/Federation/Golden/ConversationUpdate.hs
- libs/wire-api/src/Wire/API/Conversation.hs
- libs/wire-api/src/Wire/API/Conversation/Action.hs
- libs/wire-api/src/Wire/API/Event/Conversation.hs
- libs/wire-api/test/golden/fromJSON/testObject_MemberUpdateData_user_1.json
- libs/wire-api/test/golden/testObject_Event_user_5.json
- libs/wire-api/test/golden/testObject_MemberUpdateData_user_1.json
- libs/wire-api/test/golden/testObject_MemberUpdateData_user_2.json
- libs/wire-api/test/unit/Test/Wire/API/Golden/FromJSON.hs
- libs/wire-api/test/unit/Test/Wire/API/Golden/Generated/Event_user.hs
- libs/wire-api/test/unit/Test/Wire/API/Golden/Generated/MemberUpdateData_user.hs
- libs/wire-api/wire-api.cabal
- services/galley/src/Galley/API/Federation.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/API/Util.hs
- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Data/Queries.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Federation.hs
- services/galley/test/integration/API/MessageTimer.hs
- services/galley/test/integration/API/Roles.hs
- services/galley/test/integration/API/Util.hs
- tools/api-simulations/smoketest/src/Network/Wire/Simulations/SmokeTest.hs
This generalises the `on-conversation-updated` RPC to support notifications of member updates, by adding a new constructor to the corresponding "action" type.
As part of this PR, updates to remote members have also been implemented, but at the moment only for local conversations.
Note: this includes a merge commit for #1783.
This is part of https://wearezeta.atlassian.net/browse/SQCORE-885 (federated conversation metadata updates).
> Federation: support other member updates

- changelog.d/4-docs/reference-schemas
- libs/schema-profunctor/src/Data/Schema.hs
- libs/wire-api/src/Wire/API/Event/Conversation.hs
This changes the Swagger implementation of `unnamed` in schema-profunctor to drop the name, but still declare the corresponding named schema. Now even unnamed schemas that are not actually referenced anywhere will appear in the list of schemas in Swagger.
Also changed the name of the schema for `SimpleMember` to make it reflect the Haskell type name.
Thanks @atomrc for reporting this issue.
> Make sure that unnamed schemas are referenced

- changelog.d/6-federation/remote-conversations-when-deleting-user
- libs/wire-api/src/Wire/API/ErrorDescription.hs
- services/galley/src/Galley/API/Federation.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Query.hs
- services/galley/src/Galley/Data.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Util.hs
This makes sure to remove a user from their remote conversation when the user's account is being deleted.
> [Federation] When Deleting a User, Remove Them From Remote Conversations

- changelog.d/4-docs/multitable-docs
- libs/wire-api/src/Wire/API/Routes/MultiTablePaging.hs
- libs/wire-api/src/Wire/API/Routes/MultiTablePaging/State.hs
- libs/wire-api/wire-api.cabal
Splitting the state encoding functions to a separate module makes it impossible to use them by mistake with the wrong bytestring (like the Cassandra paging token).
> Split `MultiTablePaging` module and add haddocks

- changelog.d/6-federation/remote-connections-migration
- docs/reference/cassandra-schema.cql
- services/brig/brig.cabal
- services/brig/schema/src/Main.hs
- services/brig/schema/src/V65_FederatedConnections.hs
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Data/Connection.hs
Migration to add a table for remote connections.
One question is whether we need the fields for the corresponding 1-1 connection. For now they are there, with the idea that it makes sense to store them in case we want to change the algorithm used to derive the conversation id from the user pair.
> Remote connections schema

- changelog.d/6-federation/chain-of-trust
- charts/nginx-ingress-services/templates/ingress_federator.yaml
- charts/nginx-ingress-services/values.yaml
This makes it possible to use client certificates with a longer chain of trust to the root CA.
https://wearezeta.atlassian.net/browse/SQCORE-898
> Add value for client TLS verification depth

- changelog.d/5-internal/member-update-refactoring
- changelog.d/6-federation/fed-receipt-mode
- libs/types-common/src/Data/Qualified.hs
- libs/wire-api-federation/test/Test/Wire/API/Federation/Golden/ConversationUpdate.hs
- libs/wire-api-federation/test/golden/testObject_ConversationUpdate1.json
- libs/wire-api-federation/test/golden/testObject_ConversationUpdate2.json
- libs/wire-api/src/Wire/API/Conversation/Action.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- services/galley/galley.cabal
- services/galley/src/Galley/API/Create.hs
- services/galley/src/Galley/API/Federation.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/LegalHold.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/API/Util.hs
- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Data/Services.hs
- services/galley/src/Galley/Types/UserList.hs
- services/galley/src/Galley/Validation.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Federation.hs
- services/galley/test/integration/API/Roles.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Util.hs
The initial purpose of this PR was to add federation behaviour for receipt mode update, which it does. However, in an effort to avoid copy-pasting code, it also unifies all the federation-aware conversation update code paths, and as a consequence the diff ended up being quite large.
The core of the unified interface is the `updateLocalConversation` function, which performs an update and notifies local and remote users.
**Note**: the remove member update is a bit special, because it was implemented using checked exceptions. To make it compatible with the other updates, checked exceptions are not currently used, although they are still present in some type signatures.
To make the unification possible, a number of other changes were necessary:
- Removed checked add member wrapper. This …
> Federation: support read receipts

- changelog.d/5-internal/merge-http2-client-fix
- stack.yaml
- stack.yaml.lock
We now depend on a fork of http2-grpc-haskell containing fixes for:
https://github.com/haskell-grpc-native/http2-grpc-haskell/pull/46
https://github.com/haskell-grpc-native/http2-grpc-haskell/pull/48
as well as the master of http2-client:
https://github.com/lucasdicioccio/http2-client
> Merge http2 grpc fixes

- changelog.d/1-api-changes/deprecate-access
- changelog.d/1-api-changes/qualified-access
- changelog.d/5-internal/servantify-access
- libs/wire-api/src/Wire/API/ErrorDescription.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Update.hs
Converted endpoint to Servant, made a qualified version and deprecated the unqualified one.
This is part of https://wearezeta.atlassian.net/browse/SQCORE-885.
> Servantify access update

- changelog.d/5-internal/spar-random-effects
- services/spar/spar.cabal
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/App.hs
- services/spar/src/Spar/Scim.hs
- services/spar/src/Spar/Scim/Auth.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/src/Spar/Sem/Random.hs
- services/spar/src/Spar/Sem/Random/IO.hs
- services/spar/test-integration/Util/Core.hs
This PR minimizes the `MonadIO` footprint still in Spar, by creating an effect that can generate random things.
> Spar Polysemy: Random effect

- changelog.d/5-internal/logger-effect
- services/spar/spar.cabal
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/App.hs
- services/spar/src/Spar/Run.hs
- services/spar/src/Spar/Scim.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/src/Spar/Sem/BrigAccess/Http.hs
- services/spar/src/Spar/Sem/GalleyAccess/Http.hs
- services/spar/src/Spar/Sem/Logger.hs
- services/spar/src/Spar/Sem/Logger/TinyLog.hs
- services/spar/test-integration/Util/Core.hs
This PR pulls a Logger effect out of Spar. It's a little roundabout currently, for two reasons:
1. `saml2-web-sso`'s exported interface requires `HasLogger`, so we keep a `HasLogger` instance around.
2. `tinylog` doesn't export enough of its internals to abstract around its usage, so we require a `Logger (Msg -> Msg)` effect to be around
Point 1 can be cleaned up by either polysemizing `saml2-web-sso`, or adding an effect to wrap it. If we're planning to do the former (currently in scope for the polysemizing project), the latter is wasted work. It seems to me like this is worth punting on until we have a game plan. In the meantime, the logger effect is nice to have teased apart, and easy to change when we figure out the longer term plan.
> Spar Polysemy: Logger effect

- changelog.d/5-internal/spar-no-monad-reader
- services/spar/package.yaml
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/App.hs
- services/spar/src/Spar/Scim.hs
- services/spar/src/Spar/Scim/Auth.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/src/Spar/Sem/AReqIDStore/Cassandra.hs
- services/spar/src/Spar/Sem/AssIDStore/Cassandra.hs
- services/spar/src/Spar/Sem/BindCookieStore/Cassandra.hs
- services/spar/test-integration/Util/Core.hs
- stack.yaml
- stack.yaml.lock
This PR removes the `ReaderT` inside of the `Spar` newtype, instead using the `Input` effect to thread the `Opts` to whichever places need it.
To be merged after #1814.
> Spar Polysemy: Remove ReaderT from Spar

- services/galley/test/integration/API/Util.hs
I can't think of a reason why an up-to-date index should be required during adding more users?
> Only update ES index at the end of member add loop.

- changelog.d/5-internal/stern-features
- tools/stern/src/Stern/Swagger.hs
Currently, these need to be added here manually.  I also left a TODO that we should automate that.
> Add missing features to stern/backoffice.

- changelog.d/5-internal/stern-ejpd
- tools/stern/src/Stern/API.hs
- tools/stern/src/Stern/Intra.hs
This exposes an internal end-point from brig for communication with swiss law enforcement to the stern/backoffice app.  Internal process to wire.com; does not increase exposure in any way as long as you don't operate stern insecurely.
> Expose internal EJPD request end-point to backoffice.

- changelog.d/5-internal/fed-connections-data
- services/brig/brig.cabal
- services/brig/package.yaml
- services/brig/src/Brig/API/Connection.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/API/Types.hs
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Data/Connection.hs
- services/brig/src/Brig/IO/Intra.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/MessageTimer.hs
This PR makes the Data functions for connections take `Qualified` arguments and simply return `UserConnection` values instead of using existing `LocalConnection`.
The `LocalConnection` type has been deleted, and now the handlers deal with `UserConnection` objects directly.
The listing/pagination functions have not been changed, since the pagination mechanism needs to be ported to the new multi-table system anyway.
> Make federated connection functions work with qualified IDs

- changelog.d/5-internal/spar-no-io-2
- services/spar/spar.cabal
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/App.hs
- services/spar/src/Spar/CanonicalInterpreter.hs
- services/spar/src/Spar/Error.hs
- services/spar/src/Spar/Scim.hs
- services/spar/src/Spar/Scim/Auth.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/src/Spar/Sem/Reporter.hs
- services/spar/src/Spar/Sem/Reporter/Wai.hs
- services/spar/src/Spar/Sem/SAML2/Library.hs
- services/spar/src/Spar/Sem/SAMLUserStore/Cassandra.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
- services/spar/test-integration/Test/Spar/AppSpec.hs
- services/spar/test-integration/Test/Spar/DataSpec.hs
- services/spar/test-integration/Test/Spar/Intra/BrigSpec.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
- services/spar/test-integration/Util/Core.hs
- services/spar/test-integration/Util/Scim.hs
This PR replaces `Spar`:
```haskell
newtype Spar r a = Spar { Member (Final IO) r => ExceptT (Sem r) a }
```
and instead uses `Sem` directly. In doing so, it means `Spar` is now completely polysemized :tada: :tada: 
Sorry for the size here, I got excited about being as close to the finish line as I was. That being said, the commits are well-organized, so they're a reasonable way to approach this monstrosity.
Most of this PR is boring; replacing `throwSpar` with `throwSparSem` and adding `Member (Error SparError)` constraints. Also, replacing `Spar` with `Sem`. But there are a few changes of interest:
1. Removing `wrapMonadClientSem`, which previously was used to guard all of the `Cassandra` effects. This function has been removed (it required `MonadIO`), but instead, it is now used to …
> Spar Polysemy: Fully polysemize Spar

- changelog.d/5-internal/hs-certificate-master
- stack.yaml
- stack.yaml.lock
The error handling fix https://github.com/vincenthz/hs-certificate/pull/125 has been merged, so we can just use the upstream master now, and later switch to the hackage package once it is released.
> Use hs-certificate master

- changelog.d/5-internal/servantify-add-member
- libs/wire-api/src/Wire/API/Conversation.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Update.hs
Servantify a leftover unqualified endpoint for adding members to a conversation.
> Servantify legacy addMember endpoint

- changelog.d/0-release-notes/pr-1857
- changelog.d/2-features/pr-1857-self-deleting-messages-feature
- docs/reference/cassandra-schema.cql
- libs/galley-types/src/Galley/Types/Teams.hs
- libs/galley-types/test/unit/Test/Galley/Types.hs
- libs/wire-api/src/Wire/API/Event/FeatureConfig.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- libs/wire-api/src/Wire/API/Swagger.hs
- libs/wire-api/src/Wire/API/Team/Feature.hs
- libs/wire-api/test/unit/Test/Wire/API/Roundtrip/Aeson.hs
- services/galley/galley.cabal
- services/galley/schema/src/Main.hs
- services/galley/schema/src/V54_TeamFeatureSelfDeletingMessages.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Teams/Features.hs
- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Data/TeamFeatures.hs
- services/galley/test/integration/API/Teams/Feature.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-574
Adds end-points (public-team, public-team-oblivious, internal) for CRUDding `selfDeletingMessages` as a feature.  Team admins can now choose between previous behavior (default), disable self-deleting messages, and enforce self-deleting messages with a given time-out.
This is enforced on the client-side.  The server merely maintains the configuration for teams (not site or personal, those have a baked-in default).
> [feature config] self-deleting messages

- changelog.d/1-api-changes/remove-locale-in-user-profiles
- libs/wire-api/src/Wire/API/User.hs
- libs/wire-api/test/golden/testObject_UserProfile_user_2.json
- libs/wire-api/test/unit/Test/Wire/API/Golden/Generated/UserProfile_user.hs
- libs/wire-api/test/unit/Test/Wire/API/User.hs
- services/galley/test/integration/API/Util.hs
The PR removes the locale from the `UserProfile` model in public endpoints. This affects, for example, the `GET /users/:domain/:uid` endpoint where the `locale` field is dropped. Client developers confirmed they do not use it.
See https://wearezeta.atlassian.net/browse/SQCORE-1077.
> Remove Locale from the UserProfile model

- changelog.d/6-federation/extend-get-conversations-test
- services/galley/test/integration/API/Federation.hs
The PR extends a federation API test for getting conversations to also include a one-to-one conversation with a remote user.
https://wearezeta.atlassian.net/browse/FS-53
> Extend a Federation API Test for Getting Conversations

- Makefile
This changes the haddock Makefile target to pass extra options to stack when building haddocks.
> Use WIRE_STACK_OPTIONS when building haddock

- changelog.d/0-release-notes/webapp-upgrade
- charts/webapp/values.yaml
Image tag: `2021-11-01-production.0-v0.28.29-0-d919633`
Release: [`2021-11-01-production.0`](https://github.com/wireapp/wire-webapp/releases/tag/2021-11-01-production.0)
> Update webapp version in Helm chart [skip ci]

- changelog.d/6-federation/close-grpc-client
- libs/wire-api-federation/src/Wire/API/Federation/Client.hs
- libs/wire-api-federation/src/Wire/API/Federation/GRPC/Client.hs
- services/federator/src/Federator/Remote.hs
- services/federator/test/integration/Test/Federator/IngressSpec.hs
- services/federator/test/integration/Test/Federator/Util.hs
- services/federator/test/unit/Test/Federator/Remote.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/Intra/Federator/Types.hs
This is a followup PR to #1865, addressing the same issue, but for GRPC connections to the internal federator. This also takes care of cleaning of the GrpcClient in tests.
> Close GRPC client after making a request to federator

- .github/workflows/ci.yml
- changelog.d/5-internal/ormolu-direnv
- direnv.nix
- tools/ormolu.sh
This will provide ormolu via direnv, and do some CI steps in GH Actions:
- ensuring the direnv environment (still) builds
- uploading it to the cachix cache
- run `make formatc` and provide feedback if code is not formatted.
> Provide ormolu via direnv, run `make formatc` in github actions

- changelog.d/3-bug-fixes/pr-1901
- services/galley/src/Galley/API/Teams/Features.hs
- Emit event when SelfDeletingMessages config changes (oversight in https://github.com/wireapp/wire-server/pull/1857)
- Same for AppLock config (oversight back then)
- Remove unused event (classified domains are not changed via rest api, so event cannot occur)
> Fix: push events when AppLock or SelfDeletingMessages config change.

- services/galley/galley.cabal
Regenerates galley.cabal from the package.yaml
> Regenerate galley.cabal from the package.yaml

- Makefile
- changelog.d/6-federation/notify-remotes
- services/brig/federation-tests.sh
- services/brig/test/integration/API/User/Util.hs
- services/brig/test/integration/Federation/End2end.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Util.hs
https://wearezeta.atlassian.net/browse/FS-41
> Federation: Notify remote participants when a user leaves a conversation because they were deleted

- tools/convert-to-cabal/generate.sh
Fixes a missing call in generate.sh
> Fix generate.sh of ./tools/convert-to-cabal

- changelog.d/6-federation/dont-fail-user-deletion-unavailble-remotes
- services/brig/src/Brig/IO/Intra.hs
- services/brig/test/integration/API/User/Account.hs
- services/brig/test/integration/Util.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/test/integration/API.hs
https://wearezeta.atlassian.net/browse/FS-124
> Do not fail user deletion when a remote notification fails

- .envrc
- direnv.nix
The direnv hook for wire-server uses the `load_prefix` function, which sets the `LD_LIBRARY_PATH` environment variable in development shells, so that cabal can pick up non-Haskell dependencies like zlib and cryptobox. However, this means that running programs inside the dev shell environment will cause libraries from the Nix store to be loaded, which can interfere with programs from the host system, especially for non-NixOS users. For example, I can't run `nix-build` inside a dev shell on Debian, as the dynamic loader tries to load an incompatible shared library from the Nix store instead of system libraries.
I've refactored the dev shell environment, and split everything but cabal into its own environment, wrapped cabal in a script which sets `LD_LIBRARY_PATH` to point to the …
> Fix LD_LIBRARY_PATH usage in direnv build environment

- changelog.d/3-bug-fixes/metrics-handlers
- libs/extended/extended.cabal
- libs/extended/package.yaml
- libs/extended/src/Servant/API/Extended.hs
- libs/metrics-wai/metrics-wai.cabal
- libs/metrics-wai/package.yaml
- libs/metrics-wai/src/Data/Metrics/Servant.hs
- libs/wire-api/package.yaml
- libs/wire-api/src/Wire/API/ErrorDescription.hs
- libs/wire-api/src/Wire/API/Routes/MultiVerb.hs
- libs/wire-api/src/Wire/API/Routes/Public.hs
- libs/wire-api/src/Wire/API/Routes/QualifiedCapture.hs
- libs/wire-api/test/unit/Main.hs
- libs/wire-api/test/unit/Test/Wire/API/Routes.hs
- libs/wire-api/wire-api.cabal
For prometheus metrics middleware to be able to replace
/users/4f7cbd8c-5fe3-4818-94c0-8ae68460ba13 with /users/:uid, it needs to know
the paths in servant that exist. This is generated statically using the class
`RoutesToPaths`. This class had an overlappable instance for everything, this
caused to not notice when we created the QualifiedCapture type. In order to
ensure that we instantiate this class correctly, this commit removes this
catch-all instance and instantiate the class for every type that needs it
explicitly.
https://wearezeta.atlassian.net/browse/FS-224
> Report QualifiedCapture correctly in prometheus metrics

- direnv.nix
It makes `cabal build` even more pure because it doesn't depend on preset values of `LD_LIBRARY_PATH`, `CPATH`, etc.
> direnv.nix: List all system deps for building haskell libraries

- docs/developer/dependencies.md
- docs/developer/how-to.md
- tools/nginz_disco/README.md
> Update documentation of dependency setup

- CHANGELOG.md
> Remove duplicate PR numbers from changelog

- changelog.d/4-docs/servant.md
- docs/developer/servant.md
Added some documentation on Servant, which is hopefully useful for the upcoming Servantification effort tracked by https://wearezeta.atlassian.net/browse/BE-529.
> Document Servant setup and combinators

- Makefile
- changelog.d/2-features/metrics
- charts/wire-server-metrics/dashboards/message-stats.json
- charts/wire-server-metrics/dashboards/services.json
- charts/wire-server-metrics/requirements.yaml
- charts/wire-server-metrics/templates/wire-server-dashboards.yaml
- charts/wire-server-metrics/values.yaml
The old version of prometheus operator chart is no longer compatible with latest
K8s versions. The chart has also since moved to kube-prometheus-stack on the
prometheus-community helm chart reposistory from the helm-stable repository.
The kube-prometheus-stack helm chart also allows creating dashboard using labels
on configmaps, so now we don't have to refer to non-pinned versions of the
dashboard definitions. Instead each dashboard now becomes a configmap with a
specific label and grafana discovers it.
This commit also updates the dashboards to use new ways of addressing the pods
which came with the move from old version of prometheus-operator chart to the
kube-prometheus-stack chart. Along with these changes, the dashboards now also
use the qualified endpoints and federation endpoints …
> charts/wire-server-metrics: Use kube-prometheus-stack

- .github/pull_request_template.md
- changelog.d/4-docs/changelog.d-docs
- docs/developer/changelog.md
I copied some docs from the PR description into a more permanent place and referenced it here in the PR template.  This was motivated by questions from new team members that should have had an easy-to-find answer.
> Changelog.d docs

- changelog.d/0-release-notes/minio-helm
- changelog.d/5-internal/minio-helm
- charts/fake-aws-s3/requirements.yaml
- charts/fake-aws-s3/templates/reaper.yaml
- charts/fake-aws-s3/values.yaml
- charts/fake-aws/templates/NOTES.txt
The repository at helm.min.io is down. But the one at charts.min.io is up. Unfortunately, the one at charts.min.io provides a slightly different helm chart. So, some options need to be adjusted accordingly.
> Use minio helm chart from charts.min.io instead of helm.min.io

- services/galley/galley.cabal
- services/galley/package.yaml
> Fix typo in cabal file.

- changelog.d/3-bug-fixes/elasticsearch-ephemeral-disable-auto-creation
- charts/elasticsearch-ephemeral/templates/es.yaml
This PR disables the automatic creation of indices in the `elasticsearch-ephemeral` chart.
Without this PR ES will create an index whenever a document is attempted to be indexed. This leads to a race-condition right after the `elasticsearch-ephemeral` release is deployed and all indices have been removed:
A) `brig` or `brig-index-migrate-data` indexes a user into a newly auto-created index `directory`
B) The `elasticsearch-index-create` job creates  a index `directory` if it doesn't exist yet
If A) happens before B) the `directory` index is useless to brig. Brig will not be able to find any users, because it assumes that fields like `team` are of type `keyword`. The auto-created index however gives all fields the type `text`.
If B) happens before A) all is good.
This PR assures that A) …
> elasticsearch-ephemeral: Disable automatic creation of indices

- changelog.d/2-features/structured-json-logs
- libs/extended/extended.cabal
- libs/extended/package.yaml
- libs/extended/src/System/Logger/Extended.hs
This format is intended as an imporvement over the JSON format. It tries to
improve in these ways:
- Explicitly encode log level as a key in the main JSON object logged
- Encode field values as key-value pairs in the main JSON object
Encoding logs like this makes it easy for external tools like fluent-bit and
elasticsearch to understand the log level and the fields and index them as such
without requiring bonanza to be present while processing logs.
https://wearezeta.atlassian.net/browse/FS-62
> Add new LogFormat: StructuredJSON

- Makefile
- changelog.d/2-features/elasticsearch
- changelog.d/2-features/fluent-bit
- changelog.d/2-features/kibana
- charts/elasticsearch-ephemeral/values.yaml
- charts/fluent-bit/requirements.yaml
- charts/fluent-bit/values.yaml
- charts/kibana/requirements.yaml
- charts/kibana/templates/basic-auth-secret.yaml
- charts/kibana/values.yaml
This change removes dependency on the deprecated https://charts.helm.sh repository for kibana and fluent-bit. As a result we get v6.8.18 of kibana. Kibana 6.8.x requires elasticsearch 6.8.x, so this change also upgrades the default version of elasticsearch to 6.8.18 when installing with the elasticsearch-ephemeral chart.  
https://wearezeta.atlassian.net/browse/FS-62
> Upgrade kibana and fluent-bit helm charts

- dev-packages.nix
- shell.nix
There seems to be no direnv plugin for VSCode that works with remotes.
(I haven't checked the local / non-remote case.)
This commit introduces a shell.nix file that depends on the same package
list as direnv.nix, but uses mkShell instead of buildEnv to create the
environment. This works fine with nix-shell itself and VSCode's
'Nix Environment Selector' plugin.
> Add shell.nix for ad-hoc development environments

- docs/developer/editor-setup.md
VSCode provides excellent Haskell support. Thought it might be good to document how to use it for this project.
> Document how to setup VSCode

- changelog.d/3-bug-fixes/structured-json
- libs/extended/extended.cabal
- libs/extended/package.yaml
- libs/extended/src/System/Logger/Extended.hs
- libs/extended/test/Spec.hs
- libs/extended/test/Test/System/Logger/ExtendedSpec.hs
Fix for https://github.com/wireapp/wire-server/pull/1951#issuecomment-984479669
https://wearezeta.atlassian.net/browse/FS-62
> Correctly detect log level when rendering logs as structured JSON

- services/galley/src/Galley/API/Action.hs
Just a small refactoring to avoid quadratic runtime building a user team membership map when adding new members to a conversation.
> Avoid linear lookup when checking new members

- changelog.d/6-federation/add-cargohold-component
- charts/federator/templates/configmap.yaml
- charts/federator/templates/tests/configmap.yaml
- libs/wire-api-federation/src/Wire/API/Federation/API.hs
- libs/wire-api-federation/src/Wire/API/Federation/API/Cargohold.hs
- libs/wire-api-federation/src/Wire/API/Federation/Component.hs
- libs/wire-api-federation/wire-api-federation.cabal
- services/cargohold/cargohold.cabal
- services/cargohold/package.yaml
- services/cargohold/src/CargoHold/API/Federation.hs
- services/cargohold/src/CargoHold/App.hs
- services/cargohold/src/CargoHold/Run.hs
- services/federator/federator.integration.yaml
- services/federator/src/Federator/Options.hs
- services/federator/src/Federator/Run.hs
- services/federator/test/integration/Test/Federator/InwardSpec.hs
- services/federator/test/integration/Test/Federator/Util.hs
This PR simply adds Cargohold as a new federated component in Federator, and a federated API stub in Cargohold itself.
**Note**: this contains the first few commits from #1966.
> Add federation component for Cargohold

- changelog.d/4-docs/update-fed-error-docs
- libs/wire-api-federation/src/Wire/API/Federation/Error.hs
- services/brig/Setup.hs
- services/brig/brig.cabal
- services/brig/docs/swagger.md
- services/brig/package.yaml
- services/brig/src/Brig/API/Public.hs
- services/federator/src/Federator/Discovery.hs
- services/federator/src/Federator/Validation.hs
This is about making sure that the documentation of federation errors in the public API is up to date with respect to the changes introduced in https://github.com/wireapp/wire-server/pull/1930.
Tracked by https://wearezeta.atlassian.net/browse/FS-262.
> Update federation error documentation

- changelog.d/4-docs/update-fed-error-docs
- services/federator/test/integration/Test/Federator/InwardSpec.hs
Fix failing test on develop caused by merging #1956 and #1973.
> Fix assertion after #1956

- changelog.d/5-internal/galley-request-id
- services/galley/src/Galley/App.hs
- services/galley/src/Galley/Run.hs
This PR makes sure that the request ID is passed correctly to the logger on all endpoints in galley. Before the fix, only wai-route endpoints were running in an environment with the correct request ID.
> galley: Set request id correctly in Wai app

- changelog.d/4-docs/update-fed-error-docs
- services/brig/Setup.hs
- services/brig/brig.cabal
- services/brig/package.yaml
Follow-up to #1956, fixing issues reported by @fisx:
- remove obsolete data-files stanza from brig's cabal file;
- generate doc modules on repl invocation, as well as on build.
> Fix brig doc module generation

- changelog.d/5-internal/fix-cargohold-flake
- charts/fake-aws-s3/values.yaml
With `purge: true` the reaper script will delete the bucket's content when it runs, causing integration tests to fail occasionally.
This fixes a very frequent flake in CI integration tests (e.g.  https://bridge-ie-concourse.zinfra.io/builds/21651258).
> Do not purge bucket in fake-s3

- changelog.d/5-internal/cabal-make-c-test-all
- hack/bin/cabal-run-tests.sh
This fixes the cabal test running script when `package=all`.
> Fix `make c test=1`

- services/galley/test/integration/API.hs
This relates to the first item from [this ticket](https://wearezeta.atlassian.net/browse/SQSERVICES-1126)
> SQSERVICES-1126 Provide test cases for SF.Separation BSI

- changelog.d/5-internal/sftd-multi-sft
- charts/sftd/templates/statefulset.yaml
- charts/sftd/values.yaml
https://wearezeta.atlassian.net/browse/FS-265
> SFT chart: Add multiSFT option, remove additionalArgs option

- docs/developer/editor-setup.md
> Add a paragraph about using VSCode in a direnv env

- services/galley/test/integration/API.hs
> Move Integration Test BSI Tags to Top

- changelog.d/5-internal/sftd-multi-sft-fixup
- charts/sftd/templates/statefulset.yaml
> Fix bug in SFT chart: multi sft args are quoted

- changelog.d/4-docs/sqservices-1127
- services/brig/test/integration/API/User/Auth.hs
- services/brig/test/integration/API/User/Client.hs
- services/brig/test/integration/API/User/Handles.hs
This PR addresses the Haskell part of https://wearezeta.atlassian.net/browse/SQSERVICES-1127.
> Improve Test Documentation for BSI (SQSERVICES-1127)

- services/spar/test-integration/Test/Spar/APISpec.hs
- services/spar/test-integration/Test/Spar/Scim/AuthSpec.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1128
> SQSERVICES-1128 Tag Integration Tests (PROVISIONING/CHANNEL)

- changelog.d/5-internal/sqservices-1118-2
- libs/zauth/test/ZAuth.hs
- services/brig/test/integration/API/User/Account.hs
- services/brig/test/integration/API/User/Auth.hs
- services/brig/test/integration/API/User/Client.hs
- services/brig/test/integration/API/User/Handles.hs
- services/galley/test/integration/API.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
- services/spar/test-integration/Test/Spar/Scim/AuthSpec.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1128
> Add end-tags for test tag parser (BSI audit).

- changelog.d/5-internal/schema-profunctor-optional
- libs/galley-types/src/Galley/Types/Conversations/Intra.hs
- libs/schema-profunctor/README.md
- libs/schema-profunctor/src/Data/Schema.hs
- libs/schema-profunctor/test/unit/Test/Data/Schema.hs
- libs/types-common/src/Data/Domain.hs
- libs/wire-api/src/Wire/API/Connection.hs
- libs/wire-api/src/Wire/API/Conversation.hs
- libs/wire-api/src/Wire/API/Conversation/Code.hs
- libs/wire-api/src/Wire/API/Conversation/Member.hs
- libs/wire-api/src/Wire/API/Event/Conversation.hs
- libs/wire-api/src/Wire/API/Message.hs
- libs/wire-api/src/Wire/API/Routes/Internal/Brig/Connection.hs
- libs/wire-api/src/Wire/API/Routes/MultiTablePaging.hs
- libs/wire-api/src/Wire/API/User.hs
- libs/wire-api/src/Wire/API/User/Client.hs
- libs/wire-api/src/Wire/API/User/Profile.hs
Improved the API for optional fields, and made it harder to misuse it. See README for more details.
> schema-profunctor: better optional field API

- changelog.d/5-internal/sqservices-1169
- services/galley/galley.cabal
- services/galley/schema/src/Main.hs
- services/galley/schema/src/V57_GuestLinksLockStatus.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Teams/Features.hs
- services/galley/src/Galley/Cassandra.hs
- services/galley/src/Galley/Cassandra/TeamFeatures.hs
- services/galley/src/Galley/Data/TeamFeatures.hs
- services/galley/test/integration/API/Teams/Feature.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1169
> SQSERVICES-1169 New internal endpoint to configure the guest links team feature

- changelog.d/2-features/pr-1976
- libs/wire-api/src/Wire/API/ErrorDescription.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/Query.hs
- services/galley/src/Galley/API/Teams/Features.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Util.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1057
This PR handles only `conversations/join`
- ~~If HTTP endpoint paths have been added or renamed, the **endpoint / config-flag checklist** (see Wire-employee only backend [wiki page](https://github.com/zinfra/backend-wiki/wiki/Checklists)) has been followed.~~
- ~~If a cassandra schema migration has been added, I ran **`make git-add-cassandra-schema`** to update the cassandra schema documentation.~~
- ~~If new config options introduced: added usage description under docs/reference/config-options.md~~
- ~~If new config options introduced: recommended measures to be taken by on-premise instance operators.~~
- ~~If a cassandra schema migration is backwards incompatible (see also [these …
> SQSERVICES-547 Enforce disabling guest links when conversation is joined

- changelog.d/2-features/pr-1980
- services/galley/src/Galley/API/Query.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/test/integration/API.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1057
- ~~If HTTP endpoint paths have been added or renamed, the **endpoint / config-flag checklist** (see Wire-employee only backend [wiki page](https://github.com/zinfra/backend-wiki/wiki/Checklists)) has been followed.~~
- ~~If a cassandra schema migration has been added, I ran **`make git-add-cassandra-schema`** to update the cassandra schema documentation.~~
- ~~If new config options introduced: added usage description under docs/reference/config-options.md~~
- ~~If new config options introduced: recommended measures to be taken by on-premise instance operators.~~
- ~~If a cassandra schema migration is backwards incompatible (see also [these docs](https://github.com/wireapp/wire-server/blob/develop/docs/developer/cassandra-interaction.m …
> SQSERVICES-547 post/get conversation/:cnv/code returns error if feature disabled

- changelog.d/5-internal/map-federation-tests
- services/brig/docs/swagger.md
- services/federator/src/Federator/Discovery.hs
- services/federator/src/Federator/Validation.hs
- services/federator/test/integration/Test/Federator/IngressSpec.hs
- services/federator/test/integration/Test/Federator/InwardSpec.hs
- services/federator/test/unit/Test/Federator/InternalServer.hs
- services/federator/test/unit/Test/Federator/Options.hs
- services/federator/test/unit/Test/Federator/Response.hs
- services/federator/test/unit/Test/Federator/Validation.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
Documents and provides federation test cases per https://wearezeta.atlassian.net/browse/SQCORE-1198.
@mythsunwind
> Documentation for Federation Test Cases

- changelog.d/5-internal/fix-cabal-install
- hack/bin/cabal-install-artefacts.sh
The script should create the `dist` directory, if it does not exist.
> Fix cabal install script

- changelog.d/5-internal/hlint-federator
- services/federator/src/Federator/ExternalServer.hs
- services/federator/src/Federator/InternalServer.hs
- services/federator/src/Federator/MockServer.hs
- services/federator/src/Federator/Monitor/Internal.hs
- services/federator/test/integration/Test/Federator/IngressSpec.hs
- services/federator/test/unit/Test/Federator/Client.hs
- services/federator/test/unit/Test/Federator/InternalServer.hs
- services/federator/test/unit/Test/Federator/Util.hs
- services/federator/test/unit/Test/Federator/Validation.hs
> Fix doubtless HLint issues in Federator

- changelog.d/6-federation/sft-servers-all
- charts/brig/templates/configmap.yaml
- libs/dns-util/dns-util.cabal
- libs/dns-util/package.yaml
- libs/dns-util/src/Wire/Network/DNS/A.hs
- libs/dns-util/src/Wire/Network/DNS/Effect.hs
- libs/wire-api/src/Wire/API/Call/Config.hs
- libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/RTCConfiguration_user.hs
- services/brig/brig.cabal
- services/brig/package.yaml
- services/brig/src/Brig/Calling.hs
- services/brig/src/Brig/Calling/API.hs
- services/brig/src/Brig/Options.hs
- services/brig/test/integration/API/Calling.hs
- services/brig/test/unit/Test/Brig/Calling.hs
This implements https://wearezeta.atlassian.net/browse/FS-266.
> FS-266: Add sft_servers_all to calls/config/v2

- .gitignore
- docs/developer/linting.md
> Add documentation about linting

- changelog.d/6-federation/sft-servers-all-fixup
- charts/brig/templates/configmap.yaml
- services/brig/brig.cabal
- services/brig/brig.integration.yaml
- services/brig/package.yaml
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Calling.hs
- services/brig/src/Brig/Calling/API.hs
- services/brig/src/Brig/Effects/SFT.hs
- services/brig/src/Brig/Options.hs
- services/brig/test/integration/API/Calling.hs
- services/brig/test/unit/Test/Brig/Calling.hs
This is a follow-up to PR #2012 as part of https://wearezeta.atlassian.net/browse/FS-266:
- It places SFT lookup parameters to a better-suited section in Brig's configuration
- It enables making an insecure connection by using an IP address in a request to an SFT server (`https://<ip-address>/...`) if a test environment flag is set in Brig's configuration
- It fixes making a request `GET https://<sft-ip-address>/sft/url`
> Enable Insecure Requests for SFT Lookups in a Test Environment

- changelog.d/6-federation/sft-brig-configmap-fix
- charts/brig/templates/configmap.yaml
- services/brig/src/Brig/Options.hs
This is a follow-up to PR #2014 and part of https://wearezeta.atlassian.net/browse/FS-266. It fixes templating in Brig's configmap.
> Fix Brig's configmap for SFT Lookup Templating

- changelog.d/5-internal/brig-faster-doc
- services/brig/Setup.hs
- services/brig/brig.cabal
- services/brig/package.yaml
This PR makes it so that the Swagger documentation module is not regenerated if its content is unchanged. This makes brig compile times a bit better.
> Faster brig setup

- changelog.d/5-internal/simplify-ranged-schema
- libs/types-common/src/Data/Range.hs
- libs/wire-api/src/Wire/API/Conversation.hs
- libs/wire-api/src/Wire/API/Team.hs
There is no need to take in singletons in order to create the bounds for a ranged schema, so this PR simplifies `rangedSchema` so that it does not need to be passed singletons explicitly anymore.
> Simplify `rangedSchema` function

- changelog.d/5-internal/pr-2008
- libs/wire-api/src/Wire/API/ErrorDescription.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- libs/wire-api/src/Wire/API/Team/Member.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Teams.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1011
- `PUT /teams/:tid` endpoint
> SQSERVICES 1011 servantify gally team api (PUT /teams/:tid)

- changelog.d/6-federation/sft-fix-ipv4-http
- services/brig/brig.cabal
- services/brig/brig.integration.yaml
- services/brig/package.yaml
- services/brig/src/Brig/Calling.hs
- services/brig/src/Brig/Effects/SFT.hs
- services/brig/test/integration/API/Calling.hs
- services/brig/test/unit/Test/Brig/Calling.hs
This is part of https://wearezeta.atlassian.net/browse/FS-266:
- It allows for using a plain HTTP connection given an IPv4 address of an SFT server,
- It adds a proper integration test for `sft_servers_all` as the previously extended test silently ignored a code path.
> [FS-266] Fix SFT URL fecthing based on plain HTTP via IPv4

- changelog.d/0-release-notes/pr-2027
- changelog.d/1-api-changes/pr-2027
- changelog.d/5-internal/pr-2008
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Util.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1011
`GET /teams`
> SQSERVICES 1011 Servantify Gally Team API (GET /teams)

- changelog.d/5-internal/restund-chart
- charts/restund/Chart.yaml
- charts/restund/README.md
- charts/restund/templates/_helpers.tpl
- charts/restund/templates/configmap-restund-conf-template.yaml
- charts/restund/templates/secret.yaml
- charts/restund/templates/service-account.yaml
- charts/restund/templates/service.yaml
- charts/restund/templates/statefulset.yaml
- charts/restund/values.yaml
https://wearezeta.atlassian.net/browse/FS-270
schema documentation.
> Add helm chart for restund

- changelog.d/5-internal/avoid-servant-generics
- libs/wire-api/src/Wire/API/Routes/Named.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- libs/wire-api/wire-api.cabal
- services/galley/galley.cabal
- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Public/Servant.hs
The generic mechanism in Servant for defining API types is cumbersome and slow to compile. This commit replaces the API record for the public Galley API with a tree explicitly built using the `:<|>` operator.
To make up for the lack of record labels, it also introduces a `Named` combinator for servant API types, which can be used to tag an endpoint with a name (usually a symbol). The name must match the one with which the handler is wrapped.
Compile times are indeed better with this change, but unfortunately not by much.
> Remove uses of servant-generic in public Galley API

- changelog.d/3-bug-fixes/fix-cargohold-streaming
- services/cargohold/src/CargoHold/Federation.hs
- services/cargohold/test/integration/API.hs
Client teams reported that via PR #2004 merged, they cannot download remote assets of size 20 KB and larger. This fixes the issue by addressing incorrect resource handling. The limitation is that if an error happens before streaming starts, it will result in an empty response. @pcapriotti is working on addressing that case in a follow-up PR.
> Fix Remote Asset Downloading via Better Resource Handling

- changelog.d/5-internal/fix-integration-yaml
- services/integration.yaml
https://github.com/wireapp/wire-server/pull/2004 introduced a field backendTwo.carghold. This needs to be populated to be able to locally run integration tests.
> integration.yaml add missing backendTwo.carghold

- changelog.d/3-bug-fixes/fix-cargohold-streaming
- services/cargohold/src/CargoHold/Federation.hs
- services/cargohold/test/integration/API.hs
Followup to #2037. Throw the correct user-visible error, and add test to check that error responses are generated correctly.
> Followup to remote asset download fix

- changelog.d/5-internal/ghc-8107-fix-old-time
- dev-packages.nix
This PR fixes the following bug:
Building the haskell package `old-time` with the wrapped cabal (see `dev-packages.nix`) may fail dynamic library failures for `/bin/sh` such as
```
/bin/sh: /nix/store/1yvpgm763b3hvg8q4fzpzmflr5674x4j-glibc-2.32-10/lib/libc.so.6: version `GLIBC_2.33' not foun
```
This can happen if `/bin/sh` expects a different glibc than the wrapped cabal provides via `LD_LIBRARY_PATH`.
This bug is fixed by setting `CONFIG_SHELL` which will make the build script of `old-time` not use `/bin/sh` but a `sh` defined in `dev-packages.nix`.
> Fix broken build process for package "old-time"

- changelog.d/6-federation/tag-test-cases-m2
- services/federator/test/unit/Test/Federator/Remote.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Federation.hs
This implements https://wearezeta.atlassian.net/browse/FS-333. 
Still to do:
> [FS-333] Tag Test Cases for M2

- changelog.d/5-internal/scimtokenstore-lookup
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/App.hs
- services/spar/src/Spar/Scim/Auth.hs
- services/spar/src/Spar/Sem/ScimTokenStore.hs
- services/spar/src/Spar/Sem/ScimTokenStore/Cassandra.hs
- services/spar/src/Spar/Sem/ScimTokenStore/Mem.hs
- services/spar/test-integration/Test/Spar/DataSpec.hs
This PR changes the name of `Spar.Sem.ScimTokenStore.GetByTeam` to `LookupByTeam` --- a follow-up on a promise I made to @fisx to rename this in a later PR.
> Spar Polysemy: Rename ScimTokenStore.GetByTeam -> ScimTokenStore.LookupByTeam

- changelog.d/5-internal/fix-hlint-issues-in-wire-api
- libs/wire-api/src/Wire/API/Arbitrary.hs
- libs/wire-api/src/Wire/API/Conversation/Member.hs
- libs/wire-api/src/Wire/API/Conversation/Role.hs
- libs/wire-api/src/Wire/API/CustomBackend.hs
- libs/wire-api/src/Wire/API/Push/V2/Token.hs
- libs/wire-api/src/Wire/API/Routes/Internal/Brig/Connection.hs
- libs/wire-api/src/Wire/API/Routes/MultiVerb.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- libs/wire-api/src/Wire/API/Team/Invitation.hs
- libs/wire-api/src/Wire/API/Team/LegalHold.hs
- libs/wire-api/src/Wire/API/Team/LegalHold/External.hs
- libs/wire-api/src/Wire/API/Team/Permission.hs
- libs/wire-api/src/Wire/API/User/Client.hs
- libs/wire-api/src/Wire/API/User/Client/Prekey.hs
- libs/wire-api/src/Wire/API/User/Orphans.hs
- libs/wire-api/src/Wire/API/User/Password.hs
- libs/wire-api/src/Wire/API/User/RichInfo.hs
- libs/wire-api/src/Wire/API/User/Saml.hs
- libs/wire-api/test/unit/Test/Wire/API/User.hs
- libs/wire-api/test/unit/Test/Wire/API/User/RichInfo.hs
Fixing these issues has two benefits:
- The code is (hopefully) easier to read.
- HLint issues that might indicate errors are easier to spot. (Less "noise" in HLint's output.)
> Fix (some) HLint issues in wire-api

- changelog.d/3-bug-fixes/cors-followup
- charts/nginz/templates/conf/_nginx.conf.tpl
Followup to https://github.com/wireapp/wire-server/pull/1630
Without this PR the  `{{ range }}` expressions rebinds `.`, which makes `.Values.nginx_conf.external_env_domain` fail.
`$.` seems to be the outer (correct) scope. I tested the template locally with this change with the helm version in-use by `cailleach`.
> Fix: nginz template broken for allowlisted_origins

- changelog.d/3-bug-fixes/fs-266-http-exceptions
- services/brig/src/Brig/Calling/API.hs
- services/brig/src/Brig/Effects/SFT.hs
- services/brig/test/integration/API/Calling.hs
- services/brig/test/unit/Test/Brig/Calling.hs
Followup to https://github.com/wireapp/wire-server/pull/2030
> Fix bug: Calls config crashes when SFTs are unreachable

- changelog.d/0-release-notes/pr-2059
- changelog.d/2-features/pr-2059
- changelog.d/5-internal/pr-2059
- charts/galley/templates/configmap.yaml
- charts/galley/values.yaml
- docs/reference/cassandra-schema.cql
- docs/reference/config-options.md
- libs/galley-types/src/Galley/Types/Teams.hs
- libs/wire-api/src/Wire/API/Event/FeatureConfig.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- libs/wire-api/src/Wire/API/Team/Feature.hs
- libs/wire-api/test/golden/Test/Wire/API/Golden/Manual/FeatureConfigEvent.hs
- libs/wire-api/test/golden/testObject_FeatureConfigEvent_1.json
- services/galley/galley.cabal
- services/galley/galley.integration.yaml
- services/galley/schema/src/Main.hs
- services/galley/schema/src/V59_FileSharingLockStatus.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Public/Servant.hs
- services/galley/src/Galley/API/Teams/Features.hs
- services/galley/src/Galley/Data/TeamFeatures.hs
- services/galley/test/integration/API/Teams/Feature.hs
- services/galley/test/integration/API/Util/TeamFeature.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1168
> Sqservices 1168 add lockstatus to feature configs

- changelog.d/2-features/brig-two-es-clusters
- docs/reference/elastic-search.md
- services/brig/brig.cabal
- services/brig/package.yaml
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Index/Eval.hs
- services/brig/src/Brig/Index/Migrations/Types.hs
- services/brig/src/Brig/Options.hs
- services/brig/src/Brig/User/Search/Index.hs
- services/brig/test/integration/API/Search.hs
https://wearezeta.atlassian.net/wiki/spaces/PS/pages/548798616/ElasticSearch+Migration+Proposal#3.-Zero-Downtime-Migration%3F
> Support zero-downtime migration between ES clusters

- changelog.d/5-internal/multiverb-improvements
- libs/wire-api/src/Wire/API/ErrorDescription.hs
- libs/wire-api/src/Wire/API/Routes/MultiVerb.hs
- libs/wire-api/src/Wire/API/Routes/Public/Cargohold.hs
- services/cargohold/test/integration/API.hs
- services/cargohold/test/integration/API/Util.hs
This PR makes it possible to more cleanly separate content type negotiation in `MultiVerb` endpoints from the actual content types generated by responses.
It introduces a `RespondAs` type to be used as a `MultiVerb` response that always replies with a fixed content type, regardless of the content type that has been requested by the client.
It also makes it possible to pass a promoted unit value `'()` to `MultiVerb` instead of a list of content types. This disables content negotiation altogether and makes it possible for an endpoint to return statically chosen content types, rather than the one requested by the user.
This fixes an outstanding issue with the asset download endpoint, which was previously refusing to accept requests that had an `Accept` header not containing …
> Allow disabling accept check in MultiVerb

- changelog.d/5-internal/fix-pr-2070-compilation
- services/spar/src/Spar/Sem/AReqIDStore/Cassandra.hs
- services/spar/src/Spar/Sem/SAMLUserStore/Cassandra.hs
PR #2070 made export lists explicit, but some functions are non-existent, leading to compilation errors. This PR removes such problematic exports.
Somehow PR #2070 does not have a CI section on its page at https://github.com/wireapp/wire-server/pull/2070. It is possible the CI did not run for that PR. This might be due to our changes to the CI infrastructure that have been happening.
> Fix compilation errors in Spar modules

- docs/developer/servant.md
The link makes it easier to go to the mentioned `README.md`.
> Update servant.md: Add link to schema-profunctor README.md

- changelog.d/5-internal/gundeck-debug-logs
- services/gundeck/src/Gundeck/Push/Native.hs
- services/gundeck/src/Gundeck/Push/Websocket.hs
As described in https://wearezeta.atlassian.net/browse/SQPIT-834, there is an on-prem environment where we do not understand how notifications are lost or delayed.
To shed some light on this, this PR should accomplish two things:
- Ensure that all notification pushes (web and native) are logged.
- Ensure that no private / secret data is logged on level `Debug`.
With these in place, we can turn on the higher log level (`Debug`) when needed to investigate the issue further.
> More logs in gundeck - Make sure `Debug` log level may be used in production

- changelog.d/5-internal/move-internal-endpoints
- libs/wire-api/src/Wire/API/Routes/Internal/Cargohold.hs
- libs/wire-api/src/Wire/API/Routes/Internal/LegalHold.hs
- libs/wire-api/src/Wire/API/Routes/Public/Cargohold.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- libs/wire-api/src/Wire/API/Routes/Public/LegalHold.hs
- libs/wire-api/wire-api.cabal
- services/cargohold/src/CargoHold/API/Public.hs
- services/cargohold/src/CargoHold/Run.hs
- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/Run.hs
This moves internal endpoints to the `Internal` module hierarchy in `wire-api`, so that they are not included in the generated Swagger, and removes usages of servant-generic from Galley's internal API.
> Cleanup internal endpoints

- changelog.d/5-internal/brig-named-routes
- libs/wire-api/src/Wire/API/ErrorDescription.hs
- libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/Run.hs
This PR is the brig counterpart to #2022, i.e. it replaces uses of servant-generic in brig with `Named` routes, and splits the API tree into sections.
> Introduce named routes in brig

- changelog.d/1-api-changes/delete-self-name
- libs/wire-api/src/Wire/API/Swagger.hs
- libs/wire-api/src/Wire/API/User/Profile.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/test/integration/API/User/Account.hs
https://wearezeta.atlassian.net/browse/SQCORE-1167
> Brig: Delete `GET /self/name` endpoint

- changelog.d/3-bug-fixes/fix-respond-empty-swagger
- libs/wire-api/src/Wire/API/Routes/MultiVerb.hs
They appeared as empty arrays, which is the schema for the unit type.
Before this fix:
After this fix:
> Make RespondEmpty responses show up without a schema in swagger

- changelog.d/5-internal/prometheus-ignore-raw-responses
- libs/metrics-wai/src/Data/Metrics/Servant.hs
This PR makes the `servantPrometheusMiddleware` ignore all `ResponseRaw` responses. The implementation of wai and prometheus lead to `ResponseRaw` being tracked with `statusCode` `500` irrespective if the handler was successful or not (see documentation of `wai-middleware-prometheus`'s `ignoreRawResponses` or note `[Raw Response]` in the codebase).
This would remove all metrics for these endpoints, however looking at `observeSeconds` of `wai-middleware-prometheus` suggests that the status is optional, so maybe reporting duration without status is possible.
This PR is a followup to https://github.com/wireapp/wire-server/pull/2081 which lead to `cannon`'s `"await-notifications"` endpoint erroneously reporting 500s metrics.
This will also affect future potential future endpoints in `spar` …
> Prometheus: Exclude ResponseRaw responses from metrics

- libs/zauth/test/ZAuth.hs
- services/brig/test/integration/API/User/Auth.hs
- services/federator/test/unit/Test/Federator/InternalServer.hs
- services/federator/test/unit/Test/Federator/Options.hs
- services/federator/test/unit/Test/Federator/Remote.hs
- services/federator/test/unit/Test/Federator/Validation.hs
The TSFI's have changed for our BSI test-documentation. Because of this, we need to update the tags of some of the BSI testcases.
Updated the TSFI tags to the new values provided by atsec.
> refactor: Change TSFI's for BSI Testmapping

- changelog.d/3-bug-fixes/pr-2096
- libs/wire-api/package.yaml
- libs/wire-api/src/Wire/API/Team/Export.hs
- libs/wire-api/test/unit/Main.hs
- libs/wire-api/test/unit/Test/Wire/API/Team/Export.hs
- libs/wire-api/wire-api.cabal
- stack.yaml
https://wearezeta.atlassian.net/browse/SQSERVICES-1232
> SQSERVICES-1232 Prevent CSV Injection

- changelog.d/5-internal/nix-fix-build-shell
- dev-packages.nix
On some machines running `stack` from `direnv.nix` can lead to this error:
```
bash: /nix/store/xg6ilb9g9zhi2zg1dpi4zcp288rhnvns-glibc-2.30/lib/libc.so.6:
version `GLIBC_2.33' not found
(required by /nix/store/h22cdxm1252slxvb3qyfx1lnn85x5f0c-ncurses-6.2/lib/libncursesw.so.6)
```
This PR fixes this. See changes to [dev-packages.nix](https://github.com/wireapp/wire-server/pull/2105/files#diff-d3ac13b146a2d4234dbb2ef3d3f313425b08d8bd55be7df954820f6b9fcc8e9d) for details.
> Wrap stack with NIX_BUILD_SHELL set to LD_LIBRARY_PATH compatible shell

- changelog.d/6-federation/PR-2113
- charts/restund/Chart.yaml
- charts/sftd/Chart.yaml
In the M2 release, we should have included the tested SFT version 3.0.18 with Federation features, instead of the previous release 2.1.19. Jira ticket is FS-445
> Update SFTd to version 3.0.18

- changelog.d/6-federation/PR-2113
- charts/sftd/Chart.yaml
Reverting the update of sftd from 3.0.18 back to 2.1.19.
> Revert update of sftd from 3.0.18 back to 2.1.19

- changelog.d/0-release-notes/pr-2117
- docs/reference/config-options.md
- libs/galley-types/src/Galley/Types/Teams.hs
- libs/galley-types/test/unit/Test/Galley/Types.hs
- libs/wire-api/src/Wire/API/Team/Feature.hs
- services/galley/src/Galley/API/Teams/Features.hs
- services/galley/test/integration/API/Teams/Feature.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
- services/spar/test-integration/Util/Email.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1029
> SQSERVICES-1029 Refine team feature validate SAML emails

- dev-packages.nix
- nix/default.nix
- nix/overlay.nix
- nix/overlays/wire-server.nix
- nix/pkgs/cryptobox/default.nix
- nix/pkgs/zauth/default.nix
This fixes the cargoSha256 of zauth. It also moves cryptobox and zauth into their own files, to match nixpkgs style more, and adds `niv` to the dev environment.
> nix/pkgs: fix zauth build

- hack/helm_vars/wire-server/values.yaml.gotmpl
Follow-up to #2079. Just for cleanup, old and new parameter works as #2079 has a fallback to 'replicaCount', but going forward replicationFactor is the better naming.
> Stay consistent with #2079

- changelog.d/5-internal/specify-sending-to-deleted-legalhold-device
- services/galley/test/integration/API/Teams/LegalHold.hs
The test was a bit misleading about the assumptions regarding this.
> Specify how a message to a deleted legalhold device is refused to be sent

- build/ubuntu/Dockerfile.fast-intermediate
- build/ubuntu/Dockerfile.intermediate
- changelog.d/5-internal/cabal-builds
- services/brig/src/Brig/API.hs
This PR changes the way we build Docker images: `stack` is replaced by `cabal` to build all binaries.
This affects
- Docker images for PR pipelines (`Dockerfile.fast-intermediate`)
- Docker images for on-prem and other k8s-based deployments (`Dockerfile.intermediate`)
> Build ubuntu20 docker images with cabal instead of stack

- changelog.d/0-release-notes/api-version-prefix
- changelog.d/1-api-changes/api-version-endpoint
- charts/nginz/templates/conf/_nginx.conf.tpl
- charts/nginz/values.yaml
- libs/wire-api/package.yaml
- libs/wire-api/src/Wire/API/Routes/Version.hs
- libs/wire-api/src/Wire/API/Routes/Version/Wai.hs
- libs/wire-api/src/Wire/API/VersionInfo.hs
- libs/wire-api/wire-api.cabal
- services/brig/brig.cabal
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/Run.hs
- services/brig/test/integration/API/Version.hs
- services/brig/test/integration/Main.hs
- services/cannon/src/Cannon/Run.hs
- services/cargohold/src/CargoHold/Run.hs
- services/galley/src/Galley/Run.hs
- services/gundeck/src/Gundeck/Run.hs
- services/proxy/package.yaml
- services/proxy/proxy.cabal
- services/proxy/src/Proxy/Run.hs
- services/spar/src/Spar/Run.hs
This PR implements the bare minimum interface for [client API version negotiation](https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/555090587/Use+case+deciding+which+backend+API+version+to+use).
The changes in the nginz chart are based on https://github.com/zinfra/cailleach/pull/879 and result in the following [diff](https://gist.github.com/pcapriotti/1e0680ad99f5c128234ba0b876176542).
Tracked by https://wearezeta.atlassian.net/browse/FS-440.
> Minimal client API versioning

- charts/nginz/values.yaml
Add missing route to the new `/api-version` endpoint introduced in https://github.com/wireapp/wire-server/pull/2116.
> Add route for `/api-version` to nginz chart

- changelog.d/0-release-notes/pr-2138
- changelog.d/5-internal/pr-2138
- charts/galley/templates/configmap.yaml
- charts/galley/values.yaml
- docs/reference/cassandra-schema.cql
- docs/reference/config-options.md
- libs/galley-types/src/Galley/Types/Teams.hs
- libs/galley-types/test/unit/Test/Galley/Types.hs
- libs/wire-api/src/Wire/API/Event/FeatureConfig.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- libs/wire-api/src/Wire/API/Team/Feature.hs
- services/galley/galley.cabal
- services/galley/schema/src/Main.hs
- services/galley/schema/src/V60_TeamFeatureSndFactorPasswordChallenge.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Public/Servant.hs
- services/galley/src/Galley/API/Teams/Features.hs
- services/galley/src/Galley/Data/TeamFeatures.hs
- services/galley/test/integration/API/Teams/Feature.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1159
> Sqservices 1159 backend feature config 2nd factor for some password actions

- changelog.d/1-api-changes/api-version-endpoint
- libs/wire-api/src/Wire/API/Routes/Version.hs
- services/brig/brig.cabal
- services/brig/src/Brig/Run.hs
- services/brig/src/Brig/Version.hs
Make the `api-version` endpoint returns additional information about the backend:
- whether federation is supported (field `federation`);
- the federation domain (field `domain`).
Note that the federation domain is always set, even if federation is disabled.
This follows the proposal outlined in https://wearezeta.atlassian.net/wiki/spaces/CORE/pages/560234861/Deciding+whether+to+use+federation-aware+endpoints.
> Add extra information to `api-version` endpoint

- build/ubuntu/Dockerfile.deps
The crypto-cli tool is going to be used in integration test images for testing MLS functionality. See for example https://github.com/wireapp/wire-server/pull/2102.
> Add crypto-cli to the deps docker image

- changelog.d/5-internal/bump-aeson-amazonka
- libs/brig-types/brig-types.cabal
- libs/brig-types/package.yaml
- libs/schema-profunctor/package.yaml
- libs/schema-profunctor/schema-profunctor.cabal
- tools/stern/package.yaml
- tools/stern/stern.cabal
> Fix version bounds.

- changelog.d/5-internal/bump-aeson-amazonka
- charts/cargohold/templates/tests/cargohold-integration.yaml
- services/cargohold/src/CargoHold/AWS.hs
- services/cargohold/src/CargoHold/S3.hs
- services/cargohold/test/integration/API.hs
Regression introduced by #2153
> Fix: Ensure asset download URL uses S3DownloadEndpoint when provided

- changelog.d/5-internal/base64-cleanup
- libs/types-common/src/Data/Json/Util.hs
- libs/types-common/test/Test/Properties.hs
- libs/wire-api/src/Wire/API/MLS/KeyPackage.hs
- libs/wire-api/src/Wire/API/Message.hs
- libs/wire-api/src/Wire/API/ServantProto.hs
- libs/wire-api/test/golden/Test/Wire/API/Golden/Runner.hs
- services/galley/src/Galley/API/Message.hs
- services/galley/test/integration/API/Federation.hs
Clean up of `Base64ByteString`:
- Add a strict version and make it the default
- Clean up instances
- Export an unnamed schema for the raw underlying `ByteString`
- Add `*HttpApi` instances using `base64url`
> Base64 cleanup

- changelog.d/0-release-notes/nginz-upgrade
- changelog.d/1-api-changes/broadcast-qualified
- charts/nginz/values.yaml
- deploy/services-demo/conf/nginz/nginx.conf
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- services/galley/galley.cabal
- services/galley/package.yaml
- services/galley/src/Galley/API/Public/Servant.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Util.hs
This adds a qualified version of the message broadcast endpoint, with the same API as the one for normal messages. This makes it possible for the clients to uniformly use the qualified API for all possible message types.
Tracked by https://wearezeta.atlassian.net/browse/SQCORE-1257.
> Add qualified broadcast endpoint

- changelog.d/5-internal/api-version-endpoint
- services/brig/src/Brig/User/API/Auth.hs
- services/brig/test/integration/API/Version.hs
- services/brig/test/integration/Main.hs
- Add test for additional api-version info
- Comment about /access having to be unversioned, as requested [here](https://github.com/wireapp/wire-server/pull/2152#issuecomment-1049652961).
> Follow-up to `/api-version` changes

- changelog.d/3-bug-fixes/more-spar-tests
- changelog.d/5-internal/more-spar-tests
- libs/wire-api/src/Wire/API/Team/Feature.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
https://wearezeta.atlassian.net/browse/CS-742
With the tests in this PR, but without the changes, I get this error:
```
Failures:
test-integration/Test/Spar/Scim/UserSpec.hs:264:7:
1) WireIdPAPIV1.Spar.Scim.User, Create with TM invitation; then re-provision with SCIM, True
"<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\" \"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\"><html xml:lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\"><head>  <title>wire:sso:error:not-found</title>   <script type=\"text/javascript\">       const receiverOrigin = '*';       window.opener.postMessage({\"payload\":{\"errors\":[\"Could not find SAML credentials, and auto-provisioning is disabled.\"],\"label\":\"forbidden\"},\"type\":\"AUTH_ERROR\"}, receiverOrigin); …
```
> Fix spar user provisioning corner case

- changelog.d/2-features/mls
- docs/reference/cassandra-schema.cql
- libs/wire-api/src/Wire/API/MLS/Credential.hs
- libs/wire-api/src/Wire/API/MLS/KeyPackage.hs
- libs/wire-api/src/Wire/API/Routes/Internal/Brig.hs
- libs/wire-api/src/Wire/API/User/Client.hs
- services/brig/brig.cabal
- services/brig/schema/src/Main.hs
- services/brig/schema/src/V69_MLSKeyPackageRefMapping.hs
- services/brig/src/Brig/API/Internal.hs
- services/brig/src/Brig/API/MLS/KeyPackages.hs
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Data/Client.hs
- services/brig/src/Brig/Data/MLS/KeyPackage.hs
- services/brig/test/integration/API/MLS.hs
- services/galley/src/Galley/Intra/User.hs
This PR implements a mapping of key package ref to qualified clients. The corresponding cassandra table also contains fields to hold the qualified conversation ID of where the key package is being used. These fields are not set for the moment, but they will play a role when validating incoming handshake messages.
This also adds an internal brig endpoint to dereference a key package. This is only used in tests for the moment, but it will later be used by galley to resolve a key package ref to a user and client ID.
Part of https://wearezeta.atlassian.net/browse/FS-436.
**Note**: this contains a commit from https://github.com/wireapp/wire-server/pull/2170. Rebase it away before merging.
> Map claimed key packages to clients

- changelog.d/1-api-changes/strip-ibis-paths
- charts/nginz/templates/conf/_nginx.conf.tpl
- charts/nginz/values.yaml
This makes it possible to access external API endpoints not implemented in wire-server with a version prefix.
> Strip versions from ibis paths

- services/federator/test/integration/Test/Federator/InwardSpec.hs
- services/federator/test/unit/Test/Federator/Validation.hs
- services/galley/test/integration/API.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
> chore: add verbose explanation and test mapping for guest links (FS-488)

- changelog.d/0-release-notes/gc-spar-schema
- changelog.d/5-internal/gc-spar-schema
- docs/reference/cassandra-schema.cql
- services/spar/schema/src/Main.hs
- services/spar/schema/src/V16.hs
- services/spar/spar.cabal
- services/spar/src/Spar/Data.hs
> Drop deprecated table spar.scim_external_ids.

- changelog.d/5-internal/more-test-labels
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Teams.hs
https://wearezeta.atlassian.net/browse/FS-488
> More test labels [skip ci]

- hack/bin/serve-charts.sh
The script for serving local Helm charts uses Python's standard library HTTP server; however, Python 2 is decreasingly available on many platforms, so we should use Python 3 instead, which has equivalent functionality. No functional changes.
---
> Update Helm chart serving script for Python 3

- changelog.d/3-bug-fixes/fix-saml-thing
- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
- services/spar/test-integration/Util/Scim.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1376
I recommend reading this PR commit-by-commit.
> Fix: spar user import to SCIM

- build/ubuntu/Dockerfile.deps
The libssl-dev library is now needed in order to build `core-crypto` in the deps image.
> Install libssl-dev for core-crypto in ubuntu deps

- changelog.d/3-bug-fixes/pr-2211
- services/galley/src/Galley/API/Update.hs
- services/galley/test/integration/API.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1385
> SQSERVICES-1385-non-group-admins-should-not-be-able-to-create-guest-links

- changelog.d/5-internal/pr-2214
- libs/wire-api/src/Wire/API/User/Scim.hs
- services/spar/src/Spar/Intra/Brig.hs
- services/spar/src/Spar/Intra/BrigApp.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Test/Spar/DataSpec.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
- services/spar/test-integration/Util/Core.hs
- services/spar/test-integration/Util/Scim.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1376
- clarify semantics of internal functions
- crank up logging of SCIM CRUD API
- remove redundant log entries
- improve test coverage
> Spar debugging

- changelog.d/2-features/pr-2205
- charts/galley/values.yaml
- libs/galley-types/src/Galley/Types/Teams.hs
- libs/wire-api/src/Wire/API/Team/Feature.hs
- services/brig/test/integration/API/User/Auth.hs
- services/brig/test/integration/API/User/Client.hs
- services/brig/test/integration/API/User/Util.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Teams/Feature.hs
- services/spar/test-integration/Test/Spar/Scim/AuthSpec.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1300
> SQSERVICES-1300-be-lock-2nd-factor-password-challenge-team-feature-as-default

- changelog.d/5-internal/refactor-federated-conversation-actions
- changelog.d/6-federation/refactor-federated-conversation-actions
- libs/wire-api-federation/package.yaml
- libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs
- libs/wire-api-federation/test/Test/Wire/API/Federation/Golden/ConversationUpdate.hs
- libs/wire-api-federation/test/golden/testObject_ConversationUpdate1.json
- libs/wire-api-federation/test/golden/testObject_ConversationUpdate2.json
- libs/wire-api-federation/wire-api-federation.cabal
- libs/wire-api/src/Wire/API/Conversation.hs
- libs/wire-api/src/Wire/API/Conversation/Action.hs
- libs/wire-api/test/unit/Test/Wire/API/Roundtrip/Aeson.hs
- services/galley/galley.cabal
- services/galley/package.yaml
- services/galley/src/Galley/API/Action.hs
- services/galley/src/Galley/API/Federation.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/API/Util.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Federation.hs
- services/galley/test/integration/API/MessageTimer.hs
- services/galley/test/integration/API/Roles.hs
- services/galley/test/integration/API/Util.hs
Use a tagged [existential type](https://github.com/wireapp/wire-server/pull/2173/files#diff-3c203a61ccca5fe1f578d7518b2990e3fa347690624cc9cc5e4b678fc71df441R96) and a [type family](https://github.com/wireapp/wire-server/pull/2173/files#diff-c79e1b19d4681c1519e5f54d0fc5609df659a2168f84d082f31225b8824636f6R88) to provide a dedicated list of effects for each conversation action.
Previously, actions were represented by a [sum type](https://github.com/wireapp/wire-server/pull/2173/files#diff-3c203a61ccca5fe1f578d7518b2990e3fa347690624cc9cc5e4b678fc71df441L38). The replacement is a (logical) pair of a [tag](https://github.com/wireapp/wire-server/pull/2173/files#diff-3c203a61ccca5fe1f578d7518b2990e3fa347690624cc9cc5e4b678fc71df441R45) and an accompanying [action …
> Refactor conversation actions to enable dedicated effect sets for each action

- changelog.d/2-features/FS-513-restund-dtls-revert-sft-bump
- charts/sftd/Chart.yaml
Reverts temporary bump of sftd to 3.1.3
> Revert "sftd chart: upgrade to 3.1.3 (#2227)"

- services/galley/test/integration/API.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-609
This PR only contains an integration test that verifies that the backend behavior is correct. The actual fix for the bug needs to be done in the frontend.
> SQSERVICES-609-backend-disallow-guests-and-services-on-conversation-doesnt-revoke-invite-link

- changelog.d/5-internal/nix-hls-pin-direnv
- hack/bin/nix-hls.sh
This fixes a problem where an older version of direnv would make the script crash
> Pin direnv version in nix-hls.sh script

- changelog.d/5-internal/remove-deb-targets
- services/brig/Makefile
- services/cannon/Makefile
- services/cargohold/Makefile
- services/galley/Makefile
- services/gundeck/Makefile
- services/proxy/Makefile
- services/spar/Makefile
- tools/api-simulations/Makefile
- tools/stern/Makefile
The invocations of `makedeb` have been moved to cailleach:
https://github.com/zinfra/cailleach/commit/d5c787e3243aa6367cba35fb121fdfbe0edb7692
schema documentation.
> Remove unused "dist" debian Makefile targets

- changelog.d/2-features/pr-2207
- services/brig/src/Brig/IO/Intra.hs
- services/brig/src/Brig/Provider/API.hs
- services/brig/test/integration/API/Provider.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Teams/Features.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1375
> SQSERVICES-1375-block-bot-api-if-2-fa-is-enabled

- changelog.d/5-internal/cannon-remove-wai
- services/cannon/cannon.cabal
- services/cannon/package.yaml
This completes the servantification of cannon.
Tracked by https://wearezeta.atlassian.net/browse/SQCORE-1176.
> Remove wai-routing dependency from cannon

- services/brig/test/integration/API/Provider.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Teams/Features.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1375
The bot API should be blocked if the 2nd FA team feature is enabled.
This is a follow-up PR of https://github.com/wireapp/wire-server/pull/2207. This one contains an additional integration test for the `GET /bot/conversation` endpoint in galley.
If 2FA is enabled for the team the conversation belongs to, then this endpoint should return `403 access-denied`.
The `guardSecondFactorDisabled` handler needed to be changed to get the TeamId from the conversation.
> SQSERVICES 1375 - Follow up (integration test for `GET /bot/conversation`)

- CHANGELOG.md
Looking for feedback on the format. Should I put it on a separate line? Something else?
> add version information to the dates in the changelog

- changelog.d/5-internal/use-local-consistency
- services/brig/src/Brig/Data/Client.hs
This should avoid the use of Quorum consistency under the hood.
> Use local serial consistency for LWT

- .github/workflows/ci.yml
- changelog.d/5-internal/cachix
Pushing to cachix failed silently because the credentials were not provided. This PR makes use of a github environment that contain the auth token and signing key required.
> github workflows: use environment

- changelog.d/5-internal/brig-no-unliftio
- services/brig/src/Brig/API/Client.hs
- services/brig/src/Brig/API/Connection.hs
- services/brig/src/Brig/API/Federation.hs
- services/brig/src/Brig/API/Handler.hs
- services/brig/src/Brig/API/Internal.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/API/Util.hs
- services/brig/src/Brig/AWS.hs
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Data/Client.hs
- services/brig/src/Brig/Data/Connection.hs
- services/brig/src/Brig/Federation/Client.hs
- services/brig/src/Brig/IO/Intra.hs
- services/brig/src/Brig/IO/Journal.hs
- services/brig/src/Brig/InternalEvent/Process.hs
- services/brig/src/Brig/Provider/API.hs
- services/brig/src/Brig/Provider/RPC.hs
- services/brig/src/Brig/Queue.hs
- services/brig/src/Brig/Queue/Stomp.hs
- services/brig/src/Brig/RPC.hs
- services/brig/src/Brig/Run.hs
- services/brig/src/Brig/User/API/Handle.hs
As part of effort to introduce Polysemy to Brig, this PR removes the `MonadUnliftIO` instance for the App monad in Brig. It introduces no change in the behavior of Brig.
> [Polysemy] Remove MonadUnliftIO for Brig's AppT

- changelog.d/5-internal/faster-reindex
- services/brig/src/Brig/User/Search/Index.hs
Reindexing goes faster with bigger pages. Reading 1000 users in memory isn't a
problem either. This is not an optimized number, just based on 1 experiment
which showed that 1000 is better than 100. Memory consuption of the `brig-index`
process in that experiment was of the order of 100 kb.
> Increase page size read from cassandra from 100 to 1000

- changelog.d/5-internal/brig-client-reauth
- services/brig/src/Brig/API/Client.hs
- services/brig/src/Brig/API/Internal.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/Data/Client.hs
- services/galley/src/Galley/Effects/BrigAccess.hs
- services/galley/src/Galley/Intra/Client.hs
- services/galley/src/Galley/Intra/Effects.hs
This PR changes the internal Brig endpoint for adding new clients to make it skip the check for the need to re-authenticate. This is useful for integration tests that need to set up a number of clients.
Answering comments by @fisx on a similar commit in #2247:
> Maybe it would be good to somehow rename the new `Brig.API.Client.addClient` to `addClientUnsafe` (as it allows to set a bad policy), and keep `addClient` with the same interface and behavior as before?
I have done that, but called the unsafe function `addClientWithReAuthPolicy` instead, because "unsafe" usually means something else in Haskell.
> Have you double-checked that we're not calling the internal end-point from some handler in galley in production, and rely on the authentication taking place in brig there? Maybe you …
> Skip reauth when adding clients internally

- changelog.d/5-internal/SQSERVICES-1080-servantify-galley_teams-1
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Teams.hs
JIRA: https://wearezeta.atlassian.net/browse/SQSERVICES-1080
No endpoints were supposed to be added or renamed, but they are now specified in servant type instead of wai-routes paths, so this should be a point of review.
> Servantify Galley Teams [1/3]

- changelog.d/0-release-notes/mls-message-endpoint
- charts/nginz/values.yaml
- deploy/services-demo/conf/nginz/nginx.conf
- services/galley/src/Galley/API/Public/Servant.hs
PR #2247 missed to add the `/mls/messages` path to an nginz chart.
This PR also includes a cosmetic change to an unrelated Haskell module.
This is part of https://wearezeta.atlassian.net/browse/FS-207.
> [FS-207] Add MLS Message Endpoint to nginz

- changelog.d/5-internal/brig-search-tests
- services/brig/test/integration/API/Search.hs
This PR updates the test suite with hopes of improving readability:
- test case description: use consistent formulation in active voice
- number similar test cases across different settings with a roman numeral
- rename variables in test code to match the names of teams in description: `teamA` and `teamB`
This PR also fixes a test case and adds a test case:
- fix test case description: "team A member cannot find team B member by display name or exact handle". The previous description in passive voice was incorrect
- fix test case "II.  non-team user can find team A member by exact handle": handle was not searched
- add test case:
- before: "any team user cannot find any non-team user by display name"
- after:  "any team user cannot find any non-team user by display name or exact handle"
> Improve readability user search test cases

- changelog.d/3-bug-fixes/FS-631-fix-search-visibility
- services/brig/src/Brig/User/API/Search.hs
- services/brig/test/integration/API/Search.hs
https://wearezeta.atlassian.net/browse/FS-631
> Fix bug: User search endpoint hides exact handle results in SearchVisibilityNoNameOutsideTeam setting

- changelog.d/3-bug-fixes/pr-2281
- tools/stern/src/Stern/Intra.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1193
> Fix: SQSERVICES-1193-stern-backoffice-updating-email-address-for-user-fails-with-status-500

- changelog.d/5-internal/error-middleware
- docs/developer/servant.md
- libs/wai-utilities/src/Network/Wai/Utilities/Server.hs
- services/brig/src/Brig/API/Handler.hs
- services/brig/test/integration/API/User/Client.hs
- services/galley/src/Galley/App.hs
This PR adds a bit of developer documentation regarding how errors are propagated from a service, through the middleware, and to the client.
It also removes some unnecessary duplication of error logs and simplifies the way errors are thrown in the main `Handler → Servant.Handler` natural transformation.
> Document error handling and logging

- changelog.d/5-internal/SQSERVICES-1078-servantify-galley_teams-2
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Teams.hs
JIRA:
* https://wearezeta.atlassian.net/browse/SQSERVICES-1074 (search visibiliy)
* https://wearezeta.atlassian.net/browse/SQSERVICES-1078
> Servantify Galley Teams [2/2]

- changelog.d/5-internal/SQSERVICES-1479-nginx
- services/nginz/Dockerfile
- services/nginz/Makefile
https://wearezeta.atlassian.net/browse/SQSERVICES-1479
> chore: update nginx to latest stable version (SQSERVICES-1479)

- changelog.d/2-features/mls
- libs/wire-api/src/Wire/API/MLS/Credential.hs
- libs/wire-api/src/Wire/API/Routes/Internal/Brig.hs
- services/brig/src/Brig/API/Internal.hs
- services/galley/src/Galley/API/MLS/Message.hs
- services/galley/src/Galley/Effects/BrigAccess.hs
- services/galley/src/Galley/Intra/Client.hs
- services/galley/src/Galley/Intra/Effects.hs
- services/galley/test/integration/API/MLS.hs
This makes it possible to add users to an MLS conversation even if some of their clients don't have MLS public keys (and hence key packages) set up.
> Internal brig API: only return MLS clients

- changelog.d/2-features/mls
- changelog.d/5-internal/mls-tests
- libs/wire-api/src/Wire/API/Conversation/Action.hs
- libs/wire-api/src/Wire/API/Conversation/Action/Tag.hs
- libs/wire-api/src/Wire/API/Conversation/Protocol.hs
- libs/wire-api/src/Wire/API/MLS/Message.hs
- libs/wire-api/wire-api.cabal
- services/galley/galley.cabal
- services/galley/src/Galley/API/Action.hs
- services/galley/src/Galley/API/MLS/Message.hs
- services/galley/src/Galley/API/Message.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/API/Util.hs
- services/galley/src/Galley/Cassandra/Conversation.hs
- services/galley/src/Galley/Data/Conversation.hs
- services/galley/src/Galley/Data/Conversation/Types.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/MLS.hs
- services/galley/test/integration/API/MLS/Util.hs
- services/galley/test/unit/Test/Galley/Mapping.hs
Make sure that clients cannot send a proteus message to an MLS conversation, or add and remove users directly using the `/conversations/.../members` endpoints. Add corresponding tests.
Tracked by https://wearezeta.atlassian.net/browse/FS-533.
> Proteus actions on MLS conversations should fail

- changelog.d/2-features/mls
- libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
- services/brig/src/Brig/API/MLS/KeyPackages.hs
- services/brig/test/integration/API/MLS.hs
Clients need to claim key packages for other clients of the same user, but never their own. This adds a `skip_own` query parameter to the key package claiming endpoint, which can be used to prevent wasting a key package for the requesting client.
Tracked by https://wearezeta.atlassian.net/browse/FS-527.
> Add `skip_own` param to MLS kp claiming endpoint

- changelog.d/2-features/tolerate-redis-down
- libs/types-common/src/Util/Test.hs
- libs/wai-utilities/package.yaml
- libs/wai-utilities/src/Network/Wai/Utilities/MockServer.hs
- libs/wai-utilities/wai-utilities.cabal
- services/cargohold/test/integration/API/Util.hs
- services/federator/src/Federator/MockServer.hs
- services/federator/test/unit/Test/Federator/Client.hs
- services/federator/test/unit/Test/Federator/Remote.hs
- services/gundeck/gundeck.cabal
- services/gundeck/package.yaml
- services/gundeck/src/Gundeck/Push.hs
- services/gundeck/src/Gundeck/Run.hs
- services/gundeck/test/integration/API.hs
- services/gundeck/test/integration/Main.hs
- services/gundeck/test/integration/TestSetup.hs
- services/gundeck/test/integration/Util.hs
Right now, if redis is down, the lookup of presences which happens before the storage of notifications in cassandra, leads to messages unable to be persisted in the case of redis downtime. That's not necessary. This PR moves the "lookup presence location in redis" part further down in the "pushAll" function, making gundeck's code more tolerant to redis downtimes. An integration test is provided (using a tcp proxy to redis) to cover this case, which is can be seen failing with the (equivalent) old code in https://github.com/wireapp/wire-server/pull/2295/commits/b45a503aa04794b5ff46eb9713c47baa8107d610.
> Gundeck: Avoid dropping messages when redis is down

- changelog.d/5-internal/random-effect
- libs/polysemy-wire-zoo/package.yaml
- libs/polysemy-wire-zoo/polysemy-wire-zoo.cabal
- libs/polysemy-wire-zoo/src/Wire/Sem/Random.hs
- libs/polysemy-wire-zoo/src/Wire/Sem/Random/IO.hs
- services/spar/spar.cabal
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/App.hs
- services/spar/src/Spar/CanonicalInterpreter.hs
- services/spar/src/Spar/Scim.hs
- services/spar/src/Spar/Scim/Auth.hs
- services/spar/src/Spar/Scim/User.hs
The PR moves the Random effect from Spar to the polysemy-wire-zoo library as it is not Spar-specific and it will be used in Brig too.
> [Polysemy] Move the Random Effect from Spar to polysemy-wire-zoo

- changelog.d/5-internal/brig-fun-cleanup
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/IO/Intra.hs
This cleans up a couple of unsafe functions.
> [Brig] Clean up a couple of unsafe functions

- changelog.d/5-internal/pr-2301
- tools/stern/src/Stern/API.hs
- tools/stern/src/Stern/Intra.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1480
> SQSERVICES-1480-be-add-flag-for-validation-email-to-users-uid-email-in-backoffice-stern

- build/ubuntu/Dockerfile.builder
- build/ubuntu/Dockerfile.prebuilder
- changelog.d/5-internal/remvove-stack
This PR removes the `stack` tool from the build docker images.
https://wearezeta.atlassian.net/browse/BE-560
> Remove stack from builder images

- changelog.d/3-bug-fixes/nginz-access-control
- charts/nginz/templates/conf/_nginx.conf.tpl
Due to an access control quirk, clients connecting to nginz over a listener which has proxy protocol enabled may be able to bypass the IP address access control list and access the `/vts` metrics endpoint, which is otherwised considered internal. This change prevents clients connected via proxy protocol from accessing the metrics endpoint.
> Prevent PROXY protocol clients from accessing metrics endpoint.

- changelog.d/5-internal/add-gnused
- dev-packages.nix
Our CI scripts depend on sed being in the direnv.
> Add "sed" to direnv

- changelog.d/5-internal/wire-docs-pdf
- docs/Makefile
- docs/nix/default.nix
This PR
- adds latex back to the build env of the docs.
- adds publishing of the pdf to docs.wire.com/main.pdf when running "make push"
Context: https://github.com/wireapp/wire-server/pull/2258#issuecomment-1109718668
> docs: add latex to docs and publish pdf if exists

- changelog.d/5-internal/fix-versioned-metrics
- services/brig/src/Brig/Run.hs
- services/cannon/src/Cannon/Run.hs
- services/cargohold/src/CargoHold/Run.hs
- services/galley/src/Galley/Run.hs
- services/gundeck/src/Gundeck/Run.hs
- services/proxy/src/Proxy/Run.hs
- services/spar/src/Spar/Run.hs
This makes sure that every other middleware sees the rewritten (unversioned) path. In particular, the prometheus middleware will now only see paths it knows about, which prevents it from reporting "N/A" as the path.
> Fix versioned metrics

- .github/workflows/ci.yml
- changelog.d/5-internal/remove-ormolu-gh-action
This job is duplicated by a job running in concourse. Since the backend team decided to favor running jobs in concourse over github let's remove it here. The concourse job has been updated to also run in the direnv: https://github.com/zinfra/cailleach/pull/1033
> Remove oromolu Github action

- docs/src/release-notes.rst
This PR converts several links in markdown-format to the correct rst-format to fix the rendering on docs.wire.com
> Fix markdown links in RST changelog

- changelog.d/4-docs/pr-2329
- docs/src/how-to/install/index.rst
- docs/src/how-to/install/team-feature-settings.md
https://wearezeta.atlassian.net/browse/SQSERVICES-1500
> [DOC] SQSERVICES-1500 Document 2nd Factor Password Challenge Team Feature

- changelog.d/4-docs/pr-2337
- docs/src/how-to/install/web-app-settings.md
https://wearezeta.atlassian.net/browse/SQSERVICES-1503
render:
> SQSERVICES-1503-doc-1-1

- changelog.d/4-docs/pr-2338
- docs/src/how-to/install/web-app-settings.md
https://wearezeta.atlassian.net/browse/SQSERVICES-1506
rendered:
> SQSERVICES-1506-doc-1-5

- changelog.d/5-internal/add-python3-dev-dependency
- dev-packages.nix
Without this dependency `./hack/bin/serve-charts.sh` fails:
```
make clean-charts && make charts-serve DOCKER_TAG=4.7.1 HELM_SEMVER=0.0.42
rm -rf .local/charts
./hack/bin/copy-charts.sh wire-server
copied /home/sven/src/wire-server/charts/wire-server (and its local dependencies) to /home/sven/src/wire-server/.local/charts/wire-server
./hack/bin/set-wire-server-image-version.sh 4.7.1
./hack/bin/set-helm-chart-version.sh "wire-server" 0.0.42
./hack/bin/copy-charts.sh databases-ephemeral
copied /home/sven/src/wire-server/charts/databases-ephemeral (and its local dependencies) to /home/sven/src/wire-server/.local/charts/databases-ephemeral
./hack/bin/set-wire-server-image-version.sh 4.7.1
./hack/bin/set-helm-chart-version.sh "databases-ephemeral" 0.0.42
./hack/bin/copy-charts.sh fake-aws …
```
> Add python3 dependency to nix development environment

- changelog.d/4-docs/pr-2340
- docs/src/how-to/associate/custom-backend-for-desktop-client.rst
https://wearezeta.atlassian.net/browse/SQSERVICES-1504
render (outdated):
> SQSERVICES-1504-doc-1-3

- changelog.d/3-bug-fixes/fix-duplicated-enable-payment-flag-in-helm-charts
- charts/team-settings/templates/deployment.yaml
If the `FEATURE_ENABLE_PAYMENT` feature flag is set by `envVars`, do not render it again. Otherwise, we might end up in confusing cases like: The flag was set to `true`, but it's additionally rendered with a default to `false`.
I gave the `envVars` entry priority because it's used many times in *cailleach* and my gut feeling tells me that it would be confusing to override an explicitly set flag with an opposite value.
Example from k8s:
```yaml
kubectl get pod -n wire team-settings-598ddf7956-r6jfn -o yaml
...
spec:
containers:
- env:
- name: NODE_PORT
value: "8080"
- name: APP_BASE
value: https://teams.secusmart-column-1a.wire.link/
- name: BACKEND_REST
value: https://nginz-https.secusmart-column-1a.wire.link
- name: BACKEND_WS
value: wss://nginz-ssl.secusmart-column-1a.wire.link
- name: …
```
> Prevent duplicated rendering of FEATURE_ENABLE_PAYMENT

- deploy/services-demo/conf/gundeck.demo.yaml
Actually, this redis runs in "master" mode on that port (from docker-compose). There are other redises launched on other parts that run in cluster mode.
Redis part of cluster:
https://github.com/wireapp/wire-server/blob/develop/deploy/dockerephemeral/docker-compose.yaml#L98
(ports 6373 - 6378)
Redis standalone in master mode on port 6379
https://github.com/wireapp/wire-server/blob/develop/deploy/dockerephemeral/docker-compose.yaml#L77
Sorry for forgetting to do this earlier (to add config to this file). The PR #2339 is doing the wrong thing, any use of gundeck and messaging on the demo setup would fail.
> Fixup for #2339

- docs/src/how-to/install/web-app-settings.md
This PR attempts to improve the feature flag documentation from #2336 on when CBR is already used and when not.
> fixup: SQSERVICES-1507-doc-1-11

- changelog.d/6-federation/receipt-mode
- libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs
- libs/wire-api-federation/src/Wire/API/Federation/Error.hs
- libs/wire-api/src/Wire/API/Error/Galley.hs
- libs/wire-api/src/Wire/API/Routes/Public/Util.hs
- libs/wire-api/src/Wire/API/Team/Permission.hs
- services/galley/src/Galley/API/Action.hs
- services/galley/src/Galley/API/Federation.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Federation.hs
- services/galley/test/integration/API/Util.hs
This PR is the first in a series of PR that add missing implemention of conversation actions when the admin is remote (i.e. the admin is on a backend that doesn't own the conversation).
This PR implements functionality for the receipt mode update in the Client API
```
PUT /conversations/:domain/:conversation/receipt-mode
```
when `:domain` is a domain that is remote to the user calling the endpoint.
This PR also introduces a Federation API RPC `update-conversation` which is used by a backend to request a conversation update on the backend that owns the conversation. The requested action is any one of the supported conversation actions:
- `ConversationJoin`
- `ConversationLeave`
- `ConversationRemoveMembers`
- `ConversationMemberUpdate`
- `ConversationDelete`
- `ConversationRename`
- …
> Implement remote admin action: Update receipt mode

- docs/legacy/developer/dependencies.md
Closes https://github.com/wireapp/wire-server/pull/2318.
This copies over the instructions we have in cailleach on how to install Nix/Direnv, configure the binary cache, and how to handle git submodules.
There's still a bunch of leftover instructions on how to provide various tools on various distros, we might want to remove them in a followup PR.
> docs: more detailled instructions on how to set up Nix/Direnv, and our binary cache.

- .github/workflows/ci.yml
- dev-packages.nix
There's people with Mac boxes who want to iterate on `wire-server`. Being able to use Nix, have the dev-env available in a binary cache, and CI ensure there's no regressions is highly valuable, so worth the additional CI minutes spent.
> nix: build macos dev-env again

- docs/src/release-notes.rst
This PR fixes several references in the release notes to newly available locations and changed locations of internal documentation (moved from `/docs/reference/` to `/docs/legacy/reference/`)
> fixup: update links to new changed targets

- changelog.d/3-bug-fixes/nginz-access-control
- charts/nginz/templates/conf/_nginx.conf.tpl
This is the same as #2307, with the typo fixed. I've actually tested that this change is syntactically correct in a development environment this time, so hopefully this doesn't break things again.
> Prevent PROXY protocol clients accessing metrics endpoint, take 2.

- .github/workflows/ci.yml
- changelog.d/5-internal/disable-mac-builds
Disabling mac builds (which are [10x more expensive](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#minute-multipliers)) because nobody in the team needs these caches atm.
> Github Actions: disable mac builds

- docs/src/how-to/install/web-app-settings.md
This PR intends to adjust one detail from #2338, as this flag only has an effect on windows users.
> fixup: SQSERVICES-1506-doc-1-5

- Makefile
- changelog.d/5-internal/buildah-cabal
- docs/legacy/developer/how-to.md
- hack/bin/buildah-clean.sh
- hack/bin/buildah-compile.sh
- hack/bin/buildah-inside.sh
- hack/bin/buildah-make-images.sh
- hack/bin/cabal-install-artefacts.sh
We recently removed `stack` from the builder images. This PR changes the buildah-based build scripts to use cabal instead of stack.
I manually tested `make buildah-docker`
> buildah-docker: use cabal instead of stack

- Makefile
- changelog.d/5-internal/makefile-msg
There's an outdated comment on using Stack instead of Cabal in a make target. This patch simply updates the comment in the main `Makefile`.
> Fix a comment in a Makefile target

- CHANGELOG.md
- changelog.d/0-release-notes/webapp-upgrade
- charts/webapp/values.yaml
* Upgrade webapp version to 2022-05-04-production.0-v0.29.7-0-a6f2ded (#2302)
> Release 2022-05-04 - (expected chart version 4.11.0)

- docs/src/release-notes.rst
> [docs] release notes chart release 4.11.0 (2022-05-04)

- changelog.d/2-features/charts-brig-new-settings
- changelog.d/2-features/no-aws-creds
- charts/brig/templates/configmap.yaml
- charts/brig/templates/deployment.yaml
- charts/brig/templates/secret.yaml
- charts/brig/templates/serviceaccount.yaml
- charts/brig/values.yaml
- charts/cargohold/templates/deployment.yaml
- charts/cargohold/templates/secret.yaml
- charts/cargohold/templates/serviceaccount.yaml
- charts/cargohold/values.yaml
- charts/galley/templates/configmap.yaml
- charts/galley/templates/deployment.yaml
- charts/galley/templates/secret.yaml
- charts/galley/templates/serviceaccount.yaml
- charts/galley/values.yaml
- charts/gundeck/templates/configmap.yaml
- charts/gundeck/templates/deployment.yaml
- charts/gundeck/templates/secret.yaml
- charts/gundeck/templates/serviceaccount.yaml
- charts/gundeck/values.yaml
- charts/nginz/values.yaml
- hack/helm_vars/wire-server/values.yaml.gotmpl
charts/{brig,cargohol,galley,gundeck}: Allow not configuring AWS credentials and allow using a special service account.
This way, when operating wire in AWS cloud either instance profiles or IAM role attached to a service account can be used to communicate with AWS.
Allow new configurations in the brig chart:
* `config.emailSMS.user.invitationUrl`
* `config.emailSMS.team.tInvitationUrl`
* `config.emailSMS.team.tActivationUrl`
* `config.emailSMS.team.tCreatorWelcomeUrl`
* `config.emailSMS.team.tMemberWelcomeUrl`
* `config.setProviderSearchFilter`
* `config.setWhitelist`
* `config.setFeatureFlags`
* `config.setCustomerExtensions`
If any values in config.emailSMS.team are specified, all must be specified.
Allow new configurations in the gundeck chart:
* `config.perNativePushConcurrency`
* …
> Adapt wire-server charts so they can be used to run wire cloud

- docs/src/how-to/scim/index.rst
- docs/src/how-to/single-sign-on/index.rst
Accidentally added extra colons to the reference links.
> Removed extra colons from new doc references.

- README.md
Avoids having the manual redirect. Not sure how much sense it makes, if it's indeed a legacy document?
> Updated link to dependencies.

- changelog.d/4-docs/list-connections
- libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- libs/wire-api/src/Wire/API/Routes/Public/Util.hs
Copied pagination docs from the conversation listing endpoint.
> Add pagination docs to `list-connections`

- changelog.d/6-federation/fix-mls-client-assertions
- services/galley/test/integration/API/MLS.hs
- services/galley/test/integration/API/MLS/Util.hs
- services/galley/test/integration/API/Util.hs
Fix assertion (should be 404), remove duplicated `addClient` function and a redundant test.
> Fix assertion in testWelcomeNoKey

- Makefile
- changelog.d/5-internal/add-shellcheck-make-target
- dev-packages.nix
It lints all shell scripts that are not excluded, i.e. new ones and old ones without issues. Excluded are those that currently have issues. They should be fixed on a step-by-step basis. This conservative/careful approach is necessary due to shell scripts having neither a type checker nor tests. "Surprises" should be avoided, especially as they might
appear in stressful situations.
This PR supersedes https://github.com/wireapp/wire-server/pull/2310 . In that PR I learned that even simple looking quotes may lead to awful errors.
https://wearezeta.atlassian.net/browse/SQPIT-279
schema`** to update the cassandra schema documentation.
> Add ShellCheck linter target

- changelog.d/2-features/mls
- libs/wire-api-federation/src/Wire/API/Federation/API/Brig.hs
- libs/wire-api/src/Wire/API/MLS/KeyPackage.hs
- services/brig/brig.cabal
- services/brig/src/Brig/API/Federation.hs
- services/brig/src/Brig/API/MLS/KeyPackages.hs
- services/brig/src/Brig/Data/MLS/KeyPackage.hs
- services/brig/test/integration/API/Federation.hs
- services/brig/test/integration/API/MLS.hs
- services/brig/test/integration/API/MLS/Util.hs
- services/brig/test/integration/Federation/End2end.hs
This PR implements remote key package claims. It simply adds a new federation RPC for claiming remote key packages, and wires it up to the public API. When a remote key package is claimed, the corresponding key package ref mapping is established, similarly to the local case.
Tracked by: https://wearezeta.atlassian.net/browse/FS-508.
> Implement remote key package claims

- changelog.d/5-internal/pr-2309
- libs/galley-types/src/Galley/Types/Teams.hs
- libs/wire-api/src/Wire/API/Error/Galley.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- libs/wire-api/src/Wire/API/Swagger.hs
- libs/wire-api/src/Wire/API/Team.hs
- libs/wire-api/src/Wire/API/Team/Member.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Public/Servant.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/test/integration/API/Teams.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1012
> SQSERVICES-1012-backend-servantify-galley-team-member-api

- changelog.d/5-internal/log-exceptions
- services/brig/src/Brig/API/Handler.hs
- services/galley/src/Galley/App.hs
IO exceptions in brig and galley were previously just caught by the "error handling" middleware, resulting in a generic "Server Error" log message, which was useless for diagnosing the actual cause of the error. This PR adds logging for IO exceptions in Brig and Galley. The actual response returned in case of IO exceptions is unaffected.
> Log IO exceptions in Brig and Galley

- changelog.d/5-internal/refactor-turn-discovery
- services/brig/brig.cabal
- services/brig/package.yaml
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Calling.hs
- services/brig/src/Brig/Calling/API.hs
- services/brig/src/Brig/Effects/Delay.hs
- services/brig/src/Brig/Run.hs
- services/brig/test/integration/API/Calling.hs
- services/brig/test/integration/Util.hs
- services/brig/test/unit/Test/Brig/Calling.hs
- services/brig/test/unit/Test/Brig/Effects/Delay.hs
Two changes:
1. Start TURN discovery only when the app starts
Instead of starting it when the `Env` is created. This aligns the service
discovery of TURN with that of SFT. In next commits, SRV based discovery for
TURN will be implemented.
2. Refactor SFT SRV Record discovery to make it more generic and reusable
> Brig: Prepare for TURN Discovery using SRV records

- changelog.d/5-internal/develop
- services/federator/src/Federator/Monitor/Internal.hs
- services/federator/test/unit/Test/Federator/Monitor.hs
Instead of generating `String` values, which might be invalid for the file system encoding in some locales, generate bytestrings directy and encode them as paths.
I hope this fixes a flakyness in the path traversal tests reported by @jschaul.
> Attempt to fix flakyness of path traversal test

- .envrc
- Makefile
- changelog.d/5-internal/nix-locale-archive
- nix/default.nix
- tools/ormolu.sh
Some wire-server tests would fail if the locale variables were not set properly. This PR moves setting the LANG variable into `.envrc` (and also puts `LC_ALL` there). Furthermore, there is no need to set these variables any more in `tools/ormolu.sh`.
The C locale is Debian/Ubuntu-specific; it has been removed from the Ormolu script.
See https://sourceware.org/legacy-ml/libc-alpha/2015-02/msg00247.html.
> Fix locale variables in Nix and .envrc

- changelog.d/5-internal/remove-in-queries
- services/galley/src/Galley/Cassandra/Conversation.hs
- services/galley/src/Galley/Cassandra/Conversation/Members.hs
- services/galley/src/Galley/Cassandra/Queries.hs
We were previously using IN queries when fetching multiple conversations. This can cause performance issues, as cassandra needs to contact all nodes. See [docs/legacy/developer/cassandra-interaction.md].
> Replace IN queries for convs with async

- changelog.d/2-features/turn-dns
- charts/brig/templates/conf/_turn-servers-v2.txt.tpl
- charts/brig/templates/conf/_turn-servers.txt.tpl
- charts/brig/templates/configmap.yaml
- charts/brig/templates/deployment.yaml
- charts/brig/templates/turnconfigmap.yaml
- charts/brig/values.yaml
- docs/src/how-to/administrate/restund.rst
- libs/dns-util/src/Wire/Network/DNS/Effect.hs
- libs/wire-api/src/Wire/API/Call/Config.hs
- services/brig/brig.cabal
- services/brig/brig.integration.yaml
- services/brig/package.yaml
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Calling.hs
- services/brig/src/Brig/Calling/API.hs
- services/brig/src/Brig/Options.hs
- services/brig/src/Brig/Run.hs
- services/brig/test/integration/API/Calling.hs
- services/brig/test/integration/Main.hs
- services/brig/test/integration/Util.hs
- services/brig/test/unit/Test/Brig/Calling.hs
- services/brig/test/unit/Test/Brig/Effects/Delay.hs
This  is not required as the change is backwards compatibile.
> Brig: Implement TURN service discovery using SRV records

- changelog.d/0-release-notes/cert-manager
- changelog.d/2-features/ingress-services
- charts/nginx-ingress-services/templates/certificate.yaml
- charts/nginx-ingress-services/templates/certificate_federator.yaml
- charts/nginx-ingress-services/templates/ingress.yaml
- charts/nginx-ingress-services/templates/issuer.yaml
- charts/nginx-ingress-services/templates/service.yaml
- charts/nginx-ingress-services/values.yaml
charts/nginx-ingress-services: 
* Allow more fine-grained control over what services are installed. (e.g. allow webapp/fakeS3 to not be installed, and federator dns name to not be set if not using federator)
* Upgrade Certificate/Issuer resources: If using [cert-manager](https://github.com/cert-manager/cert-manager), you need to have least version 1.0.0 installed (0.15.X will no longer work).
Related to https://github.com/zinfra/cailleach/pull/1079
> chart/nginx-ingress-services: upgrade resources and allow fine-grained configurability

- changelog.d/3-bug-fixes/pr-2374
- libs/wire-api/src/Wire/API/User/Scim.hs
- services/spar/src/Spar/App.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
- services/spar/test-integration/Util/Core.hs
- services/spar/test-integration/Util/Invitation.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-377
> SQSERVICES-377 fix email verification when external id is updated via SCIM

- .github/pull_request_template.md
See content (it's a very small edit!).  I also updated the internal docs: https://github.com/zinfra/backend-wiki/wiki/Checklists/_compare/6d4ec175eb53d82d0ff9c2584fc26760f101c4ce...2d905781b64273d92a7629daf6476a22fa5cd6f9
note to the reviewer: pls merge right away if you approve.
> Tweak github PR checklist template.

- changelog.d/5-internal/SQSERVICES-1530
- libs/galley-types/src/Galley/Types/Teams.hs
- libs/galley-types/test/unit/Test/Galley/Types.hs
- services/galley/src/Galley/API/LegalHold.hs
- services/galley/src/Galley/API/Teams/Features.hs
> SQSERVICES-1530 view and change team feature permission not by individual feature

- changelog.d/2-features/chart-brig-geoip
- charts/brig/templates/configmap.yaml
- charts/brig/templates/deployment.yaml
- charts/brig/templates/geoip-secret.yaml
- charts/brig/values.yaml
- hack/bin/set-chart-image-version.sh
- hack/bin/set-wire-server-image-version.sh
This optionally allows configuring GeoIP to make IP->latitude/longitude lookups. When this is enabled, `brig` uses this during client registration to save from where a certain client was registered.
Related PR: https://github.com/zinfra/cailleach/pull/1087
> charts/brig: Support running brig with GeoIP database

- changelog.d/5-internal/fs-532-brig
- libs/wire-api/src/Wire/API/Routes/Internal/Brig.hs
- services/brig/src/Brig/API/Internal.hs
- services/brig/src/Brig/Data/MLS/KeyPackage.hs
- services/brig/test/integration/API/Internal.hs
https://wearezeta.atlassian.net/browse/FS-532 (partial, brig changes)
New endpoints are not in use, but brig will need to be deployed before galley, which I think is the status quo.
> KeyPackage -> Conversation Internal API

- changelog.d/3-bug-fixes/pr-2400
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/Sem/IdPConfigStore.hs
- services/spar/src/Spar/Sem/IdPConfigStore/Cassandra.hs
- services/spar/src/Spar/Sem/IdPConfigStore/Mem.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1519
When an IdP was updated, the entry in the table `issuer_idp_v2` did not get overridden, but instead a new entry was made. Because the old entry still existed, adding the old IdP again failed.
In this PR, on IdP update, old issuers in `issuer_idp_v2` will be deleted. Not sure if this is the correct fix, as those old issuers may serve some other purpose that I am not aware of?
> SQSERVICES-1519 IdP for SAML that was overridden by update cannot be added again

- changelog.d/5-internal/SQSERVICES-1559
- libs/wire-api/src/Wire/API/Team/Feature.hs
- libs/wire-api/test/unit/Test/Wire/API/Roundtrip/Aeson.hs
- services/galley/src/Galley/API/Public/Servant.hs
- services/galley/src/Galley/API/Teams/Features.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1559
> SQSERVICES-559 make `AllFeatureConfigs` typed

- changelog.d/0-release-notes/cannon-drain
- changelog.d/2-features/cannon-drain
- charts/cannon/templates/configmap.yaml
- charts/cannon/templates/statefulset.yaml
- charts/cannon/values.yaml
- deploy/services-demo/conf/cannon.demo-docker.yaml
- deploy/services-demo/conf/cannon.demo.yaml
- docs/src/how-to/install/configuration-options.rst
- services/cannon/cannon.cabal
- services/cannon/cannon.integration.yaml
- services/cannon/cannon2.integration.yaml
- services/cannon/package.yaml
- services/cannon/src/Cannon/Dict.hs
- services/cannon/src/Cannon/Options.hs
- services/cannon/src/Cannon/Run.hs
- services/cannon/src/Cannon/Types.hs
- services/cannon/src/Cannon/WS.hs
The plan to implement this is described internally here: https://wearezeta.atlassian.net/wiki/spaces/PS/pages/585564424/How+to+gracefully+drain+cannon+but+not+so+slowly
Related PR: https://github.com/zinfra/cailleach/pull/1092
> Cannon:  Drain websockets in a controlled fashion on SIGTERM or SIGINT

- changelog.d/2-features/pr-2407
- libs/wire-api/src/Wire/API/Team/Export.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/test/integration/API/Teams.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1546
> Sqservices 1546 number of devices in csv export in tm

- changelog.d/5-internal/servantify-csv
- libs/wire-api/src/Wire/API/Routes/CSV.hs
- libs/wire-api/src/Wire/API/Routes/LowLevelStream.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- libs/wire-api/wire-api.cabal
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Public/Servant.hs
- services/galley/src/Galley/API/Teams.hs
Servantify Team CSV endpoint. Since it does not seem to be straightforward to convert a Sem action into a SourceIO value, this PR introduces a new Servant combinator called `LowLevelStream` that directly accepts a `StreamingBody` as the return type of the handler.
Tracked by https://wearezeta.atlassian.net/browse/SQSERVICES-1522.
> Servantify Team CSV endpoint

- changelog.d/5-internal/SQSERVICES-1560
- libs/galley-types/src/Galley/Types/Teams.hs
- libs/wire-api/src/Wire/API/Team/Feature.hs
- services/brig/src/Brig/User/Auth.hs
- services/galley/src/Galley/API/Teams/Features.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1560
> SQSERVICES-1560-more-canonical-handling-of-hard-wired-defaults-type-class-have-defaults-for-all-features

- changelog.d/5-internal/galley-no-sessiont
- services/galley/galley.cabal
- services/galley/package.yaml
- services/galley/src/Galley/Run.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Federation.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Teams/Feature.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
- services/galley/test/integration/API/Util.hs
- services/galley/test/integration/API/Util/TeamFeature.hs
Refactors `withSettingsOverrides` analogous to the refactorings `withSettingsOverrides` of  `cargohold` and `gundeck`:
This PR makes `withSettingsOverrides` spawn galley in a proper http server instead of relying on `SessionT`.
Using `SessionT` has the common pitfall that *any* http calls get interpreted as calls to the application, e.g.
without this PR:
```haskell
brig <- view tsBrig
galley <- view tsGalley
withSettingsOverrides opts $ do
callBrig brig -- this is a lie. The MonadHttp call is interepred as a SessionT call to galley (host ignored), not brig! Most likely this results in `404` that is hard to debug
callGalley galley -- another lie, same as above
```
with this PR (real http server):
```haskell
brig <- view tsBrig
withSettingsOverrides updateOpts $ do
galleyWithOpts <- view …
```
> galley: refactor withSettingsOverrides

- hack/bin/cabal-run-all-tests.sh
This change leads to the following new behaviour:
* show package name for the unit tests that run
* stop executing other packages' unit tests if there's a failure
doesn't warrant a changelog I think.
> show package name for which tests run

- changelog.d/4-docs/feature-schema-fix
- libs/wire-api/src/Wire/API/Team/Feature.hs
This fixes an issue with the generated swagger for e.g. `AllFeatureConfigs`, where some fields were pointing to the schema for the wrong config.
> Feature configs should have different swagger schema names

- .dockerignore
- changelog.d/2-features/cannon-nginz
- charts/cannon/conf/static/zauth.acl
- charts/cannon/templates/conf/_nginx.conf.tpl
- charts/cannon/templates/configmap.yaml
- charts/cannon/templates/nginz-certificate-secret.yaml
- charts/cannon/templates/nginz-certificate.yaml
- charts/cannon/templates/nginz-configmap.yaml
- charts/cannon/templates/nginz-secret.yaml
- charts/cannon/templates/nginz-service.yaml
- charts/cannon/templates/ngniz-service.yaml
- charts/cannon/templates/statefulset.yaml
- charts/cannon/values.yaml
- charts/nginx-ingress-services/templates/certificate.yaml
- charts/nginx-ingress-services/templates/ingress.yaml
- charts/nginx-ingress-services/templates/service.yaml
- charts/nginx-ingress-services/values.yaml
- charts/nginz/templates/conf/_nginx.conf.tpl
- charts/nginz/templates/conf/_upstreams.txt.tpl
- charts/nginz/templates/deployment.yaml
- charts/nginz/values.yaml
- docs/src/how-to/install/configuration-options.rst
- services/nginz/Dockerfile
- services/nginz/nginz_reload.sh
By default, incoming network traffic for websockets comes through these network
hops:
Internet -> LoadBalancer -> kube-proxy -> nginx-ingress-controller -> nginz -> cannon
In order to have graceful draining of websockets when something gets restarted (as implemented in #2416 ), as it is not easily
possible to implement the graceful draining on nginx-ingress-controller or nginz by itself, with this PR there is now
a configuration option to get the following network hops:
Internet -> separate LoadBalancer for cannon only -> kube-proxy -> [nginz->cannon (2 containers in the same pod)]
https://wearezeta.atlassian.net/wiki/spaces/PS/pages/585564424/How+to+gracefully+drain+cannon+but+not+so+slowly
FUTUREWORK: this introduces some nginz config duplication; some way to refactor this (e.g. by …
> charts/cannon: Bundle nginz and expose directly to load balancer

- changelog.d/3-bug-fixes/pr-2430
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/Data/User.hs
- services/brig/src/Brig/User/Auth.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1557
> SQSERVICES-1557-be-unexpected-logic-in-password-verification-for-accounts-with-saml-credentials

- hack/bin/integration-spring-cleaning.sh
- hack/bin/integration-teardown-federation.sh
For internal CI resource cleaning, otherwise we have hundreds of `test-...` namespaces that remain.
> delete namespace after helm resource deletion

- nix/default.nix
Without this, cabal was unable to find glibc when building.
> Export NIX_BUILD_SHELL for cabal also.

- changelog.d/5-internal/nginz-randomport
- charts/cannon/templates/conf/_nginx.conf.tpl
- charts/cannon/values.yaml
- charts/nginz/templates/conf/_nginx.conf.tpl
- charts/nginz/values.yaml
Some internal test environments like staging, must allow requests from arbitrary domains which different teams use. It should also allow requests from `localhost:<some-port>`. This PR expands the purpose of `nginx_conf.randomport_allowlisted_origins` to allow any arbitrary host name.
> charts/{cannon,nginz}: Allow configuring arbitrary hosts for CORS allowlisting

- changelog.d/5-internal/nginz-map-hash-bucket-size
- charts/cannon/templates/conf/_nginx.conf.tpl
- charts/nginz/templates/conf/_nginx.conf.tpl
This is needed when there are many CORS origin to be allowed.
> charts/{cannon,nginz}: Increase map_hash_bucket_size for nginx to 128

- services/cannon/src/Cannon/API/Internal.hs
- services/cannon/src/Cannon/App.hs
- services/cannon/src/Cannon/Dict.hs
- services/cannon/src/Cannon/Run.hs
- services/cannon/src/Cannon/Types.hs
- services/cannon/src/Cannon/WS.hs
- services/cannon/test/Test/Cannon/Dict.hs
Split into two commits. One for general linting and a second one just for return/pure replacement to reduce the noise during review.
> Linted Cannon.

- services/spar/test-integration/Test/Spar/APISpec.hs
- services/spar/test-integration/Test/Spar/AppSpec.hs
- services/spar/test-integration/Test/Spar/DataSpec.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
- services/spar/test-integration/Util/Core.hs
- services/spar/test-integration/Util/Email.hs
- services/spar/test-integration/Util/Invitation.hs
- services/spar/test-integration/Util/Scim.hs
- services/spar/test/Test/Spar/APISpec.hs
- services/spar/test/Test/Spar/DataSpec.hs
- services/spar/test/Test/Spar/Intra/BrigSpec.hs
- services/spar/test/Test/Spar/ScimSpec.hs
- services/spar/test/Test/Spar/Sem/IdPConfigStoreSpec.hs
Missed tests files when linting before.
> Lint Spar test files

- services/cargohold/src/CargoHold/API/Federation.hs
- services/cargohold/src/CargoHold/API/Legacy.hs
- services/cargohold/src/CargoHold/API/Public.hs
- services/cargohold/src/CargoHold/API/V3.hs
- services/cargohold/src/CargoHold/AWS.hs
- services/cargohold/src/CargoHold/App.hs
- services/cargohold/src/CargoHold/CloudFront.hs
- services/cargohold/src/CargoHold/S3.hs
- services/cargohold/src/CargoHold/Util.hs
- services/cargohold/test/integration/API.hs
- services/cargohold/test/integration/API/V3.hs
- services/cargohold/test/integration/Main.hs
Split in two commits for easy of review. s/return/pure is a separate commit.
> Lint cargohold

- changelog.d/5-internal/bitnami-old-repo
- charts/legalhold/requirements.yaml
- charts/redis-ephemeral/requirements.yaml
They've deleted the versions we use from the latest index. More details:
https://github.com/bitnami/charts/issues/10539
> Use old bitnami helm repo from git for redis and postgresql

- changelog.d/3-bug-fixes/pr-2445
- libs/wire-api/src/Wire/API/User/Scim.hs
- services/brig/src/Brig/Data/User.hs
- services/brig/src/Brig/Team/API.hs
- services/spar/src/Spar/Intra/Brig.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/src/Spar/Sem/BrigAccess.hs
- services/spar/src/Spar/Sem/BrigAccess/Http.hs
We now account for the preferred language field in the SCIM spec, and fallback to it in case of locale being undefined.
Currently untested.
> Email localization when provisioning users with SCIM.

- changelog.d/1-api-changes/added-ttl-param-to-back-office-feature-api
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- libs/wire-api/src/Wire/API/Team/Feature.hs
- libs/wire-api/test/unit/Test/Wire/API/Roundtrip/ByteString.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Public/Servant.hs
- services/galley/src/Galley/API/Teams/Features.hs
- services/galley/src/Galley/Cassandra/TeamFeatures.hs
- services/galley/src/Galley/Effects/TeamFeatureStore.hs
- services/galley/test/integration/API/Teams/Feature.hs
- services/galley/test/integration/API/Util/TeamFeature.hs
- tools/stern/src/Stern/API.hs
- tools/stern/src/Stern/Intra.hs
> Added TTL query field to features API.

- changelog.d/3-bug-fixes/nginz-collision
- charts/nginz/values.yaml
Things done:
- List all `/self*` endpoints of brig so the catch all `/self` doesn't forward `/self/consent` to brig
- Ensure that `envs: [ all ]` is set for `/self/consent` and `/signatures`. This was missed in previous PR
> charts/nginz: Ensure traffic can be routed to galeb correctly

- docs/src/how-to/install/dependencies.rst
glibc 2.34 uses the clone3 syscall, which is not part of the seccomp
filters that moby ships on older versions.
While as a workaround you might be able to run containers with
`--privileged`, it's the better call to just run a more recent Docker
runtime.
References:
- https://github.com/docker/buildx/issues/772
- https://github.com/moby/buildkit/pull/2379
- https://github.com/moby/moby/pull/42836
- https://github.com/NixOS/nixpkgs/pull/170900
> docs/src/how-to/install/dependencies.rst: require Docker >= 20.10.14

- services/federator/src/Federator/Monitor.hs
- services/federator/src/Federator/Run.hs
- services/federator/test/integration/Test/Federator/Util.hs
- services/federator/test/unit/Test/Federator/Options.hs
- services/proxy/src/Proxy/API.hs
- services/proxy/src/Proxy/API/Public.hs
- services/proxy/src/Proxy/Env.hs
- services/spar/migrate-data/src/Spar/DataMigration/V1_ExternalIds.hs
And that's the lest of /services. Next, tools and libs!
> Lint remaining services

- changelog.d/3-bug-fixes/fix-saml-corner-case
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/Data/User.hs
- services/brig/src/Brig/User/Auth.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1616
> Fix saml corner case

- docs/src/understand/single-sign-on/main.rst
A missing newline prevented the code-block from being rendered, the added newline fixes this
> fix: add missing newline in code-block

- docs/src/_templates/layout.html
It looks like the sphinx version in our docker container is older than the one being used to generate the documentation with sphinx.
Prior to this change the logo was only added correctly locally but not on the data ending up on docs.wire.com
> fix(docs): use if-block to support older version of sphinx when adding the logo

- changelog.d/0-release-notes/nginz-ingress
- charts/nginx-ingress-services/templates/ingress.yaml
- charts/nginx-ingress-services/templates/service.yaml
- charts/nginx-ingress-services/values.yaml
- charts/nginz/templates/service.yaml
- charts/nginz/templates/servicemonitor.yaml
- charts/nginz/values.yaml
This provides a prometheus endpoint out of the box, so we can access it
at /vts/status/format/prometheus.
It also moves the `nginz{-tcp,-http}` service into a merged `nginz` service in the `nginz` helm chart, and adds `servicemonitor` support to it, so metrics can be scraped.
> //services/nginz/third_party/nginx-module-vts: update

- changelog.d/5-internal/pr-2479
- charts/galley/templates/configmap.yaml
- charts/galley/values.yaml
All feature configs like guest links e.g. can now be overridden in the helm configuration, so that they can be disabled/enabled and configured server wide.
> Make all feature configs overridable

- charts/nginz/templates/service.yaml
Use the same set of labels for the nginz service that we add to other
services.
The ServiceMonitor resource wants app=nginz, which right now is missing
- so the ServiceMonitor doesn't select anything currently.
Follow-up of https://github.com/wireapp/wire-server/pull/2476.
> charts/nginz: add necessary labels to service

- changelog.d/0-release-notes/nginz-ingress
- charts/nginz/templates/conf/_nginx.conf.tpl
- charts/nginz/templates/deployment.yaml
- charts/nginz/templates/service.yaml
- charts/nginz/templates/servicemonitor.yaml
- charts/nginz/values.yaml
> charts/nginz: move /vts endpoint to a new http-metrics port

- changelog.d/2-features/backoffice
- changelog.d/3-bug-fixes/backoffice
- charts/backoffice/values.yaml
- charts/wire-server/requirements.yaml
- charts/wire-server/values.yaml
- hack/bin/set-chart-image-version.sh
- hack/bin/set-wire-server-image-version.sh
This change fixes the backoffice chart versions, includes it in the wire-server chart  and ensures that stern versions are bumped correctly.
> Optionally include backoffice when installing wire-server helm chart

- docs/src/conf.py
Doing something completely unrelated I've noticed the uppercase 'W' in the filename.
This could never have worked on case sensitive filesystems ;)
This should finalize our attempts done in #2471 and fix the missing logo on docs.wire.com
> fix(docs): use correct case for wire logo path

- changelog.d/1-api-changes/pr-2492
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- services/galley/src/Galley/API/Internal.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1529
The API changes in this PR were also added here: https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/603095166/API+changes+v1+v2
> SQSERVICES-1529 Swagger docs and endpoint deprecation for API version V2

- changelog.d/3-bug-fixes/mls-public-keys
- libs/wire-api/src/Wire/API/User/Client.hs
- services/brig/src/Brig/Data/Client.hs
- services/brig/test/integration/API/User/Client.hs
- services/brig/test/integration/API/User/Util.hs
This PR fixes a bug where all clients, including non-MLS clients, would be associated with the same MLS public key in the response to `GET /clients`.
Tracked by https://wearezeta.atlassian.net/browse/FS-705.
> [FS-705] Fix Repeated MLS Public Keys

- changelog.d/5-internal/flaky-email-update-test-fix
- services/brig/test/integration/API/User/Account.hs
As the code comment hints at, we have a very narrow window between a user being created and the account being suspended inside the test environment. For a good reason too. We don't want to run a test that takes too long to check that account suspension works. But a suspended account can no longer be updated, rendering this particular test flaky, especially on subsequent test suite runs.
This should address that issue but immediately cleaning up after itself.
> Fixed flakiness of a test by adding a clean-up step at the end.

- charts/coturn/Chart.yaml
- charts/coturn/templates/configmap-coturn-conf-template.yaml
Our coturn fork previously had username labeling of Prometheus metrics patched out, however wireapp/coturn#7 reintroduced these metrics with a flag to disable them at runtime. This change updates the coturn image to include this change, and updates the configuration in the Helm chart to ensure this functionality remains disabled. This should not introduce any functional changes.
See also https://wearezeta.atlassian.net/browse/SQPIT-1012.
> Bump coturn image, update chart config for configurable metrics labels

- changelog.d/0-release-notes/coturn-udp-ports
- changelog.d/3-bug-fixes/coturn-udp-ports
- charts/coturn/templates/service.yaml
- charts/coturn/templates/statefulset.yaml
This change adds the port definitions for coturn's UDP control port to the `StatefulSet` and `Service` definitions in the Helm chart. While this doesn't introduce any direct functional changes, it ensures that the control plane is aware of the fixed UDP port in use by coturn, which may then be advertised by service discovery glue which announces coturn pods based on the ports they expose.
I've run into difficulties updating prior versions of the coturn Helm chart to the one in this PR, which turns out is [a Kubernetes bug](https://github.com/kubernetes/kubernetes/issues/39188). I've added a release notes entry to the changelog with the required manual actions required to perform the upgrade.
This is the UDP half of https://wearezeta.atlassian.net/browse/SQPIT-1018.
> Add UDP endpoints to coturn Helm chart

- changelog.d/0-release-notes/coturn-udp-ports
> Amend changelog wording for redundancy

- build/ubuntu/Dockerfile.deps
This PR adds a new incompatible implementation (`mls-test-cli`) of the CLI tool used in MLS integration tests in PR #2508.
Once #2508 is merged, the plan is to remove all traces of the old tool (`crypto-cli`). However, for the moment they both need to be in place, since the other active PRs are still using it.
> Add new MLS test tool to ubuntu image

- changelog.d/2-features/pr-2503
- docs/legacy/reference/config-options.md
- libs/galley-types/src/Galley/Types/Teams.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- libs/wire-api/src/Wire/API/Team/Feature.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Public/Servant.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/API/Teams/Features.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Teams/Feature.hs
- services/galley/test/integration/API/Util/TeamFeature.hs
The feature `searchVisibilityInbound` has been added to the public and internal team feature API as well as included in the response of `GET /feature-configs`.
https://wearezeta.atlassian.net/browse/SQSERVICES-1441
> SQSERVICES-1441 Search visibility rules

- changelog.d/2-features/create-team-members
- deploy/services-demo/create_team_members.sh
Run `./deploy/services-demo/create_team_members.sh` without arguments for help.
The `inviter_name` field in the request has been ignored for a while now, and it was only providing a dummy value here anyway, so it's gone now.
> Accept roles when creating teams with demo script.

- docs/src/how-to/install/configuration-options.rst
> add info on IS_SELF_HOSTED in docs

- changelog.d/5-internal/pr-2512
- services/gundeck/gundeck.cabal
- services/gundeck/src/Gundeck/Env.hs
- services/gundeck/src/Gundeck/Monad.hs
- services/gundeck/src/Gundeck/Redis.hs
- services/gundeck/src/Gundeck/Run.hs
The plain `hedis` client discards the initial connection data and only retains a list of Redis cluster node IPs. When none of these IPs is valid anymore, for instance, due to Redis cluster or (Kubernetes) node updates, `hedis` immediately looses all retained connections to Redis without any option to reconnect. In this patch, we wrap the `hedis` client and retry connecting with the initially provided connection data in case of network errors. Also, the wrapper makes sure that
* if reconnecting fails, it is retried with exponential back-off, and
* only one thread reconnects while all other threads are blocked and are immediately unblocked as soon as the new connection is established.
> retry Redis connection in case of network errors

- services/gundeck/src/Gundeck/Monad.hs
- services/gundeck/src/Gundeck/Redis.hs
> Gundeck: Log when connection with redis breaks

- changelog.d/3-bug-fixes/pr-2519
- libs/wire-api/src/Wire/API/User.hs
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/Error.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1628
> SQSERVICES-1628-dont-allow-deleting-id-ps-if-the-deleting-user-is-authenticated-by-it
