- libs/bilge/stack.yaml
- libs/brig-types/stack.yaml
- libs/cargohold-types/stack.yaml
- libs/galley-types/stack.yaml
- libs/gundeck-types/stack.yaml
- libs/tasty-cannon/stack.yaml
- libs/types-common/stack.yaml
- libs/wai-utilities/stack.yaml
Allows running `stack build --test` from within libs' directory. CI may also run on this PR...
> Update types-common flags for 'stack build --test'

- services/nginz/Makefile
(also trying out pull-request-builder for nginz)
> Upgrade nginx to 1.12.0

- services/proxy/src/Proxy/API.hs
Since [this commit](https://github.com/wireapp/wire-server/commit/1c97bdc44672679476a5d07f6abca0c1431a31c6#diff-173e3cfb37e3312fbc6545496e6d6b68L193), proxy causes a runtime StatusCodeException on the soundcloud stream requests, since that library throws exceptions [when a status code != 2XX](https://github.com/snoyberg/http-client/blob/master/http-client/Network/HTTP/Client/Request.hs#L88-L91), i.e. also on a 302 (which we expect here).
> [proxy] FIX: Don't throw a StatusCodeException on a 302

- services/brig/src/Brig/Provider/API.hs
- services/brig/test/integration/API/Provider.hs
Auto-approve all service providers upon successful e-mail verification. Due to popular demand.
> Auto-approve all providers.

- services/galley/Makefile
- services/galley/deb-journaler/DEBIAN/control
- services/galley/deb-journaler/DEBIAN/postinst
- services/galley/deb-journaler/opt/galley/bin/galley-journaler
- services/galley/galley.cabal
- services/galley/journaler/src/Journal.hs
- services/galley/journaler/src/Main.hs
- services/galley/journaler/src/Options.hs
- services/galley/src/Galley/Intra/Journal.hs
- services/galley/src/Galley/Options.hs
`galley-journaler` script to (re-) initialize team creation/deletion on a queue.
> Journaling script to initialize team events

- tools/bonanza/bonanza.cabal
- tools/bonanza/src/Bonanza/Parser/Journald.hs
- tools/bonanza/src/Bonanza/Parser/Rkt.hs
- tools/bonanza/src/Bonanza/Parser/Time.hs
- tools/bonanza/src/Bonanza/Streaming/Parser.hs
Adds basic parsers for `journald` and `rkt`. Some testing to be added later.
> Add journald rkt parsers

- services/brig/src/Brig/Provider/API.hs
- services/brig/test/integration/API/Provider.hs
https://github.com/wearezeta/backend-issues/issues/561
> Catch exceptions when validating a service key

- services/brig/src/Brig/API/User.hs
- services/galley/src/Galley/Data/Queries.hs
https://github.com/wearezeta/backend-issues/issues/604
> Set sensible defaults when users and teams are deleted

- libs/galley-types/src/Galley/Types/Teams.hs
- services/brig/src/Brig/IO/Intra.hs
- services/brig/test/integration/API.hs
- services/brig/test/integration/API/Team.hs
- services/brig/test/integration/Main.hs
- services/brig/test/integration/Util.hs
- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/Teams.hs
* Add an internal endpoint for getting the bound team members of the user
* Notify bound team members on user updates
> Notify team contacts on user update

- .gitignore
- libs/galley-types/src/Galley/Types.hs
- libs/galley-types/src/Galley/Types/Teams.hs
- services/brig/src/Brig/API/Connection.hs
- services/brig/src/Brig/API/Error.hs
- services/brig/src/Brig/API/Types.hs
- services/brig/src/Brig/API/User.hs
- services/brig/test/integration/API/Team.hs
- services/galley/galley.cabal
- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/Create.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/API/Util.hs
- services/galley/src/Galley/Data.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Util.hs
Replaces https://github.com/wireapp/wire-server/pull/73
* Allows members of the same binding to create 1to1 conversations inside a team
* Prevents members of the same binding team to create connections (they are unnecessary and can create some confusion)
> Issue 581 v2

- libs/galley-types/src/Galley/Types/Teams.hs
- libs/galley-types/src/Galley/Types/Teams/Intra.hs
- libs/types-common-journal/proto/TeamEvents.proto
- services/galley/journaler/src/Journal.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/Aws.hs
- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Data/Queries.hs
- services/galley/src/Galley/Intra/Journal.hs
- services/galley/test/integration/API/SQS.hs
- services/galley/test/integration/API/Teams.hs
Note that I opted to pattern match on explicit states to make it easier for us to notice when we to add new states to pattern match on.
> Do not journal teams in PendingActive state

- services/brig/brig.yaml.example
> Update brig yaml config 

- libs/brig-types/src/Brig/Types/Connection.hs
- services/brig/src/Brig/API.hs
- services/brig/src/Brig/API/Connection.hs
- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Data/Types.hs
- services/galley/src/Galley/Intra/User.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/SQS.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Util.hs
Broadcast a message to all team members and all contacts
> /broadcast/otr/messages endpoint

- services/brig/README.md
Supersedes #71 (contributor has not signed CLA)
> fix: corrected links that were 404 in the brig README

- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/Data.hs
Move the concurrency to the `Data` module, thereby having only a single way to look clients up from cassandra
> Move client lookup concurrency to the data module

- libs/api-bot/src/Network/Wire/Bot/Monad.hs
- stack.yaml
Some dependencies were not building so they were added to the top level stack.yaml too to make it easier to check that all dependencies build correctly
> Fixed dependencies and added them to the top level stack.yaml

- build/alpine/Dockerfile.builder
- build/alpine/Dockerfile.deps
Also update to latest `stack`.
> Upgrade alpine docker base image to 3.7

- services/brig/index/src/Options.hs
Prerequisite for https://github.com/wireapp/wire-server/pull/216, allowing to specify e.g. `brig-index create --elasticsearch-server http://elasticsearch:9200`
> [brig-index] allow specifying ES base url

- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/Data.hs
Minor refactoring of the conversation "garbage collection".
> Move conversation GC to data

- services/brig/test/integration/Main.hs
Fixes `parseConfigPaths` to allow e.g. 
```sh
./dist/brig-integration -i ../integration.yaml -s brig.integration.yaml -p "cookies"
```
to work without interference of the `-i` option to the tasty parser and without interference of the `-p` option to the parseConfigPaths parser.
Prerequisite to using config files during local integration tests.
> Fix handling of config files in brig-integration

- README.md
- doc/Dependencies.md
This documentation only becomes correct after #244 is merged.
> Updated documentation on building & integration tests

- libs/cargohold-types/src/CargoHold/Types/V3.hs
- services/cargohold/src/CargoHold/S3.hs
- services/cargohold/test/integration/API/V3.hs
Adds other retention possibilities, depending on the desired use case. Adjusts existing retention policies.
> New retention types and policies for assets

- README.md
- services/nginz/README.md
> Update docs for nginz

- services/brig/test/integration/API.hs
- services/brig/test/integration/API/Team.hs
Removes some hardcoded timeout values and also improves `testInvitationTooManyPending` by not making more requests than needed, allowing it to run much faster (given a `TeamSizeLimit` much smaller than 128 as we have, by default, on our tests).
It's still, however, not bulletproof (commented in the code); not sure how to improve this test further since it depends on "how fast one can create invitations" and test the invitation `N+1` without them expiring.
> Improve expiry/timeout based tests

- services/brig/deb/opt/brig/templates/de/user/email/activation-subject.txt
- services/brig/deb/opt/brig/templates/en/user/email/activation-subject.txt
- services/brig/deb/opt/brig/templates/et/user/email/activation-subject.txt
@lipis Can you fix the originals in https://github.com/wireapp/wire-emails please?
> Fix activation-subject

- services/brig/deb/etc/sv/brig/run
> Fix for CLI parameters for #296

- libs/api-bot/src/Network/Wire/Bot/Assert.hs
- libs/api-bot/src/Network/Wire/Bot/Cache.hs
- libs/api-bot/src/Network/Wire/Bot/Monad.hs
- libs/api-client/src/Network/Wire/Client/API/Conversation.hs
- libs/galley-types/src/Galley/Types.hs
- services/brig/test/integration/API/Provider.hs
- services/brig/test/integration/API/Search/Util.hs
- services/brig/test/integration/API/TURN.hs
- services/brig/test/integration/API/Team.hs
- services/brig/test/integration/API/Team/Util.hs
- services/brig/test/integration/API/User/Auth.hs
- services/brig/test/integration/API/User/Util.hs
- services/brig/test/integration/Util.hs
- services/cargohold/test/integration/API/V3.hs
- services/galley/test/integration/API/SQS.hs
- services/galley/test/integration/API/Util.hs
- services/gundeck/test/integration/API.hs
- tools/api-simulations/lib/src/Network/Wire/Simulations.hs
- tools/api-simulations/loadtest/src/Main.hs
- tools/api-simulations/loadtest/src/Network/Wire/Simulations/LoadTest.hs
- tools/api-simulations/smoketest/src/Main.hs
- tools/api-simulations/smoketest/src/Network/Wire/Simulations/SmokeTest.hs
> Rewrite the smoketest to support more than 3 users

- deploy/services-demo/create_test_user.sh
* can create many users
* can create users in `users.txt` format
> Extend the create_test_user.sh script

- libs/libzauth/libzauth-c/Makefile
I checked locally and it works
> Fix docker nginz build

- services/brig/test/integration/API/Search.hs
- tools/api-simulations/loadtest/src/Network/Wire/Simulations/LoadTest.hs
- tools/api-simulations/smoketest/src/Network/Wire/Simulations/SmokeTest.hs
This doesn't change any behavior whatsoever. Just a precaution.
> Never user unsafe async

- libs/brig-types/src/Brig/Types/Swagger.hs
- libs/brig-types/src/Brig/Types/User/Auth.hs
- services/brig/src/Brig/User/API/Auth.hs
- services/brig/src/Brig/User/Auth.hs
- services/brig/test/integration/API/User/Auth.hs
- services/brig/test/integration/Util.hs
This adds an internal endpoint that lets you login as any (existing, non-suspended) user.
> Backdoor login

- deploy/services-demo/conf/nginz/nginx.conf
Addresses https://github.com/wireapp/wire-server/issues/324
> Add missing routing of /properties to brig

- stack.yaml
See https://github.com/tiago-loureiro/aws/pull/1
> Get rid of some AWS garbage in integration tests

- services/galley/src/Galley/Intra/User.hs
- tools/api-simulations/lib/src/Network/Wire/Simulations.hs
- tools/api-simulations/loadtest/src/Network/Wire/Simulations/LoadTest.hs
**Use distinct names for bots**
**Add some comments**
**Change 'prepareConv' to do N connection requests instead of N^2**
> Some improvements to the loadtest

- services/brig/test/integration/API/User/Auth.hs
This test relied on the fact that subsequent logins could be made after one second (thus the call to `wait`, which pauses for a second). This value though will not be sufficient if `Retry-After` is greater than 1 second.
I have modified the test so that it waits for `Retry-After` before logging in again and also run in parallel both tests for `Persistent` and `Session` cookies.
In order for this test to finish, we need to wait roughly for:
* `setUserCookieLimit` logins, attempted once per second
* `RetryAfter` * `value of carry` in the test
With a `RetryAfter` of 5 seconds, `setUserCookieLimit` of 5 and `carry = 2`, the test takes about 20 seconds to finish.
> Fixed flaky cookie limit test

- deploy/docker-ephemeral/init.sh
- libs/brig-types/src/Brig/Types/Common.hs
- libs/brig-types/test/unit/Test/Brig/Types/User.hs
- services/brig/brig.cabal
- services/brig/src/Brig/Data/Instances.hs
- services/brig/src/Brig/Data/User.hs
- services/brig/test/integration/API/Team.hs
- services/brig/test/integration/API/User/Account.hs
Relax UserSSOId type to contain any strings (not just UUID).
Store the values as json blobs on cassandra.
Introduces string-conversions, one of my favorite packages.
> Tweak user sso id type

- services/gundeck/src/Gundeck/Push/Native/Serialise.hs
- services/gundeck/test/unit/Native.hs
This does not fix this issue, but sheds some light on it in case it pops up again in the future.
> Document #341.

- deploy/services-demo/conf/brig.demo.yaml
- deploy/services-demo/resources/turn/servers-v2.txt
Missed this one when turnV2 was added
> Added missing config to brig when running the demo

- services/brig/src/Brig/API/User.hs
Fixes https://github.com/wearezeta/backend-issues/issues/711. I haven't added a regression test for this, but teams.wire.com will hopefully maybe switch to the new flow at some point and make the existence of a regression test irrelevant.
> Send team activation emails on /activate/send

- libs/gundeck-types/src/Gundeck/Types/Push/V2.hs
- libs/gundeck-types/src/Gundeck/Types/Swagger.hs
- services/gundeck/src/Gundeck/API.hs
- services/gundeck/src/Gundeck/Push.hs
- services/gundeck/test/integration/API.hs
Which is more flexible than using a plain list
> Expose push token list as a json object

- services/spar/src/Spar/Error.hs
- services/spar/src/Spar/Intra/Brig.hs
- https://github.com/wireapp/wire-server/blob/develop/services/brig/src/Brig/API.hs#L131
- https://github.com/wireapp/wire-server/blob/develop/services/brig/src/Brig/API.hs#L1121
> Fix Spar: expect the correct response body type.

- services/spar/src/Spar/API.hs
- services/spar/src/Spar/Error.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
This PR adjusts response codes, labels and messages to be more descriptive and allow clients to programatically process these labels and better messages when debugging issues.
> Improve spar error granularity

- README.md
- services/restund/.gitignore
- services/restund/Dockerfile
- services/restund/LICENSE
- services/restund/Makefile
- services/restund/README.md
- services/restund/modules/drain/drain.c
- services/restund/modules/drain/module.mk
- services/restund/modules/zrest/module.mk
- services/restund/modules/zrest/zrest.c
Open-source the custom modules `zrest` and `drain` on top of [restund](https://github.com/wireapp/restund), and provide some documentation.
> Import restund/turn setup

- services/spar/package.yaml
- services/spar/src/Spar/App.hs
- services/spar/src/Spar/Run.hs
- services/spar/test-integration/Test/Spar/DataSpec.hs
- services/spar/test/Test/Spar/AppSpec.hs
there is a small integration test "fix" piggy-backing on this (last commit).
> Add RequestId field to Spar logs

- libs/brig-types/src/Brig/Types/Code.hs
- libs/types-common/src/Data/Code.hs
- services/brig/src/Brig/Code.hs
- services/brig/src/Brig/Provider/API.hs
- services/brig/test/integration/API/Provider.hs
Allows for better automation of provider creation/activation
> Internal provider activation

- services/brig/src/Brig/Provider/RPC.hs
- services/brig/test/integration/API/Provider.hs
> Release 2018-08-22

- services/integration.yaml
- services/spar/package.yaml
- services/spar/spar.integration.yaml
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/API/Instances.hs
- services/spar/src/Spar/API/Swagger.hs
- services/spar/src/Spar/Types.hs
- services/spar/test-integration/Spec.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
- services/spar/test-integration/Test/Spar/DataSpec.hs
- services/spar/test-integration/Util.hs
- services/spar/test-integration/Util/MockIdP.hs
- services/spar/test-integration/Util/Types.hs
- services/spar/test/Arbitrary.hs
- stack.yaml
This is closely related to https://github.com/wireapp/saml2-web-sso/pull/21
> SSO integration tests; refactoring.

- Makefile
- build/alpine/Makefile
- libs/libzauth/Makefile
- libs/libzauth/libzauth-c/Makefile
- libs/metrics-collectd/Makefile
- services/brig/Makefile
- services/brig/schema/Makefile
- services/cannon/Makefile
- services/cargohold/Makefile
- services/galley/Makefile
- services/gundeck/Makefile
- services/gundeck/test/Makefile
- services/nginz/Makefile
- services/proxy/Makefile
- services/restund/Makefile
- services/spar/Makefile
- tools/api-simulations/Makefile
- tools/bonanza/Makefile
- tools/db/auto-whitelist/Makefile
- tools/db/service-backfill/Makefile
- tools/makedeb/Makefile
`find Makefile build/ tools/ services/ libs/ -name Makefile -exec perl -i -pe 'unless ($done) { $done = 1; print "LANG := en_US.UTF-8\n" }' {} \;`
> Set LANG in all Makefiles.

- build/alpine/Dockerfile.builder
- build/alpine/Dockerfile.prebuilder
I *think* this is what caused [the ci failiue on #470](https://bridge-ie-concourse.zinfra.io/builds/5610), even though I have no idea why this hasn't been caught a log earlier.
> upgrade stack in alpine-prebuilder, alpine-builder

- deploy/services-demo/conf/nginz/nginx.conf
Fixes https://github.com/wireapp/wire-server/issues/484
> Route calls/config in the demo to brig

- deploy/services-demo/README.md
Docs on https://github.com/wireapp/wire-server/issues/326
> Add docs on docker max memory usage adjustment

- build/alpine/Dockerfile
- services/brig/Dockerfile
> exectuable -> executable

- libs/brig-types/src/Brig/Types/Properties.hs
- libs/brig-types/src/Brig/Types/Swagger.hs
- services/brig/src/Brig/API.hs
- services/brig/src/Brig/API/Properties.hs
- services/brig/src/Brig/Data/Properties.hs
- services/brig/test/integration/API/User/Property.hs
A single endpoint (e.g. GET /properties-values) to get a JSON object that provides keys and values, so that client can fetch all the necessary properties in one request.
> New end-point: return all user properties together with values.

- services/gen-aws-conf.sh
This worked for me.  Thanks @tiago-loureiro!
Reviewer: please double-check the aws-cli github repo and the s3 path.
> Improve error info in real-aws integration test script.

- deploy/services-demo/conf/gundeck.demo.yaml
- deploy/services-demo/conf/spar.demo.yaml
Demo configs for spar, gundeck were outdated.  No harm was done from that, but the changes are helpful for the reader.
> Demo configs for spar, gundeck

- Makefile
first commit fixes a problem that nobody has tripped over for a while, so the second commit just removes the entire rule.
> Dead code in Makefile

- libs/types-common/src/Data/Id.hs
- libs/types-common/types-common.cabal
- services/brig/src/Brig/API/Handler.hs
- services/brig/src/Brig/App.hs
- services/cannon/cannon.cabal
- services/cannon/src/Cannon/Types.hs
- services/cannon/src/Cannon/WS.hs
- services/cargohold/src/CargoHold/App.hs
- services/galley/galley.cabal
- services/galley/src/Galley/App.hs
- services/gundeck/src/Gundeck/Env.hs
- services/gundeck/src/Gundeck/Monad.hs
- services/proxy/proxy.cabal
- services/proxy/src/Proxy/Env.hs
- services/proxy/src/Proxy/Proxy.hs
- services/spar/package.yaml
- services/spar/src/Spar/Run.hs
Change base and merge once the LTS-12 PR is merged.
> Get rid of a Monoid RequestId instance

- deploy/services-demo/conf/brig.demo.yaml
- deploy/services-demo/conf/galley.demo.yaml
- deploy/services-demo/demo.sh
- services/brig/brig.integration.yaml
- services/galley/galley.integration.yaml
- services/integration.sh
* Don't use netstrings locally
* Don't override logLevel with LOG_LEVEL
> Fix logging

- deploy/services-demo/conf/cannon.demo.yaml
- deploy/services-demo/demo.sh
- services/cannon/cannon.cabal
- services/cannon/cannon.integration.yaml
- services/cannon/cannon2.integration.yaml
- services/cannon/deb/etc/sv/cannon/run
- services/cannon/src/Cannon/API.hs
- services/cannon/src/Cannon/Options.hs
- services/cannon/src/Main.hs
- services/integration.sh
Don't merge until Hegemony and Cailleach PRs are done.
> Switch Cannon to YAML-only config

- README.md
- services/brig/Makefile
- services/brig/src/Brig/ZAuth.hs
- services/cargohold/Makefile
- services/galley/Makefile
- services/gundeck/Makefile
- services/spar/Makefile
- services/spar/test-integration/Spec.hs
- services/spar/test-integration/Util/Core.hs
This is for the last two commits; the earlier refactorings are needed to make those changes more convenient.
> Integration tests in spar; test instructions in README.

- libs/galley-types/galley-types.cabal
- libs/galley-types/test/unit/Main.hs
- libs/galley-types/test/unit/Test/Galley/Types.hs
[as discussed here](https://github.com/wireapp/wire-server/pull/573#discussion_r249049467)
> Make role-perm mapping more robust to change.

- services/nginz/Dockerfile
> Fix nginz docker image building

- services/spar/src/Spar/Scim.hs
- services/spar/src/Spar/Scim/Types.hs
> Slightly update SCIM comments in regard to names, etc

- snapshots/wire-1.1.yaml
- stack.yaml
https://github.com/wireapp/hsaml2/pull/4
> bump hsaml2 dep

- libs/metrics-wai/src/Data/Metrics/Servant.hs
- libs/metrics-wai/src/Data/Metrics/Types.hs
- services/brig/test/integration/API/Metrics.hs
- services/spar/test-integration/Test/MetricsSpec.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
The metrics dashboards expect the capture variables from the wai routes in the metrics output, so here you go.
> Downgrade metrics output

- services/spar/src/Spar/API/Swagger.hs
- services/spar/src/Spar/Data.hs
- services/spar/src/Spar/Data/Instances.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
- services/spar/test-integration/Test/Spar/DataSpec.hs
- services/spar/test-integration/Util/Core.hs
- services/spar/test-integration/Util/Scim.hs
- services/spar/test/Test/Spar/Intra/BrigSpec.hs
- stack.yaml
Depends on https://github.com/wireapp/saml2-web-sso/pull/47
> SAML input sanitization

- .linting/duplicate-ids-whitelist.txt
- deploy/services-demo/conf/cargohold.demo-docker.yaml
- deploy/services-demo/conf/cargohold.demo.yaml
- deploy/services-demo/demo.sh
- services/cargohold/cargohold.integration.yaml
- services/cargohold/deb/etc/sv/cargohold/run
- services/cargohold/src/CargoHold/API.hs
- services/cargohold/src/CargoHold/App.hs
- services/cargohold/src/CargoHold/Options.hs
- services/cargohold/src/Main.hs
- services/integration.sh
Should be rebased and fixed after https://github.com/wireapp/wire-server/pull/642 is merged.
> Switch Cargohold to YAML-only config

- deploy/docker-ephemeral/build/README.md
- docs/reference/make-docker-and-qemu.md
take some PR comments from #622 into account.
> Jel docker 1

- libs/metrics-wai/package.yaml
- libs/metrics-wai/src/Data/Metrics/Middleware/Prometheus.hs
- libs/metrics-wai/src/Data/Metrics/Types.hs
- services/galley/package.yaml
- services/galley/src/Galley/API.hs
- services/galley/src/Galley/Run.hs
- services/galley/src/Main.hs
- services/galley/test/integration/API.hs
> Reusable wai middleware for prometheus (And add it to Galley)

- build/alpine/Dockerfile.builder
- services/integration.sh
inspired by http://www.perkin.org.uk/posts/how-to-fix-stdio-buffering.html
> Do not buffer stdout in integration tests.

- deploy/services-demo/conf/proxy.demo.yaml
- deploy/services-demo/demo.sh
- services/proxy/deb/etc/sv/proxy/run
- services/proxy/proxy.integration.yaml
- services/proxy/src/Main.hs
- services/proxy/src/Proxy/Env.hs
- services/proxy/src/Proxy/Options.hs
> Switch Proxy to YAML-only config

- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
I couldn't resist.
Hspec only gives us the first entry of the call stack -- for some weird reason -- so having a HasCallStack constraint on the test itself breaks reporting. The 'Char' trick is still useful, just not in this case.
> Fix HasCallStack usage

- services/brig/test/integration/API/User/Account.hs
we've had sporadic failures like this for a long time:
```
Brig API Integration
user
account
[...]
post /register - 201 anonymous expiry:                           FAIL (0.20s)
test/integration/API/User/Account.hs:436:
expiry must in be the future
```
i'm pretty confident this PR will get rid of those.
> Fix: timing in integration test.

- libs/imports/package.yaml
- libs/imports/src/Imports.hs
- libs/metrics-core/package.yaml
- libs/metrics-core/src/Data/Metrics/GC.hs
- libs/wai-utilities/src/Network/Wai/Utilities/Server.hs
- services/spar/package.yaml
I missed this the first time around because I didn't know what all these
stats were for; now that I'm going through the grafana dashboards I know what
they're for and it's worth porting over :)
> Report Garbage Collection & Runtime stats to prometheus

- docs/_config.yml
Same as https://wireapp.github.io/wire-server-deploy/
> Use the Slate theme for https://wireapp.github.io/wire-server/

- deploy/services-demo/README.md
Added instructions for adding the Twilio SID and token and smsSender in the code.
> Documentation changes for Twilio configurations

- deploy/services-demo/conf/brig.demo-docker.yaml
- deploy/services-demo/conf/brig.demo.yaml
- deploy/services-demo/create_test_user.sh
- libs/api-bot/src/Network/Wire/Bot/Settings.hs
- services/galley/package.yaml
- services/nginz/README.md
- tools/api-simulations/loadtest/README.md
- Add additional options to create_test_user script
- Add docs for loadtest exe
- Fixes in config files for loadtest
> Updates to docs/scripts for running load tests

- libs/metrics-wai/package.yaml
- libs/metrics-wai/src/Data/Metrics/Middleware/Prometheus.hs
Note to reviewer: please read commit-by-commit.
> Cannon analytics (3)

- libs/extended/package.yaml
- libs/extended/src/System/Logger/Extended.hs
- snapshots/wire-1.3.yaml
- stack.yaml
> Bump tinylog

- libs/brig-types/src/Brig/Types/Team/LegalHold.hs
- libs/brig-types/src/Brig/Types/Test/Arbitrary.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/LegalHold.hs
- services/galley/src/Galley/API/Swagger.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
- stack.yaml
- change the `ViewLegalHoldService` type to accomodate the web team requirements
- change the way team disablement is hacked so testing can continue
- fix a few misc bugs (mostly in test suite)
> Misc LH updates

- services/galley/src/Galley/API/Swagger.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
- Work-around for issue described here: https://github.com/haskell-servant/servant-swagger/pull/104
- Fix typo
[i know this doesn't have prio, so I did it on my own time.  Couldn't let it go!  :)]
> Fix: swagger tests

- libs/bilge/src/Bilge/Request.hs
- libs/brig-types/src/Brig/Types/Instances.hs
- libs/brig-types/src/Brig/Types/Team/LegalHold.hs
- libs/brig-types/src/Brig/Types/Test/Arbitrary.hs
- libs/brig-types/test/unit/Test/Brig/Types/Common.hs
- libs/galley-types/src/Galley/Types/Teams.hs
- libs/galley-types/src/Galley/Types/Teams/Swagger.hs
- libs/types-common/package.yaml
- libs/types-common/src/Data/LegalHold.hs
- libs/types-common/src/Data/Misc.hs
- services/brig/src/Brig/API/Client.hs
- services/brig/src/Brig/IO/Intra.hs
- services/brig/src/Brig/User/Event.hs
- services/brig/test/integration/API/User/Client.hs
- services/brig/test/integration/API/User/Util.hs
- services/galley/schema/src/V32.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/LegalHold.hs
- services/galley/src/Galley/API/Swagger.hs
- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Data/LegalHold.hs
- services/galley/src/Galley/Data/Queries.hs
- services/galley/src/Galley/External/LegalHoldService.hs
- services/galley/src/Galley/Intra/Client.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
- services/galley/test/integration/API/Util.hs
- services/galley/test/integration/TestHelpers.hs
> Expose legal hold team member status; send client ID with LH event

- libs/brig-types/src/Brig/Types/Team/LegalHold.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/LegalHold.hs
- services/galley/src/Galley/External/LegalHoldService.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
Also; actually parse the base-url and use the path from it properly 😬
> Call LH service to remove users on disable

- libs/brig-types/src/Brig/Types/Team/LegalHold.hs
- libs/brig-types/src/Brig/Types/Test/Arbitrary.hs
- libs/brig-types/test/unit/Test/Brig/Types/Common.hs
- services/galley/src/Galley/External/LegalHoldService.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
We verified that we are passing a valid user token to the renew endpoint.
>  Test that we can renew tokens 

- deploy/services-demo/create_team_members.sh
- deploy/services-demo/create_test_team_members.sh
My attempt at addressing https://github.com/wireapp/wire-server/pull/801#discussion_r304877786
> scripts sending emails

- services/spar/src/Spar/Error.hs
- services/spar/test-integration/Test/LoggingSpec.hs
See https://github.com/wireapp/wire-server/pull/814#issuecomment-518210690
> Disable failing test.

- services/galley/src/Galley/Intra/Client.hs
- services/proxy/src/Proxy/API.hs
- services/spar/src/Spar/App.hs
> Make develop great again!

- tools/nginz_disco/Dockerfile
- tools/nginz_disco/Makefile
- tools/nginz_disco/README.md
- tools/nginz_disco/nginz_disco.sh
Related: https://github.com/wireapp/wire-server-deploy/pull/58
> release nginz_disco

- tools/stern/src/Stern/Intra.hs
Cleanup code (that wasn't ported over when stern was added to wire-server repo).
> [stern] allow galeb returning a 404

- deploy/services-demo/README.md
- mailboxes.json
- services/restund/README.md
> Documentation update for restund and smoketester

- libs/brig-types/src/Brig/Types/Client.hs
- libs/brig-types/src/Brig/Types/Connection.hs
- libs/brig-types/src/Brig/Types/Intra.hs
- libs/galley-types/src/Galley/Types.hs
- libs/galley-types/src/Galley/Types/Teams/Intra.hs
- libs/types-common/src/Data/Id.hs
- services/galley/src/Galley/Data/Types.hs
> Derive Generic everywhere.

- .github/ISSUE_TEMPLATE/question-installation.md
Since we get an increasing number of issues relating to people trying to install wire-server and hitting some problem, this issue template should help us have better context to be able to answer questions.
> add issue template

- services/gundeck/src/Gundeck/Notification/Data.hs
- services/gundeck/src/Gundeck/Push/Native.hs
Instead of chunked mapconcurrently.
I would expect throughput should be better, as a task in the second
batch doesn't have to wait for all tasks from the first batch to
complete. I didn't know this function existed previously.
> Gundeck: Use pooledMapConcurrently

- services/galley/src/Galley/Data.hs
I can reproduce a current failure `Invalid "Batch too large"` as seen on staging, introduced with #911 :
```
galley
Galley integration tests
Main API
create large conversation: 2019-12-17T14:50:39Z, D, Connecting to 127.0.0.1:9042
2019-12-17T14:50:39Z, I, Known hosts: [datacenter1:rack1:127.0.0.1:9042]
2019-12-17T14:50:39Z, I, New control connection: datacenter1:rack1:127.0.0.1:9042#12
[galley] E, request=N/A, ResponseError {reHost = datacenter1:rack1:127.0.0.1:9042, reTrace = Nothing, reWarn = [], reCause = Invalid "Batch too large"}
FAIL
1: 201 =/= 500
Response was:
Response {responseStatus = Status {statusCode = 500, statusMessage = "Internal Server Error"}, responseVersion = HTTP/1.1, responseHeaders = [("Transfer-Encoding","chunked"),("Date","Tue, 17 Dec …
```
> Fix for large conversation creation

- services/galley/src/Galley/API/Update.hs
I will add a test for this later but would like to get this reviewed + merged as is since it's breaking many QA test cases right now...
> Users join conversations as members

- services/spar/src/Spar/Data.hs
context: https://github.com/wireapp/wire-server/pull/875#pullrequestreview-342421346
> Fix complexity issue in cassandra query.

- services/spar/src/Spar/Scim/User.hs
Otherwise you might brick the account
Also some whitepsace issues. And some TODOs about code I don't fully
understand and I should have a closer look at with fisx
> Make sure that someone is SSO user before setting ManagedBy

- services/spar/src/Spar/Scim/Types.hs
- services/spar/src/Spar/Scim/User.hs
not really bugs, but rather good examples of malevolent code obfuscation.  please read commit-by-commit!
> Fix more SCIM bugs

- libs/brig-types/src/Brig/Types/Test/Arbitrary.hs
- libs/brig-types/test/unit/Test/Brig/Types/Common.hs
- libs/galley-types/package.yaml
- libs/galley-types/src/Galley/Types.hs
- libs/galley-types/src/Galley/Types/Swagger.hs
- services/galley/package.yaml
- services/galley/schema/src/Main.hs
- services/galley/schema/src/V37.hs
- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/CustomBackend.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Data/CustomBackend.hs
- services/galley/src/Galley/Data/Instances.hs
- services/galley/src/Galley/Data/Queries.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/CustomBackend.hs
Fixes https://github.com/zinfra/backend-issues/issues/1098
> Implement a 'domain -> custom backend' mapping.

- libs/extended/src/System/Logger/Extended.hs
- services/brig/src/Brig/ZAuth.hs
- services/galley/src/Galley/API/LegalHold.hs
this should be the rest of it...
> Whitespace

- libs/bilge/package.yaml
- libs/bilge/src/Bilge/IO.hs
- services/brig/src/Brig/API/Client.hs
- services/brig/src/Brig/Data/Client.hs
- services/brig/src/Brig/Options.hs
- services/brig/src/Brig/Provider/API.hs
- services/brig/test/integration/API/User/Client.hs
- services/brig/test/integration/Util.hs
- Max number of devices is now configurable in options.
- Running tests against `Application`s of services with modified options has been fixed to allow for requests with content in the body.
> Limit max nr of devices

- libs/federation-util/.ghcid
- libs/federation-util/LICENSE
- libs/federation-util/package.yaml
- libs/federation-util/src/Network/Federation/Util.hs
- libs/federation-util/src/Network/Federation/Util/DNS.hs
- libs/federation-util/src/Network/Federation/Util/Internal.hs
- libs/federation-util/test/Spec.hs
- libs/federation-util/test/Test/DNSSpec.hs
- stack.yaml
* a new shared library for federation-related functions
* implementation of SRV lookup with ordering.
Real integration testing requires creating real DNS records (unless there is a way to mock these?), so I have not included those.
> SRV resolution

- services/brig/brig.integration.yaml
Small doc follow up to https://github.com/wireapp/wire-server/pull/969
> Better docs on brig integration yaml

- snapshots/wire-2.0.yaml
- snapshots/wire-2.1.yaml
- stack.yaml
> Stop using fork of amazonka

- services/gundeck/test/unit/ThreadBudget.hs
https://github.com/zinfra/backend-issues/issues/1166
> Puny attempt at fixing a rarely occurring timing issue.

- Makefile
- docs/developer/editor-setup.md
- some docs on editor integration (thanks @mheinzel for the vim part) (couldn't find anything for sublime, sorry...)
- a make rule needed for the concourse pipeline
> More ormolu

- libs/brig-types/src/Brig/Types/Team/LegalHold.hs
- libs/extended/src/Servant/API/Extended.hs
- libs/ropes/src/Ropes/Aws.hs
- libs/ropes/src/Ropes/Nexmo.hs
- libs/ropes/src/Ropes/Twilio.hs
- libs/wai-utilities/src/Network/Wai/Utilities/Error.hs
- libs/wai-utilities/src/Network/Wai/Utilities/Request.hs
Those files were not actually using any CPP. Now they get formatted, too!
(14 files remaining with actual CPP usage)
> Remove unnecessary LANGUAGE CPP pragmas

- libs/sodium-crypto-sign/package.yaml
> Cleanup compiler warnings

- libs/wai-utilities/src/Network/Wai/Utilities/Request.hs
- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/Clients.hs
- services/galley/src/Galley/API/Create.hs
- services/galley/src/Galley/API/CustomBackend.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/LegalHold.hs
- services/galley/src/Galley/API/Query.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/App.hs
This has already been done for brig in #967, now for galley.
> Refactor: separate HTTP handlers from app logic (galley)

- Makefile
- docs/reference/cassandra-schema.cql
This will ensure that github highlights the code nicely.
> Rename cassandra-schema.txt to cassandra-schema.cql

- services/cannon/src/Cannon/API.hs
- services/gundeck/src/Gundeck/API.hs
- services/gundeck/src/Gundeck/Client.hs
- services/gundeck/src/Gundeck/Notification.hs
- services/gundeck/src/Gundeck/Push.hs
https://github.com/zinfra/backend-issues/issues/1185
all in all this was definitely worth it, but i'm not sure i got 5207159 right, and it would be nice to have some explanation for the status code function.
> Cleanup handlers in gundeck, cannon

- snapshots/wire-2.2.yaml
- stack.yaml
- [PR](https://github.com/wireapp/hsaml2/pull/6)
- [failing test](https://github.com/wireapp/hsaml2/pull/6/commits/39a462f01d923183ea9d7f4ed810597c4d122471)
- [fix](https://github.com/wireapp/hsaml2/pull/6/commits/f5d34ee9493ced01457b65355bb5b8407940b4da)
> Upgrade hsaml2 (fixes utf8 handling in bytestrings).

- CHANGELOG.md
- snapshots/wire-2.0.yaml
- snapshots/wire-2.2.yaml
- stack.yaml
- Fix encoding bug in SAML SSO (#995)
> Release 2020-02-27

- tools/ormolu.sh
- don't choke in check mode, but report all errors.
- in check mode in case of error, give hints on how to fix this.
> Tweak ormolu script

- libs/galley-types/src/Galley/Types/Teams.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/Options.hs
- services/brig/test/integration/API/Settings.hs
- services/brig/test/integration/API/User/Account.hs
https://github.com/zinfra/backend-issues/issues/1187
> Email visibility

- services/spar/test-integration/Spec.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
- stack.yaml
~~blocked by #958, which is fine.  this is not urgent.~~
This was a TODO in a fix from last week, but it's actually quite simple to actually do it.
Also, removed some trailing whitespace.
> Run hscim azure tests

- libs/types-common/src/Data/Qualified.hs
- libs/types-common/test/Main.hs
- libs/types-common/test/Test/Qualified.hs
Should have been part of #997 already.
> types-common: write unit tests for Data.Qualified

- libs/brig-types/src/Brig/Types/Swagger.hs
- libs/galley-types/src/Galley/Types.hs
- libs/galley-types/src/Galley/Types/Swagger.hs
(the list of possible values is added after the description, plus the description was outdated.)
> Fix swagger.

- services/restund/Makefile
Driven by https://github.com/wireapp/restund/pull/3
> Use restund 0.4.14

- libs/api-bot/src/Network/Wire/Bot/Crypto.hs
- libs/galley-types/src/Galley/Types.hs
- libs/galley-types/src/Galley/Types/Proto.hs
- libs/galley-types/src/Galley/Types/Swagger.hs
- services/galley/src/Galley/API.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/test/integration/API/Util.hs
https://github.com/zinfra/backend-issues/issues/1248
missing:
> Allow for `report_missing` in `NewOtrMessage`.

- services/brig/src/Brig/User/Search/Index.hs
This reverts commit 00b573e80cae2b0c8453dc043de68fd9c15b280f.
> Revert hotfix, we deicided to delete the bad data instead

- libs/galley-types/src/Galley/Types/Proto.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Util.hs
This can be reviewed, but the important thing is that the tests pass, not that it gets merged.  I am planning to add a few more unit / qc tests soon.
Fixes https://github.com/zinfra/backend-issues/issues/1248
> Tests for otr end-points.

- libs/brig-types/test/unit/Test/Brig/Roundtrip.hs
- libs/federation-util/src/Network/Federation/Util/Internal.hs
- libs/galley-types/src/Galley/Types.hs
- libs/galley-types/src/Galley/Types/Conversations/Roles.hs
- libs/sodium-crypto-sign/src/Sodium/Crypto/Sign.hsc
- libs/wai-utilities/src/Network/Wai/Utilities/Request.hs
- libs/wai-utilities/src/Network/Wai/Utilities/ZAuth.hs
- services/brig/src/Brig/API.hs
- services/brig/src/Brig/IO/Intra.hs
- services/brig/src/Brig/User/API/Auth.hs
- services/galley/src/Galley/API/Swagger.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/Data.hs
- services/spar/src/Spar/API/Swagger.hs
- services/spar/src/Spar/API/Types.hs
- services/spar/src/Spar/Scim.hs
- services/spar/src/Spar/Scim/Swagger.hs
- services/spar/src/Spar/Scim/Types.hs
- services/spar/test-integration/Test/Spar/DataSpec.hs
- tools/ormolu.sh
The accumulated over time on a branch.
> Some random cleanups and refactorings

- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/App.hs
The original logic was flawed.
> Allow galley to start but issue a warning

- stack.yaml
- tools/db/billing-team-member-backfill/Makefile
- tools/db/billing-team-member-backfill/README.md
- tools/db/billing-team-member-backfill/billing-team-member-backfill.cabal
- tools/db/billing-team-member-backfill/package.yaml
- tools/db/billing-team-member-backfill/src/Main.hs
- tools/db/billing-team-member-backfill/src/Options.hs
- tools/db/billing-team-member-backfill/src/Work.hs
Merge after: https://github.com/wireapp/wire-server/pull/1081
Fixes https://github.com/zinfra/backend-issues/issues/1296
> Add tool to backfill billing_team_member

- .headroom.yaml
- libs/wire-api/src/Wire/API/Swagger.hs
- libs/wire-api/src/Wire/API/Team/SearchVisibility.hs
- libs/wire-api/test/unit/Test/Wire/API/Call/TURN.hs
- services/galley/Makefile
- services/galley/deb-migrate-data/DEBIAN/control
- services/galley/deb-migrate-data/opt/galley-migrate-data/galley-migrate-data
- services/galley/galley.cabal
- services/galley/migrate-data/src/Galley/DataMigration.hs
- services/galley/migrate-data/src/Galley/DataMigration/Types.hs
- services/galley/migrate-data/src/Main.hs
- services/galley/migrate-data/src/V1_BackfillBillingTeamMembers.hs
- services/galley/package.yaml
- services/galley/schema/src/Main.hs
- services/galley/schema/src/V40_CreateTableDataMigration.hs
- stack-deps.nix
Fixes https://github.com/zinfra/backend-issues/issues/1422
One this is merged and we start creating docker images for each build, we can integrate it with helm charts using post-install hooks.
> Add tool to migrate data for galley

- services/brig/src/Brig/Options.hs
- services/brig/test/integration/API/Team.hs
- services/galley/src/Galley/App.hs
- services/galley/src/Galley/Options.hs
Fixes: https://github.com/zinfra/backend-issues/issues/1459
> Change maxTeamSize to Word32 to allow for larger teams

- services/galley/galley.cabal
- services/galley/schema/src/Main.hs
- services/galley/schema/src/V41_TeamNotificationQueue.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/TeamNotifications.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Data/TeamNotifications.hs
- services/galley/src/Galley/Intra/User.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Util.hs
- services/galley/test/integration/TestHelpers.hs
- stack.yaml.lock
Fixes https://github.com/zinfra/backend-issues/issues/1409
> Team event queue for MemberJoin events.

- libs/api-bot/src/Network/Wire/Bot/Assert.hs
- libs/api-client/api-client.cabal
- libs/api-client/package.yaml
- libs/api-client/src/Network/Wire/Client/API/Asset.hs
- libs/api-client/src/Network/Wire/Client/API/Auth.hs
- libs/api-client/src/Network/Wire/Client/API/Client.hs
- libs/api-client/src/Network/Wire/Client/API/Conversation.hs
- libs/api-client/src/Network/Wire/Client/API/Push.hs
- libs/api-client/src/Network/Wire/Client/API/Search.hs
- libs/api-client/src/Network/Wire/Client/API/User.hs
- libs/brig-types/src/Brig/Types/User.hs
- libs/galley-types/src/Galley/Types.hs
- libs/wire-api/src/Wire/API/Conversation.hs
- libs/wire-api/src/Wire/API/Event/Conversation.hs
- libs/wire-api/src/Wire/API/Message.hs
- libs/wire-api/src/Wire/API/User.hs
- tools/api-simulations/loadtest/src/Network/Wire/Simulations/LoadTest.hs
- tools/api-simulations/smoketest/src/Network/Wire/Simulations/SmokeTest.hs
Follow up to https://github.com/zinfra/backend-issues/issues/1416
> api-client: depend on wire-api only

- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/Public.hs
Related: https://github.com/zinfra/backend-issues/issues/1409
> Swagger docs.

- services/brig/src/Brig/API/Public.hs
We should have warnings against this.
> Fix incomplete pattern in code checking email domain (custom extensions)

- libs/brig-types/src/Brig/Types/Common.hs
- libs/wire-api/package.yaml
- libs/wire-api/src/Wire/API/User/Identity.hs
- libs/wire-api/wire-api.cabal
- services/brig/brig.cabal
- services/brig/package.yaml
- services/brig/src/Brig/Email.hs
- services/brig/test/integration/API/User/Account.hs
This was not covered so far and would have caught [the custom extensions bug we had to fix](https://github.com/wireapp/wire-server/pull/1130).
> Test sign up with invalid email

- deploy/services-demo/demo.sh
I had to copy some code from `/services/integration.sh` that should probably be located in something like `/scripts/libs.sh` that could then be sourced by everybody.
Anyway this fixes things for now.
> Fix demo.sh on nixos.

- docs/reference/user/registration.md
- services/brig/brig.integration.yaml
- services/brig/src/Brig/API/Error.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/API/Types.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/Options.hs
- services/brig/test/integration/API/User/Account.hs
- services/brig/test/integration/Util.hs
Fixes https://github.com/zinfra/backend-issues/issues/1491
See 209a08f for context.
> Restrict user creation

- docs/reference/cassandra-schema.cql
- libs/types-common/src/Data/IdMapping.hs
- services/brig/brig.cabal
- services/brig/schema/src/Main.hs
- services/brig/schema/src/V60_AddFederationIdMapping.hs
- services/brig/src/Brig/API/Client.hs
- services/brig/src/Brig/API/Connection.hs
- services/brig/src/Brig/API/Error.hs
- services/brig/src/Brig/API/IdMapping.hs
- services/brig/src/Brig/API/Internal.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/API/Util.hs
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Data/IdMapping.hs
- services/brig/src/Brig/Data/Instances.hs
- services/brig/src/Brig/IO/Intra/IdMapping.hs
- services/brig/test/integration/API/IdMapping.hs
- services/brig/test/integration/Main.hs
- services/galley/src/Galley/API/IdMapping.hs
See https://github.com/zinfra/backend-issues/issues/1178
Similar to https://github.com/wireapp/wire-server/pull/1134, but for Brig. Unfortunately we still have a lot of different ways of doing things between Galley and Brig, so it needed some modifications. There's also no nice place to abstract this out, so I think some duplication is okay here.
> Federation: Implement ID mapping (brig)

- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/IO/Intra.hs
- services/brig/src/Brig/User/Event.hs
- services/spar/src/Spar/Scim/Auth.hs
- services/spar/src/Spar/Scim/Swagger.hs
- services/spar/src/Spar/Scim/Types.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
- services/spar/test-integration/Test/Spar/Scim/AuthSpec.hs
- services/spar/test-integration/Util/Core.hs
These are a few very low-hanging fruits, please read commit-by-commit when reviewing, it's quite self-contained.
> Cleanup (mostly spar)

- libs/wire-api/package.yaml
- libs/wire-api/src/Wire/API/Call/Config.hs
- libs/wire-api/test/unit/Test/Wire/API/Call/Config.hs
- libs/wire-api/wire-api.cabal
Fixes https://github.com/zinfra/backend-issues/issues/1453
> Ensure `sft_servers` is never set to `null` in /calls/config

- tools/rebase-onto-formatter.sh
Fixes https://github.com/zinfra/backend-issues/issues/1651
> work on rebase-formatter script

- libs/wire-api-federation/LICENSE
- libs/wire-api-federation/package.yaml
- libs/wire-api-federation/src/Wire/API/Federation/Event.hs
- libs/wire-api-federation/src/Wire/API/Federation/Util/Aeson.hs
- libs/wire-api-federation/test/Spec.hs
- libs/wire-api-federation/test/Test/SerializationSpec.hs
- libs/wire-api-federation/wire-api-federation.cabal
- libs/wire-api/src/Wire/API/Event/Conversation.hs
- stack.yaml
Part 1 of https://github.com/zinfra/backend-issues/issues/1213#issuecomment-659237907
> create wire-api-federation with definition of MemberJoin event

- tools/rebase-onto-formatter.sh
The previous approach kept the commit message, but overwrote the author of the commits being rebased.
This is fixed by using `git commit --reuse-message`.
I tested this on a branch already and it seems to work as expected.
> Fix: preserve commit author in rebase-onto-formatter.sh

- libs/types-common/src/Data/Range.hs
- libs/wire-api/src/Wire/API/User.hs
- libs/wire-api/src/Wire/API/User/Profile.hs
- services/galley/test/integration/API/Util.hs
- services/spar/src/Spar/App.hs
- services/spar/src/Spar/Intra/Brig.hs
- services/spar/src/Spar/Scim/Types.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Util/Scim.hs
Some more or less trivial code simplifications.
This is the first step in taking apart the completely unhinged https://github.com/wireapp/wire-server/pull/1181.
> spar cleanup (1)

- libs/wire-api/src/Wire/API/User.hs
Small follow-up to #1197 required for solving https://github.com/zinfra/backend-issues/issues/1365
> Scim-created users are never ephemeral.

- libs/wire-api/src/Wire/API/User.hs
- libs/wire-api/src/Wire/API/User/Profile.hs
- libs/wire-api/test/unit/Test/Wire/API/Roundtrip/Aeson.hs
- libs/wire-api/test/unit/Test/Wire/API/Roundtrip/ByteString.hs
- services/brig/src/Brig/API/Internal.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/User/Handle.hs
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/App.hs
- services/spar/src/Spar/Error.hs
- services/spar/src/Spar/Intra/Brig.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
Motivated by https://github.com/zinfra/backend-issues/issues/1365, https://github.com/zinfra/backend-issues/issues/1572.
Please read the commit messages for details.
None of this should change behavior / semantics.
All tests passed locally.
> Refactor misc things.

- docs/reference/cassandra-schema.cql
- services/spar/schema/src/Main.hs
- services/spar/schema/src/V11.hs
- services/spar/spar.cabal
- services/spar/src/Spar/Data.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
Fixes https://github.com/zinfra/backend-issues/issues/1631
> Remove unused scim_user table

- services/gundeck/src/Gundeck/Push/Native/Serialise.hs
Fixes https://github.com/zinfra/backend-issues/issues/889 (part 2 and 3)
> Use mutable content for non-voip notifications and update limits

- services/gundeck/gundeck.cabal
- services/gundeck/package.yaml
- services/gundeck/src/Gundeck/Push/Native.hs
- services/gundeck/src/Gundeck/Push/Native/Serialise.hs
- services/gundeck/test/bench/Main.hs
- services/gundeck/test/unit/Native.hs
This is left-over from https://github.com/zinfra/backend-issues/issues/1797.  Could be useful in the future, and should be harmless for the same reasons as in https://github.com/wireapp/wire-server/pull/1220.
Can be read commit-by-commit.
> Yet more debug logs

- docs/reference/config-options.md
Spun out of: https://github.com/wireapp/wire-server-deploy/pull/276
> [brig:docs] Add a note on feature flag: setEmailVisibility

- docs/reference/provisioning/scim-token.md
Fixes https://github.com/zinfra/backend-issues/issues/1294
> Correct outdated docs.

- tools/bonanza/src/Bonanza/Parser/Nginz.hs
- tools/bonanza/test/unit/Test/Bonanza/Arbitrary.hs
See also https://github.com/zinfra/backend-issues/issues/1863
and https://github.com/wireapp/wire-server-deploy/pull/376
> [bonanza] also parse 'tracestate' nginx log

- services/spar/spar.integration.yaml
- services/spar/src/Spar/Types.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
Fixes https://github.com/zinfra/backend-issues/issues/1875
> Introduce config brigSettingsTeamInvitationTimeout and use in test

- services/spar/src/Spar/App.hs
- services/spar/src/Spar/Error.hs
- services/spar/src/Spar/Intra/Brig.hs
- services/spar/src/Spar/Intra/Galley.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
Fixes https://github.com/zinfra/backend-issues/issues/1613
> Spar: Forward errors from brig

- services/federator/federator.cabal
- services/federator/federator.integration.yaml
- services/federator/package.yaml
- services/federator/src/Federator/Options.hs
- services/federator/src/Federator/Run.hs
- services/federator/src/Federator/Util.hs
- services/federator/test/unit/Main.hs
- services/federator/test/unit/Test/Federator/Options.hs
(extracted from #1261 after discussion with @akshaymankar  )
> Federator: allow_list configuration options

- services/brig/src/Brig/API/Public.hs
Order and naming of the endpoint definitions were inconsistent.
Wanted to fix this quickly before building more stuff on top of the API.
I can rebase https://github.com/wireapp/wire-server/pull/1270 once this is merged (or the other way around).
> Refactor brig Servant API for consistency

- libs/hscim/hscim.cabal
- libs/hscim/package.yaml
- libs/hscim/server/Main.hs
- libs/hscim/src/Web/Scim/Capabilities/MetaSchema.hs
- libs/hscim/src/Web/Scim/Filter.hs
- libs/hscim/src/Web/Scim/Schema/Common.hs
- libs/hscim/src/Web/Scim/Schema/User.hs
- libs/hscim/src/Web/Scim/Schema/User/Address.hs
- libs/hscim/src/Web/Scim/Schema/User/Email.hs
- libs/hscim/test/Test/Schema/UserSpec.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
- services/spar/test-integration/Util/Scim.hs
- services/spar/test-scim-suite/update.jq
Hopefully fixes https://wearezeta.atlassian.net/browse/SQSERVICES-154
> SCIM: Allow strings for boolean values

- services/spar/src/Spar/Scim/User.hs
> Better error message.

- stack.yaml.lock
Align stack.yaml.lock with stack.yaml.
> Generate stack.yaml.lock from stack.yaml

- CHANGELOG.md
- deploy/services-demo/create_test_team_scim.sh
- libs/types-common/package.yaml
- libs/types-common/src/Util/Logging.hs
- libs/types-common/types-common.cabal
- nix/sources.json
- services/brig/src/Brig/API/Error.hs
- services/brig/src/Brig/API/Internal.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/API/Types.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/API/Util.hs
- services/brig/src/Brig/Team/API.hs
- services/spar/src/Spar/Intra/Brig.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
- services/spar/test-integration/Util/Core.hs
- services/spar/test-integration/Util/Email.hs
- shell.nix
> Release 2020-01-12

- nix/sources.json
- nix/sources.nix
I did this for getting HLS 0.8.0.0
> Upgrade nixpkgs and niv

- libs/hscim/src/Web/Scim/Filter.hs
- services/spar/src/Spar/Scim/User.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-194
> Scim: Change log level to Warning & format filter logs

- CHANGELOG.md
- charts/federator/.helmignore
- charts/federator/Chart.yaml
- charts/federator/templates/configmap.yaml
- charts/federator/templates/deployment.yaml
- charts/federator/templates/service.yaml
- charts/federator/values.yaml
- charts/wire-server/requirements.yaml
- charts/wire-server/values.yaml
- hack/bin/set-wire-server-image-version.sh
- hack/helm_vars/wire-server/values.yaml
- libs/hscim/src/Web/Scim/Filter.hs
- nix/sources.json
- nix/sources.nix
- services/brig/test/integration/API/Search.hs
- services/federator/src/Federator/API.hs
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/Scim/Auth.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
This release contains bugfixes and internal changes.
* [federation] Add helm chart for the federator (#1317)
* [SCIM] Accept any query string for externalId (#1330)
* [SCIM] Allow at most one identity provider (#1332)
* [SCIM] Change log level to Warning & format filter logs (#1331)
* Improve flaky integration tests (#1333)
* Upgrade nixpkgs and niv (#1326)
> Release 2021-01-15

- services/spar/schema/src/Main.hs
- services/spar/schema/src/V12.hs
- services/spar/spar.cabal
- services/spar/src/Spar/Data.hs
- services/spar/src/Spar/Scim/User.hs
Note: This PR requires a migration of spar's DB.
https://wearezeta.atlassian.net/browse/SQSERVICES-268
> Add spar.scim_external table and follow changes from spar.scim_external_ids

- stack.yaml
No change in formatting of the existing code, but some [nice bug fixes](https://hackage.haskell.org/package/ormolu-0.1.4.1/changelog).  (Ormolu formatting seems to stabilize.  Good.)
> Bump ormolu version.

- stack.yaml.lock
> Commit missing stack.yaml.lock

- charts/sftd/README.md
- charts/wire-server/values.yaml
This makes adding of `sftd` a non-breaking change
> sftd: Make install as part of umbrella-chart opt-in instead of opt-out

- stack.yaml
- stack.yaml.lock
I'm hoping to fix a dsig bug in hsam2 here.  Hold your breath...
> Bump hsaml2, saml2-web-sso to support envelopping saml signatures.

- docs/reference/user/registration.md
depends on https://github.com/wireapp/wire-docs/pull/105
> Move docs around.

- libs/galley-types/src/Galley/Types/Teams.hs
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/Error.hs
- services/spar/src/Spar/Intra/Brig.hs
- services/spar/src/Spar/Intra/Galley.hs
(before, team ownership was required in some cases, but that was a bug.)
> Fix: spar permissions for idp crud operations.

- services/federator/src/Federator/Discovery.hs
As documented in
https://hackage.haskell.org/package/dns-4.0.1/docs/Network-DNS-Types.html#t:DNSError
> federator: Report NameError as SrvNotAvailable

- libs/wire-api/src/Wire/API/Swagger.hs
- libs/wire-api/src/Wire/API/User/Client.hs
- services/brig/src/Brig/API/Client.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/test/integration/API/User/Client.hs
- services/brig/test/integration/API/User/Util.hs
This PR refactors 2 endpoints and creates stubs for qualified versions
- `/users/{uid}/clients` with qualified version `/users/{domain}/{uid}/clients`
- `/users/{uid}/clients/{client}` with qualified version `/users/{domain}/{uid}/clients/{client}`
> [federation] brig: refactor GET /users/*/clients endpoints

- CHANGELOG.md
Keep the CHANGELOG.md in sync with the documentation in https://github.com/wireapp/wire-docs/pull/126
> Update release notes with data migration for SCIM

- libs/wire-api/src/Wire/API/User.hs
- services/brig/test/integration/API/User/Account.hs
This adds a test for the (qualified) `/list-user` endpoint and fixes a bug in the JSON parser for the body of that request.
> Fix FromJSON instance of ListUsersQuery

- charts/account-pages/values.yaml
- charts/team-settings/values.yaml
- charts/webapp/values.yaml
(Updated container image tags)
> Bump webapp and team-settings versions

- CHANGELOG.md
- docs/reference/team/legalhold.md
- libs/galley-types/src/Galley/Types/Teams.hs
- libs/types-common/src/Data/LegalHold.hs
- libs/wire-api/src/Wire/API/Team/Member.hs
- services/galley/src/Galley/API/Error.hs
- services/galley/src/Galley/API/LegalHold.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Swagger.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/API/Teams/Features.hs
- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Options.hs
- services/galley/src/Galley/Run.hs
- services/galley/test/integration/API/MessageTimer.hs
- services/galley/test/integration/API/SQS.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Teams/Feature.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-402
see CHANGELOG.md for the jist of it.
> LH consent

- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Data/Queries.hs
https://github.com/wireapp/wire-server/pull/1507#discussion_r639484134
https://github.com/wireapp/wire-server/pull/1507#discussion_r639176423
> Fix slow cassandra query.

- services/galley/src/Galley/API/Create.hs
This replaces manual lifting to a Union type with a call to `Servant.respond`, helped by some annotations. Thanks @akshaymankar for showing me how to make this work.
> Use Servant.respond instead of explicit SOP

- docs/reference/user/rich-info.md
remove any mention of the deprecated API
> Update Rich Info docs

- Makefile
I noticed these aren't getting bumped and synced anymore
> Add some missing charts

- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/API/Util.hs
It used to run in a monad, presumably to do some logging, but that is not the case anymore. This gets rid of the monad and makes the code simpler.
> Make botsAndUsers pure

- services/nginz/Dockerfile
Also:
- Run apk update in a separate RUN command
- Do not double install libsodium-dev and llvm-libunwind-dev
- Add comment to explain the 'curl -h'
> nginz/Dockerfile: Run 'apk add' verbosely for debugging

- services/cargohold/src/CargoHold/API/Public.hs
- services/cargohold/src/CargoHold/S3.hs
- services/cargohold/test/integration/API/V3.hs
This reverts commit 20d0028c845f7a1b466ebabc04e07e7df1eb7a94.
> Revert "Merge pull request from GHSA-hxmc-g6x8-h2mh"

- services/cargohold/src/CargoHold/API/Public.hs
- services/cargohold/src/CargoHold/S3.hs
- services/cargohold/test/integration/API/V3.hs
Reverts wireapp/wire-server#1571
> Revert "Revert "Merge pull request from GHSA-hxmc-g6x8-h2mh""

- services/galley/src/Galley/API/Federation.hs
Addressing a review comment in #1547.
> Remove stale FUTUREWORK comment

- docs/developer/cassandra-interaction.md
Feel free to suggest more links.
> initial few anti-patterns and links about cassandra

- docs/developer/dependencies.md
> docs: submodules

- services/brig/src/Brig/Run.hs
- services/brig/test/integration/API/User/Client.hs
- services/brig/test/integration/API/User/Util.hs
- services/brig/test/integration/Util.hs
- services/galley/src/Galley/Run.hs
> Brig: Maintain backward compat for body parse errors from servant

- docs/reference/cassandra-schema.cql
> Update cassandra dump

- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
Member join event propagation is now implemented.
> Remove WIP addendum from addMembers endpoint

- services/brig/test/integration/API/Search.hs
> Brig/int/Search: Add debug info for sporadic failures

- services/galley/src/Galley/API/Util.hs
> Galley: Delete UnionT

- CHANGELOG.md
- docs/reference/cassandra-schema.cql
- libs/galley-types/src/Galley/Types/Teams.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- libs/wire-api/src/Wire/API/Team/Feature.hs
- libs/wire-api/test/unit/Test/Wire/API/Roundtrip/Aeson.hs
- services/galley/galley.cabal
- services/galley/schema/src/Main.hs
- services/galley/schema/src/V51_FeatureFileSharing.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Teams/Features.hs
- services/galley/src/Galley/Data.hs
- services/galley/src/Galley/Data/TeamFeatures.hs
- services/galley/test/integration/API/Teams/Feature.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-622
[swagger.json.zip](https://github.com/wireapp/wire-server/files/6793721/swagger.json.zip)
> Allow disabeling file sharing on a per-team basis.

- CHANGELOG.md
- libs/wire-api/src/Wire/API/Event/FeatureConfig.hs
- libs/wire-api/src/Wire/API/Team/Feature.hs
- libs/wire-api/test/golden/testObject_FeatureConfigEvent_1.json
- libs/wire-api/test/golden/testObject_FeatureConfigEvent_2.json
- libs/wire-api/test/golden/testObject_FeatureConfigEvent_3.json
- libs/wire-api/test/unit/Test/Wire/API/Golden/Manual.hs
- libs/wire-api/test/unit/Test/Wire/API/Golden/Manual/FeatureConfigEvent.hs
- libs/wire-api/wire-api.cabal
- services/galley/src/Galley/API/Teams/Features.hs
- services/galley/src/Galley/Intra/Push.hs
- services/galley/test/integration/API/Teams/Feature.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-622
Related: https://github.com/wireapp/wire-server/pull/1652, https://github.com/wireapp/wire-server/pull/1652
> Emit event notification for file sharing feature update.

- services/galley/src/Galley/API/Query.hs
- services/galley/src/Galley/Data.hs
> refactor: remove duplicate function

- libs/hscim/CHANGELOG
- libs/hscim/hscim.cabal
- libs/hscim/package.yaml
I needed to make these changes for a hackage release, and the seem generally beneficial to me.
I deliberately did not make any CHANGELOG entry, I think it's not important enough to be in the release notes.
> Changes to libs/hscim metadata.

- CHANGELOG-draft.md
- services/galley/src/Galley/API/Query.hs
- services/galley/test/integration/API.hs
Also add a few integration tests. Depends on #1703
> Avoid remote calls to get conversation when it is not found locally

- charts/federator/values.yaml
- libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs
- libs/wire-api-federation/src/Wire/API/Federation/GRPC/Types.hs
- services/brig/src/Brig/API/Federation.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/Federation/Client.hs
- services/brig/test/integration/Federation/End2end.hs
- services/federator/src/Federator/Discovery.hs
- services/federator/src/Federator/ExternalServer.hs
- services/federator/src/Federator/Remote.hs
- services/federator/src/Federator/Run.hs
- services/galley/src/Galley/API/Create.hs
- services/galley/src/Galley/API/Query.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/src/Galley/API/Util.hs
- services/galley/src/Galley/Data.hs
> Update FUTUREWORKS as discussed

- CHANGELOG-draft.md
- charts/sftd/Chart.yaml
> Bump sftd to 2.0.127

- changelog.d/2-features/blacklist-change-phone
- services/brig/src/Brig/API/Error.hs
- services/brig/src/Brig/API/Types.hs
- services/brig/src/Brig/API/User.hs
- services/brig/test/integration/API/User/Account.hs
> Allow blacklisting rules to changing phone numbers

- .github/pull_request_template.md
> Reword PR template

- changelog.d/6-federation/convention
- docs/developer/federation-api-conventions.md
- libs/wire-api-federation/src/Wire/API/Federation/API/Brig.hs
- libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs
- services/galley/src/Galley/API/Federation.hs
- services/galley/src/Galley/API/Message.hs
- services/galley/src/Galley/API/Util.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Federation.hs
- services/galley/test/integration/API/Util.hs
https://wearezeta.atlassian.net/browse/SQCORE-918
> Establish conventions for federation APIs

- changelog.d/6-federation/search-endpoint
- libs/wire-api-federation/src/Wire/API/Federation/API/Brig.hs
- services/brig/src/Brig/API/Federation.hs
- services/brig/src/Brig/Federation/Client.hs
- services/brig/src/Brig/User/API/Search.hs
- services/brig/test/integration/API/Federation.hs
- services/brig/test/integration/API/Search.hs
https://wearezeta.atlassian.net/browse/SQCORE-915
> Remove ES specific details from the federation search endpoint

- changelog.d/5-internal/raw-effect-row
- services/spar/package.yaml
- services/spar/spar.cabal
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/App.hs
- services/spar/src/Spar/Scim.hs
- services/spar/src/Spar/Scim/Auth.hs
- services/spar/src/Spar/Scim/User.hs
- services/spar/src/Spar/Sem/SAMLUser.hs
- services/spar/src/Spar/Sem/SAMLUser/Cassandra.hs
- services/spar/test-integration/Util/Core.hs
Cloned from #1775 (forks are not picked up by our CI); see description there.
>  Add polysemy to spar; promote the SAMLUser CRUD interface to an effect

- changelog.d/5-internal/abstract-multi-table-paging
- libs/wire-api/src/Wire/API/Conversation.hs
- libs/wire-api/src/Wire/API/Routes/MultiTablePaging.hs
- libs/wire-api/test/unit/Test/Wire/API/Golden/Manual/ConversationPagingState.hs
- libs/wire-api/test/unit/Test/Wire/API/Golden/Manual/GetPaginatedConversationIds.hs
- libs/wire-api/wire-api.cabal
- services/galley/src/Galley/API/Query.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Util.hs
> Abstract out multi-table-pagination

- changelog.d/mk-changelog.sh
> mk-changelog.sh: ignore emacs backup files.

- changelog.d/5-internal/test-fed-message-multi-domain
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Federation.hs
- services/galley/test/integration/API/Util.hs
https://wearezeta.atlassian.net/browse/FS-52
> Test sending message to multiple remote domains

- services/galley/test/integration/API/Federation.hs
- services/galley/test/integration/API/Util.hs
Feedback in #1872 
No changelog.
> galley: Refactor Federation.onUserDeleted integration test

- changelog.d/4-docs/doc-more-helm-deploy
- docs/developer/how-to.md
- hack/bin/set-chart-image-version.sh
> Federation: Document how to deploy local builds

- deploy/services-demo/conf/nginz/nginx.conf
> Add /list-connections to the local nginz config

- changelog.d/0-release-notes/minio-helm
> Add note about manual action required to ugprade fake-aws-s3

- services/brig/src/Brig/Options.hs
- services/galley/src/Galley/API/CustomBackend.hs
https://wearezeta.atlassian.net/browse/BE-534
> Enrich haddocks with cross-references.

- charts/elasticsearch-ephemeral/templates/es.yaml
Without this fluent-bit cannot store logs into ES.
No changelog.
> charts/elasticsearch-ephemeral: Allow indices for logs to be created automatically

- charts/webapp/values.yaml
> Update webapp version in Helm chart

- changelog.d/5-internal/backoffice-suspend-teams
- tools/stern/src/Stern/API.hs
- tools/stern/src/Stern/Intra.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-772
> Suspend/unsuspend teams in backoffice/stern.

- changelog.d/4-docs/fix-swagger-2
- libs/wire-api/src/Wire/API/Conversation.hs
https://wearezeta.atlassian.net/browse/BE-538
see also: https://github.com/GetShopTV/swagger2/issues/229
> Fix typo in swagger.

- changelog.d/0-release-notes/update-sftd
- charts/sftd/Chart.yaml
This new version is needed for an on-premise deployment to be delivered next week.
> Update sftd to 2.1.19

- changelog.d/5-internal/pr-2023
- services/brig/src/Brig/API/Public.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-996
> Return specific error when a domain is blocked

- changelog.d/2-features/helm-brig-setDefaultLocale
- charts/brig/templates/configmap.yaml
- charts/brig/values.yaml
https://wearezeta.atlassian.net/browse/JCT-82
> charts/brig: Make setDefaultLocale configurable

- Makefile
- changelog.d/5-internal/restund-chart-followup
> Publish restund helm chart

- nix/overlays/wire-server.nix
> nix/cryptobox: Fix cargoSha256

- changelog.d/0-release-notes/update-sft-urls
https://wearezeta.atlassian.net/browse/FS-338
https://github.com/wireapp/wire-server/pull/2030
> Add release notes for #2030

- changelog.d/5-internal/bump-hsaml2
- stack.yaml
https://wearezeta.atlassian.net/browse/SQSERVICES-1248
> Bump hsaml2 dependency

- changelog.d/0-release-notes/bump_webapp
- charts/webapp/values.yaml
> bump webapp version.

- CHANGELOG.md
- changelog.d/0-release-notes/bump_webapp
- charts/webapp/values.yaml
- libs/wire-api/package.yaml
- libs/wire-api/src/Wire/API/Conversation.hs
- libs/wire-api/wire-api.cabal
- services/brig/test/integration/API/Provider.hs
- services/galley/test/integration/API.hs
* Bump the webapp version. (#2082)
* Additional integration testing for conversation access control. (#2057)
> Release 2022-01-28

- charts/webapp/values.yaml
> ship M2 compatible webapp.

- changelog.d/5-internal/pr-2092
- libs/wire-api/src/Wire/API/ErrorDescription.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- services/brig/test/integration/API/Team/Util.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Public/Servant.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/test/integration/API/Teams.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1011
> SQSERVICES-1011-Servantify-Galley-Team-API

- changelog.d/5-internal/pr-2099
- charts/brig/templates/configmap.yaml
- charts/brig/values.yaml
- services/brig/brig.integration.yaml
https://wearezeta.atlassian.net/browse/SQSERVICES-1239
> SQSERVICES 1239 remove unused locale setting in brig's values.yaml

- changelog.d/6-federation/restund
- charts/restund/Chart.yaml
> Revert restund to 0.4.17

- libs/wire-api/src/Wire/API/ErrorDescription.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1174
> Updat Swagger docs with error responses for `add-member` endpoint

- changelog.d/5-internal/i-tests
- services/spar/test-integration/Test/Spar/APISpec.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
- services/spar/test-integration/Util/Core.hs
Trying to reproduce https://wearezeta.atlassian.net/browse/SQSERVICES-1279, but failing: everything seems to be in order.  I would like to add these tests anyway.
> Extend test suite slightly

- changelog.d/2-features/federated-freetext-search
- services/brig/src/Brig/API/Federation.hs
- services/brig/src/Brig/Federation/Client.hs
- services/brig/src/Brig/User/API/Search.hs
- services/brig/src/Brig/User/Search/SearchIndex.hs
- services/brig/test/integration/API/Federation.hs
https://wearezeta.atlassian.net/browse/FS-412
> Add freetext search results to "search-users" federation endpoint

- services/galley/test/integration/API/Teams/LegalHold.hs
According to the boy scout rule, we cleaned up some tests a bit (to increase their maintainability, readability, ...).
> Cleanup after review

- libs/wire-api/src/Wire/API/Team.hs
- services/galley/test/integration/API/Teams.hs
https://wearezeta.atlassian.net/browse/SQCORE-1252
> support default as icon update

- cabal.project
- services/gundeck/test/bench/Main.hs
- tools/convert-to-cabal/generate.sh
> Enable benchmarks when building with cabal

- changelog.d/5-internal/queued-notification-schemas
- libs/types-common/package.yaml
- libs/types-common/src/Data/Json/Util.hs
- libs/types-common/types-common.cabal
- libs/wire-api/src/Wire/API/Notification.hs
- libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/QueuedNotificationList_user.hs
- libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/QueuedNotification_user.hs
- libs/wire-api/test/unit/Test/Wire/API/Roundtrip/Aeson.hs
- services/galley/test/integration/API/Util.hs
- services/gundeck/test/integration/API.hs
Motivation: Unit tests for roundtrip tests are slow
> Add ToSchema instances for QueuedNotification and QueuedNotificationList

- build/ubuntu/Dockerfile.builder
- changelog.d/5-internal/ubuntu20-add-cabal
> Dockerfile.builder: Add "cabal update" step

- cabal.project
- stack.yaml
- tools/db/assets/README.md
- tools/db/assets/app/Main.hs
- tools/db/assets/assets.cabal
- tools/db/assets/src/Assets/Lib.hs
`assets` is a small tool that scans the brig user table, searches for mal-formatted asset keys and prints them.
> Asset key validation

- changelog.d/5-internal/accountpages-digest
- charts/account-pages/templates/deployment.yaml
> account-pages chart: add image digest option

- changelog.d/5-internal/more-test-labels
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Teams.hs
https://wearezeta.atlassian.net/browse/FS-488
Co-authored-by: Sven Jost <sven@wire.com>
This only adds comments to integration tests; hopefully not controversial.
> More test labels (#2185)

- changelog.d/2-features/team-create-shell-script
- deploy/services-demo/create_team.sh
- deploy/services-demo/create_team_request_code.sh
See the comments below for how this is used, and why.
> Script for creating a team with owner via the public API.

- services/galley/src/Galley/API/Util.hs
- services/galley/src/Galley/Data/Conversation.hs
- services/galley/src/Galley/Data/Types.hs
Noticed some example dead code from running weeder, see https://github.com/wireapp/wire-server/pull/2223
> delete some dead code in galley

- changelog.d/0-release-notes/pr-2231
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- services/galley/src/Galley/API/Public/Servant.hs
- services/galley/src/Galley/API/Query.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Util/TeamFeature.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1405
> Sqservices 1405 be endpoint to verify guest links allowed on other team

- CHANGELOG.md
- changelog.d/0-release-notes/webapp-upgrade
- charts/webapp/values.yaml
* Upgrade webapp version to 2022-03-30-production.0-v0.29.2-0-d144552 (#2246)
> Release 2022 03 30 16 50

- cabal.project
- changelog.d/5-internal/bump-hsaml2
- stack.yaml
- stack.yaml.lock
https://github.com/wireapp/hsaml2/pull/10
Only trivial changes and changes in the test suite.
> Bump hsaml2.

- changelog.d/5-internal/brig-no-monadmask
- services/brig/src/Brig/API/Client.hs
- services/brig/src/Brig/API/Connection.hs
- services/brig/src/Brig/API/Connection/Remote.hs
- services/brig/src/Brig/API/Handler.hs
- services/brig/src/Brig/API/MLS/KeyPackages.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/IO/Intra.hs
- services/brig/src/Brig/Provider/API.hs
- services/brig/src/Brig/Provider/RPC.hs
- services/brig/src/Brig/Team/API.hs
- services/brig/src/Brig/Team/Util.hs
- services/brig/src/Brig/User/API/Search.hs
- services/brig/src/Brig/User/Auth.hs
- services/brig/src/Brig/User/EJPD.hs
The title says it all. This is part of introducing Polysemy to Brig.
> [Polysemy] Drop The MonadMask Instance For AppT in Brig

- changelog.d/3-bug-fixes/FS-491-helm-chart-mapping
- charts/galley/templates/configmap.yaml
https://wearezeta.atlassian.net/browse/FS-491
> Add missing helm chart mapping for inbound search visibility

- deploy/services-demo/conf/nginz/nginx.conf
Fix a syntax error in the demo nginx configuration file.
> Fix demo nginx config syntax

- changelog.d/2-features/helm-allow-filter-cass-dc
- charts/brig/templates/configmap.yaml
- charts/galley/templates/configmap.yaml
- charts/gundeck/templates/configmap.yaml
- charts/spar/templates/configmap.yaml
> [helm-charts] Allow filtering cassandra nodes by datacenter

- changelog.d/5-internal/brig-index-logs
- services/brig/src/Brig/Index/Migrations.hs
- services/brig/src/Brig/Index/Migrations/Types.hs
> Print more logs while migrating data in Elasticsearch

- changelog.d/2-features/mls
- changelog.d/5-internal/mls-tests
- libs/wire-api/src/Wire/API/MLS/Message.hs
- services/galley/galley.cabal
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/MLS.hs
- services/galley/test/integration/API/MLS/Util.hs
- Split messaging test setup to its own module
- Remove unused functions
- Fix some FUTUREWORKs and remove stale ones
- Add more assertions
> MLS test additions and cleanups

- changelog.d/5-internal/SQSERVICES-1074-servantify-galley_misc-3
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/LegalHold.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1074
> Servantify Galley Misc. 3

- changelog.d/5-internal/pr-2286
- libs/wire-api/src/Wire/API/CustomBackend.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- libs/wire-api/src/Wire/API/Swagger.hs
- libs/wire-api/src/Wire/API/Team/SearchVisibility.hs
- services/galley/src/Galley/API/CustomBackend.hs
- services/galley/src/Galley/API/Public.hs
- services/galley/src/Galley/API/Public/Servant.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/API/Teams/Features.hs
- services/galley/test/integration/API/CustomBackend.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1014
> SQSERVICES-1014-backend-servantify-galley-team-feature-flags-api

- docs/src/release-notes.rst
> Release notes for helm chart version 4.9.0 in docs

- changelog.d/4-docs/pr-2336
- docs/src/how-to/install/web-app-settings.md
> Sqservices 1507 doc 1 11

- changelog.d/5-internal/libzauth-nix-sha256
- nix/pkgs/zauth/default.nix
> libzauth: Update sha256 for source in nix expression

- .gitignore
No need to add dev env specific files to the repository.
> Added dir-locals.el to gitignore.

- changelog.d/4-docs/pr-2356
- docs/src/how-to/scim/index.rst
- docs/src/how-to/single-sign-on/index.rst
- docs/src/understand/single-sign-on/main.rst
[SQSERVICES-1518](https://wearezeta.atlassian.net/browse/SQSERVICES-1518)
> Moved docs from how-tos to the SSO page.

- changelog.d/5-internal/remove-unused-datatype
- services/brig/src/Brig/Options.hs
> Remove unused data type AllowedUserSearch

- dev-packages.nix
Should've been there all along. :)
> Added ghcid to nix env.

- Makefile
A suggestion for using ghcid more easily. We can expand on it as necessary.
> Added ghcid to makefile.

- services/brig/brig.cabal
- services/brig/package.yaml
- services/brig/src/Brig/API/Public.hs
https://github.com/haskell/haskell-language-server/issues/481
> Workaround for HLS not finding files while running template haskell

- docs/src/how-to/associate/custom-backend-for-desktop-client.rst
> SQSERVICES-1495-improve-docs-follow-up

- changelog.d/2-features/no-aws-creds
No changelog for changelog changes.
> Fix typo in changelog

- charts/nginx-ingress-services/templates/certificate_federator.yaml
> Ensure federator certificate is a valid v1 Certificate resource

- docs/src/security-responses/2022-05_website_outage.md
This PR adds a Security Response about the wire.com outage on 2022-05-23
This PR is documentation/publication only.
> Add security response about wire.com outage on 2022-05-23

- docs/src/_templates/layout.html
> fix: missing docs logo

- services/gundeck/src/Gundeck/API/Internal.hs
- services/gundeck/src/Gundeck/API/Public.hs
- services/gundeck/src/Gundeck/Aws.hs
- services/gundeck/src/Gundeck/Aws/Arn.hs
- services/gundeck/src/Gundeck/Aws/Sns.hs
- services/gundeck/src/Gundeck/Env.hs
- services/gundeck/src/Gundeck/Instances.hs
- services/gundeck/src/Gundeck/Monad.hs
- services/gundeck/src/Gundeck/Notification.hs
- services/gundeck/src/Gundeck/Notification/Data.hs
- services/gundeck/src/Gundeck/Presence.hs
- services/gundeck/src/Gundeck/Presence/Data.hs
- services/gundeck/src/Gundeck/Push.hs
- services/gundeck/src/Gundeck/Push/Data.hs
- services/gundeck/src/Gundeck/Push/Native.hs
- services/gundeck/src/Gundeck/Push/Native/Serialise.hs
- services/gundeck/src/Gundeck/Push/Websocket.hs
- services/gundeck/src/Gundeck/React.hs
- services/gundeck/src/Gundeck/ThreadBudget/Internal.hs
- services/gundeck/src/Gundeck/Util.hs
- services/gundeck/src/Gundeck/Util/DelayQueue.hs
- services/gundeck/test/bench/Main.hs
- services/gundeck/test/integration/Main.hs
- services/gundeck/test/integration/Util.hs
- services/gundeck/test/unit/DelayQueue.hs
- services/gundeck/test/unit/Json.hs
- services/gundeck/test/unit/Native.hs
As it says on the tin. There's one spot that might be contentions, so keep an eye out.
> Linted Gundeck

- docs/src/understand/single-sign-on/main.rst
This is a tiny tweak of the "scim via curl" documentation.
> Explain user lookup by email or handle.

- services/galley/src/Galley/API/MLS/Welcome.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Federation.hs
- services/galley/test/integration/API/MLS.hs
- services/galley/test/integration/API/MessageTimer.hs
- services/galley/test/integration/API/Roles.hs
- services/galley/test/integration/API/SQS.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
- services/galley/test/integration/API/Teams/LegalHold/DisabledByDefault.hs
- services/galley/test/integration/API/Util.hs
- services/galley/test/integration/Main.hs
- services/galley/test/integration/TestHelpers.hs
- services/galley/test/unit/Test/Galley/API.hs
- services/galley/test/unit/Test/Galley/Intra/User.hs
- services/galley/test/unit/Test/Galley/Mapping.hs
- services/gundeck/test/integration/API.hs
> Linted Galley

- changelog.d/5-internal/nginz-legalhold
- charts/nginz/values.yaml
> charts/nginz: Forward `/i/legalhold/whitelisted-teams` to galley instead of brig

- tools/bonanza/test/unit/Test/Bonanza/Arbitrary.hs
We can change this back if that gets solved, or we develop a better understanding of the issue.
> Reverted back to sequence+map to avoid GHC issue when dealing with Arbitrary instances

- changelog.d/5-internal/nginz-ifeatures-route
- charts/nginz/values.yaml
> charts/nginz: Forward /i/users/:uid/features/:feature to brig

- changelog.d/2-features/pr-2494
- charts/galley/templates/configmap.yaml
- charts/galley/values.yaml
> Add missing config mapping and sort feature flags by name

- docs/src/how-to/administrate/users.rst
> add more details on grabbing metrics

- cassandra-schema.cql
- changelog.d/2-features/pr-2522
- charts/brig/templates/configmap.yaml
- charts/brig/values.yaml
- docs/src/how-to/install/team-feature-settings.md
- hack/helm_vars/wire-server/values.yaml.gotmpl
- libs/types-common/src/Data/RetryAfter.hs
- libs/types-common/types-common.cabal
- services/brig/brig.cabal
- services/brig/brig.integration.yaml
- services/brig/schema/src/Main.hs
- services/brig/schema/src/V71_AddTableVCodesThrottle.hs
- services/brig/src/Brig/API/Error.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/API/Types.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/API/Util.hs
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Code.hs
- services/brig/src/Brig/Options.hs
- services/brig/src/Brig/Provider/API.hs
- services/brig/src/Brig/User/Auth/Cookie.hs
- services/brig/src/Brig/User/Auth/Cookie/Limit.hs
- services/brig/test/integration/API/Provider.hs
- services/brig/test/integration/API/User/Auth.hs
- services/brig/test/integration/API/User/Util.hs
- services/galley/test/integration/API/Teams/Feature.hs
- services/spar/test-integration/Test/Spar/Scim/AuthSpec.hs
- services/spar/test-integration/Util/Core.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1436
> Sqservices 1436 improve security of 2nd factor authentication

- changelog.d/2-features/charts-logging
- charts/brig/templates/configmap.yaml
- charts/brig/values.yaml
- charts/cannon/templates/configmap.yaml
- charts/cannon/values.yaml
- charts/cargohold/templates/configmap.yaml
- charts/cargohold/values.yaml
- charts/federator/templates/configmap.yaml
- charts/federator/values.yaml
- charts/galley/templates/configmap.yaml
- charts/galley/values.yaml
- charts/gundeck/templates/configmap.yaml
- charts/gundeck/values.yaml
- charts/proxy/templates/configmap.yaml
- charts/proxy/values.yaml
- charts/spar/templates/configmap.yaml
- charts/spar/values.yaml
- services/spar/test-integration/Test/LoggingSpec.hs
This format was introduced in #1951 and #1959.
> charts/*: default logFormat=StructuredJSON format

- services/galley/src/Galley/App.hs
This makes sure that any IO exception thrown within the bracket results in the finaliser being called.
> Use resourceToFinalIO to run the Resource effect

- docs/src/how-to/administrate/elasticsearch.rst
> move listing into a new section

- docs/src/how-to/install/troubleshooting.rst
> adding information on diagnosis and configuration for bad network issues

- changelog.d/3-bug-fixes/nginz-rate-limit-exemptions
- charts/nginz/templates/conf/_nginx.conf.tpl
It broke the rate limiting exemption on staging.
> Revert "do rate limiting exemptions by proxy_protocol_ip (#2581)"

- stack.yaml
- stack.yaml.lock
I know we've been meaning to kill stack.yaml, but as long as it's there, I'll use it and keep it in working order.  :-)
> Tweak stack.yaml

- libs/schema-profunctor/README.md
> Updated Schema Profuctor readme with another example

- build/ubuntu/Dockerfile.builder
- build/ubuntu/Dockerfile.deps
> print mls-test-cli Git revision when building Docker image

- changelog.d/5-internal/FS-435
- nix/pkgs/mls_test_cli/default.nix
- services/galley/src/Galley/API/MLS/Message.hs
- services/galley/test/integration/API/MLS.hs
- services/galley/test/integration/API/MLS/Util.hs
https://wearezeta.atlassian.net/browse/FS-435
> Add support for MLS External Add Proposals

- services/galley/src/Galley/API/MLS/Message.hs
> apply linter suggestions

- libs/wire-api/src/Wire/API/MLS/Commit.hs
- libs/wire-api/src/Wire/API/MLS/Epoch.hs
- libs/wire-api/src/Wire/API/MLS/Group.hs
- libs/wire-api/src/Wire/API/MLS/KeyPackage.hs
- libs/wire-api/src/Wire/API/MLS/Message.hs
- libs/wire-api/src/Wire/API/MLS/Proposal.hs
- libs/wire-api/src/Wire/API/MLS/Serialisation.hs
- libs/wire-api/test/unit/Main.hs
- libs/wire-api/test/unit/Test/Wire/API/MLS.hs
- libs/wire-api/test/unit/Test/Wire/API/Roundtrip/MLS.hs
- libs/wire-api/wire-api.cabal
- nix/pkgs/mls_test_cli/default.nix
This PR adds serialisation of signed remove proposals.
https://wearezeta.atlassian.net/browse/FS-823
> Serialisation of remove proposals

- cassandra-schema.cql
- changelog.d/0-release-notes/pr-2641
- changelog.d/2-features/pr-2641
- charts/brig/templates/configmap.yaml
- charts/brig/values.yaml
- charts/nginz/values.yaml
- deploy/services-demo/conf/brig.demo-docker.yaml
- deploy/services-demo/conf/brig.demo.yaml
- deploy/services-demo/conf/nginz/nginx.conf
- docs/src/how-to/install/team-feature-settings.md
- hack/helm_vars/wire-server/values.yaml.gotmpl
- libs/types-common/src/Data/Nonce.hs
- libs/types-common/src/Data/Text/Ascii.hs
- libs/types-common/test/Test/Properties.hs
- libs/types-common/types-common.cabal
- libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
- services/brig/brig.cabal
- services/brig/brig.integration.yaml
- services/brig/schema/src/Main.hs
- services/brig/schema/src/V72_AddNonceTable.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/App.hs
- services/brig/src/Brig/Data/Nonce.hs
- services/brig/src/Brig/Options.hs
- services/brig/test/integration/API/User/Client.hs
- services/brig/test/integration/API/User/Util.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1721
> Sqservices 1721 acme be new nonce endpoint

- changelog.d/1-api-changes/fix-mls-error-desc
- libs/wire-api/src/Wire/API/Error/Brig.hs
> Fix key package error description

- libs/polysemy-wire-zoo/polysemy-wire-zoo.cabal
> Fix cabal formatting

- .github/pull_request_template.md
> PR template formatting

- .github/pull_request_template.md
- changelog.d/5-internal/fix-pr-template
> Fix link in PR template

- docs/src/release-notes.rst
[PR guidelines](https://github.com/wireapp/wire-server/blob/develop/docs/developer/pr-guidelines.md)
> SER-191: update release notes

- changelog.d/5-internal/FS-905-async
- services/brig/src/Brig/API/Client.hs
- services/brig/src/Brig/IO/Intra.hs
- services/brig/src/Brig/InternalEvent/Process.hs
- services/brig/src/Brig/InternalEvent/Types.hs
- services/brig/test/integration/API/User/Client.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/MLS.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Teams/LegalHold.hs
- services/galley/test/integration/API/Util.hs
> Make client deletion asynchronous

- docs/src/how-to/install/team-feature-settings.md
> [Docs] Change h3 to h2 in feature setting docs

- changelog.d/5-internal/pr-2703
- libs/wire-api/src/Wire/API/Error/Brig.hs
- libs/wire-api/src/Wire/API/MLS/CommitBundle.hs
- libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
- libs/wire-api/src/Wire/API/Swagger.hs
- libs/wire-api/src/Wire/API/User/Password.hs
- services/brig/src/Brig/API/Error.hs
- services/brig/src/Brig/API/Internal.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/Provider/API.hs
- services/galley/src/Galley/API/MLS/Message.hs
- services/galley/src/Galley/API/MLS/Propagate.hs
> [SQSERVICES-1643] Servantify brig account API 5 - `POST /password-reset`

- changelog.d/1-api-changes/remove-legalhold-conversation
- changelog.d/1-api-changes/v2
- libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
- libs/wire-api/src/Wire/API/Routes/Version.hs
- libs/wire-api/src/Wire/API/VersionInfo.hs
- services/brig/brig.cabal
- services/brig/docs/swagger-v2.json
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/API/Public/Swagger.hs
- services/brig/test/integration/API/User/Auth.hs
- Remove legalhold conversation alias from v2
- Slight cleanup of swagger API definition
- Introduce API version 3
> Finalise version 2

- Makefile
- changelog.d/0-release-notes/nix-builds
- changelog.d/5-internal/nix-builds
> Avoid building haddocks while building production images

- changelog.d/0-release-notes/nix-builds
- nix/wire-server.nix
> nix: fix typo in optimized nix builds

- changelog.d/4-docs/sns-clarification
- docs/src/how-to/install/aws-prod.rst
- docs/src/how-to/install/configuration-options.rst
- docs/src/how-to/install/helm-prod.rst
- docs/src/understand/overview.rst
> Improve docs on SNS / push notifications.

- services/brig/test/integration/API/Provider.hs
- services/brig/test/integration/Util.hs
Hopefully fixes https://wearezeta.atlassian.net/browse/FS-1097
> Deflake team deletion test

- nix/wire-server.nix
> hoogleImage: Add Entrypoint and CA Certs

- .envrc.local.default
- docs/src/developer/developer/building.md
- docs/src/developer/developer/how-to.md
- services/integration.sh
Please contribute more information, other possible variables we might want here and why.
> Added a default .envrc.local with some info

- changelog.d/5-internal/galley-memory
- charts/galley/values.yaml
https://wearezeta.atlassian.net/browse/SQCORE-1373
> Higher memory limit for galley

- libs/wire-api/src/Wire/API/Routes/MultiTablePaging/State.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Util.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1769
extension to PR #2802
> use base64url in JSON isntances

- docs/src/how-to/associate/deeplink.rst
> adding note about deeplinks

- changelog.d/5-internal/pr-2850
- tools/stern/src/Stern/API/Routes.hs
> Fix stern API endpoint ejpd-info with correct HTTP method

- libs/wire-api/src/Wire/API/Routes/Public/Galley/Conversation.hs
- services/galley/src/Galley/API/Public/Conversation.hs
- services/galley/test/integration/API/MLS.hs
> Commented out GTC for release.

- changelog.d/0-release-notes/webapp-upgrade
- charts/webapp/values.yaml
This reverts commit b83a35447ff6f6fa3c884a301e2f686d4dd4173a.
> Revert "chore: [charts] Update webapp version (#2873)"

- README.md
Fix broken image URL in README
> Fix image URL in README

- docs/src/developer/developer/pr-guidelines.md
> Fix path in PR guidelines

- changelog.d/1-api-changes/mls-flag-galley
- charts/brig/templates/configmap.yaml
- docs/src/developer/reference/config-options.md
- docs/src/how-to/install/mls.md
- hack/helm_vars/wire-server/values.yaml.gotmpl
- libs/wire-api/src/Wire/API/Error/Brig.hs
- services/brig/brig.cabal
- services/brig/brig.integration.yaml
- services/brig/src/Brig/API/Error.hs
- services/brig/src/Brig/API/MLS/KeyPackages.hs
- services/brig/src/Brig/API/MLS/Util.hs
- services/brig/src/Brig/Data/Client.hs
- services/brig/src/Brig/Options.hs
https://wearezeta.atlassian.net/browse/FS-1280
> MLS flag in brig

- services/galley/src/Galley/API/MLS/Message.hs
> Use same validation error in internal & external commit validation

- changelog.d/6-federation/mls-flag-brig
- services/brig/src/Brig/API/Federation.hs
- services/brig/src/Brig/Options.hs
- services/brig/test/integration/API/Federation.hs
> Honour MLS flag in brig's federation API

- Makefile
- changelog.d/2-features/vhost-addressing-for-s3
- charts/cargohold/templates/configmap.yaml
- docs/src/how-to/install/configuration-options.rst
- libs/types-common-aws/default.nix
- libs/types-common-aws/src/AWS/Util.hs
- libs/types-common-aws/types-common-aws.cabal
- nix/haskell-pins.nix
- services/brig/brig.cabal
- services/brig/default.nix
- services/brig/src/Brig/AWS.hs
- services/brig/src/Brig/Data/Client.hs
- services/cargohold/src/CargoHold/AWS.hs
- services/cargohold/src/CargoHold/App.hs
- services/cargohold/src/CargoHold/Options.hs
- services/cargohold/src/CargoHold/S3.hs
- services/galley/src/Galley/Aws.hs
- services/gundeck/default.nix
- services/gundeck/gundeck.cabal
- services/gundeck/src/Gundeck/Aws.hs
https://github.com/brendanhay/amazonka/pull/832 should have solved our problems, so we shouldn't need the fork.
> Use amazonka from upstream head intead of fork

- charts/inbucket/values.yaml
> add default host address in values.yaml for inbucket chart

- changelog.d/3-bug-fixes/pr-2960
- services/brig/src/Brig/Code.hs
- services/brig/test/integration/API/User/Auth.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1824
[SQSERVICES-1824]: https://wearezeta.atlassian.net/browse/SQSERVICES-1824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SQSERVICES-1824] [fix] Entering 2FA code multiple times does not invalidate it

- libs/wire-api/src/Wire/API/OAuth.hs
- libs/wire-api/src/Wire/API/Routes/Public.hs
- libs/wire-api/src/Wire/API/Routes/Public/Brig/OAuth.hs
- services/brig/src/Brig/API/OAuth.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/test/integration/API/OAuth.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1826
based on #2989
> [SQSERVICES-1826] [OAUTH] Use refresh token to retrieve access token

- Makefile
> Don't remove global cabal store in 'make full-clean'.

- Makefile
- changelog.d/5-internal/makefile-kind-restart-all
> fix Makefile kind-restart-all target

- libs/wire-api/src/Wire/API/OAuth.hs
- libs/wire-api/src/Wire/API/Routes/Public/Brig/OAuth.hs
- services/brig/src/Brig/API/OAuth.hs
- services/brig/test/integration/API/OAuth.hs
> [SQSERVICES-1841/1842] [OAUTH] Get apps with account access and revoke access

- hack/helmfile.yaml
> hack/helmfile.yaml: Use hcloud-volumes for redis storage in CI

- docs/src/understand/searchability.md
Fix small errata and move a section to the end.
> Update searchability documentation

- docs/src/developer/reference/user/activation.md
- services/brig/brig.integration.yaml
- services/brig/src/Brig/API/Handler.hs
Fixes an issue with config parser introduced in #3043
> Fix brig config for local testing

- Makefile
- docs/src/developer/developer/building.md
quick & dirty internal make rule to make sure concourse won't have any avoidable issues with a PR.
> Add sanitize-pr make rule.

- changelog.d/2-features/improve-error-message
- services/brig/src/Brig/API/MLS/KeyPackages/Validation.hs
Better error message for invalid ID in credential.
> Improve error message

- changelog.d/5-internal/amazon-retry
- services/gundeck/src/Gundeck/Aws.hs
- retry with exp backoff when rate limited by Amazon
- add changelog
> retry with exp backoff when rate limited by Amazon

- services/gundeck/src/Gundeck/Push/Data.hs
> streamline module export list with module name

- changelog.d/5-internal/backoffice-ci
- hack/helm_vars/wire-server/values.yaml.gotmpl
> launch a backoffice pod in CI to catch issues with it earlier

- charts/nginz/values.yaml
- libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
- services/brig/test/integration/API/SystemSettings.hs
- services/nginz/integration-test/conf/nginz/nginx.conf
https://wearezeta.atlassian.net/browse/SQSERVICES-1911
This is a fix for https://github.com/wireapp/wire-server/pull/3082
> [SQSERVICES-1911] Team features MLS E2E ID (2/2)

- libs/wire-api/src/Wire/API/OAuth.hs
- libs/wire-api/src/Wire/API/Routes/Public.hs
- services/brig/src/Brig/API/OAuth.hs
- services/brig/test/integration/API/OAuth.hs
Small refactoring to record dot syntax and overloaded record fields for OAuth.
> record dot syntax and overloaded record fields

- charts/brig/templates/tests/brig-integration.yaml
- charts/galley/templates/tests/galley-integration.yaml
- charts/spar/templates/tests/spar-integration.yaml
> galley/brig/spar: launch pods with decent starting cpu/memory resources

- hack/bin/flaky_tests.py
- nix/wire-server.nix
> flaky_tests.py: Add -l to see logs

- flaky-tests.yaml
- services/galley/test/integration/API/Federation.hs
> fix unexpected notification received in test

- docs/src/understand/api-client-perspective/swagger.md
just adding a paragraph of markdown, i would like to avoid cluttering the changelog with this.  (or even this description :)
> Tweak docs.wire.com re. swagger

- charts/brig/values.yaml
- charts/cannon/values.yaml
- charts/cargohold/values.yaml
- charts/galley/values.yaml
- charts/gundeck/values.yaml
- charts/proxy/values.yaml
- charts/spar/values.yaml
- docs/src/developer/reference/config-options.md
related:
- https://github.com/wireapp/wire-server/pull/3075
- https://github.com/wireapp/wire-server/pull/3152
> Fix syntax for disabelling versions in docs and comments.

- changelog.d/5-internal/unversion-internal-apis
- docs/src/understand/api-client-perspective/swagger.md
- libs/wire-api/src/Wire/API/Routes/Version/Wai.hs
- services/brig/brig.cabal
- services/brig/default.nix
- services/brig/test/integration/API/Metrics.hs
- services/brig/test/integration/API/Swagger.hs
- services/brig/test/integration/Main.hs
- services/cargohold/test/integration/Metrics.hs
- services/galley/default.nix
- services/galley/galley.cabal
- services/galley/test/integration/API/Util.hs
https://wearezeta.atlassian.net/browse/SQPIT-1688
> Un-version internal apis

- charts/webapp/values.yaml
> chore: update webapp version for frida

- charts/team-settings/values.yaml
> chore: update TM version

- changelog.d/5-internal/update-kubectl-images-helm-charts
- charts/coturn/templates/statefulset.yaml
- charts/reaper/templates/deployment.yaml
- charts/restund/templates/statefulset.yaml
- charts/sftd/templates/statefulset.yaml
> upgrade kubectl images

- changelog.d/4-docs/update-of-sso-integration-using-octa
- docs/src/understand/single-sign-on/okta/main.md
> Corrected a spelling mistake in docs-sso-okta

- changelog.d/5-internal/reuse-http2
- libs/http2-manager/src/HTTP2/Client/Manager.hs
- libs/http2-manager/src/HTTP2/Client/Manager/Internal.hs
- libs/http2-manager/test/Test/HTTP2/Client/ManagerSpec.hs
- libs/wire-api-federation/src/Wire/API/Federation/Client.hs
- services/federator/default.nix
- services/federator/federator.cabal
- services/federator/src/Federator/Env.hs
- services/federator/src/Federator/Monitor.hs
- services/federator/src/Federator/Monitor/Internal.hs
- services/federator/src/Federator/Remote.hs
- services/federator/src/Federator/Response.hs
- services/federator/src/Federator/Run.hs
- services/federator/test/integration/Test/Federator/IngressSpec.hs
- services/federator/test/unit/Test/Federator/Client.hs
- services/federator/test/unit/Test/Federator/Monitor.hs
- services/federator/test/unit/Test/Federator/Remote.hs
> Use http2-manager to communicate with remotes

- changelog.d/5-internal/pr-3240
- services/galley/test/integration/TestHelpers.hs
- services/spar/test-integration/Util/Core.hs
> fix eventually

- cassandra-schema.cql
- changelog.d/2-features/pr-3237
- charts/galley/values.yaml
- docs/src/developer/reference/config-options.md
- docs/src/understand/team-feature-settings.md
- libs/wire-api/src/Wire/API/Team/Feature.hs
- libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/WithStatus_team.hs
- libs/wire-api/test/golden/testObject_WithStatus_team_18.json
- services/galley/galley.cabal
- services/galley/galley.integration.yaml
- services/galley/schema/src/Main.hs
- services/galley/schema/src/V81_TeamFeatureMlsE2EIdUpdate.hs
- services/galley/src/Galley/Cassandra/TeamFeatures.hs
- services/galley/test/integration/API/Teams/Feature.hs
https://wearezeta.atlassian.net/browse/FS-1849
> [FS-1849] Change Team Management settings for End-to-end Identity

- changelog.d/2-features/pr-3237
- changelog.d/4-docs/pr-3244
- docs/src/developer/reference/config-options.md
- docs/src/understand/team-feature-settings.md
- libs/wire-api/src/Wire/API/Team/Feature.hs
> FS-1879 Backend Docs: Change default. Add explanation of acmeDiscoveryUrl.

- changelog.d/5-internal/coturn-verbose
- charts/coturn/templates/configmap-coturn-conf-template.yaml
- charts/coturn/values.yaml
> coturn: disable verbose by default.

- Makefile
> Tweak sanitize-pr.

- docs/src/grepinclude.py
Followup, as suggested in the PR review comment of #3256
This PR also reformats the source code a little to adhere more to Python standards.
example:
```
[sphinx-autobuild] > sphinx-build -b html -q /home/user/Documents/git/wire-server/docs/src /home/user/Documents/git/wire-server/docs/build
ERROR: Unable to find substring 'fiifif'
in file ../charts/coturn/values.yaml".
GrepInclude called on line 66
in /home/user/Documents/git/wire-server/docs/src/how-to/install/tls.md
[sphinx-autobuild] Serving on http://127.0.0.1:3000
```
It also shows an error inside the documenation (so if this error isn't fixed the documentation page rendered shows an error, too). Not sure if this is a good or a bad idea, but at least it makes the problem visible even if nobody looks at the sphinx compilation logs.
> grepinclude: log and show error when no match found

- changelog.d/3-bug-fixes/pr-3267
- libs/wire-api/src/Wire/API/Routes/Public.hs
- libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
- services/brig/src/Brig/API/Client.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/test/integration/API/User.hs
- services/brig/test/integration/API/User/Client.hs
- services/brig/test/integration/Main.hs
https://wearezeta.atlassian.net/browse/FS-1927
> [FS-1927] Use Correct Domain During DPoP Access Token Request

- changelog.d/3-bug-fixes/pr-3281
- tools/stern/src/Stern/Intra.hs
- tools/stern/test/integration/API.hs
> Fix: `/i/user/meta-info` (stern)

- changelog.d/5-internal/integration-qol
- integration/integration.cabal
- integration/test/API/Brig.hs
- integration/test/API/Galley.hs
- integration/test/MLS/Util.hs
- integration/test/Test/Demo.hs
- integration/test/Testlib/App.hs
- integration/test/Testlib/Assertions.hs
- integration/test/Testlib/Cannon.hs
- integration/test/Testlib/Env.hs
- integration/test/Testlib/HTTP.hs
- integration/test/Testlib/JSON.hs
- integration/test/Testlib/ModService.hs
- integration/test/Testlib/Options.hs
- integration/test/Testlib/Prekeys.hs
- integration/test/Testlib/Prelude.hs
- integration/test/Testlib/Printing.hs
- integration/test/Testlib/Run.hs
- integration/test/Testlib/Types.hs
- Add convenience getJSON and getBody functions
- baseRequest now adds Z headers automatically
- Added liftIO versions of putStrLn etc
- Add Show instances for MLSState
> Small improvements to the new integration suite

- changelog.d/5-internal/list-tests
- integration/Setup.hs
- integration/test/Test/Demo.hs
- integration/test/Testlib/Options.hs
- integration/test/Testlib/Printing.hs
- integration/test/Testlib/Run.hs
Implement test listing. Call the integration binary with `-l` to get a list of tests and their descriptions.
> Implement test listing

- changelog.d/5-internal/pr-3321-scim-email-script
- hack/bin/change_emails.py
- hack/python/wire/api.py
> Script to bulk-change/-repair user's scim and brig email address

- changelog.d/1-api-changes/add-conv-id-to-welcome-event
- integration/test/Test/MLS.hs
- libs/wire-api-federation/src/Wire/API/Federation/API/Galley.hs
- services/galley/src/Galley/API/Federation.hs
- services/galley/src/Galley/API/MLS/Message.hs
- services/galley/src/Galley/API/MLS/Welcome.hs
- services/galley/test/integration/API/MLS.hs
- services/galley/test/integration/API/Util.hs
> [FS-1915] Add conversation id to welcome messages

- changelog.d/4-docs/cassandra-guidelines
- docs/src/developer/developer/cassandra-interaction.md
Fixes https://wearezeta.atlassian.net/browse/WPB-1232
> Write cassandra developer guidelines.

- charts/nginz/values.yaml
> Add /self/supported-protocols to nginz routes

- changelog.d/3-bug-fixes/pr-3362
- services/nginz/integration-test/conf/nginz/nginx.conf
> fix: local integration tests nginx.conf

- changelog.d/5-internal/test-swagger-ui
- docs/src/understand/api-client-perspective/swagger.md
- integration/test/API/Brig.hs
- integration/test/Test/Brig.hs
- integration/test/Testlib/Assertions.hs
- integration/test/Testlib/HTTP.hs
- integration/test/Testlib/JSON.hs
> Test swagger docs.

- integration/test/Test/MLS.hs
> [WPB-200] Added integration test for MLS client removal

- changelog.d/0-release-notes/background-worker
- charts/background-worker/templates/configmap.yaml
- charts/background-worker/templates/deployment.yaml
- charts/background-worker/values.yaml
- services/background-worker/background-worker.cabal
- services/background-worker/background-worker.integration.yaml
- services/background-worker/default.nix
- services/background-worker/src/Wire/BackendNotificationPusher.hs
- services/background-worker/src/Wire/BackgroundWorker.hs
- services/background-worker/src/Wire/BackgroundWorker/Env.hs
- services/background-worker/src/Wire/BackgroundWorker/Health.hs
- services/background-worker/src/Wire/BackgroundWorker/Options.hs
- services/background-worker/test/Test/Wire/BackendNotificationPusherSpec.hs
- services/run-services
https://wearezeta.atlassian.net/browse/WPB-2400
> background-worker: Add status endpoint 

- charts/integration/templates/configmap.yaml
- integration/test/Test/Demo.hs
- integration/test/Testlib/App.hs
- integration/test/Testlib/Env.hs
- integration/test/Testlib/ModService.hs
- integration/test/Testlib/Types.hs
- services/integration.yaml
https://wearezeta.atlassian.net/browse/WPB-2400
> integration: Use status endpoint for background-worker

- changelog.d/0-release-notes/background-worker
- charts/background-worker/templates/service.yaml
- charts/background-worker/templates/servicemonitor.yaml
- charts/background-worker/values.yaml
- services/background-worker/background-worker.cabal
- services/background-worker/default.nix
- services/background-worker/src/Wire/BackendNotificationPusher.hs
- services/background-worker/src/Wire/BackgroundWorker.hs
- services/background-worker/src/Wire/BackgroundWorker/Env.hs
- services/background-worker/test/Test/Wire/BackendNotificationPusherSpec.hs
https://wearezeta.atlassian.net/browse/WPB-2401
https://wearezeta.atlassian.net/browse/WPB-2402
https://wearezeta.atlassian.net/browse/WPB-2403
https://wearezeta.atlassian.net/browse/WPB-2404
> background-worker: Add metrics

- libs/gundeck-types/src/Gundeck/Types/Push/V2.hs
- services/gundeck/test/unit/Json.hs
https://wearezeta.atlassian.net/browse/WPB-2965
> gundeck-types: Delete obsolete 'RouteNative' and clarify haddocks

- changelog.d/5-internal/improve-websocket-tests
- integration/test/Test/Brig.hs
- integration/test/Testlib/Cannon.hs
- integration/test/Testlib/Types.hs
- Better error reporting in WS tests
- Add domain to cannon requests in integration tests
> Websocket test improvements

- nix/manual-overrides.nix
https://wearezeta.atlassian.net/browse/WPB-2911
> Enable haddocks for cql-io

- changelog.d/4-docs/swagger-docs-2023-07-10
- docs/src/understand/api-client-perspective/swagger.md
> Swagger docs for custom backends.

- integration/test/SetupHelpers.hs
- integration/test/Test/Conversation.hs
> fix: Wait for federation status to sync in new integration tests

- integration/test/Test/Brig.hs
- integration/test/Testlib/ModService.hs
- integration/test/Testlib/RunServices.hs
> fix: RunServices.hs for integration test suite

- .hlint.yaml
> Tweak hlint to not disagree with ormolu.

- changelog.d/3-bug-fixes/pr-3420
- integration/test/Test/Brig.hs
- services/brig/src/Brig/API/Federation.hs
- services/brig/src/Brig/API/Util.hs
https://wearezeta.atlassian.net/browse/WPB-3064
> [WPB-3064] Fix cross domain user search

- hack/helm_vars/rabbitmq/values.yaml.gotmpl
part of https://wearezeta.atlassian.net/browse/WPB-2783
> Disable persistence for rabbitmq in tests

- services/galley/src/Galley/API/Teams/Features.hs
- services/galley/test/integration/API/Teams/Feature.hs
> fix interdependency between feature configs

- changelog.d/5-internal/pr-3425
- charts/integration/templates/configmap.yaml
- integration/test/Testlib/Env.hs
- integration/test/Testlib/ModService.hs
- integration/test/Testlib/RunServices.hs
- integration/test/Testlib/Types.hs
- services/integration.yaml
> internal fix: Add `stern` to run-services implementation for integration tests

- docs/src/how-to/install/version-requirements.md
> Make note about poetry clearer.

- integration/test/Test/Brig.hs
- integration/test/Testlib/RunServices.hs
> fix: Local integration tests

- changelog.d/3-bug-fixes/pr-3436
- tools/stern/src/Stern/API.hs
- tools/stern/src/Stern/API/Routes.hs
> fix: ster get-meta-info

- changelog.d/4-docs/sso-faq
- docs/src/understand/single-sign-on/generic-setup.md
- docs/src/understand/single-sign-on/trouble-shooting.md
> SSO Faq entry on CSP.

- changelog.d/5-internal/federator-status
- charts/federator/templates/deployment.yaml
- libs/extended/extended.cabal
- libs/extended/src/Servant/API/Extended/Endpath.hs
- libs/wire-api/src/Wire/API/MakesFederatedCall.hs
- services/federator/default.nix
- services/federator/federator.cabal
- services/federator/src/Federator/Env.hs
- services/federator/src/Federator/ExternalServer.hs
- services/federator/src/Federator/Health.hs
- services/federator/src/Federator/InternalServer.hs
- services/federator/src/Federator/MockServer.hs
- services/federator/src/Federator/RPC.hs
- services/federator/src/Federator/Response.hs
- services/federator/src/Federator/Run.hs
- services/federator/src/Federator/Validation.hs
- services/federator/test/integration/Test/Federator/InwardSpec.hs
- services/federator/test/unit/Test/Federator/ExternalServer.hs
- services/federator/test/unit/Test/Federator/InternalServer.hs
- services/federator/test/unit/Test/Federator/Validation.hs
https://wearezeta.atlassian.net/browse/WPB-41
> federator: Add status endpoints and migrate to servant

- integration/test/Test/Conversation.hs
This fixes an integration test failure on develop
> Fix assertion in integration tests

- integration/README.md
- integration/test/Testlib/JSON.hs
> Remove incorrect instructions from integration's README.

- integration/test/Test/Conversation.hs
- integration/test/Test/Demo.hs
- integration/test/Test/Presence.hs
- integration/test/Testlib/App.hs
- integration/test/Testlib/Cannon.hs
>  Rename helper function 'unrace' in new integration tests

- docs/src/how-to/install/infrastructure-configuration.md
> add section about having more than 500 users

- hack/bin/create-user
> Add diya/elna to create-user

- hack/bin/create-user
> create-user script: Add ability to create team with members

- services/galley/src/Galley/Intra/Util.hs
Tracked by https://wearezeta.atlassian.net/browse/WPB-3649
> Don't retry intra Galley->Gundeck calls

- services/brig/test/integration/API/Search.hs
https://wearezeta.atlassian.net/browse/SQSERVICES-1894
> Additional test for user search with umlaut

- docs/src/understand/single-sign-on/trouble-shooting.md
> SSO CSP trouble shooting details.

- integration/test/Testlib/App.hs
- integration/test/Testlib/ModService.hs
- integration/test/Testlib/ResourcePool.hs
> Add more call HasCallStack constraints to functions in test suite

- changelog.d/3-bug-fixes/wpd-3888
- libs/wire-api/src/Wire/API/Routes/Internal/Brig.hs
- services/brig/src/Brig/API/Internal.hs
- services/brig/src/Brig/Data/Client.hs
- services/brig/src/Brig/Data/MLS/KeyPackage.hs
https://wearezeta.atlassian.net/browse/WPB-3888
> Fix cassandra query.

- deploy/dockerephemeral/docker-compose.yaml
> dockerephemeral: Increase nofile ulimits for ES and Fake DynamoDB

- changelog.d/5-internal/pr-3540
- libs/types-common/src/Data/Id.hs
- libs/wire-api/src/Wire/API/Conversation/Bot.hs
- libs/wire-api/src/Wire/API/Error/Brig.hs
- libs/wire-api/src/Wire/API/Provider/Bot.hs
- libs/wire-api/src/Wire/API/Routes/Public.hs
- libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
- libs/wire-api/src/Wire/API/Routes/Public/Brig/Bot.hs
- libs/wire-api/src/Wire/API/User/Client.hs
- libs/wire-api/wire-api.cabal
- services/brig/src/Brig/API.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/Provider/API.hs
- services/brig/test/integration/API/Provider.hs
https://wearezeta.atlassian.net/browse/WPB-662
> [WPB-662] servantify brig provider bot api

- README.md
> Fix broken "we are hiring" link

- libs/jwt-tools/test/Spec.hs
- nix/overlay.nix
- nix/pkgs/rusty_jwt_tools_ffi/default.nix
- nix/sources.json
- services/brig/brig.cabal
- services/brig/default.nix
- services/brig/test/integration/API/User/Client.hs
> [WPB-4361] upgrade jwt-tools

- changelog.d/3-bug-fixes/WPB-4629
- integration/test/Test/Conversation.hs
- integration/test/Test/Federation.hs
- services/galley/src/Galley/API/Action.hs
https://wearezeta.atlassian.net/browse/WPB-4629
> WPB-4629 impossible to add users to a conversation if one of the members is from an offline backend

- libs/wire-api/src/Wire/API/Routes/Public/Galley/Conversation.hs
- services/galley/test/integration/API/Util.hs
https://wearezeta.atlassian.net/browse/WPB-701
> [WPB-701] Deprecated joining unqualified conversation

- libs/wire-api/src/Wire/API/Routes/Internal/Brig.hs
- services/brig/src/Brig/API/Internal.hs
- tools/stern/src/Stern/API/Routes.hs
- tools/stern/src/Stern/Intra.hs
- tools/stern/test/integration/API.hs
https://wearezeta.atlassian.net/browse/WPB-700
> [WPB-700] Pass along server errors between Galley and Stern

- docs/src/developer/developer/building.md
This is important when running federation integration tests locally.
> Add note about localhost. resolution

- charts/webapp/values.yaml
> Webapp mandarin rc 4

- libs/wire-api/src/Wire/API/Provider.hs
- libs/wire-api/src/Wire/API/Routes/Public/Brig/Provider.hs
- libs/wire-api/src/Wire/API/User/Auth.hs
https://wearezeta.atlassian.net/browse/WPB-4931
> wire-api: Fix issues due to swagger2 -> openapi3 migration and concurrent merges

- docs/src/developer/developer/building.md
- add documentation for increasing resources
- update documentation to use the proper command
> [chore] update the developer documentation

- docs/src/understand/classified-domains.md
> Add documentation of team/backend distinction, as per WPB-4344

- deploy/dockerephemeral/docker-compose.yaml
> [chore] Pin rabbitmq docker image to 3.11.x

- changelog.d/5-internal/xml-reports
- charts/backoffice/templates/tests/secret.yaml
- charts/backoffice/templates/tests/stern-integration.yaml
- charts/backoffice/values.yaml
- charts/brig/templates/tests/brig-integration.yaml
- charts/brig/templates/tests/secret.yaml
- charts/brig/values.yaml
- charts/cargohold/templates/tests/cargohold-integration.yaml
- charts/cargohold/templates/tests/secret.yaml
- charts/cargohold/values.yaml
- charts/federator/templates/tests/federator-integration.yaml
- charts/federator/templates/tests/secret.yaml
- charts/federator/values.yaml
- charts/galley/templates/tests/galley-integration.yaml
- charts/galley/templates/tests/secret.yaml
- charts/galley/values.yaml
- charts/gundeck/templates/tests/gundeck-integration.yaml
- charts/gundeck/templates/tests/secret.yaml
- charts/gundeck/values.yaml
- charts/integration/templates/integration-integration.yaml
- charts/integration/templates/secret.yaml
- charts/integration/values.yaml
- charts/spar/templates/tests/secret.yaml
- charts/spar/templates/tests/spar-integration.yaml
- charts/spar/values.yaml
- hack/helm_vars/common.yaml.gotmpl
- hack/helm_vars/flake-finder.yaml.gotmpl
- hack/helm_vars/wire-server/values.yaml.gotmpl
- hack/helmfile.yaml
https://wearezeta.atlassian.net/browse/WPB-4267
> integration-tests: Allow uploading XML results to S3

- integration/test/Testlib/ModService.hs
https://wearezeta.atlassian.net/browse/WPB-4810
> Integration tests flake when assuming federation ingress is up.

- .envrc
- ~~Add a new entry in an appropriate subdirectory of `changelog.d`~~ no changelog
> [feat] use nom in the direnv invocation if it is available

- changelog.d/5-internal/WPB-4848
- services/brig/test/integration/API/Provider.hs
> WPB-4848 Flaky test

- cassandra-schema.cql
- changelog.d/2-features/WPB-5105
- integration/test/API/BrigInternal.hs
- integration/test/Test/Brig.hs
- integration/test/Test/Conversation.hs
- libs/wire-api/src/Wire/API/Routes/FederationDomainConfig.hs
- libs/wire-api/src/Wire/API/Routes/Internal/Brig.hs
- services/brig/brig.cabal
- services/brig/src/Brig/API/Internal.hs
- services/brig/src/Brig/Data/Federation.hs
- services/brig/src/Brig/Data/Instances.hs
- services/brig/src/Brig/Options.hs
- services/brig/src/Brig/Schema/Run.hs
- services/brig/src/Brig/Schema/V81_AddFederationRemoteTeams.hs
- services/brig/src/Brig/Schema/V81_AddTeamtoFederationRemotes.hs
- services/brig/test/integration/API/Federation.hs
- services/federator/test/unit/Test/Federator/InternalServer.hs
- services/federator/test/unit/Test/Federator/Validation.hs
https://wearezeta.atlassian.net/browse/WPB-5385
> WPB-5385 Extend internal federation config API with team ID

- docs/src/understand/api-client-perspective/authentication.md
> [docs] Update number of days the login cookie is valid for

- .envrc
- .gitignore
- not applicable ~~Add a new entry in an appropriate subdirectory of `changelog.d`~~
> [fix] fix the envrc invocation

- changelog.d/5-internal/PR-3723
- libs/wire-api/src/Wire/API/Team/Feature.hs
> [fix] stern/backoffice conference calling TTL

- nix/haskell-pins.nix
> [chore] add link to PR to HaskellNetSSL upstream

- changelog.d/3-bug-fixes/WPB-5417
- charts/cargohold/values.yaml
https://wearezeta.atlassian.net/browse/WPB-5417
> WPB-5417 limit file upload to 100MiB

- hack/bin/upload-helm-charts-s3.sh
> Add -U option to upload-helm-charts-s3.sh

- changelog.d/5-internal/nixpkgs-bump-libcurl
- integration/test/Testlib/Mock.hs
- nix/manual-overrides.nix
- nix/sources.json
- nix/wire-server.nix
https://wearezeta.atlassian.net/browse/WPB-5165
> [feat] nixpkgs bump

- changelog.d/5-internal/upgrade-sftd-versions
- charts/sftd/Chart.yaml
- charts/sftd/values.yaml
If you approve, please merge this PR immediately.
> Update SFTD and its nginx images used by default in the helm charts

- changelog.d/5-internal/WPB-6001
- services/brig/src/Brig/API/Internal.hs
- services/brig/src/Brig/Team/API.hs
> WPB-6001 suspend user logging

- changelog.d/5-internal/WPB-6099
- charts/nginz/values.yaml
https://wearezeta.atlassian.net/browse/WPB-6101
> WPB-6101 make feature enforceFileDownloadLocation unlockable for QA

- changelog.d/5-internal/restored-brig-memory-quota
- hack/helm_vars/wire-server/values.yaml.gotmpl
Reverts wireapp/wire-server#3806
> Revert "Revert brig memory setup back to 512mb"

- changelog.d/5-internal/restored-brig-memory-quota
- hack/helm_vars/wire-server/values.yaml.gotmpl
Reverts wireapp/wire-server#3819
> Revert "Revert "Revert brig memory setup back to 512mb""

- changelog.d/5-internal/WPB-6073
- nix/haskell-pins.nix
- nix/manual-overrides.nix
> Revert "[WPB-6073] cleanup haskell pins"

- integration/test/Testlib/Env.hs
- nix/pkgs/mls-test-cli/default.nix
> reactivate post-quatum cipher tests

- nix/haskell-pins.nix
Updated references to git repositories to wireapp forks
> Refactor/use GitHub forks

- nix/haskell-pins.nix
> Move repository from GitLab to GitHub

- Makefile
- services/run-services
> restore  for integration tests

- README.md
- charts/gundeck/templates/tests/configmap.yaml
- docs/src/developer/developer/how-to.md
- hack/bin/cabal-run-integration.sh
- integration/README.md
- services/spar/test-scim-suite/README.md
- services/start-services-only.sh
- tools/stern/README.md
- treefmt.toml
>  Replace services/run-services with dist/run-services 

- hack/helm_vars/wire-server/values.yaml.gotmpl
It seems to be OOMKilled sometimes.
> Give brig more RAM in integration tests

- changelog.d/3-bug-fixes/WPB-6351
- libs/wire-api/src/Wire/API/Routes/Version.hs
- libs/wire-api/test/unit/Test/Wire/API/Routes/Version.hs
- services/brig/src/Brig/CanonicalInterpreter.hs
- services/brig/src/Brig/Effects/GalleyProvider/RPC.hs
> [Q1-2024] WPB-6351 fix: diya elna return 500 on register endpoint zulu

- changelog.d/5-internal/WPB-6254-translate-LH-tests-part-1
- integration/integration.cabal
- integration/test/API/Brig.hs
- integration/test/API/BrigCommon.hs
- integration/test/API/BrigInternal.hs
- integration/test/MLS/Util.hs
- integration/test/Test/Conversation.hs
- integration/test/Test/Demo.hs
- integration/test/Test/LegalHold.hs
- integration/test/Testlib/PTest.hs
- services/brig/test/integration/API/User/Client.hs
https://wearezeta.atlassian.net/browse/WPB-6254
> Clean up LH tests

- changelog.d/2-features/WPB-6190
- libs/jwt-tools/src/Data/Jwt/Tools.hs
- libs/jwt-tools/test/Spec.hs
- nix/pkgs/rusty_jwt_tools_ffi/default.nix
- nix/sources.json
- services/brig/src/Brig/API/Client.hs
- services/brig/src/Brig/API/Error.hs
- services/brig/src/Brig/API/Types.hs
- services/brig/src/Brig/Effects/JwtTools.hs
- services/brig/test/integration/API/User/Client.hs
> WPB-6190 Backend should validate display name during DPoP challenge

- changelog.d/2-features/WPB-6190
- libs/jwt-tools/src/Data/Jwt/Tools.hs
- libs/jwt-tools/test/Spec.hs
- nix/pkgs/rusty_jwt_tools_ffi/default.nix
- nix/sources.json
- services/brig/src/Brig/API/Client.hs
- services/brig/src/Brig/API/Error.hs
- services/brig/src/Brig/API/Types.hs
- services/brig/src/Brig/Effects/JwtTools.hs
- services/brig/test/integration/API/User/Client.hs
> [Q1-2024] WPB-6190 backend should validate display name during DPoP challenge

- changelog.d/5-internal/wpb6998-improve-federator-error-logs
- libs/wire-api-federation/default.nix
- libs/wire-api-federation/src/Wire/API/Federation/Error.hs
- libs/wire-api-federation/wire-api-federation.cabal
- services/federator/src/Federator/Remote.hs
https://wearezeta.atlassian.net/browse/WPB-6998
https://github.com/wireapp/wire-server/pull/3919
> Fix federator error logs  (q1-2024)

- changelog.d/3-bug-fixes/WPB-7023
- services/galley/src/Galley/Cassandra/Conversation.hs
- services/galley/src/Galley/Cassandra/Queries.hs
https://wearezeta.atlassian.net/browse/WPB-7023
> avoid IO Exception when group state not set

- changelog.d/3-bug-fixes/WPB-6524
- charts/nginz/templates/conf/_deeplink.json.tpl
https://wearezeta.atlassian.net/browse/WPB-6524
Test like this:
cd into `charts`
create file `nginz-overrides.yaml`
```shell
echo 'nginx_conf:
deeplink:
endpoints:
backendURL: "https://prod-nginz-https.wire.com"
backendWSURL: "https://prod-nginz-ssl.wire.com"
blackListURL: "https://clientblacklist.wire.com/prod"
teamsURL: "https://teams.wire.com"
accountsURL: "https://accounts.wire.com"
websiteURL: "https://wire.com"
title: "Leif Test"
apiProxy: # (optional)
host: "socks5.proxy.com"
port: 1080
needsAuthentication: true' > nginz-overrides.yaml
```
create file `nginz-secrets.yaml`
```shell
echo 'secrets:
basicAuth: "whatever"
zAuth:
publicKeys: 0UW38se1yeoc5bVNEvf5LyrHWGZkyvcGTVilK2geGdU=
oAuth:
publicKeys: |
{
"kty": "OKP",
"crv": "Ed25519",
"x": …
```
> WPB-6524 Added optional api proxy attribute to deeplink json in nginz chart

- charts/elasticsearch-ephemeral/templates/es.yaml
- charts/elasticsearch-index/templates/create-index.yaml
- charts/elasticsearch-index/templates/migrate-data.yaml
- charts/elasticsearch-index/templates/secret.yaml
- charts/elasticsearch-index/values.yaml
- docs/src/developer/reference/config-options.md
- hack/helm_vars/wire-server/values.yaml.gotmpl
> WPB-7177 implement credential support in wires elastic search staging prod

- integration/test/Testlib/Run.hs
- nix/haskell-pins.nix
> Parallelise new integration tests

- docs/src/developer/developer/pr-guidelines.md
> add API change documentation to PR guidlines

- Makefile
- changelog.d/5-internal/WPB-7021
- libs/hscim/src/Web/Scim/Schema/User.hs
- libs/hscim/test/Test/Class/UserSpec.hs
- libs/wire-api/src/Wire/API/User/Scim.hs
- services/spar/spar.cabal
- services/spar/src/Spar/API.hs
- services/spar/src/Spar/Error.hs
- services/spar/src/Spar/Scim/Auth.hs
- services/spar/src/Spar/Sem/ScimTokenStore/Cassandra.hs
- services/spar/test-integration/Test/Spar/APISpec.hs
- services/spar/test-integration/Test/Spar/AppSpec.hs
- services/spar/test-integration/Test/Spar/DataSpec.hs
- services/spar/test-integration/Test/Spar/Scim/AuthSpec.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
- services/spar/test-integration/Util/Core.hs
- services/spar/test-integration/Util/Scim.hs
https://wearezeta.atlassian.net/browse/WPB-7021
> [WPB-7021] how to associate `IdP`s with `scim` tokens in the backend

- integration/test/Test/Login.hs
The test `testLoginVerify6DigitExpiredCodeFails` turned out to flake during a local run, which could be reproduced by running it 100x using `replicateM_` (in sequence).
Setting the verification timeout from 1 sec to 2 sec seemed to remove the flakiness.
We could just merge this or spend some more time trying to understand better what is going on exactly?
> Increase 2FA timeout to unflake test

- changelog.d/3-bug-fixes/es-tls-template-fix
- charts/brig/templates/configmap.yaml
https://wearezeta.atlassian.net/browse/WPB-6716
> charts/brig: Fix template for settings ES CA certs

- changelog.d/1-api-changes/WPB-484
- integration/integration.cabal
- integration/test/Test/MLS.hs
- integration/test/Test/MLS/Keys.hs
- libs/types-common/src/Data/Json/Util.hs
- libs/wire-api/src/Wire/API/Error/Galley.hs
- libs/wire-api/src/Wire/API/MLS/Keys.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley/MLS.hs
- services/galley/src/Galley/API/MLS.hs
- services/galley/src/Galley/API/Public/MLS.hs
> use JWK instead of bare keys as MLS removal keys

- changelog.d/4-docs/WPB-7036
- charts/wire-server/values.yaml
- docs/src/how-to/install/infrastructure-configuration.md
- docs/src/how-to/install/sft.md
- docs/src/how-to/install/troubleshooting.md
- docs/src/how-to/install/web-app-settings.md
- docs/src/understand/mls.md
> Update docs: Migrated Helm charts (#3931)

- changelog.d/3-bug-fixes/wpb9362-lh-logic-glitch
- integration/test/SetupHelpers.hs
- integration/test/Test/LegalHold.hs
- integration/test/Testlib/Assertions.hs
- services/brig/src/Brig/API/Connection.hs
- services/galley/src/Galley/API/LegalHold.hs
- services/galley/src/Galley/API/LegalHold/Conflicts.hs
- services/galley/src/Galley/API/Util.hs
https://wearezeta.atlassian.net/browse/WPB-9362
> Treat pending legalhold devices as not having a legalhold device

- integration/test/Test/LegalHold.hs
https://wearezeta.atlassian.net/browse/WPB-9362
missed a spot in https://github.com/wireapp/wire-server/pull/4056
> Increase test coverage ever so slightly.

- hack/bin/Sbom.hs
- hack/bin/bombon.hs
- n/a Add a new entry in an appropriate subdirectory of `changelog.d`
> [fix] fix sbom generation as deptrack now does validation [skip-ci]

- changelog.d/5-internal/more-metadata-in-meta
- nix/wire-server.nix
> [feat] add more metadata in nix to own code

- services/brig/test/integration/API/User/Account.hs
> Make flaky test more robust.

- changelog.d/3-bug-fixes/WPB-9488-fix-update-origin
- services/brig/src/Brig/API/Public.hs
https://wearezeta.atlassian.net/browse/WPB-9488
> Do not set update origin "scim" in public brig api.

- hack/bin/Sbom.hs
- n/a Add a new entry in an appropriate subdirectory of `changelog.d`
> [feat] include meta.homepage for the purl [skip-ci]

- changelog.d/3-bug-fixes/WPB-9488-fix-update-origin
- services/brig/src/Brig/API/Public.hs
https://wearezeta.atlassian.net/browse/WPB-9488
> Port #4072 to q1-2024

- charts/nginx-ingress-services/templates/service.yaml
- charts/nginx-ingress-services/values.yaml
> change externallyCreated to useFakeS3 and change its depth

- services/brig/src/Brig/User/Search/Index.hs
> [fix] remove redundant MonadProm constraint in brig

- changelog.d/3-bug-fixes/WBP-9677
- tools/stern/src/Stern/API.hs
- tools/stern/src/Stern/API/Routes.hs
- tools/stern/src/Stern/Intra.hs
https://wearezeta.atlassian.net/browse/WPB-9677
> WPB-9677 fix stern endpoint `/i/users/meta-info`

- services/spar/src/Spar/Scim/User.hs
inspired by https://wearezeta.atlassian.net/browse/WPB-9755
> Make error messages in scim user create more helpful.

- changelog.d/3-bug-fixes/WPB-6567
- charts/coturn/templates/statefulset.yaml
> WPB-6567 Coturn certificate reloader sidecar not working as designed

- changelog.d/2-features/coturn-params
- charts/coturn/templates/configmap-coturn-conf-template.yaml
- charts/coturn/templates/statefulset.yaml
- charts/coturn/values.yaml
> coturn: Add IP configuration options (#4083)

- changelog.d/2-features/WPB-6954
- charts/integration/templates/configmap.yaml
- integration/test/Testlib/ResourcePool.hs
- libs/extended/src/Network/AMQP/Extended.hs
- libs/wire-api/src/Wire/API/Call/Config.hs
- libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/RTCConfiguration_user.hs
- libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/SFTServer_user.hs
- libs/wire-api/test/golden/testObject_RTCConfiguration_user_7.json
- services/brig/src/Brig/Calling/API.hs
- services/brig/test/unit/Test/Brig/Calling.hs
- services/integration.yaml
> WPB-6954 Set SFT username's shared field according to team setting

- libs/wire-api/src/Wire/API/Event/Conversation.hs
- services/cannon/src/Cannon/App.hs
- services/gundeck/default.nix
> Added EventType mapping.

- changelog.d/2-features/WPB-9773
- integration/test/Test/MLS/SubConversation.hs
- services/galley/src/Galley/API/MLS/SubConversation.hs
https://wearezeta.atlassian.net/browse/WPB-9773
> allow subconversations for MLS 1-1 conversation

- changelog.d/3-bug-fixes/ciphersuite-update
- integration/test/Test/MLS/One2One.hs
- services/galley/src/Galley/API/MLS/Commit/ExternalCommit.hs
- services/galley/src/Galley/API/MLS/Commit/InternalCommit.hs
- services/galley/src/Galley/API/MLS/Message.hs
https://wearezeta.atlassian.net/browse/WPB-9061
> move ciphersuite updates into the commit lock

- integration/test/API/Brig.hs
- integration/test/Test/MLS/KeyPackage.hs
> WPB-10207 follow up: clean up test code

- cassandra-schema.cql
In #4155, a schema change was not added to Git. This PR fixes it.
Tracked by https://wearezeta.atlassian.net/browse/WPB-10204.
> [WPB-10204] Add a forgotten schema change for #4155

- integration/test/Test/Property.hs
Remove debug statement in integrationt tests.
> Remove debug statement

- changelog.d/3-bug-fixes/wpb8713-get-feature-configs-end-point-performance
- libs/wire-api/test/unit/Test/Wire/API/Run.hs
- libs/wire-api/test/unit/Test/Wire/API/Team/Feature.hs
- libs/wire-api/wire-api.cabal
- services/galley/default.nix
- services/galley/galley.cabal
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Teams/Features.hs
- services/galley/src/Galley/API/Teams/Features/Get.hs
- services/galley/src/Galley/App.hs
- services/galley/src/Galley/Cassandra/GetAllTeamFeatureConfigs.hs
- services/galley/src/Galley/Cassandra/TeamFeatures.hs
- services/galley/src/Galley/Effects.hs
- services/galley/src/Galley/Effects/TeamFeatureStore.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Teams/Feature.hs
- services/galley/test/integration/API/Util/TeamFeature.hs
https://wearezeta.atlassian.net/browse/WPB-10235
> Backport #4002

- changelog.d/1-api-changes/finalise-v6
- integration/test/Test/Version.hs
- libs/wire-api/src/Wire/API/Routes/Version.hs
Finalise API v6
https://wearezeta.atlassian.net/browse/WPB-10263
> backport to q1: Finalise API v6

- changelog.d/2-features/WPB-1334
- integration/integration.cabal
- integration/test/API/Brig.hs
- integration/test/API/BrigInternal.hs
- integration/test/Test/OAuth.hs
- integration/test/Testlib/HTTP.hs
- libs/wire-api/src/Wire/API/OAuth.hs
- services/brig/src/Brig/API/OAuth.hs
- services/brig/test/integration/API/OAuth.hs
https://wearezeta.atlassian.net/browse/WPB-1334
> WPB-1334 extend list of OAuth apps with active refresh token ids

- services/brig/docs/swagger-v6.json
This fix is necessarry after f624ffab7ae65b73e96587d9c6a86dcf1a702385.
https://wearezeta.atlassian.net/browse/WPB-10263
> correct swagger for APIv6

- changelog.d/5-internal/wpb-9844
- charts/wire-server/templates/NOTES.txt
https://wearezeta.atlassian.net/browse/WPB-9844
> add warning when team/user creation is enabled over internet

- changelog.d/2-features/WPB-1333
- integration/test/API/Brig.hs
- integration/test/Test/OAuth.hs
- libs/wire-api/src/Wire/API/Password.hs
- libs/wire-api/src/Wire/API/Routes/Public/Brig/OAuth.hs
- services/brig/src/Brig/API/OAuth.hs
- services/brig/test/integration/API/OAuth.hs
https://wearezeta.atlassian.net/browse/WPB-1333
https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/1309868033/API+changes+v6+v7
> WPB-1333 OAuth endpoint to revoke single refresh tokens

- changelog.d/5-internal/WPB-10302
- charts/brig/templates/configmap.yaml
- charts/brig/templates/secret.yaml
- charts/brig/values.yaml
https://wearezeta.atlassian.net/browse/WPB-10302
> Read sftToken from secrets.yaml

- docs/src/developer/reference/config-options.md
> [docs] config for dpop access token signing key

- docs/src/developer/reference/config-options.md
> [fix docs] truncated key to prevent unintentional usage

- Makefile
> Add rabbitmq gc to `make full-clean`.

- changelog.d/1-api-changes/finalise-v6
- services/brig/docs/swagger-v6.json
https://wearezeta.atlassian.net/browse/WPB-10737
> Update generated swagger.json for client API v6

- changelog.d/5-internal/background-worker
- libs/extended/src/Network/AMQP/Extended.hs
Use the name defined by our convention to get better error messages.
> Fix FromJSON AmqpEndpoint error message

- changelog.d/3-bug-fixes/services-tags
- libs/wire-api/src/Wire/API/Routes/Public/Brig/Services.hs
https://wearezeta.atlassian.net/browse/WPB-11162
> brig: Make `GET /services/tags` work again

- Makefile
- hack/bin/helm-template.sh
- hack/bin/integration-setup-federation.sh
- hack/lib/dirs.sh
- hack/lib/helm-overrides.sh
- hack/lib/helmfile-env-vars.sh
- hack/lib/kube-metadata.sh
- nix/wire-server.nix
>  Makefile: Add target to template helmfile 

- changelog.d/2-features/WPB-11183
- libs/wire-subsystems/src/Wire/EmailSubsystem/Template.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/Team/Email.hs
- services/brig/src/Brig/Team/Template.hs
https://wearezeta.atlassian.net/browse/WPB-11183
> WPB-11183 confirmation email after team creation and account migration of the team owner

- changelog.d/3-bug-fixes/WPB-15085
- libs/wire-subsystems/src/Wire/EmailSubsystem/Template.hs
- services/brig/src/Brig/API/User.hs
- services/brig/src/Brig/Team/Email.hs
- services/brig/src/Brig/Team/Template.hs
https://wearezeta.atlassian.net/browse/WPB-15085
> Add profile name to new team owner welcome mail

- integration/test/Testlib/Env.hs
- integration/test/Testlib/ModService.hs
- integration/test/Testlib/Run.hs
- integration/test/Testlib/RunServices.hs
- integration/test/Testlib/Types.hs
> integration: Print name of the test in logs from dynamic backends

- integration/test/Testlib/ModService.hs
- nix/wire-server.nix
https://wearezeta.atlassian.net/browse/WPB-15156
> WPB-15156 Ensure federator port is free

- changelog.d/5-internal/federator-signal-handling
- integration/test/Test/User.hs
- integration/test/Testlib/ModService.hs
- services/federator/src/Federator/ExternalServer.hs
- services/federator/src/Federator/InternalServer.hs
- services/federator/src/Federator/Interpreter.hs
- services/federator/src/Federator/Run.hs
>  federator: Close sockets on SIGINT/SIGTERM

- integration/test/Test/Events.hs
https://wearezeta.atlassian.net/browse/WPB-15208
Merely waiting doesn't seem to work, sometimes there are 4 connections called "pool 0" in RabbitMQ, possible because those cannons were SIGKILLed.
> integration/testChannelKilled: Kill previous connections to RabbitMQ

- changelog.d/1-api-changes/WPB-15030
- libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley/Conversation.hs
- libs/wire-api/src/Wire/API/Routes/Public/Spar.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Util.hs
> WPB-15030 Delete deprecated and unqualified endpoints from V8

- integration/test/Test/Events.hs
> integration: deflake testTransientEventsDoNotTriggerDeadLetters

- changelog.d/5-internal/WPB-14307
- integration/integration.cabal
- integration/test/API/SparInternal.hs
- integration/test/Test/Spar.hs
- libs/wire-api/src/Wire/API/Routes/Internal/Spar.hs
- services/spar/src/Spar/API.hs
> WPB-14307 internal spar endpoint to get the team's identity providers

- cassandra-schema.cql
- changelog.d/2-features/WPB-15551
- charts/galley/templates/configmap.yaml
- charts/galley/values.yaml
- docs/src/developer/reference/config-options.md
- hack/helm_vars/wire-server/values.yaml.gotmpl
- integration/integration.cabal
- integration/test/Test/FeatureFlags/DomainRegistration.hs
- integration/test/Test/FeatureFlags/Util.hs
- libs/galley-types/src/Galley/Types/Teams.hs
- libs/wire-api/src/Wire/API/Routes/Internal/Galley.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley/Feature.hs
- libs/wire-api/src/Wire/API/Team/Feature.hs
- services/galley/galley.cabal
- services/galley/galley.integration.yaml
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Public/Feature.hs
- services/galley/src/Galley/API/Teams/Features.hs
- services/galley/src/Galley/API/Teams/Features/Get.hs
- services/galley/src/Galley/Cassandra/MakeFeature.hs
- services/galley/src/Galley/Schema/Run.hs
- services/galley/src/Galley/Schema/V94_DomainRegistrationConfig.hs
- tools/stern/src/Stern/API.hs
- tools/stern/src/Stern/API/Routes.hs
- tools/stern/test/integration/API.hs
https://wearezeta.atlassian.net/browse/WPB-15551
This is a standalone PR that just adds the team feature. Integrating this into the domain registration flow will be a follow up.
> WPB-15551 Domain Registration Team Feature

- .gitmodules
> Make wire-server-enterprise point to main history

- changelog.d/1-api-changes/WPB-14307
- integration/test/Test/DomainVerification.hs
- libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem/Interpreter.hs
https://wearezeta.atlassian.net/browse/WPB-15551
REBASE BEFORE MERGING
> WPB-15551 Domain Registration Team Feature Integration

- changelog.d/5-internal/single-consumer-test
- integration/test/Test/Events.hs
https://wearezeta.atlassian.net/browse/WPB-14517
> Test single consumer behaviour of notifications

- changelog.d/2-features/domain-registration-blocks
- integration/integration.cabal
- integration/test/API/Brig.hs
- integration/test/API/Common.hs
- integration/test/SetupHelpers.hs
- integration/test/Test/DomainVerification.hs
- integration/test/Test/Register.hs
- integration/test/Test/Spar/STM.hs
- integration/test/Test/Teams.hs
- integration/test/Test/User.hs
- libs/wire-api/src/Wire/API/User/IdentityProvider.hs
- libs/wire-subsystems/default.nix
- libs/wire-subsystems/src/Wire/InvitationStore.hs
- libs/wire-subsystems/src/Wire/TeamInvitationSubsystem.hs
- libs/wire-subsystems/src/Wire/UserSubsystem.hs
- libs/wire-subsystems/src/Wire/UserSubsystem/Interpreter.hs
- libs/wire-subsystems/test/unit/Wire/EnterpriseLoginSubsystem/InterpreterSpec.hs
- libs/wire-subsystems/test/unit/Wire/MiniBackend.hs
- libs/wire-subsystems/test/unit/Wire/MockInterpreters/GalleyAPIAccess.hs
- libs/wire-subsystems/test/unit/Wire/MockInterpreters/IndexedUserStore.hs
- libs/wire-subsystems/test/unit/Wire/MockInterpreters/SparAPIAccess.hs
- libs/wire-subsystems/test/unit/Wire/MockInterpreters/UserSubsystem.hs
- libs/wire-subsystems/test/unit/Wire/UserSubsystem/InterpreterSpec.hs
- libs/wire-subsystems/wire-subsystems.cabal
- services/brig/src/Brig/API/Auth.hs
- services/brig/src/Brig/API/Internal.hs
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/API/User.hs
- services/spar/test/Arbitrary.hs
https://wearezeta.atlassian.net/browse/WPB-14310
> WPB-14310 Implement checks for domain registration

- changelog.d/5-internal/upgrade-redis
- charts/cannon/values.yaml
- charts/gundeck/values.yaml
- charts/redis-ephemeral/requirements.yaml
- charts/redis-ephemeral/templates/helpers.tpl
- charts/redis-ephemeral/values.yaml
- hack/helm_vars/certs/values.yaml.gotmpl
- hack/helm_vars/wire-server/values.yaml.gotmpl
- hack/helmfile.yaml
Context https://wearezeta.atlassian.net/browse/WPB-15658
> Upgrade to later redis chart with an image containing fewer CVEs

- CODEOWNERS
> create CODEOWNERS file

- CODEOWNERS
> Add backend team to all subdirs in CODEOWNERS

- changelog.d/5-internal/update-fake-aws-sqs-elasticmq-native
- charts/fake-aws-sqs/values.yaml
Ticket: https://wearezeta.atlassian.net/browse/WPB-15521
> feat(fake-aws-sqs): softwaremill/elasticmq-native image version bump to 1.6.11

- changelog.d/3-bug-fixes/WPB-15480
- tools/sftd_disco/Dockerfile
- tools/sftd_disco/Makefile
related to WPB-15480
- [👀] Read and follow the [PR guidelines](https://docs.wire.com/developer/developer/pr-guidelines.html)
> WPB-15480: fix(sftd_disco): update base image to fix CVEs

- tools/sftd_disco/sftd_disco.sh
Related to ticket:
https://wearezeta.atlassian.net/browse/WPB-15480
> fix: sftd_disco.sh script is fixed after testing

- tools/sftd_disco/Makefile
- tools/sftd_disco/sftd_disco.sh
Related to https://wearezeta.atlassian.net/browse/WPB-15480
- **fix: sftd_disco.sh script is fixed after testing**
- **fix: fixed version in Dockerfile**
> fix/vferdinandov/WPB 15480 Fixing script sftd

- changelog.d/3-bug-fixes/asset-uploads-500
- integration/test/Test/Cargohold/API/V3.hs
- integration/test/Testlib/HTTP.hs
- libs/wire-api/src/Wire/API/Error/Cargohold.hs
- libs/wire-api/src/Wire/API/Routes/Public/Cargohold.hs
- services/cargohold/src/CargoHold/API/Error.hs
- services/cargohold/src/CargoHold/AWS.hs
https://wearezeta.atlassian.net/browse/WPB-2766
> Cargohold: make AWS incomplete body a user errror

- tools/db/migrate-features/src/Main.hs
- tools/db/migrate-features/src/Options.hs
- tools/db/migrate-features/src/Work.hs
- tools/make-image
Only migrate teams that haven't been migrated yet.
https://wearezeta.atlassian.net/browse/WPB-16238
> Fix migration tool

- changelog.d/3-bug-fixes/WPB-16258
- integration/test/Test/User.hs
- libs/wire-api/src/Wire/API/Error/Brig.hs
- libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
- libs/wire-subsystems/src/Wire/UserSubsystem/Error.hs
- libs/wire-subsystems/src/Wire/UserSubsystem/Interpreter.hs
- libs/wire-subsystems/test/unit/Wire/MiniBackend.hs
- libs/wire-subsystems/test/unit/Wire/UserSubsystem/InterpreterSpec.hs
https://wearezeta.atlassian.net/browse/WPB-16258
> WPB-16258 Prevent removal of MLS support

- changelog.d/2-features/WPB-16153
- integration/integration.cabal
- integration/test/Test/FeatureFlags.hs
- integration/test/Test/FeatureFlags/Channels.hs
- integration/test/Test/FeatureFlags/Util.hs
- libs/galley-types/src/Galley/Types/Teams.hs
- libs/wire-api/src/Wire/API/Routes/Internal/Galley.hs
- libs/wire-api/src/Wire/API/Routes/Public/Galley/Feature.hs
- libs/wire-api/src/Wire/API/Team/Feature.hs
- services/galley/src/Galley/API/Internal.hs
- services/galley/src/Galley/API/Public/Feature.hs
- services/galley/src/Galley/API/Teams/Features.hs
- services/galley/src/Galley/API/Teams/Features/Get.hs
- tools/stern/src/Stern/API.hs
- tools/stern/src/Stern/API/Routes.hs
- tools/stern/test/integration/API.hs
Ticket: https://wearezeta.atlassian.net/browse/WPB-16153
Wait for the team feature config changes to be released before merging, to avoid any potential problems due to old-to-new feature config transition.
> WPB-16153 allow configuring channels for a team

- changelog.d/3-bug-fixes/WPB-16437
- integration/test/SetupHelpers.hs
- integration/test/Test/DomainVerification.hs
- libs/wire-api/src/Wire/API/Routes/Public/Brig/DomainVerification.hs
- libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem/Interpreter.hs
https://wearezeta.atlassian.net/browse/WPB-16437
> WPB-16437 Handle existing user when domain is registered for SSO

- changelog.d/3-bug-fixes/WPB-16544
- integration/test/Test/DomainVerification.hs
- libs/wire-api/src/Wire/API/Routes/Public/Brig/DomainVerification.hs
- libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem/Interpreter.hs
https://wearezeta.atlassian.net/browse/WPB-16544
> WPB-16544 Allow setting domain_redirect for team registered domains

- changelog.d/3-bug-fixes/WPB-16640
- charts/nginz/values.yaml
- integration/test/API/Brig.hs
- integration/test/API/BrigInternal.hs
- integration/test/SetupHelpers.hs
- integration/test/Test/DomainVerification.hs
- integration/test/Test/Register.hs
- integration/test/Test/Teams.hs
- integration/test/Test/User.hs
- libs/wire-api/src/Wire/API/Routes/Public/Brig/DomainVerification.hs
- libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem.hs
- libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem/Interpreter.hs
- services/brig/src/Brig/API/Public.hs
- services/nginz/integration-test/conf/nginz/nginx.conf
https://wearezeta.atlassian.net/browse/WPB-16640
https://wearezeta.atlassian.net/browse/WPB-16641
> WPB-16640 be create a team authenticated endpoint for domain registration

- changelog.d/0-release-notes/ldap-scim-bridge-update-image
- charts/ldap-scim-bridge/values.yaml
There are BOM files for the new image.
Ticket: https://wearezeta.atlassian.net/browse/WPB-15475
> Update ldap-scim-bridge image 0.4 -> 0.10.4

- changelog.d/5-internal/fed-denied-log-level
- services/brig/brig.integration.yaml
- services/federator/src/Federator/Discovery.hs
- services/federator/src/Federator/Error.hs
- services/federator/src/Federator/Error/ServerError.hs
- services/federator/src/Federator/Interpreter.hs
- services/federator/src/Federator/MockServer.hs
- services/federator/src/Federator/Remote.hs
- services/federator/src/Federator/Validation.hs
https://wearezeta.atlassian.net/browse/WPB-15425
> Use warn level when logging federation denied errors

- changelog.d/5-internal/cassandra-improve-script
- hack/bin/cassandra_dump_schema
- Avoid dealing with empty strings
- PEP 8
- Shorten keyspace enumeration code
> Improve cassandra dump script

- changelog.d/2-features/WPB-16388
- integration/test/API/Galley.hs
- integration/test/Test/Channels.hs
- libs/wire-api/src/Wire/API/Conversation.hs
- libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/NewConv_user.hs
- libs/wire-api/test/golden/testObject_NewConv_user_3.json
- libs/wire-api/test/golden/testObject_NewConv_v2_user_3.json
- services/brig/test/integration/API/OAuth.hs
- services/brig/test/integration/API/Provider.hs
- services/brig/test/integration/API/Team/Util.hs
- services/brig/test/integration/Util.hs
- services/galley/src/Galley/API/Create.hs
- services/galley/test/integration/API.hs
- services/galley/test/integration/API/Util.hs
https://wearezeta.atlassian.net/browse/WPB-16917
> WPB-16917 Set Add-Permissions on Channel Creation

- changelog.d/1-api-changes/WPB-16457
- services/brig/docs/swagger-v8.json
> WPB-16457 Fix finalized API v8

- integration/test/Test/ExternalPartner.hs
> test that external partner cannot add member even if they are wire_admin

- Makefile
- deploy/dockerephemeral/run.sh
- docs/src/developer/developer/building.md
> Small unrelated tweaks to Makefile && shell script.

- changelog.d/3-bug-fixes/cannon-nginz-events
- charts/cannon/values.yaml
> charts/cannon: Add the events endpoint to nginz config

- changelog.d/3-bug-fixes/cannon-nginz-events
- charts/nginz/values.yaml
> charts/nginz: Add the events endpoint to nginz config

- services/gundeck/src/Gundeck/Notification.hs
- services/gundeck/src/Gundeck/Push.hs
This will reduce noise log in brig.
> gundeck: Use rpc method from Bilge so request ID is included in internal requests

- changelog.d/3-bug-fixes/WPB-16953
- libs/wire-api/src/Wire/API/Event/Conversation.hs
- libs/wire-api/test/unit/Test/Wire/API/Conversation.hs
- services/galley/src/Galley/API/Cells.hs
https://wearezeta.atlassian.net/browse/WPB-16953
> WPB-16953 fix: conversation delete event is cells notification

- docs/src/developer/reference/config-options.md
> remove duplicated docs section about password hashing rate limiting

- changelog.d/3-bug-fixes/WPB-17378
- integration/test/Test/Events.hs
- libs/wire-api/src/Wire/API/Push/V2.hs
- services/gundeck/default.nix
- services/gundeck/gundeck.cabal
- services/gundeck/src/Gundeck/Push.hs
- services/gundeck/test/unit/MockGundeck.hs
- services/gundeck/test/unit/Push.hs
https://wearezeta.atlassian.net/browse/WPB-17378
> WPB-17378 gundeck: Fix logic to split pushes between cassandra and rabbitmq

- .github/pull_request_template.md
https://docs.wire.com/developer/developer/pr-guidelines.html => https://docs.wire.com/latest/developer/developer/pr-guidelines.html
> fix broken link.

- integration/test/Test/Spar/STM.hs
when a SCIM user is provisioned and SCIM is associated with a SAML IdP
even if validateSAMLEmails is enabled
> test: No invitation for SCIM + SSO

- docs/src/developer/developer/coding-conventions.md
- integration/test/Test/MLS/One2One.hs
- libs/ssl-util/src/Ssl/Util.hs
- libs/wire-api/src/Wire/API/Team/Feature.hs
- libs/wire-api/src/Wire/API/User/Client.hs
- libs/wire-subsystems/src/Wire/UserStore/Unique.hs
- services/brig/src/Brig/IO/Journal.hs
- services/cargohold/src/CargoHold/Federation.hs
- services/cargohold/src/CargoHold/S3.hs
- services/galley/src/Galley/Intra/Journal.hs
Fix the format of the source note. This e.g. helps to apply tools... (and my pedantry :wink: )
And, document that we're using this kind of comments.
> Fix source note format

- libs/wire-api/src/Wire/API/EnterpriseLogin.hs
Actually, this contains only a small left-over refactoring.
Ticket: https://wearezeta.atlassian.net/browse/WPB-17032
> Add a webapp url field to email domain registration (3)

- changelog.d/5-internal/WPB-17585-hotpatch-more-error-info
- libs/hscim/hscim.cabal
- libs/saml2-web-sso/src/SAML2/WebSSO/API.hs
- libs/saml2-web-sso/src/SAML2/WebSSO/XML.hs
- libs/saml2-web-sso/src/Text/XML/Util.hs
- libs/schema-profunctor/schema-profunctor.cabal
- tools/stern/stern.cabal
https://wearezeta.atlassian.net/browse/WPB-17585
> More SAML login error details.

- changelog.d/2-features/rabbitmq-admin-host
- charts/background-worker/templates/configmap.yaml
- charts/gundeck/values.yaml
- charts/integration/templates/configmap.yaml
- docs/src/developer/reference/config-options.md
- libs/extended/src/Network/AMQP/Extended.hs
- services/background-worker/background-worker.integration.yaml
- services/integration.yaml
https://wearezeta.atlassian.net/browse/WPB-17710
> Add adminHost setting for rabbitmq admin interface

- changelog.d/5-internal/WPB-17597
- changelog.d/5-internal/WPB-17597-2
- integration/test/Test/FeatureFlags/ConferenceCalling.hs
- integration/test/Test/FeatureFlags/Util.hs
- services/galley/src/Galley/API/Teams/Features.hs
- services/galley/src/Galley/Cassandra/TeamFeatures.hs
- services/galley/src/Galley/Effects/TeamFeatureStore.hs
- tools/stern/src/Stern/API.hs
- tools/stern/src/Stern/API/Routes.hs
- tools/stern/src/Stern/Intra.hs
- tools/stern/test/integration/API.hs
https://wearezeta.atlassian.net/browse/WPB-17597
> WPB-17597 stern backoffice endpoint to generically lock or unlock any team feature

- services/spar/src/Spar/Scim/User.hs
- services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
> Make a spar error message more helpful.

- README.md
> README.md: Change link to new jobs page

- changelog.d/5-internal/WPB-9531
- charts/redis-ephemeral/requirements.yaml
- charts/redis-ephemeral/values.yaml
- deploy/dockerephemeral/docker-compose.yaml
- nix/haskell-pins.nix
> WPB-9531 gundeck: support Redis >= 7.0

- charts/cannon/conf/static/zauth.acl
> Add `/events` to cannon ACL

- changelog.d/2-features/WPB-16870-user-groups-everything-except-search
- libs/wire-subsystems/postgres-migrations/20250423115049-create-user-group-member-table.sql
> Fix postgres migration

- changelog.d/2-features/WPB-16889
- libs/wire-api/src/Wire/API/UserEvent.hs
- libs/wire-subsystems/src/Wire/UserGroupSubsystem/Interpreter.hs
- libs/wire-subsystems/test/unit/Wire/UserGroupSubsystem/InterpreterSpec.hs
> WPB-16889 user group join event gets sent on user group creation update

- changelog.d/2-features/WPB-17696
- integration/test/API/Gundeck.hs
- integration/test/Test/Notifications.hs
- libs/wire-api/src/Wire/API/Notification.hs
- libs/wire-api/src/Wire/API/Routes/Public/Gundeck.hs
- services/gundeck/src/Gundeck/API/Public.hs
- services/gundeck/src/Gundeck/Monad.hs
- services/gundeck/src/Gundeck/Notification.hs
https://wearezeta.atlassian.net/browse/WPB-17696
> WPB-17696 Endpoint to get the current server time

- changelog.d/5-internal/WPB-17737
- integration/test/Test/Cells.hs
- libs/wire-api/src/Wire/API/Event/FeatureConfig.hs
- libs/wire-api/src/Wire/API/Team/Feature.hs
- libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/Event_featureConfig.hs
- libs/wire-api/test/golden/Test/Wire/API/Golden/Manual/FeatureConfigEvent.hs
- libs/wire-api/test/golden/testObject_Event_featureConfig_1.json
- libs/wire-api/test/golden/testObject_Event_featureConfig_10.json
- libs/wire-api/test/golden/testObject_Event_featureConfig_2.json
- libs/wire-api/test/golden/testObject_Event_featureConfig_3.json
- libs/wire-api/test/golden/testObject_Event_featureConfig_4.json
- libs/wire-api/test/golden/testObject_Event_featureConfig_5.json
- libs/wire-api/test/golden/testObject_Event_featureConfig_6.json
- libs/wire-api/test/golden/testObject_Event_featureConfig_7.json
- libs/wire-api/test/golden/testObject_Event_featureConfig_8.json
- libs/wire-api/test/golden/testObject_Event_featureConfig_9.json
- libs/wire-api/test/golden/testObject_FeatureConfigEvent_1.json
- libs/wire-api/test/golden/testObject_FeatureConfigEvent_2.json
- libs/wire-api/test/golden/testObject_FeatureConfigEvent_3.json
- services/galley/src/Galley/API/Teams/Features.hs
https://wearezeta.atlassian.net/browse/WPB-17737
> WPB-17737 send an event to rabbit mq cells bus when the cells feature flag is enabled on a team

- changelog.d/5-internal/WPB-18206-scim-update-email
- docs/src/developer/reference/config-options.md
- integration/test/SetupHelpers.hs
- integration/test/Test/DomainVerification.hs
- integration/test/Test/Spar.hs
- libs/wire-api/src/Wire/API/Routes/Internal/Brig.hs
- libs/wire-api/src/Wire/API/User.hs
- libs/wire-api/test/unit/Test/Wire/API/Roundtrip/ByteString.hs
- libs/wire-api/test/unit/Test/Wire/API/Roundtrip/HttpApiData.hs
- libs/wire-subsystems/src/Wire/TeamInvitationSubsystem/Interpreter.hs
- libs/wire-subsystems/wire-subsystems.cabal
- services/brig/src/Brig/API/Internal.hs
- services/brig/test/integration/API/TeamUserSearch.hs
- services/brig/test/integration/API/User/Account.hs
- services/brig/test/integration/API/User/Util.hs
- services/spar/src/Spar/Intra/Brig.hs
- services/spar/src/Spar/Scim/User.hs
i think it's best to read this commit-by-commit.
> [WPB-18206] More tests for SCIM email update (validated vs. not, vs. auto)

- changelog.d/3-bug-fixes/consumable-notif-push-notifications
- libs/wire-api/src/Wire/API/User/Client.hs
- services/brig/src/Brig/API/Client.hs
- services/gundeck/default.nix
- services/gundeck/gundeck.cabal
- services/gundeck/src/Gundeck/Push.hs
- services/gundeck/test/unit/MockGundeck.hs
- services/gundeck/test/unit/Push.hs
https://wearezeta.atlassian.net/browse/WPB-18369
> gundeck: Send push notifications to clients with `consumable-notifications` capability

- changelog.d/2-features/WPB-18179
- integration/test/MLS/Util.hs
- integration/test/Test/Channels.hs
- integration/test/Test/MLS.hs
- integration/test/Test/MLS/One2One.hs
- integration/test/Test/MLS/SubConversation.hs
- integration/test/Testlib/Types.hs
- services/galley/src/Galley/API/Action.hs
- services/galley/src/Galley/API/MLS/Propagate.hs
- services/galley/src/Galley/API/Update.hs
https://wearezeta.atlassian.net/browse/WPB-18179
> WPB-18179 Allow team admin to remove members from channel

- charts/nginz/values.yaml
> charts/nginz: Remove unused default value

- changelog.d/2-features/add-team-collaborator-endpoints
- charts/nginz/values.yaml
- integration/integration.cabal
- integration/test/API/Brig.hs
- integration/test/Notifications.hs
- integration/test/Test/TeamCollaborators.hs
- libs/wire-api/src/Wire/API/Error/Brig.hs
- libs/wire-api/src/Wire/API/Event/Team.hs
- libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
- libs/wire-api/src/Wire/API/Team/Collaborator.hs
- libs/wire-api/src/Wire/API/Team/Member.hs
- libs/wire-api/wire-api.cabal
- libs/wire-subsystems/default.nix
- libs/wire-subsystems/postgres-migrations/20250709174300-create-collaborators-table.sql
- libs/wire-subsystems/src/Wire/TeamCollaboratorsStore.hs
- libs/wire-subsystems/src/Wire/TeamCollaboratorsStore/Postgres.hs
- libs/wire-subsystems/src/Wire/TeamCollaboratorsSubsystem.hs
- libs/wire-subsystems/src/Wire/TeamCollaboratorsSubsystem/Interpreter.hs
- libs/wire-subsystems/test/unit/Wire/MiniBackend.hs
- libs/wire-subsystems/test/unit/Wire/MockInterpreters.hs
- libs/wire-subsystems/test/unit/Wire/MockInterpreters/GalleyAPIAccess.hs
- libs/wire-subsystems/test/unit/Wire/MockInterpreters/TeamCollaboratorsStore.hs
- libs/wire-subsystems/test/unit/Wire/TeamCollaboratorsSubsystem/InterpreterSpec.hs
- libs/wire-subsystems/test/unit/Wire/UserSubsystem/InterpreterSpec.hs
- libs/wire-subsystems/wire-subsystems.cabal
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/CanonicalInterpreter.hs
- services/brig/src/Brig/Team/API.hs
- services/nginz/integration-test/conf/nginz/nginx.conf
Ticket: https://wearezeta.atlassian.net/browse/WPB-18189
> Add collaborators table and creation / get all endpoints

- Makefile
- cassandra-schema.cql
- changelog.d/5-internal/tweak-makefile-devtest
- docs/src/developer/developer/pr-guidelines.md
- hack/bin/cassandra_dump_schema
- libs/types-common/types-common.cabal
https://wearezeta.atlassian.net/browse/WPB-18858
> [WPB-18858] fix devtest-package workflow

- changelog.d/0-release-notes/quorum-queues
- libs/wire-api/src/Wire/API/Notification.hs
- services/background-worker/src/Wire/DeadUserNotificationWatcher.hs
- services/cannon/src/Cannon/RabbitMq.hs
- services/gundeck/src/Gundeck/Run.hs
https://wearezeta.atlassian.net/browse/WPB-18920
Queues changed:
1. user notification queues
2. dead user notification queue
3. cells queue
> Use quorum queues for everything

- integration/test/Testlib/ModService.hs
- libs/tasty-cannon/src/Test/Tasty/Cannon.hs
- services/galley/test/integration/API/Federation.hs
- services/galley/test/integration/API/MLS.hs
- services/galley/test/integration/API/MLS/Util.hs
- services/galley/test/integration/API/Teams.hs
- services/galley/test/integration/API/Util.hs
- services/galley/test/integration/TestHelpers.hs
> WPB-19123 fix flaky tests

- changelog.d/5-internal/WPB-19422
- libs/extended/src/Network/AMQP/Extended.hs
https://wearezeta.atlassian.net/browse/WPB-19422
> WPB-19422 Improve logging on RabbitMQ connection

- changelog.d/2-features/WPB-19234
- integration/test/API/Brig.hs
- integration/test/Notifications.hs
- integration/test/Test/UserGroup.hs
- libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
- libs/wire-api/src/Wire/API/UserGroup.hs
- libs/wire-subsystems/src/Wire/UserGroupSubsystem.hs
- libs/wire-subsystems/src/Wire/UserGroupSubsystem/Interpreter.hs
- services/brig/src/Brig/API/Public.hs
https://wearezeta.atlassian.net/browse/WPB-19234
> WPB-19234: Allow team admins to bulk add users to user groups

- changelog.d/5-internal/WPB-19085
- libs/wire-subsystems/src/Wire/ConversationStore.hs
- libs/wire-subsystems/src/Wire/ConversationStore/Cassandra.hs
- libs/wire-subsystems/src/Wire/ConversationStore/Cassandra/Queries.hs
- services/galley/src/Galley/API/Teams.hs
- services/galley/src/Galley/Cassandra/Queries.hs
- services/galley/src/Galley/Cassandra/Team.hs
- services/galley/src/Galley/Effects/TeamStore.hs
> WPB-19085 move team conv operations

- libs/wire-api/src/Wire/API/Team/Member.hs
- services/galley/src/Galley/API/Update.hs
- services/galley/test/integration/API/Teams.hs
https://wearezeta.atlassian.net/browse/WPB-18197
> WPD-18197: Add join conversation permission

- changelog.d/2-features/WPB-19933
- charts/nginz/values.yaml
> WPB-19933 Add nginz config for new user group endpoints

- changelog.d/2-features/WPB-19590
- charts/backoffice/templates/poddisruptionbudget.yaml
Ticket: https://wearezeta.atlassian.net/browse/WPB-19590
This PR will add PDB to backoffice if replicaCount of pods is more than 1
> feat: add pdb to backoffice

- changelog.d/2-features/apps-table
- integration/integration.cabal
- integration/test/API/Brig.hs
- integration/test/Test/Apps.hs
- libs/wire-api/src/Wire/API/App.hs
- libs/wire-api/src/Wire/API/Event/Team.hs
- libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
- libs/wire-api/src/Wire/API/Team/Member.hs
- libs/wire-api/src/Wire/API/User/Auth.hs
- libs/wire-api/wire-api.cabal
- libs/wire-subsystems/postgres-migrations/20250721-create-apps-table.sql
- libs/wire-subsystems/src/Wire/AppStore.hs
- libs/wire-subsystems/src/Wire/AppStore/Postgres.hs
- libs/wire-subsystems/src/Wire/AppSubsystem.hs
- libs/wire-subsystems/src/Wire/AppSubsystem/Interpreter.hs
- libs/wire-subsystems/src/Wire/Postgres.hs
- libs/wire-subsystems/src/Wire/PostgresMarshall.hs
- libs/wire-subsystems/src/Wire/TeamCollaboratorsSubsystem/Interpreter.hs
- libs/wire-subsystems/src/Wire/TeamSubsystem/Util.hs
- libs/wire-subsystems/wire-subsystems.cabal
- services/brig/src/Brig/API/Public.hs
- services/brig/src/Brig/CanonicalInterpreter.hs
https://wearezeta.atlassian.net/browse/WPB-18186
> Create apps table

- charts/nginz/values.yaml
- services/nginz/integration-test/conf/nginz/nginx.conf
https://wearezeta.atlassian.net/browse/WPB-18186
> Add apps routes to nginx config

- Makefile
- changelog.d/5-internal/postgres-schema
- docs/src/developer/developer/pr-guidelines.md
- hack/bin/postgres_dump_schema
- postgres-schema.sql
cloned from the corresp. cassandra script.
> Make rule and python script for creating `/postgres-schema.sql`.

- integration/test/Test/MLS.hs
- libs/wire-subsystems/src/Wire/ConversationStore/Cassandra.hs
https://wearezeta.atlassian.net/browse/WPB-20229
> WPB-20229: use shadow conversation membership first

- changelog.d/3-bug-fixes/WPB-20532
- libs/schema-profunctor/src/Data/Schema.hs
- libs/schema-profunctor/test/unit/Test/Data/Schema.hs
- services/brig/docs/swagger-v0.json
- services/brig/docs/swagger-v1.json
- services/brig/docs/swagger-v10.json
- services/brig/docs/swagger-v11.json
- services/brig/docs/swagger-v2.json
- services/brig/docs/swagger-v3.json
- services/brig/docs/swagger-v4.json
- services/brig/docs/swagger-v5.json
- services/brig/docs/swagger-v6.json
- services/brig/docs/swagger-v7.json
- services/brig/docs/swagger-v8.json
- services/brig/docs/swagger-v9.json
> add type to Pict data type in Swagger

- hack/helmfile.yaml.gotmpl
> redis-ephemeral: use public.ecr.aws/bitnami repository in tests
